Repository gatsbyjs/gatsby, pull requests merged in 2018-08, with the labels that each got.

#6988 Fix broken title in v2 migration guide
  docs/docs/migrating-from-v1-to-v2.md
Labels: 🏷 type: bug

#7121 Added three new sections to the docs
  www/src/data/sidebars/doc-links.yaml
Labels: 🏷 type: documentation

#7200 Stub Articles and new names
  docs/docs/custom-components.md
  docs/docs/sourcing-content-and-data.md
  docs/docs/sourcing-from-contentful.md
  docs/docs/sourcing-from-databases.md
  docs/docs/sourcing-from-drupal.md
  docs/docs/sourcing-from-netlify-cms.md
  docs/docs/sourcing-from-private-apis.md
  docs/docs/sourcing-from-prose.md
  docs/docs/sourcing-from-saas-services.md
  docs/docs/sourcing-from-the-filesystem.md
  docs/docs/sourcing-from-wordpress.md
  docs/docs/testing.md
  www/gatsby-node.js
Labels: 🏷 type: documentation

#7249 [docs] Add video lesson to the StaticQuery docs
  docs/docs/static-query.md
  www/src/utils/typography.js
Labels: 🏷 type: documentation

#7292 feat: headless CMS overview
  docs/docs/content-and-data.md
  docs/docs/headless-cms.md
  www/src/data/sidebars/doc-links.yaml
  www/src/templates/template-docs-markdown.js
Labels: 🏷 type: documentation

#7315 fix: update docs to remove `gatsby-link` reference
  examples/simple-auth/package.json
  examples/using-redirects/src/pages/index.js
  packages/gatsby-plugin-catch-links/README.md
Labels: 🏷 type: documentation

#7330 feat: add an images and files overview
  docs/docs/images-and-files.md
  www/src/data/sidebars/doc-links.yaml
Labels: 🏷 type: documentation

#7280 Adds snapshot test + onError event for gatsby-image
  packages/gatsby-image/package.json
  packages/gatsby-image/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-image/src/__tests__/index.js
  packages/gatsby-image/src/index.js
Labels: enhancement

#7353 Fix invisible "Load More" button and small typo fix (double quotes) (See #7321)
  www/src/views/shared/styles.js
Labels: design

#7262 WIP: add repl command to gatsby-cli
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby/src/commands/repl.js
Labels: 🏷 type: feature

#7640 Add StaticQuery reference note
  docs/docs/static-query.md
Labels: 🏷 type: documentation

#7700 Remove outdated section from CONTRIBUTING_ES.md
  docs/docs/images/open-remote-dev-tools.png
  docs/docs/images/remote-dev-settings.png
  docs/docs/images/running-redux-devtools.png
  translations/es/CONTRIBUTING_ES.md
Labels: type: maintenance

#7699 Update creating-global-styles.md
  docs/docs/creating-global-styles.md
Labels: type: documentation
