Repository gatsbyjs/gatsby, pull requests merged in 2018-04, with the labels that each got.

#4786 Add OutboundLink component to gatsby-plugin-google-analytics + track links on gatsbyjs.org
  .eslintrc
  docs/docs/seo.md
  packages/gatsby-plugin-google-analytics/.gitignore
  packages/gatsby-plugin-google-analytics/index.js
  packages/gatsby-plugin-google-analytics/src/index.js
  www/src/components/discord.js
  www/src/components/navigation.js
  www/src/pages/index.js
  www/src/templates/template-blog-post.js
  www/src/templates/template-contributor-page.js
Labels: review

#4788 Add banner for Gatsby workshops
  packages/gatsby-plugin-google-analytics/src/index.js
  www/src/layouts/index.js
Labels: review

#4781 Add Photon to starters
  docs/docs/gatsby-starters.md
Labels: review

#4801 Don't query for unnecessary fields in gatsby-node.js createPages so people don't think these are needed
  docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md
Labels: review

#4791 readme: Add Rohit's HBTU MUN site
  README.md
Labels: review

#4758 Added blog post
  docs/blog/2018-03-29-migration-from-wordpress-to-gatsby/chrome-audit-performance-metrics.jpg
  docs/blog/2018-03-29-migration-from-wordpress-to-gatsby/chrome-audit-score-before.jpg
  docs/blog/2018-03-29-migration-from-wordpress-to-gatsby/index.md
  docs/blog/2018-03-29-migration-from-wordpress-to-gatsby/jam.jpg
  docs/blog/2018-03-29-migration-from-wordpress-to-gatsby/jamstack.png
  docs/blog/2018-03-29-migration-from-wordpress-to-gatsby/results.png
  docs/blog/2018-03-29-migration-from-wordpress-to-gatsby/static-gen.png
  docs/blog/author.yaml
  docs/blog/avatars/vojtech-ruzicka.jpg
  www/gatsby-config.js
  www/package.json
  www/src/layouts/index.js
  www/src/templates/template-blog-post.js
Labels: review

#4755 Flag to disable uglify for production builds
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby/src/commands/build.js
  packages/gatsby/src/utils/babel-config.js
  packages/gatsby/src/utils/webpack.config.js
Labels: review

#4808 Fix banner styles
  www/src/components/navigation.js
  www/src/layouts/index.js
  www/src/pages/blog/index.js
  www/src/pages/plugins.js
Labels: review

#4805 [v2] adjust createLocation calls after #4714
  packages/gatsby-link/src/index.js
Labels: review

#4810 Banner positioning fix for www
  www/src/layouts/index.js
Labels: review

#4785 [json-loader] Don't emit new file node until previous is finished processing
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/create-file-node.js
  packages/gatsby-source-filesystem/src/gatsby-node.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/bootstrap/page-hot-reloader.js
  packages/gatsby/src/internal-plugins/query-runner/query-queue.js
  packages/gatsby/src/utils/api-runner-node.js
  yarn.lock
Labels: review

#4757 Docgen improvements
  packages/gatsby-transformer-react-docgen/src/Doclets.js
  packages/gatsby-transformer-react-docgen/src/__tests__/Doclets.js
  packages/gatsby-transformer-react-docgen/src/__tests__/fixtures/classes.js
  packages/gatsby-transformer-react-docgen/src/__tests__/fixtures/flow.js
  packages/gatsby-transformer-react-docgen/src/__tests__/on-node-create.js
  packages/gatsby-transformer-react-docgen/src/extend-node-type.js
Labels: review

#4823 Don't handle line highlights unless there's actually line highlights fixes #4802
  packages/gatsby-remark-embed-snippet/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/src/highlight-code.js
Labels: review

#4826 [json-loader] Only log file events if we're past bootstrap
  packages/gatsby-source-filesystem/src/gatsby-node.js
Labels: review

#4782 Tags to posts
  docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md
  docs/blog/2017-09-13-why-is-gatsby-so-fast/index.md
  docs/blog/2017-09-18-gatsby-modern-static-generation/index.md
  docs/blog/2017-09-21-community-roundup-1/index.md
  docs/blog/2017-09-26-embracing-graphql/index.md
  docs/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/index.md
  docs/blog/2017-10-03-smartive-goes-gatsby/index.md
  docs/blog/2017-10-05-portfolio-site-gatsby-wordpress/index.md
  docs/blog/2017-10-16-making-website-building-fun/index.md
  docs/blog/2017-10-17-building-i18n-with-gatsby/index.md
  docs/blog/2017-10-20-from-wordpress-to-developing-in-react-starting-to-see-it/index.md
  docs/blog/2017-10-29-my-search-for-the-perfect-universal-javaScript-framework/index.md
  docs/blog/2017-11-06-migrate-hugo-gatsby/index.md
  docs/blog/2017-11-08-migrate-from-jekyll-to-gatsby/index.md
  docs/blog/2017-11-09-why-i-created-my-blog-with-gatsby-and-contentful/index.md
  docs/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/index.md
  docs/blog/2017-12-07-taking-gatsby-for-a-spin/index.md
  docs/blog/2017-12-20-introducing-the-gatsby-ux-research-program/index.md
  docs/blog/2018-01-18-how-boston-gov-used-gatsby-to-be-selected-as-an-amazon-hq2-candidate-city/index.md
  docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md
  docs/blog/2018-02-09-announcing-gatsby-manor-themes-for-gatsbyjs/index.md
  docs/blog/2018-02-16-bright-future-for-the-web/index.md
  docs/blog/2018-02-28-documentation-project/index.md
  docs/blog/2018-03-07-why-we-created-the-plugin-library/index.md
  docs/blog/2018-1-18-strapi-and-gatsby/index.md
  docs/blog/2018-1-24-creative-software-destruction-new-presentation-layer/index.md
  docs/blog/2018-1-25-building-a-site-with-react-and-contentful/index.md
  docs/blog/2018-2-16-how-to-build-a-website-with-react/index.md
  docs/blog/2018-2-27-why-i-upgraded-my-website-to-gatsbyjs-from-jekyll/index.md
  docs/blog/2018-2-3-sites-with-headless-cms/index.md
  docs/blog/2018-2-6-choosing-a-back-end/index.md
  docs/blog/2018-2-7-jam-out-your-blog/index.md
  docs/blog/2018-3-03-case-study-mike-johnston/index.md
  www/gatsby-node.js
  www/src/components/tags-section.js
  www/src/pages/blog/tags.js
  www/src/templates/tags.js
  www/src/templates/template-blog-post.js
Labels: review

#4822 links to plugin authoring page added and fixed
  docs/docs/plugins.md
  www/src/pages/packages.js~HEAD
  www/src/pages/plugins.js
Labels: Documentation, review

#4795 Add new example doc: GraphQL Reference/Query Variables
  docs/docs/graphql-reference.md
Labels: review

#4615 improve error message for graphql queries
  packages/gatsby/src/internal-plugins/query-runner/query-runner.js
Labels: review

#3304 Styleguide example
  examples/styleguide/.eslintrc
  examples/styleguide/.gitignore
  examples/styleguide/README.md
  examples/styleguide/gatsby-config.js
  examples/styleguide/gatsby-node.js
  examples/styleguide/package.json
  examples/styleguide/src/components/Button/Button.js
  examples/styleguide/src/components/Button/README.md
  examples/styleguide/src/components/Button/index.js
  examples/styleguide/src/pages/index.js
  examples/styleguide/src/templates/ComponentPage/ComponentPage.js
  examples/styleguide/src/templates/ComponentPage/components/ComponentPreview/ComponentPreview.js
  examples/styleguide/src/templates/ComponentPage/components/ComponentPreview/index.js
  examples/styleguide/src/templates/ComponentPage/components/ComponentPreview/prism-theme.css
  examples/styleguide/src/templates/ComponentPage/components/Example/Example.js
  examples/styleguide/src/templates/ComponentPage/components/Example/index.js
  examples/styleguide/src/templates/ComponentPage/index.js
  examples/styleguide/src/templates/TOC/TOC.js
  examples/styleguide/src/templates/TOC/index.js
Labels: review

#4829 Update README.md
  packages/gatsby-remark-autolink-headers/README.md
Labels: review

#4817 [gatsby-source-wordpress] Handle all media types
  packages/gatsby-source-wordpress/README.md
  packages/gatsby-source-wordpress/src/__tests__/request-in-queue.js
  packages/gatsby-source-wordpress/src/fetch.js
  packages/gatsby-source-wordpress/src/normalize.js
  packages/gatsby-source-wordpress/src/request-in-queue.js
Labels: review

#4852 Completed instructions to use gatsby-transformer-excel
  packages/gatsby-transformer-excel/README.md
Labels: review

#4840 [www] add missing import
  www/src/pages/plugins.js
Labels: review

#4382 Updating gatsby-plugin-manifest
  packages/gatsby-plugin-manifest/README.md
  packages/gatsby-plugin-manifest/package.json
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-ssr.js
Labels: review

#4837 [json-loader] dont recompile on data change - part 2
  packages/gatsby/src/internal-plugins/query-runner/redirects-writer.js
  packages/gatsby/src/redux/reducers/redirects.js
Labels: review

#4855 Update Gatsbygram data from instagram
  examples/gatsbygram/data/images/T4ygWXs98-.jpg
  examples/gatsbygram/data/images/ToYJj0M92U.jpg
  examples/gatsbygram/data/posts.json
Labels: review

#4850 [json-loader] develop - reading results from file improvments
  packages/gatsby/cache-dir/json-store.js
  packages/gatsby/src/internal-plugins/query-runner/query-runner.js
  packages/gatsby/src/utils/websocket-manager.js
Labels: review

#4555 [v2] improve how we load GraphQL query results in development/production (aka Ludicrous Mode)
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/create-file-node.js
  packages/gatsby-source-filesystem/src/gatsby-node.js
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/component-renderer.js
  packages/gatsby/cache-dir/json-store.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/root.js
  packages/gatsby/cache-dir/socketIo.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/bootstrap/page-hot-reloader.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/internal-plugins/query-runner/gatsby-node.js
  packages/gatsby/src/internal-plugins/query-runner/page-query-runner.js
  packages/gatsby/src/internal-plugins/query-runner/pages-writer.js
  packages/gatsby/src/internal-plugins/query-runner/query-queue.js
  packages/gatsby/src/internal-plugins/query-runner/query-runner.js
  packages/gatsby/src/internal-plugins/query-runner/redirects-writer.js
  packages/gatsby/src/redux/actions.js
  packages/gatsby/src/redux/index.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/json-data-paths.js
  packages/gatsby/src/redux/reducers/layouts.js
  packages/gatsby/src/redux/reducers/pages.js
  packages/gatsby/src/redux/reducers/redirects.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/websocket-manager.js
  yarn.lock
Labels: review

#4872 [gatsby-source-wordpress] dont request remote file if we already have cached up to date version of it
  packages/gatsby-source-wordpress/src/gatsby-node.js
  packages/gatsby-source-wordpress/src/normalize.js
Labels: review

#4876 Add blog post introducing RFC process
  CONTRIBUTING.md
  docs/blog/2018-04-06-introducing-gatsby-rfc-process/index.md
  docs/docs/community.md
  www/src/templates/template-blog-post.js
Labels: review

#4877 [gatsby-source-filesystem/createRemoteFileNode] wait for file stream to finish, not just for response
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
Labels: review

#4879 [Docs][Minor] Link Gatsbygram Case Study in README
  examples/gatsbygram/README.md
Labels: Documentation, review

#4886 Handle banner in sidebar styles fixes #4878
  www/package.json
  www/src/layouts/index.js
Labels: review

#4869 Add dependency instruction
  packages/gatsby-transformer-javascript-frontmatter/README.md
Labels: review

#4737 Explained what cd means for starter installation
  docs/tutorial/part-four/index.md
  docs/tutorial/part-one/index.md
  docs/tutorial/part-three/index.md
  docs/tutorial/part-two/index.md
Labels: Documentation, review

#4831 Don't add an extra trailing newline part deux
  packages/gatsby-remark-embed-snippet/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/highlight-code.js.snap
  packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js
  packages/gatsby-remark-prismjs/src/highlight-code.js
Labels: review

#4891 [v2] Clean up active path when a user disconnects
  packages/gatsby/src/utils/websocket-manager.js
Labels: review

#4889 adjust indices used for extracting GraphQLParser errors
  packages/gatsby/src/internal-plugins/query-runner/graphql-errors.js
Labels: review

#4927 Add Airtable tutorial to awesome Gatsby file
  docs/docs/awesome-gatsby.md
Labels: review

#4924 update CONTRIBUTING.md with DCO section
  CONTRIBUTING.md
Labels: review

#4923 feat: add simple auth example
  examples/simple-auth/README.md
  examples/simple-auth/gatsby-config.js
  examples/simple-auth/gatsby-node.js
  examples/simple-auth/package.json
  examples/simple-auth/src/components/Details.js
  examples/simple-auth/src/components/Form/form.module.css
  examples/simple-auth/src/components/Form/index.js
  examples/simple-auth/src/components/Header/header.module.css
  examples/simple-auth/src/components/Header/index.js
  examples/simple-auth/src/components/Home.js
  examples/simple-auth/src/components/Login.js
  examples/simple-auth/src/components/PrivateRoute.js
  examples/simple-auth/src/components/Status/index.js
  examples/simple-auth/src/components/Status/status.module.css
  examples/simple-auth/src/components/View/index.js
  examples/simple-auth/src/components/View/view.module.css
  examples/simple-auth/src/layouts/global.css
  examples/simple-auth/src/layouts/index.js
  examples/simple-auth/src/layouts/main.module.css
  examples/simple-auth/src/pages/404.js
  examples/simple-auth/src/pages/app.js
  examples/simple-auth/src/pages/index.js
  examples/simple-auth/src/utils/auth.js
  yarn.lock
Labels: review

#4936 Fix typo
  docs/blog/2018-04-10-how-to-handle-comments-in-gatsby-blogs/index.md
Labels: review

#5154 Hyperlinks, optionality, and "easy"
  docs/docs/gatsby-style-guide.md
Labels: 🏷 type: documentation

#5167 [v2] [gatsby-source-contentful] fix normalize id issues
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby/src/utils/eslint-config.js
Labels: 🏷 type: bug
