Repository gatsbyjs/gatsby, pull requests merged in 2018-10, with the labels that each got.

#8626 Linking between pages doc
  docs/docs/linking-between-pages.md
Labels: type: documentation

#8773 Fixed link to `withPrefix` function in adding-images-fonts-files.md
  docs/docs/adding-images-fonts-files.md
Labels: type: documentation

#8807 Update how-to-contribute.md
  docs/docs/how-to-contribute.md
Labels: type: documentation

#8995 [www] Drop Space Mono in favor of monospace system stack
  www/package.json
  www/src/components/layout.js
  www/src/utils/typography.js
Labels: type: design

#8966 Typo/fix small typo issues
  www/.eslintignore
  www/.eslintrc.json
  www/src/components/email-capture-form.js
  www/src/components/package-readme.js
  www/src/components/showcase-details.js
  www/src/components/sidebar/accordion.js
  www/src/components/sidebar/scroll-sync-sidebar.js
  www/src/components/sidebar/sticky-responsive-sidebar.js
  www/src/pages/docs/actions.js
  www/src/pages/docs/node-apis.js
  www/src/pages/features.js
  www/src/pages/index.js
  www/src/pages/newsletter.js
  www/src/utils/form-styles.js
Labels: type: feature or enhancement

#9277 docs: remove a reference to the v2 tag
  docs/docs/centralizing-your-sites-navigation.md
Labels: type: documentation

#8861 Add "sourcing from Contentful" section.
  docs/docs/sourcing-from-contentful.md
Labels: type: documentation

#9402 docs(gatsby-image): use shortcut for multi package npm installs
  packages/gatsby-image/README.md
Labels: type: documentation

#9494 Make text a little less wordy, as people generally don't read long text on-screen
  docs/docs/visual-testing-with-storybook.md
Labels: type: documentation

#9562 Update index.md
  docs/tutorial/part-two/index.md
Labels: invalid

#9510 Minor typo corrections for gatsby-style-guide.md
  docs/docs/gatsby-style-guide.md
Labels: status: awaiting author response
