Repository gatsbyjs/gatsby, pull requests merged in 2018-09, with the labels that each got.

#7968 Fix page rendering issue [breaking]
  www/src/views/community/index.js
Labels: type: bug :beetle:

#7995 [www] A couple of main navigation improvements (following up on #7933 (active nav state))
  www/src/components/banner.js
  www/src/components/navigation.js
  www/src/components/page-with-plugin-searchbar.js
  www/src/components/search-form.js
  www/src/components/sidebar/sidebar.js
  www/src/components/sidebar/sticky-responsive-sidebar.js
  www/src/pages/plugins.js
  www/src/utils/colors.js
  www/src/utils/presets.js
  www/src/views/shared/styles.js
  www/src/views/showcase/filtered-showcase.js
  www/src/views/showcase/filters.js
  www/src/views/showcase/index.js
  www/src/views/starter-showcase/filtered-showcase.js
Labels: type: design

#7510 behind the scenes docs
  docs/docs/behind-the-scenes-terminology.md
  docs/docs/behind-the-scenes.md
  docs/docs/build-caching.md
  docs/docs/data-storage-redux.md
  docs/docs/how-plugins-apis-are-run.md
  docs/docs/internal-data-bridge.md
  docs/docs/node-creation.md
  docs/docs/node-tracking.md
  docs/docs/page-creation.md
  docs/docs/page-node-dependencies.md
  docs/docs/query-behind-the-scenes.md
  docs/docs/query-execution.md
  docs/docs/query-extraction.md
  docs/docs/recipes.md
  docs/docs/schema-connections.md
  docs/docs/schema-generation.md
  docs/docs/schema-gql-type.md
  docs/docs/schema-input-gql.md
  docs/docs/schema-sift.md
  docs/docs/static-vs-normal-queries.md
  packages/gatsby-remark-graphviz/README.md
  www/gatsby-config.js
  www/package.json
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#8004 [www] Realign „Plugins“ sidebar
  www/src/components/page-with-plugin-searchbar.js
  www/src/components/plugin-searchbar-body.js
  www/src/utils/styles.js
Labels: type: design

#8036 chore: Upgrade lodash to current version.
  examples/client-only-paths/package.json
  examples/gatsbygram/package.json
  examples/hn/package.json
  examples/no-plugins/package.json
  examples/no-trailing-slashes/package.json
  examples/using-asciidoc/package.json
  examples/using-contentful/package.json
  examples/using-drupal/package.json
  examples/using-emotion-prismjs/package.json
  examples/using-glamor/package.json
  examples/using-prefetching-preloading-modules/package.json
  examples/using-remark/package.json
  examples/using-styled-components/package.json
  examples/using-wordpress/package.json
  packages/gatsby-cli/package.json
  packages/gatsby-dev-cli/package.json
  packages/gatsby-plugin-netlify/package.json
  packages/gatsby-plugin-page-creator/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-remark-copy-linked-files/package.json
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-remark-images/package.json
  packages/gatsby-remark-responsive-iframe/package.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-hacker-news/package.json
  packages/gatsby-source-lever/package.json
  packages/gatsby-source-mongodb/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-transformer-documentationjs/README.md
  packages/gatsby-transformer-react-docgen/package.json
  packages/gatsby-transformer-remark/package.json
  packages/gatsby-transformer-xml/package.json
  packages/gatsby-transformer-yaml/package.json
  packages/gatsby/package.json
  scripts/site-up-checker/package.json
  www/package.json
  www/src/data/StarterShowcase/generatedGithubData/gatsby-advanced-starter.json
  www/src/data/StarterShowcase/generatedGithubData/gatsby-starter-forty.json
  www/src/data/StarterShowcase/generatedGithubData/gatsby-typescript-starter.json
Labels: type: maintenance

#8055 Url Query and Filters are being updated correctly on navigation (Creators Showcase)
  www/src/views/community/index.js
Labels: type: bug :beetle:

#7851 Update typography-js.md
  docs/docs/typography-js.md
Labels: status: WIP

#8201 [v2] [cache-dir] fix: rendering pages with missing data
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/public-page-renderer-prod.js
Labels: 🚨 Importance: Critical

#8230 Lighthouse doc
  docs/docs/add-a-manifest-file.md
  docs/docs/add-offline-support.md
  docs/docs/add-page-metadata.md
  docs/docs/audit-with-lighthouse.md
  docs/docs/lighthouse-audit.md
Labels: type: documentation

#8276 Docs: Fix links
  docs/docs/behind-the-scenes-terminology.md
  docs/docs/node-tracking.md
  docs/docs/page-node-dependencies.md
  docs/docs/production-app.md
  docs/docs/write-pages.md
Labels: type: documentation

#8121 Responsive Design/Mobile Layout for Creators Showcase
  www/src/templates/template-creator-details.js
  www/src/views/community/community-header.js
  www/src/views/community/index.js
Labels: type: feature or enhancement

#8282 Draft of v2 release notes to match v1 release notes
  docs/docs/v2-release-notes.md
Labels: type: documentation

#8284 Updated doc with details from other source
  docs/docs/gatsby-cli.md
Labels: type: documentation

#8329 Deleted docs per conversation last week
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#8281 deleted docs we decided we don't need anymore
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#8131 Create using-gatsby-image.md
  docs/docs/using-gatsby-image.md
Labels: type: documentation

#8359 fix scroll behaviour + [wip] cypress tests for scroll behaviour
  integration-tests/production-runtime/cypress/integration/production.js
  integration-tests/production-runtime/package.json
  integration-tests/production-runtime/src/components/header.js
  integration-tests/production-runtime/src/pages/index.js
  integration-tests/production-runtime/src/pages/long-page.js
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/cache-dir/page-renderer.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/root.js
Labels: status: WIP

#8383 Routing section
  docs/docs/reach-router-and-gatsby.md
  docs/docs/routing.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#8449 [www] Add active state to mobile navigation
  www/src/assets/blog.svg
  www/src/assets/docs.svg
  www/src/assets/mobile-nav-icons.js
  www/src/assets/plugins.svg
  www/src/assets/showcase-magic.svg
  www/src/assets/showcase.svg
  www/src/assets/svg-defs.js
  www/src/assets/tutorial.svg
  www/src/components/navigation-mobile.js
  www/src/utils/colors.js
  www/src/utils/styles.js
  www/src/views/showcase/featured-sites.js
Labels: type: design

#8382 first-draft-css-modules-page
  docs/docs/css-modules.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#8509 Update doc-links.yaml
  docs/docs/gatsby-project-structure.md
  docs/docs/recipes.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#8537 Rfc process doc
  docs/docs/rfc-process.md
Labels: type: documentation

#8411 [www] Site/Starter Showcase refactor, rinse II
  www/src/views/shared/reset-filters.js
  www/src/views/shared/sidebar.js
  www/src/views/shared/styles.js
  www/src/views/showcase/filtered-showcase.js
  www/src/views/showcase/filters.js
  www/src/views/showcase/showcase-list.js
  www/src/views/starter-showcase/filtered-showcase.js
Labels: type: design

#8528 Added redirect
  www/gatsby-node.js
Labels: type: documentation

#8599 Draft graphiql doc
  docs/docs/images/graphiql-docs.png
  docs/docs/introducing-graphiql.md
Labels: type: documentation

#8617 [www] Don't `redirectInBrowser` our redirects
  www/gatsby-node.js
Labels: type: maintenance
