Repository gatsbyjs/gatsby, pull requests merged in 2018-11, with the labels that each got.

#8956 docs(www): Add "Sourcing from Prismic"
  docs/docs/images/prismic-categories-query.jpg
  docs/docs/images/prismic-index-query.jpg
  docs/docs/sourcing-from-prismic.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#9652 remove asterisk from 'Sourcing from the filesystem'
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#9651 Update hyperlink to the gatsby-link package
  docs/docs/path-prefix.md
Labels: type: documentation

#9605 feat(examples): add a remote-images plugin so as to not introduce bloat
  examples/using-gatsby-image/content/images/alexander-andrews-260988-unsplash-edited.jpg
  examples/using-gatsby-image/content/unsplash-images.yaml
  examples/using-gatsby-image/gatsby-config.js
  examples/using-gatsby-image/package.json
  examples/using-gatsby-image/plugins/gatsby-source-remote-images/README.md
  examples/using-gatsby-image/plugins/gatsby-source-remote-images/gatsby-node.js
  examples/using-gatsby-image/plugins/gatsby-source-remote-images/index.js
  examples/using-gatsby-image/plugins/gatsby-source-remote-images/package.json
  examples/using-gatsby-image/src/components/image-gallery.js
  examples/using-gatsby-image/src/images/charles-deluvio-542217-unsplash.jpg
  examples/using-gatsby-image/src/images/charles-deluvio-716555-unsplash.jpg
  examples/using-gatsby-image/src/images/charles-deluvio-716558-unsplash.jpg
  examples/using-gatsby-image/src/images/charles-deluvio-782457-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/charles-deluvio-695732-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/charles-deluvio-695760-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/chris-lee-654655-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/chuttersnap-1103171-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/igor-son-320878-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/martin-reisch-113179-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/martin-reisch-185835-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/martin-reisch-199362-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/martin-reisch-272883-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/michele-feola-166138-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/ryan-christodoulou-369286-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/simone-hutsch-384830-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/simone-hutsch-384862-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/spencer-watson-362476-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/syd-sujuaan-293256-unsplash.jpg
  examples/using-gatsby-image/src/images/gallery/yoann-siloine-532511-unsplash.jpg
  examples/using-gatsby-image/src/pages/background-color.js
  examples/using-gatsby-image/src/pages/blur-up.js
  examples/using-gatsby-image/src/pages/index.js
  examples/using-gatsby-image/src/pages/prefer-webp.js
  examples/using-gatsby-image/src/pages/traced-svg.js
Labels: status: WIP

#9650 Emphasize importance of promise return on source-plugin docs
  docs/docs/create-source-plugin.md
  docs/docs/source-plugin-tutorial.md
Labels: type: documentation

#9498 Fix grammar and punctuation
  docs/tutorial/part-one/index.md
  docs/tutorial/part-two/index.md
Labels: status: awaiting author response

#8622 Format all supported files (except JS)
  CHANGELOG.md
  docs/blog/2018-10-09-hacktoberfest-kickoff/index.md
  docs/blog/2018-10-15-beyond-static-intro/index.md
  docs/docs/adding-website-functionality.md
  docs/docs/behind-the-scenes.md
  docs/docs/creating-slugs-for-pages.md
  docs/docs/deploying-to-aerobatic.md
  docs/docs/deploying-to-heroku.md
  docs/docs/deploying-to-s3-cloudfront.md
  docs/docs/environment-variables.md
  docs/docs/gatsby-cli.md
  docs/docs/gatsby-link.md
  docs/docs/linking-between-pages.md
  docs/docs/node-creation.md
  docs/docs/node-tracking.md
  docs/docs/page-creation.md
  docs/docs/post-css.md
  docs/docs/query-behind-the-scenes.md
  docs/docs/query-execution.md
  docs/docs/query-extraction.md
  docs/docs/schema-connections.md
  docs/docs/schema-generation.md
  docs/docs/sourcing-from-drupal.md
  docs/docs/sourcing-from-wordpress.md
  docs/docs/static-folder.md
  docs/docs/static-vs-normal-queries.md
  docs/docs/testing.md
  examples/hn/src/css/news.css
  examples/using-css-modules/src/styles/another-page.module.css
  examples/using-css-modules/src/styles/index.module.css
  examples/using-css-modules/src/styles/sass.module.scss
  examples/using-faker/src/layouts/index.css
  examples/using-javascript-transforms/src/articles/2017-03-09-choropleth-on-d3v4/style.scss
  examples/using-javascript-transforms/src/articles/2017-05-30-choropleth-on-d3v4-alternate/style.scss
  examples/using-javascript-transforms/src/components/SiteLinks/style.css
  examples/using-javascript-transforms/src/components/SiteNav/style.css
  examples/using-javascript-transforms/src/static/css/base.scss
  examples/using-javascript-transforms/src/static/fonts/fontawesome/style.css
  examples/using-page-transitions/src/layouts/layout.css
  examples/using-prefetching-preloading-modules/src/pages/style.css
  examples/using-redirects/src/components/layout.css
  examples/using-redirects/src/components/selected.css
  examples/using-sass/src/styles/main.scss
  examples/using-sqip/src/index.css
  packages/gatsby-cli/README.md
  packages/gatsby-image/README.md
  packages/gatsby-plugin-layout/README.md
  packages/gatsby-plugin-netlify-cms/README.md
  packages/gatsby-plugin-page-creator/README.md
  packages/gatsby-plugin-remove-trailing-slashes/README.md
  packages/gatsby-transformer-javascript-frontmatter/README.md
  packages/gatsby-transformer-pdf/README.md
  packages/gatsby-transformer-remark/README.md
Labels: status: WIP

#9763 docs: Fix nonsensical sentence in project structure docs
  docs/docs/gatsby-project-structure.md
Labels: type: documentation

#9865 docs: updated install hint for gatsby-plugin-typography
  docs/docs/typography-js.md
Labels: type: documentation

#9497 docs(gatsby-plugin-google-gtag): clarify that this plugin is inactive in dev
  packages/gatsby-plugin-google-gtag/README.md
Labels: status: awaiting author response

#10075 docs(gatsby-plugin-offline): Add instructions for removing service worker
  packages/gatsby-plugin-offline/README.md
Labels: type: documentation

#10158 docs: Add instructions for un-marking stub documents
  docs/docs/how-to-contribute.md
Labels: type: documentation
