Repository gatsbyjs/gatsby, pull requests merged in 2018-03, with the labels that each got.

#4291 Encrypt env var correctly
  .travis.yml
Labels: review

#4272 docs: improve documentation for plugin authors
  CONTRIBUTING.md
  docs/docs/plugin-authoring.md
  docs/docs/plugins.md
  www/src/pages/docs/doc-links.yaml
Labels: Documentation, review

#4301 Redirect from tweeted out link to blog post to changed link
  www/gatsby-node.js
Labels: review

#4315 Fix docker build
  Dockerfile
  packages/gatsby-remark-copy-linked-files/src/index.js
Labels: review

#4143 Add live examples to the GraphQL reference page
  docs/docs/graphql-reference.md
Labels: review

#4324 Update graphql-reference.md
  docs/docs/graphql-reference.md
Labels: review

#4328 Set valid defaults for noscript images
  packages/gatsby-image/src/index.js
Labels: review

#4329 Fix plugins not running `gatsby-browser.js`
  examples/using-remark/src/layouts/index.js
  examples/using-remark/src/pages/2017-11-14---excerpts/index.md
  examples/using-remark/src/pages/examples/example---custom-separator/index.md
  examples/using-remark/src/templates/template-blog-post.js
  packages/gatsby-plugin-catch-links/src/gatsby-browser.js
  packages/gatsby-plugin-typography/src/gatsby-browser.js
Labels: review

#4339 Compare search and hash not just pathname fixes #4292
  packages/gatsby/cache-dir/production-app.js
Labels: review

#4332 Add PrismJS classname to <pre> and <code> tags
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/src/index.js
Labels: review

#4330 Add documentation for createRemoteFileNode
  packages/gatsby-source-filesystem/README.md
Labels: review

#4298 [v2] Refactor loading Babel to make it behave like rest of Gatsby
  docs/docs/babel.md
  examples/using-emotion/package.json
  examples/using-emotion/src/pages/index.js
  examples/using-glamor/package.json
  examples/using-glamor/src/html.js
  examples/using-styled-jsx/package.json
  packages/gatsby-plugin-emotion/package.json
  packages/gatsby-plugin-emotion/src/gatsby-node.js
  packages/gatsby-plugin-glamor/src/gatsby-node.js
  packages/gatsby-plugin-lodash/package.json
  packages/gatsby-plugin-lodash/src/gatsby-node.js
  packages/gatsby-plugin-react-css-modules/package.json
  packages/gatsby-plugin-react-css-modules/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-react-css-modules/src/gatsby-node.js
  packages/gatsby-plugin-styled-components/README.md
  packages/gatsby-plugin-styled-jsx/package.json
  packages/gatsby-plugin-styled-jsx/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-styled-jsx/src/gatsby-node.js
  packages/gatsby/src/bootstrap/__tests__/__snapshots__/load-plugins.js.snap
  packages/gatsby/src/bootstrap/load-plugins.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/internal-plugins/dev-404-page/gatsby-node.js
  packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js
  packages/gatsby/src/internal-plugins/load-babel-config/index.js
  packages/gatsby/src/internal-plugins/load-babel-config/package.json
  packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.js.snap
  packages/gatsby/src/redux/__tests__/babelrc.js
  packages/gatsby/src/redux/__tests__/mocks/.babelrc
  packages/gatsby/src/redux/actions.js
  packages/gatsby/src/redux/reducers/babelrc.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/utils/api-node-docs.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/babel-config.js
  packages/gatsby/src/utils/webpack-utils.js
  www/src/pages/docs/doc-links.yaml
Labels: review

#3993 Cross Post - Case Study: Mike Johnston for Colorado
  docs/blog/2018-3-03-case-study-mike-johnston/index.md
  docs/blog/2018-3-03-case-study-mike-johnston/mike-johnston-homepage.png
  docs/blog/author.yaml
  docs/blog/avatars/brandon-konkle.jpg
Labels: review

#4153 New intro to docs/tutorials, Part Zero of tutorials, editing names of tutorials
  docs/blog/money-pit-2.jpeg
  docs/tutorial/index.md
  docs/tutorial/part-zero/index.md
  www/src/pages/docs/index.js
  www/src/pages/docs/tutorial-links.yml
  www/src/pages/tutorial.js
Labels: Documentation, review

#4352 docs: Clarify queries and Components
  docs/docs/querying-with-graphql.md
Labels: review

#4353 Actually handle deletes fixes #4351
  packages/gatsby/src/internal-plugins/query-runner/page-query-runner.js
  packages/gatsby/src/redux/__tests__/nodes.js
  packages/gatsby/src/redux/actions.js
  packages/gatsby/src/redux/index.js
  packages/gatsby/src/redux/reducers/__tests__/page-data-dependencies.js
  packages/gatsby/src/redux/reducers/component-data-dependencies.js
  packages/gatsby/src/redux/reducers/nodes.js
Labels: review

#4327 Add Gatsby CLI options to docs
  www/src/pages/docs/index.js
Labels: review

#4363 Issue template update
  .github/ISSUE_TEMPLATE.md
Labels: review

#4355 Don't use deleteNodes as not handled as well internally
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: review

#4365 Upgrade to sharp v.0.20.0
  packages/gatsby-plugin-sharp/package.json
  yarn.lock
Labels: review

#4378 Skip libvips and builds tools as sharp v0.20.0 now downloads binaries
  Dockerfile
Labels: review

#4356 feat: add gatsby-remark-numbered-footnotes to community plugins
  docs/docs/plugins.md
Labels: review

#4381 Fix actionifying babel config + test
  packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js
  packages/gatsby/src/redux/__tests__/babelrc.js
Labels: review

#4386 docs: move gatsby-plugin-sharp to main plugins array
  packages/gatsby-remark-images/README.md
Labels: Documentation, review

#3906 Plugin Library build fixes
  packages/gatsby-source-drupal/.Rhistory
  packages/gatsby-source-npm-package-search/.gitignore
  packages/gatsby-source-npm-package-search/.npmignore
  packages/gatsby-source-npm-package-search/README.md
  packages/gatsby-source-npm-package-search/index.js
  packages/gatsby-source-npm-package-search/package.json
  packages/gatsby-source-npm-package-search/src/.gitkeep
  packages/gatsby-source-npm-package-search/src/gatsby-node.js
  www/gatsby-config.js
  www/gatsby-node.js
  www/package.json
  www/src/components/markdown-page-footer.js
  www/src/components/package-readme.js
  www/src/components/searchbar-body.js
  www/src/css/searchbox-style.css
  www/src/html.js
  www/src/layouts/index.js
  www/src/pages/packages.js
  www/src/pages/packages.js~HEAD
  www/src/templates/template-docs-local-packages.js
  www/src/templates/template-docs-packages.js
  www/src/templates/template-docs-remote-packages.js
Labels: UX Design, review

#4389 add package-source
  www/package.json
Labels: review

#4388 Add node.id to cache id to avoid cache collissions if the nodes have identical content fixes #4385
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-remark/src/on-node-create.js
  packages/gatsby/src/schema/run-sift.js
Labels: review

#4391 fix infinity loop when inferring input fields for linked nodes
  examples/using-drupal/gatsby-config.js
  packages/gatsby/src/schema/infer-graphql-input-fields.js
Labels: review

#4400 Restore fileAbsolutePath to MarkdownRemark nodes fixes #4399
  packages/gatsby-transformer-remark/src/on-node-create.js
Labels: review

#4403 Remove gatsby-plugin-aphrodite since no one ever built it
  docs/docs/plugins.md
Labels: review

#4405 [v2] Bump SASS peer dep
  packages/gatsby-plugin-sass/package.json
Labels: review

#4406 [v2] Standardize modifyWebpackConfig API to onCreateWebpackConfig
  Breaking Changes.md
  docs/docs/add-custom-webpack-config.md
  docs/docs/debugging-html-builds.md
  examples/using-remark/gatsby-node.js
  packages/gatsby-1-config-css-modules/README.md
  packages/gatsby-plugin-coffeescript/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-coffeescript/src/gatsby-node.js
  packages/gatsby-plugin-glamor/src/gatsby-node.js
  packages/gatsby-plugin-less/src/gatsby-node.js
  packages/gatsby-plugin-lodash/src/gatsby-node.js
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  packages/gatsby-plugin-netlify/src/gatsby-node.js
  packages/gatsby-plugin-no-sourcemaps/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
  packages/gatsby-plugin-react-next/src/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-stylus/src/gatsby-node.js
  packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-typescript/src/gatsby-node.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.js.snap
  packages/gatsby/src/utils/api-node-docs.js
  packages/gatsby/src/utils/webpack.config.js
Labels: review

#4408 Print deprecation notice for deleteNodes and don't show in docs any longer fixes #4407
  packages/gatsby/src/redux/actions.js
  www/src/pages/docs/actions.js
Labels: review

#4410 [www] Design tweaks for the Gatsby Package Library
  www/src/components/package-readme.js
  www/src/components/searchbar-body.js
  www/src/css/searchbox-style.css
  www/src/layouts/index.js
Labels: review

#4414 Remove stray console.log()
  www/src/components/searchbar-body.js
Labels: review

#4420 Add gatsby-plugin as keyword to packages so they'll show up in package search
  packages/gatsby-plugin-aphrodite/package.json
  packages/gatsby-plugin-canonical-urls/package.json
  packages/gatsby-plugin-coffeescript/package.json
  packages/gatsby-plugin-create-client-paths/package.json
  packages/gatsby-plugin-cxs/package.json
  packages/gatsby-plugin-emotion/package.json
  packages/gatsby-plugin-facebook-analytics/package.json
  packages/gatsby-plugin-glamorous/package.json
  packages/gatsby-plugin-less/package.json
  packages/gatsby-plugin-lodash/package.json
  packages/gatsby-plugin-no-sourcemaps/package.json
  packages/gatsby-plugin-nprogress/package.json
  packages/gatsby-plugin-react-helmet/package.json
  packages/gatsby-plugin-react-next/package.json
  packages/gatsby-plugin-remove-trailing-slashes/package.json
  packages/gatsby-plugin-sass/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sitemap/package.json
  packages/gatsby-plugin-styled-jsx/package.json
  packages/gatsby-plugin-styletron/package.json
  packages/gatsby-plugin-twitter/package.json
  packages/gatsby-plugin-typescript/package.json
  packages/gatsby-react-router-scroll/package.json
  packages/gatsby-source-medium/package.json
  packages/gatsby-source-mongodb/package.json
  packages/gatsby-source-npm-package-search/package.json
  packages/gatsby-source-wordpress-com/package.json
  packages/gatsby-transformer-docx/package.json
  packages/gatsby-transformer-javascript-frontmatter/package.json
  packages/gatsby-transformer-pdf/package.json
  packages/gatsby-transformer-screenshot/lambda/package.json
  packages/gatsby-transformer-xml/package.json
Labels: review

#4421 Tweaks for package search
  www/package.json
  www/src/components/package-readme.js
  www/src/components/searchbar-body.js
Labels: review

#4423 [www] Remove stray imports, unused date-fns package
  www/package.json
  www/src/components/searchbar-body.js
  www/src/layouts/index.js
Labels: review

#4424 Restore special class for Algolia
  www/src/layouts/index.js
Labels: review

#4426 Fix pathname for packages so prefetching works
  www/src/components/searchbar-body.js
Labels: review

#4379 fix netlify-cms and sass plugin css extraction
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: review

#4448 Make the blog searchable by Algolia as well
  www/src/layouts/index.js
Labels: review

#4436 Package Library fixes
  www/src/assets/algolia.svg
  www/src/components/searchbar-body.js
  www/src/layouts/index.js
Labels: review

#4429 [gatsby-source-contentful] create children nodes after parent was created
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-contentful/src/normalize.js
Labels: review

#4469 [www] Fix highlighted code block containers in docs/bound-action-creators
  www/src/components/function-list.js
  www/src/pages/docs/bound-action-creators.js
Labels: review

#4471 [www] Increase default <h3> top margin
  www/src/components/evaluation-table-section-title.js
  www/src/utils/typography.js
Labels: review

#4494 Update dep
  packages/gatsby-source-npm-package-search/package.json
Labels: review

#4501 [gatsby-source-wordpress] create children nodes after parent node was created
  packages/gatsby-source-wordpress/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-wordpress/src/normalize.js
Labels: review

#4502 Issue #4498 Update gatsby-remark-prismjs lang deps
  packages/gatsby-remark-prismjs/README.md
  packages/gatsby-remark-prismjs/package.json
  packages/gatsby-remark-prismjs/scripts/get-prism-language-dependencies.js
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/highlight-code.js.snap
  packages/gatsby-remark-prismjs/src/prism-language-dependencies.js
Labels: review

#4495 sass plugin: use existing extract plugin for current stage
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: review

#4466 Support mapping to fields other than id
  packages/gatsby/src/schema/__tests__/infer-graphql-type-test.js
  packages/gatsby/src/schema/infer-graphql-type.js
Labels: review

#4505 Update Styled Components example site title
  examples/using-styled-components/src/html.js
Labels: review

#4506 Update styletron example site title
  examples/using-styletron/src/html.js
Labels: review

#4472 [WIP][www] Replace main navigation item "Community" with "Plugins"
  docs/docs/community.md
  www/gatsby-node.js
  www/src/assets/community.svg
  www/src/assets/mobile-nav-icons.js
  www/src/assets/plugins.svg
  www/src/components/navigation-mobile.js
  www/src/components/navigation.js
  www/src/layouts/index.js
  www/src/pages/docs/doc-links.yaml
  www/src/pages/packages.js
Labels: review

#4422 Plugin library blogpost
  docs/blog/2018-03-07-why-we-created-the-plugin-library/empathy-map.png
  docs/blog/2018-03-07-why-we-created-the-plugin-library/gatsby-plugin-library-compressed.mp4
  docs/blog/2018-03-07-why-we-created-the-plugin-library/index.md
  docs/blog/2018-03-07-why-we-created-the-plugin-library/plugin-tweet.png
  www/static/images/gatsby-plugin-library-compressed.mp4
Labels: UX Design, review

#4481 Update README.md with personal website and source.
  README.md
Labels: review

#4526 upload google search console html file
  www/static/google007cad3f98c003c0.html
Labels: review

#4525 Remove list of official/community plugins and link to plugin library
  docs/docs/plugins.md
Labels: review

#4511 Add Fröhlich ∧ Frei to showcase
  README.md
Labels: review

#4369 Added ability to exclude paths from sitemap plugin
  packages/gatsby-plugin-sitemap/README.md
  packages/gatsby-plugin-sitemap/src/__tests__/index.js
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
  packages/gatsby-plugin-sitemap/src/internals.js
  yarn.lock
Labels: review

#4544 Tweaked capitalization in docs for consistency
  CONTRIBUTING.md
  docs/docs/add-custom-webpack-config.md
  docs/docs/adding-tags-and-categories-to-blog-posts.md
  docs/docs/api-specification.md
  docs/docs/building-apps-with-gatsby.md
  docs/docs/caching.md
  docs/docs/create-source-plugin.md
  docs/docs/creating-and-modifying-pages.md
  docs/docs/deploy-gatsby.md
  docs/docs/how-gatsby-works-with-github-pages.md
  docs/docs/how-to-file-an-issue.md
  docs/docs/path-prefix.md
  docs/docs/querying-with-graphql.md
  www/src/pages/docs/doc-links.yaml
  www/src/pages/docs/index.js
Labels: review

#4546 smoother wording
  docs/blog/2018-03-07-why-we-created-the-plugin-library/index.md
Labels: review

#4522 Add --https option for `gatsby develop`
  docs/docs/local-https.md
  packages/gatsby-cli/README.md
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby/package.json
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/utils/get-ssl-cert.js
  packages/gatsby/src/utils/webpack.config.js
  www/src/pages/docs/doc-links.yaml
Labels: review

#4532 add extract-text-webpack-plugin helper package
  packages/gatsby-1-config-extract-plugin/.gitignore
  packages/gatsby-1-config-extract-plugin/.npmignore
  packages/gatsby-1-config-extract-plugin/README.md
  packages/gatsby-1-config-extract-plugin/package.json
  packages/gatsby-1-config-extract-plugin/src/__tests__/index.js
  packages/gatsby-1-config-extract-plugin/src/index.js
Labels: review

#4393 Split part 4 into three parts
  docs/tutorial/index.md
  docs/tutorial/part-five/allfile-query.png
  docs/tutorial/part-five/data-in-console.png
  docs/tutorial/part-five/filesystem-autocomplete.png
  docs/tutorial/part-five/filesystem-query.png
  docs/tutorial/part-five/graphiql-filesystem.png
  docs/tutorial/part-five/index.md
  docs/tutorial/part-five/my-files-page.png
  docs/tutorial/part-four/index.md
  docs/tutorial/part-four/markdown-example-query.png
  docs/tutorial/part-one/index.md
  docs/tutorial/part-seven/blog-post.png
  docs/tutorial/part-seven/hello-world-blog-post.png
  docs/tutorial/part-seven/index.md
  docs/tutorial/part-seven/markdown-relative-path.png
  docs/tutorial/part-seven/new-pages.png
  docs/tutorial/part-seven/query-markdown-slugs.png
  docs/tutorial/part-six/frontpage.png
  docs/tutorial/part-six/index.md
  docs/tutorial/part-six/markdown-autocomplete.png
  docs/tutorial/part-six/markdown-query.png
  docs/tutorial/part-six/two-posts.png
  docs/tutorial/part-two/index.md
  www/src/pages/docs/tutorial-links.yml
Labels: Documentation, review

#4551 Fix typo
  docs/docs/building-with-components.md
Labels: review

#4552 Add descriptions to plugins missing them
  packages/gatsby-plugin-canonical-urls/package.json
  packages/gatsby-plugin-react-helmet/package.json
  packages/gatsby-plugin-remove-trailing-slashes/package.json
  packages/gatsby-plugin-sitemap/package.json
  packages/gatsby-plugin-styletron/package.json
  packages/gatsby-plugin-twitter/package.json
  packages/gatsby-source-mongodb/package.json
  packages/gatsby-transformer-xml/package.json
Labels: review

#4553 fix typo
  packages/gatsby-plugin-fullstory/README.md
Labels: review

#4561 [www] Fix search box
  www/src/components/search-form.js
Labels: review

#4563 [www] Use algolia's config for search box keyboard shortcut
  www/src/components/search-form.js
Labels: review

#4566 Fix usage instructions for remark-embed-snippet
  packages/gatsby-remark-embed-snippet/README.md
Labels: review

#4554 Filter out deprecated packages
  www/src/components/searchbar-body.js
Labels: review

#4559 Implement extract text plugin helper
  packages/gatsby-1-config-extract-plugin/package.json
  packages/gatsby-plugin-sass/package.json
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: review

#4573 Detect additional export syntaxes
  packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js
  packages/gatsby/src/bootstrap/resolve-module-exports.js
Labels: review

#4375 Standardizing headers, tweaked wording
  docs/tutorial/index.md
  docs/tutorial/part-two/index.md
Labels: review

#4576 Move gatsby-1-config-extract-plugin to dependencies so it'll install
  packages/gatsby-plugin-sass/package.json
  packages/gatsby/package.json
Labels: review

#4587 Revert "gatsby-remark-prismjs: support inline code (single ticks)"
  packages/gatsby-remark-prismjs/README.md
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/src/__tests__/index.js
  packages/gatsby-remark-prismjs/src/index.js
Labels: review

#4595 Remove "gatsby-plugin" keyword from gatsby-react-router-scroll as it's not a plugin
  packages/gatsby-react-router-scroll/package.json
Labels: review

#4630 Update README.md
  README.md
Labels: review

#4632 Add Hapticmedia to the showcase
  README.md
Labels: review

#4635 [WIP][v2] build updates
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/internal-plugins/query-runner/gatsby-node.js
  packages/gatsby/src/internal-plugins/query-runner/pages-writer.js
  packages/gatsby/src/internal-plugins/query-runner/query-runner.js
  packages/gatsby/src/redux/actions.js
  packages/gatsby/src/redux/reducers/layouts.js
  packages/gatsby/src/redux/reducers/pages.js
  packages/gatsby/src/utils/test-require-error.js
Labels: review

#4638 Update jsdoc description
  packages/gatsby/src/redux/index.js
Labels: review

#4646 Update plugins with plugin authoring link
  docs/docs/plugins.md
Labels: review

#4648 Specify Counter.js file name and location.
  docs/tutorial/part-one/index.md
Labels: review

#4246 Add figure and figcaption tags based on content of title
  packages/gatsby-remark-images/README.md
  packages/gatsby-remark-images/src/index.js
Labels: review

#4675 fix some jsdoc parsing bits
  .babelrc.js
  packages/gatsby-transformer-react-docgen/src/Doclets.js
  packages/gatsby-transformer-react-docgen/src/__tests__/Doclets.js
Labels: review

#4607 Consistently use `npm` instead of `yarn` [Docs][Review]
  docs/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/index.md
  docs/docs/deploy-gatsby.md
  docs/docs/gatsby-style-guide.md
  docs/docs/how-gatsby-works-with-github-pages.md
  packages/gatsby-1-config-css-modules/README.md
  packages/gatsby-plugin-coffeescript/README.md
  packages/gatsby-plugin-create-client-paths/README.md
  packages/gatsby-plugin-postcss-sass/README.md
  packages/gatsby-plugin-react-css-modules/README.md
  packages/gatsby-plugin-remove-trailing-slashes/README.md
  packages/gatsby-plugin-sass/README.md
  packages/gatsby-plugin-styled-components/README.md
  packages/gatsby-plugin-styled-jsx/README.md
  packages/gatsby-plugin-stylus/README.md
  packages/gatsby-plugin-typescript/README.md
  packages/gatsby-source-faker/README.md
  packages/gatsby-transformer-react-docgen/README.md
Labels: Documentation

#4658 [v2] Enable cached query results to be loaded
  packages/gatsby/cache-dir/json-store.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/internal-plugins/query-runner/pages-writer.js
  packages/gatsby/src/internal-plugins/query-runner/query-runner.js
  packages/gatsby/src/redux/index.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/json-data-paths.js
  packages/gatsby/src/redux/reducers/layouts.js
  packages/gatsby/src/redux/reducers/pages.js
  packages/gatsby/src/utils/websocket-manager.js
  packages/gatsby/src/utils/websocket.js
Labels: review

#4700 Add CodeBushi to showcase
  README.md
Labels: review

#4695 Add direct link to download VS Community 2015
  docs/docs/gatsby-on-windows.md
Labels: review

#4706 [www] Fix logic to determine selected plugin from list
  www/src/components/searchbar-body.js
Labels: review

#4717 Fix inlined styles with path-prefixing
  packages/gatsby/cache-dir/static-entry.js
Labels: review

#4716 Add docs page on setting up Linux for Gatsby
  docs/docs/gatsby-on-linux.md
Labels: review

#4722 Add support for the Styled Components Babel plugin
  examples/using-styled-components/package.json
  packages/gatsby-plugin-styled-components/README.md
  packages/gatsby-plugin-styled-components/package.json
  packages/gatsby-plugin-styled-components/src/gatsby-node.js
  packages/gatsby/src/utils/babel-config.js
Labels: review

#4734 [gatsby-transformer-remark] Don't generate AST for same node multiple times in parallel
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: review

#4705 [www] Move Plugins page from /packages to /plugins
  www/gatsby-node.js
  www/src/components/navigation-mobile.js
  www/src/components/navigation.js
  www/src/layouts/index.js
  www/src/pages/plugins.js
Labels: review

#4678 Added my personal website with the source code.
  README.md
Labels: review

#4747 [gatsby-source-wordpress] Link Parent pages to pages
  packages/gatsby-source-wordpress/src/gatsby-node.js
  packages/gatsby-source-wordpress/src/normalize.js
Labels: review

#4759 [json-loader] dont recompile on data change
  packages/gatsby/src/internal-plugins/query-runner/pages-writer.js
Labels: review

#4777 updating scrape.js for gatsbygram
  examples/gatsbygram/data/images/T4ygWXs98-.jpg
  examples/gatsbygram/data/posts.json
  examples/gatsbygram/scrape.js
Labels: review

#4766 Add seo docs
  docs/docs/seo.md
  www/src/pages/docs/doc-links.yaml
Labels: review

#4778 Correct potential miscommunication in SEO doc
  docs/docs/seo.md
Labels: review
