Repository gatsbyjs/gatsby, pull requests merged in 2019-12, with the labels that each got.

#19916 fix(gatsby): support union types for one-to-one ___NODE relations
  packages/gatsby/src/schema/__tests__/rebuild-schema.js
  packages/gatsby/src/schema/infer/__tests__/inference-metadata.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/infer/inference-metadata.js
Labels: bot: merge on green

#19933 chore(gatsby-transformer-sharp): remove fragment copying from plugins
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby-transformer-sharp/src/gatsby-node.js
Labels: bot: merge on green

#19910 chore: flatten gatsby-theme dir
  packages/gatsby-theme/CHANGELOG.md
  packages/gatsby-theme/cli.js
  packages/gatsby-theme/gatsby-theme-debug.js
  packages/gatsby-theme/gatsby-theme-eject.js
  packages/gatsby-theme/gatsby-theme-new.js
  packages/gatsby-theme/gatsby-theme/package.json
  packages/gatsby-theme/package.json
Labels: bot: merge on green, type: maintenance

#19946 feat(gatsby): add all rules from eslint-plugin-jsx-a11y
  packages/gatsby/package.json
  packages/gatsby/src/utils/eslint-config.js
  yarn.lock
Labels: bot: merge on green

#19700 Update Routing docs main page
  docs/docs/linking-and-prefetching-with-gatsby.md
  docs/docs/routing.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#18426 chore(docs): Add sourcing-from-forestry doc page
  docs/docs/headless-cms.md
  docs/docs/sourcing-from-forestry.md
Labels: type: documentation

#19967 Importing the Link component is missing
  docs/docs/recipes.md
Labels: bot: merge on green, type: documentation

#19950 fix(gatsby-source-shopify): allShopifyPage node creation issue #18249 fix
  packages/gatsby-source-shopify/src/gatsby-node.js
Labels: bot: merge on green

#19963 Change "the public do" to "the public does"
  docs/docs/glossary.md
Labels: bot: merge on green

#19968 docs: added two portfolios to sites.yml
  docs/sites.yml
Labels: bot: merge on green

#19971 chore(showcase): Add Code Examples blog
  docs/sites.yml
Labels: topic: showcase

#19972 chore(showcase): Add harshil.net
  docs/sites.yml
Labels: topic: showcase

#19960 docs: add 'Deploying to Firebase Hosting' tutorial
  docs/docs/deploying-to-firebase.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#19975 fix(gatsby): Ensure the number of jest-workers respects GATSBY_CPU_COUNT env var
  packages/gatsby/src/utils/worker/pool.js
Labels: bot: merge on green, type: bug

#19984 chore(i18n/update-source): use master over test branch
  scripts/i18n/update-source.js
Labels: bot: merge on green

#19985 fix(gatsby-dev-cli): chmod gatsby bin on copy
  packages/gatsby-dev-cli/src/watch.js
Labels: bot: merge on green, effort: low, impact: low, type: bug

#19998 chore(starters): add gatsby-starter-keturah
  docs/starters.yml
Labels: bot: merge on green

#19504 feat(gatsby): use embedded remote schemas
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/__tests__/gatsby-node.js
  packages/gatsby-source-graphql/src/gatsby-node.js
  packages/gatsby-source-graphql/src/transforms.js
  yarn.lock
Labels: bot: merge on green, topic: GraphQL

#19991 chore: lint all shell scripts
  benchmarks/query/bin/runQueryTiming.sh
  packages/gatsby-transformer-screenshot/chrome/buildChrome.sh
  scripts/assert-changed-files.sh
  scripts/e2e-test.sh
  scripts/prepublish.sh
  scripts/publish-canary.sh
  scripts/publish-site-from-npm.sh
  scripts/publish-starters.sh
  scripts/validate-starters.sh
Labels: bot: merge on green

#18263 chore(docs): Update the "Gatsby on Linux" page
  docs/docs/gatsby-on-linux.md
Labels: type: documentation

#19987 chore(showcase): Add samirmujanovic.com portfolio
  docs/sites.yml
Labels: topic: showcase

#20013 chore(showcase): Remove Smoopit
  docs/sites.yml
Labels: topic: showcase

#20012 chore(showcase): Remove unionpluscard.com
  docs/sites.yml
Labels: topic: showcase

#19888 Moves responsive image CSS back into attribute
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/gatsby-ssr.js
  packages/gatsby-remark-images/src/index.js
Labels: bot: merge on green

#20010 feat(gatsby): support nullish coalescing operator in gatsby
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/index.js
  packages/babel-preset-gatsby-package/package.json
Labels: bot: merge on green

#19023 Update docs unit testing typescript
  docs/docs/unit-testing.md
Labels: status: awaiting reviewer response, type: documentation

#18753 Add config for gatsby-transformer-remark
  docs/docs/working-with-images-in-markdown.md
Labels: status: awaiting reviewer response, type: documentation

#20033 Add the "Documentation" tag to React website
  docs/sites.yml
Labels: bot: merge on green

#18543 feat(gatsby-transformer-remark): allow generating relative path in `tableOfContents`
  packages/gatsby-transformer-remark/README.md
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: status: awaiting reviewer response, type: feature or enhancement

#19137 feat(gatsby-transformer-remark): fall back to pruneLength if no content separator present
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: status: awaiting reviewer response

#19667 Adding blog entry for mediacurrent.com case study
  docs/blog/2019-11-19-gatsby-brings-speed-to-mediacurrent-com/index.md
  docs/blog/author.yaml
  docs/blog/avatars/mark-casias.png
Labels: bot: merge on green, topic: blogpost

#20041 chore(gatsby-plugin-mdx): stop using "babylon" as parser in test
  packages/gatsby-plugin-mdx/loaders/mdx-loader.test.js
Labels: bot: merge on green

#19277 Material-UI and Ant Design requires a plugin
  docs/docs/what-you-dont-need-plugins-for.md
Labels: status: awaiting author response, type: documentation

#20036 feat(gatsby): support `?.` and `??` in generated pages
  packages/babel-preset-gatsby/README.md
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby/src/index.js
Labels: bot: merge on green

#19997 chore(starters):update gatsby-snyung-starter(gatsby-sseon-starter) info
  docs/starters.yml
Labels: status: awaiting author response

#20051 fix(blog): changed date in blog mediacurrent
  docs/blog/2019-12-10-gatsby-brings-speed-to-mediacurrent-com/index.md
Labels: bot: merge on green

#19965 Docs: Encyclopedia: Add entry for Node.js
  docs/docs/glossary.md
  docs/docs/glossary/node.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal

#20063 fix(docs): run prettier on malformed files
  docs/docs/glossary/node.md
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green

#20061 fix(docs): typo in adding-search-with-algolia
  docs/docs/adding-search-with-algolia.md
Labels: bot: merge on green

#20023 fix(gatsby): remove default noscript tag from html.js template
  docs/docs/custom-html.md
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/default-html.js
Labels: bot: merge on green

#20068 fix(gatsby): Add early return in link resolver for empty arrays
  packages/gatsby/src/schema/resolvers.js
Labels: bot: merge on green, type: bug

#20060 Feat: cache queries and monitor for schema changes [gatsby-source-wordpress]
  examples/using-gatsby-source-wordpress-experimental/gatsby-config.js
  examples/using-gatsby-source-wordpress-experimental/package.json
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/graphql-queries.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/on-pre-bootstrap.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/on-pre-bootstrap/build-queries-from-introspection/build-query-on-field-name.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/on-pre-bootstrap/build-queries-from-introspection/index.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/on-pre-bootstrap/build-queries-from-introspection/recursively-transform-fields.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/on-pre-bootstrap/check-if-schema-has-changed.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/on-pre-bootstrap/check-plugin-requirements.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/on-pre-bootstrap/index.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/on-pre-bootstrap/set-api-helpers-to-state.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/source-nodes/create-nodes.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/source-nodes/fetch-nodes.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/source-nodes/get-content-types.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/source-nodes/index.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/source-nodes/paginated-wp-node-fetch.js
  packages/gatsby-source-wordpress-experimental/src/gatsby-node/source-nodes/wp-actions/index.js
  packages/gatsby-source-wordpress-experimental/src/models.js
Labels: topic: WordPress

#20077 fix(docs): add missing closing parens in api-files-gatsby-node.md
  docs/docs/api-files-gatsby-node.md
Labels: bot: merge on green

#18262 Docs: Update install instructions for Windows and Linux on the "Part 0" page
  docs/tutorial/part-zero/01-node-npm-versions.png
  docs/tutorial/part-zero/index.md
Labels: status: awaiting author response, type: documentation

#19966 docs: guide on troubleshooting common errors
  docs/docs/troubleshooting-common-errors.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#20104 chore(sites): Add diyheatpump.net
  docs/sites.yml
Labels: bot: merge on green

#20118 chore: fix linting...
  docs/blog/2019-12-11-reducing-interaction-cloud/index.md
Labels: bot: merge on green

#20025 docs: add info on plugins, themes, and starters
  docs/docs/plugins-themes-and-starters.md
  docs/docs/plugins.md
  docs/docs/starters.md
  docs/docs/themes.md
  docs/docs/themes/converting-a-starter.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#20057 [contributing] update docs on guides & contributions
  docs/contributing/docs-contributions.md
  docs/contributing/docs-templates.md
  docs/contributing/gatsby-style-guide.md
  docs/contributing/managing-pull-requests.md
  docs/docs/api-reference.md
  docs/docs/conceptual-guide.md
  docs/docs/releases-and-migration.md
Labels: type: documentation

#20076 chore(gatsby-plugin-sharp): Use createContentDigest helper
  packages/gatsby-plugin-sharp/src/trace-svg.js
Labels: bot: merge on green

#18849 Resolve package.json of plugins using node resolution algorithm
  packages/gatsby/src/bootstrap/load-plugins/load.js
Labels: bot: merge on green

#20144 feat(gatsby-source-shopify): Add compareAtPrice to presentment prices
  packages/gatsby-source-shopify/src/queries.js
Labels: bot: merge on green

#20066 feat(gatsby-source-shopify): add metafields to each product variant node
  packages/gatsby-source-shopify/src/constants.js
  packages/gatsby-source-shopify/src/gatsby-node.js
  packages/gatsby-source-shopify/src/nodes.js
  packages/gatsby-source-shopify/src/queries.js
Labels: bot: merge on green

#20067 Use webpack watchOptions config for webpack-dev-middleware
  packages/gatsby/src/commands/develop.js
Labels: bot: merge on green

#19713 chore(www): Lazy load components
  www/src/components/code-block/index.js
  www/src/components/layout.js
  www/src/components/modal.js
  www/src/pages/guidelines/color.js
Labels: type: feature or enhancement

#20145 chore(docs): Fix little typo
  docs/docs/themes/shadowing.md
Labels: bot: merge on green, type: documentation

#20134 chore(showcase): Add rumaan.me to showcase
  docs/sites.yml
Labels: topic: showcase

#19570 Update building-a-contact-form.md
  docs/docs/building-a-contact-form.md
Labels: status: awaiting author response, type: documentation

#20115 chore(showcase): Add Saobear's blog
  docs/sites.yml
Labels: topic: showcase

#20024 fix(gatsby-transformer-remark): fix plugin conflict causing escaped HTML in headings
  packages/gatsby-transformer-remark/package.json
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
  packages/gatsby-transformer-remark/src/on-node-create.js
  yarn.lock
Labels: bot: merge on green

#20105 Docs: Encyclopedia entry for GraphQL
  docs/docs/glossary.md
  docs/docs/glossary/graphql.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal

#20113 [docs] move recipes to individual pages
  docs/contributing/docs-templates.md
  docs/docs/gatsby-project-structure.md
  docs/docs/graphql-api.md
  docs/docs/importing-assets-into-files.md
  docs/docs/porting-an-html-site-to-gatsby.md
  docs/docs/recipes.md
  docs/docs/recipes/deploying-your-site.md
  docs/docs/recipes/pages-layouts.md
  docs/docs/recipes/querying-data.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/recipes/styling-css.md
  docs/docs/recipes/transforming-data.md
  docs/docs/recipes/working-with-images.md
  docs/docs/recipes/working-with-starters.md
  docs/docs/recipes/working-with-themes.md
  docs/docs/typography-js.md
  examples/recipe-sourcing-contentful/README.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#20153 Fixed a typo
  www/src/data/sidebars/tutorial-links.yaml
Labels: type: documentation

#20103 blog: Add 'How we accidentally launched a popular Gatsby plugin' post
  docs/blog/2019-12-12-how-we-accidentally-launched-a-popular-gatsby-plugin/index.md
  docs/blog/2019-12-12-how-we-accidentally-launched-a-popular-gatsby-plugin/oerol.png
  docs/blog/avatars/jari-zwarts.png
Labels: bot: merge on green, topic: blogpost

#20157 fix(gatsby): Address npm audit that blocked CI
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/default/package-lock.json
  starters/default/package.json
  starters/gatsby-starter-blog-theme-core/package-lock.json
  starters/gatsby-starter-blog-theme-core/package.json
  starters/gatsby-starter-blog-theme/package-lock.json
  starters/gatsby-starter-blog-theme/package.json
  starters/gatsby-starter-notes-theme/package-lock.json
  starters/gatsby-starter-notes-theme/package.json
  starters/gatsby-starter-theme/package-lock.json
  starters/gatsby-starter-theme/package.json
  starters/hello-world/package-lock.json
  starters/hello-world/package.json
Labels: bot: merge on green, type: maintenance

#20154 chore(gatsby-theme-notes): Use createContentDigest helper
  packages/gatsby-theme-notes/gatsby-node.js
Labels: bot: merge on green

#20158 fix(#19220): added default args for generateBase64 function
  packages/gatsby-plugin-sharp/src/index.js
Labels: bot: merge on green

#20101 chore(docs): Adjust Windows WSL section to point to new Linux docs
  docs/docs/gatsby-on-windows.md
Labels: type: documentation

#20124 fix(www): improve PrevAndNext arrows design
  www/src/components/prev-and-next.js
Labels: bot: merge on green, type: design

#20039 fix(gatsby): fix circular ref stack overflow checks
  packages/gatsby/src/db/__tests__/__snapshots__/sanitize-node.js.snap
  packages/gatsby/src/db/__tests__/sanitize-node.js
  packages/gatsby/src/db/sanitize-node.js
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
Labels: bot: merge on green

#19885 chore(gatsby-plugin-mdx): refactored to use createContentDigest (#8805)
  packages/gatsby-plugin-mdx/utils/create-mdx-node.js
Labels: status: awaiting author response

#20172 fix(blog): Fix missing author
  docs/blog/author.yaml
Labels: bot: merge on green, topic: blogpost

#20169 fix(gatsby): add ./ prefix to paths in async-requires
  e2e-tests/production-runtime/cypress/integration/1-production.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/src/templates/static-page-from-cache.js
  packages/gatsby/src/bootstrap/requires-writer.js
Labels: bot: merge on green

#20178 feat(blog): Add Post - Integrate TinaCMS With Your Gatsby Website
  docs/blog/2019-12-20-integrate-tinacms-with-your-gatsby-website/index.md
  docs/blog/2019-12-20-integrate-tinacms-with-your-gatsby-website/step-five_create-content.jpg
  docs/blog/2019-12-20-integrate-tinacms-with-your-gatsby-website/step-four_inline-editing.jpg
  docs/blog/2019-12-20-integrate-tinacms-with-your-gatsby-website/step-one_empty-sidebar.jpg
  docs/blog/2019-12-20-integrate-tinacms-with-your-gatsby-website/step-three_custom-form.jpg
  docs/blog/2019-12-20-integrate-tinacms-with-your-gatsby-website/step-two_default-form.jpg
  docs/blog/author.yaml
  docs/blog/avatars/scott-byrne.jpg
Labels: bot: merge on green, topic: blogpost

#19786 docs: gatsby for apps - data fetching
  docs/docs/client-data-fetching.md
  docs/docs/data-fetching.md
  docs/docs/recipes.md
  docs/docs/recipes/querying-data.md
  examples/data-fetching/.env.sample
  examples/data-fetching/README.md
  examples/data-fetching/gatsby-config.js
  examples/data-fetching/package.json
  examples/data-fetching/src/components/header.js
  examples/data-fetching/src/components/layout.css
  examples/data-fetching/src/components/layout.js
  examples/data-fetching/src/images/gatsby-icon.png
  examples/data-fetching/src/pages/404.js
  examples/data-fetching/src/pages/index.js
  www/gatsby-node.js
  www/package.json
  www/src/components/build-data-example.js
  www/src/components/client-data-example.js
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green, status: awaiting reviewer response, type: documentation

#20174 docs(environment-variables.md): use `const` instead of `let` if we are not re-assigning it
  docs/docs/environment-variables.md
Labels: bot: merge on green

#20165 fix(gatsby): support unicode characters for 404 page
  e2e-tests/development-runtime/cypress/integration/navigation/linking.js
  e2e-tests/production-runtime/cypress/integration/1-production.js
  packages/gatsby/cache-dir/production-app.js
Labels: bot: merge on green

#20099 fix(gatsby): do not rebuild schema having identical conflicts
  packages/gatsby/src/schema/infer/inference-metadata.js
Labels: bot: merge on green

#20073 fix(docs): fix deprecation warning for boundActionCreators
  www/src/pages/docs/actions.js
Labels: bot: merge on green

#20193 fix(docs): 404 on image and links in recipes
  docs/docs/recipes/querying-data.md
  docs/docs/recipes/sourcing-data.md
Labels: bot: merge on green

#20183 Add flexsearch (client-side engine) to site search overview docs
  docs/docs/adding-search.md
Labels: bot: merge on green, type: documentation

#20147 fix(gatsby-telemetry): only report unique plugins
  packages/gatsby/src/bootstrap/index.js
Labels: bot: merge on green

#20176 chore(starters): add gatsby-starter-chronoblog-hacker
  docs/starters.yml
Labels: bot: merge on green, type: documentation

#20190 docs: Add documentation about GraphQL `skip` and `include` directives
  docs/docs/graphql-reference.md
Labels: bot: merge on green, type: documentation

#20186 fix(gatsby): support file inference for any field name (not just [a-zA-Z0-9_])
  packages/gatsby/src/schema/infer/__tests__/infer.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/infer/is-file.js
Labels: bot: merge on green, impact: low, type: bug

#20175 fix(docs): transition link
  docs/docs/adding-page-transitions-with-plugin-transition-link.md
Labels: bot: merge on green, topic: plugins, type: documentation

#20110 feat(gatsby-cli): support for develop PORT env var
  packages/gatsby-cli/src/create-cli.js
Labels: bot: merge on green

#20196 Add DigiGov to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#20202 chore(starters): change links for chronoblog starters
  docs/starters.yml
Labels: bot: merge on green

#20210 chore(docs): Add Bengali language in transalation list
  docs/contributing/gatsby-docs-translation-guide.md
Labels: type: documentation

#20042 fix(gatsby-source-graphql): use embedded remote schemas
  examples/using-gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/__tests__/__snapshots__/transforms.js.snap
  packages/gatsby-source-graphql/src/__tests__/gatsby-node.js
  packages/gatsby-source-graphql/src/__tests__/transforms.js
  packages/gatsby-source-graphql/src/gatsby-node.js
  packages/gatsby-source-graphql/src/transforms.js
  yarn.lock
Labels: bot: merge on green, needs manual testing, status: awaiting reviewer response, topic: GraphQL

#20212 fix(gatsby): Fix sift query against empty nodes
  packages/gatsby/src/redux/__tests__/run-sift.js
  packages/gatsby/src/redux/run-sift.js
Labels: bot: merge on green

#20219 fix(docs): use new -v for gatsby-dev-cli
  docs/contributing/setting-up-your-local-dev-environment.md
Labels: bot: merge on green

#20206 chore(showcase): Add Zeek Interactive
  docs/sites.yml
Labels: topic: showcase

#20207 chore(showcase): Add Sites by Bare Advertising & Communications
  docs/sites.yml
Labels: topic: showcase

#20217 chore(showcase): Add Paul Scanlon Blog
  docs/sites.yml
Labels: topic: showcase

#20209 docs: add the Gatsby Magic doc
  docs/docs/gatsby-magic.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#20218 refactor(www): Improve consistency of lazy components usage
  www/src/components/code-block/index.js
  www/src/components/layout.js
  www/src/components/lazy-highlight.js
  www/src/components/lazy-modal.js
  www/src/pages/guidelines/color.js
Labels: bot: merge on green

#20204 feat(gatsby-source-shopify): Add support for custom domains
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/__tests__/create-client.js
  packages/gatsby-source-shopify/src/create-client.js
Labels: effort: low, type: bug

#20156 feat(gatsby-remark-prism-js): add additional html escapes
  packages/gatsby-remark-prismjs/README.md
  packages/gatsby-remark-prismjs/src/__tests__/escape-html.js
  packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js
  packages/gatsby-remark-prismjs/src/escape-html.js
  packages/gatsby-remark-prismjs/src/highlight-code.js
  packages/gatsby-remark-prismjs/src/index.js
Labels: bot: merge on green, status: awaiting reviewer response, topic: plugins, type: feature or enhancement

#20236 fix(www): Improve accessibility of showcase page
  www/src/views/shared/collapsible.js
  www/src/views/showcase/showcase-list.js
  www/src/views/starter-library/starter-list.js
Labels: bot: merge on green, type: feature or enhancement

#20188 fix(gatsby-source-filesystem): fix add/change text
  packages/gatsby-source-filesystem/src/gatsby-node.js
Labels: test: manual

#19986 fix(gatsby): enable static queries in `wrapRootElement`
  e2e-tests/development-runtime/cypress/integration/functionality/static-queries.js
  e2e-tests/development-runtime/gatsby-browser.js
  e2e-tests/development-runtime/src/wrap-root-element.js
  e2e-tests/production-runtime/cypress/integration/static-query.js
  e2e-tests/production-runtime/gatsby-browser.js
  e2e-tests/production-runtime/gatsby-ssr.js
  e2e-tests/production-runtime/src/wrap-root-element.js
  packages/gatsby/cache-dir/public-page-renderer-dev.js
  packages/gatsby/cache-dir/query-result-store.js
  packages/gatsby/cache-dir/root.js
Labels: bot: merge on green

#20228 [blog] add 100 days of Gatsby and new email capture form
  docs/blog/100days/100daysofgatsby.png
  docs/blog/100days/index.md
  www/src/components/email-capture-form-100days.js
Labels: bot: merge on green, topic: blogpost, topic: internal, 🎯 Marketing

#20146 feat(gatsby): bundle and page-data stats for telemetry
  packages/gatsby-telemetry/src/index.js
  packages/gatsby-telemetry/src/telemetry.js
  packages/gatsby/src/commands/build-html.js
  packages/gatsby/src/commands/build.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/index.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/page-data-stats.js
  packages/gatsby/src/utils/page-data.js
Labels: bot: merge on green

#19923 chore(gatsby): Use Typescript internally!
  .babelrc.js
  .circleci/config.yml
  jest.config.js
  package.json
  packages/gatsby-cli/.babelrc
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/index.ts
  packages/gatsby-cli/tsconfig.json
  packages/gatsby-core-utils/index.d.ts
  packages/gatsby/package.json
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/tsconfig.json
  peril/package.json
  peril/tsconfig.json
  scripts/check-ts.js
  tsconfig.json
  yarn.lock
Labels: bot: merge on green, effort: med, impact: med, type: maintenance

#20241 fix(gatsby): don't write out `isCreatedByStatefulCreatePages` to page-data files
  packages/gatsby/src/query/query-runner.js
Labels: bot: merge on green

#20120 feat(gatsby): Improve structured errors around GraphQL
  packages/gatsby-cli/src/structured-errors/error-map.js
  packages/gatsby/src/query/__tests__/__snapshots__/error-parser.js.snap
  packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap
  packages/gatsby/src/query/__tests__/error-parser.js
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/error-parser.js
  packages/gatsby/src/query/graphql-errors.js
  packages/gatsby/src/query/query-runner.js
  packages/gatsby/src/utils/api-runner-node-error-parser.js
  packages/gatsby/src/utils/api-runner-node.js
Labels: bot: merge on green, type: feature or enhancement

#20242 docs: Update Contributor triage instructions
  docs/contributing/triaging-github-issues/BugFlow.png
  docs/contributing/triaging-github-issues/DocumentationFlow.png
  docs/contributing/triaging-github-issues/FeatureFlow.png
  docs/contributing/triaging-github-issues/index.md
Labels: bot: merge on green

#20257 chore(actions): Run the site showcase validator only on the base repo
  .github/workflows/schedule-site-showcase-validator-workflow.yml
Labels: bot: merge on green

#20261 Fix typo and add links
  docs/blog/100days/index.md
Labels: bot: merge on green, topic: blogpost, topic: internal, 🎯 Marketing

#19264 Move edit link markdown right under the content
  www/src/templates/template-docs-markdown.js
Labels: bot: merge on green, type: design

#20252 docs: Add documentation issue template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: bot: merge on green, type: documentation

#20251 fix(docs): fix spelling in winning-over-developers
  docs/docs/winning-over-developers.md
Labels: bot: merge on green

#20205 Use gatsby-remark-embedder
  docs/blog/2017-09-26-embracing-graphql/index.md
  docs/blog/2018-05-24-launching-new-gatsby-company/index.md
  docs/blog/2018-06-08-life-after-layouts/index.md
  docs/blog/2018-08-09-swag-store/index.md
  docs/blog/2018-08-11-gatsby-pair-programming/index.md
  docs/blog/2018-09-07-gatsby-values/index.md
  docs/blog/2018-09-17-gatsby-v2.md
  docs/blog/2018-09-27-reach-router/index.md
  docs/blog/2018-1-18-strapi-and-gatsby/index.md
  docs/blog/2018-10-09-hacktoberfest-kickoff/index.md
  docs/blog/2018-10-25-using-gatsby-without-graphql/index.md
  docs/blog/2018-11-01-hacktoberfest-wrapup/index.md
  docs/blog/2018-11-27-gatsby-days/index.md
  docs/blog/2019-01-24-swag-store/index.md
  docs/blog/2019-01-25-blazing-fast-development-with-gatsby-and-sanity-io/index.md
  docs/blog/2019-01-31-why-themes/index.md
  docs/blog/2019-02-11-gatsby-themes-livestream-and-example/index.md
  docs/blog/2019-02-20-introducing-use-static-query/index.md
  docs/blog/2019-03-18-releasing-new-schema-customization/index.md
  docs/blog/2019-03-21-add-auth0-to-gatsby-livestream/index.md
  docs/blog/2019-03-22-introducing-gatsby-preview-beta/index.md
  docs/blog/2019-04-02-behind-the-scenes-what-makes-gatsby-great/index.md
  docs/blog/2019-04-19-gatsby-why-we-write/index.md
  docs/blog/2019-06-26-live-preview-for-drupal/index.md
  docs/blog/2019-08-02-what-is-jsx-pragma/index.md
  docs/blog/2019-08-07-gazette-august/index.md
  docs/blog/2019-11-14-announcing-gatsby-cloud/index.md
  docs/blog/gatsby-v1.md
  docs/docs/adding-search-with-algolia.md
  docs/docs/building-a-contact-form.md
  docs/docs/deploying-to-aws-amplify.md
  docs/docs/sourcing-from-prismic.md
  docs/tutorial/blog-netlify-cms-tutorial/index.md
  www/gatsby-config.js
  www/package.json
Labels: bot: merge on green

#20243 chore(showcase): Add EF
  docs/sites.yml
Labels: bot: merge on green

#20250 feat(gatsby-cli): update docs for develop PORT env var
  docs/docs/cheat-sheet.md
  docs/docs/gatsby-cli.md
  packages/gatsby-cli/src/create-cli.js
Labels: bot: merge on green, topic: cli

#20272 docs: fix case of GitHub and WordPress.
  docs/blog/2019-11-21-how-to-convert-an-existing-gatsby-blog-to-use-mdx/index.md
  docs/blog/2019-11-25-getting-started-with-gatsby-cloud/index.md
  docs/docs/glossary.md
Labels: bot: merge on green, type: documentation

#20274 docs: fix case of Twitter, Netlify and GitHub Pages.
  docs/blog/2018-04-10-how-to-handle-comments-in-gatsby-blogs/index.md
  docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
  docs/blog/2019-04-26-how-to-build-a-blog-with-wordpress-and-gatsby-part-1/index.md
  docs/docs/how-gatsby-works-with-github-pages.md
  docs/starters.yml
  examples/client-only-paths/gatsby-config.js
Labels: bot: merge on green, type: documentation

#20275 docs: update Jest option setupFilesAfterEnv
  docs/docs/testing-css-in-js.md
Labels: bot: merge on green

#20276 docs: fix whitespace around markdown links
  docs/blog/2017-11-09-why-i-created-my-blog-with-gatsby-and-contentful/index.md
  docs/blog/2019-01-09-gatsby-days-talks-are-here.md
  docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
  docs/docs/environment-variables.md
Labels: bot: merge on green, type: documentation

#20277 docs: 🔒 Fix missing HTTPS on gatsbyjs.org links
  docs/blog/2017-11-09-why-i-created-my-blog-with-gatsby-and-contentful/index.md
  docs/docs/gatsby-vendor-partnership.md
  examples/data-fetching/README.md
  starters/gatsby-starter-blog-theme-core/README.md
  starters/gatsby-starter-blog-theme/README.md
  starters/gatsby-starter-notes-theme/README.md
Labels: bot: merge on green, type: documentation

#20278 docs: Fix headings in Markdown.
  docs/blog/2018-04-04-gatsby-contentful-starter-tutorial/index.md
Labels: bot: merge on green, topic: blogpost

#20281 fix(docs): Remove superfluous `-- ` from `gatsby develop` cmd
  docs/tutorial/part-zero/index.md
Labels: bot: merge on green

#19937 feat(gatsby-remark-autolink-headers): Allow `after` option to make icon appear after header text
  packages/gatsby-remark-autolink-headers/README.md
  packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-autolink-headers/src/__tests__/index.js
  packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js
  packages/gatsby-remark-autolink-headers/src/index.js
Labels: bot: merge on green

#20283 docs: Fix Markdown link
  docs/blog/2019-02-27-reactiflux-q-and-a/index.md
Labels: bot: merge on green, topic: blogpost

#20286 Fix commas in code blocks of markdown
  packages/gatsby-remark-prismjs/src/escape-html.js
Labels: bot: merge on green

#20293 fix(gatsby-source-graphql): filter unused variables
  packages/gatsby-source-graphql/package.json
Labels: bot: merge on green

#20304 fix(docs): fix broken url to run-sift.js
  docs/docs/page-node-dependencies.md
Labels: bot: merge on green

#20307 Readd missing id field in refactored Index query
  docs/docs/graphql-concepts.md
Labels: bot: merge on green

#20264 fix(plugin-netlify-cms): set global window vars required for Gatsby components
  packages/gatsby-plugin-netlify-cms/src/cms.js
Labels: bot: merge on green

#20187 Docs: Add "Data Integration" section in winning-over-developers.md
  docs/docs/winning-over-developers.md
Labels: bot: merge on green

#19726 fix(docs): update link to using-gatsby-without-graphql example
  examples/using-local-plugins/README.md
Labels: bot: merge on green, type: documentation

#20349 Update contributor numbers for December 2019
  docs/contributing/community.md
Labels: type: documentation

#20351 (100DaysOfGatsby) Add challenge 1: create blog
  docs/blog/100days/start-blog/index.md
Labels: bot: merge on green, topic: blogpost, topic: internal

#20348 Remove gatsby-plugin-offline
  starters/blog/gatsby-config.js
Labels: bot: merge on green
