Repository gatsbyjs/gatsby, pull requests merged in 2019-11, with the labels that each got.

#19192 chore(showcase): Add Lusta Hair website
  docs/sites.yml
Labels: topic: showcase

#19164 chore(starters): add gatsby-starter-saas-marketing
  docs/starters.yml
Labels: bot: merge on green

#18822 docs: added guide for available components for contributors to gatsbyjs.org
  docs/contributing/docs-and-website-components.md
  www/src/components/shared/pullquote.js
  www/src/data/sidebars/contributing-links.yaml
Labels: bot: merge on green, type: documentation

#19175 Docs/improve gatsby plugin google analytics docs
  packages/gatsby-plugin-google-analytics/README.md
Labels: type: documentation

#19213 fix(starters): revert Kentico Kontent starter
  docs/starters.yml
Labels: bot: merge on green

#19238 docs(starter): fix small typo
  docs/starters.yml
Labels: type: documentation

#19208 fix(gatsby): Fix flatMap import in schema/print.js
  packages/gatsby/package.json
  packages/gatsby/src/schema/print.js
  yarn.lock
Labels: bot: merge on green

#19159 fix(gatsby): clear cache before refresh
  packages/gatsby/cache-dir/navigation.js
Labels: bot: merge on green

#18760 fix(gatsby-plugin-offline): Improve reliability of JS detection
  packages/gatsby-plugin-offline/src/gatsby-ssr.js
  packages/gatsby-plugin-offline/src/sw-append.js
Labels: bot: merge on green

#19254 perf(gatsby-remark-custom-blocks): `_.has` already do `_.isNil`, so remove redundant check
  packages/gatsby-remark-custom-blocks/src/index.js
Labels: bot: merge on green

#18759 Add blog post about using gatsby-plugin-offline with JS disabled
  docs/blog/2019-11-05-how-gatsby-can-power-your-site-offline-even-without-javascript/index.md
Labels: bot: merge on green, topic: blogpost

#19231 [docs] Add Browse themes section
  docs/docs/themes.md
Labels: impact: low, topic: themes, type: documentation

#19244 [docs] Add bullet about themes to What are Plugins
  docs/docs/what-is-a-plugin.md
Labels: impact: low, topic: plugins, topic: themes, type: documentation, type: maintenance

#19245 [docs] Organizing themes tutorials and walkthroughs
  docs/docs/themes.md
  docs/docs/themes/converting-a-starter.md
  docs/tutorial/building-a-theme.md
Labels: topic: themes, type: documentation, type: maintenance, 🎯 Learning

#19146 add gatsby installation instructions for environment setup
  docs/contributing/docs-contributions.md
  docs/contributing/setting-up-your-local-dev-environment.md
Labels: bot: merge on green, type: documentation

#19257 docs: update community event support page
  docs/contributing/organize-a-gatsby-event.md
Labels: type: documentation

#19271 fix(gatsby-transformer-javascript-frontmatter): use typescript parser instead of flow parser for typescript files
  packages/gatsby-transformer-javascript-frontmatter/src/gatsby-node.js
Labels: status: awaiting reviewer response, type: bug

#19054 fix(www): Support dark mode in the feedback widget on mobile devices
  www/src/components/feedback-widget/buttons.js
  www/src/gatsby-plugin-theme-ui/index.js
Labels: bot: merge on green

#19276 feat(starters): Kentico Kontent starter based on Photon
  docs/starters.yml
Labels: bot: merge on green

#19099 update translation guide
  docs/contributing/gatsby-docs-translation-guide.md
Labels: type: documentation

#19246 [docs] Add link to publishing theme and update instructions with gatsby-theme keyword
  docs/contributing/submit-to-plugin-library.md
  docs/docs/themes/building-themes.md
Labels: topic: plugins, topic: themes, type: documentation, type: maintenance

#18921 chore(docs): Styleguide changes
  docs/docs/page-creation.md
  docs/docs/performance-tracing.md
  docs/docs/porting-from-create-react-app-to-gatsby.md
  docs/docs/query-execution.md
  docs/docs/query-extraction.md
  docs/docs/quick-start.md
Labels: status: awaiting author response, type: documentation

#19243 [docs] Refactoring Using Gatsby Themes, how to install a theme directly
  docs/docs/themes/getting-started.md
  docs/docs/themes/using-a-gatsby-theme.md
  docs/docs/themes/using-multiple-gatsby-themes.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: themes, type: documentation, type: maintenance, 🎯 Learning

#19298 chore(gatsby): Bump `graphql-compose` to ^6.3.7
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green

#19141 Add CircleCI job and check if there are changes before commit
  .circleci/config.yml
  scripts/i18n/update-source.js
Labels: topic: i18n

#18388 Added 'winning over content creators' reference.
  docs/docs/winning-over-content-creators.md
  www/src/data/sidebars/doc-links.yaml
Labels: Hacktoberfest, type: documentation

#19278 chore(showcase): Add 'Really Fast Sites' website
  docs/sites.yml
Labels: topic: showcase

#19308 chore: Add stale workflow
  .github/workflows/schedule-stale.yml
Labels: topic: internal

#19341 fix(showcase): remove not whitelisted categories from entries
  docs/sites.yml
Labels: topic: showcase

#19221 chore(showcase): Add peluqueriavenezolana.cl
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#19327 chore(showcase): Add The Fabulous Lifestyles website
  docs/sites.yml
Labels: topic: showcase

#19364 chore(showcase): Added binaria.com
  docs/sites.yml
Labels: bot: merge on green

#19259 chore(showcase): Add Mieke Frouws portfolio
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#19328 fix(blog-starter): remove unused query field from blog-post template
  starters/blog/src/templates/blog-post.js
Labels: topic: GraphQL

#19214 docs: adding rehydration doc and updates to building apps overview (gatsby for apps workflow)
  docs/blog/2018-10-15-beyond-static-intro/index.md
  docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
  docs/blog/2019-03-21-add-auth0-to-gatsby-livestream/index.md
  docs/docs/adding-app-and-website-functionality.md
  docs/docs/adding-website-functionality.md
  docs/docs/building-a-site-with-authentication.md
  docs/docs/building-apps-with-gatsby.md
  docs/docs/creating-and-modifying-pages.md
  docs/docs/images/simple-client-only-routes.png
  docs/docs/images/simple-hybrid-site.png
  docs/docs/images/simple-static-site.png
  docs/docs/porting-from-create-react-app-to-gatsby.md
  docs/docs/react-rehydration.md
  docs/tutorial/authentication-tutorial.md
  www/gatsby-node.js
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green, type: documentation

#19405 docs: styles folder name incorrect
  docs/docs/recipes.md
Labels: bot: merge on green

#19404 Update gatsby-style-guide.md
  docs/contributing/gatsby-style-guide.md
Labels: bot: merge on green

#19338 fix(gatsby): Ensure inferred types do not conflict with types created via schema customization
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
Labels: bot: merge on green

#19416 chore(showcase): Add To Be Created
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#19410 chore(showcase): Add Wealthsimple
  docs/sites.yml
Labels: topic: showcase

#19186 Add instructions for changing deeplinks when editing headings
  docs/contributing/docs-contributions.md
Labels: bot: merge on green, type: documentation

#19435 fix(www): scrolling of feedback widget in docs
  www/src/components/feedback-widget/feedback-form.js
Labels: topic: ux, type: maintenance

#19434 chore(starters): add gatsby-london-after-midnight
  docs/starters.yml
Labels: bot: merge on green

#19376 fix(gatsby): non-latin hash link
  packages/gatsby/cache-dir/navigation.js
Labels: bot: merge on green

#19399 Add note how to enable eslint-loader with custom config
  docs/docs/eslint.md
Labels: bot: merge on green

#18548 adding the ability to select different qualities for png, jpeg and we…
  packages/gatsby-plugin-sharp/README.md
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/plugin-options.js
  packages/gatsby-plugin-sharp/src/process-file.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: bot: merge on green

#19168 fix(gatsby): controlled search input component on dev-404-page
  packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js
Labels: bot: merge on green

#18883 feat(gatsby-remark-images-contentful): add native lazy loading support to contentful images
  packages/gatsby-remark-images-contentful/README.md
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-remark-images-contentful/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images-contentful/src/index.js
Labels: bot: merge on green

#19366 docs(mdx): add caveat on graphql query export
  docs/docs/mdx/writing-pages.md
Labels: bot: merge on green

#19390 fix(gatsby-cli): remove $ for better copy paste
  packages/gatsby-cli/src/init-starter.js
Labels: bot: merge on green

#19342 Use StaleWhileRevalidate for page-data files
  packages/gatsby-plugin-offline/src/gatsby-node.js
Labels: bot: merge on green

#19211 docs(gatsby): html.js docs for themes
  docs/docs/custom-html.md
Labels: bot: merge on green

#17544 fix(gatsby): add / to prefix when stripping prefixes
  e2e-tests/path-prefix/cypress/integration/path-prefix.js
  e2e-tests/path-prefix/src/pages/blogtest.js
  e2e-tests/path-prefix/src/pages/index.js
  packages/gatsby/cache-dir/__tests__/__snapshots__/dev-loader.js.snap
  packages/gatsby/cache-dir/__tests__/__snapshots__/loader.js.snap
  packages/gatsby/cache-dir/__tests__/dev-loader.js
  packages/gatsby/cache-dir/__tests__/loader.js
  packages/gatsby/cache-dir/__tests__/strip-prefix.js
  packages/gatsby/cache-dir/find-path.js
  packages/gatsby/cache-dir/strip-prefix.js
Labels: status: awaiting author response, type: bug

#19449 docs: consistent terminology for hydration
  docs/docs/react-hydration.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#19413 docs: add better source plugin documentation
  docs/docs/creating-a-source-plugin.md
Labels: bot: merge on green, type: documentation

#19443 chore(showcase): Add B-Engaged
  docs/categories.yml
  docs/sites.yml
Labels: topic: showcase

#19402 chore(showcase): Add Century 21 Financial and Base Backpackers
  docs/sites.yml
Labels: topic: showcase

#19460 chore(showcase): Update WAGEC
  docs/sites.yml
Labels: topic: showcase

#19305 chore(showcase): Add Yoseph.tech
  docs/sites.yml
Labels: topic: showcase

#19374 chore(showcase): Add Quema Labs
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#19370 chore(showcase): Add Akshay Thakur's Portfolio
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#19455 chore(showcase): add Kosmos to the showcase
  docs/sites.yml
Labels: bot: merge on green

#19471 chore: Update stale action
  .github/workflows/schedule-stale.yml
Labels: bot: merge on green

#19472 chore(gatsby): remove array.prototype.flatmap
  packages/gatsby/package.json
  packages/gatsby/src/schema/print.js
  yarn.lock
Labels: bot: merge on green

#19424 chore(docs): link to gatsby-plugin-catch-links in gatsby link docs
  docs/docs/gatsby-link.md
Labels: bot: merge on green, type: documentation

#17747 chore(docs): Add documentation for tailwindcss support
  docs/docs/tailwind-css.md
  packages/gatsby-plugin-sass/README.md
Labels: status: awaiting author response, type: documentation

#17612 feat(gatsby-plugin-google-analytics): add custom event helper
  packages/gatsby-plugin-google-analytics/README.md
  packages/gatsby-plugin-google-analytics/index.d.ts
  packages/gatsby-plugin-google-analytics/package.json
  packages/gatsby-plugin-google-analytics/src/__tests__/index.js
  packages/gatsby-plugin-google-analytics/src/index.js
Labels: status: awaiting reviewer response

#19454 feat(gatsby-source-shopify): support multi currency
  packages/gatsby-source-shopify/src/queries.js
Labels: bot: merge on green

#18621 chore(www): Referrer policy
  www/gatsby-config.js
Labels: Hacktoberfest, type: feature or enhancement

#17581 fix(gatsby): Use crossorigin for link in linkPrefetch strategy
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/prefetch.js
Labels: bot: merge on green

#19171 Add hint how to disable ESLint
  docs/docs/eslint.md
Labels: Hacktoberfest, bot: merge on green

#19422 fix(www): line-height in docs feedback
  www/src/components/feedback-widget/feedback-form.js
Labels: bot: merge on green, type: design

#19494 Fix spelling mistake in eCommerce tutorial index
  docs/tutorial/ecommerce-tutorial/index.md
Labels: bot: merge on green

#19293 Update the readme and the docs site to include Netlify hosting
  www/src/data/diagram/static-hosts.yml
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green

#19490 chore(starters): Add gatsby-typescript-tailwind
  docs/starters.yml
Labels: bot: merge on green

#19162 chore(starters): add semantic-ui-docs-gatsby
  docs/starters.yml
Labels: bot: merge on green

#19469 Update sites.yml
  docs/sites.yml
Labels: bot: merge on green

#19467 chore(docs): Add new language in transalation list
  docs/contributing/gatsby-docs-translation-guide.md
Labels: bot: merge on green

#19459 feat(gatsby-dev-cli): Add --version
  packages/gatsby-dev-cli/src/index.js
  packages/gatsby-dev-cli/src/utils/version.js
Labels: bot: merge on green

#19521 fix(www): pullquote colors/contrast for dark theme
  www/src/components/__tests__/banner.js
  www/src/components/shared/pullquote.js
  www/src/gatsby-plugin-theme-ui/index.js
Labels: bot: merge on green, type: design

#18669 chore(docs): Adds two key steps on building ecommerce sites with Stripe tutorial
  docs/tutorial/ecommerce-tutorial/index.md
  docs/tutorial/ecommerce-tutorial/stripe-checkout-clientside-functionality.png
Labels: Hacktoberfest, bot: merge on green, type: documentation

#17061 docs: Importing JSON files correctly outside GraphQL
  docs/docs/static-folder.md
Labels: bot: merge on green, type: documentation

#19539 chore(docs): Add Vietnamese language in transalation list
  docs/contributing/gatsby-docs-translation-guide.md
Labels: bot: merge on green, type: documentation

#19517 chore(showcase): Added bakkenbaeck.com
  docs/sites.yml
Labels: bot: merge on green

#19542 Update second code block to include title field which is missing
  docs/docs/use-static-query.md
Labels: bot: merge on green

#18934 chore(gatsby-plugin-sharp): move image processing to a worker
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/scheduler.js.snap
  packages/gatsby-plugin-sharp/src/__tests__/scheduler.js
  packages/gatsby-plugin-sharp/src/__tests__/worker.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/scheduler.js
  packages/gatsby-plugin-sharp/src/utils.js
  packages/gatsby-plugin-sharp/src/worker.js
  yarn.lock
Labels: bot: merge on green, release: minor

#19546 fix(gatsby-transformer-remark): pass current textNode into recursive call to maintain reference
  packages/gatsby-transformer-remark/src/hast-processing.js
Labels: bot: merge on green

#19372 chore(ci): Nightly run e2e test suite against React prerelease channels
  .circleci/config.yml
  scripts/upgrade-react.js
Labels: bot: merge on green

#19565 chore(showcase): Add nmimicro.no to showcase.
  docs/sites.yml
Labels: topic: showcase

#19583 fix: circleci workspace checks
  .circleci/config.yml
Labels: bot: merge on green

#19586 fix(gatsby): Fix filtering on resolvable children
  packages/gatsby/src/schema/node-model.js
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green

#19219 docs: remove TODOs from Static vs Normal Queries to focus more on internals
  docs/docs/query-execution.md
  docs/docs/static-vs-normal-queries.md
Labels: type: documentation

#19602 fix(scripts): Fix starters_publish circle-ci script
  .circleci/config.yml
Labels: bot: merge on green

#19600 fix(gatsby): Handle special characters in windows paths
  packages/gatsby-core-utils/src/__tests__/path.js
  packages/gatsby-core-utils/src/index.js
  packages/gatsby-core-utils/src/path.js
  packages/gatsby-page-utils/package.json
  packages/gatsby-page-utils/src/watch-directory.js
  packages/gatsby-plugin-mdx/loaders/mdx-loader.js
  packages/gatsby-plugin-mdx/loaders/mdx-scopes.js
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-mdx/utils/create-fake-file-node.js
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-plugin-offline/src/gatsby-node.js
  packages/gatsby-remark-images/package.json
  packages/gatsby-remark-images/src/index.js
  packages/gatsby-source-filesystem/src/__tests__/utils.js
  packages/gatsby-source-filesystem/src/create-file-node.js
  packages/gatsby-source-filesystem/src/create-file-path.js
  packages/gatsby-source-filesystem/src/utils.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.js
  packages/gatsby/src/bootstrap/load-plugins/load.js
  packages/gatsby/src/bootstrap/requires-writer.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/query/__tests__/file-parser.js
  packages/gatsby/src/query/file-parser.js
  packages/gatsby/src/query/query-watcher.js
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/schema/__tests__/kitchen-sink.js
  packages/gatsby/src/schema/__tests__/queries-file.js
  packages/gatsby/src/schema/infer/__tests__/infer.js
  packages/gatsby/src/schema/infer/is-file.js
  packages/gatsby/src/utils/tracer/index.js
  yarn.lock
Labels: bot: merge on green

#19599 fix(gatsby): Improve perf of stale node detection
  packages/gatsby/src/redux/__tests__/nodes.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/nodes-touched.js
  packages/gatsby/src/utils/source-nodes.js
Labels: bot: merge on green

#19587 chore: bump caches for www build
  .circleci/config.yml
Labels: bot: merge on green

#19601 🔒 Fix links missing HTTPS
  starters/gatsby-starter-theme/README.md
Labels: bot: merge on green, type: documentation

#19092 feat(gatsby): Schema rebuilding
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/__tests__/on-node-create.js
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/bootstrap/schema-hot-reloader.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/db/loki/nodes.js
  packages/gatsby/src/query/query-watcher.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/actions/restricted.js
  packages/gatsby/src/redux/index.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/inference-metadata.js
  packages/gatsby/src/redux/reducers/schema-customization.js
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-node-connections.js
  packages/gatsby/src/schema/__tests__/build-node-types.js
  packages/gatsby/src/schema/__tests__/connection-input-fields.js
  packages/gatsby/src/schema/__tests__/rebuild-schema.js
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
  packages/gatsby/src/schema/__tests__/run-query.js
  packages/gatsby/src/schema/extensions/__tests__/field-extensions.js
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/index.js
  packages/gatsby/src/schema/infer/__tests__/__snapshots__/example-value.js.snap
  packages/gatsby/src/schema/infer/__tests__/__snapshots__/inference-metadata.js.snap
  packages/gatsby/src/schema/infer/__tests__/infer-input.js
  packages/gatsby/src/schema/infer/__tests__/infer.js
  packages/gatsby/src/schema/infer/__tests__/inference-metadata.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/infer/example-value.js
  packages/gatsby/src/schema/infer/index.js
  packages/gatsby/src/schema/infer/inference-metadata.js
  packages/gatsby/src/schema/infer/type-conflict-reporter.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/derived-types.js
  packages/gatsby/src/schema/types/filter.js
  packages/gatsby/src/schema/types/node-interface.js
  packages/gatsby/src/schema/types/pagination.js
  packages/gatsby/src/schema/types/sort.js
  packages/gatsby/src/schema/types/type-defs.js
  packages/gatsby/src/utils/create-schema-customization.js
  packages/gatsby/src/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.js
  packages/gatsby/src/utils/gatsby-webpack-stats-extractor.js
  packages/gatsby/src/utils/webpack-utils.js
  packages/gatsby/src/utils/webpack.config.js
Labels: bot: merge on green, release: minor

#19610 feat(gatsby-plugin-typescript): add support for numeric separators
  packages/gatsby-plugin-typescript/package.json
  packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-typescript/src/gatsby-node.js
  yarn.lock
Labels: bot: merge on green

#19615 chore: Delete unused stale.yml file
  .github/stale.yml
Labels: bot: merge on green

#19573 chore(showcase): Add docs.subscribepro.com
  docs/sites.yml
Labels: topic: showcase

#19558 chore(showcase): Add codesundar.com
  docs/sites.yml
Labels: topic: showcase

#19562 chore(showcase): Add VeganWorks
  docs/sites.yml
Labels: topic: showcase

#19550 chore(showcase): Add Anurag Hazra's Portfolio
  docs/sites.yml
Labels: topic: showcase

#19250 chore(starters): add graphcs-landing-starter
  docs/starters.yml
Labels: topic: showcase

#19616 fix(gatsby): don't rerun static queries if text didn't change
  packages/gatsby/src/query/query-watcher.js
Labels: bot: merge on green

#19624 chore(showcase): Add WTL Studio
  docs/sites.yml
Labels: bot: merge on green

#19622 🔒 Fix missing HTTPS on link.
  www/README.md
Labels: type: documentation

#19330 [docs] Add local plugins to "Building Themes"
  docs/docs/themes/building-themes.md
Labels: topic: themes, type: documentation, type: maintenance

#19635 refactor: use includes() instead of indexOf()
  packages/gatsby/src/commands/develop.js
Labels: bot: merge on green

#19554 docs: add detail on server configurations for client side routing
  docs/docs/client-only-routes-and-user-authentication.md
Labels: type: documentation

#19633 Fix e.g. typos
  benchmarks/query/README.md
  e2e-tests/production-runtime/cypress/integration/1-production.js
  examples/using-remark/src/pages/2019-02-06---graphviz/index.md
  packages/gatsby-remark-code-repls/README.md
  packages/gatsby-remark-prismjs/README.md
  packages/gatsby-source-contentful/README.md
  packages/gatsby/cache-dir/find-path.js
  packages/gatsby/src/bootstrap/load-plugins/load.js
  packages/gatsby/src/db/loki/index.js
  packages/gatsby/src/db/loki/nodes-query.js
  packages/gatsby/src/query/index.js
  packages/gatsby/src/redux/actions/restricted.js
  packages/gatsby/src/utils/api-node-helpers-docs.js
Labels: bot: merge on green, type: documentation

#19629 chore(docs): Fix typo in wordpress-source-plugin-tutorial.md
  docs/tutorial/wordpress-source-plugin-tutorial.md
Labels: type: documentation

#19637 fix(gatsby): Nightly job to not skip on files changed
  .circleci/config.yml
Labels: bot: merge on green

#19161 feat(gatsby-source-contentful): handle SELF_SIGNED_CERT_IN_CHAIN error.
  packages/gatsby-source-contentful/src/fetch.js
Labels: status: awaiting author response

#19626 chore(docs): Fix case of Gatsby, Strapi, Bootstrap and WordPress
  docs/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/index.md
  docs/docs/creating-a-source-plugin.md
  docs/docs/themes/conventions.md
  docs/starters.yml
  packages/gatsby-plugin-catch-links/src/__tests__/catch-links.js
  packages/gatsby/src/bootstrap/load-themes/index.js
Labels: bot: merge on green, type: documentation

#19495 Remove creator showcase
  docs/contributing/submit-to-creator-showcase.md
  peril/rules/validate-yaml.ts
  peril/tests/validate-yaml/validate-yaml-creators.test.ts
  www/gatsby-node.js
  www/src/components/creator-data.js
  www/src/data/sidebars/contributing-links.yaml
  www/src/pages/creators/agencies.js
  www/src/pages/creators/companies.js
  www/src/pages/creators/index.js
  www/src/pages/creators/people.js
  www/src/templates/template-creator-details.js
  www/src/views/creators/badge.js
  www/src/views/creators/check.svg
  www/src/views/creators/creators-header.js
  www/src/views/creators/index.js
Labels: bot: merge on green

#17681 feat(gatsby): Enable shadowing of page template queries
  e2e-tests/themes/development-runtime/cypress/integration/pages.js
  e2e-tests/themes/development-runtime/src/gatsby-theme-about/pages/about.js
  e2e-tests/themes/production-runtime/cypress/integration/pages.js
  e2e-tests/themes/production-runtime/src/gatsby-theme-about/pages/about.js
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/create-page.js
  packages/gatsby/src/redux/actions/public.js
Labels: topic: themes

#19657 fix(gatsby): Improve warning message about implicit child fields
  packages/gatsby/src/schema/extensions/__tests__/child-relations.js
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green

#19651 fix(docs): spelling, punctuation, and grammar in blog post.
  docs/blog/2019-11-14-announcing-gatsby-cloud/index.md
Labels: bot: merge on green

#19645 Update README.md
  examples/using-gatsby-without-graphql/README.md
Labels: bot: merge on green

#19656 refactor: use includes over indexOf
  packages/gatsby/src/query/file-parser.js
Labels: bot: merge on green

#19412 [blogpost] "How to convert an existing Gatsby blog to use MDX"
  docs/blog/2019-11-10-how-to-convert-an-existing-gatsby-blog-to-use-mdx/index.md
  docs/blog/2019-11-10-how-to-convert-an-existing-gatsby-blog-to-use-mdx/screenshot.png
  docs/blog/author.yaml
Labels: topic: MDX, topic: blogpost

#19551 docs: gatsby for apps - auth and client only routes
  docs/docs/adding-app-and-website-functionality.md
  docs/docs/building-a-site-with-authentication.md
  docs/docs/client-only-routes-and-user-authentication.md
  docs/docs/images/basic-auth.png
  docs/docs/images/client-only-routes.png
  docs/tutorial/authentication-tutorial.md
  examples/simple-auth/src/components/Details.js
  examples/simple-auth/src/components/Header/index.js
  examples/simple-auth/src/components/Home.js
  examples/simple-auth/src/components/Profile.js
  examples/simple-auth/src/pages/app.js
  examples/simple-auth/src/pages/index.js
  www/gatsby-node.js
Labels: status: awaiting reviewer response, type: documentation

#19556 feat(www): scroll sidebar to display active doc
  www/src/components/sidebar/accordion.js
  www/src/components/sidebar/item.js
  www/src/components/sidebar/scrollbar-position-provider.js
  www/src/components/sidebar/section-title.js
  www/src/components/sidebar/sidebar.js
  www/src/components/sidebar/sticky-responsive-sidebar.js
Labels: 🎯Ecosystem

#19690 Typo in third-party-graphql.md
  docs/docs/third-party-graphql.md
Labels: bot: merge on green

#19672 chore(showcase): Add ToolsDB
  docs/sites.yml
Labels: topic: showcase

#19686 chore(showcase): Update built_by for Headless.page
  docs/sites.yml
Labels: topic: showcase

#19692 refactor(type-conflict-reporter): use `array.prototype.includes` instead of `array.prototype.indexOf`
  packages/gatsby/src/schema/infer/type-conflict-reporter.js
Labels: bot: merge on green

#19371 Added information about deployment to Microsoft IIS
  docs/docs/deploying-to-iis.md
  docs/docs/preparing-for-deployment.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#19671 Include gatsby-remark-images in RootConfig.Plugins array of code-copy section in docs.
  docs/docs/mdx/plugins.md
Labels: bot: merge on green

#19411 Fix and clarify Ghost sourcing page
  docs/docs/sourcing-from-ghost.md
Labels: type: documentation

#19704 [blogpost] Small fixes to "How to convert an existing Gatsby blog to use MDX"
  docs/blog/2019-11-21-how-to-convert-an-existing-gatsby-blog-to-use-mdx/index.md
  docs/blog/2019-11-21-how-to-convert-an-existing-gatsby-blog-to-use-mdx/screenshot.png
Labels: effort: low, type: maintenance

#19708 Update sites.yml
  docs/sites.yml
Labels: bot: merge on green

#19730 refactor(gatsby-plugin-netlify): use includes
  packages/gatsby-plugin-netlify/src/create-redirects.js
Labels: bot: merge on green

#19153 Add new blog submission process and guidelines
  docs/contributing/blog-and-website-contributions.md
Labels: status: awaiting author response, type: documentation

#19735 chore(showcase): Add Whipstitch Webwork
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#19757 refactor(gatsby-source-wordpress): use includes
  packages/gatsby-source-wordpress/src/fetch.js
Labels: bot: merge on green

#19754 chore(showcase) Add talkoverflow
  docs/sites.yml
Labels: bot: merge on green

#19749 chore(showcase): Add lesleylai.info to sites.yml
  docs/sites.yml
Labels: bot: merge on green

#19746 chore(starters): add gatsby-eth-dapp-starter
  docs/starters.yml
Labels: bot: merge on green

#19711 Blogpost about .com/get-started
  docs/blog/2019-11-25-getting-started-with-gatsby-cloud/final-state-comment.png
  docs/blog/2019-11-25-getting-started-with-gatsby-cloud/final-state.png
  docs/blog/2019-11-25-getting-started-with-gatsby-cloud/first-phase.png
  docs/blog/2019-11-25-getting-started-with-gatsby-cloud/index.md
  docs/blog/2019-11-25-getting-started-with-gatsby-cloud/middle-option.png
Labels: topic: blogpost

#18609 docs: guide for porting an html site to gatsby
  docs/docs/porting-an-html-site-to-gatsby.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#19673 chore(gatsby-theme-blog): Add missing css() invocations
  packages/gatsby-theme-blog/src/components/header.js
  packages/gatsby-theme-blog/src/components/headings.js
  packages/gatsby-theme-blog/src/components/post-footer.js
  packages/gatsby-theme-blog/src/components/posts.js
Labels: topic: themes

#19753 chore(gatsby-theme-notes): Adjust directory-list margin
  packages/gatsby-theme-notes/src/components/directory-list.js
Labels: status: awaiting reviewer response, topic: themes

#19773 chore(showcase): Add owlypixel.com
  docs/sites.yml
Labels: topic: showcase

#19747 swap broken link
  docs/docs/mdx/writing-pages.md
Labels: type: documentation

#19654 chore(examples): Updated i18n & typescript
  examples/using-i18n/gatsby-config.js
  examples/using-i18n/package.json
  examples/using-i18n/src/components/layout.js
  examples/using-i18n/src/components/useTranslations.js
  examples/using-i18n/src/templates/post.js
  examples/using-typescript/.eslintrc.js
  examples/using-typescript/gatsby-config.js
  examples/using-typescript/package.json
  examples/using-typescript/src/components/layout.tsx
  examples/using-typescript/src/components/source.tsx
  examples/using-typescript/src/pages/404.tsx
  examples/using-typescript/src/pages/index.tsx
  examples/using-typescript/src/utils/typography.js
  examples/using-typescript/tslint.json
  package.json
Labels: bot: merge on green, type: maintenance

#19756 Update blog-and-website-contributions.md
  docs/contributing/blog-and-website-contributions.md
Labels: type: documentation

#19628 feat: Use "Stale" GitHub action
  .github/workflows/schedule-stale.yml
  peril.settings.json
  peril/rules/not-stale.ts
  peril/rules/run-stale-immediately.ts
  peril/tasks/stale.ts
  peril/tests/not-stale.test.ts
  peril/tests/stale.test.ts
Labels: topic: internal, type: feature or enhancement
