Repository gatsbyjs/gatsby, pull requests merged in 2019-06, with the labels that each got.

#14452 chore(showcase): Add Acto
  docs/sites.yml
Labels: topic: showcase

#14471 added graphicintuitions.com
  docs/sites.yml
Labels: topic: showcase

#14506 fix(docs): Fix typo in blog
  docs/blog/2019-04-29-component-shadowing/index.md
Labels: type: documentation

#14507 fix(staters-showcase): Fix typo
  docs/starters.yml
Labels: type: documentation

#14508 fix(docs): Fix typo
  docs/docs/schema-customization.md
Labels: type: documentation

#14484 chore(showcase): Add Timeline of Terror
  docs/sites.yml
Labels: topic: showcase

#14393 blog: add blog post about recently added graphiql-explorer
  docs/blog/2019-06-03-intergrating-graphiql-explorer/graphiql-explorer-demo.mp4
  docs/blog/2019-06-03-intergrating-graphiql-explorer/graphiql-explorer-union-demo.mp4
  docs/blog/2019-06-03-intergrating-graphiql-explorer/index.md
  docs/blog/author.yaml
  docs/blog/avatars/michal-piechowiak.jpeg
Labels: topic: blogpost

#11932 feat(gatsby-remark-prismjs): add support for language extensions
  packages/gatsby-remark-prismjs/README.md
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/src/__tests__/index.js
  packages/gatsby-remark-prismjs/src/__tests__/load-prism-language-extension.js
  packages/gatsby-remark-prismjs/src/highlight-code.js
  packages/gatsby-remark-prismjs/src/index.js
  packages/gatsby-remark-prismjs/src/load-prism-language-extension.js
  packages/gatsby-remark-prismjs/src/replace-string-with-regexp.js
Labels: bot: merge on green

#14532 feat(showcase): add carine roitfeld site
  docs/sites.yml
Labels: topic: showcase

#13450 feat(gatsby-cli): Add a plugin authoring help in gatsby-cli
  docs/docs/gatsby-cli.md
  packages/gatsby-cli/README.md
  packages/gatsby-cli/src/create-cli.js
Labels: status: awaiting reviewer response, topic: cli

#14211 chore(docs): Add content for "client side only packages"
  docs/docs/using-client-side-only-packages.md
  www/src/data/sidebars/doc-links.yaml
Labels: status: awaiting reviewer response, type: documentation

#14549 chore(showcase): Add the edit suite
  docs/sites.yml
Labels: topic: showcase

#14583 chore(showcase): Add TomTom Traffic Index website
  docs/sites.yml
Labels: topic: showcase

#14584 chore(starters): add gatsby-gitbook-starter
  docs/starters.yml
Labels: bot: merge on green

#14556 List PRs that haven't been updated recently
  .github/actions/high-priority-prs/Dockerfile
  .github/actions/high-priority-prs/data.json
  .github/actions/high-priority-prs/jest.config.js
  .github/actions/high-priority-prs/package.json
  .github/actions/high-priority-prs/src/__tests__/__snapshots__/pr-message.js.snap
  .github/actions/high-priority-prs/src/__tests__/__snapshots__/process.js.snap
  .github/actions/high-priority-prs/src/__tests__/fixtures/data.json
  .github/actions/high-priority-prs/src/__tests__/pr-message.js
  .github/actions/high-priority-prs/src/__tests__/process.js
  .github/actions/high-priority-prs/src/data.json
  .github/actions/high-priority-prs/src/fetch.js
  .github/actions/high-priority-prs/src/index.js
  .github/actions/high-priority-prs/src/pr-message.js
  .github/actions/high-priority-prs/src/process.js
  .github/main.workflow
Labels: bot: merge on green

#14283 refactor(gatsby): restrict actions available in Node APIs
  packages/gatsby-transformer-documentationjs/src/gatsby-node.js
  packages/gatsby/src/redux/actions/__tests__/restricted.js
  packages/gatsby/src/redux/actions/add-page-dependency.js
  packages/gatsby/src/redux/actions/index.js
  packages/gatsby/src/redux/actions/internal.js
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/actions/restricted.js
  packages/gatsby/src/redux/actions/types.js
  packages/gatsby/src/utils/api-runner-node.js
  www/gatsby-node.js
  www/src/components/api-reference/doc-block.js
  www/src/pages/docs/actions.js
Labels: bot: merge on green

#13851 Improve docs for setting up a Gatsby application that pulls content from Markdown files
  docs/docs/adding-markdown-pages.md
  examples/using-markdown-pages/.gitignore
  examples/using-markdown-pages/README.md
  examples/using-markdown-pages/gatsby-browser.js
  examples/using-markdown-pages/gatsby-config.js
  examples/using-markdown-pages/gatsby-node.js
  examples/using-markdown-pages/gatsby-ssr.js
  examples/using-markdown-pages/package.json
  examples/using-markdown-pages/src/components/header.js
  examples/using-markdown-pages/src/components/layout.css
  examples/using-markdown-pages/src/components/layout.js
  examples/using-markdown-pages/src/images/gatsby-astronaut.png
  examples/using-markdown-pages/src/images/gatsby-icon.png
  examples/using-markdown-pages/src/markdown-pages/post-1.md
  examples/using-markdown-pages/src/pages/404.js
  examples/using-markdown-pages/src/pages/index.js
  examples/using-markdown-pages/src/templates/blogTemplate.js
Labels: status: awaiting reviewer response, type: documentation

#14568 chore(starters): add gatsby-starter-blog-with-lunr
  docs/starters.yml
Labels: bot: merge on green

#14589 Update gatsby-node.js
  examples/hn/gatsby-node.js
Labels: bot: merge on green

#14617 Revert "Update gatsby-node.js"
  examples/hn/gatsby-node.js
Labels: bot: merge on green

#14619 chore(CODEOWNERS): protect all files
  CODEOWNERS
Labels: bot: merge on green

#14621 fix: fix pr action
  .github/actions/high-priority-prs/README.md
  .github/actions/high-priority-prs/src/__tests__/pr-message.js
  .github/actions/high-priority-prs/src/__tests__/process-data.js
  .github/actions/high-priority-prs/src/index.js
  .github/actions/high-priority-prs/src/process-data.js
Labels: bot: merge on green

#14624 fix(gatsby): respect the GATSBY_CPU_COUNT env var, if set, by default for sharp
  packages/gatsby/src/utils/__tests__/cpu-core-count.js
  packages/gatsby/src/utils/cpu-core-count.js
Labels: bot: merge on green

#14633 chore(blog): use US English in blog post
  docs/blog/2019-05-17-improvements-to-schema-customization/index.md
Labels: bot: merge on green

#14643 chore(starters): add gatsby-starter-spectral
  docs/starters.yml
Labels: bot: merge on green

#14628 chore(starters): add gatsby-starter-directive
  docs/starters.yml
Labels: bot: merge on green

#14646 chore(blog): add part 1 delicious simplicity blog post
  docs/blog/2019-06-08-delicious-simplicity-case-study-part-1/index.md
  docs/blog/author.yaml
  docs/blog/avatars/michelle-gienow.jpg
Labels: bot: merge on green

#14402 fix(gatsby-source-mongodb): fix mapping function signature
  packages/gatsby-source-mongodb/package.json
  packages/gatsby-source-mongodb/src/__tests__/mapping.js
  packages/gatsby-source-mongodb/src/gatsby-node.js
  packages/gatsby-source-mongodb/src/mapping.js
Labels: impact: low, status: awaiting reviewer response, topic: plugins

#14159 feat(gatsby-source-contentful): Remove default image transform width
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/extend-node-type.js.snap
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: status: awaiting reviewer response

#13184 fix(react-hooks-support): Changed the gatsby browser entry to not bre…
  packages/gatsby/cache-dir/gatsby-browser-entry.js
Labels: bot: merge on green

#14691 fix(gatsby-remark-graphviz): fix graphviz on node < 10
  packages/gatsby-remark-graphviz/package.json
  packages/gatsby-remark-graphviz/src/__tests__/index.js
  packages/gatsby-remark-graphviz/src/index.js
Labels: bot: merge on green

#14692 fix(www): Bump up to gatsby-remark-graphviz@1.0.11 to fix builds on Node < 10
  www/package.json
Labels: bot: merge on green

#14675 feat(showcase): Add Asjas Gatsby Site
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#14257 chore(docs): Update tutorial documentation part 4, 7 & 8
  docs/tutorial/part-eight/icon.png
  docs/tutorial/part-eight/index.md
  docs/tutorial/part-four/index.md
  docs/tutorial/part-seven/index.md
Labels: type: documentation

#14706 chore(docs): Fix use of navigate
  docs/tutorial/authentication-tutorial.md
Labels: bot: merge on green

#14702 chore(showcase): Add Glug-Infinite site to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#14728 fix(gatsby): Fix group and distinct when used with fragments
  packages/gatsby/src/db/common/query.js
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/resolvers.js
Labels: bot: merge on green

#14679 fix(gatsby): Make createPageDependency public again
  docs/docs/sourcing-from-sanity.md
  packages/gatsby/src/redux/actions/public.js
Labels: bot: merge on green

#14660 chore(starters): add website-static
  docs/starters.yml
Labels: bot: merge on green

#14724 chore(docs): fill out winning over developers stub
  docs/docs/winning-over-developers.md
Labels: bot: merge on green, type: documentation

#14626 www(docs): Guide on porting Create React App to Gatsby
  docs/docs/porting-create-react-app-to-gatsby.md
  docs/docs/porting-to-gatsby.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation, 🎯 Learning

#14749 fix(docs): renamed file to match slug with doc links sidebar
  docs/docs/porting-from-create-react-app-to-gatsby.md
Labels: bot: merge on green

#14697 fix(docs): improve image docs from workflow evaluation
  docs/docs/gatsby-config.md
  docs/docs/gatsby-image.md
  docs/docs/gatsby-link.md
  docs/docs/images-and-files.md
  docs/docs/images/dancing-otter.gif
  docs/docs/images/duotone-before-after.png
  docs/docs/images/grayscale-before-after.png
  docs/docs/using-gatsby-image.md
  docs/docs/working-with-gifs.md
  docs/docs/working-with-images.md
  packages/gatsby-image/README.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#14743 fix: change md quote to pullquote
  docs/blog/2019-06-10-how-to-recognize-when-gatsby-is-a-good-fit-for-your-client/index.md
Labels: topic: blogpost

#14751 fix(www): Update webinar banner for upcoming - ImpossibleFoods
  www/src/components/banner.js
Labels: 🎯 Marketing

#14761 chore(docs): include link to Jason's You Belong Here talk
  docs/docs/gatsby-core-philosophy.md
Labels: bot: merge on green

#14730 feat(blog): add per page manifest blog post
  docs/blog/2019-06-12-performance-improvements-for-large-sites/comparison.png
  docs/blog/2019-06-12-performance-improvements-for-large-sites/index.md
  docs/blog/author.yaml
  docs/blog/avatars/anthony-marcar.jpg
Labels: topic: blogpost

#14757 chore(showcase): add Bytom Blockchain
  docs/sites.yml
Labels: bot: merge on green

#14379 feat(gatsby-remark-images): add option to use alt text as caption fallback
  packages/gatsby-remark-images/README.md
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/index.js
Labels: bot: merge on green

#14767 Rollback DANGEROUSLY_DISABLE_OOM
  docs/docs/scaling-issues.md
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/index.js
Labels: bot: merge on green

#14764 chore(showcase): Add StateOfCSS website
  docs/sites.yml
Labels: bot: merge on green

#14775 chore(docs): update days in advance
  docs/contributing/pair-programming.md
Labels: bot: merge on green

#14769 docs(blog): recommend using gatsby@2.9.x instead of 2.9.0
  docs/blog/2019-06-12-performance-improvements-for-large-sites/index.md
Labels: bot: merge on green

#14253 feat(gatsby-remark-autolink-headers): Support {#custom-id} header syntax
  packages/gatsby-remark-autolink-headers/README.md
  packages/gatsby-remark-autolink-headers/src/__tests__/index.js
  packages/gatsby-remark-autolink-headers/src/index.js
Labels: status: awaiting reviewer response

#14547 chore(starters): Add Yellowcake to starters
  docs/starters.yml
Labels: bot: merge on green

#14299 docs: Using Prismic source with graphql plugin
  docs/tutorial/prismic-source-graphql-tutorial.md
  www/src/data/sidebars/tutorial-links.yaml
Labels: bot: merge on green, type: documentation

#14781 chore(docs): move "starting site without Gatsby new" link
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green

#14777 Add https://gatsbyguides.com/ to awesome-gatsby.md
  docs/docs/awesome-gatsby.md
Labels: bot: merge on green

#14783 fix(gatsby-plugin-netlify-cms): Fix minimizer for production builds with gatsby-plugins-netlify-cms
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
Labels: bot: merge on green

#14784 chore(actions): Add Kyle G to list of maintainers
  .github/actions/high-priority-prs/src/process-data.js
Labels: bot: merge on green

#13973 feat(gatsby-remark-embed-snippet): apply gatsby-remark-prismjs configuration to embedded snippets
  examples/using-remark/package.json
  packages/gatsby-remark-embed-snippet/README.md
  packages/gatsby-remark-embed-snippet/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-embed-snippet/src/__tests__/index.js
  packages/gatsby-remark-embed-snippet/src/index.js
Labels: breaking change

#14785 feat(docs): Add documentation on upgrading from Node 6
  docs/docs/upgrading-node-js.md
Labels: bot: merge on green

#14763 docs(www): Managing Pull Requests
  docs/contributing/managing-pull-requests.md
  www/src/data/sidebars/contributing-links.yaml
Labels: bot: merge on green

#14727 feat(blog): add day in the life blog post
  docs/blog/2019-06-17-day-in-the-life-of-a-core-maintainer/images/discord.png
  docs/blog/2019-06-17-day-in-the-life-of-a-core-maintainer/index.md
Labels: topic: blogpost

#14671 docs: end to end testing writing tests.
  docs/docs/end-to-end-testing.md
Labels: type: documentation

#14829 Add Oerol Festival to sites.yml
  docs/sites.yml
Labels: bot: merge on green

#14823 Added a guide for Bulma.io
  docs/docs/bulma.md
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green

#14822 chore(starters): add minimal-gatsby-typescript-starter
  docs/starters.yml
Labels: bot: merge on green

#14811 Update Deploying to Heroku docs
  docs/docs/deploying-to-heroku.md
Labels: bot: merge on green

#14787 chore(docs): Update prismic-source-graphql-tutorial.md
  docs/tutorial/prismic-source-graphql-tutorial.md
Labels: bot: merge on green

#14804 chore(starters): add gatsby-starter-fractal
  docs/starters.yml
Labels: bot: merge on green

#14719 feat(themes): blog theme a11y fixes
  themes/gatsby-starter-theme/content/posts/hello-world.mdx
  themes/gatsby-starter-theme/content/posts/hi-folks.mdx
  themes/gatsby-starter-theme/content/posts/my-second-post.mdx
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-blog/src/components/home-footer-content.js
  themes/gatsby-theme-blog/src/components/home-footer.js
  themes/gatsby-theme-blog/src/components/layout.js
  themes/gatsby-theme-blog/src/components/post-footer-content.js
  themes/gatsby-theme-blog/src/components/post-footer.js
  themes/gatsby-theme-blog/src/pages/index.js
  themes/gatsby-theme-blog/src/templates/blog-post.js
Labels: topic: themes

#14795 fix(gatsby-plugin-netlify-cms): fix minimizer settings
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
Labels: bot: merge on green

#14853 chore: fix linting and optimise svgs in www
  docs/blog/2017-11-08-migrate-from-jekyll-to-gatsby/gatsby.svg
  docs/blog/2019-06-17-product-management-at-Gatsby/index.md
  docs/docs/images/disqus-logo.svg
  examples/using-gatsby-image/src/images/monogram.svg
  examples/using-remark/src/pages/2017-01-02---responsive-images-and-iframes/awesome_tiger.svg
  examples/using-remark/src/pages/2017-01-02---responsive-images-and-iframes/squiggly.svg
  packages/gatsby-remark-graphviz/rendered-graph.svg
  www/src/assets/algolia.svg
  www/src/assets/bg-featured-sites.svg
  www/src/assets/blog.svg
  www/src/assets/docs.svg
  www/src/assets/ecosystem.svg
  www/src/assets/fabric.svg
  www/src/assets/featured-detailpage-featuredicon.svg
  www/src/assets/featured-sites-icons--white.svg
  www/src/assets/featured-sites-icons.svg
  www/src/assets/formidable.svg
  www/src/assets/graphql.svg
  www/src/assets/info-icon.svg
  www/src/assets/jekyll.svg
  www/src/assets/js.svg
  www/src/assets/netlify.svg
  www/src/assets/newsletter-form-ornament.svg
  www/src/assets/plugins-ecosystem.svg
  www/src/assets/plugins.svg
  www/src/assets/quotation-mark-ornament.svg
  www/src/assets/react.svg
  www/src/assets/showcase-feather.svg
  www/src/assets/showcase-magic.svg
  www/src/assets/showcase.svg
  www/src/assets/star-ornament.svg
  www/src/assets/starters.svg
  www/src/assets/tutorial.svg
  www/src/assets/v2icon.svg
  www/src/assets/webpack.svg
  www/src/logo.svg
  www/src/monogram.svg
  www/src/views/creators/check.svg
  www/static/Gatsby-Logo.svg
  www/static/Gatsby-Monogram.svg
  www/static/monogram.svg
  www/static/safari-pinned-tab.svg
Labels: bot: merge on green

#14832 chore(docs): update Edit Tags-Category gatsby-node.js sample code
  docs/docs/adding-tags-and-categories-to-blog-posts.md
Labels: type: documentation

#14760 fix(gatsby-source-contentful): Restricts images to 4000 max image width/height
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/extend-node-type.js.snap
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: status: awaiting author response

#13349 chore(gatsby-transformer-sqip): improve sqip performance and debug logging
  packages/gatsby-transformer-sqip/package.json
  packages/gatsby-transformer-sqip/src/extend-node-type.js
  packages/gatsby-transformer-sqip/src/generate-sqip.js
  yarn.lock
Labels: status: awaiting author response

#14220 feat(gatsby-cli): move progressbar into ink
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/reporter/index.js
  packages/gatsby-cli/src/reporter/reporters/ink/components/progress-bar.js
  packages/gatsby-cli/src/reporter/reporters/ink/components/spinner.js
  packages/gatsby-cli/src/reporter/reporters/ink/reporter.js
  packages/gatsby-cli/src/reporter/reporters/yurnalist/index.js
  packages/gatsby-cli/src/util/calc-elapsed-time.js
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/__tests__/utils.js
  packages/gatsby-plugin-sharp/src/scheduler.js
  packages/gatsby-plugin-sharp/src/utils.js
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/__tests__/utils.js
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/utils.js
  yarn.lock
Labels: status: awaiting reviewer response

#14711 chore(telemetry): add ability to inject tags from env and track websocket updates
  packages/gatsby-telemetry/package.json
  packages/gatsby-telemetry/src/index.js
  packages/gatsby-telemetry/src/telemetry.js
  packages/gatsby/src/utils/websocket-manager.js
Labels: topic: analytics

#14869 fix(www): `fontSizes` tokens in typography.js 🤦‍♂️
  www/src/utils/typography.js
Labels: bot: merge on green

#14812 chore(showcase): Remove McDonald's Design System site
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#14856 docs(www): link to plugin README templates from plugins guide
  docs/contributing/submit-to-plugin-library.md
Labels: type: documentation

#14830 Revised "winning over engineering leaders" Docs page
  docs/docs/winning-over-engineering-leaders.md
Labels: type: documentation

#14623 feat(themes): use gatsby-theme-ui in blog and notes themes
  themes/gatsby-starter-theme/gatsby-config.js
  themes/gatsby-theme-blog-mdx/package.json
  themes/gatsby-theme-blog/gatsby-browser.js
  themes/gatsby-theme-blog/gatsby-config.js
  themes/gatsby-theme-blog/gatsby-ssr.js
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-blog/src/components/mdx.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/colors.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/components.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/index.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/prism.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/styles.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/typography.js
  themes/gatsby-theme-blog/src/templates/blog-post.js
  themes/gatsby-theme-blog/src/theme/provider.js
  themes/gatsby-theme-notes/gatsby-browser.js
  themes/gatsby-theme-notes/gatsby-config.js
  themes/gatsby-theme-notes/gatsby-ssr.js
  themes/gatsby-theme-notes/package.json
  themes/gatsby-theme-notes/src/components/note.js
  themes/gatsby-theme-notes/src/gatsby-theme-ui/index.js
  themes/gatsby-theme-notes/src/root.js
  themes/gatsby-theme-notes/src/templates/note.js
  themes/package.json
Labels: topic: themes

#14779 docs(www): 25 Workflows - Adding CSS and/or Sass
  docs/docs/css-in-js.md
  docs/docs/css-libraries-and-frameworks.md
  docs/docs/post-css.md
  docs/docs/sass.md
  docs/docs/tailwind-css.md
  packages/gatsby-plugin-sass/README.md
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green

#14543 docs(www): 25 Workflows - Embedding components in Markdown with MDX
  docs/docs/adding-markdown-pages.md
  docs/docs/mdx/getting-started.md
  docs/docs/mdx/index.md
  docs/docs/mdx/programmatically-creating-pages.md
  docs/docs/mdx/writing-pages.md
  docs/tutorial/writing-documentation-with-docz.md
  www/src/data/sidebars/doc-links.yaml
  www/src/utils/typography.js
Labels: type: documentation, 🎯 Learning

#14847 fix(tutorials): rename "advanced" to "additional
  docs/tutorial/additional-tutorials.md
  docs/tutorial/advanced-tutorials.md
  docs/tutorial/index.md
  docs/tutorial/part-eight/index.md
  www/gatsby-node.js
  www/src/data/sidebars/doc-links.yaml
  www/src/data/sidebars/tutorial-links.yaml
  www/src/pages/docs/index.js
Labels: bot: merge on green

#14906 chore(gatsby-remark-graphviz): add --ignore for test directory
  packages/gatsby-remark-graphviz/package.json
Labels: bot: merge on green

#14855 feat(blog): Site Showcase Validator blogpost
  docs/blog/2019-06-17-site-showcase-validator/index.md
  docs/blog/author.yaml
  docs/blog/avatars/benjamin-lannon.jpg
Labels: status: WIP, topic: blogpost

#14908 fix(gatsby-cli): add missing node-fetch dependency
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/reporter/reporters/ink/components/develop.js
  yarn.lock
Labels: bot: merge on green

#14910 fix(gatsby): Normalize paths for run queries before caching
  packages/gatsby/src/utils/normalize-page-path.js
  packages/gatsby/src/utils/websocket-manager.js
Labels: bot: merge on green

#14475 chore(docs): update api-reference for component shadowing
  docs/docs/themes/api-reference.md
Labels: type: documentation

#14867 chore(showcase): Added blog.rayriffy.com
  docs/sites.yml
Labels: topic: showcase

#14942 [www] showcase - add libra.org
  docs/sites.yml
Labels: topic: showcase

#14974 chore(*): remove old infrastructure directory
  .prettierignore
  infrastructure/Dockerfile
  infrastructure/blue
  infrastructure/build-site.js
  infrastructure/functions/onGithubWebhook/handler.js
  infrastructure/functions/onGithubWebhook/package.json
  infrastructure/functions/onGithubWebhook/serverless.yml
  infrastructure/functions/onGithubWebhook/yarn.lock
  infrastructure/package.json
  infrastructure/yarn.lock
Labels: bot: merge on green

#15008 fix(showcase): Remove developerecosystem.com
  docs/sites.yml
Labels: bot: merge on green

#15014 fix(gatsby-plugin-create-client-paths): set matchPath correctly
  packages/gatsby-plugin-create-client-paths/README.md
  packages/gatsby-plugin-create-client-paths/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-create-client-paths/src/gatsby-node.js
Labels: bot: merge on green

#15015 refactor(gatsby-plugin-create-client-paths): remove promise
  packages/gatsby-plugin-create-client-paths/src/gatsby-node.js
Labels: bot: merge on green

#14956 fix(gatsby): minor refactor of console functions
  packages/gatsby-cli/src/reporter/index.js
Labels: status: awaiting reviewer response

#14051 feat(gatsby-page-utils): extract logic for watching a directory from gatsby-page-creator so can reuse for custom page creation
  packages/gatsby-page-utils/.babelrc
  packages/gatsby-page-utils/.gitignore
  packages/gatsby-page-utils/README.md
  packages/gatsby-page-utils/package.json
  packages/gatsby-page-utils/src/__tests__/__snapshots__/create-path.js.snap
  packages/gatsby-page-utils/src/__tests__/create-path.js
  packages/gatsby-page-utils/src/__tests__/ignore-path.js
  packages/gatsby-page-utils/src/__tests__/validate-path.js
  packages/gatsby-page-utils/src/create-path.js
  packages/gatsby-page-utils/src/ignore-path.js
  packages/gatsby-page-utils/src/index.js
  packages/gatsby-page-utils/src/validate-path.js
  packages/gatsby-page-utils/src/watch-directory.js
  packages/gatsby-plugin-page-creator/package.json
  packages/gatsby-plugin-page-creator/src/gatsby-node.js
Labels: status: awaiting reviewer response

#14899 Revised "Winning over executives" Docs page
  docs/docs/winning-over-executives.md
Labels: bot: merge on green, type: documentation

#14097 feat(gatsby-cli): Prompt user for options (no args with gatsby new)
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby-cli/src/init-starter.js
Labels: bot: merge on green, topic: cli, type: feature or enhancement

#14738 Add draggable prop to gatsby-image img element, issue #4631
  packages/gatsby-image/README.md
  packages/gatsby-image/index.d.ts
  packages/gatsby-image/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-image/src/__tests__/index.js
  packages/gatsby-image/src/index.js
Labels: bot: merge on green

#15003 Add an entry for https://ldi.global in the showcase sites
  docs/sites.yml
Labels: topic: showcase

#15039 chore(showcase): Add nehalist.io
  docs/sites.yml
Labels: topic: showcase

#15054 fix(www): Center footer links
  www/src/components/shared/footer-links.js
Labels: status: awaiting author response

#15022 docs: add storybook V5 configuration for typescript project
  docs/docs/visual-testing-with-storybook.md
Labels: status: awaiting author response, type: documentation

#15056 docs(gatsby-image): Add SEO advice to the readme
  packages/gatsby-image/README.md
Labels: bot: merge on green

#14996 fix(gatsby-transformer-sqip): make it work again
  packages/gatsby-transformer-sqip/src/extend-node-type.js
  packages/gatsby-transformer-sqip/src/generate-sqip.js
Labels: bot: merge on green, status: awaiting reviewer response

#15051 chore(starters): add gatsby-starter-resume
  docs/starters.yml
Labels: bot: merge on green

#15061 chore(starters): add gatsby-starter-typescript-jest
  docs/starters.yml
Labels: bot: merge on green

#15063 chore: fix domain issue for GreenOrbit
  docs/sites.yml
Labels: status: awaiting author response

#15036 docs: improve 404 docs page
  docs/docs/add-404-page.md
  docs/docs/images/gatsby-custom-404.png
  docs/docs/images/gatsby-default-404.png
Labels: bot: merge on green

#15078 fix(gatsby-cli): Added better-opn as a dependency
  packages/gatsby-cli/package.json
  yarn.lock
Labels: bot: merge on green

#14924 feat(gatsby-cli): improve version output
  packages/gatsby-cli/src/create-cli.js
Labels: bot: merge on green, topic: cli

#15010 fix(gatsby): Fix client side routing match paths regression
  e2e-tests/development-runtime/cypress/integration/functionality/paths.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/pages/paths.js
  e2e-tests/production-runtime/cypress/integration/paths.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/src/pages/paths.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/production-app.js
Labels: bot: merge on green

#12516 feat(publish): clear built files before building package and packing
  package.json
  scripts/clear-package-dir.js
  yarn.lock
Labels: bot: merge on green

#13913 fix(gatsby-remark-responsive-iframe): Support MDX by visiting JSX nodes
  packages/gatsby-remark-responsive-iframe/package.json
  packages/gatsby-remark-responsive-iframe/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-responsive-iframe/src/__tests__/index.js
  packages/gatsby-remark-responsive-iframe/src/index.js
Labels: status: awaiting author response

#11528 fix(gatsby-remark-images): remove clickable whitespace around image when linking
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/index.js
Labels: bot: merge on green

#14963 [www] creators - adding myself to the list
  docs/creators/creators.yml
  docs/creators/images/sankarsan-kampa.jpg
Labels: topic: creators

#14939 feat(docs): updates to the glossary
  docs/docs/client-data-fetching.md
  docs/docs/glossary.md
  www/src/components/horizontal-nav-list.js
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#15067 chore(showcase): Add March And Ash site
  docs/sites.yml
Labels: status: awaiting author response, topic: showcase

#15026 docs: Update deploying-to-heroku.md
  docs/docs/deploying-to-heroku.md
Labels: status: awaiting author response

#15089 chore(showcase): Add ttwo.ca
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#15085 chore(gatsby): bump react-dev-utils to 4.2.3 (security vuln fix)
  packages/gatsby/package.json
Labels: bot: merge on green

#15053 chore(showcase): Updated gvdrenovations URL, added new site
  docs/sites.yml
Labels: bot: merge on green, status: awaiting author response, topic: showcase

#15009 fix(starters): restore vertical spacing in blog post layout
  starters/blog/src/templates/blog-post.js
Labels: status: awaiting author response

#15086 chore(showcase): Add Vazco.eu
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#15113 fix(peril): Fix missing dir name
  peril.settings.json
Labels: bot: merge on green

#15076 docs: Replace gatsby-mdx by gatsby-plugin-mdx
  docs/docs/mdx/getting-started.md
  docs/docs/mdx/index.md
  docs/docs/mdx/plugins.md
  docs/docs/mdx/programmatically-creating-pages.md
Labels: status: awaiting author response

#12936 refactor(gatsby-remark-code-repls): move config per provider
  packages/gatsby-remark-code-repls/README.md
  packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js
  packages/gatsby-remark-code-repls/src/__tests__/index.js
  packages/gatsby-remark-code-repls/src/constants.js
  packages/gatsby-remark-code-repls/src/gatsby-node.js
  packages/gatsby-remark-code-repls/src/index.js
Labels: status: awaiting reviewer response

#15128 fix(docs): updates for contributing to recipes and docs
  docs/contributing/docs-contributions.md
  docs/contributing/docs-templates.md
Labels: type: documentation

#13343 feat(gatsby-source-wordpress): Add support for WP-REST-API V2 Menus
  packages/gatsby-source-wordpress/src/fetch.js
  packages/gatsby-source-wordpress/src/gatsby-node.js
  packages/gatsby-source-wordpress/src/normalize.js
Labels: status: awaiting reviewer response

#15035 chore: change workflows around ~ use less resources
  .circleci/config.yml
Labels: bot: merge on green

#15142 fix(docs): Fix/developer blog
  docs/blog/gatsbygram-case-study/index.md
  docs/docs/gatsby-vendor-partnership.md
Labels: bot: merge on green

#15012 test(gatsby-plugin-google-analytics): improve test suite
  packages/gatsby-plugin-google-analytics/package.json
  packages/gatsby-plugin-google-analytics/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-google-analytics/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-google-analytics/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-google-analytics/src/__tests__/index.js
  packages/gatsby-plugin-google-analytics/src/gatsby-browser.js
  packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js
  yarn.lock
Labels: bot: merge on green

#14923 chore(telemetry): Track createNode utilization
  packages/gatsby-telemetry/src/telemetry.js
  packages/gatsby/src/redux/actions/public.js
Labels: bot: merge on green, topic: analytics

#15162 Create SECURITY.md
  SECURITY.md
Labels: bot: merge on green

#15020 add context to client data fetching page aiming to be easier to understand
  docs/docs/client-data-fetching.md
Labels: bot: merge on green, topic: feedback, type: documentation

#15188 docs(www): updated title for Minimal Reproduction doc for SEO
  docs/contributing/how-to-make-a-reproducible-test-case.md
Labels: bot: merge on green, type: documentation

#15154 docs: update readme with modern web framework
  README.md
Labels: bot: merge on green, status: awaiting reviewer response

#15240 chore(showcase): Removing invalid entries
  docs/sites.yml
Labels: topic: showcase
