Repository gatsbyjs/gatsby, pull requests merged in 2019-09, with the labels that each got.

#17066 docs(gatsby-plugin-mdx): Add reference to shortcodes section
  packages/gatsby-plugin-mdx/README.md
Labels: topic: MDX

#17282 chore(showcase): Add coleruche.com
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#17286 chore(starters): add bonneville
  docs/starters.yml
Labels: bot: merge on green

#17271 Docs: Fix typos
  docs/contributing/using-an-online-dev-environment.md
Labels: bot: merge on green

#17078 fix(gatsby): fix an infinite loop in node child collection
  packages/gatsby/src/redux/actions/public.js
Labels: bot: merge on green

#17240 fix typo
  docs/blog/2017-05-31-introduction-to-gatsby/index.md
Labels: bot: merge on green

#17251 typo error fixed
  docs/docs/sourcing-from-ghost.md
Labels: bot: merge on green

#17252 removed repetition
  docs/docs/sourcing-from-buttercms.md
Labels: bot: merge on green

#17248 fix typo
  docs/tutorial/ecommerce-tutorial/index.md
Labels: bot: merge on green

#17250 Update sourcing-from-sanity.md
  docs/docs/sourcing-from-sanity.md
Labels: bot: merge on green

#17229 fix typo
  docs/blog/2018-10-18-vscode-gatsby-development/index.md
Labels: bot: merge on green

#17265 chore(showcase): Add vermarcsport.com
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#17269 docs(gatsby-image): Document itemProp
  packages/gatsby-image/README.md
Labels: bot: merge on green

#17205 Update typefaces docs
  docs/docs/recipes.md
Labels: bot: merge on green, topic: recipes, type: documentation

#17290 fix(gatsby-plugin-mdx): fix slashes for Windows
  packages/gatsby-plugin-mdx/loaders/mdx-loader.js
Labels: bot: merge on green

#17289 chore(gatsby): Remove unnecessary checks
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
  packages/gatsby/src/schema/resolvers.js
Labels: bot: merge on green

#17275 chore(docs): fixes section sequencing
  www/src/data/sidebars/tutorial-links.yaml
Labels: bot: merge on green

#17199 Fix minor typo
  docs/docs/why-gatsby-uses-graphql.md
  docs/docs/write-pages.md
  packages/gatsby-transformer-xml/README.md
Labels: bot: merge on green

#17107 fix(gatsby-plugin-feed): replace title feed requirement with a warning
  packages/gatsby-plugin-feed/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-feed/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-feed/src/gatsby-node.js
  packages/gatsby-plugin-feed/src/plugin-options.js
Labels: bot: merge on green

#17295 Fix typos in working-with-video.md
  docs/docs/working-with-video.md
Labels: bot: merge on green

#17305 chore(showcase): Add wedding photography site to showcase
  docs/sites.yml
Labels: topic: showcase

#17266 chore(showcase): Add abhith.net.
  docs/sites.yml
Labels: topic: showcase

#17187 chore(starters): Added starter for Agility CMS
  docs/starters.yml
Labels: bot: merge on green

#17225 chore(starters): add gatsby-typescript-minimal
  docs/starters.yml
Labels: bot: merge on green

#17270 chore(starters): Added Start Bootstrap Creative starter
  docs/starters.yml
Labels: bot: merge on green

#17135 fix(gatsby-plugin-mdx): prevent crash when Markdown syntax error
  packages/gatsby-plugin-mdx/loaders/mdx-loader.js
Labels: topic: MDX

#17320 fixed typo
  docs/docs/schema-customization.md
Labels: bot: merge on green

#17120 feat(gatsby-graphiql-explorer): Implement CodeExporter
  packages/gatsby-graphiql-explorer/package.json
  packages/gatsby-graphiql-explorer/src/app/app.js
  packages/gatsby-graphiql-explorer/src/app/snippets.js
  yarn.lock
Labels: topic: GraphQL

#17325 fixed typos
  docs/docs/production-app.md
Labels: bot: merge on green

#17105 docs: Add Recipe on Deploying to ZEIT Now
  docs/docs/recipes.md
Labels: bot: merge on green, topic: recipes, type: documentation

#17327 docs: Fix typos
  docs/docs/programmatically-create-pages-from-data.md
Labels: bot: merge on green

#17277 docs(gatsby-cli): update readme
  packages/gatsby-cli/README.md
Labels: bot: merge on green

#17333 docs: Remove stub for gatsby-plugin-page-transitions
  docs/docs/adding-page-transitions-with-plugin-page-transitions.md
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green, type: documentation

#17274 docs: Add recipe for Using CSS Modules in Styling section
  docs/docs/recipes.md
Labels: bot: merge on green, topic: recipes, type: documentation

#17334 fix(gatsby-plugin-catch-links): fix pluginOptions
  packages/gatsby-plugin-catch-links/.gitignore
  packages/gatsby-plugin-catch-links/README.md
  packages/gatsby-plugin-catch-links/src/catch-links.js
  packages/gatsby-plugin-catch-links/src/gatsby-node.js
Labels: bot: merge on green

#17314 feat(telemetry): Refactor and test CI detection and add support for heroku and now
  packages/gatsby-telemetry/src/__mocks__/ci-info.js
  packages/gatsby-telemetry/src/__tests__/ci.js
  packages/gatsby-telemetry/src/ci.js
  packages/gatsby-telemetry/src/telemetry.js
Labels: bot: merge on green, topic: analytics

#17256 docs: diversity and inclusion blog post
  docs/blog/2018-09-07-gatsby-values/index.md
  docs/blog/2019-07-11-user-testing-accessible-client-routing/index.md
  docs/blog/2019-08-30-diversity-and-inclusion/index.md
  docs/blog/author.yaml
  docs/blog/avatars/maddie-wolf.jpeg
  www/src/data/tags-docs.js
Labels: topic: blogpost

#17366 fix(gatsby-graphiql-explorer): Add missing dep
  packages/gatsby-graphiql-explorer/package.json
  yarn.lock
Labels: bot: merge on green

#17359 docs(recipe): Using global CSS files
  docs/docs/recipes.md
Labels: bot: merge on green, topic: recipes, type: documentation

#16698 feat(gatsby): enable page-creator on all themes
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.js.snap
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.js
  packages/gatsby/src/bootstrap/load-plugins/load.js
Labels: bot: merge on green, topic: themes

#12634 Docs/yaml json source client import
  docs/docs/sourcing-content-from-json-or-yaml.md
  examples/using-gatsby-with-json-yaml/README.md
  examples/using-gatsby-with-json-yaml/content/My-JSON-Content.json
  examples/using-gatsby-with-json-yaml/content/My-YAML-Content.yaml
  examples/using-gatsby-with-json-yaml/content/index.yaml
  examples/using-gatsby-with-json-yaml/gatsby-config.js
  examples/using-gatsby-with-json-yaml/gatsby-node.js
  examples/using-gatsby-with-json-yaml/package.json
  examples/using-gatsby-with-json-yaml/src/pages/index.js
  examples/using-gatsby-with-json-yaml/src/pages/json-at-buildtime.js
  examples/using-gatsby-with-json-yaml/src/pages/yml-at-buildtime.js
  examples/using-gatsby-with-json-yaml/src/templates/basicTemplate.js
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green, type: documentation

#17389 fix: close html comment in recipes.md
  docs/docs/recipes.md
Labels: bot: merge on green

#17371 update email in CoC to a team alias
  docs/blog/2019-08-30-diversity-and-inclusion/index.md
  docs/contributing/code-of-conduct.md
Labels: bot: merge on green

#17347 Added recipe for global styles with layout
  docs/docs/recipes.md
Labels: bot: merge on green, topic: recipes, type: documentation

#17146 feat(docs): Add shadowing reference guide
  docs/docs/themes/shadowing.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: themes, type: documentation

#17405 chore(docs): Add missing "to" in phrase
  docs/docs/optimizing-site-performance-with-guessjs.md
Labels: type: documentation

#17406 fix(gatsby-plugin-offline): prevent caching invalid relative paths
  packages/gatsby-plugin-offline/src/get-resources-from-html.js
Labels: bot: merge on green

#17410 fix(scripts): Exit gracefully in publish starters if nothing to commit
  scripts/publish-starters.sh
Labels: bot: merge on green

#17411 fix(gatsby): order matchpaths paths by specificity
  packages/gatsby/src/bootstrap/__tests__/__snapshots__/requires-writer.js.snap
  packages/gatsby/src/bootstrap/__tests__/requires-writer.js
  packages/gatsby/src/bootstrap/requires-writer.js
Labels: bot: merge on green

#17349 Docs: Added content to SaaS services stub
  docs/docs/sourcing-from-saas-services.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#17408 fix(gatsby-plugin-offline): set path resources on route update to ensure initial page is cached
  packages/gatsby-plugin-offline/src/gatsby-browser.js
Labels: bot: merge on green

#17445 fix(gatsby): fix mapping stack trace to source file after dependency upgrade
  packages/gatsby-cli/src/reporter/__tests__/errors.js
  packages/gatsby-cli/src/reporter/errors.js
  packages/gatsby-cli/src/reporter/prepare-stack-trace.js
  packages/gatsby/src/commands/build-html.js
Labels: bot: merge on green

#17382 chore(docs): Add Agility CMS information
  docs/docs/headless-cms.md
  docs/docs/images/agilitycms-api-keys.png
  docs/docs/images/agilitycms-jumbotron.png
  docs/docs/sourcing-from-agilitycms.md
Labels: type: documentation

#17466 chore(showcase): Remove oern.tv
  docs/sites.yml
Labels: topic: showcase

#17465 fix(docs): correct links in sourcing from json page
  docs/docs/sourcing-content-from-json-or-yaml.md
Labels: type: documentation

#17464 chore(doc): accessibility statement: better link
  docs/accessibility-statement.md
Labels: type: documentation

#17441 chore(showcase): add LeReacteur.io
  docs/sites.yml
Labels: topic: showcase

#17284 fix(gatsby): Use concrete type resolver on interface fields
  packages/gatsby/src/schema/extensions/__tests__/interfaces.js
  packages/gatsby/src/schema/node-model.js
Labels: topic: GraphQL

#17415 chore(docs): Clarify SKUs in Stripe guide
  docs/tutorial/ecommerce-tutorial/index.md
Labels: type: documentation

#17468 chore(showcase): add somo to creators and cinch to sites
  docs/creators/creators.yml
  docs/creators/images/somo.jpg
  docs/sites.yml
Labels: topic: showcase

#17474 chore(starters): add gatsby-starter-nehalem
  docs/starters.yml
Labels: bot: merge on green

#17494 chore(starters): add gatsby-skeleton
  docs/starters.yml
Labels: bot: merge on green

#17488 chore(starters): add gatsby-starter-i18next-sanity
  docs/starters.yml
Labels: bot: merge on green

#17483 chore(docs): fix typos on gatsby-plugin-manifest
  packages/gatsby-plugin-manifest/README.md
Labels: bot: merge on green

#17492 fix(gatsby): Handle Windows drive letter casing correctly
  packages/gatsby/src/redux/actions/public.js
Labels: impact: low

#17420 fix(gatsby): Allow overriding options for default instance of gatsby-plugin-page-creator
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.js.snap
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.js
  packages/gatsby/src/bootstrap/load-plugins/load.js
Labels: bot: merge on green

#17449 chore(starters): add gatsby_starter_portfolio
  docs/starters.yml
Labels: bot: merge on green

#17482 fix(gatsby-cli): added effective condition to check empty path
  packages/gatsby-cli/src/init-starter.js
Labels: bot: merge on green

#17409 fix(gatsby): move default-site-plugin lower than plugin page-creation
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.js.snap
  packages/gatsby/src/bootstrap/load-plugins/load.js
Labels: bot: merge on green

#17339 feat(gatsby-remark-embed-snippet): allow relative embeds
  packages/gatsby-remark-embed-snippet/README.md
  packages/gatsby-remark-embed-snippet/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-embed-snippet/src/__tests__/index.js
  packages/gatsby-remark-embed-snippet/src/index.js
Labels: status: awaiting reviewer response

#17517 Add internal links to updated headless CMS article
  docs/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/index.md
  docs/blog/2018-02-16-bright-future-for-the-web/index.md
  docs/blog/2018-04-10-how-to-handle-comments-in-gatsby-blogs/index.md
  docs/blog/2018-04-27-building-eviction-free-nyc-with-gatsbyjs-and-contentful/index.md
  docs/blog/2018-06-18-why-narative-loves-gatsby/index.md
  docs/blog/2018-08-13-using-decoupled-drupal-with-gatsby/index.md
  docs/blog/2018-1-18-strapi-and-gatsby/index.md
  docs/blog/2018-1-24-creative-software-destruction-new-presentation-layer/index.md
  docs/blog/2018-10-10-unbundling-of-the-cms/index.md
  docs/blog/2018-10-11-rise-of-modern-web-development/index.md
  docs/blog/2018-10-18-creating-compelling-content-experiences/index.md
  docs/blog/2018-12-19-gatsby-scales-with-expertise-and-scope/index.md
  docs/blog/2018-12-19-kentico-cloud-and-gatsby-take-you-beyond-static-websites/index.md
  docs/blog/2018-2-6-choosing-a-back-end/index.md
  docs/blog/2019-01-14-modern-publications-with-gatsby-ghost.md
  docs/blog/2019-03-26-what-the-jamstack-means-for-marketing/index.md
  docs/blog/2019-03-29-interview-with-david-eads/index.md
  docs/blog/2019-04-06-security-for-modern-web-frameworks/index.md
  docs/blog/2019-05-07-advanced-sitemap-plugin-for-seo/index.md
  docs/blog/2019-05-15-enterprise-gatsby-how-to-reduce-your-digital-total-cost-of-ownership-with-gatsby/index.md
  docs/blog/2019-06-08-delicious-simplicity-case-study-part-1/index.md
  docs/blog/2019-06-19-how-the-couch-builds-websites-in-half-the-time-with-gatsby/index.md
  docs/blog/2019-08-23-creating-a-purpose-driven-media-platform/index.md
Labels: bot: merge on green

#17491 chore(gatsby): Add type arguments to <StaticQuery/> to infer prop types
  packages/gatsby/index.d.ts
Labels: bot: merge on green

#17446 fix(gatsby-plugin-offline): use base path instead of path prefix
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-plugin-offline/src/gatsby-browser.js
Labels: bot: merge on green

#17523 docs: fix up some recipe entries
  docs/docs/recipes.md
Labels: bot: merge on green

#17511 fix(gatsby): fix node internal validation
  packages/gatsby-cli/src/structured-errors/error-map.js
  packages/gatsby/src/joi-schemas/__tests__/__snapshots__/joi.js.snap
  packages/gatsby/src/joi-schemas/__tests__/joi.js
  packages/gatsby/src/joi-schemas/joi.js
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/__tests__/stack-trace-utils.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/stack-trace-utils.js
Labels: bot: merge on green

#17522 chore(sites): Add Third and Grove
  docs/sites.yml
Labels: topic: blogpost

#17259 docs: Building The New Third And Grove Website In Gatsby
  docs/blog/2019-06-26-live-preview-for-drupal/index.md
  docs/blog/2019-09-12-building-the-new-third-and-grove-website-in-gatsby/index.md
Labels: topic: blogpost

#17524 chore(showcase): Added nubrakes.com to the sites.yml
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#17479 fix(examples): Update mobx example
  examples/using-mobx/package.json
  examples/using-mobx/readme.md
  examples/using-mobx/src/components/layout.js
Labels: bot: merge on green, status: awaiting author response

#17513 docs: update Segment analytics to proper package and add simple-analytics
  docs/docs/adding-analytics.md
Labels: bot: merge on green

#17518 chore(showcase): Add Recetas EL Universo 💜
  docs/sites.yml
Labels: topic: showcase

#17500 fix(gatsby-source-contentful): Prevent TypeError if many-to-one reference already exists
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-contentful/src/__tests__/data.json
  packages/gatsby-source-contentful/src/normalize.js
Labels: status: awaiting author response

#17154 feat(gatsby-remark-images): Add flag to suppress css background-image to prevent FOUB
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-sharp/src/__tests__/images/alphatest.png
  packages/gatsby-plugin-sharp/src/__tests__/index.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-remark-images/README.md
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/constants.js
  packages/gatsby-remark-images/src/index.js
Labels: topic: images/media

#17538 fix(gatsby-plugin-netlify): security headers merging
  packages/gatsby-plugin-netlify/src/__tests__/__snapshots__/build-headers-program.js.snap
  packages/gatsby-plugin-netlify/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-netlify/src/build-headers-program.js
Labels: bot: merge on green

#17543 docs: Change capitalization of Public to public
  docs/docs/preparing-for-deployment.md
Labels: bot: merge on green

#17348 chore(gatsby): improve wrapPageElement & wrapRootElement doc
  docs/docs/layout-components.md
  packages/gatsby/cache-dir/api-ssr-docs.js
  packages/gatsby/src/utils/api-browser-docs.js
Labels: type: documentation

#17585 chore(showcase): Fox Circus site is closed
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#17602 Update greyscale → grayscale (gatsby-image README)
  packages/gatsby-image/README.md
Labels: type: documentation

#17351 Docs: Recipe for styling with Emotion
  docs/docs/recipes.md
Labels: topic: recipes, type: documentation

#17600 chore(showcase): Add new site to Showcase and new Creator
  docs/creators/creators.yml
  docs/sites.yml
  gerald-martinez.jpg
Labels: topic: creators, topic: showcase

#17629 Change command to gatsby develop
  docs/docs/typography-js.md
Labels: bot: merge on green, type: documentation

#17640 fix(gatsby-plugin-typescript): typo in readme
  packages/gatsby-plugin-typescript/README.md
Labels: type: documentation

#17649 chore(showcase): Removing Design Systems Weekly
  docs/sites.yml
Labels: topic: showcase

#17650 chore(showcase): Removing Fusion Media Group site
  docs/sites.yml
Labels: topic: showcase

#17651 chore(showcase): Remove Herman Starikov site
  docs/sites.yml
Labels: topic: showcase

#17654 chore(showcase): Removing Distrupting Nate
  docs/sites.yml
Labels: topic: showcase

#17655 chore(showcase): Removing How to Book Cheap Flights
  docs/sites.yml
Labels: topic: showcase

#17583 chore(docs): Add info about withPrefix to path-prefix
  docs/docs/path-prefix.md
Labels: type: documentation

#17631 chore(showcase): Add thoughtsandstuff.com
  docs/sites.yml
Labels: topic: showcase

#17652 chore(showcase): Updating Quick Stop Nicaragua catgories
  docs/sites.yml
Labels: topic: showcase

#17627 chore(showcase): Add nicaraguabestguides.com to showcase
  docs/sites.yml
Labels: topic: showcase

#17619 chore(showcase): Add xiel.dev to Showcase
  docs/sites.yml
Labels: topic: showcase

#17648 fix(gatsby-theme-notes): replace path.join
  themes/gatsby-theme-notes/gatsby-node.js
Labels: topic: themes, type: bug

#17642 docs(gatsby-plugin-offline): update appendScript in readme
  packages/gatsby-plugin-offline/README.md
Labels: type: documentation

#17540 Add Impossible Foods case study
  docs/blog/2019-09-11-impossible-foods/index.md
Labels: bot: merge on green, topic: blogpost

#17378 Docs: Recipe for sourcing from Drupal
  docs/docs/recipes.md
Labels: topic: recipes, type: documentation

#17680 fix(blog): Impossible Foods headings rendering
  docs/blog/2019-09-11-impossible-foods/index.md
Labels: topic: blogpost

#17693 fix(gatsby-plugin-sharp): Set a unique uuid for each job
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/scheduler.js
  yarn.lock
Labels: bot: merge on green

#17632 chore(docs): Add section on client only routes
  docs/docs/creating-and-modifying-pages.md
Labels: type: documentation

#17571 fix(gatsby-source-contentful): Fixing when assets are in draft state
  packages/gatsby-source-contentful/src/download-contentful-assets.js
Labels: status: awaiting author response

#17541 chore(gatsby-cli): better error messages with wrong arguments in new command
  packages/gatsby-cli/src/init-starter.js
Labels: topic: cli

#17700 chore(showcase): add Tracli
  docs/sites.yml
Labels: bot: merge on green, status: awaiting author response, topic: showcase

#17694 docs: convert console/shell/terminal into shell
  README.md
  benchmarks/plugin-manifest/README.md
  docs/blog/2018-06-18-moving-from-create-react-app-to-gatsby-js/index.md
  docs/blog/2018-08-24-gatsby-aws-hosting/index.md
  docs/blog/2018-11-03-building-an-accessible-lightbox/index.md
  docs/blog/2019-02-26-getting-started-with-gatsby-themes/index.md
  docs/contributing/using-an-online-dev-environment.md
  docs/docs/mdx/getting-started.md
  e2e-tests/development-runtime/README.md
  e2e-tests/gatsby-image/README.md
  e2e-tests/path-prefix/README.md
  e2e-tests/production-runtime/README.md
  examples/using-shopify/README.md
  examples/using-type-definitions/README.md
  packages/gatsby-codemods/README.md
  packages/gatsby-core-utils/README.md
  packages/gatsby-design-tokens/README.md
  packages/gatsby-page-utils/README.md
  packages/gatsby-plugin-manifest/README.md
  packages/gatsby-plugin-mdx/README.md
  packages/gatsby-plugin-netlify/README.md
  packages/gatsby-plugin-sharp/README.md
  packages/gatsby-plugin-styletron/README.md
  packages/gatsby-remark-images-contentful/README.md
  packages/gatsby-source-shopify/README.md
  packages/gatsby-transformer-sharp/README.md
  packages/gatsby/README.md
  starters/README-template.md
  starters/README.md
  starters/blog/README.md
  starters/default/README.md
  starters/hello-world/README.md
  themes/gatsby-starter-blog-theme-core/README.md
  themes/gatsby-starter-blog-theme/README.md
  themes/gatsby-starter-notes-theme/README.md
  themes/gatsby-starter-theme-workspace/README.md
  themes/gatsby-starter-theme-workspace/gatsby-theme-minimal/README.md
  themes/gatsby-starter-theme/README.md
  themes/gatsby-theme-blog-core/README.md
  themes/gatsby-theme-blog/README.md
  themes/gatsby-theme-notes/README.md
  www/gatsby-config.js
Labels: bot: merge on green

#17707 docs(blog): Sharing the Gatsby Love with Content Creators (Evie Magazine)
  docs/blog/2019-09-18-delicious-simplicity-case-study-part2/index.md
Labels: bot: merge on green, topic: blogpost, 🎯 Marketing

#17717 chore(showcase): Add Fifteen Seconds Istanbul
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#17723 fix(babel-preset-gatsby-package): Add corejs to config
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/index.js
  packages/babel-preset-gatsby-package/package.json
  yarn.lock
Labels: bot: merge on green

#17548 docs: Gazette September, 2019
  docs/blog/2019-09-11-gazette-september/2019-09-1308.05.19.gif
  docs/blog/2019-09-11-gazette-september/gatsby-theme-novela-hero.jpg
  docs/blog/2019-09-11-gazette-september/ghost.org_.png
  docs/blog/2019-09-11-gazette-september/index.mdx
Labels: topic: blogpost

#17590 feat(gatsby-plugin-offline): "Magic" JS detection to make sites function correctly when JS is disabled retroactively
  packages/gatsby-plugin-offline/src/gatsby-browser.js
  packages/gatsby-plugin-offline/src/gatsby-ssr.js
  packages/gatsby-plugin-offline/src/sw-append.js
Labels: bot: merge on green

#17673 chore(gatsby-plugin-typography): tweak readme for clarity
  docs/docs/typography-js.md
Labels: status: awaiting reviewer response, type: documentation

#17735 fix(gatsby): add timeout so fetching API info doesn't fail on very slow connections
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/validate.js
  packages/gatsby/src/bootstrap/load-plugins/index.js
  packages/gatsby/src/bootstrap/load-plugins/validate.js
  packages/gatsby/src/utils/__tests__/get-latest-apis.js
  packages/gatsby/src/utils/get-latest-apis.js
Labels: bot: merge on green

#17755 docs: incorporate blog content (sept 2019 review)
  docs/docs/adding-comments.md
  docs/docs/content-and-data.md
  docs/docs/creating-a-sitemap.md
  docs/docs/introducing-graphiql.md
  docs/docs/sourcing-content-and-data.md
  docs/docs/sourcing-from-hosted-services.md
  www/gatsby-node.js
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green, type: documentation

#17769 chore(showcase): Added spon.io to showcase
  docs/sites.yml
Labels: topic: showcase

#17770 chore(starters): add gatsby-starter-typescript-deluxe
  docs/starters.yml
Labels: bot: merge on green

#17785 chore(docs): Fix typo
  docs/docs/gatsby-in-the-enterprise.md
Labels: bot: merge on green

#17801 docs: Update authentication-tutorial.md
  docs/tutorial/authentication-tutorial.md
Labels: type: documentation

#17791 chore(starters): add gatsby-wordpress-typescript-blog-boilerplate
  docs/starters.yml
Labels: bot: merge on green

#17805 chore(docs): Fix typos
  docs/blog/2019-07-15-theme-jam-contest/index.md
  docs/sites.yml
  docs/starters.yml
Labels: bot: merge on green, type: documentation

#17794 Docs: updated month and contributors count
  docs/contributing/community.md
Labels: type: documentation

#17442 feat(gatsby-plugin-netlify-cms): new option customizeWebpackConfig
  packages/gatsby-plugin-netlify-cms/README.md
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
Labels: bot: merge on green

#17820 chore(showcase): Add Appes
  docs/sites.yml
Labels: topic: showcase

#17823 chore(docs): Corrected case of JavaScript and TypeScript
  docs/blog/2019-06-26-live-preview-for-drupal/index.md
  docs/sites.yml
  docs/starters.yml
Labels: type: documentation

#17589 docs: layer model interactive component
  docs/docs/building-with-components.md
  docs/docs/gatsby-lifecycle-apis.md
  docs/docs/querying-with-graphql.md
  www/src/assets/icons/layer-icon.js
  www/src/components/layer-model/index.js
  www/src/components/layer-model/layer-content-sections.js
  www/src/components/layer-model/layer-model.js
Labels: type: documentation

#17803 Update 'Adding a local font' in recipes.md
  docs/docs/recipes.md
Labels: type: documentation

#17833 chore(starters): update gatsby-wordpress-typescript-scss-blog
  docs/starters.yml
Labels: bot: merge on green

#17516 docs: graphql api page and other incremental improvements
  docs/docs/creating-slugs-for-pages.md
  docs/docs/glossary.md
  docs/docs/graphql-api.md
  docs/docs/graphql-concepts.md
  docs/docs/graphql-reference.md
  docs/docs/images/basic-query.png
  docs/docs/running-queries-with-graphiql.md
  docs/docs/schema-customization.md
  packages/gatsby-image/README.md
  packages/gatsby-source-contentful/src/fragments.js
  packages/gatsby-transformer-sharp/src/fragments.js
  www/gatsby-node.js
  www/package.json
  www/src/components/api-reference/doc-block.js
  www/src/components/api-reference/doc-static-queries.js
  www/src/components/api-reference/index.js
  www/src/data/sidebars/doc-links.yaml
  www/src/pages/docs/node-apis.js
  www/src/pages/docs/node-model.js
Labels: bot: merge on green, type: documentation

#17834 chore(docs): Update awesome gatsby
  docs/docs/awesome-gatsby.md
Labels: bot: merge on green, type: documentation

#17708 [docs] New contributing doc on How to Open a Pull Request
  docs/contributing/docs-contributions.md
  docs/contributing/docs-templates.md
  docs/contributing/how-to-contribute.md
  docs/contributing/how-to-file-an-issue.md
  docs/contributing/how-to-open-a-pull-request.md
  docs/contributing/managing-pull-requests.md
  docs/contributing/site-showcase-submissions.md
  docs/docs/mdx/index.md
  www/src/components/guide-list.js
  www/src/data/sidebars/contributing-links.yaml
Labels: type: documentation

#17412 fix(gatsby): remove 404 pagedata logic on client side pages
  packages/gatsby/cache-dir/__tests__/__snapshots__/dev-loader.js.snap
  packages/gatsby/cache-dir/__tests__/__snapshots__/loader.js.snap
  packages/gatsby/cache-dir/__tests__/dev-loader.js
  packages/gatsby/cache-dir/__tests__/find-path.js
  packages/gatsby/cache-dir/__tests__/loader.js
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/cache-dir/find-path.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/src/bootstrap/__tests__/__snapshots__/requires-writer.js.snap
  packages/gatsby/src/bootstrap/__tests__/requires-writer.js
  packages/gatsby/src/bootstrap/requires-writer.js
Labels: bot: merge on green

#17869 chore(showcase): Add Global Citizen Foundation
  docs/sites.yml
Labels: topic: showcase

#17874 chore(showcase): Add Intern
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#17877 test(babel-preset-gatsby): create custom snapshot serializer
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/dependencies.js
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/utils/path-serializer.js
Labels: bot: merge on green

#17790 Reference guide on how to upgrade Gatsby and its dependencies for minor and patch releases
  docs/docs/upgrade-gatsby-and-dependencies.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#17884 fix(core): Use present tense for telemetry message
  packages/gatsby-telemetry/src/showAnalyticsNotification.js
Labels: bot: merge on green

#17878 chore(showcase): Remove BetterDocs
  docs/sites.yml
Labels: topic: showcase

#17881 chore(starters): add Blogerist
  docs/starters.yml
Labels: bot: merge on green

#17574 fix(gatsby-source-contentful): Allow proxy to be passed in to contentful client
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/src/__tests__/fetch.js
  packages/gatsby-source-contentful/src/fetch.js
  packages/gatsby-source-contentful/src/plugin-options.js
Labels: status: awaiting author response

#17888 chore(showcase): Add afexnigeria.com to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#17901 chore(starters): gatsby-wordpress-typescript-scss-blog
  docs/starters.yml
Labels: bot: merge on green

#17897 docs: add leading slash to img
  docs/docs/static-folder.md
Labels: bot: merge on green

#17732 blog: update graphiql improvements blog post with code exporter section
  docs/blog/2019-06-03-integrating-graphiql-explorer/graphiql-exporter-demo.mp4
  docs/blog/2019-06-03-integrating-graphiql-explorer/index.md
Labels: topic: blogpost
