Repository gatsbyjs/gatsby, pull requests merged in 2019-07, with the labels that each got.

#15266 [www] sites - add AwesomeDocs website
  docs/sites.yml
Labels: topic: showcase

#15171 chore(showcase): Update March and Ash details
  docs/sites.yml
Labels: topic: showcase

#15250 chore(showcase): Update sites.yml
  docs/sites.yml
Labels: topic: showcase

#15264 chore(sites): - add prism lang website
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#15263 chore(sites): sites - add traction.one
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#15260 chore(showcase): Add APIs You Won't Hate
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#15230 chore(showcase): Add majorleagueeating.com
  docs/sites.yml
Labels: topic: showcase

#15155 chore(starters): add gatsby-starter-act-blog
  docs/starters.yml
Labels: bot: merge on green

#15138 chore(starters): Added TailwindPlay - GatsbyJS Tailwind Starter
  docs/starters.yml
Labels: bot: merge on green

#15269 feat(gatsby): Add gatsby-dependents util
  packages/gatsby/package.json
  packages/gatsby/src/utils/gatsby-dependents.js
  yarn.lock
Labels: bot: merge on green

#15179 feat(gatsby): Handle duplicated fragment definitions
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/utils/webpack.config.js
Labels: bot: merge on green

#15283 fix(www): updated copy on webinar banner
  www/src/components/banner.js
Labels: bot: merge on green

#15243 gatsby-theme-blog: Mdx -> BlogPost
  themes/gatsby-theme-blog/gatsby-node.js
  themes/gatsby-theme-blog/src/components/post-footer-content.js
  themes/gatsby-theme-blog/src/components/post.js
  themes/gatsby-theme-blog/src/components/posts.js
  themes/gatsby-theme-blog/src/templates/post.js
Labels: topic: themes

#14596 feat(themes): add custom toggle switch component for blog theme
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-blog/src/components/layout.js
  themes/gatsby-theme-blog/src/components/switch.js
  themes/gatsby-theme-blog/src/components/toggle.css
  themes/gatsby-theme-blog/src/components/toggle.js
Labels: topic: themes

#15215 feat(themes): Notes theme header
  themes/gatsby-starter-theme/src/gatsby-theme-blog/components/header.js
  themes/gatsby-starter-theme/src/gatsby-theme-notes/components/layout.js
  themes/gatsby-theme-blog/gatsby-config.js
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-blog/src/components/bio.js
  themes/gatsby-theme-blog/src/components/header.js
  themes/gatsby-theme-blog/src/components/layout.js
  themes/gatsby-theme-blog/src/components/post.js
  themes/gatsby-theme-blog/src/components/posts.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/index.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/styles.js
  themes/gatsby-theme-blog/src/gatsby-theme-ui/typography.js
  themes/gatsby-theme-notes/gatsby-config.js
  themes/gatsby-theme-notes/gatsby-node.js
  themes/gatsby-theme-notes/package.json
  themes/gatsby-theme-notes/src/components/breadcrumbs.js
  themes/gatsby-theme-notes/src/components/layout.js
  themes/gatsby-theme-notes/src/components/note.js
  themes/gatsby-theme-notes/src/components/notes.js
  themes/gatsby-theme-notes/src/templates/note.js
  themes/gatsby-theme-notes/src/templates/notes.js
Labels: topic: themes

#15271 chore(showcase): Add arnondora.in.th
  docs/sites.yml
Labels: topic: showcase

#15307 fix(themes): normalize plugin entries before merging plugin arrays
  packages/gatsby/src/utils/merge-gatsby-config.js
Labels: topic: themes

#13471 feat(gatsby-plugin-manifest): add i18n, localization
  packages/gatsby-plugin-manifest/README.md
  packages/gatsby-plugin-manifest/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-manifest/src/__tests__/__snapshots__/gatsby-ssr.js.snap
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-ssr.js
Labels: status: awaiting author response, topic: plugins, type: feature or enhancement

#15295 feat(gatsby): support symlinked directories
  packages/gatsby/src/utils/get-static-dir.js
Labels: type: feature or enhancement

#15308 feat(gatsby): Switch to name based package filtering for speed
  packages/gatsby/src/utils/gatsby-dependents.js
Labels: bot: merge on green

#15318 fix(gatsby): Exclude gatsby itself in gatsby-dependents
  packages/gatsby/src/utils/gatsby-dependents.js
Labels: bot: merge on green, topic: themes

#15284 feat(gatsby): enable babel in deps
  e2e-tests/development-runtime/cypress/integration/functionality/queries-in-packages.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/src/pages/queries-in-packages.js
  e2e-tests/production-runtime/cypress/integration/queries-in-packages.js
  e2e-tests/production-runtime/gatsby-config.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/components/bio.js
  e2e-tests/production-runtime/src/components/static-query/exported-variable-query.js
  e2e-tests/production-runtime/src/pages/queries-in-packages.js
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.js.snap
  packages/gatsby/src/utils/__tests__/webpack-utils.js
  packages/gatsby/src/utils/__tests__/webpack.config.js
  packages/gatsby/src/utils/gatsby-dependents.js
  packages/gatsby/src/utils/webpack-utils.js
  packages/gatsby/src/utils/webpack.config.js
Labels: bot: merge on green

#15325 chore(themes): Add LICENSE, .gitignore, .prettierrc for theme starters
  themes/gatsby-starter-blog-theme/.gitignore
  themes/gatsby-starter-blog-theme/.prettierrc
  themes/gatsby-starter-blog-theme/LICENSE
  themes/gatsby-starter-notes-theme/.gitignore
  themes/gatsby-starter-notes-theme/.prettierrc
  themes/gatsby-starter-notes-theme/LICENSE
  themes/gatsby-starter-theme/.gitignore
  themes/gatsby-starter-theme/.prettierrc
  themes/gatsby-starter-theme/LICENSE
Labels: bot: merge on green, topic: themes

#15144 feat(gatsby): Make __experimentalThemes part of plugin APIs
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/bootstrap/load-themes/index.js
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/gatsby-node.js
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/utils/get-static-dir.js
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: themes

#15324 chore(themes): Add lock files for theme starters
  .gitignore
  themes/gatsby-starter-blog-theme/package-lock.json
  themes/gatsby-starter-notes-theme/package-lock.json
  themes/gatsby-starter-theme/package-lock.json
Labels: bot: merge on green, topic: themes

#15331 fix(gatsby): Default to empty arrays in load-themes
  packages/gatsby/src/bootstrap/load-themes/index.js
Labels: bot: merge on green

#15323 chore(scripts): mirror theme starters to independent repos and add theme packages to lerna
  .circleci/config.yml
  lerna.json
  renovate.json
  scripts/clone-and-validate-theme-starters.sh
Labels: bot: merge on green, topic: themes

#15333 feat(themes): Update theme-ui plugin
  themes/gatsby-starter-blog-theme/gatsby-config.js
  themes/gatsby-starter-blog-theme/src/gatsby-theme-blog/gatsby-theme-ui/colors.js
  themes/gatsby-starter-notes-theme/gatsby-config.js
  themes/gatsby-starter-theme/gatsby-config.js
  themes/gatsby-theme-blog/gatsby-config.js
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-blog/src/gatsby-plugin-theme-ui/colors.js
  themes/gatsby-theme-blog/src/gatsby-plugin-theme-ui/components.js
  themes/gatsby-theme-blog/src/gatsby-plugin-theme-ui/index.js
  themes/gatsby-theme-blog/src/gatsby-plugin-theme-ui/prism.js
  themes/gatsby-theme-blog/src/gatsby-plugin-theme-ui/styles.js
  themes/gatsby-theme-blog/src/gatsby-plugin-theme-ui/typography.js
  themes/gatsby-theme-notes/gatsby-config.js
  themes/gatsby-theme-notes/package.json
  themes/gatsby-theme-notes/src/gatsby-plugin-theme-ui/index.js
Labels: topic: themes

#15342 feat: add more details for accessibility testing
  docs/docs/making-your-site-accessible.md
Labels: type: documentation

#15360 feat(docs): themes launch docs updates
  docs/docs/themes.md
  docs/docs/themes/building-themes.md
  docs/docs/themes/using-multiple-gatsby-themes.md
  docs/tutorial/using-multiple-themes-together.md
  themes/gatsby-starter-blog-theme/README.md
  themes/gatsby-starter-notes-theme/README.md
  themes/gatsby-starter-theme/README.md
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green

#15364 chore(gatsby-theme-*): Bump dependencies of themes
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-notes/package.json
Labels: bot: merge on green

#15355 feat(blog): themes are stable
  docs/blog/2019-07-03-announcing-stable-release-gatsby-themes/index.md
Labels: bot: merge on green, topic: blogpost, topic: themes

#15363 feat(docs): themes no longer experimental
  docs/docs/themes/api-reference.md
  docs/docs/themes/conventions.md
Labels: bot: merge on green, topic: themes, type: documentation

#15330 feat(blog): Using Themes for Distributed Docs
  docs/blog/2019-07-03-using-themes-for-distributed-docs/images/code-blocks.gif
  docs/blog/2019-07-03-using-themes-for-distributed-docs/images/many-to-one.png
  docs/blog/2019-07-03-using-themes-for-distributed-docs/images/mdx-components.png
  docs/blog/2019-07-03-using-themes-for-distributed-docs/images/one-to-one.png
  docs/blog/2019-07-03-using-themes-for-distributed-docs/images/project-panel.gif
  docs/blog/2019-07-03-using-themes-for-distributed-docs/images/shared-content.png
  docs/blog/2019-07-03-using-themes-for-distributed-docs/index.md
  docs/blog/author.yaml
  docs/blog/avatars/trevor-blades.jpg
Labels: bot: merge on green, topic: blogpost, topic: themes

#15352 fix(gatsby): regression ~ show non structured grapqhl errors
  packages/gatsby/src/bootstrap/__tests__/__snapshots__/graphql-runner.js.snap
  packages/gatsby/src/bootstrap/__tests__/graphql-runner.js
  packages/gatsby/src/bootstrap/graphql-runner.js
  packages/gatsby/src/bootstrap/index.js
Labels: bot: merge on green

#15236 docs: misc feedback improvements
  docs/contributing/docs-contributions.md
  docs/contributing/docs-templates.md
  docs/contributing/gatsby-style-guide.md
  docs/docs/gatsby-link.md
  docs/docs/quick-start.md
  docs/docs/recipes.md
  docs/docs/testing-components-with-graphql.md
Labels: topic: feedback, type: documentation

#15376 feat: updates to the accessibility docs page
  docs/docs/making-your-site-accessible.md
Labels: type: documentation

#15290 feat(blog): Customizing Styles in Gatsby Themes with Theme UI
  docs/blog/2019-07-03-announcing-stable-release-gatsby-themes/index.md
  docs/blog/2019-07-03-customizing-styles-in-gatsby-themes-with-theme-ui/index.md
Labels: topic: blogpost, topic: themes

#15238 Update Debugging HTML Builds Page
  docs/docs/debugging-html-builds.md
Labels: bot: merge on green, type: documentation

#15197 docs: explain missing file loading step for schema mapping
  docs/docs/gatsby-config.md
Labels: type: documentation

#15390 Add placeholder page to fix 404 in themes docs
  docs/docs/themes/what-are-gatsby-themes.md
Labels: bot: merge on green

#15389 fix(docs): Removing theme transpilation section
  docs/docs/themes/api-reference.md
Labels: topic: themes, type: documentation

#14816 Fix blur-up preview image not working on initial page load
  packages/gatsby-remark-images/.gitignore
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/constants.js
  packages/gatsby-remark-images/src/gatsby-browser.js
  packages/gatsby-remark-images/src/gatsby-ssr.js
  packages/gatsby-remark-images/src/index.js
Labels: status: awaiting author response

#15418 fix(docs): Fix broken link on docs contribution page
  docs/contributing/docs-contributions.md
Labels: bot: merge on green, type: documentation

#15413 fix(docs): fix link to Contentful Marketplace
  docs/docs/gatsby-vendor-partnership.md
Labels: type: documentation

#15417 feat(docs): theme doc updates
  docs/docs/themes/building-themes.md
  docs/docs/themes/what-are-gatsby-themes.md
Labels: topic: themes, type: documentation

#15116 chore(starters): add bunch of starters
  docs/starters.yml
Labels: effort: low, status: awaiting reviewer response

#15427 chore(showcase): add easyfloh
  docs/sites.yml
Labels: topic: showcase

#15414 fix(docs): update LernaJS link from https://lernajs.io/ to https://lerna.js.org/
  docs/contributing/setting-up-your-local-dev-environment.md
Labels: bot: merge on green, type: documentation

#14994 fix(gatsby-source-contentful): include locale in asset cache key
  packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js
  packages/gatsby-source-contentful/src/download-contentful-assets.js
Labels: bot: merge on green

#15422 chore(showcase): Add KingsDesign to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#15455 fix(docs): Fix more broken blog post links
  docs/blog/2017-10-17-building-i18n-with-gatsby/index.md
  docs/blog/2019-04-02-behind-the-scenes-what-makes-gatsby-great/index.md
Labels: type: documentation

#15454 fix(docs): Fix broken link on site showcase blog post
  docs/blog/2018-07-20-why-we-built-the-site-showcase/index.md
Labels: type: documentation

#15437 feat(showcase): Add HomeAlarmReport.com
  docs/sites.yml
Labels: topic: showcase

#15467 chore(showcase): Add onramp and write speak code to showcase
  docs/sites.yml
Labels: topic: showcase

#15472 chore(showcase): Removing F1vision site from showcase
  docs/sites.yml
Labels: topic: showcase

#15468 chore(showcase): Add Venus Lover to showcase
  docs/sites.yml
Labels: topic: showcase

#14630 feat(gatsby-source-drupal): added preview feature
  packages/gatsby-source-drupal/.gitignore
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/webhook-insert.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/webhook-update.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/normalize.js
  packages/gatsby-source-drupal/src/utils.js
  yarn.lock
Labels: bot: merge on green

#15492 chore(showcase): Added Cosmotory to showcase
  docs/sites.yml
Labels: topic: showcase

#15517 fix(gatsby): Fix support for yarn workspaces in gatsby-dependents
  packages/gatsby/package.json
  packages/gatsby/src/utils/gatsby-dependents.js
  yarn.lock
Labels: topic: themes

#15079 [docs][recipes] Added a recipe for StaticQuery and useStaticQuery
  docs/docs/recipes.md
Labels: topic: recipes

#15296 feat(docs): Add Working With Images in Markdown page
  docs/docs/working-with-images-in-markdown.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: images/media, type: documentation

#15478 chore(showcase): Add danieljs.tech
  docs/sites.yml
Labels: topic: showcase

#15526 chore(showcase): Add mojo.is
  docs/sites.yml
Labels: topic: showcase

#15457 fix(gatsby): restore client-only-paths behaviour
  e2e-tests/development-runtime/cypress/integration/functionality/accessibility.js
  e2e-tests/development-runtime/cypress/integration/functionality/client-only-paths.js
  e2e-tests/development-runtime/cypress/integration/functionality/paths.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/pages/client-only-paths.js
  e2e-tests/development-runtime/src/pages/paths.js
  e2e-tests/production-runtime/cypress/integration/accessibility.js
  e2e-tests/production-runtime/cypress/integration/client-only-paths.js
  e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js
  e2e-tests/production-runtime/cypress/integration/paths.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/src/pages/client-only-paths.js
  e2e-tests/production-runtime/src/pages/paths.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/root.js
  packages/gatsby/src/utils/reach-router-add-basecontext-export-loader.js
  packages/gatsby/src/utils/webpack.config.js
Labels: status: awaiting reviewer response

#15452 fix(gatsby-plugin-mdx): Use babel plugin to remove export keyword
  packages/gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords/index.js
  packages/gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords/index.test.js
  packages/gatsby-plugin-mdx/utils/gen-mdx.js
Labels: bot: merge on green

#15335 [docs] Added 'excerpt' info to Blog & Website Contributions page
  docs/contributing/blog-and-website-contributions.md
Labels: type: documentation

#15409 chore(gatsby-source-filesystem): Deprecate fields
  packages/gatsby-source-filesystem/index.d.ts
  packages/gatsby-source-filesystem/src/gatsby-node.js
Labels: bot: merge on green

#15587 docs: Add note that createSchemaCustomization is available only in ^2.12
  docs/docs/schema-customization.md
Labels: bot: merge on green, type: documentation

#15522 [docs] Add note about resolver execution order
  docs/docs/schema-customization.md
Labels: bot: merge on green

#15521 chore(gatsby-plugin-mdx): Remove unused _PARENT frontmatter field
  packages/gatsby-plugin-mdx/utils/create-mdx-node.js
Labels: bot: merge on green

#15515 feat(gatsby): Make builtin field extensions wrap resolvers
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/extensions/__tests__/field-extensions.js
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/resolvers.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/__tests__/date.js
  packages/gatsby/src/schema/types/date.js
Labels: bot: merge on green

#15590 chore(showcase):Updated main_url of Cosmotory
  docs/sites.yml
Labels: bot: merge on green

#15518 fix(gatsby-transformer-remark): Fix transformer-remark when using assetPrefix
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: status: awaiting author response

#15525 chore(starters): add gatsby-tailwind-serif
  docs/starters.yml
Labels: status: awaiting author response

#15527 chore(showcase): Add Armorblox
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#15621 chore(gatsby-plugin-feed): bump lodash.merge min. version to 4.6.2
  packages/gatsby-plugin-feed/package.json
Labels: bot: merge on green

#15165 feat(www): added breadcrumb to docs
  docs/docs/add-custom-webpack-config.md
  docs/docs/babel-plugin-macros.md
  docs/docs/eslint.md
  www/src/components/docs-breadcrumb.js
  www/src/components/sidebar/sidebar.js
  www/src/data/sidebars/doc-links.yaml
  www/src/data/sidebars/tutorial-links.yaml
  www/src/pages/docs/index.js
  www/src/templates/template-docs-markdown.js
  www/src/utils/sidebar/get-active-item-parents.js
  www/src/utils/sidebar/get-active-item.js
  www/src/utils/sidebar/item-list.js
Labels: bot: merge on green, type: documentation

#15579 feat: blog post on accessible client-side routing research
  docs/blog/2019-07-11-user-testing-accessible-client-routing/images/magnification-a11y.png
  docs/blog/2019-07-11-user-testing-accessible-client-routing/index.md
Labels: topic: blogpost

#15642 chore(www): update banner text to point users to Gatsby Preview
  www/src/components/__tests__/banner.js
  www/src/components/banner.js
Labels: bot: merge on green, 🎯 Marketing

#15643 Fix(www): uppercase breadcrumbTitles and change separator to ChevronLeft
  www/src/components/docs-breadcrumb.js
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green

#15640 feat(themes): Add a starter for theme development
  .gitignore
  scripts/clone-and-validate-theme-starters.sh
  themes/gatsby-starter-theme-workspace/.gitignore
  themes/gatsby-starter-theme-workspace/README.md
  themes/gatsby-starter-theme-workspace/example/README.md
  themes/gatsby-starter-theme-workspace/example/gatsby-config.js
  themes/gatsby-starter-theme-workspace/example/package.json
  themes/gatsby-starter-theme-workspace/example/src/pages/index.js
  themes/gatsby-starter-theme-workspace/gatsby-theme-minimal/README.md
  themes/gatsby-starter-theme-workspace/gatsby-theme-minimal/gatsby-config.js
  themes/gatsby-starter-theme-workspace/gatsby-theme-minimal/index.js
  themes/gatsby-starter-theme-workspace/gatsby-theme-minimal/package.json
  themes/gatsby-starter-theme-workspace/package-lock.json
  themes/gatsby-starter-theme-workspace/package.json
  themes/package.json
Labels: status: blocked, topic: themes

#14272 feat(gatsby-plugin-sass): add option to enable resolve-url-loader
  packages/gatsby-plugin-sass/README.md
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: bot: merge on green

#15384 feat(gatsby-plugin-sharp): enable gatsby cloud processing
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/process-file.js.snap
  packages/gatsby-plugin-sharp/src/__tests__/process-file.js
  packages/gatsby-plugin-sharp/src/process-file.js
  yarn.lock
Labels: bot: merge on green

#15656 chore(showcase): Add marcelhauri.ch to showcase
  docs/sites.yml
Labels: topic: showcase

#15326 chore(starters): add gatsby-starter-typescript-graphql
  docs/starters.yml
Labels: status: awaiting author response

#14839 docs: update one-way relational note for clarity
  packages/gatsby-source-contentful/README.md
Labels: bot: merge on green, type: documentation

#15657 fix(babel-preset-gatsby): Add babel-plugin-dynamic-import-node for tests
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/index.js
  packages/babel-preset-gatsby-package/package.json
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/index.js
Labels: bot: merge on green

#15567 chore(showcase): Added projektmanagementblog.de
  docs/sites.yml
Labels: topic: showcase

#15288 docs(www): Added a link to "Adding an SEO Component"
  docs/docs/seo.md
Labels: bot: merge on green

#15309 Add REPL documentation to the Gatsby Docs
  docs/docs/gatsby-cli.md
  docs/docs/gatsby-repl.md
  packages/gatsby-cli/src/create-cli.js
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green, type: documentation

#15510 feat(gatsby-core-utils): add url resolve
  packages/gatsby-core-utils/.babelrc
  packages/gatsby-core-utils/.gitignore
  packages/gatsby-core-utils/CHANGELOG.md
  packages/gatsby-core-utils/README.md
  packages/gatsby-core-utils/index.d.ts
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/__tests__/__snapshots__/create-content-digest.js.snap
  packages/gatsby-core-utils/src/__tests__/cpu-core-count.js
  packages/gatsby-core-utils/src/__tests__/create-content-digest.js
  packages/gatsby-core-utils/src/__tests__/path.js
  packages/gatsby-core-utils/src/__tests__/physical-cpu-count.js
  packages/gatsby-core-utils/src/__tests__/url.js
  packages/gatsby-core-utils/src/cpu-core-count.js
  packages/gatsby-core-utils/src/create-content-digest.js
  packages/gatsby-core-utils/src/index.js
  packages/gatsby-core-utils/src/path.js
  packages/gatsby-core-utils/src/physical-cpu-count.js
  packages/gatsby-core-utils/src/url.js
Labels: bot: merge on green

#15370 fix(gatsby-theme-blog): drop path.join to support windows
  themes/gatsby-theme-blog/gatsby-node.js
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-notes/gatsby-node.js
  themes/gatsby-theme-notes/package.json
Labels: bot: merge on green

#15649 feat(gatsby-dev-cli): add initial support for handling yarn workspaces
  packages/gatsby-dev-cli/package.json
  packages/gatsby-dev-cli/src/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
  packages/gatsby-dev-cli/src/watch.js
  yarn.lock
Labels: bot: merge on green

#15665 fix(actions): fix PR bot action via await on each report call
  .github/actions/high-priority-prs/src/filter.js
  .github/actions/high-priority-prs/src/index.js
  .github/actions/high-priority-prs/src/process-data.js
Labels: bot: merge on green

#14987 feat(babel-preset-gatsby): add babel-plugin-transform-react-remove-prop-types for production builds
  packages/babel-preset-gatsby/README.md
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/index.js
  yarn.lock
Labels: bot: merge on green

#15572 chore(scripts): clean up CI scripts for starters
  .circleci/config.yml
  lerna.json
  renovate.json
  scripts/clone-and-validate.sh
  scripts/publish-starters.sh
  scripts/validate-starters.sh
Labels: bot: merge on green

#15637 chore(themes): Add some basic end to end tests for themes
  .circleci/config.yml
  e2e-tests/themes/gatsby-theme-about/README.md
  e2e-tests/themes/gatsby-theme-about/gatsby-config.js
  e2e-tests/themes/gatsby-theme-about/index.js
  e2e-tests/themes/gatsby-theme-about/package.json
  e2e-tests/themes/gatsby-theme-about/src/components/date.js
  e2e-tests/themes/gatsby-theme-about/src/components/time.js
  e2e-tests/themes/gatsby-theme-about/src/pages/about.js
  e2e-tests/themes/gatsby-theme-about/src/pages/contact.js
  e2e-tests/themes/package.json
  e2e-tests/themes/production-runtime/.gitignore
  e2e-tests/themes/production-runtime/README.md
  e2e-tests/themes/production-runtime/cypress.json
  e2e-tests/themes/production-runtime/cypress/fixtures/example.json
  e2e-tests/themes/production-runtime/cypress/integration/components.js
  e2e-tests/themes/production-runtime/cypress/integration/pages.js
  e2e-tests/themes/production-runtime/cypress/integration/site-metadata.js
  e2e-tests/themes/production-runtime/cypress/plugins/index.js
  e2e-tests/themes/production-runtime/cypress/support/index.js
  e2e-tests/themes/production-runtime/gatsby-browser.js
  e2e-tests/themes/production-runtime/gatsby-config.js
  e2e-tests/themes/production-runtime/package.json
  e2e-tests/themes/production-runtime/src/gatsby-theme-about/components/time.js
  e2e-tests/themes/production-runtime/src/pages/contact.js
  e2e-tests/themes/production-runtime/src/pages/index.js
  e2e-tests/themes/production-runtime/src/pages/shadowed.js
Labels: bot: merge on green

#15674 chore: and CoC link to repo
  CODE_OF_CONDUCT.md
Labels: type: documentation

#14537 fix(gatsby): Add NodeInput for createNode function types
  packages/gatsby/index.d.ts
Labels: status: awaiting reviewer response

#13985 feat(gatsby): add prefetchPathname to programmatically prefetch (#8122)
  packages/gatsby/cache-dir/gatsby-browser-entry.js
  packages/gatsby/index.d.ts
Labels: status: awaiting author response

#15677 chore(showcase): add Anthony Boyd Graphics
  docs/sites.yml
Labels: topic: showcase

#15681 chore(starters): add gatsby-all-in
  docs/starters.yml
Labels: bot: merge on green

#15721 fix(blog): correct GraphQL SDL syntax error
  docs/blog/2019-03-04-new-schema-customization/index.md
Labels: topic: blogpost, type: bug

#15659 chore(telemetry): collect bootstrap times
  packages/gatsby-cli/src/reporter/index.js
Labels: bot: merge on green

#15714 fix(babel-preset-gatsby): add @babel/plugin-transform-spread as dependencies
  packages/babel-preset-gatsby/package.json
  yarn.lock
Labels: bot: merge on green

#15727 chore(telemetry): normalize starter name
  packages/gatsby-cli/src/init-starter.js
Labels: bot: merge on green

#15695 docs(gatsby-source-wordpress): add note about limitation of pagination in WordPress.com API
  packages/gatsby-source-wordpress/README.md
Labels: status: awaiting reviewer response, type: documentation

#15743 feat(gatsby-cypress): Add ability to pass in options in getTestElement
  packages/gatsby-cypress/src/commands.js
Labels: bot: merge on green

#15757 fix(docs): add note about theme plugin naming
  docs/docs/naming-a-plugin.md
Labels: bot: merge on green, type: documentation

#15027 Create gatsby-image-tutorial
  docs/blog/2018-05-31-open-sourcing-gatsby-workshops/index.md
  docs/tutorial/gatsby-image-tutorial/ErrorMessage.png
  docs/tutorial/gatsby-image-tutorial/index.md
  docs/tutorial/wordpress-image-tutorial.md
  docs/tutorial/wordpress-source-plugin-tutorial.md
  www/gatsby-node.js
  www/src/data/sidebars/tutorial-links.yaml
Labels: bot: merge on green, status: awaiting author response, topic: images/media, type: documentation

#15204 docs: expand and clarify add algolia search
  docs/docs/adding-search-with-algolia.md
  docs/docs/images/algolia-api-keys.png
Labels: type: documentation

#15769 feat(blog): add Theme Jam blog post
  docs/blog/2019-07-15-theme-jam-contest/index.md
Labels: bot: merge on green

#15776 chore(starters): Fix "npm audit" errors for starters
  starters/blog/package-lock.json
  themes/gatsby-starter-blog-theme/package-lock.json
  themes/gatsby-starter-notes-theme/package-lock.json
  themes/gatsby-starter-theme/package-lock.json
Labels: bot: merge on green

#15762 fix(gatsby): fix matchpath prioritisation
  packages/gatsby/cache-dir/__tests__/__snapshots__/dev-loader.js.snap
  packages/gatsby/cache-dir/__tests__/__snapshots__/loader.js.snap
  packages/gatsby/cache-dir/__tests__/dev-loader.js
  packages/gatsby/cache-dir/__tests__/find-path.js
  packages/gatsby/cache-dir/__tests__/loader.js
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/cache-dir/find-path.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/production-app.js
Labels: bot: merge on green

#15795 Don't use npx or yarn for installation instructions
  docs/docs/mdx/getting-started.md
Labels: bot: merge on green

#15799 chore(e2e): Sunset gatsbygram end to end tests
  .circleci/config.yml
Labels: bot: merge on green

#15791 chore(www): Switch to gatsby-design-tokens package
  www/package.json
  www/src/utils/presets.js
  www/src/utils/sidebar/indention.js
  www/src/utils/tokens/breakpoints.js
  www/src/utils/tokens/colors.js
  www/src/utils/tokens/font-sizes.js
  www/src/utils/tokens/font-weights.js
  www/src/utils/tokens/fonts.js
  www/src/utils/tokens/index.js
  www/src/utils/tokens/letter-spacings.js
  www/src/utils/tokens/line-heights.js
  www/src/utils/tokens/media-queries.js
  www/src/utils/tokens/radii.js
  www/src/utils/tokens/shadows.js
  www/src/utils/tokens/sizes.js
  www/src/utils/tokens/space.js
  www/src/utils/tokens/transition.js
  www/src/utils/tokens/z-indices.js
  www/src/utils/typography.js
Labels: bot: merge on green

#15772 fix(themes): update README for gatsby-starter-theme-workspace
  themes/gatsby-starter-theme-workspace/README.md
  themes/gatsby-starter-theme-workspace/example/package.json
Labels: bot: merge on green, type: documentation

#15668 feat(docs): building a theme tutorial
  docs/tutorial/building-a-theme.md
  docs/tutorial/images/building-a-theme-add-test-event.png
  docs/tutorial/images/building-a-theme-changed-basepath.png
  docs/tutorial/images/building-a-theme-events-listing-styling.png
  docs/tutorial/images/building-a-theme-events-page-data.png
  docs/tutorial/images/building-a-theme-events-page-markup.png
  docs/tutorial/images/building-a-theme-events-test-query.png
  docs/tutorial/images/building-a-theme-individual-event-data.png
  docs/tutorial/images/building-a-theme-individual-event-markup.png
  docs/tutorial/images/building-a-theme-override-colors.png
  docs/tutorial/images/building-a-theme-override-component.png
  docs/tutorial/images/building-a-theme-query-event-type.png
  docs/tutorial/images/building-a-theme-running-theme.png
  docs/tutorial/images/building-a-theme-theme-ui-changes.png
  www/src/data/sidebars/tutorial-links.yaml
Labels: bot: merge on green

#15822 chore(gatsby-design-tokens): Fix z-inidices naming d'ohs, bump README
  packages/gatsby-design-tokens/README.md
  packages/gatsby-design-tokens/src/z-indices.js
Labels: bot: merge on green

#15829 fix(gatsby-transformer-sharp): mark highlight/shadow duotone args as required
  packages/gatsby-transformer-sharp/src/types.js
Labels: bot: merge on green

#15608 chore(example): Migrate gatsbygram's createPages hook to async/await
  examples/gatsbygram/gatsby-node.js
Labels: bot: merge on green

#15564 feat(gatsby): pass webhook data to sourceNodes functions
  .eslintrc.json
  e2e-tests/development-runtime/cypress/integration/gatsby-preview/updating.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/api.js
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/gatsby-node.js
  e2e-tests/development-runtime/scripts/hook-with-data.js
  e2e-tests/development-runtime/scripts/webhook.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/utils/source-nodes.js
Labels: Gatsby Cloud

#15817 fix(docs): add requirement of node-sass
  docs/docs/sass.md
Labels: bot: merge on green, type: documentation

#15720 fix(gatsby): Track nodes when mutated
  packages/gatsby/src/redux/actions/public.js
Labels: bot: merge on green

#15840 Add `export default`
  docs/docs/mdx/programmatically-creating-pages.md
Labels: topic: MDX, type: documentation

#15865 chore(blog): Fix broken link and typo in card sort result blog
  docs/blog/2018-06-26-card-sort-results/index.md
Labels: type: documentation

#15858 fix(gatsby): 404 page when using path-prefix
  e2e-tests/path-prefix/cypress/integration/navigate.js
  e2e-tests/path-prefix/src/pages/index.js
  packages/gatsby/cache-dir/production-app.js
Labels: bot: merge on green

#15869 chore(showcase): Removing Devol's Dance from showcase
  docs/sites.yml
Labels: topic: showcase

#15874 chore(docs): Reformat "Hosting on Netlify" docs
  docs/docs/hosting-on-netlify.md
Labels: type: documentation

#15831 chore(docs): Update gatsby-plugin-mdx README.md to correct docs example
  packages/gatsby-plugin-mdx/README.md
Labels: topic: MDX, type: documentation

#15257 Adds local font example to recipes
  docs/docs/recipes.md
Labels: bot: merge on green, topic: recipes, type: documentation

#15886 Fix typo
  packages/gatsby-plugin-mdx/README.md
Labels: bot: merge on green

#15889 fix(gatsby-transformer-remark): Restore pathPrefix option in remark plugins
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: topic: plugins, type: bug

#15888 chore(docs): fix typo
  docs/starters.yml
Labels: bot: merge on green

#15907 fix(gatsby-cli): fix cut off text
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/reporter/reporters/ink/components/messages.js
  packages/gatsby-cli/src/reporter/reporters/ink/reporter.js
  yarn.lock
Labels: bot: merge on green

#15763 chore(gatsby-theme-blog): Use deepmerge instead lodash.merge
  themes/gatsby-starter-blog-theme/src/gatsby-theme-blog/gatsby-plugin-theme-ui/colors.js
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-blog/src/gatsby-plugin-theme-ui/index.js
Labels: bot: merge on green

#15848 chore(docs): Improve readability in environment-variables.md
  docs/docs/environment-variables.md
Labels: type: documentation

#15691 fix(gatsby-plugin-mdx): Fix graphql query examples in readme
  packages/gatsby-plugin-mdx/README.md
Labels: bot: merge on green, status: awaiting author response

#15618 feat(blog): Mediacurrent case-study
  docs/blog/2019-06-28-component-driven-drupal-development/index.md
Labels: bot: merge on green, topic: blogpost

#15913 fix(docs): Fix typos in Building a Theme tutorial
  docs/tutorial/building-a-theme.md
Labels: bot: merge on green

#15198 added few info on non-page components
  docs/docs/building-with-components.md
Labels: bot: merge on green

#15605 Docs: expand deploy recipe
  docs/docs/recipes.md
Labels: bot: merge on green, topic: recipes

#15789 fix(gatsby-theme-notes): Fix path in config
  themes/gatsby-theme-notes/gatsby-config.js
Labels: topic: themes

#15946 chore(*): fix typos
  docs/blog/2018-11-01-hacktoberfest-wrapup/index.md
  docs/blog/2018-12-17-turning-the-static-dynamic/index.md
  docs/blog/2019-07-03-using-themes-for-distributed-docs/index.md
  docs/starters.yml
  packages/gatsby-transformer-documentationjs/src/gatsby-node.js
  scripts/check-repo-fields.js
Labels: type: documentation

#15972 Revert to Hacktoverfest
  docs/blog/2018-11-01-hacktoberfest-wrapup/index.md
Labels: bot: merge on green, type: documentation

#15950 chore(showcase): Add Carbon8 Regenerative Agriculture
  docs/sites.yml
Labels: topic: showcase

#15962 chore(showcase): Add Jana Desomer website to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#15933 chore(showcase): Add portfolio of Cole Townsend
  docs/sites.yml
Labels: topic: showcase
