Repository gatsbyjs/gatsby, pull requests merged in 2019-05, with the labels that each got.

#13234 docs: Remark Plugin tutorial
  docs/docs/images/remark-ast-output.png
  docs/docs/remark-plugin-tutorial.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#13749 docs(gatsby-plugin-netlify): remove comment that states to put it last
  packages/gatsby-plugin-netlify/README.md
Labels: status: assigned, status: awaiting reviewer response, type: documentation

#13767 chore(showcase): Remove WhittleSchool from showcase
  docs/sites.yml
Labels: topic: showcase

#13753 feat(showcase) : add peintagone website
  docs/sites.yml
Labels: topic: showcase

#13758 feat(docs): Adding AST and Remark to the glossary
  docs/docs/glossary.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#13745 feat(www): update react-instantsearch to v5
  www/package.json
  www/src/components/plugin-searchbar-body.js
Labels: status: awaiting author response

#13689 chore(showcase): Add MangoART's profile to creators and some recent sites
  docs/creators/creators.yml
  docs/creators/images/mangoart.png
  docs/sites.yml
Labels: status: awaiting author response, topic: showcase

#13796 chore(starters): Fix wrong tags
  docs/starters.yml
Labels: bot: merge on green

#13771 fix(blog): Update MDX install in themes blog post
  docs/blog/2019-02-26-getting-started-with-gatsby-themes/index.md
Labels: bot: merge on green

#13716 chore(gatsby): warn about service workers running in development
  packages/gatsby/cache-dir/app.js
Labels: bot: merge on green

#13741 chore: add script to add packages to a npm team
  scripts/add-packages-to-team/index.js
  scripts/add-packages-to-team/package.json
  scripts/get-unowned-packages/index.js
Labels: status: awaiting reviewer response, type: maintenance

#13824 chore(showcase): added CSUMB website
  docs/sites.yml
Labels: bot: merge on green

#13036 refactor(gatsby-plugin-netlify-cms): major netlify-cms upgrade
  packages/gatsby-plugin-netlify-cms/.gitignore
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-netlify-cms/src/cms.js
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  packages/gatsby-plugin-netlify-cms/src/index.js
  yarn.lock
Labels: breaking change, status: awaiting author response

#13868 refactor(gatsby-plugin-netlify-cms): replace string.match with regex.test
  packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js
Labels: bot: merge on green

#13743 chore(gatsby-cli): Improve Flow annotations for reporter
  packages/gatsby-cli/src/reporter/index.js
  packages/gatsby-cli/src/reporter/types.js
Labels: bot: merge on green

#13879 chore(docs): Clarify language codename in Kentico tutorial
  docs/docs/sourcing-from-kentico-cloud.md
Labels: bot: merge on green, type: documentation

#13923 fix(www): improve feedback-widget toggle button and hover state
  www/src/components/feedback-widget/buttons.js
  www/src/components/feedback-widget/feedback-widget.js
Labels: bot: merge on green

#13943 fix(gatsby-source-drupal): limit concurrentFileRequests while downloading remote images
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  yarn.lock
Labels: bot: merge on green, type: bug

#13890 chore(docs): Add link to graphql reference on conceptual guide
  docs/docs/querying-with-graphql.md
Labels: type: documentation

#14019 chore: fix master lint issue
  packages/gatsby-plugin-google-analytics/README.md
Labels: bot: merge on green

#14009 chore(starters): add gatsby-starter-identity
  docs/starters.yml
Labels: bot: merge on green

#13096 fix(gatsby-cli): Only init git repository if no git repository exists
  packages/gatsby-cli/src/init-starter.js
Labels: bot: merge on green

#13738 [WIP] [schema] Allow registering custom field extensions
  packages/gatsby/src/schema/__tests__/kitchen-sink.js
  packages/gatsby/src/schema/__tests__/queries-file.js
  packages/gatsby/src/schema/add-field-resolvers.js
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/infer/__tests__/infer.js
  packages/gatsby/src/schema/infer/__tests__/merge-types.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/infer/index.js
  packages/gatsby/src/schema/schema-composer.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/date.js
  packages/gatsby/src/schema/types/directives.js
Labels: status: WIP

#12748 feat(gatsby): Allow awaiting API run triggered by createNode action
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby/package.json
  packages/gatsby/src/redux/__tests__/nodes.js
  packages/gatsby/src/redux/actions.js
  packages/gatsby/src/redux/index.js
  packages/gatsby/src/redux/plugin-runner.js
  packages/gatsby/src/utils/api-runner-node.js
  yarn.lock
Labels: bot: merge on green

#14035 chore(docs): More SEO Improvements
  docs/docs/first-professional-project.md
  docs/docs/graphql.md
  docs/docs/programmatically-create-pages-from-data.md
  docs/docs/sourcing-from-buttercms.md
  docs/docs/using-gatsby-image.md
  docs/docs/using-gatsby-without-graphql.md
  www/gatsby-node.js
  www/src/components/package-readme.js
  www/src/pages/blog/tags.js
  www/src/pages/contributing/events.js
  www/src/pages/contributing/index.js
  www/src/pages/contributing/stub-list.js
  www/src/pages/docs/actions.js
  www/src/pages/docs/browser-apis.js
  www/src/pages/docs/index.js
  www/src/pages/docs/node-api-helpers.js
  www/src/pages/docs/node-apis.js
  www/src/pages/docs/node-model.js
  www/src/pages/docs/ssr-apis.js
  www/src/pages/features.js
  www/src/pages/newsletter.js
  www/src/pages/plugins.js
  www/src/templates/tags.js
  www/src/templates/template-blog-list.js
  www/src/templates/template-contributor-page.js
  www/src/templates/template-creator-details.js
  www/src/views/creators/creators-header.js
  www/src/views/creators/index.js
  www/src/views/shared/sidebar.js
  www/src/views/showcase/index.js
Labels: 🎯 Marketing

#13651 fix(gatsby): compile themes through default webpack config
  packages/gatsby/src/utils/webpack.config.js
Labels: bot: merge on green, topic: themes

#14025 chore(showcase) Removing CMSbased.net from showcase
  docs/sites.yml
Labels: topic: showcase

#14028 chore(showcase): Add PygmalionPolymorph Portfolio
  docs/sites.yml
Labels: topic: showcase

#14039 test(e2e): add a Gatsby Preview e2e test
  e2e-tests/development-runtime/cypress/integration/gatsby-preview/base-functionality.js
  e2e-tests/development-runtime/cypress/integration/gatsby-preview/updating.js
  e2e-tests/development-runtime/cypress/support/commands.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/.gitignore
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/api.js
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/gatsby-node.js
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/index.js
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/package.json
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/reset.js
  e2e-tests/development-runtime/src/pages/preview.js
  e2e-tests/development-runtime/src/templates/preview-item.js
Labels: status: awaiting reviewer response

#14062 test(gatsby-source-filesystem): Fix test assertions now that createRemoteFileNode throws
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
Labels: bot: merge on green

#14061 feat(blog): Add enterprise Gatsby blog post
  docs/blog/2019-05-15-enterprise-gatsby-how-to-reduce-your-digital-total-cost-of-ownership-with-gatsby/index.md
Labels: topic: blogpost, type: documentation, 🎯 Marketing

#14066 feat(gatsby-theme-notes): Implement initial version of notes theme
  themes/gatsby-starter-theme-blog-mdx/gatsby-config.js
  themes/gatsby-starter-theme/gatsby-config.js
  themes/gatsby-starter-theme/notes/example-dir/hi.mdx
  themes/gatsby-starter-theme/notes/hello.mdx
  themes/gatsby-starter-theme/package.json
  themes/gatsby-starter-theme/posts/hello.mdx
  themes/gatsby-starter-theme/src/data/author.yml
  themes/gatsby-theme-blog-mdx/gatsby-config.js
  themes/gatsby-theme-blog-mdx/package.json
  themes/gatsby-theme-blog/package.json
  themes/gatsby-theme-notes/README.md
  themes/gatsby-theme-notes/gatsby-browser.js
  themes/gatsby-theme-notes/gatsby-config.js
  themes/gatsby-theme-notes/gatsby-node.js
  themes/gatsby-theme-notes/gatsby-ssr.js
  themes/gatsby-theme-notes/index.js
  themes/gatsby-theme-notes/package.json
  themes/gatsby-theme-notes/src/components/breadcrumb-divider.js
  themes/gatsby-theme-notes/src/components/breadcrumb-home.js
  themes/gatsby-theme-notes/src/components/breadcrumbs.js
  themes/gatsby-theme-notes/src/components/directory-list.js
  themes/gatsby-theme-notes/src/components/file-list.js
  themes/gatsby-theme-notes/src/components/layout.js
  themes/gatsby-theme-notes/src/components/note.js
  themes/gatsby-theme-notes/src/components/notes.js
  themes/gatsby-theme-notes/src/root.js
  themes/gatsby-theme-notes/src/templates/note.js
  themes/gatsby-theme-notes/src/templates/notes.js
  themes/gatsby-theme-notes/src/theme.js
  themes/gatsby-theme-notes/src/use-options.js
  themes/gatsby-theme-notes/src/use-site-metadata.js
  themes/package.json
Labels: topic: themes

#14065 feat(gatsby): cors is enabled correctly in development
  packages/gatsby/package.json
  packages/gatsby/src/commands/develop.js
  yarn.lock
Labels: Gatsby Cloud

#13774 chore(docs): Setting Up a Gatsby Site Without Gatsby New
  docs/docs/preparing-your-environment.md
  docs/docs/setting-up-gatsby-without-gatsby-new.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#14024 chore(gatsby-plugin-typescript): Types install instruction
  packages/gatsby-plugin-typescript/README.md
Labels: status: awaiting author response

#13217 feat(gatsby-image): Add support for native lazy loading
  packages/gatsby-image/README.md
  packages/gatsby-image/index.d.ts
  packages/gatsby-image/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-image/src/index.js
Labels: bot: merge on green

#14088 docs: Fix typographical error
  docs/docs/sourcing-from-sanity.md
Labels: type: documentation

#13871 fix(gatsby): refresh browser if webpack rebuild occurs
  e2e-tests/production-runtime/cypress/integration/1-production.js
  e2e-tests/production-runtime/cypress/integration/compilation-hash.js
  e2e-tests/production-runtime/cypress/plugins/compilation-hash.js
  e2e-tests/production-runtime/cypress/plugins/index.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/pages/compilation-hash.js
  e2e-tests/production-runtime/src/pages/deep-link-page.js
  e2e-tests/production-runtime/src/pages/index.js
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/commands/build-html.js
  packages/gatsby/src/commands/build-javascript.js
  packages/gatsby/src/commands/build.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/query/query-runner.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/index.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/webpack-compilation-hash.js
  packages/gatsby/src/utils/html-renderer-queue.js
  packages/gatsby/src/utils/page-data.js
  packages/gatsby/src/utils/worker/__tests__/physical-cpu-count.js
  packages/gatsby/src/utils/worker/child.js
  packages/gatsby/src/utils/worker/cpu-core-count.js
  packages/gatsby/src/utils/worker/page-data.js
  packages/gatsby/src/utils/worker/physical-cpu-count.js
  packages/gatsby/src/utils/worker/pool.js
  packages/gatsby/src/utils/worker/render-html.js
Labels: status: awaiting reviewer response

#13919 chore(gatsby-plugin-preact): Update to Preact X beta
  packages/gatsby-plugin-preact/README.md
  packages/gatsby-plugin-preact/package.json
  packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
Labels: status: blocked

#14037 feat(gatsby-plugin-checker): filter archived repositories
  scripts/gatsby-plugin-checker/.env
  scripts/gatsby-plugin-checker/README.md
  scripts/gatsby-plugin-checker/index.js
  scripts/gatsby-plugin-checker/package.json
  scripts/gatsby-plugin-checker/plugins.json
Labels: bot: merge on green

#14118 fix(gatsby): include includePrerelease in semver.satisfies check
  packages/gatsby/src/bootstrap/load-plugins/validate.js
Labels: bot: merge on green

#12406 docs(www): First Touch Maintenance
  docs/contributing/triaging-github-issues.md
Labels: status: WIP, type: documentation

#13905 docs(blog): add Advanced Sitemap Plugin for SEO
  docs/blog/2019-05-07-advanced-sitemap-plugin-for-seo/images/advanced_sitemaps.png
  docs/blog/2019-05-07-advanced-sitemap-plugin-for-seo/images/seo_results.png
  docs/blog/2019-05-07-advanced-sitemap-plugin-for-seo/index.md
  docs/blog/author.yaml
  docs/blog/avatars/aileen-nowak.jpeg
Labels: status: awaiting reviewer response, topic: blogpost

#14036 chore(docs): Improve linking and starters workflows
  docs/docs/linking-between-pages.md
  docs/docs/recipes.md
  docs/docs/starters.md
  www/src/data/sidebars/doc-links.yaml
  www/src/views/starter-library/starter-list.js
Labels: type: documentation

#14121 fix(www): Add og:url meta property to fix LinkedIn shares
  www/src/templates/template-blog-post.js
Labels: bot: merge on green

#14140 chore(starters): add gatsby-starter-readonly
  docs/starters.yml
Labels: bot: merge on green

#14132 chore(docs): add links to philosophy
  docs/docs/gatsby-core-philosophy.md
Labels: bot: merge on green

#14164 chore(showcase): Add purple11.com
  docs/sites.yml
Labels: topic: showcase

#14155 chore(starters): add gatsby-starter-overflow
  docs/starters.yml
Labels: bot: merge on green

#14171 chore(showcase): add greenorbit.com
  docs/sites.yml
Labels: topic: showcase

#12695 docs(blog): Update and Revise Strapi Gatsby Tutorial
  docs/blog/2018-1-18-strapi-and-gatsby/adding-images.png
  docs/blog/2018-1-18-strapi-and-gatsby/article-entries.png
  docs/blog/2018-1-18-strapi-and-gatsby/create-first-user.png
  docs/blog/2018-1-18-strapi-and-gatsby/define-relation.png
  docs/blog/2018-1-18-strapi-and-gatsby/gatsby-article.png
  docs/blog/2018-1-18-strapi-and-gatsby/gatsby-author.png
  docs/blog/2018-1-18-strapi-and-gatsby/gatsby-home.png
  docs/blog/2018-1-18-strapi-and-gatsby/gatsby-strapi.png
  docs/blog/2018-1-18-strapi-and-gatsby/index.md
  docs/blog/2018-1-18-strapi-and-gatsby/restart-server.png
  docs/blog/2018-1-18-strapi-and-gatsby/roles-and-permissions.png
  docs/blog/2018-1-18-strapi-and-gatsby/static-page-result.png
  docs/blog/2018-1-18-strapi-and-gatsby/strapi-content-manager.png
  docs/blog/2018-1-18-strapi-and-gatsby/strapi-new-type.png
  docs/blog/2018-1-18-strapi-and-gatsby/strapi-permissions.png
  docs/blog/2018-1-18-strapi-and-gatsby/strapi-register.png
  docs/blog/2018-1-18-strapi-and-gatsby/what-we-are-doing.png
Labels: topic: blogpost, type: documentation

#13766 [docs] Restructure styling section
  docs/docs/component-css.md
  docs/docs/creating-global-styles.md
  docs/docs/css-in-js.md
  docs/docs/css-libraries-and-frameworks.md
  docs/docs/css-modules.md
  docs/docs/emotion.md
  docs/docs/glamor.md
  docs/docs/global-css.md
  docs/docs/layout-components.md
  docs/docs/styled-components.md
  docs/docs/styling.md
  www/gatsby-node.js
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#13089 refactor(gatsby-cli): rework cli to use ink
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/reporter/index.js
  packages/gatsby-cli/src/reporter/reporters/index.js
  packages/gatsby-cli/src/reporter/reporters/ink/components/activity.js
  packages/gatsby-cli/src/reporter/reporters/ink/components/messages.js
  packages/gatsby-cli/src/reporter/reporters/ink/index.js
  packages/gatsby-cli/src/reporter/reporters/ink/reporter.js
  packages/gatsby/package.json
  packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/query/__tests__/file-parser.js
  yarn.lock
Labels: effort: high, impact: med, status: awaiting reviewer response

#11975 chore(docs): Update build-caching
  docs/docs/build-caching.md
Labels: type: documentation

#14144 chore(docs): Algolia search guide from class to functional components
  docs/docs/adding-search-with-algolia.md
Labels: type: documentation

#13827 feat(gatsby-plugin-feed): add match plugin option
  docs/docs/adding-an-rss-feed.md
  packages/gatsby-plugin-feed/README.md
  packages/gatsby-plugin-feed/src/__tests__/__snapshots__/gatsby-ssr.js.snap
  packages/gatsby-plugin-feed/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-feed/src/gatsby-ssr.js
  packages/gatsby-plugin-feed/src/plugin-options.js
Labels: status: awaiting reviewer response

#14204 chore(docs): update storybook instructions
  docs/docs/visual-testing-with-storybook.md
Labels: type: documentation

#14131 chore(blog): Gatsby CLI/Error blogpost
  docs/blog/2019-05-22-cli-error-redesign/index.md
Labels: topic: blogpost

#14209 chore(gatsby): adds support for PnP in test-require-error
  packages/gatsby/src/utils/test-require-error.js
Labels: status: awaiting reviewer response

#14227 chore(docs): Files Gatsby Looks for in a Plugin
  docs/docs/files-gatsby-looks-for-in-a-plugin.md
Labels: type: documentation

#14238 fix(gatsby-telemetry): enable CI name for unsupported CI & fixed cpu count
  packages/gatsby-telemetry/src/telemetry.js
Labels: bot: merge on green

#14246 chore(blog): add link to Gatsby Preview integrations from intro blog post
  docs/blog/2019-03-22-introducing-gatsby-preview-beta/index.md
Labels: bot: merge on green

#12996 feat(blog): add Yarn workspaces for theme development blog post
  docs/blog/2019-05-22-setting-up-yarn-workspaces-for-theme-development/index.md
  docs/blog/author.yaml
  docs/blog/avatars/brent-jackson.jpg
Labels: topic: blogpost, topic: themes, type: documentation

#14208 fix(gatsby): improve `externals` webpack configuration to better support yarn PnP
  packages/gatsby/src/utils/webpack.config.js
Labels: status: awaiting reviewer response

#13832 feat(docs): Add schema customization docs
  docs/docs/schema-connections.md
  docs/docs/schema-customization.md
  docs/docs/schema-generation.md
  docs/docs/schema-gql-type.md
  docs/docs/schema-input-gql.md
  docs/docs/schema-sift.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#14201 feat(gatsby-plugin-sharp): remove 3x DPi resolutions
  docs/blog/2019-04-02-behind-the-scenes-what-makes-gatsby-great/index.md
  docs/docs/preoptimizing-images.md
  e2e-tests/gatsby-image/cypress/integration/fixed.js
  examples/image-processing/src/pages/index.js
  packages/gatsby-plugin-sharp/README.md
  packages/gatsby-plugin-sharp/src/index.js
Labels: topic: plugins

#14267 chore(showcase): Add Aditus.io
  docs/sites.yml
Labels: topic: showcase

#14240 feat(www): Add source links to API docs
  www/gatsby-config.js
  www/gatsby-node.js
  www/package.json
  www/plugins/gatsby-transformer-gatsby-api-calls/find-api-calls.js
  www/plugins/gatsby-transformer-gatsby-api-calls/gatsby-node.js
  www/plugins/gatsby-transformer-gatsby-api-calls/index.js
  www/plugins/gatsby-transformer-gatsby-api-calls/package.json
  www/src/components/api-reference/doc-block.js
  www/src/components/api-reference/index.js
  www/src/components/api-reference/utils.js
  www/src/pages/docs/actions.js
  www/src/pages/docs/browser-apis.js
  www/src/pages/docs/node-apis.js
  www/src/pages/docs/ssr-apis.js
  www/src/utils/normalize-gatsby-api-call.js
Labels: status: awaiting reviewer response

#14119 docs(blog): adding blog post for community events support
  docs/blog/2019-05-24-community-events-support/index.md
Labels: topic: blogpost

#14308 chore(gatsby-plugin-sharp): Adjust docs to match code changes
  packages/gatsby-plugin-sharp/README.md
Labels: bot: merge on green

#14311 feat(gatsby-plugin-facebook-analytics): Add version, cookie and xfbml config options
  packages/gatsby-plugin-facebook-analytics/README.md
  packages/gatsby-plugin-facebook-analytics/src/__tests__/__snapshots__/gatsby-ssr.js.snap
  packages/gatsby-plugin-facebook-analytics/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-facebook-analytics/src/gatsby-ssr.js
Labels: bot: merge on green

#14309 chore(showcase): Adds ultraconfig.com.au
  docs/sites.yml
Labels: bot: merge on green

#14330 chore(showcase): Removing Little Wolf Studio
  docs/sites.yml
Labels: topic: showcase

#14324 chore(showcase): Removing Austrilia Bureau Of Meteorology site
  docs/sites.yml
Labels: topic: showcase

#14323 chore(showcase): Updated Aman Mittal's portfolio domain
  docs/sites.yml
Labels: topic: showcase

#14334 chore(showcase): Add malice
  docs/sites.yml
Labels: topic: showcase

#14343 chore(showcase): Add Axel Fuhrmann's portfolio
  docs/sites.yml
Labels: topic: showcase

#14306 chore(docs): Add note about pageContext being serialized
  docs/docs/creating-and-modifying-pages.md
Labels: type: documentation

#14346 chore(docs): Update "Centralized Navigation"
  docs/docs/centralizing-your-sites-navigation.md
Labels: type: documentation

#13183 feat(gatsby-source-shopify): Add support for Shopify Pages
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/gatsby-node.js
  packages/gatsby-source-shopify/src/nodes.js
  packages/gatsby-source-shopify/src/queries.js
Labels: status: awaiting author response

#12044 fix(*): cache tracedSVG calculations when cache is present
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-remark-images/src/index.js
  packages/gatsby-transformer-sharp/src/extend-node-type.js
Labels: bot: merge on green

#14369 chore(showcase): add lukesecomb.digital portfolio site
  docs/sites.yml
Labels: topic: showcase

#14382 feat(blog): add gatsby gathering + gatsby days post
  docs/blog/2019-05-29-the-great-gatsby-gathering-nyc/images/chris-dustin.jpg
  docs/blog/2019-05-29-the-great-gatsby-gathering-nyc/images/harrys.jpg
  docs/blog/2019-05-29-the-great-gatsby-gathering-nyc/images/lunch.jpg
  docs/blog/2019-05-29-the-great-gatsby-gathering-nyc/images/marisa-dustin-michal.jpg
  docs/blog/2019-05-29-the-great-gatsby-gathering-nyc/images/team.jpg
  docs/blog/2019-05-29-the-great-gatsby-gathering-nyc/images/unconference.jpg
  docs/blog/2019-05-29-the-great-gatsby-gathering-nyc/index.md
Labels: bot: merge on green

#14378 chore(graphql-reference): bump gatsby version
  docs/docs/graphql-reference.md
  examples/graphql-reference/package.json
Labels: status: blocked

#14387 chore(showcase): add globalcitydata website
  docs/sites.yml
Labels: topic: showcase

#14392 chore(showcase): add wearebrew site to sites.yml
  docs/sites.yml
Labels: topic: showcase

#14407 chore(docs): fix typo in creating-a-source-plugin
  docs/docs/creating-a-source-plugin.md
Labels: impact: low, type: documentation

#14437 fix(gatsby-plugin-google-tagmanager): guard against dataLayer being undefined in development
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-browser.js
Labels: bot: merge on green

#13929 docs(gatsby-source-wordpress): Clarify how to retrieve post meta
  packages/gatsby-source-wordpress/README.md
Labels: status: awaiting author response

#14459 chore(showcase): Add Gatsby GitHub Stats site
  docs/sites.yml
Labels: topic: showcase

#14445 chore(docs): add contributing examples note; move schema customization, etc.
  docs/contributing/code-contributions.md
  docs/docs/gatsby-internals.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#13110 feat(gatsby-source-filesystem): add an environment variable to control concurrent queue size
  packages/gatsby-source-filesystem/README.md
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
Labels: status: awaiting reviewer response

#14472 feat(gatsby): update graphiql-explorer
  packages/gatsby-graphiql-explorer/package.json
  packages/gatsby-graphiql-explorer/src/app/app.js
  yarn.lock
Labels: status: awaiting reviewer response
