Repository gatsbyjs/gatsby, pull requests merged in 2019-02, with the labels that each got.

#10940 test(production-e2e): Add offline tests
  .circleci/config.yml
  e2e-tests/development-runtime/package.json
  e2e-tests/gatsby-image/package.json
  e2e-tests/path-prefix/cypress/plugins/index.js
  e2e-tests/path-prefix/package.json
  e2e-tests/production-runtime/cypress.json
  e2e-tests/production-runtime/cypress/integration/1-production.js
  e2e-tests/production-runtime/cypress/integration/plugins/index.js
  e2e-tests/production-runtime/gatsby-config.js
  e2e-tests/production-runtime/package.json
  examples/gatsbygram/package.json
  packages/gatsby/cache-dir/api-runner-browser.js
  packages/gatsby/src/utils/webpack.config.js
  scripts/e2e-test.sh
Labels: status: inkteam to review

#11344 docs(building-with-components): convert class to functional components
  docs/docs/building-with-components.md
Labels: type: documentation

#11425 feat(gatsby-source-wordpress): add jwt_base_path option
  packages/gatsby-source-wordpress/README.md
  packages/gatsby-source-wordpress/src/fetch.js
Labels: status: awaiting author response, type: feature or enhancement

#11299 feat(docs): add company blogspot
  docs/blog/2019-01-29-gatsby-eng-hiring-philosophy/index.md
Labels: blogpost

#11410 fix(blog): Re-arrange content after code was moved between snippets
  docs/blog/2019-01-31-using-react-context-api-with-gatsby/index.md
Labels: blogpost, type: documentation

#11499 fix(doc): Remove broken link (fixes #11297)
  docs/docs/adding-images-fonts-files.md
Labels: type: documentation

#11542 fix(gatsby): update terser-webpack-plugin to avoid webpack error
  packages/gatsby/package.json
Labels: type: maintenance

#11444 docs(tutorial): Updated div's style to be consistent with the previous one
  docs/tutorial/part-three/index.md
Labels: type: documentation

#11551 feat(blog): add haptic media case study
  .forestry/front_matter/templates/blog.yml
  .forestry/settings.yml
  docs/blog/2019-02-05-hapticmedia-case-study/images/hapticmedia.jpg
  docs/blog/2019-02-05-hapticmedia-case-study/index.md
  www/src/fonts/Webfonts/futurapt_bookitalic_macroman/ftn46-webfont.eot
Labels: status: WIP

#11562 docs(starter): Add hello-friend starter
  docs/starters.yml
Labels: type: documentation

#10936 feat(www): update tags design, add 'View All Tags' buttons
  www/src/components/tags-section.js
  www/src/pages/blog/tags.js
  www/src/templates/tags.js
  www/src/templates/template-blog-list.js
Labels: status: awaiting reviewer response

#11484 feat(gatsby-plugin-netlify): Allow status codes in redirects (#11255)
  packages/gatsby-plugin-netlify/README.md
  packages/gatsby-plugin-netlify/src/create-redirects.js
  packages/gatsby/src/redux/actions.js
Labels: type: feature or enhancement

#11514 feat(docs): add migrating to React Hooks Blog Post
  docs/blog/2019-02-04-pragmatic-lessons-from-converting-to-react-hooks/images/hooks-diff.jpg
  docs/blog/2019-02-04-pragmatic-lessons-from-converting-to-react-hooks/index.md
  docs/blog/author.yaml
  docs/blog/avatars/daniel-lemay.jpg
Labels: type: documentation

#11466 docs: add https://fedonman.com to featured websites
  docs/sites.yml
Labels: status: blocked

#11614 fix(docs): typos in using-react-context-api-with-gatsby
  docs/blog/2019-01-31-using-react-context-api-with-gatsby/index.md
Labels: type: documentation

#10599 chore(docs): explain "replace" settings for gatsby-link
  docs/docs/gatsby-link.md
Labels: type: documentation

#11615 fix(docs): update starter creation readme
  starters/README.md
Labels: status: awaiting author response, type: documentation

#11098 feat(docs): Add Sourcing from Sanity Documentation
  docs/docs/sourcing-from-sanity.md
Labels: type: documentation

#11567 test: enable integation tests for image sharp
  .circleci/config.yml
  integration-tests/gatsby-pipeline/LICENSE
  integration-tests/gatsby-pipeline/README.md
  integration-tests/gatsby-pipeline/__tests__/lazy-image-build/develop.js
  integration-tests/gatsby-pipeline/gatsby-browser.js
  integration-tests/gatsby-pipeline/gatsby-config.js
  integration-tests/gatsby-pipeline/package.json
  integration-tests/gatsby-pipeline/src/components/header.js
  integration-tests/gatsby-pipeline/src/components/image.js
  integration-tests/gatsby-pipeline/src/components/layout.css
  integration-tests/gatsby-pipeline/src/components/layout.js
  integration-tests/gatsby-pipeline/src/components/seo.js
  integration-tests/gatsby-pipeline/src/images/gatsby-astronaut.png
  integration-tests/gatsby-pipeline/src/images/gatsby-icon.png
  integration-tests/gatsby-pipeline/src/pages/404.js
  integration-tests/gatsby-pipeline/src/pages/index.js
  integration-tests/gatsby-pipeline/src/pages/page-2.js
  integration-tests/gatsby-pipeline/utils/create-devserver.js
  integration-tests/jest.config.js
  integration-tests/long-term-caching/__tests__/long-term-caching.js
  integration-tests/long-term-caching/package.json
  scripts/e2e-test.sh
Labels: status: awaiting reviewer response, type: maintenance

#11685 post: new blog about the themes livestream
  docs/blog/2019-02-11-gatsby-themes-livestream-and-example/index.md
Labels: blogpost

#11702 docs(s3-cloudfront): update install doc (aws -> awscli)
  docs/docs/deploying-to-s3-cloudfront.md
Labels: type: documentation

#10868 feat(gatsby-cli): Initialize the newly cloned repository as git
  packages/gatsby-cli/src/init-starter.js
Labels: type: feature or enhancement

#11697 docs(creating-and-modifying-pages): remove unnecessary promise
  docs/docs/creating-and-modifying-pages.md
Labels: type: documentation

#11689 docs(starters): Added https://unda.com.au
  docs/sites.yml
Labels: type: documentation

#11493 docs(gatsby-plugin-catch-links): clarify this handle all links (and not just markdown)
  packages/gatsby-plugin-catch-links/README.md
Labels: type: documentation

#11647 docs: added aria-label to link
  www/src/components/package-readme.js
Labels: type: documentation

#11631 docs(showcase): Add Parallel Polis Kosice to showcase
  docs/sites.yml
Labels: type: documentation

#11652 docs(starters): Add kepinski.me
  docs/sites.yml
Labels: type: documentation

#11699 docs: add egghead lesson to quickstart
  docs/docs/quick-start.md
Labels: type: documentation

#11700 docs: add videos for Gatsby Link + rewrite for flow
  docs/docs/gatsby-link.md
Labels: status: WIP, type: documentation

#10560 chore: minify svg husky hook
  docs/blog/2017-11-08-migrate-from-jekyll-to-gatsby/gatsby.svg
  package.json
  scripts/format-svg.js
  www/src/assets/showcase-feather.svg
Labels: type: feature or enhancement

#11439 chore(docs): reword CSS in JS docs for clarity
  docs/docs/emotion.md
  docs/docs/glamor.md
  docs/docs/styled-components.md
Labels: status: awaiting reviewer response

#11588 feat(gatsby): add useStaticQuery hook
  e2e-tests/development-runtime/cypress/integration/functionality/static-queries.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/static-queries.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/src/components/seo.js
  e2e-tests/development-runtime/src/components/static-query/exported-variable-query.js
  e2e-tests/development-runtime/src/components/static-query/hot.js
  e2e-tests/development-runtime/src/components/static-query/index.js
  e2e-tests/development-runtime/src/components/static-query/inline-query.js
  e2e-tests/development-runtime/src/components/static-query/use-static-query/destructuring.js
  e2e-tests/development-runtime/src/components/static-query/use-static-query/exported-variable-query.js
  e2e-tests/development-runtime/src/components/static-query/use-static-query/hot.js
  e2e-tests/development-runtime/src/components/static-query/use-static-query/index.js
  e2e-tests/development-runtime/src/components/static-query/use-static-query/inline-query.js
  e2e-tests/development-runtime/src/components/static-query/use-static-query/variable-query.js
  e2e-tests/development-runtime/src/components/static-query/variable-query.js
  e2e-tests/development-runtime/src/pages/static-query.js
  e2e-tests/production-runtime/cypress/integration/static-query.js
  e2e-tests/production-runtime/cypress/integration/static-query/extraction.js
  e2e-tests/production-runtime/src/components/static-query/exported-variable-query.js
  e2e-tests/production-runtime/src/components/static-query/index.js
  e2e-tests/production-runtime/src/components/static-query/inline-query.js
  e2e-tests/production-runtime/src/components/static-query/use-static-query/destructuring.js
  e2e-tests/production-runtime/src/components/static-query/use-static-query/exported-variable-query.js
  e2e-tests/production-runtime/src/components/static-query/use-static-query/index.js
  e2e-tests/production-runtime/src/components/static-query/use-static-query/inline-query.js
  e2e-tests/production-runtime/src/components/static-query/use-static-query/variable-query.js
  e2e-tests/production-runtime/src/components/static-query/variable-query.js
  e2e-tests/production-runtime/src/pages/index.js
  e2e-tests/production-runtime/src/pages/static-query.js
  packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
  packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js
  packages/babel-plugin-remove-graphql-queries/src/index.js
  packages/gatsby/cache-dir/gatsby-browser-entry.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/internal-plugins/query-runner/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/internal-plugins/query-runner/file-parser.js
  packages/gatsby/src/internal-plugins/query-runner/query-compiler.js
Labels: type: feature or enhancement

#11729 feat(showcase): add Incremental.com.au
  docs/sites.yml
Labels: type: documentation

#11750 fix(blog): 2019-01-01 json code blocks
  docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
Labels: type: documentation

#11749 feat(blog): add a behind the scenes q and a blog post
  docs/blog/2019-02-14-behind-the-scenes-q-and-a/images/what-makes-gatsby-great.png
  docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
Labels: blogpost

#10249 fix(www): Fix showcase visit site link overlap
  www/src/components/share-menu.js
  www/src/components/showcase-details.js
Labels: status: awaiting reviewer response, type: documentation

#11728 chore(docs): clarify that Gatsby can be hosted anywhere
  docs/docs/deploying-and-hosting.md
Labels: type: documentation

#11743 fix(gatsby-remark-images): ensure query string is ignored when detecting images
  packages/gatsby-remark-images/package.json
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/index.js
Labels: status: awaiting author response

#11671 chore(www): add target blank to showcase url
  www/src/components/showcase-details.js
Labels: status: awaiting reviewer response, type: documentation

#11608 fix(gatsby-plugin-manifest): improve SVG->PNG fidelity
  packages/gatsby-plugin-manifest/README.md
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
Labels: status: awaiting reviewer response

#11789 docs(awesome-gatsby): Add link to official YouTube channel
  docs/docs/awesome-gatsby.md
Labels: type: documentation

#11848 fix(themes): Remove require.resolve in component resolve path
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js
Labels: themes

#11655 Docs/headless cms/sourcing from graphcms
  docs/docs/headless-cms.md
  docs/docs/sourcing-from-graphcms.md
  docs/starters.yml
Labels: type: documentation

#11777 fix(gatsby): Stopped queueing further calls to onCreatePage after a page is deleted
  packages/gatsby/src/utils/api-runner-node.js
Labels: type: bug

#11811 docs(www): use static query blog post
  docs/blog/2019-02-20-introducing-use-static-query/images/excited.gif
  docs/blog/2019-02-20-introducing-use-static-query/index.md
  docs/blog/author.yaml
  docs/blog/avatars/sidhartha-chatterjee.jpg
Labels: blogpost

#11954 fix(themes): reverse order of themes checked when shadowing
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js
Labels: themes

#11959 docs(www): Fix link to withPrefix on Adding images docs
  docs/docs/adding-images-fonts-files.md
Labels: type: documentation

#11478 docs: Create a guide on sourcing from Kentico Cloud
  docs/docs/sourcing-from-kentico-cloud.md
Labels: type: documentation

#11237 feat(gatsby-transformer-remark): add excerptAst to be exported as a GraphQL field
  e2e-tests/development-runtime/plugins/gatsby-remark-subcache/index.js
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: status: awaiting author response

#12096 docs(gatsby-source-wordpress): add ACF option pages troubleshooting
  packages/gatsby-source-wordpress/README.md
Labels: type: documentation

#12043 Don't run base64 calculation when demanding tracedSVG
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-sharp/src/__tests__/index.js
  packages/gatsby-plugin-sharp/src/index.js
Labels: status: awaiting author response

#11939 feat(blog): add gatsby themes + mdx blog post
  docs/blog/2019-02-26-getting-started-with-gatsby-themes/index.md
  docs/blog/author.yaml
  docs/blog/avatars/katie-fujihara.jpg
Labels: blogpost

#12106 docs(typography): add some references about typography to tutorial
  docs/tutorial/part-three/index.md
Labels: type: documentation

#11071 fix(docs): mention to add your own icon inside a directory
  docs/docs/add-a-manifest-file.md
  docs/tutorial/part-eight/index.md
Labels: type: documentation

#11909 docs(gatsby-link): Added some information regarding the limitations with the link package
  docs/docs/gatsby-link.md
Labels: status: awaiting author response

#11684 feat(blog): add localization with gatsby and sanity
  docs/blog/2019-03-01-localization-with-gatsby-and-sanity/images/gatsby-sanity-l10n.png
  docs/blog/2019-03-01-localization-with-gatsby-and-sanity/images/ui-example.png
  docs/blog/2019-03-01-localization-with-gatsby-and-sanity/index.md
  docs/blog/author.yaml
  docs/blog/avatars/travis_stanley.jpg
Labels: blogpost

#12167 docs(404): replace setup => set up in 404 page
  docs/docs/add-404-page.md
Labels: type: documentation

#12171 chore(docs): "behaviour" to "behavior"
  docs/docs/environment-variables.md
  packages/gatsby-plugin-catch-links/README.md
  packages/gatsby-plugin-manifest/README.md
  packages/gatsby-plugin-remove-trailing-slashes/README.md
  packages/gatsby-transformer-excel/README.md
Labels: status: awaiting reviewer response, type: documentation

#12098 fix(www): fix gdpr for google analytics
  www/gatsby-config.js
Labels: type: bug

#12173 fix(www): fix inf loop on reset filters in showcase
  www/src/views/showcase/index.js
Labels: type: bug

#12161 chore: bump fs-extra to 7.0.0
  packages/gatsby-transformer-sharp/package.json
Labels: status: awaiting reviewer response

#11459 docs: write adding-search-with-algolia guide
  docs/docs/adding-search-with-algolia.md
  www/src/data/sidebars/doc-links.yaml
Labels: status: awaiting author response

#11771 chore(www): migrate to emotion 10
  www/package.json
  www/src/components/banner.js
  www/src/components/card.js
  www/src/components/diagram.js
  www/src/components/ecosystem/ecosystem-board.js
  www/src/components/ecosystem/ecosystem-featured-item.js
  www/src/components/ecosystem/ecosystem-featured-items.js
  www/src/components/ecosystem/ecosystem-section.js
  www/src/components/email-capture-form.js
  www/src/components/evaluation-table-section-header-top.js
  www/src/components/homepage/homepage-blog-post.js
  www/src/components/homepage/homepage-blog-posts.js
  www/src/components/homepage/homepage-ecosystem.js
  www/src/components/homepage/homepage-newsletter.js
  www/src/components/homepage/homepage-section.js
  www/src/components/layout/layout-with-heading.js
  www/src/components/layout/page-heading.js
  www/src/components/navigation-mobile.js
  www/src/components/plugin-searchbar-body.js
  www/src/components/search-form.js
  www/src/components/shared/horizontal-scroller.js
  www/src/components/shared/pullquote.js
  www/src/components/slider.js
  www/src/components/unbird.js
  www/src/utils/styles.js
Labels: status: awaiting author response
