Repository gatsbyjs/gatsby, pull requests merged in 2019-04, with the labels that each got.

#12968 Config info for GitLab Client-Side Implicit Grant
  docs/docs/sourcing-from-netlify-cms.md
Labels: type: documentation

#12263 fix(gatsby): Only use one redux namespace for plugins
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/validate.js.snap
  packages/gatsby/src/bootstrap/load-plugins/__tests__/validate.js
  packages/gatsby/src/bootstrap/load-plugins/index.js
  packages/gatsby/src/bootstrap/load-plugins/validate.js
  packages/gatsby/src/redux/reducers/api-to-plugins.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/plugins.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/source-nodes.js
Labels: status: awaiting reviewer response

#13002 chore(showcase): Add Assortment to site showcase
  docs/sites.yml
Labels: topic: showcase

#12001 feat(gatsby-transformer-react-docgen): use local babel config for react-docgen
  packages/gatsby-transformer-react-docgen/README.md
  packages/gatsby-transformer-react-docgen/package.json
  packages/gatsby-transformer-react-docgen/src/__tests__/fixtures/babel-config/.babelrc
  packages/gatsby-transformer-react-docgen/src/__tests__/fixtures/babel-config/classes.js
  packages/gatsby-transformer-react-docgen/src/__tests__/on-node-create.js
  packages/gatsby-transformer-react-docgen/src/parse.js
  yarn.lock
Labels: breaking change, status: awaiting reviewer response

#13046 chore(showcase): Add altstadtdomizil-idstein.de
  docs/sites.yml
Labels: topic: showcase

#13045 chore(showcase): Adding Mission42 to sites.yml
  docs/sites.yml
Labels: topic: showcase

#10994 style(www): improve style of code block language tabs
  www/src/pages/docs/actions.js
  www/src/pages/docs/node-apis.js
  www/src/utils/typography.js
Labels: status: awaiting reviewer response

#12873 docs(gatsby-plugin-react-helmet): add React hooks compatibility information
  packages/gatsby-plugin-react-helmet/README.md
Labels: status: awaiting author response

#13031 chore(docs): fix commas and tweak small issues in tutorial
  docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md
  docs/tutorial/part-eight/index.md
  docs/tutorial/part-four/index.md
  docs/tutorial/part-one/index.md
  docs/tutorial/part-seven/index.md
  docs/tutorial/part-six/index.md
  docs/tutorial/part-three/index.md
  docs/tutorial/part-two/index.md
Labels: status: awaiting author response

#13066 feat(gatsby): add DANGEROUSLY_DISABLE_OOM
  docs/docs/scaling-issues.md
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/index.js
Labels: status: awaiting reviewer response

#11595 feat(gatsby-source-wordpress): Add yoast premium redirects in know entitites
  packages/gatsby-source-wordpress/README.md
  packages/gatsby-source-wordpress/src/gatsby-node.js
  packages/gatsby-source-wordpress/src/normalize.js
Labels: status: awaiting author response

#13123 fix(gatsby-plugin-sitemap): add meaningful error when siteUrl is missing
  packages/gatsby-plugin-sitemap/src/__tests__/internals.js
  packages/gatsby-plugin-sitemap/src/internals.js
Labels: bot: merge on green

#13155 chore(showcase): add Paul Clifton Photography to showcase
  docs/sites.yml
Labels: topic: showcase

#13057 Docs: Create a Starter
  docs/contributing/create-a-starter.md
  docs/docs/creating-a-starter.md
  docs/docs/starters.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#12893 docs/blog - Static Site Security
  docs/blog/2019-03-27-security-for-modern-web-frameworks/index.md
  docs/blog/author.yaml
  docs/blog/avatars/alex-moon.jpg
Labels: topic: blogpost

#13191 blog/fix post date
  docs/blog/2019-04-06-security-for-modern-web-frameworks/index.md
Labels: topic: blogpost

#12757 refactor: (gatsby-plugin-manifest) misc code and doc updates
  benchmarks/plugin-manifest/README.md
  benchmarks/plugin-manifest/index.js
  benchmarks/plugin-manifest/package.json
  benchmarks/plugin-manifest/public/.gitkeep
  packages/gatsby-plugin-manifest/README.md
  packages/gatsby-plugin-manifest/package.json
  packages/gatsby-plugin-manifest/src/__tests__/__snapshots__/gatsby-ssr.js.snap
  packages/gatsby-plugin-manifest/src/__tests__/common.js
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-manifest/src/common.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-ssr.js
Labels: bot: merge on green

#13000 chore(*): Use new createContentDigest helper
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/gatsby-node.js
  packages/gatsby-source-hacker-news/package.json
  packages/gatsby-source-hacker-news/src/gatsby-node.js
  packages/gatsby-source-lever/package.json
  packages/gatsby-source-lever/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-lever/src/__tests__/normalize.js
  packages/gatsby-source-lever/src/gatsby-node.js
  packages/gatsby-source-lever/src/normalize.js
  packages/gatsby-source-npm-package-search/package.json
  packages/gatsby-source-npm-package-search/src/gatsby-node.js
  packages/gatsby-source-wikipedia/src/gatsby-node.js
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-source-wordpress/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-wordpress/src/__tests__/normalize.js
  packages/gatsby-source-wordpress/src/gatsby-node.js
  packages/gatsby-source-wordpress/src/normalize.js
  packages/gatsby-transformer-excel/package.json
  packages/gatsby-transformer-excel/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-excel/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-excel/src/gatsby-node.js
  packages/gatsby-transformer-hjson/package.json
  packages/gatsby-transformer-hjson/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-hjson/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-hjson/src/gatsby-node.js
  packages/gatsby-transformer-javascript-frontmatter/package.json
  packages/gatsby-transformer-javascript-frontmatter/src/gatsby-node.js
  packages/gatsby-transformer-javascript-static-exports/package.json
  packages/gatsby-transformer-javascript-static-exports/src/gatsby-node.js
  packages/gatsby-transformer-react-docgen/package.json
  packages/gatsby-transformer-react-docgen/src/__tests__/on-node-create.js
  packages/gatsby-transformer-react-docgen/src/on-node-create.js
Labels: status: awaiting reviewer response

#13156 feat(showcase): add Little Wolf Studio to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#13169 chore(showcase): add site attejuvonen.fi to site showcase
  docs/sites.yml
Labels: topic: showcase

#13209 chore(gatsby): Get rid of "DeprecationWarning: asynchronous function without callback"
  packages/gatsby/src/commands/build-html.js
Labels: bot: merge on green

#13175 chore(showcase): add redcarpetup.com
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#13178 chore(showcase): Added Kibuk Construction to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#13226 chore(docs): reword module name for building themes
  docs/docs/themes/api-reference.md
Labels: topic: themes

#13088 feat(blog): Add a new blog about how we think about product at Gatsby
  docs/blog/2019-04-03-how-we-think-about-product-at-gatsby/index.md
Labels: topic: blogpost

#12927 fix(gatsby-plugin-sharp): don't write to same temporary time multiple times at a same time
  packages/gatsby-plugin-sharp/src/__tests__/trace-svg.js
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/plugin-options.js
  packages/gatsby-plugin-sharp/src/report-error.js
  packages/gatsby-plugin-sharp/src/trace-svg.js
Labels: bot: merge on green, status: awaiting reviewer response

#13061 refactor(gatsby): Make query queue constructable
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/query/page-query-runner.js
  packages/gatsby/src/query/query-queue.js
  packages/gatsby/src/query/query-runner.js
  packages/gatsby/src/query/query-watcher.js
  packages/gatsby/src/query/queue.js
Labels: status: awaiting reviewer response

#13279 feat(showcase): add PicPick to showcase
  docs/sites.yml
Labels: topic: showcase

#13263 chore(showcase): Add Ste O'Neill Portfolio to showcase
  docs/sites.yml
Labels: topic: showcase

#13225 feat(gatsby-cli): Remove one of package-lock.json and yarn.lock on gatsby new
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/init-starter.js
  packages/gatsby-telemetry/package.json
  yarn.lock
Labels: bot: merge on green

#13087 fix(gatsby-telemetry): Ensure we capture cli version even with older gatsby-cli
  packages/gatsby-telemetry/src/telemetry.js
Labels: status: awaiting reviewer response

#13152 chore(starters): add gatsby-firebase-hosting-starter
  docs/starters.yml
Labels: status: awaiting author response

#12930 fix(themes): Restrict the paths that count as shadowable for an issuer
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/index.js
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/gatsby-node.js
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js
Labels: no triage, topic: themes

#12110 feat(gatsby-remark-code-repls): include matching css option (CodePen)
  packages/gatsby-remark-code-repls/README.md
  packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js
  packages/gatsby-remark-code-repls/src/__tests__/index.js
  packages/gatsby-remark-code-repls/src/constants.js
  packages/gatsby-remark-code-repls/src/gatsby-node.js
Labels: bot: merge on green

#13318 chore(showcase): Add Progressive Massachusetts Legislator Scorecard to showcase
  docs/sites.yml
Labels: topic: showcase

#13294 fix(cpu-core-count): fallback to generic Node.JS method if system specific call fails
  packages/gatsby/src/utils/__tests__/physical-cpu-count.js
  packages/gatsby/src/utils/cpu-core-count.js
  packages/gatsby/src/utils/physical-cpu-count.js
Labels: status: awaiting reviewer response

#13247 chore(showcase): Adding Talita Traveler's personal blog to site showcase
  docs/sites.yml
Labels: topic: showcase

#13336 feat(showcase): add Pantene website
  docs/sites.yml
Labels: topic: showcase

#13354 docs: Update eslint documentation
  docs/docs/eslint.md
Labels: type: documentation

#13341 fix(docs): Two missing lines in "Adding pagination"
  docs/docs/adding-pagination.md
Labels: type: documentation

#12962 fix(docs): Update GraphQL description in Tutorial Part Zero
  docs/tutorial/part-zero/index.md
Labels: type: documentation

#13295 fix: Handle links to array of array of File nodes
  packages/gatsby/src/schema/__tests__/queries-file.js
  packages/gatsby/src/schema/resolvers.js
  packages/gatsby/src/schema/utils/__tests__/get-value-at.js
  packages/gatsby/src/schema/utils/get-value-at.js
Labels: bot: merge on green

#13369 chore(docs): removed language header from inline code block.
  docs/blog/2019-02-26-getting-started-with-gatsby-themes/index.md
Labels: topic: blogpost, type: documentation

#13370 chore(showcase): Add Prevue to Site Showcase
  docs/sites.yml
Labels: topic: showcase

#13063 refactor(gatsby): Refactor query calc query ids
  packages/gatsby/src/query/page-query-runner.js
  packages/gatsby/src/query/query-watcher.js
Labels: status: awaiting reviewer response

#10902 feat(docs): Create gatsby internationalization guide
  docs/docs/localization-i18n.md
  www/src/data/sidebars/doc-links.yaml
Labels: status: awaiting reviewer response, type: documentation

#13398 feat(showcase): Add krashna.nl site to the showcase
  docs/sites.yml
Labels: topic: showcase

#13397 chore(showcase): add Gold Medal Flour to site showcase
  docs/sites.yml
Labels: topic: showcase

#13064 refactor(gatsby): Split static/page queries
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/commands/develop.js
  packages/gatsby/src/query/page-query-runner.js
  packages/gatsby/src/query/queue.js
Labels: bot: merge on green, status: awaiting reviewer response

#13389 Websocket manager use page data
  packages/gatsby/src/utils/page-data.js
  packages/gatsby/src/utils/websocket-manager.js
Labels: status: awaiting reviewer response

#12688 chore(docs): tweak gatsby-node in ghost doc
  docs/docs/sourcing-from-ghost.md
Labels: type: documentation

#13431 feat(showcase): Add nikodemdeja.pl to showcase
  docs/sites.yml
Labels: topic: showcase

#13428 feat(blog): add blog post from allan pooley
  docs/blog/2019-04-19-your-website-should-be-built-with-gatsby/images/base64-images.jpg
  docs/blog/2019-04-19-your-website-should-be-built-with-gatsby/images/cdn.jpg
  docs/blog/2019-04-19-your-website-should-be-built-with-gatsby/images/littleandbig-site-performance.jpg
  docs/blog/2019-04-19-your-website-should-be-built-with-gatsby/images/mobile-web-pages.jpg
  docs/blog/2019-04-19-your-website-should-be-built-with-gatsby/images/website-landscape.jpg
  docs/blog/2019-04-19-your-website-should-be-built-with-gatsby/index.md
  docs/blog/author.yaml
  docs/blog/avatars/allan-pooley.jpg
Labels: topic: blogpost

#13051 docs: Install Node with Homebrew
  docs/tutorial/part-zero/index.md
Labels: status: awaiting author response, type: documentation

#13438 chore(showcase): Add zuyetawarmatrip.com to showcase
  docs/sites.yml
Labels: topic: showcase

#13170 fix(docs): improve Gatsby Image docs
  docs/docs/adding-images-fonts-files.md
  docs/docs/gatsby-project-structure.md
  docs/docs/images-and-files.md
  docs/docs/importing-assets-into-files.md
  docs/docs/importing-media-content.md
  docs/docs/static-folder.md
  docs/docs/using-gatsby-image.md
  docs/docs/working-with-images.md
  examples/using-gatsby-image/src/components/layout.js
  examples/using-gatsby-image/src/components/navigation.js
  examples/using-gatsby-image/src/pages/background-color.js
  examples/using-gatsby-image/src/pages/blur-up.js
  examples/using-gatsby-image/src/pages/prefer-webp.js
  examples/using-gatsby-image/src/pages/traced-svg.js
  www/gatsby-node.js
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#13424 feat(gatsby-plugin-google-tagmanager): Allow to place the GTM script …
  packages/gatsby-plugin-google-tagmanager/README.md
  packages/gatsby-plugin-google-tagmanager/package.json
  packages/gatsby-plugin-google-tagmanager/src/gatsby-ssr.js
Labels: status: awaiting author response

#11627 fix(docs): add description of contentDigest and clean up doc
  docs/docs/node-interface.md
Labels: type: documentation

#13435 chore(showcase): add sals-pals.net to showcase
  docs/sites.yml
Labels: topic: showcase

#13489 fix(gatsby-remark-images): update to accept alt as title when no title present
  packages/gatsby-remark-images/README.md
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/index.js
Labels: bot: merge on green

#13419 feat(docs): Update "Writing documentation with Docz"
  docs/docs/writing-documentation-with-docz.md
Labels: status: awaiting reviewer response, type: documentation

#13345 why we write
  docs/blog/2019-04-19-gatsby-why-we-write/index.md
Labels: status: awaiting reviewer response, topic: blogpost

#12521 fix(gatsby-plugin-netlify): add all .js files from webpack.stats.json to _headers
  packages/gatsby-plugin-netlify/src/build-headers-program.js
  packages/gatsby-plugin-netlify/src/plugin-data.js
Labels: bot: merge on green

#13499 docs(gatsby-plugin-remove-trailing-slashes): remove useless "that"
  packages/gatsby-plugin-remove-trailing-slashes/README.md
Labels: bot: merge on green

#13261 Reorganizing plugin docs
  docs/contributing/submit-to-plugin-library.md
  docs/docs/creating-a-local-plugin.md
  docs/docs/creating-plugins.md
  docs/docs/files-gatsby-looks-for-in-a-plugin.md
  docs/docs/how-plugins-work.md
  docs/docs/maintaining-a-plugin.md
  docs/docs/naming-a-plugin.md
  docs/docs/pixabay-source-plugin-tutorial.md
  docs/docs/plugins.md
  docs/docs/using-a-plugin-in-your-site.md
  docs/docs/what-is-a-plugin.md
  docs/docs/what-you-dont-need-plugins-for.md
  docs/loading-plugins-from-your-local-plugins-folder.md
  www/gatsby-node.js
  www/src/data/sidebars/doc-links.yaml
Labels: status: WIP

#13520 Fix spelling. GitHub not Github. JavaScript not Javascript. TypeScript not Typescript. GitLab not Gitlab.
  docs/accessibility-statement.md
  docs/blog/2018-10-16-why-mobile-performance-is-crucial/index.md
  docs/blog/2018-10-18-vscode-gatsby-development/index.md
  docs/blog/2018-10-26-export-a-drupal-site-to-gatsby/index.md
  docs/blog/2018-12-04-gatsby-analogy/index.md
  docs/blog/2018-12-17-turning-the-static-dynamic/index.md
  docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
  docs/blog/2019-03-11-dot-org-prototypes/index.md
  docs/blog/2019-04-19-gatsby-why-we-write/index.md
  docs/contributing/community-contributions.md
  docs/docs/adding-page-transitions-with-plugin-transition-link.md
  docs/docs/creating-a-starter.md
  docs/docs/debugging-cache-issues.md
  docs/docs/environment-variables.md
  docs/docs/gatsby-vendor-partnership.md
  docs/docs/localization-i18n.md
  docs/sites.yml
  docs/starters.yml
  examples/using-typescript/README.md
  examples/using-typescript/src/pages/index.tsx
  packages/gatsby/CHANGELOG.md
Labels: type: documentation

#13522 Fix spelling. TypeScript not typescript. Yarn not yarn. Netlify not netlify.
  azure-pipelines.yml
  docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
  docs/docs/adding-search-with-algolia.md
  docs/docs/hosting-on-netlify.md
  packages/gatsby-image/CHANGELOG.md
  packages/gatsby-plugin-netlify/README.md
  packages/gatsby-plugin-typescript/README.md
  packages/gatsby-transformer-react-docgen/CHANGELOG.md
  packages/gatsby/CHANGELOG.md
  packages/gatsby/src/utils/babel-parse-to-ast.js
Labels: status: assigned, type: documentation

#13523 feat(showcase) : add pella website
  docs/sites.yml
Labels: topic: showcase

#13526 feat(showcase): Add blog.nikodemdeja.pl to the showcase.
  docs/sites.yml
Labels: topic: showcase

#13527 fix(docs): Fix typo in Gatsby Browser APIs
  packages/gatsby/src/utils/api-browser-docs.js
Labels: type: documentation

#13539 chore: Fix typos
  docs/docs/adding-page-transitions-with-plugin-transition-link.md
  e2e-tests/development-runtime/cypress/integration/hot-reloading/arrow-functions.js
  packages/gatsby/src/redux/actions.js
Labels: bot: merge on green

#8992 chore(*): Use new createContentDigest helper
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/create-file-node.js
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/__tests__/on-node-create.js
  packages/gatsby-transformer-remark/src/on-node-create.js
  packages/gatsby/utils.js
Labels: bot: merge on green

#13566 feat(gatsby-image): Add durationFadeIn
  packages/gatsby-image/README.md
  packages/gatsby-image/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-image/src/__tests__/index.js
  packages/gatsby-image/src/index.js
Labels: status: awaiting author response

#11000 doc: update links to moved run-sift.js
  docs/docs/schema-sift.md
Labels: status: awaiting author response

#13491 fix(showcase): creator detail 'worked on' site list multiple lines
  docs/creators/creators.yml
  docs/creators/images/web-hart.jpg
  docs/sites.yml
  www/src/templates/template-creator-details.js
Labels: bot: merge on green

#13538 tests: add node 12 to tests
  .circleci/config.yml
Labels: status: blocked

#13563 feat(gatsby-transformer-yaml): support typeName
  packages/gatsby-transformer-yaml/README.md
  packages/gatsby-transformer-yaml/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-yaml/src/gatsby-node.js
Labels: status: awaiting author response

#12458 feat(docs): Adds "Adding Comments" guide
  docs/contributing/gatsby-style-guide.md
  docs/docs/adding-comments.md
  docs/docs/images/disqus-comments.png
  docs/docs/images/disqus-logo.svg
  www/src/data/sidebars/doc-links.yaml
Labels: status: awaiting reviewer response, type: documentation

#13510 feat(docs): Grouping stubs on Stub List
  www/src/pages/contributing/stub-list.js
Labels: status: awaiting reviewer response, type: documentation

#13500 docs(gatsby-cypress): add missing deps + more info + examples
  packages/gatsby-cypress/README.md
Labels: bot: merge on green

#12878 fix(gatsby-transformer-remark): fix excerpt generation - strip excessive white spaces, extract alt from images
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: bot: merge on green

#13629 docs: Add call to action for Stub List in Docs Contributions Page
  docs/contributing/docs-contributions.md
Labels: type: documentation

#13449 docs: update tutorial to useStaticQuery
  docs/tutorial/part-four/index.md
Labels: status: awaiting reviewer response

#12929 feat: add a community events page
  www/gatsby-config.js
  www/gatsby-node.js
  www/package.json
  www/src/components/events/event.js
  www/src/components/events/events.js
  www/src/data/sidebars/contributing-links.yaml
  www/src/hooks/use-community-events.js
  www/src/pages/contributing/events.js
Labels: 🎯Ecosystem

#11093 feat(gatsby-plugin-checker): add more filters to filter out bad packages
  scripts/gatsby-plugin-checker/README.md
  scripts/gatsby-plugin-checker/index.js
Labels: status: awaiting reviewer response

#13654 feat(showcase): Add justgraphql.com to showcase
  docs/sites.yml
Labels: topic: showcase

#13659 Added Stylo markdown writing app textually.net website.
  docs/sites.yml
Labels: topic: showcase

#13671 chore(showcase): add peter.macinkovic.id.au to showcase
  docs/sites.yml
Labels: topic: showcase

#13650 Add Penrose GDM to Gatsby sites
  docs/sites.yml
Labels: topic: showcase

#13640 [docs] Add Surge.sh deployment tutorial
  docs/docs/deploying-to-surge.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#13460 feat(blog): Add "What is Component Shadowing?" blog post
  docs/blog/2019-04-29-component-shadowing/index.md
  docs/blog/author.yaml
  docs/blog/avatars/john-otander.jpg
Labels: topic: blogpost

#13691 chore(showcase): add garethweaver.com
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#13694 chore(showcase): Add Holly Lodge Community Centre page to Site Showcase
  docs/sites.yml
Labels: topic: showcase

#13623 [WIP] [schema] Allow registering custom field extensions
  packages/gatsby/src/schema/add-field-resolvers.js
  packages/gatsby/src/schema/context.js
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/infer/__tests__/infer.js
  packages/gatsby/src/schema/infer/__tests__/merge-types.js
  packages/gatsby/src/schema/infer/index.js
  packages/gatsby/src/schema/schema-composer.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/date.js
  packages/gatsby/src/schema/types/directives.js
  packages/gatsby/src/utils/api-node-docs.js
Labels: status: WIP

#10897 chore(gatsby): add TypeScript definitions for config & plugin APIs
  packages/gatsby/index.d.ts
Labels: status: awaiting author response

#13731 fix(www): Update minimum required Gatsby version to 2.3.33
  www/package.json
Labels: type: documentation, type: maintenance

#13748 chore(ci): revert "tests: add node 12 to tests (#13538)"
  .circleci/config.yml
Labels: status: awaiting reviewer response, type: maintenance
