Repository gatsbyjs/gatsby, pull requests merged in 2019-01, with the labels that each got.

#10481 UX research blogpost
  docs/blog/2018-12-31-how-we-do-high-impact-ux-research/gatsby-days-dot-org-diagram.png
  docs/blog/2018-12-31-how-we-do-high-impact-ux-research/gatsby-days-dot-org-homepage.png
  docs/blog/2018-12-31-how-we-do-high-impact-ux-research/index.md
Labels: blogpost

#10476 feat(blog): Add "Gatsby scales with expertise & scope" blog post
  docs/blog/2018-12-19-gatsby-scales-with-expertise-and-scope/images/Gatsby-Scope-Expertise.png
  docs/blog/2018-12-19-gatsby-scales-with-expertise-and-scope/images/Venn_React-GraphQL-Web-Performance.jpg
  docs/blog/2018-12-19-gatsby-scales-with-expertise-and-scope/index.md
  docs/blog/author.yaml
  docs/blog/avatars/lekoarts.png
Labels: blogpost, status: confirmed

#10891 fix(gatsby-source-wordpress): add a check for namespaces in response from wp
  packages/gatsby-source-wordpress/src/fetch.js
Labels: type: bug

#10929 [tutorial] Rewrite the styles section
  docs/tutorial/part-three/about-uncentered.png
  docs/tutorial/part-three/index.md
  docs/tutorial/part-three/typography-centered.png
  docs/tutorial/part-three/typography-not-centered.png
  docs/tutorial/part-three/typography-styles.png
  docs/tutorial/part-three/with-navigation2.png
  docs/tutorial/part-two/css-modules-basic.png
  docs/tutorial/part-two/css-modules-userlist.png
  docs/tutorial/part-two/global-css.png
  docs/tutorial/part-two/index.md
  www/src/data/sidebars/tutorial-links.yaml
Labels: status: WIP

#10490 docs: Add "Develop and Deploy your own React monorepo app" blog post
  docs/blog/2019-01-01-publish-multiple-gatsby-sites/images/monorepo-diagram.jpeg
  docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
  docs/blog/author.yaml
  docs/blog/avatars/andrico-karoulla.jpg
Labels: blogpost

#11067 feat(blog): add "Modern publications with Gatsby & Ghost" post
  .forestry/front_matter/templates/blog.yml
  docs/blog/2019-01-14-modern-publications-with-gatsby-ghost.md
  docs/blog/author.yaml
  docs/blog/avatars/john-o-nolan.jpg
  docs/blog/images/gatsby-starter-ghost.jpg
  docs/blog/images/ghost-core-1.png
  docs/blog/images/ghost-headless-feature-image.png
  docs/blog/images/ghost-jamstack.png
Labels: blogpost

#9563 feat(gatsby-plugin-sharp): Add support for pngquant speed option
  packages/gatsby-plugin-sharp/README.md
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-transformer-sharp/src/extend-node-type.js
Labels: status: awaiting author response

#8899 feat(docs): update docs on Guess.js
  docs/docs/optimize-prefetching-with-guessjs.md
  docs/docs/optimizing-site-performance-with-guessjs.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#11152 fix(docs): Update adding-images-fonts-files.md
  docs/docs/adding-images-fonts-files.md
Labels: type: documentation

#10173 WIP Swag Store Case Study Post
  docs/blog/2018-11-27-swag-store/1_93222BZZGSWF__LBsgVvPg.jpg
  docs/blog/2018-11-27-swag-store/Screenshot 2018-12-05 15.19.14.png
  docs/blog/2018-11-27-swag-store/images/.gitkeep
  docs/blog/2018-11-27-swag-store/images/1_93222BZZGSWF__LBsgVvPg.jpg
  docs/blog/2018-11-27-swag-store/images/1_tzPNjNB2Lf0w_7mu21JDTQ.png
  docs/blog/2018-11-27-swag-store/images/giphy-1.gif
  docs/blog/2018-11-27-swag-store/images/money-shower.gif
  docs/blog/2018-11-27-swag-store/index.md
Labels: status: WIP

#11147 fix(docs): correct various grammatical errors and broken links
  docs/docs/add-page-metadata.md
  docs/docs/glamor.md
  docs/docs/making-your-site-accessible.md
  docs/docs/plugin-authoring.md
  docs/docs/plugins.md
  docs/docs/seo.md
  docs/tutorial/part-eight/index.md
  e2e-tests/README.md
  examples/README.md
Labels: type: documentation

#11115 fix(Docs) Correct some spelling and grammar in eCommerce tutorial
  docs/docs/ecommerce-tutorial/index.md
Labels: type: documentation

#10772 docs: Add stub articles for search guides
  docs/docs/adding-search-with-algolia.md
  docs/docs/adding-search-with-elasticlunr.md
  docs/docs/adding-search-with-js-search.md
  docs/docs/adding-search.md
  www/src/data/sidebars/doc-links.yaml
  www/src/templates/template-docs-markdown.js
Labels: status: awaiting author response

#10924 fix(gatsby-transformer-remark): don't convert Date objects
  packages/gatsby-transformer-remark/src/on-node-create.js
Labels: status: awaiting author response

#9499 Docs - Clarify how to pass state with Link
  docs/docs/gatsby-link.md
Labels: status: awaiting author response

#11244 feat(docs): add guide for ButterCMS
  docs/docs/headless-cms.md
  docs/docs/sourcing-from-buttercms.md
  docs/starters.yml
Labels: type: documentation

#10898 Added Documentation for using Tailwind with Gatsby
  docs/docs/tailwind-css.md
Labels: type: documentation

#11351 Add Daniel Wellington blog article
  docs/blog/2019-01-28-building-a-large-ecommerce-website-with-gatsby-at-daniel-wellington/index.md
  docs/blog/author.yaml
  docs/blog/avatars/thibaut-remy.jpg
Labels: blogpost

#10834 docs(blog): add Using React Context API with Gatsby post
  docs/blog/2019-01-31-using-react-context-api-with-gatsby/index.md
  docs/blog/author.yaml
  docs/blog/avatars/muhammad-muhsin.jpg
Labels: blogpost

#11356 feat(docs): add emotion as an option for styling
  docs/docs/emotion.md
  docs/docs/glamor.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#11210 docs: Document internal resource handling + SWs
  docs/docs/resource-handling-and-service-workers.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#11408 feat(blog): add flamingo case study
  docs/blog/2019-01-30-flamingo-case-study/images/flamingo.png
  docs/blog/2019-01-30-flamingo-case-study/images/lighthouse.png
  docs/blog/2019-01-30-flamingo-case-study/index.md
Labels: blogpost, status: WIP

#11174 feat(docs): Guide to integrate Docz
  docs/docs/writing-documentation-with-docz.md
  docs/starters.yml
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#11434 chore(renovate): Set semantic commit scope to starters
  renovate.json
Labels: type: maintenance

#11396 add child themes blogpost
  docs/blog/2019-01-29-themes-update-child-theming-and-component-shadowing/index.md
Labels: blogpost
