Repository gatsbyjs/gatsby, pull requests merged in 2020-09, with the labels that each got.

#26737 chore(gatsby-recipes): update snapshot
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
Labels: type: maintenance

#26745 chore(gatsby): bump lodash to fix vuln report
  packages/gatsby-cli/package.json
  packages/gatsby-dev-cli/package.json
  packages/gatsby-page-utils/package.json
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-netlify/package.json
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-plugin-page-creator/package.json
  packages/gatsby-recipes/package.json
  packages/gatsby-remark-autolink-headers/package.json
  packages/gatsby-remark-copy-linked-files/package.json
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-remark-images/package.json
  packages/gatsby-remark-responsive-iframe/package.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-shopify/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-telemetry/package.json
  packages/gatsby-theme/package.json
  packages/gatsby-transformer-remark/package.json
  packages/gatsby-transformer-toml/package.json
  packages/gatsby-transformer-xml/package.json
  packages/gatsby-transformer-yaml/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green

#26304 enhancement(docs): Remove excited.gif from the dictionary
  dictionary.txt
  docs/blog/2019-02-20-introducing-use-static-query/index.md
Labels: status: needs docs review

#26674 chore(docs): maintainers changes
  docs/contributing/how-to-label-an-issue.md
  docs/contributing/how-to-open-a-pull-request.md
  docs/contributing/images/github-topic-labels.png
  docs/contributing/images/github-type-labels.png
  docs/contributing/managing-pull-requests.md
  docs/contributing/triaging-github-issues/index.md
  docs/contributing/where-to-participate.md
Labels: type: documentation

#26718 chore(docs): Update visual-testing-with-storybook
  docs/docs/visual-testing-with-storybook.md
Labels: status: needs docs review

#26724 chore(actions): unschedule showcase validator action
  .github/workflows/schedule-site-showcase-validator-workflow.yml
Labels: status: inkteam assigned, topic: showcase

#26742 fix(docs): remove unused runInitialQuerys from dictionary.txt
  dictionary.txt
Labels: status: needs docs review

#26725 chore(docs): Update graphql to GraphQL
  packages/gatsby-transformer-excel/README.md
Labels: status: needs docs review

#26754 chore: Remove `www` from Renovate
  renovate.json5
Labels: bot: merge on green, type: maintenance

#26704 chore(docs): add Deploying to Bip tutorial
  dictionary.txt
  docs/docs/deploying-to-bip.md
  www/src/data/sidebars/doc-links.yaml
Labels: status: needs docs review, type: documentation

#26755 chore: Delete site showcase validator workflow
  .github/workflows/schedule-site-showcase-validator-workflow.yml
Labels: type: maintenance

#26753 chore(docs): fix typos in migrating-from-v1-to-v2
  docs/docs/migrating-from-v1-to-v2.md
Labels: type: documentation

#26433 Fix typo on L#218
  packages/gatsby-cli/src/structured-errors/error-map.ts
Labels: bot: merge on green, topic: cli

#26756 chore(benchmarks): Drop unused stuff from an mdx benchmark
  benchmarks/mdx-without-images/gatsby-config.js
  benchmarks/mdx-without-images/src/pages/#index.js#
Labels: status: triage needed

#26757 chore(benchmarks): move mdx-without-images to gabe-mdx and remove irrelevant deps
  benchmarks/gabe-mdx/.gitattributes
  benchmarks/gabe-mdx/.gitignore
  benchmarks/gabe-mdx/.prettierrc.js
  benchmarks/gabe-mdx/LICENSE
  benchmarks/gabe-mdx/README.md
  benchmarks/gabe-mdx/gatsby-browser.js
  benchmarks/gabe-mdx/gatsby-config.js
  benchmarks/gabe-mdx/gatsby-node.js
  benchmarks/gabe-mdx/gen.js
  benchmarks/gabe-mdx/package.json
  benchmarks/gabe-mdx/src/components/layout_1.js
  benchmarks/gabe-mdx/src/components/layout_2.js
  benchmarks/gabe-mdx/src/pages/index.js
  benchmarks/gabe-mdx/src/templates/article.js
  benchmarks/gabe-mdx/static/favicon.ico
  benchmarks/gabe-mdx/styles.css
Labels: topic: benchmarks

#26758 chore(benchmarks): cleanup gabe-mdx package.json
  benchmarks/gabe-mdx/package.json
Labels: status: triage needed

#26760 chore(benchmarks): Add markdown benchmark for gabe
  benchmarks/gabe-markdown/.gitignore
  benchmarks/gabe-markdown/LICENSE
  benchmarks/gabe-markdown/README.md
  benchmarks/gabe-markdown/gatsby-browser.js
  benchmarks/gabe-markdown/gatsby-config.js
  benchmarks/gabe-markdown/gatsby-node.js
  benchmarks/gabe-markdown/gen.js
  benchmarks/gabe-markdown/package.json
  benchmarks/gabe-markdown/src/components/bio.js
  benchmarks/gabe-markdown/src/components/layout.js
  benchmarks/gabe-markdown/src/components/seo.js
  benchmarks/gabe-markdown/src/pages/404.js
  benchmarks/gabe-markdown/src/pages/index.js
  benchmarks/gabe-markdown/src/templates/blog-post.js
  benchmarks/gabe-markdown/static/favicon.ico
  benchmarks/gabe-markdown/static/robots.txt
Labels: topic: benchmarks

#25454 fix(starters): Duplicate style value
  starters/default/src/components/layout.css
Labels: topic: starters

#26542 chore(docs): Add Utterances
  docs/docs/adding-comments.md
Labels: type: documentation

#26672 chore(docs): Update Deploy to Vercel documentation
  docs/docs/deploying-to-vercel.md
Labels: status: needs docs review

#26540 fix(doc): page graphiql explorer: add backlink to refresh content
  docs/docs/running-queries-with-graphiql.md
Labels: status: awaiting reviewer response, type: documentation

#26527 chore(tutorial): Clarify onCreateNode log in Tutorial
  docs/tutorial/part-seven/index.md
Labels: status: needs docs review

#26116 chore(docs): add asynchronous example to remark-plugin-tutorial
  docs/tutorial/remark-plugin-tutorial.md
Labels: type: documentation

#26764 fix(benchmarks): remove helmet stuff from gabe-markdown
  benchmarks/gabe-markdown/src/components/seo.js
  benchmarks/gabe-markdown/src/pages/404.js
  benchmarks/gabe-markdown/src/pages/index.js
  benchmarks/gabe-markdown/src/templates/blog-post.js
Labels: topic: benchmarks

#26425 chore(docs): Adding FastComments to comments doc
  docs/docs/adding-comments.md
Labels: type: documentation

#26767 docs: change references from codesandbox embeds to gatsby cloud
  docs/contributing/docs-contributions.md
  docs/docs/graphql-reference.md
  docs/docs/recipes/querying-data.md
Labels: status: triage needed, type: documentation

#26766 fix(gatsby-image): do not render the source tag if no srcSet is provided
  packages/gatsby-image/src/__tests__/index.js
  packages/gatsby-image/src/index.js
Labels: topic: images/media

#25810 chore(docs): add force install command
  packages/gatsby-dev-cli/README.md
Labels: topic: dev tooling

#26772 chore: Rename ZEIT to Vercel
  packages/gatsby-core-utils/README.md
  packages/gatsby-core-utils/src/ci.ts
Labels: type: maintenance

#25085 docs: show how to pass plugin options to Babel
  docs/docs/babel.md
Labels: type: documentation

#26362 docs(api-ssr-docs): Improve onRenderBody example
  packages/gatsby/cache-dir/api-ssr-docs.js
Labels: status: awaiting author response, type: documentation

#26022 enhancement(docs): Remove entries in dictionary.txt and fix alt text values in docs files
  dictionary.txt
  docs/docs/preprocessing-external-images.md
  docs/docs/sourcing-from-the-filesystem.md
  docs/tutorial/part-five/index.md
Labels: type: documentation

#26370 fix(docs): governance model -> fix 404 on internal links
  docs/contributing/gatsby-governance-model.md
Labels: status: awaiting reviewer response, type: documentation

#25212 fix(doc): updated onCreateBabelConfig documentation
  packages/gatsby/src/utils/api-node-docs.ts
Labels: status: needs core review, type: chore, type: documentation

#25155 chore(docs): apache troubleshooting section to gatsby-plugin-manifest
  packages/gatsby-plugin-manifest/README.md
Labels: type: documentation

#25022 chore(docs): Documented that location does not include href
  docs/docs/location-data-from-props.md
Labels: type: documentation

#26778 fix(gatsby): tap just into main compilation in webpack-dep-tree-plugin
  packages/gatsby/src/commands/build-javascript.ts
Labels: topic: StaticQuery

#26748 Add additional logging around conditional page builds
  packages/gatsby/src/commands/build.ts
Labels: topic: conditional page builds*

#26779 chore(gatsby-telemetry): Generate typings
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
  packages/gatsby-telemetry/package.json
  packages/gatsby-telemetry/src/index.ts
  packages/gatsby-telemetry/src/telemetry.ts
  packages/gatsby-telemetry/tsconfig.json
Labels: topic: TypeScript migration

#26805 fix(gatsby): catch when lock already unlocked
  packages/gatsby/src/commands/develop.ts
Labels: bot: merge on green

#26799 chore(docs): Remove "simply" wordpress-source-plugin-tutorial
  docs/tutorial/wordpress-source-plugin-tutorial.md
Labels: status: triage needed

#26781 fix(gatsby-cli): Fix typo (repeated ://)
  packages/gatsby/src/commands/develop.ts
Labels: topic: cli

#26780 chore: changes according to policy update -> removed old info
  peril/README.md
Labels: type: documentation

#26819 chore(gatsby-transformer-remark): undo const->let change
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: type: chore

#26807 fix(gatsby-plugin-page-creator) Add missing chokidar dependency
  packages/gatsby-plugin-page-creator/package.json
Labels: status: triage needed

#26818 fix(gatsby-recipes): Normalise recipes snapshots
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
Labels: bot: merge on green, topic: recipes

#26806 fix(gatsby-plugin-sharp): Don't swallow sharp errors
  packages/gatsby-plugin-sharp/src/sharp-error.js
Labels: bot: merge on green, status: needs core review, topic: sharp

#26808 fix(gatsby): Run mutations during query running
  packages/gatsby/src/services/types.ts
  packages/gatsby/src/state-machines/__tests__/develop.ts
  packages/gatsby/src/state-machines/develop/actions.ts
  packages/gatsby/src/state-machines/develop/index.ts
Labels: bot: merge on green, status: needs core review, topic: state machine

#26822 fix(gatsby): fix `$in` operator to return unique elements
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/schema/__tests__/run-query.js
Labels: bot: merge on green, topic: GraphQL, type: bug

#26824 chore(gatsby): revert #26636; and pin uuid to v3.4.0
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/reporter/redux/internal-actions.ts
  packages/gatsby-plugin-benchmark-reporting/package.json
  packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/scheduler.js
  packages/gatsby-recipes/package.json
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/gatsby-node.js
  packages/gatsby-telemetry/package.json
  packages/gatsby-telemetry/src/in-memory-store.ts
  packages/gatsby-telemetry/src/telemetry.ts
  packages/gatsby/package.json
  packages/gatsby/src/redux/__tests__/jobsv2.js
  packages/gatsby/src/utils/__tests__/jobs-manager.js
  packages/gatsby/src/utils/create-node-id.ts
  packages/gatsby/src/utils/jobs-manager.ts
  yarn.lock
Labels: bot: merge on green, topic: npm*

#26825 Revert "fix(gatsby-recipes): Add mdx packages to rollup"
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/rollup.config.js
Labels: topic: MDX, topic: npm*

#26787 fix(gatsby): Properly slugify fields with periods
  packages/gatsby-plugin-page-creator/package.json
  packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
  packages/gatsby-plugin-page-creator/src/derive-path.ts
  yarn.lock
Labels: topic: internal, type: bug

#26821 tests(gatsby-recipes): Use mock fs and fetch
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/providers/fs/__snapshots__/directory.test.js.snap
  packages/gatsby-recipes/src/providers/fs/__snapshots__/file.test.js.snap
  packages/gatsby-recipes/src/providers/fs/directory.js
  packages/gatsby-recipes/src/providers/fs/directory.test.js
  packages/gatsby-recipes/src/providers/fs/file.test.js
  yarn.lock
Labels: bot: merge on green, topic: recipes

#26826 revert(gatsby-plugin-sharp): update dependencies
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/process-file.js
  yarn.lock
Labels: topic: npm*, topic: sharp

#26770 fix(gatsby-source-filesystem) Clarify createFilePath docs
  packages/gatsby-source-filesystem/README.md
Labels: topic: filesystem, type: documentation

#26833 fix(gatsby-recipes): Cache readme and always return string
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
Labels: bot: merge on green, topic: recipes

#24271 fix(gatsby-plugin-mdx): mdxrender should not accept components
  packages/gatsby-plugin-mdx/index.d.ts
  packages/gatsby-plugin-mdx/mdx-renderer.js
Labels: topic: MDX

#26837 tests(gatsby-recipes): Mock loading of readme from unpkg
  packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
  packages/gatsby-recipes/src/providers/gatsby/shadow-file.test.js
  packages/gatsby-recipes/src/providers/gatsby/site-metadata.test.js
  packages/gatsby-recipes/src/test-helper.js
Labels: status: needs core review, topic: recipes

#26838 Revert "revert(gatsby-plugin-sharp): update dependencies"
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/process-file.js
  yarn.lock
Labels: topic: sharp

#26699 fix(gatsby-recipes): renable e2e test for npm package resource & fix dev/prod resource bug
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package.test.js.snap
  packages/gatsby-recipes/src/providers/npm/fixtures/package-json/package.json
  packages/gatsby-recipes/src/providers/npm/fixtures/scripts/package.json
  packages/gatsby-recipes/src/providers/npm/package-json.test.js
  packages/gatsby-recipes/src/providers/npm/package.js
  packages/gatsby-recipes/src/providers/npm/package.test.js
  packages/gatsby-recipes/src/providers/npm/script.test.js
Labels: topic: recipes

#26841 fix(renovate): remove prettier from "packages" group
  renovate.json5
Labels: status: triage needed

#26847 fix(gatsby): Run actions while recreating pages and draining mutation queue
  packages/gatsby/src/state-machines/data-layer/actions.ts
  packages/gatsby/src/state-machines/data-layer/index.ts
  packages/gatsby/src/state-machines/develop/index.ts
  packages/gatsby/src/state-machines/waiting/actions.ts
  packages/gatsby/src/state-machines/waiting/index.ts
Labels: bot: merge on green, status: needs core review, topic: state machine

#26842 fix(yarn.lock): reduce monorepo vulnerabilities by over 1000x
  yarn.lock
Labels: status: needs core review, topic: dev tooling

#26810 fix(gatsby): do not initialize cache in onPreInit API
  packages/gatsby/src/utils/__tests__/api-runner-node.js
  packages/gatsby/src/utils/api-runner-node.js
Labels: status: needs core review

#26848 fix(gatsby): Handle node mutations immediately after file change
  packages/gatsby/src/state-machines/waiting/index.ts
Labels: bot: merge on green, topic: state machine

#26782 chore(docs): Fix and simplify VS Code launch.json
  docs/docs/debugging-the-build-process.md
Labels: type: documentation

#26840 Allow for double slashes on windows
  packages/gatsby/src/utils/__tests__/test-require-error.ts
  packages/gatsby/src/utils/test-require-error.ts
Labels: bot: merge on green, status: awaiting author response, topic: windows*

#26853 feat(gatsby): start telemetry server on gatsby develop for Admin
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/telemetry-server.ts
Labels: topic: cli

#26610 feat(gatsby-starter-blog): Post schema tags
  starters/blog/src/pages/index.js
  starters/blog/src/templates/blog-post.js
Labels: topic: starters

#26525 feat(gatsby-remark-prismjs): syntax highlighting inside diffs
  packages/gatsby-remark-prismjs/README.md
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/highlight-code.js.snap
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js
  packages/gatsby-remark-prismjs/src/__tests__/index.js
  packages/gatsby-remark-prismjs/src/highlight-code.js
  packages/gatsby-remark-prismjs/src/index.js
Labels: topic: Markdown/remark

#26870 chore(docs): Minor Typo In Tutorial - Theme-UI Directive
  docs/tutorial/building-a-theme.md
Labels: type: documentation

#26832 feat(gatsby): create telemetry service and start it during develop
  packages/gatsby-telemetry/src/index.ts
  packages/gatsby/package.json
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/telemetry-server.ts
Labels: topic: telemetry*

#26634 chore(gatsby-plugin-preact): update prefresh
  packages/gatsby-plugin-preact/package.json
  yarn.lock
Labels: status: needs core review

#26886 chore(docs): Fix broken links in blog-netlify-cms-tutorial
  docs/tutorial/blog-netlify-cms-tutorial/index.md
Labels: type: documentation

#26885 feat(gatsby-admin): track plugin telemetry
  packages/gatsby-admin/gatsby-config.js
  packages/gatsby-admin/src/components/providers.tsx
  packages/gatsby-admin/src/components/services-provider.tsx
  packages/gatsby-admin/src/pages/plugins.tsx
  packages/gatsby-admin/src/urql-client.ts
  packages/gatsby-admin/src/utils/use-telemetry.tsx
  packages/gatsby/src/utils/telemetry-server.ts
Labels: topic: admin

#26864 feat(gatsby): merge GraphQL types defined by different plugins (with a warning)
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green, topic: GraphQL

#26876 Security: Switch isomorphic-fetch to cross-fetch
  packages/gatsby-admin/src/components/recipes-gui/index.js
  packages/gatsby-recipes/package.json
  yarn.lock
Labels: topic: npm*, topic: recipes, type: maintenance

#26678 fix(gatsby-admin): logo link
  packages/gatsby-admin/src/components/navbar.tsx
Labels: topic: admin

#26891 chore: fix renovate configuration
  renovate.json5
Labels: bot: merge on green, status: needs core review, type: maintenance

#26892 chore: update renovate config
  renovate.json5
Labels: status: needs core review, type: maintenance

#26868 fix(gatsby): resend pageData when socket disconnect
  packages/gatsby/cache-dir/socketIo.js
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/websocket-manager.ts
Labels: status: awaiting reviewer response, topic: frontend-core

#26902 feat(gatsby-admin): track pageviews to telemetry
  packages/gatsby-admin/src/components/layout.tsx
  packages/gatsby-admin/src/components/pageview-tracker.tsx
  packages/gatsby-admin/src/utils/use-telemetry.tsx
Labels: topic: admin

#26903 feat(gatsby-admin): track errors
  packages/gatsby-admin/package.json
  packages/gatsby-admin/src/components/error-tracker.tsx
  packages/gatsby-admin/src/components/providers.tsx
  packages/gatsby-admin/src/utils/use-telemetry.tsx
  packages/gatsby-telemetry/src/error-helpers.ts
  packages/gatsby/src/utils/telemetry-server.ts
  yarn.lock
Labels: topic: admin

#26887 chore(gatsby-cli): bundle ink logger
  packages/gatsby-cli/.babelrc
  packages/gatsby-cli/non-rollup-babel.config.js
  packages/gatsby-cli/package.json
  packages/gatsby-cli/rollup.config.js
  yarn.lock
Labels: type: maintenance

#26904 fix(gatsby-cli): pass --verbose flag to gatsby build properly
  packages/gatsby/src/commands/build.ts
Labels: bot: merge on green, topic: cli

#26866 feat(gatsby): add `Site` and `SiteSiteMetadata` to built-in GraphQL types
  e2e-tests/development-runtime/cypress/integration/types/site-data.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/src/pages/site-data.js
  e2e-tests/production-runtime/cypress/integration/types/site-data.js
  e2e-tests/production-runtime/src/pages/site-data.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/built-in-types.ts
Labels: bot: merge on green, topic: GraphQL

#26097 fix(gatsby-image): Don't assume DOM state is valid at hydration stage
  packages/gatsby-image/src/index.js
Labels: topic: images/media, type: bug

#26907 feat(gatsby): print node counts in CLI
  packages/gatsby/src/services/create-pages.ts
  packages/gatsby/src/services/source-nodes.ts
Labels: topic: cli

#26632 add Flotiq benchmark code
  benchmarks/source-flotiq/.env.example
  benchmarks/source-flotiq/LICENSE
  benchmarks/source-flotiq/README.md
  benchmarks/source-flotiq/gatsby-config.js
  benchmarks/source-flotiq/gatsby-node.js
  benchmarks/source-flotiq/package.json
  benchmarks/source-flotiq/scripts/data-update.js
  benchmarks/source-flotiq/scripts/updater.js
  benchmarks/source-flotiq/src/components/layout_1.js
  benchmarks/source-flotiq/src/components/layout_2.js
  benchmarks/source-flotiq/src/pages/index.js
  benchmarks/source-flotiq/src/styles/styles.css
  benchmarks/source-flotiq/src/templates/article.js
  benchmarks/source-flotiq/static/favicon.ico
Labels: topic: benchmarks

#24490 docs(gatsby-plugin-manifest): Allow icons to be used without a mask on other devices
  packages/gatsby-plugin-manifest/README.md
Labels: status: needs core review, topic: PWA, type: bug

#26000 chore(gatsby): expose full structured logs over the develop status websocket server
  e2e-tests/development-runtime/cypress.json
  e2e-tests/development-runtime/cypress/integration/functionality/restarting-prompt.js
  e2e-tests/development-runtime/cypress/plugins/gatsby-config.js
  e2e-tests/development-runtime/cypress/plugins/index.js
  packages/gatsby/cache-dir/app.js
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/restarting-screen.ts
Labels: status: inkteam assigned

#26916 feat(gatsby-admin): prompt to restart develop process on config changes
  packages/gatsby-admin/gatsby-config.js
  packages/gatsby-admin/package.json
  packages/gatsby-admin/src/components/navbar.tsx
  packages/gatsby-admin/src/utils/use-develop-logs.ts
  yarn.lock
Labels: status: triage needed, topic: admin

#26611 feat(gatsby): add babel-lodash plugin to reduce lodash filesize
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/bootstrap/load-plugins/load.ts
  packages/gatsby/src/internal-plugins/bundle-optimisations/gatsby-node.js
  packages/gatsby/src/internal-plugins/bundle-optimisations/index.js
  packages/gatsby/src/internal-plugins/bundle-optimisations/package.json
  packages/gatsby/src/internal-plugins/bundle-optimisations/polyfills/fetch.js
  packages/gatsby/src/internal-plugins/bundle-optimisations/polyfills/no-op.js
  packages/gatsby/src/internal-plugins/bundle-optimisations/polyfills/object-assign.js
  packages/gatsby/src/internal-plugins/bundle-optimisations/polyfills/whatwg-fetch.js
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: bot: merge on green, topic: frontend-core, topic: performance

#26921 Revert "chore(gatsby-cli): bundle ink logger (#26887)"
  packages/gatsby-cli/.babelrc
  packages/gatsby-cli/non-rollup-babel.config.js
  packages/gatsby-cli/package.json
  packages/gatsby-cli/rollup.config.js
  yarn.lock
Labels: bot: merge on green, topic: cli

#26389 chore(docs): remove remaining spectrum references
  docs/blog/100days/accessibility/index.md
  docs/blog/100days/apps/index.md
  docs/blog/100days/cms/index.md
  docs/blog/100days/comments/index.md
  docs/blog/100days/create-themes/index.md
  docs/blog/100days/free-hosting/index.md
  docs/blog/100days/gatsby-image/index.md
  docs/blog/100days/index.md
  docs/blog/100days/mdx/index.md
  docs/blog/100days/performance/index.md
  docs/blog/100days/pwa/index.md
  docs/blog/100days/react-component/index.md
  docs/blog/100days/seo/index.md
  docs/blog/100days/serverless/index.md
  docs/blog/100days/start-blog/index.md
  docs/blog/100days/use-themes/index.md
  docs/contributing/gatsby-style-guide.md
  packages/gatsby/README.md
  starters/README.md
Labels: status: awaiting reviewer response, type: documentation

#26733 chore(gatsby): Migrate types/node-interface.js to TypeScript
  packages/gatsby/src/schema/types/node-interface.ts
Labels: bot: merge on green, topic: TypeScript migration

#26929 perf(gabe): add gabe-csv-text benchmark
  benchmarks/gabe-csv-text/.gitignore
  benchmarks/gabe-csv-text/LICENSE
  benchmarks/gabe-csv-text/README.md
  benchmarks/gabe-csv-text/gatsby-browser.js
  benchmarks/gabe-csv-text/gatsby-config.js
  benchmarks/gabe-csv-text/gatsby-node.js
  benchmarks/gabe-csv-text/gen.js
  benchmarks/gabe-csv-text/package.json
  benchmarks/gabe-csv-text/src/components/bio.js
  benchmarks/gabe-csv-text/src/components/layout.js
  benchmarks/gabe-csv-text/src/pages/404.js
  benchmarks/gabe-csv-text/src/pages/index.js
  benchmarks/gabe-csv-text/src/templates/blog-post.js
  benchmarks/gabe-csv-text/static/favicon.ico
  benchmarks/gabe-csv-text/static/robots.txt
Labels: bot: merge on green, topic: benchmarks

#26936 fix(benchmarks): add missing plugin to package.json
  benchmarks/gabe-csv-text/package.json
Labels: status: triage needed

#26940 fix(gatsby): Finish running queries if source files change
  packages/gatsby/src/state-machines/query-running/actions.ts
  packages/gatsby/src/state-machines/query-running/index.ts
Labels: status: needs core review, topic: state machine

#26711 chore(gatsby): enable parallel terser runs on WSL
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack-utils.ts
  yarn.lock
Labels: topic: webpack/babel

#26844 Fix gatsby-plugin-manifest using withAssetPrefix in manifest file link, where it gets improperly sanitized
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-manifest/src/gatsby-browser.js
  packages/gatsby-plugin-manifest/src/gatsby-ssr.js
Labels: status: needs core review, topic: PWA

#26923 chore(renovate): allow updates to Gatsby packages immediately after publish
  renovate.json5
Labels: type: maintenance

#26935 chore(gatsby-source-contentful): README typo
  packages/gatsby-source-contentful/README.md
Labels: type: documentation

#26949 chore(benchmarks): move gabe-mdx
  benchmarks/gabe-fs-mdx/.gitattributes
  benchmarks/gabe-fs-mdx/.gitignore
  benchmarks/gabe-fs-mdx/.prettierrc.js
  benchmarks/gabe-fs-mdx/LICENSE
  benchmarks/gabe-fs-mdx/README.md
  benchmarks/gabe-fs-mdx/gatsby-browser.js
  benchmarks/gabe-fs-mdx/gatsby-config.js
  benchmarks/gabe-fs-mdx/gatsby-node.js
  benchmarks/gabe-fs-mdx/gen.js
  benchmarks/gabe-fs-mdx/package.json
  benchmarks/gabe-fs-mdx/src/components/layout_1.js
  benchmarks/gabe-fs-mdx/src/components/layout_2.js
  benchmarks/gabe-fs-mdx/src/pages/index.js
  benchmarks/gabe-fs-mdx/src/templates/article.js
  benchmarks/gabe-fs-mdx/static/favicon.ico
  benchmarks/gabe-fs-mdx/styles.css
Labels: status: triage needed

#26856 feat(gatsby-cli): enable set packagemanager
  integration-tests/gatsby-cli/__tests__/new.js
  integration-tests/gatsby-cli/__tests__/options.js
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby-cli/src/init-starter.ts
  packages/gatsby-cli/src/util/package-manager.ts
  scripts/publish-starters.sh
Labels: topic: cli

#26829 chore: write graphql schema, fragments and config file to cache
  packages/gatsby-plugin-graphql-config/.babelrc
  packages/gatsby-plugin-graphql-config/.gitignore
  packages/gatsby-plugin-graphql-config/.npmignore
  packages/gatsby-plugin-graphql-config/README.md
  packages/gatsby-plugin-graphql-config/package.json
  packages/gatsby-plugin-graphql-config/src/gatsby-node.ts
  packages/gatsby-plugin-graphql-config/src/index.ts
  packages/gatsby-plugin-graphql-config/tsconfig.json
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/reducers/definitions.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/types.ts
Labels: status: needs core review, topic: GraphQL

#26977 perf(benchmarks): add gabe-csv-markdown benchmark
  benchmarks/gabe-csv-markdown/README.md
  benchmarks/gabe-csv-markdown/gatsby-browser.js
  benchmarks/gabe-csv-markdown/gatsby-config.js
  benchmarks/gabe-csv-markdown/gatsby-node.js
  benchmarks/gabe-csv-markdown/gen.js
  benchmarks/gabe-csv-markdown/package.json
  benchmarks/gabe-csv-markdown/src/pages/index.js
  benchmarks/gabe-csv-markdown/src/templates/blog-post.js
Labels: topic: benchmarks

#26971 tests: fix integration test
  integration-tests/cache-resilience/__tests__/cache.js
  integration-tests/cache-resilience/package.json
  integration-tests/structured-logging/__tests__/ipc-send.js
  integration-tests/structured-logging/__tests__/logs.js
  integration-tests/structured-logging/__tests__/panic.js
  integration-tests/structured-logging/__tests__/status.js
  integration-tests/structured-logging/__tests__/to-do.js
  integration-tests/structured-logging/package.json
Labels: bot: merge on green, type: maintenance

#26970 fix(gatsby-plugin-graphql-config): add dependencies
  packages/gatsby-plugin-graphql-config/.npmignore
  packages/gatsby-plugin-graphql-config/package.json
  packages/gatsby-plugin-graphql-config/src/gatsby-node.ts
Labels: type: maintenance

#26976 fix(gatsby-remark-copy-linked-files): respect assetPrefix
  packages/gatsby-remark-copy-linked-files/src/__tests__/index.js
  packages/gatsby-remark-copy-linked-files/src/index.js
Labels: bot: merge on green, topic: Markdown/remark, type: bug

#26950 fix(gatsby-cli): circular type dependency
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby-cli/src/init-starter.ts
  packages/gatsby-cli/tsconfig.json
Labels: topic: TypeScript*

#26943 chore: Add starters to README
  starters/README.md
Labels: topic: starters, type: documentation

#26982 chore(docs): Set correct path to the image
  docs/tutorial/part-five/index.md
Labels: type: documentation

#26986 fix(gatsby-theme-blog): ThemeUI folder location
  starters/gatsby-starter-blog-theme/src/gatsby-plugin-theme-ui/index.js
Labels: topic: themes

#26452 feat(gatsby): Expose typescript transpiler to default site in plugin list
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/bootstrap/load-plugins/load.ts
Labels: status: needs core review, topic: TypeScript*

#26689 update gatsby-interface dependency
  packages/gatsby-admin/package.json
  packages/gatsby-recipes/package.json
Labels: bot: merge on green, topic: admin, topic: recipes

#26673 chore(docs): rename the Github learning team
  .github/PULL_REQUEST_TEMPLATE.md
  CODEOWNERS
  docs/contributing/docs-templates.md
  docs/contributing/docs-writing-process.md
  docs/contributing/how-to-write-a-reference-guide.md
  docs/contributing/how-to-write-a-tutorial.md
  docs/contributing/managing-pull-requests.md
Labels: type: documentation

#26985 fix(docs): Remove `--save` from install prompts
  docs/docs/add-a-manifest-file.md
  docs/docs/add-a-service-worker.md
  docs/docs/add-offline-support-with-a-service-worker.md
  docs/docs/add-page-metadata.md
  docs/docs/adding-an-rss-feed.md
  docs/docs/adding-analytics.md
  docs/docs/adding-markdown-pages.md
  docs/docs/adding-page-transitions-with-plugin-transition-link.md
  docs/docs/adding-search-with-js-search.md
  docs/docs/building-an-ecommerce-site-with-shopify.md
  docs/docs/creating-a-sitemap.md
  docs/docs/creating-a-transformer-plugin.md
  docs/docs/creating-slugs-for-pages.md
  docs/docs/data-fetching.md
  docs/docs/emotion.md
  docs/docs/gatsby-image.md
  docs/docs/glossary/decoupled-drupal.md
  docs/docs/glossary/headless-wordpress.md
  docs/docs/glossary/markdown.md
  docs/docs/glossary/mdx.md
  docs/docs/glossary/wpgraphql.md
  docs/docs/migrating-from-v0-to-v1.md
  docs/docs/migrating-from-v1-to-v2.md
  docs/docs/porting-an-html-site-to-gatsby.md
  docs/docs/porting-from-create-react-app-to-gatsby.md
  docs/docs/post-css.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/recipes/styling-css.md
  docs/docs/sass.md
  docs/docs/setting-up-gatsby-without-gatsby-new.md
  docs/docs/sourcing-content-from-json-or-yaml.md
  docs/docs/sourcing-from-contentful.md
  docs/docs/sourcing-from-flotiq.md
  docs/docs/sourcing-from-gentics-mesh.md
  docs/docs/sourcing-from-ghost.md
  docs/docs/sourcing-from-graphcms.md
  docs/docs/sourcing-from-netlify-cms.md
  docs/docs/sourcing-from-prismic.md
  docs/docs/sourcing-from-sanity.md
  docs/docs/sourcing-from-seams-cms.md
  docs/docs/sourcing-from-the-filesystem.md
  docs/docs/sourcing-from-woocommerce.md
  docs/docs/styled-components.md
  docs/docs/tailwind-css.md
  docs/docs/themes/converting-a-starter.md
  docs/docs/themes/getting-started.md
  docs/docs/troubleshooting-common-errors.md
  docs/docs/upgrade-gatsby-and-dependencies.md
  docs/docs/using-a-plugin-in-your-site.md
  docs/docs/using-gatsby-image.md
  docs/docs/why-gatsby-uses-graphql.md
  docs/docs/working-with-images-in-markdown.md
  docs/tutorial/part-eight/index.md
  docs/tutorial/part-five/index.md
  docs/tutorial/part-four/index.md
  docs/tutorial/part-six/index.md
  docs/tutorial/part-three/index.md
  docs/tutorial/prismic-source-graphql-tutorial.md
  docs/tutorial/wordpress-image-tutorial.md
  docs/tutorial/writing-documentation-with-docz.md
Labels: type: documentation

#27003 fix(gatsby): Recognise null pages as not found
  e2e-tests/development-runtime/cypress/integration/navigation/redirect.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/pages/redirect-me.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/src/utils/websocket-manager.ts
Labels: bot: merge on green, topic: reach/router and Links

#26914 fix(gatsby-plugin-mdx): Fix not passing file path to remark plugins
  e2e-tests/mdx/gatsby-config.js
  packages/gatsby-plugin-mdx/utils/gen-mdx.js
Labels: topic: MDX

#27001 feat(gatsby-starter-blog): Remove typography.js
  starters/blog/content/blog/hello-world/index.md
  starters/blog/gatsby-browser.js
  starters/blog/gatsby-config.js
  starters/blog/gatsby-node.js
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/blog/src/components/bio.js
  starters/blog/src/components/layout.js
  starters/blog/src/normalize.css
  starters/blog/src/pages/index.js
  starters/blog/src/pages/using-typescript.tsx
  starters/blog/src/style.css
  starters/blog/src/templates/blog-post.js
  starters/blog/src/utils/typography.js
Labels: topic: starters

#27005 chore(benchmarks): cleanup the gabe benchmarks a bit
  benchmarks/gabe-csv-markdown/.gitignore
  benchmarks/gabe-csv-markdown/gen.js
  benchmarks/gabe-csv-text/.gitignore
  benchmarks/gabe-csv-text/gen.js
  benchmarks/gabe-fs-markdown/.gitignore
  benchmarks/gabe-fs-mdx/.gitignore
Labels: status: triage needed

#27004 perf(benchmarks): add a fs-text benchmark
  benchmarks/gabe-fs-text/.gitignore
  benchmarks/gabe-fs-text/LICENSE
  benchmarks/gabe-fs-text/README.md
  benchmarks/gabe-fs-text/gatsby-browser.js
  benchmarks/gabe-fs-text/gatsby-config.js
  benchmarks/gabe-fs-text/gatsby-node.js
  benchmarks/gabe-fs-text/gen.js
  benchmarks/gabe-fs-text/package.json
  benchmarks/gabe-fs-text/src/components/bio.js
  benchmarks/gabe-fs-text/src/components/layout.js
  benchmarks/gabe-fs-text/src/pages/404.js
  benchmarks/gabe-fs-text/src/pages/index.js
  benchmarks/gabe-fs-text/src/templates/blog-post.js
  benchmarks/gabe-fs-text/static/favicon.ico
  benchmarks/gabe-fs-text/static/robots.txt
Labels: topic: benchmarks

#27008 fix benchmark name
  benchmarks/gabe-csv-text/README.md
Labels: status: triage needed

#27009 chore(gatsby-plugin-graphql-config): README typos
  packages/gatsby-plugin-graphql-config/README.md
Labels: type: documentation

#26937 fix(build): remove stale page-data files
  integration-tests/artifacts/__tests__/index.js
  integration-tests/artifacts/__tests__/static-queries.js
  integration-tests/artifacts/gatsby-node.js
  integration-tests/artifacts/src/templates/dummy.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/utils/page-data.ts
  yarn.lock
Labels: topic: stale-artifacts*

#27013 chore: Fix dirty lock file
  yarn.lock
Labels: bot: merge on green, type: maintenance

#27015 perf(benchmarks): add json and yaml benchmarks for gabe
  benchmarks/gabe-fs-json/.gitignore
  benchmarks/gabe-fs-json/LICENSE
  benchmarks/gabe-fs-json/README.md
  benchmarks/gabe-fs-json/gatsby-browser.js
  benchmarks/gabe-fs-json/gatsby-config.js
  benchmarks/gabe-fs-json/gatsby-node.js
  benchmarks/gabe-fs-json/gen.js
  benchmarks/gabe-fs-json/package.json
  benchmarks/gabe-fs-json/src/components/bio.js
  benchmarks/gabe-fs-json/src/components/layout.js
  benchmarks/gabe-fs-json/src/pages/404.js
  benchmarks/gabe-fs-json/src/pages/index.js
  benchmarks/gabe-fs-json/src/templates/blog-post.js
  benchmarks/gabe-fs-json/static/favicon.ico
  benchmarks/gabe-fs-json/static/robots.txt
  benchmarks/gabe-fs-yaml/.gitignore
  benchmarks/gabe-fs-yaml/LICENSE
  benchmarks/gabe-fs-yaml/README.md
  benchmarks/gabe-fs-yaml/gatsby-browser.js
  benchmarks/gabe-fs-yaml/gatsby-config.js
  benchmarks/gabe-fs-yaml/gatsby-node.js
  benchmarks/gabe-fs-yaml/gen.js
  benchmarks/gabe-fs-yaml/package.json
  benchmarks/gabe-fs-yaml/src/components/bio.js
  benchmarks/gabe-fs-yaml/src/components/layout.js
  benchmarks/gabe-fs-yaml/src/pages/404.js
  benchmarks/gabe-fs-yaml/src/pages/index.js
  benchmarks/gabe-fs-yaml/src/templates/blog-post.js
  benchmarks/gabe-fs-yaml/static/favicon.ico
  benchmarks/gabe-fs-yaml/static/robots.txt
Labels: topic: benchmarks

#27012 feat(gatsby-recipes): Add a built in recipe for Gatsby Image
  packages/gatsby-recipes/recipes/gatsby-image.mdx
  packages/gatsby-recipes/src/recipes-list.js
Labels: topic: recipes

#27018 Fix gatsby-cli changes for yarn2
  packages/gatsby-cli/src/init-starter.ts
Labels: topic: cli

#26176 chore(docs): add fonts and typography reference guide
  dictionary.txt
  docs/blog/2019-04-25-plugin-authoring-study/index.md
  docs/docs/using-local-fonts.md
  docs/docs/using-typography-js.md
  docs/docs/using-web-fonts.md
  docs/docs/working-with-fonts-and-typography.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#27021 chore: Update link to retext-smartypants
  packages/gatsby-remark-smartypants/README.md
Labels: type: documentation

#27043 chore(gatsby-admin): track feedback button clicks
  packages/gatsby-admin/src/components/navbar.tsx
Labels: bot: merge on green, topic: admin

#27044 chore(benchmarks): clean up and make gabe benchmarks consistent
  benchmarks/gabe-csv-markdown/gatsby-browser.js
  benchmarks/gabe-csv-markdown/gatsby-node.js
  benchmarks/gabe-csv-markdown/gen.js
  benchmarks/gabe-csv-markdown/src/pages/index.js
  benchmarks/gabe-csv-markdown/src/templates/blog-post.js
  benchmarks/gabe-csv-text/gatsby-browser.js
  benchmarks/gabe-csv-text/gatsby-node.js
  benchmarks/gabe-csv-text/gen.js
  benchmarks/gabe-csv-text/src/pages/index.js
  benchmarks/gabe-csv-text/src/templates/blog-post.js
  benchmarks/gabe-fs-json/gatsby-browser.js
  benchmarks/gabe-fs-json/gatsby-node.js
  benchmarks/gabe-fs-json/gen.js
  benchmarks/gabe-fs-json/src/pages/index.js
  benchmarks/gabe-fs-json/src/templates/blog-post.js
  benchmarks/gabe-fs-markdown/gatsby-browser.js
  benchmarks/gabe-fs-markdown/gatsby-node.js
  benchmarks/gabe-fs-markdown/gen.js
  benchmarks/gabe-fs-markdown/src/pages/index.js
  benchmarks/gabe-fs-markdown/src/templates/blog-post.js
  benchmarks/gabe-fs-mdx/gatsby-browser.js
  benchmarks/gabe-fs-mdx/gatsby-node.js
  benchmarks/gabe-fs-mdx/gen.js
  benchmarks/gabe-fs-mdx/src/components/layout.js
  benchmarks/gabe-fs-mdx/src/pages/404.js
  benchmarks/gabe-fs-mdx/src/pages/index.js
  benchmarks/gabe-fs-mdx/src/templates/blog-post.js
  benchmarks/gabe-fs-text/gatsby-node.js
  benchmarks/gabe-fs-text/src/pages/index.js
  benchmarks/gabe-fs-text/src/templates/blog-post.js
  benchmarks/gabe-fs-yaml/gatsby-browser.js
  benchmarks/gabe-fs-yaml/gatsby-node.js
  benchmarks/gabe-fs-yaml/gen.js
  benchmarks/gabe-fs-yaml/src/pages/index.js
  benchmarks/gabe-fs-yaml/src/templates/blog-post.js
Labels: status: triage needed

#26653 fix: migrate from request to alternative modules
  integration-tests/gatsby-pipeline/__tests__/lazy-image-build/develop.js
  integration-tests/gatsby-pipeline/package.json
  packages/gatsby-dev-cli/package.json
  packages/gatsby-dev-cli/src/utils/check-deps-changes.js
  yarn.lock
Labels: topic: dev tooling

#27046 chore: update renovate split per package
  package.json
  renovate.json5
Labels: type: maintenance

#27040 fix(docs): remove README.md not displaying on Gatsby plugin library
  packages/gatsby-cypress/package.json
  packages/gatsby-plugin-coffeescript/package.json
  packages/gatsby-plugin-postcss/package.json
  packages/gatsby-plugin-sass/package.json
  packages/gatsby-plugin-stylus/package.json
Labels: bot: merge on green, type: maintenance

#27049 docs: updated https
  docs/blog/gatsby-v1.md
Labels: type: documentation

#27050 docs: readme
  README.md
Labels: status: triage needed

#27048 chore: Update index.md
  docs/blog/2018-07-17-announcing-gatsby-preview/index.md
Labels: status: triage needed

#26913 chore: update some nonbreaking packages from the <1.0.0-minor Renovate group
  examples/using-gatsby-without-graphql/package.json
  examples/using-jest/package.json
  examples/using-js-search/package.json
  examples/using-local-plugins/package.json
  examples/using-reach-skip-nav/package.json
  packages/gatsby-codemods/package.json
  packages/gatsby-plugin-guess-js/package.json
  packages/gatsby-plugin-mdx/loaders/mdx-loader.test.js
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-hacker-news/package.json
  packages/gatsby-source-lever/package.json
  packages/gatsby-source-medium/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-transformer-excel/package.json
  packages/gatsby-transformer-react-docgen/package.json
  packages/gatsby-transformer-screenshot/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green, type: maintenance

#27053 chore(benchmarks): more appropriate gabe benchmark naming
  benchmarks/gabe-json-text/.gitignore
  benchmarks/gabe-json-text/LICENSE
  benchmarks/gabe-json-text/README.md
  benchmarks/gabe-json-text/gatsby-config.js
  benchmarks/gabe-json-text/gatsby-node.js
  benchmarks/gabe-json-text/gen.js
  benchmarks/gabe-json-text/package.json
  benchmarks/gabe-json-text/src/components/bio.js
  benchmarks/gabe-json-text/src/components/layout.js
  benchmarks/gabe-json-text/src/pages/404.js
  benchmarks/gabe-json-text/src/pages/index.js
  benchmarks/gabe-json-text/src/templates/blog-post.js
  benchmarks/gabe-json-text/static/favicon.ico
  benchmarks/gabe-json-text/static/robots.txt
  benchmarks/gabe-yaml-text/.gitignore
  benchmarks/gabe-yaml-text/LICENSE
  benchmarks/gabe-yaml-text/README.md
  benchmarks/gabe-yaml-text/gatsby-config.js
  benchmarks/gabe-yaml-text/gatsby-node.js
  benchmarks/gabe-yaml-text/gen.js
  benchmarks/gabe-yaml-text/package.json
  benchmarks/gabe-yaml-text/src/components/bio.js
  benchmarks/gabe-yaml-text/src/components/layout.js
  benchmarks/gabe-yaml-text/src/pages/404.js
  benchmarks/gabe-yaml-text/src/pages/index.js
  benchmarks/gabe-yaml-text/src/templates/blog-post.js
  benchmarks/gabe-yaml-text/static/favicon.ico
  benchmarks/gabe-yaml-text/static/robots.txt
Labels: status: triage needed

#26809 fix(gatsby): set proper cacheIdentifier for babel
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
  packages/gatsby/src/utils/babel-loader.js
  packages/gatsby/src/utils/webpack-utils.ts
Labels: status: needs core review, topic: webpack/babel

#27037 chore(gatsby-transformer-csv): update csv processors
  packages/gatsby-transformer-csv/package.json
  packages/gatsby-transformer-csv/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-csv/src/gatsby-node.js
  yarn.lock
Labels: topic: transformers

#26974 fix(gatsby): PageProps TS type: add `params`
  packages/gatsby/index.d.ts
Labels: bot: merge on green, topic: TypeScript*

#26956 fix(gatsby-plugin-preact): use new babel plugin for better context compat
  packages/gatsby-plugin-preact/package.json
  packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
Labels: bot: merge on green, type: chore

#27038 chore: update micromatch
  packages/gatsby-page-utils/package.json
  packages/gatsby-page-utils/src/ignore-path.ts
  packages/gatsby-page-utils/src/validate-path.ts
  packages/gatsby/package.json
  packages/gatsby/src/redux/run-fast-filters.ts
Labels: type: maintenance

#26946 fix(gatsby-plugin-manifest): re-use domain connection
  packages/gatsby-plugin-manifest/src/__tests__/__snapshots__/gatsby-ssr.js.snap
  packages/gatsby-plugin-manifest/src/gatsby-ssr.js
Labels: bot: merge on green, topic: PWA

#27022 fix(gatsby-remark-autolink-headers): option to disable "position: relative" when icon is not present
  packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-autolink-headers/src/index.js
Labels: topic: Markdown/remark

#27125 chore(docs): remove extra "you" (typo)
  docs/docs/recipes/working-with-plugins.md
Labels: status: triage needed
