Repository gatsbyjs/gatsby, pull requests merged in 2020-04, with the labels that each got.

#22604 [docs]Docs/Blog Frontmatter Documentation
  docs/contributing/docs-and-blog-components.md
Labels: type: documentation

#22705 fix(gatsby-plugin-google-gtag): OutboundLink Forward Ref
  packages/gatsby-plugin-google-gtag/src/index.js
Labels: bot: merge on green

#22720 docs: clarification about `.cache` and `public` persistance when using GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES
  docs/docs/page-build-optimizations-for-incremental-data-changes.md
Labels: type: documentation

#22727 Fix typo
  docs/blog/2020-03-26-service-relief-project/index.md
Labels: topic: blogpost

#22739 chore(gatsby-cli): use `gatsby clean` in tests to test `gatsby clean`
  integration-tests/gatsby-cli/__tests__/build.js
  integration-tests/gatsby-cli/__tests__/develop.js
Labels: bot: merge on green

#22737 Add blog post for community Q&A
  docs/blog/2020-04-02-community-qa-with-kyle-mathews/index.md
Labels: topic: blogpost

#22745 fix(gatsby-source-contentful): use request url for base64 image cache key
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: bot: merge on green

#22690 chore(starters): add gatsby-starter-reason-blog
  docs/starters.yml
Labels: status: awaiting author response, topic: showcase

#22736 Add blog post with Gatsby LA video 2 - Dustin Schau
  docs/blog/2020-04-02-LA-2020-Schau/index.md
Labels: topic: blogpost

#22686 Added Fluiditype
  docs/sites.yml
Labels: status: awaiting author response, topic: showcase

#22692 chore(starters): add gatsby-starter-builder
  docs/starters.yml
Labels: status: awaiting author response, topic: showcase

#22738 chore(gatsby) Migrate joi schema to Typescript
  packages/gatsby-cli/src/structured-errors/__tests__/error-schema.ts
  packages/gatsby-cli/src/structured-errors/construct-error.ts
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-cli/src/structured-errors/error-schema.ts
  packages/gatsby-cli/src/structured-errors/types.ts
  packages/gatsby/index.d.ts
  packages/gatsby/package.json
  packages/gatsby/src/joi-schemas/__tests__/__snapshots__/joi.ts.snap
  packages/gatsby/src/joi-schemas/__tests__/joi.ts
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/redux/actions/public.js
  yarn.lock
Labels: bot: merge on green, type: TypeScript migration

#22752 fix(gatsby): Fix OOM from telemetry storing too much
  packages/gatsby/src/query/graphql-runner.ts
Labels: bot: merge on green

#22799 (blog) 100days challenge 14
  docs/blog/100days/use-themes/index.md
Labels: topic: blogpost

#22771 docs: add missing quote
  docs/docs/recipes/working-with-plugins.md
Labels: type: documentation

#22802 Blog case study commonwealth aten
  docs/blog/2020-04-06-commonwealth-aten-case-study/commonwealth_scorecard_redesign.png
  docs/blog/2020-04-06-commonwealth-aten-case-study/index.md
  docs/blog/author.yaml
  docs/blog/avatars/debra-combs.png
Labels: topic: blogpost

#22807 Fix incorrect benchmark working directory
  .circleci/config.yml
Labels: bot: merge on green

#22790 chore(showcase): Add hanarecafe.com to the Showcase
  docs/sites.yml
Labels: topic: showcase

#22371 Adding www.kosmosandkaos.is to the sites.yml file
  docs/sites.yml
Labels: status: awaiting author response, topic: showcase

#22698 chore(starters): update gatsby-theme-oss
  docs/starters.yml
Labels: topic: showcase

#22712 chore(starters): add gatsby-starter-song
  docs/starters.yml
Labels: topic: showcase

#22756 chore(starters): add gatsby-starter-22boxes-uno
  docs/starters.yml
Labels: topic: showcase

#22769 Update sites.yml
  docs/sites.yml
Labels: topic: showcase

#22362 chore(showcase): Add ocius.com.au to showcase
  docs/sites.yml
Labels: bot: merge on green, status: awaiting author response, topic: showcase

#22787 Update Zestard.com site for showcase
  docs/sites.yml
Labels: topic: showcase

#22837 chore(starters): add gatsby-starter-basic-bootstrap
  docs/starters.yml
Labels: topic: showcase

#22839 chore(sites): Add covid19.thegauntlet.ca
  docs/sites.yml
Labels: topic: showcase

#22848 fix(gatsby-source-graphql): Convert ts to plain js until better times
  packages/gatsby-source-graphql/src/batching/__tests__/dataloader-link.js
  packages/gatsby-source-graphql/src/batching/__tests__/merge-queries.js
  packages/gatsby-source-graphql/src/batching/dataloader-link.js
  packages/gatsby-source-graphql/src/batching/merge-queries.js
Labels: bot: merge on green

#22836 Added mrkaluzny.com
  docs/docs/telemetry.md
  docs/sites.yml
Labels: topic: showcase

#22850 chore(starters): add gatsby-starter-kontent-lumen
  docs/starters.yml
Labels: topic: showcase

#22767 Add docs/hydration entry.
  docs/docs/glossary.md
  docs/docs/glossary/hydration.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal

#22835 chore(starters): gatsby-ts-tw-styled-eslint-starter
  docs/starters.yml
Labels: topic: showcase

#22775 🏠 showcase bradgarropy.com
  docs/sites.yml
Labels: topic: showcase

#22861 fix(recipes): Don't duplicate plugin configuration by default
  packages/gatsby/src/recipes/providers/fs/file.test.js
  packages/gatsby/src/recipes/providers/gatsby/__snapshots__/plugin.test.js.snap
  packages/gatsby/src/recipes/providers/gatsby/plugin.js
  packages/gatsby/src/recipes/providers/gatsby/plugin.test.js
Labels: status: WIP

#22796 Blog virtual gatsby days cfp
  docs/blog/2020-04-07-virtual-gatsby-days-2020-CFP/index.md
  docs/blog/author.yaml
  docs/blog/avatars/laci-texter.jpg
Labels: topic: blogpost

#22793 Blog gatsby days LA video 4
  docs/blog/2020-04-05-LA-2020-Gladwell.md
  docs/blog/2020-04-06-LA-2020-Gordon/index.md
Labels: topic: blogpost

#22820 docs: fix references to undefined data variable
  docs/tutorial/seo-and-social-sharing-cards-tutorial/index.md
Labels: type: documentation

#22864 feat(recipes): Generate graphql schema from resources
  packages/gatsby/package.json
  packages/gatsby/src/recipes/__snapshots__/create-types.test.js.snap
  packages/gatsby/src/recipes/create-types.js
  packages/gatsby/src/recipes/create-types.test.js
  packages/gatsby/src/recipes/graphql.js
  packages/gatsby/src/recipes/providers/fs/__snapshots__/file.test.js.snap
  packages/gatsby/src/recipes/providers/fs/file.js
  packages/gatsby/src/recipes/providers/gatsby/__snapshots__/plugin.test.js.snap
  packages/gatsby/src/recipes/providers/gatsby/plugin.js
  packages/gatsby/src/recipes/providers/gatsby/plugin.test.js
  packages/gatsby/src/recipes/providers/npm/__snapshots__/package-json.test.js.snap
  packages/gatsby/src/recipes/providers/npm/package-json.js
  packages/gatsby/src/recipes/providers/npm/package-json.test.js
  packages/gatsby/src/recipes/providers/resource-test-helper.js
Labels: status: WIP

#22866 Date Change for virtual Gatsby Days
  docs/blog/2020-04-07-virtual-gatsby-days-2020-CFP/index.md
Labels: topic: blogpost

#22786 Improve README for twitter plugin
  packages/gatsby-plugin-twitter/README.md
Labels: type: documentation

#22870 Add Gatsby Days LA video blog 5
  docs/blog/2020-04-07-LA-2020-Boss/index.md
Labels: topic: blogpost

#22851 Use v8 serialize for context
  packages/gatsby/src/query/graphql-runner.ts
Labels: bot: merge on green

#22882 chore(benchmarks): Add ability to fix broken images for contentful sites
  benchmarks/source-contentful/README.md
  benchmarks/source-contentful/bin/site.js
  benchmarks/source-contentful/package.json
Labels: bot: merge on green

#22628 chore(docs): Add Snipcart reference guide
  docs/docs/adding-a-shopping-cart-with-snipcart.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#22648 Recipe google analytics
  docs/docs/recipes.md
  docs/docs/recipes/deploying-your-site.md
Labels: type: documentation

#22814 Add TUKUTTEMITA LAB to sites.yml
  docs/sites.yml
Labels: topic: showcase

#22020 fix(blog): Building multilingual sites with Gatsby
  docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/index.md
Labels: topic: blogpost

#22931 Virtual Gatsby Days CFP time change and typo fix
  docs/blog/2020-04-07-virtual-gatsby-days-2020-CFP/index.md
Labels: topic: blogpost

#22934 Add Gatsby Days LA video blog 9 Empowering Content Creators with Head…
  docs/blog/2020-04-13-LA-2020-Comeau/index.md
Labels: topic: blogpost

#22892 (blog)Create challenge 15
  docs/blog/100days/create-themes/index.md
Labels: topic: blogpost

#22869 chore(gatsby-cli): Migrate reporter to TypeScript
  package.json
  packages/gatsby-cli/src/index.ts
  packages/gatsby-cli/src/reporter/__tests__/index.js
  packages/gatsby-cli/src/reporter/catch-exit-signals.ts
  packages/gatsby-cli/src/reporter/index.js
  packages/gatsby-cli/src/reporter/index.ts
  packages/gatsby-cli/src/reporter/patch-console.ts
  packages/gatsby-cli/src/reporter/reporter-phantom.ts
  packages/gatsby-cli/src/reporter/reporter-progress.ts
  packages/gatsby-cli/src/reporter/reporter-timer.ts
  packages/gatsby-cli/src/reporter/reporter.ts
  packages/gatsby-cli/src/reporter/start-logger.ts
  packages/gatsby-cli/src/reporter/types.js
  packages/gatsby-cli/src/reporter/types.ts
  yarn.lock
Labels: type: TypeScript migration

#22810 chore(gatsby): Convert redux/reducers/redirects to typescript
  packages/gatsby/src/redux/reducers/__tests__/redirects.ts
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/redirects.js
  packages/gatsby/src/redux/reducers/redirects.ts
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green, type: TypeScript migration

#22959 fix(gatsby): Use tmp dir for tmp redux cache folder
  packages/gatsby/src/redux/persist.ts
Labels: bot: merge on green

#22947 Add Gatsby Days LA video 11
  docs/blog/2020-04-15-LA-2020-estevez/index.md
Labels: topic: blogpost

#22946 Add video blog post 10 for April 14th
  docs/blog/2020-04-14-LA-2020-Kim/index.md
Labels: topic: blogpost

#22860 refactor: migrate graphql-runner into TypeScript
  packages/gatsby/src/bootstrap/__tests__/__snapshots__/create-graphql-runner.js.snap
  packages/gatsby/src/bootstrap/__tests__/create-graphql-runner.js
  packages/gatsby/src/bootstrap/create-graphql-runner.ts
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/types.ts
Labels: bot: merge on green, type: TypeScript migration

#22956 maintenance(www) value to check if i18n is enabled for this build
  www/gatsby-config.js
  www/gatsby-node.js
  www/src/components/I18nContext.js
  www/src/utils/i18n.js
Labels: topic: i18n

#22798 chore(doc): Add using cloudinary plugin for images to reference guides.
  docs/docs/using-cloudinary-image-service.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#22943 docs: update creating source plugins guide & add example repo
  docs/docs/creating-a-source-plugin.md
  docs/docs/creating-a-transformer-plugin.md
  examples/creating-source-plugins/README.md
  examples/creating-source-plugins/api/README.md
  examples/creating-source-plugins/api/package.json
  examples/creating-source-plugins/api/src/index.js
  examples/creating-source-plugins/api/src/schema.graphql
  examples/creating-source-plugins/example-site/README.md
  examples/creating-source-plugins/example-site/gatsby-config.js
  examples/creating-source-plugins/example-site/package.json
  examples/creating-source-plugins/example-site/src/pages/index.js
  examples/creating-source-plugins/example-site/static/favicon.ico
  examples/creating-source-plugins/package.json
  examples/creating-source-plugins/source-plugin/README.md
  examples/creating-source-plugins/source-plugin/gatsby-node.js
  examples/creating-source-plugins/source-plugin/index.js
  examples/creating-source-plugins/source-plugin/package.json
Labels: type: documentation

#22898 fix(gatsby-source-drupal): Verify nodes exist before looping through them
  packages/gatsby-source-drupal/src/utils.js
Labels: bot: merge on green, topic: Drupal

#22929 chore(scripts): Fix grammar in comment
  scripts/e2e-test.sh
Labels: bot: merge on green

#22774 fix: create unique Nodes
  packages/gatsby-transformer-documentationjs/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-documentationjs/src/gatsby-node.js
Labels: bot: merge on green

#22747 feat(gatsby-cli): allow --recursive git url
  packages/gatsby-cli/src/init-starter.ts
Labels: bot: merge on green

#22967 Automate i18n sync
  .circleci/config.yml
Labels: topic: i18n

#22981 fix(scripts/i18n) Make the sync script work better for integration
  scripts/i18n/sync.js
Labels: topic: i18n

#22942 Adds NPM article.
  docs/docs/glossary.md
  docs/docs/glossary/npm.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal

#22297 chore(gatsby): Migrate redux/actions/types and redux/actions/restricted to TypeScript
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/actions/restricted.js
  packages/gatsby/src/redux/actions/restricted.ts
  packages/gatsby/src/redux/actions/types.js
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green, type: TypeScript migration

#22854 chore(gatsby): properly typed return types of replaceHydrateFunction
  packages/gatsby/index.d.ts
Labels: bot: merge on green

#22638 fix(gatsby-plugin-mdx): Truncate non-latin language excerpts correctly
  packages/gatsby-plugin-mdx/README.md
  packages/gatsby-plugin-mdx/gatsby/source-nodes.js
Labels: bot: merge on green

#22881 Add Jamify.me to sites.yml
  docs/sites.yml
Labels: topic: showcase

#23007 Fix misspelling of Dustin's last name in blog post
  docs/blog/2020-04-02-LA-2020-Schau/index.md
Labels: topic: blogpost

#22750 Added doc for absolute import from gatsby eslint rules or other tools
  docs/docs/add-custom-webpack-config.md
Labels: type: documentation

#21907 feat(remark-embed-snippet): embed specific lines
  packages/gatsby-remark-embed-snippet/README.md
  packages/gatsby-remark-embed-snippet/src/__tests__/index.js
  packages/gatsby-remark-embed-snippet/src/index.js
Labels: bot: merge on green

#22985 Add blog post Agility CMS upgrades to Gatsby with author avatar
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/index.md
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/post-image-1.png
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/post-image-2.png
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/post-image-3.png
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/post-image-4.png
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/post-image-5.png
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/post-image-6.png
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/post-image-7.png
  docs/blog/author.yaml
  docs/blog/avatars/joel-varty.jpg
Labels: topic: blogpost

#23015 docs: Update spelling error in 2020-04-05 blog post
  docs/blog/2020-04-05-LA-2020-Gladwell/index.md
Labels: topic: blogpost

#23029 fix(gatsby): Use `moveSync` over `renameSync` to fix cross mount cases
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/persist.ts
Labels: bot: merge on green

#22843 fix(plugin-sitemap): missing data in query results
  packages/gatsby-plugin-sitemap/src/__tests__/internals.js
  packages/gatsby-plugin-sitemap/src/internals.js
Labels: bot: merge on green, type: bug

#22965 fix: Ensure component order is deterministic
  packages/gatsby/src/bootstrap/__tests__/requires-writer.js
  packages/gatsby/src/bootstrap/requires-writer.js
Labels: bot: merge on green

#23046 chore(wordpress-benchmark): upgrade to latest packages and remove unneeded packages
  benchmarks/source-wordpress/package.json
Labels: bot: merge on green

#22960 Update starters.yml
  docs/starters.yml
Labels: topic: showcase

#23042 chore(starters): update gatsby-starter-typescript
  docs/starters.yml
Labels: topic: showcase

#23053 chore(docs): fix e-commerce showcase link
  docs/docs/building-an-e-commerce-site.md
Labels: type: chore

#23048 Adds duetocovid19.com to sites.yml
  docs/sites.yml
Labels: topic: showcase

#23021 fix(gatsby-cli): Fix console methods incorrectly handling falsy values
  packages/gatsby-cli/src/reporter/__tests__/patch-console.ts
  packages/gatsby-cli/src/reporter/patch-console.ts
Labels: bot: merge on green

#23056 Update tagging
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/index.md
Labels: topic: blogpost

#23028 Update tailwind-css.md
  docs/docs/tailwind-css.md
Labels: type: documentation

#23060 Add Virtual Gatsby Days registration blog post
  docs/blog/2020-04-14-virtual-gatsby-days-registration/index.md
  docs/blog/2020-04-14-virtual-gatsby-days-registration/virutalGatsbyDays.jpg
Labels: topic: blogpost

#22788 chore(starters): add gatsby-redux-toolkit-typescript-starter
  docs/starters.yml
Labels: topic: showcase

#22858 chore(starters): add gatsby-custom-tailwind
  docs/starters.yml
Labels: topic: showcase

#22883 chore(sites): add whilenext.com
  docs/sites.yml
Labels: topic: showcase

#22954 chore(starters): add gatsby-starter-ts
  docs/starters.yml
Labels: topic: showcase

#23063 feat(recipes): Implement shadow file resource and test it
  packages/gatsby/src/recipes/providers/fs/file.js
  packages/gatsby/src/recipes/providers/gatsby/__snapshots__/plugin.test.js.snap
  packages/gatsby/src/recipes/providers/gatsby/__snapshots__/shadow-file.test.js.snap
  packages/gatsby/src/recipes/providers/gatsby/fixtures/gatsby-config.js
  packages/gatsby/src/recipes/providers/gatsby/fixtures/gatsby-starter-blog/gatsby-config.js
  packages/gatsby/src/recipes/providers/gatsby/fixtures/gatsby-starter-hello-world/gatsby-config.js
  packages/gatsby/src/recipes/providers/gatsby/fixtures/node_modules/gatsby-theme-blog/src/components/author.js
  packages/gatsby/src/recipes/providers/gatsby/plugin.test.js
  packages/gatsby/src/recipes/providers/gatsby/shadow-file.js
  packages/gatsby/src/recipes/providers/gatsby/shadow-file.test.js
Labels: topic: recipes

#23069 fix (www) Fix mobile nav bar text
  www/src/components/navigation-mobile.js
Labels: topic: i18n

#23043 Add The Cares Family to Showcase
  docs/sites.yml
Labels: topic: showcase

#23095 Revert "fix(gatsby): Set a timeout of 15 seconds on queries"
  packages/gatsby/src/query/queue.js
Labels: bot: merge on green

#23096 chore(gatsby): Test sift filtering on date instances (skipped for now)
  packages/gatsby/src/schema/__tests__/node-model.js
Labels: bot: merge on green

#23086 feat(Recipes): Show list of recipes when one isn't passed in
  packages/gatsby/package.json
  packages/gatsby/src/recipes/README.md
  packages/gatsby/src/recipes/cli.js
  packages/gatsby/src/recipes/mdx-src/emotion.mdx
  packages/gatsby/src/recipes/mdx-src/gatsby-plugin-layout.mdx
  packages/gatsby/src/recipes/mdx-src/gatsby-theme-blog.mdx
  packages/gatsby/src/recipes/mdx-src/jest.mdx
  packages/gatsby/src/recipes/mdx-src/prettier-git-hook.mdx
  packages/gatsby/src/recipes/mdx-src/sass.mdx
  packages/gatsby/src/recipes/mdx-src/theme-ui.mdx
  packages/gatsby/src/recipes/parser/__snapshots__/parser.test.js.snap
  packages/gatsby/src/recipes/providers/npm/package-json.js
  packages/gatsby/src/recipes/recipe-machine.js
  packages/gatsby/src/recipes/todo.md
  packages/gatsby/src/recipes/validate-steps.js
Labels: topic: recipes

#23103 chore(gatsby-source-graphql): Use GraphQL Tools again
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/__tests__/gatsby-node.js
  packages/gatsby-source-graphql/src/gatsby-node.js
  packages/gatsby-source-graphql/src/transforms.js
  yarn.lock
Labels: bot: merge on green

#23108 feat(recipes): Move recipes to a standalone package
  packages/gatsby-recipes/README.md
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/recipes/emotion.mdx
  packages/gatsby-recipes/recipes/eslint.mdx
  packages/gatsby-recipes/recipes/gatsby-plugin-layout.mdx
  packages/gatsby-recipes/recipes/gatsby-theme-blog
  packages/gatsby-recipes/recipes/gatsby-theme-blog.mdx
  packages/gatsby-recipes/recipes/jest.mdx
  packages/gatsby-recipes/recipes/prettier-git-hook.mdx
  packages/gatsby-recipes/recipes/sass.mdx
  packages/gatsby-recipes/recipes/theme-ui.mdx
  packages/gatsby/src/recipes/parser/__snapshots__/parser.test.js.snap
  packages/gatsby/src/recipes/parser/fixtures/prettier-git-hook.mdx
  packages/gatsby/src/recipes/parser/index.js
  packages/gatsby/src/recipes/parser/parser.test.js
  packages/gatsby/src/recipes/todo.md
Labels: topic: recipes

#23111 blog post urging Gatsby community members to meet virtually, not in p…
  docs/blog/2020-04-15-get-together-by-staying-apart-for-now/index.md
Labels: topic: blogpost

#23078 Bigger changes
  packages/gatsby/src/recipes/README.md
Labels: topic: recipes

#23113 fix(www) Fix translated aria-label for sidebar section toggles
  www/src/components/sidebar/section-title.js
  www/src/data/locales/en/messages.po
  www/src/data/locales/ja/messages.po
Labels: topic: i18n

#23132 chore(showcase): Cleaning up showcase
  docs/sites.yml
Labels: topic: showcase

#21574 docs: split up docs templates into different pages
  docs/contributing/docs-templates.md
  docs/contributing/how-to-write-a-plugin-readme.md
  docs/contributing/how-to-write-a-recipe.md
  docs/contributing/how-to-write-a-reference-guide.md
  docs/contributing/how-to-write-a-starter-readme.md
  docs/contributing/how-to-write-a-tutorial.md
  docs/contributing/submit-to-plugin-library.md
  docs/contributing/translation/maintainers.md
  www/src/data/sidebars/contributing-links.yaml
Labels: type: documentation

#22185 feat(gatsby-theme-blog): Refactor some larger components to be smaller
  packages/gatsby-theme-blog/src/components/post-date.js
  packages/gatsby-theme-blog/src/components/post-link.js
  packages/gatsby-theme-blog/src/components/post-list.js
  packages/gatsby-theme-blog/src/components/post-title.js
  packages/gatsby-theme-blog/src/components/post.js
  packages/gatsby-theme-blog/src/components/posts.js
  packages/gatsby-theme-blog/src/components/seo.js
Labels: topic: themes

#22292 chore(gatsby-cli): migrate redux folder to typescript
  packages/gatsby-cli/src/reporter/__tests__/index.js
  packages/gatsby-cli/src/reporter/catch-exit-signals.ts
  packages/gatsby-cli/src/reporter/redux/actions.js
  packages/gatsby-cli/src/reporter/redux/actions.ts
  packages/gatsby-cli/src/reporter/redux/index.js
  packages/gatsby-cli/src/reporter/redux/index.ts
  packages/gatsby-cli/src/reporter/redux/internal-actions.ts
  packages/gatsby-cli/src/reporter/redux/reducer.ts
  packages/gatsby-cli/src/reporter/redux/types.ts
  packages/gatsby-cli/src/reporter/redux/utils.ts
  packages/gatsby-cli/src/reporter/reporter-phantom.ts
  packages/gatsby-cli/src/reporter/reporter-progress.ts
  packages/gatsby-cli/src/reporter/reporter-timer.ts
  packages/gatsby-cli/src/reporter/reporter.ts
  packages/gatsby/src/redux/reducers/index.js
Labels: type: TypeScript migration

#23146 chore(recipes): Add codeowners to gatsby-recipes
  CODEOWNERS
  packages/gatsby-recipes/src/todo.md
Labels: topic: recipes

#23154 chore(recipes): fix stuff
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/cli.js
  packages/gatsby-recipes/src/joi-to-graphql/helpers/joi-to-graphql.js
  packages/gatsby-recipes/src/joi-to-graphql/methods/compose-schema.js
  packages/gatsby-recipes/src/joi-to-graphql/methods/compose-type.js
  packages/gatsby/src/commands/recipes.ts
Labels: topic: recipes

#23152 fix(recipes): Update tests and fix babel config, tweak readme
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/recipes/cypress.mdx
  packages/gatsby-recipes/src/README.md
  packages/gatsby-recipes/src/providers/gatsby/fixtures/node_modules/gatsby-theme-blog/src/components/author.js
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
  packages/gatsby-recipes/src/providers/npm/__snapshots__/script.test.js.snap
  packages/gatsby-recipes/src/todo.md
Labels: topic: recipes

#23136 chore(docs): Add section to document best practice usage of pageContext
  docs/docs/creating-and-modifying-pages.md
Labels: type: documentation

#23157 fix(docs): update programmatically-creating-pages.md add missing shortcodes
  docs/docs/mdx/programmatically-creating-pages.md
Labels: bot: merge on green

#23155 fix(docs): recipe google analytics - fix 404 link
  docs/docs/recipes/deploying-your-site.md
Labels: bot: merge on green

#22377 feat(gatsby-source-medium): define types explicitly via createSchemaCustomization (#20069)
  packages/gatsby-source-medium/src/gatsby-node.js
Labels: bot: merge on green

#23151 fix(blog): agility - fix brand names
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/index.md
Labels: bot: merge on green, topic: blogpost

#23143 fix(docs): contributing - add word and
  docs/contributing/how-to-file-an-issue.md
Labels: bot: merge on green, type: documentation

#23091 [gatsby-plugin-google-analytics] Set nonInteraction param default value to false
  packages/gatsby-plugin-google-analytics/src/index.js
Labels: bot: merge on green

#23059 fix(starters): Upgrade react-helmet in default starter
  starters/default/package-lock.json
  starters/default/package.json
  starters/default/src/components/seo.js
Labels: bot: merge on green

#23161 fix(www): 404ed giphy link
  docs/blog/2019-04-26-how-to-build-a-blog-with-wordpress-and-gatsby-part-1/index.md
  docs/blog/2019-04-30-how-to-build-a-blog-with-wordpress-and-gatsby-part-2/index.md
Labels: bot: merge on green

#22997 fix(gatsby-plugin-sharp): trim option failed
  packages/gatsby-plugin-sharp/src/plugin-options.js
Labels: bot: merge on green

#23168 chore(recipes): Move recipes readme to gatsby-recipes root, add example images
  packages/gatsby-recipes/README.md
  packages/gatsby-recipes/src/README.md
  packages/gatsby-recipes/src/todo.md
  yarn.lock
Labels: topic: recipes

#23169 fix(recipes): Don't write out debug log unless env var is set
  packages/gatsby-recipes/src/cli.js
Labels: topic: recipes

#23175 fix(recipes): Handle errors during package installs
  packages/gatsby-recipes/src/providers/npm/package.js
Labels: topic: recipes

#22619 Optimize hook destructuring
  packages/babel-preset-gatsby/.babelrc
  packages/babel-preset-gatsby/README.md
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby/src/__tests__/optimize-hook-destructuring.js
  packages/babel-preset-gatsby/src/index.js
  packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts
  packages/gatsby-dev-cli/src/__tests__/watch.js
Labels: bot: merge on green

#23187 chore(blog): 🧹 Remove whitespace from Markdown link
  docs/blog/2020-04-15-announcing-gatsby-recipes/index.md
Labels: type: documentation

#23188 chore(recipes): Mark recipes command experimental, fix linting and skip snapshot tests
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/__snapshots__/create-types.test.js.snap
  packages/gatsby-recipes/src/__snapshots__/recipe-machine.test.js.snap
  packages/gatsby-recipes/src/__snapshots__/validate-recipe.test.js.snap
  packages/gatsby-recipes/src/create-types.test.js
  packages/gatsby-recipes/src/joi-to-graphql/helpers/joi-to-graphql.js
  packages/gatsby-recipes/src/parser/__snapshots__/parser.test.js.snap
  packages/gatsby-recipes/src/parser/index.js
  packages/gatsby-recipes/src/parser/parser.test.js
  packages/gatsby-recipes/src/providers/fs/__snapshots__/file.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/shadow-file.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
  packages/gatsby-recipes/src/providers/gatsby/shadow-file.test.js
  packages/gatsby-recipes/src/providers/git/__snapshots__/ignore.test.js.snap
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package.test.js.snap
  packages/gatsby-recipes/src/providers/npm/__snapshots__/script.test.js.snap
  packages/gatsby-recipes/src/providers/resource-test-helper.js
  packages/gatsby-recipes/src/providers/utils/__snapshots__/get-diff.test.js.snap
  packages/gatsby-recipes/src/providers/utils/get-diff.test.js
  packages/gatsby-recipes/src/recipe-machine.test.js
  packages/gatsby-recipes/src/validate-recipe.test.js
  yarn.lock
Labels: bot: merge on green, topic: recipes

#23199 [minor] Update typescript.mdx for the capital S in TypeScript
  packages/gatsby-recipes/recipes/typescript.mdx
Labels: topic: recipes

#23116 Blog gatsby cli survey
  docs/blog/2020-04-17-gatsby-survey-goes-command-line/improve_results.png
  docs/blog/2020-04-17-gatsby-survey-goes-command-line/index.md
  docs/blog/2020-04-17-gatsby-survey-goes-command-line/question_one.png
  docs/blog/2020-04-17-gatsby-survey-goes-command-line/survey-screenshot.png
Labels: topic: blogpost

#23097 Add my Gatsby-Blog-Starter-Dyuzz
  docs/starters.yml
Labels: topic: showcase

#23031 fix(gatsby-remark-prismjs): Use gatsby-highlight class to calculate line numbers
  packages/gatsby-remark-prismjs/package.json
  packages/gatsby-remark-prismjs/src/__tests__/add-line-numbers.js
  packages/gatsby-remark-prismjs/src/__tests__/index.js
  packages/gatsby-remark-prismjs/src/add-line-numbers.js
  packages/gatsby-remark-prismjs/src/index.js
Labels: bot: merge on green

#23190 chore(gatsby-cli): move recipes out of gatsby
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby-cli/src/recipes.ts
  packages/gatsby/package.json
  packages/gatsby/src/commands/types.ts
Labels: bot: merge on green

#23232 feat(recipes): Update gatsby-recipes README.md
  packages/gatsby-recipes/README.md
Labels: bot: merge on green

#23182 chore(docs): Add note to "Aliasing"
  docs/docs/graphql-reference.md
Labels: type: documentation

#23218 docs: fix "Porting from CRA to Gatsby" provider section
  docs/docs/porting-from-create-react-app-to-gatsby.md
Labels: type: documentation

#23049 docs/glossary: Add Yarn glossary entry.
  docs/docs/glossary.md
  docs/docs/glossary/yarn.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, type: documentation

#18703 fix(gatsby): Add self-signed cert to node trust store (https)
  docs/docs/local-https.md
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/get-ssl-cert.js.snap
  packages/gatsby/src/utils/__tests__/get-ssl-cert.js
  packages/gatsby/src/utils/get-ssl-cert.js
  yarn.lock
Labels: bot: merge on green, status: awaiting reviewer response, topic: cli, type: bug

#23230 Create README.md for the "recipes" MDX directory
  packages/gatsby-recipes/recipes/README.md
Labels: bot: merge on green

#23118 test(www): Add tests for the sidebar
  www/src/components/sidebar/__tests__/sidebar.js
Labels: topic: i18n

#23087 maintenance (www): Sidebar function component
  www/src/components/sidebar/sidebar.js
Labels: topic: i18n

#23260 fix(recipes): Add missing package cors
  packages/gatsby-recipes/package.json
Labels: bot: merge on green, topic: recipes

#23251 fix(recipes): adjust path to layout component
  packages/gatsby-recipes/recipes/gatsby-plugin-layout.mdx
Labels: bot: merge on green, topic: recipes

#23290 fix(docs): Link to apollo blog
  docs/docs/graphql-concepts.md
Labels: bot: merge on green, type: documentation

#23106 docs: added details signifying that node fields can be arbitrary
  docs/docs/data-fetching.md
Labels: type: documentation

#23125 chore(showcase): Add new sites built by Bejamas to showcase; change Bejamas creator cover
  docs/creators/images/bejamas.jpg
  docs/sites.yml
Labels: topic: showcase

#23128 chore(showcase):Add SofaScore Corporate web to showcase sites
  docs/sites.yml
Labels: topic: showcase

#23149 fix(blog): agility - fix local links
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/index.md
Labels: topic: blogpost

#23241 chore(docs): Reference new ComponentModel component rather than generic LayerModel
  docs/contributing/docs-and-blog-components.md
  docs/docs/gatsby-lifecycle-apis.md
  docs/docs/graphql-concepts.md
  docs/docs/overview-of-the-gatsby-build-process.md
  www/src/components/layer-model/component-model/index.js
  www/src/components/layer-model/image-model/index.js
  www/src/components/layer-model/layer-model.js
Labels: type: documentation

#23301 fix(www): fix sidebar
  www/src/components/sidebar/sidebar.js
Labels: bot: merge on green

#23274 fix(recipes): Fix shadow-file resource for scoped NPM packages & re-enable e2e testing for resources
  .circleci/config.yml
  packages/gatsby-recipes/README.md
  packages/gatsby-recipes/src/providers/fs/__snapshots__/file.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/shadow-file.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/shadow-file.js
  packages/gatsby-recipes/src/providers/gatsby/shadow-file.test.js
  packages/gatsby-recipes/src/providers/git/__snapshots__/ignore.test.js.snap
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package.test.js.snap
  packages/gatsby-recipes/src/providers/npm/__snapshots__/script.test.js.snap
  packages/gatsby-recipes/src/providers/npm/package-json.js
  packages/gatsby-recipes/src/providers/resource-test-helper.js
Labels: bot: merge on green, topic: recipes

#23037 chore(starters): add gatsby-starter-ecommerce
  docs/starters.yml
Labels: topic: showcase

#23130 Add site Interficie Internet Services
  docs/sites.yml
Labels: topic: showcase
