Repository gatsbyjs/gatsby, pull requests merged in 2020-03, with the labels that each got.

#20735 chore(blog): Add "Faster Sites with Optimized Media Assets" to blog.
  docs/blog/2020-01-12-faster-sites-with-optimized-media-assets/index.md
  docs/blog/author.yaml
  docs/blog/avatars/william-imoh.jpg
Labels: bot: merge on green, topic: blogpost

#21817 chore(showcase):Add vaktija.eu to showcase
  docs/sites.yml
Labels: topic: showcase

#18721 feat(gatsby-plugin-typescript): Supports linting
  packages/gatsby-plugin-typescript/README.md
  packages/gatsby-plugin-typescript/package.json
  packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-typescript/src/gatsby-node.js
Labels: status: awaiting reviewer response

#21881 chore(starters): Update description for gis-netzwerk
  docs/sites.yml
Labels: topic: showcase

#21880 chore(showcase): Add dynobase.dev to sites.yml
  docs/sites.yml
Labels: topic: showcase

#21827 Move buildTime into new node type
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.js.snap
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
Labels: bot: merge on green

#21889 fix(benchmark/readme): adjust images count
  benchmarks/image-processing/README.md
Labels: bot: merge on green

#21888 fix(docs): fix anchor links
  docs/docs/setting-up-gatsby-without-gatsby-new.md
Labels: bot: merge on green

#21769 feat(gatsby): Allow silencing the warning for adding resolvers for missing types
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/utils/api-node-docs.js
Labels: topic: GraphQL

#21839 fix(gatsby): Check for nullable locations in query-runner
  packages/gatsby/src/query/query-runner.js
Labels: bot: merge on green

#21829 fix(gatsby): fix codepaths that result in js errors
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/navigation.js
Labels: bot: merge on green

#21861 fix:(gatsby-plugin-mdx) Require a default export when needed
  packages/gatsby-plugin-mdx/gatsby/source-nodes.js
  packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
  packages/gatsby-plugin-mdx/utils/interop-default.js
Labels: bot: merge on green

#21876 FIx (www): fixed rendering errors in showcase and starter page.
  www/src/views/showcase/filtered-showcase.js
  www/src/views/starter-library/filtered-starters.js
Labels: type: bug

#21439 feat(gatsby-remark-prismjs): add show invisibles plugin
  packages/gatsby-remark-prismjs/.gitignore
  packages/gatsby-remark-prismjs/src/__tests__/plugins/prism-show-invisibles.js
  packages/gatsby-remark-prismjs/src/index.js
  packages/gatsby-remark-prismjs/src/plugins/prism-show-invisibles.js
Labels: bot: merge on green

#21872 fix(docs): add trainling slashes to doc-links.yaml
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#21517 (blog) Bulding multilingual sites with Gatsby
  docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/images/flags.jpg
  docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/images/intranet.png
  docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/images/link-with-desc.png
  docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/images/required-field.png
  docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/images/rich-text.png
  docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/images/zoo-sign.jpg
  docs/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/index.md
Labels: topic: blogpost

#21874 Improve consistent usage of "CSS"
  docs/tutorial/part-two/index.md
Labels: type: documentation

#21037 feat(gatsby-plugin-preload-fonts): Add option to run in CI
  packages/gatsby-plugin-preload-fonts/README.md
  packages/gatsby-plugin-preload-fonts/src/__tests__/fetch-routes.test.js
  packages/gatsby-plugin-preload-fonts/src/prepare/fetch-routes.js
  packages/gatsby-plugin-preload-fonts/src/prepare/index.js
Labels: bot: merge on green, effort: low

#21903 Add date to rss feed
  www/gatsby-config.js
Labels: bot: merge on green

#21865 Chore(creators) add usama liaquat
  docs/creators/creators.yml
  docs/creators/images/usama-liaquat.jpg
Labels: effort: low

#17547 fix(gatsby-source-medium): fix data fecthing & add limitation to readme
  packages/gatsby-source-medium/README.md
  packages/gatsby-source-medium/src/gatsby-node.js
Labels: status: awaiting reviewer response

#21899 fix(gatsby): Improve warning for built-in GraphQL type overrides
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green

#21883 chore(showcase): add Messi vs Ronaldo
  docs/sites.yml
Labels: topic: showcase

#21887 chore(starters): add gatsby-starter-typescript-themes
  docs/starters.yml
Labels: topic: showcase

#21884 chore(showcase): added medignition site information
  docs/sites.yml
Labels: topic: showcase

#21833 misc(sites): add noima.xyz
  docs/sites.yml
Labels: topic: showcase

#21902 chore(showcase): add creative code daily
  docs/sites.yml
Labels: topic: showcase

#21873 chore(showcase): Add the Gene website to showcase
  docs/sites.yml
Labels: status: awaiting author response, topic: showcase

#21523 feat(gatsby): Page build optimisations for incremental data changes
  docs/docs/overview-of-the-gatsby-build-process.md
  docs/docs/page-build-optimizations-for-incremental-data-changes.md
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/commands/build-utils.js
  packages/gatsby/src/commands/build.js
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/query/query-runner.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/page-data.js
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/page-data.js
  packages/gatsby/src/utils/page-html.js
  packages/gatsby/src/utils/worker/render-html.js
  www/src/data/sidebars/doc-links.yaml
Labels: type: feature or enhancement

#21925 Fix company name of author (rebranded)
  docs/blog/author.yaml
Labels: topic: website

#21931 test: fix snapshot after merging #21523
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
Labels: bot: merge on green

#21917 chore(blog): Add hyperlink in first paragraph
  docs/blog/2020-01-12-faster-sites-with-optimized-media-assets/index.md
Labels: bot: merge on green

#21659 docs: flowchart and tables for differences between plugins, themes, and starters
  docs/docs/images/plugin-starter-theme-flowchart.png
  docs/docs/plugins-themes-and-starters.md
Labels: status: awaiting reviewer response, type: documentation

#21381 (blog): Add D&I blog post from writing sample
  .typo-ci.yml
  docs/blog/2020-02-17-changing-the-oss-status-quo/index.md
  docs/blog/author.yaml
  docs/blog/avatars/aisha-blake.jpg
Labels: topic: blogpost, 🎯 Marketing

#21937 chore(showcase): Add Em Em Recipes website to Showcase
  docs/sites.yml
Labels: topic: showcase

#21753 feat(docs): Guide for syncing translation repos
  docs/contributing/translation/sync-guide.md
Labels: topic: i18n, type: documentation

#21960 Fix Typos across Gatsby Repo
  docs/blog/2019-08-30-speed-up-your-time-to-interactive-by-delaying-third-party-scripts/index.md
  docs/blog/2019-12-11-reducing-interaction-cloud/index.md
  docs/contributing/translation/sync-guide.md
  docs/creators/creators.yml
  docs/docs/sourcing-from-woocommerce.md
  docs/docs/working-with-images-in-markdown.md
  docs/starters.yml
Labels: effort: low, topic: blogpost

#21964 Update madewithlove url since it was moved to a different TLD
  docs/sites.yml
Labels: bot: merge on green

#21875 chore(starters): add gatsby-simple-blog-with-asciidoctor
  docs/starters.yml
Labels: topic: showcase

#21855 [docs][guides] update Performance doc per style guide
  docs/docs/performance.md
Labels: type: documentation

#20964 [docs] Add advanced tutorials for SEO and social sharing cards
  docs/docs/seo.md
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/facebook.png
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/google.png
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/seo.jpg
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/slack.png
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/twitter.png
  docs/tutorial/seo-and-social-sharing-cards-tutorial/index.md
  www/src/data/sidebars/tutorial-links.yaml
Labels: type: documentation

#21972 fix(blog): remove tweet that is no longer available
  docs/blog/2019-04-19-gatsby-why-we-write/index.md
Labels: topic: blogpost

#21675 [eCom Tutorial] Refactor to function components and use `loadStripe` helper.
  docs/tutorial/ecommerce-tutorial/index.md
  docs/tutorial/ecommerce-tutorial/stripe-public-test-key.png
  examples/ecommerce-tutorial-with-stripe/README.md
  examples/ecommerce-tutorial-with-stripe/gatsby-config.js
  examples/ecommerce-tutorial-with-stripe/netlify.toml
  examples/ecommerce-tutorial-with-stripe/package.json
  examples/ecommerce-tutorial-with-stripe/src/components/Products/SkuCard.js
  examples/ecommerce-tutorial-with-stripe/src/components/Products/Skus.js
  examples/ecommerce-tutorial-with-stripe/src/components/checkout.js
  examples/ecommerce-tutorial-with-stripe/src/components/header.js
  examples/ecommerce-tutorial-with-stripe/src/components/image.js
  examples/ecommerce-tutorial-with-stripe/src/components/layout.css
  examples/ecommerce-tutorial-with-stripe/src/components/layout.js
  examples/ecommerce-tutorial-with-stripe/src/components/seo.js
  examples/ecommerce-tutorial-with-stripe/src/images/gatsby-astronaut.png
  examples/ecommerce-tutorial-with-stripe/src/images/gatsby-icon.png
  examples/ecommerce-tutorial-with-stripe/src/images/powered_by_stripe.svg
  examples/ecommerce-tutorial-with-stripe/src/pages/404.js
  examples/ecommerce-tutorial-with-stripe/src/pages/advanced.js
  examples/ecommerce-tutorial-with-stripe/src/pages/index.js
  examples/ecommerce-tutorial-with-stripe/src/pages/page-2.js
Labels: type: documentation

#21969 (blog)Draft challenge 10 of 100daysofgatsby
  docs/blog/100days/performance/index.md
Labels: topic: blogpost

#21798 [RFC] TypeScript Refactor
  rfcs/typescript-refactor.md
Labels: type: rfc

#21993 (fix gatsby - redux cache) Reduced chunk size buffer from 150 gb to 1.5 gb
  packages/gatsby/src/redux/persist.ts
Labels: bot: merge on green

#22009 fix(gatsby): Prevent cache invalidation case for loki
  packages/gatsby/src/redux/persist.ts
Labels: bot: merge on green

#21994 chore: Ts/setup typescript for all
  packages/babel-plugin-remove-graphql-queries/tsconfig.json
  packages/babel-preset-gatsby-package/tsconfig.json
  packages/babel-preset-gatsby/tsconfig.json
  packages/gatsby-core-utils/tsconfig.json
  packages/gatsby-image/tsconfig.json
  packages/gatsby-link/tsconfig.json
  packages/gatsby-page-utils/tsconfig.json
  packages/gatsby-react-router-scroll/tsconfig.json
  packages/gatsby-telemetry/tsconfig.json
  scripts/check-ts.js
Labels: bot: merge on green, type: TypeScript migration

#21871 docs(style guide): new section about internal links
  docs/contributing/gatsby-style-guide.md
Labels: type: documentation

#21987 docs(gatsbt-theme-blog): add instructions on avatar image
  packages/gatsby-theme-blog/README.md
Labels: topic: themes, type: documentation

#22028 chore(gatsby): Port build-javascript to TypeScript
  packages/gatsby/src/commands/build-javascript.ts
  packages/gatsby/src/commands/build.js
Labels: bot: merge on green, type: TypeScript migration

#22037 chore(gatsby): Convert repl to typescript
  packages/gatsby/src/commands/repl.ts
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green, type: TypeScript migration

#22036 chore(gatsby): Convert clean to typescript
  packages/gatsby/src/commands/clean.ts
Labels: bot: merge on green, type: TypeScript migration

#22061 chore(gatsby): Convert detect-port-in-use-and-prompt to typescript
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/commands/serve.js
  packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts
Labels: bot: merge on green, type: TypeScript migration

#22063 chore(gatsby): Convert redux/actions/index to TS
  packages/gatsby/src/redux/actions/index.js
  packages/gatsby/src/redux/actions/index.ts
Labels: bot: merge on green, type: TypeScript migration

#22092 chore(showcase): Site Showcase maintainence
  docs/sites.yml
Labels: topic: showcase

#22089 chore(gatsby): Convert utils/browserslist to typescript
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/utils/__tests__/browserslist.js
  packages/gatsby/src/utils/browserslist.ts
Labels: bot: merge on green, type: TypeScript migration

#22006 Adding xavie.mirmon.co.uk to sites.yml
  docs/sites.yml
Labels: topic: showcase

#22081 chore(cli): migrate progress-bar to typescript
  packages/gatsby-cli/src/reporter/loggers/ink/cli.js
  packages/gatsby-cli/src/reporter/loggers/ink/components/progress-bar.tsx
  packages/gatsby-cli/src/util/calc-elapsed-time.js
  packages/gatsby-cli/src/util/calc-elapsed-time.ts
Labels: bot: merge on green, type: TypeScript migration

#22069 docs: Add MDN links to globals section of porting from CRA to Gatsby
  docs/docs/porting-from-create-react-app-to-gatsby.md
Labels: type: documentation

#22008 docs: Add 'System limit for number of file watchers' troubleshooting
  docs/docs/troubleshooting-common-errors.md
Labels: type: documentation

#22093 chore(gatsby): Migrate utils/get-public-path.js to ts
  packages/gatsby/src/utils/__tests__/get-public-path.ts
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/get-public-path.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: bot: merge on green, type: TypeScript migration

#22076 chore(gatsby): Convert src/utils/utils/app-data.js to typescript
  packages/gatsby/src/commands/build.js
  packages/gatsby/src/utils/app-data.ts
Labels: type: TypeScript migration

#22068 chore(gatsby-cli): Convert did-you-mean to typescript
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby-cli/src/did-you-mean.ts
Labels: bot: merge on green, type: TypeScript migration

#22014 chore(starters): add gatsby-starter-i18n-bulma
  docs/starters.yml
Labels: topic: showcase

#22079 chore(showcase): add junchenjun.me to the showcase list
  docs/sites.yml
Labels: topic: showcase

#22077 chore(starters): add gatsby-starter-clean-resume
  docs/starters.yml
Labels: topic: showcase

#21974 docs/glossary: WPGraphQL article
  docs/docs/glossary.md
  docs/docs/glossary/wpgraphql.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, 🎯 Marketing

#22106 chore(gatsby): Convert develop-static to TypeScript
  packages/gatsby/src/commands/develop-static.js
  packages/gatsby/src/commands/develop-static.ts
  packages/gatsby/src/commands/develop.ts
Labels: type: TypeScript migration

#22094 chore(gatsby): Migrate utils/get-cache.js to ts
  packages/gatsby/src/utils/__tests__/get-cache.ts
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/get-cache.ts
Labels: bot: merge on green, type: TypeScript migration

#22035 chore(babel-preset-gatsby): Convert path-serializer to TS
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/dependencies.js
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/utils/path-serializer.js
  packages/babel-preset-gatsby/src/utils/path-serializer.ts
Labels: type: TypeScript migration

#22080 chore(cli): migrate spinner to typescript
  packages/gatsby-cli/src/reporter/loggers/ink/cli.js
  packages/gatsby-cli/src/reporter/loggers/ink/components/spinner.js
  packages/gatsby-cli/src/reporter/loggers/ink/components/spinner.tsx
Labels: bot: merge on green, type: TypeScript migration

#21908 Rename Theme tutorials to Plugin and Theme Tutorials and update redir…
  docs/blog/100days/start-blog/index.md
  docs/contributing/docs-contributions.md
  docs/docs/gatsby-vendor-partnership.md
  docs/docs/naming-a-plugin.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/schema-gql-type.md
  docs/docs/sourcing-from-private-apis.md
  docs/docs/themes.md
  docs/tutorial/index.md
  docs/tutorial/pixabay-source-plugin-tutorial.md
  docs/tutorial/remark-plugin-tutorial.md
  docs/tutorial/theme-tutorials.md
  examples/using-local-plugins/README.md
  packages/gatsby-cli/src/create-cli.js
  www/redirects.yaml
  www/src/data/sidebars/doc-links.yaml
  www/src/data/sidebars/tutorial-links.yaml
Labels: status: awaiting reviewer response

#22111 fix(gatsby-cli): Update build script to properly handle .tsx files
  packages/gatsby-cli/.babelrc
  packages/gatsby-cli/package.json
Labels: bot: merge on green

#22051 chore(gatsby-core-utils): get-config-store to TS
  packages/gatsby-core-utils/src/get-config-store.ts
Labels: type: TypeScript migration

#22047 chore(gatsby-core-utils): ci to TS
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/__mocks__/ci-info.ts
  packages/gatsby-core-utils/src/ci.ts
  yarn.lock
Labels: type: TypeScript migration

#22048 chore(gatsby-core-utils): cpu-core-count to TS
  packages/gatsby-core-utils/src/cpu-core-count.ts
Labels: type: TypeScript migration

#22049 chore(gatsby-core-utils): create-content-digest to TS
  packages/gatsby-core-utils/src/__tests__/create-content-digest.ts
  packages/gatsby-core-utils/src/create-content-digest.ts
Labels: type: TypeScript migration

#22050 chore(gatsby-core-utils): create-require-from-path to TS
  packages/gatsby-core-utils/src/create-require-from-path.js
  packages/gatsby-core-utils/src/create-require-from-path.ts
Labels: type: TypeScript migration

#22052 chore(gatsby-core-utils): get-gatsby-version to TS
  packages/gatsby-core-utils/src/get-gatsby-version.ts
Labels: type: TypeScript migration

#22053 chore(gatsby-core-utils): index to TS
  packages/gatsby-core-utils/src/index.js
  packages/gatsby-core-utils/src/index.ts
Labels: type: TypeScript migration

#22054 chore(gatsby-core-utils): path to ts
  packages/gatsby-core-utils/src/__tests__/path.ts
  packages/gatsby-core-utils/src/path.ts
Labels: type: TypeScript migration

#22056 chore(gatsby-core-utils): url to TS
  packages/gatsby-core-utils/src/__tests__/url.ts
  packages/gatsby-core-utils/src/url.ts
Labels: bot: merge on green, type: TypeScript migration

#22029 Added MPG Calculator to submitted sites.yml
  docs/sites.yml
Labels: topic: showcase, type: documentation

#22083 chore(gatsby): Convert get-static-dir to typescript
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/get-static-dir.ts
Labels: type: TypeScript migration

#22067 chore(showcase): add www.yuuniworks.com
  docs/sites.yml
Labels: topic: showcase

#22096 chore(gatsby): Convert utils/create-node-id to TypeScript
  packages/gatsby/src/bootstrap/load-plugins/load.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/create-node-id.ts
Labels: bot: merge on green, type: TypeScript migration

#22126 perf(gatsby): more efficient parent-child check through arrays
  packages/gatsby/src/redux/actions/public.js
Labels: bot: merge on green

#21945 [contributing] New doc on Gatsby's Docs Writing Process
  docs/contributing/docs-writing-process.md
  docs/contributing/gatsby-style-guide.md
  www/src/data/sidebars/contributing-links.yaml
Labels: type: documentation

#22062 chore(gatsby): Convert redux/actions/add-page-dependency to TS
  packages/gatsby/src/db/loki/nodes.js
  packages/gatsby/src/query/graphql-runner.ts
  packages/gatsby/src/redux/actions/add-page-dependency.js
  packages/gatsby/src/redux/actions/add-page-dependency.ts
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/nodes.js
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/schema/__tests__/build-node-connections.js
  packages/gatsby/src/schema/__tests__/build-node-types.js
  packages/gatsby/src/schema/context.js
  packages/gatsby/src/schema/infer/__tests__/infer-input.js
Labels: bot: merge on green, type: TypeScript migration

#22133 chore(gatsby): Convert utils/prepare-regex to typescript
  packages/gatsby/src/db/loki/nodes-query.js
  packages/gatsby/src/redux/run-sift.js
  packages/gatsby/src/utils/__tests__/prepare-regex.js
  packages/gatsby/src/utils/prepare-regex.ts
Labels: type: TypeScript migration

#22130 chore(gatsby): Convert utils/path to typescript
  packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js
  packages/gatsby/src/utils/__tests__/path.ts
  packages/gatsby/src/utils/path.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: type: TypeScript migration

#22086 chore(gatsby-cli): Convert init-starter to typescript
  packages/gatsby-cli/src/init-starter.ts
Labels: bot: merge on green, type: TypeScript migration

#22034 Cleanup build-html
  packages/gatsby/src/commands/build-html.ts
Labels: bot: merge on green, type: TypeScript migration

#22033 Cleanup build-javascript
  packages/gatsby/src/commands/build-javascript.ts
Labels: bot: merge on green, type: TypeScript migration

#21740 Update Readme with information for multiple spaces
  packages/gatsby-source-contentful/README.md
Labels: status: awaiting author response, type: documentation

#22084 chore(cli): migrate messages to typescript
  packages/gatsby-cli/src/reporter/constants.js
  packages/gatsby-cli/src/reporter/constants.ts
  packages/gatsby-cli/src/reporter/loggers/ink/components/messages.js
  packages/gatsby-cli/src/reporter/loggers/ink/components/messages.tsx
Labels: type: TypeScript migration

#22140 chore(gatsby-cli): Convert ensure-windows-drive-letter-is-uppercase to typescript
  packages/gatsby-cli/src/index.ts
  packages/gatsby-cli/src/util/ensure-windows-drive-letter-is-uppercase.ts
Labels: bot: merge on green, type: TypeScript migration

#22122 Ts/gatsby core utils
  .eslintrc.js
  packages/gatsby-core-utils/.babelrc
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/__mocks__/ci-info.js
  packages/gatsby-core-utils/src/__tests__/ci.ts
  packages/gatsby-core-utils/src/__tests__/cpu-core-count.js
  packages/gatsby-core-utils/src/__tests__/cpu-core-count.ts
  packages/gatsby-core-utils/src/__tests__/create-content-digest.ts
  packages/gatsby-core-utils/src/__tests__/path.ts
  packages/gatsby-core-utils/src/__tests__/physical-cpu-count.ts
  packages/gatsby-core-utils/src/__tests__/url.ts
  packages/gatsby-core-utils/src/ci.ts
  packages/gatsby-core-utils/src/cpu-core-count.ts
  packages/gatsby-core-utils/src/create-content-digest.ts
  packages/gatsby-core-utils/src/create-require-from-path.js
  packages/gatsby-core-utils/src/create-require-from-path.ts
  packages/gatsby-core-utils/src/get-config-store.ts
  packages/gatsby-core-utils/src/get-gatsby-version.ts
  packages/gatsby-core-utils/src/index.js
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-core-utils/src/path.ts
  packages/gatsby-core-utils/src/physical-cpu-count.ts
  packages/gatsby-core-utils/src/url.ts
  yarn.lock
Labels: bot: merge on green, type: TypeScript migration

#22138 chore(gatsby): Convert is-32-bit-integer to TypeScript
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/infer/inference-metadata.js
  packages/gatsby/src/schema/infer/is-32-bit-integer.js
  packages/gatsby/src/utils/__tests__/is-32-bit-integer.ts
  packages/gatsby/src/utils/is-32-bit-integer.js
  packages/gatsby/src/utils/is-32-bit-integer.ts
Labels: bot: merge on green, type: TypeScript migration

#22137 Submit Softblues.io site to Gatsby Showcase
  docs/sites.yml
Labels: topic: showcase

#22141 chore(gatsby-cli): Tweak init-starter types
  packages/gatsby-cli/src/init-starter.ts
Labels: bot: merge on green, type: TypeScript migration

#22024 blog: add jsparty + gatsby post
  docs/blog/2020-03-09-gatsby-and-jsparty-podcast/images/jsparty.png
  docs/blog/2020-03-09-gatsby-and-jsparty-podcast/index.md
  docs/blog/author.yaml
  www/package.json
  www/src/components/script-loader.js
  www/src/gatsby-plugin-theme-ui/components.js
Labels: topic: blogpost

#22146 Update Feedback/Env Var docs to follow style guide
  docs/docs/cli-feedback.md
  docs/docs/environment-variables.md
Labels: type: documentation

#22144 Adding author bio
  docs/blog/author.yaml
  docs/blog/avatars/rich-manalang.jpeg
Labels: topic: blogpost

#22147 fix(gatsby-dev-cli): Include theme src directories
  packages/gatsby-dev-cli/src/__tests__/watch.js
  packages/gatsby-dev-cli/src/watch.js
Labels: bot: merge on green, status: WIP, topic: themes

#22150 chore(gatsby): Convert utils/worker/pool to typescript
  packages/gatsby/src/commands/build.js
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/worker/pool.js
  packages/gatsby/src/utils/worker/pool.ts
Labels: bot: merge on green, type: TypeScript migration

#22155 chore(gatsby): Convert utils/worker/page-data to typescript
  packages/gatsby/src/utils/worker/child.js
  packages/gatsby/src/utils/worker/page-data.ts
Labels: type: TypeScript migration

#22167 chore(gatsby): Clean up file name and dir for wait-until-jobs-complete
  packages/gatsby/src/commands/build.js
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/wait-until-jobs-complete.ts
Labels: bot: merge on green

#22143 chore(gatsby-core-utils): Autogenerate types declaration
  packages/gatsby-core-utils/index.d.ts
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/ci.ts
  packages/gatsby-core-utils/src/cpu-core-count.ts
  packages/gatsby-core-utils/src/create-content-digest.ts
  packages/gatsby-core-utils/src/get-config-store.ts
  packages/gatsby-core-utils/src/path.ts
  packages/gatsby-core-utils/src/url.ts
  packages/gatsby-core-utils/tsconfig.json
Labels: type: TypeScript migration

#21534 feat(gatsby): Support FastRefresh for development hot reloading
  packages/gatsby/cache-dir/error-overlay-handler.js
  packages/gatsby/cache-dir/root.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/requires-writer.js
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/webpack-plugins.js
  packages/gatsby/src/utils/webpack-utils.js
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: bot: merge on green, breaking change

#22123 docs(gatsby-plugin-mdx): fix broken links in readme
  packages/gatsby-plugin-mdx/README.md
Labels: topic: MDX

#22156 [docs][guides] Running a Gatsby Preview Server
  docs/docs/running-a-gatsby-preview-server.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#22098 chore(cli): migrate error component to typescript
  packages/gatsby-cli/src/reporter/loggers/ink/cli.js
  packages/gatsby-cli/src/reporter/loggers/ink/components/error.js
  packages/gatsby-cli/src/reporter/loggers/ink/components/error.tsx
Labels: bot: merge on green, type: TypeScript migration

#21658 docs: add Cloudflare Workers documentation
  docs/docs/deploying-to-cloudflare-workers.md
  docs/docs/preparing-for-deployment.md
  docs/docs/recipes.md
  docs/docs/recipes/deploying-your-site.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#22160 [docs] fix plugin/theme tutorial links and copy
  docs/docs/creating-a-source-plugin.md
  docs/docs/creating-a-transformer-plugin.md
  docs/tutorial/index.md
  docs/tutorial/pixabay-source-plugin-tutorial.md
  docs/tutorial/plugin-and-theme-tutorials.md
  docs/tutorial/remark-plugin-tutorial.md
  docs/tutorial/theme-tutorials.md
  www/src/data/sidebars/doc-links.yaml
  www/src/data/sidebars/tutorial-links.yaml
Labels: type: documentation

#22182 chore(gatsby) Convert get-value-at to typescript
  packages/gatsby/src/db/loki/nodes-query.js
  packages/gatsby/src/redux/run-sift.js
  packages/gatsby/src/schema/infer/is-file.js
  packages/gatsby/src/schema/resolvers.js
  packages/gatsby/src/utils/__tests__/get-value-at.ts
  packages/gatsby/src/utils/get-value-at.ts
Labels: bot: merge on green, type: TypeScript migration

#22180 chore(gatsby-cli): Convert util/configstore to typescript
  packages/gatsby-cli/src/init-starter.ts
  packages/gatsby-cli/src/util/configstore.js
  packages/gatsby-cli/src/util/package-manager.ts
Labels: bot: merge on green, type: TypeScript migration

#22187 Update index.d.ts
  packages/gatsby/index.d.ts
Labels: bot: merge on green

#21933 chore(starters): add gatsby-starter-strata-notion
  docs/starters.yml
Labels: topic: showcase

#22178 (blog)100DaysOfGatsby Challenge 11
  docs/blog/100days/cms/index.md
Labels: topic: blogpost

#21518 fix(gatsby): Show meaningful error when directory names are too long
  packages/gatsby-cli/src/structured-errors/error-map.js
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/__tests__/path.ts
  packages/gatsby/src/utils/path.ts
Labels: status: awaiting reviewer response

#21948 feat(gatsby-plugin-sitemap): handle different query structures and allow custom siteUrl resolution
  packages/gatsby-plugin-sitemap/README.md
  packages/gatsby-plugin-sitemap/src/__tests__/internals.js
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
  packages/gatsby-plugin-sitemap/src/internals.js
Labels: topic: plugins, type: bug

#22171 chore(gatsby): Convert query/utils to typescript
  packages/gatsby/src/query/__tests__/__snapshots__/utils.ts.snap
  packages/gatsby/src/query/__tests__/utils.ts
  packages/gatsby/src/query/utils.js
  packages/gatsby/src/query/utils.ts
Labels: type: TypeScript migration

#22121 fix(gatsby-plugin-mdx): add context dependency to mdx-scopes loader
  packages/gatsby-plugin-mdx/loaders/mdx-scopes.js
Labels: topic: MDX

#22162 chore(showcase): Add clipchamp.com to site showcase
  docs/sites.yml
Labels: topic: showcase

#22197 chore(gatsby-source-filesystem): fix jdoc
  packages/gatsby-source-filesystem/src/utils.js
Labels: bot: merge on green

#22196 chore(gatsby): remove yarn.lock from gitignore
  .gitignore
Labels: bot: merge on green

#18051 fix: runtime network/resource loading resilience fixes + restore e2e tests for it
  e2e-tests/production-runtime/cypress/integration/resource-loading-resilience.js
  packages/gatsby/cache-dir/__tests__/dev-loader.js
  packages/gatsby/cache-dir/__tests__/loader.js
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/cache-dir/ensure-resources.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/cache-dir/production-app.js
Labels: bot: merge on green

#20472 perf(gatsby-telemetry): Memoize the getRepositoryId
  packages/gatsby-telemetry/src/telemetry.js
Labels: bot: merge on green

#21877 feat(docs): Adding Building a SaaS app with Gatsby and the JAMstack
  docs/docs/awesome-gatsby-resources.md
Labels: type: documentation

#22202 docs(gatsby): Fix broken links
  docs/docs/write-pages.md
Labels: bot: merge on green, type: documentation

#22204 chore(docs): remove whitespace from Markdown link
  docs/docs/maintaining-a-plugin.md
Labels: type: documentation

#22217 chore(docs): 🧹 Fix case of GitHub and JavaScript
  docs/blog/2020-02-11-founding-organizations/index.md
  docs/docs/deploying-to-cloudflare-workers.md
  examples/recipe-linking-between-pages/README.md
  examples/using-square-payments/src/components/paymentForm.js
Labels: topic: blogpost, type: documentation

#22210 chore(docs): 🔒 Fix missing HTTPS on graphql.org links.
  docs/blog/2017-02-21-1-0-progress-update-where-came-from-where-going/index.md
  docs/blog/2017-10-05-portfolio-site-gatsby-wordpress/index.md
  docs/blog/2017-10-20-from-wordpress-to-developing-in-react-starting-to-see-it/index.md
  docs/blog/2017-11-08-migrate-from-jekyll-to-gatsby/index.md
  docs/blog/2017-12-07-taking-gatsby-for-a-spin/index.md
  docs/blog/2018-02-16-bright-future-for-the-web/index.md
  docs/blog/2018-04-11-trying-out-gatsby-at-work-and-co/index.md
  docs/blog/2018-2-27-why-i-upgraded-my-website-to-gatsbyjs-from-jekyll/index.md
  docs/blog/2018-2-6-choosing-a-back-end/index.md
  docs/blog/2018-3-03-case-study-mike-johnston/index.md
  docs/blog/gatsbygram-case-study/index.md
  docs/docs/graphql-concepts.md
  docs/docs/graphql.md
  docs/docs/migrating-from-v0-to-v1.md
  docs/tutorial/part-four/index.md
  docs/tutorial/part-zero/index.md
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-wordpress/README.md
  packages/gatsby/src/query/query-watcher.js
Labels: topic: blogpost, type: documentation

#22177 feat(docs): Official theme development workflow
  docs/contributing/code-contributions.md
Labels: topic: themes

#22237 chore(docs): Fixed typo
  docs/blog/100days/react-component/index.md
Labels: topic: blogpost

#22232 chore(docs): 🧹 Fix Markdown link
  docs/docs/sourcing-from-sanity.md
Labels: type: documentation

#22026 chore(starters): add gatsby-graphcms-ecommerce-starter
  docs/starters.yml
Labels: topic: showcase

#20597 Port parts of Structured Errors to TS + Add two more errors
  package.json
  packages/gatsby-cli/src/reporter/index.js
  packages/gatsby-cli/src/structured-errors/__tests__/construct-error.ts
  packages/gatsby-cli/src/structured-errors/__tests__/error-map.ts
  packages/gatsby-cli/src/structured-errors/__tests__/error-schema.ts
  packages/gatsby-cli/src/structured-errors/construct-error.js
  packages/gatsby-cli/src/structured-errors/construct-error.ts
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-cli/src/structured-errors/error-schema.ts
  packages/gatsby/src/query/__tests__/__snapshots__/error-parser.ts.snap
  packages/gatsby/src/query/__tests__/error-parser.js
  packages/gatsby/src/query/__tests__/error-parser.ts
  packages/gatsby/src/query/error-parser.ts
  packages/gatsby/src/types.ts
  packages/gatsby/src/utils/api-runner-error-parser.ts
  packages/gatsby/src/utils/api-runner-node.js
  yarn.lock
Labels: bot: merge on green, type: TypeScript migration, type: feature or enhancement

#22242 chore(docs) : fixed several typos
  examples/ecommerce-tutorial-with-stripe/src/pages/page-2.js
  packages/gatsby-cli/src/reporter/index.js
  packages/gatsby/src/bootstrap/load-plugins/validate.js
  peril/rules/validate-yaml.ts
  www/src/templates/template-api-markdown.js
Labels: bot: merge on green

#22213 fix(gatsby-source-drupal): Add safety check for existence of datum.
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: bot: merge on green

#22245 chore: bump @typescript-eslint/* packages
  .eslintrc.js
  package.json
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green, type: chore

#22246 chore: bump cache-manager
  package.json
  packages/gatsby/package.json
  packages/gatsby/src/utils/cache.ts
  yarn.lock
Labels: type: chore

#22249 fix: make 11321 and 11330 error formatters backward compatible
  packages/gatsby-cli/src/structured-errors/error-map.ts
Labels: bot: merge on green

#21941 chore(www) Add unit tests for i18n utils
  www/src/utils/__tests__/i18n.js
  www/src/utils/i18n.js
  www/src/utils/node/docs.js
Labels: topic: i18n

#22078 Adding new starter theme Barcadia
  docs/starters.yml
Labels: topic: showcase

#22225 chore(starters): add gatsby-contentful-portfolio
  docs/starters.yml
Labels: topic: showcase

#22216 Fixing tfe energy by url
  docs/sites.yml
Labels: topic: showcase

#21633 feature(www): Translate text through js-lingui
  .typo-ci.yml
  www/.gitignore
  www/gatsby-node.js
  www/package.json
  www/src/components/I18nContext.js
  www/src/components/dark-mode-toggle.js
  www/src/components/docs-table-of-contents.js
  www/src/components/guide-list.js
  www/src/components/layout.js
  www/src/components/localized-link.js
  www/src/components/markdown-page-footer.js
  www/src/components/navigation-mobile.js
  www/src/components/navigation.js
  www/src/components/prev-and-next.js
  www/src/components/search-form/search-form.js
  www/src/components/shared/egghead-embed.js
  www/src/components/shared/footer-links.js
  www/src/components/sidebar/button-expand-all.js
  www/src/components/sidebar/section-title.js
  www/src/components/sidebar/sidebar.js
  www/src/components/sidebar/sticky-responsive-sidebar.js
  www/src/components/site-metadata.js
  www/src/components/skip-nav-link.js
  www/src/data/locales/en/messages.po
  www/src/data/locales/ja/messages.po
  www/src/layouts/index.js
  www/src/templates/__tests__/template-starter-page.js
Labels: topic: i18n
