Repository gatsbyjs/gatsby, pull requests merged in 2020-02, with the labels that each got.

#20962 docs/glossary: Headless WordPress entry.
  docs/docs/glossary.md
  docs/docs/glossary/headless-wordpress.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, 🎯 Marketing

#20913 docs: move Breadcrumb and ToC component docs for i18n efforts
  docs/contributing/docs-and-website-components.md
  docs/contributing/docs-contributions.md
Labels: topic: i18n, type: documentation

#21062 (blog)Add challenge 6 of #100daysOfGatsby
  docs/blog/100days/serverless/index.md
Labels: bot: merge on green, topic: blogpost

#21123 Update sites.yml
  docs/sites.yml
Labels: bot: merge on green

#21115 perf(www): get rid of unnecessary items in query
  www/gatsby-node.js
Labels: bot: merge on green

#21113 fix doc: delete import { Link } from "gatsby"
  docs/tutorial/ecommerce-tutorial/index.md
Labels: bot: merge on green

#20948 feat(www): Adds CodeSandbox in Try this starter
  www/src/assets/vendor-logos/codesandbox.svg
  www/src/templates/template-starter-page.js
  www/src/views/starter/source.js
Labels: bot: merge on green

#21071 chore(starters): add gatsby-starter-catalyst-basic
  docs/starters.yml
Labels: bot: merge on green

#21114 fix doc: integrate quote type
  docs/tutorial/ecommerce-tutorial/index.md
Labels: bot: merge on green

#20807 fix(gatsby-link): Adds Type, PropType, tests, and docs for `state` prop
  docs/docs/gatsby-link.md
  docs/docs/location-data-from-props.md
  packages/gatsby-link/index.d.ts
  packages/gatsby-link/src/__tests__/index.js
  packages/gatsby-link/src/index.js
Labels: bot: merge on green

#21045 fix(gatsby-plugin-sharp): throw error when not added to gatsby-config
  examples/using-gatsby-image/gatsby-config.js
  packages/gatsby-plugin-sharp/src/index.js
Labels: bot: merge on green

#21106 chore(showcase): Add Smile and DG Recruit
  docs/sites.yml
Labels: bot: merge on green

#21125 chore: Update using-javascript-transforms example to es6 declarations
  examples/using-javascript-transforms/src/articles/2017-05-30-choropleth-on-d3v4-alternate/index.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: bot: merge on green

#21128 fix(gatsby): Fix invalid algorithm of fragment cycles detection
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/query-compiler.js
Labels: bot: merge on green

#21127 fix(gatsby-source-mongodb): pass useUnifiedTopology option to MongoClient
  packages/gatsby-source-mongodb/README.md
  packages/gatsby-source-mongodb/src/gatsby-node.js
Labels: bot: merge on green

#21020 chore(showcase): Add Choose Tap
  docs/sites.yml
Labels: bot: merge on green

#21118 chore(starter): Add starter with TypeScript
  docs/starters.yml
Labels: bot: merge on green

#21160 chore(showcase): Clean up showcase
  docs/sites.yml
Labels: topic: showcase

#20998 feat(gatsby-source-wordpress): Ability to set a custom rest api route prefix
  packages/gatsby-source-wordpress/README.md
  packages/gatsby-source-wordpress/src/fetch.js
  packages/gatsby-source-wordpress/src/gatsby-node.js
Labels: bot: merge on green, type: feature or enhancement

#21132 Update creators.yml
  docs/creators/creators.yml
Labels: bot: merge on green

#21214 chore(blog): 🧹 Fix case of Twitter. Remove duplicate line.
  docs/blog/100days/free-hosting/index.md
  docs/blog/100days/gatsby-image/index.md
  docs/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/index.md
  docs/blog/2019-05-02-how-to-build-a-blog-with-wordpress-and-gatsby-part-3/index.md
  docs/starters.yml
Labels: topic: blogpost, type: documentation

#21204 feat(gatsby-plugin-benchmark-reporting): Use the telemetry session id
  packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Labels: topic: analytics

#19981 docs(dynamic-routes): utilize `basepath` of router
  docs/docs/client-only-routes-and-user-authentication.md
Labels: type: documentation

#21206 docs: update naming-a-plugin for actual theme conventions
  docs/docs/naming-a-plugin.md
Labels: type: documentation

#21018 Blog 2020-02-05 Accessible Routing
  docs/blog/2020-02-10-accessible-client-side-routing-improvements/index.md
Labels: bot: merge on green, status: inkteam to review, topic: blogpost

#21303 Fixed typo
  docs/tutorial/building-a-theme.md
Labels: bot: merge on green

#21310 Docs: Minor typo correction
  docs/docs/adding-app-and-website-functionality.md
Labels: bot: merge on green, type: documentation

#21288 Replace custom 100days email component with normal EmailCaptureForm
  docs/blog/100days/index.md
  www/src/components/email-capture-form-100days.js
  www/src/components/email-capture-form.js
Labels: bot: merge on green

#21295 perf(www): Add additional filter when searching sites in creator-details template
  www/gatsby-node.js
  www/src/templates/template-creator-details.js
Labels: bot: merge on green

#21199 Replace siteMetadata 'subtitle' with 'description'
  examples/using-wordpress/src/templates/page.js
  examples/using-wordpress/src/templates/post.js
Labels: bot: merge on green

#21208 doc: fix netlify command option
  docs/docs/recipes/deploying-your-site.md
Labels: bot: merge on green, type: documentation

#20978 chore(www): Factor out prev-and-next calculation to its own util
  www/gatsby-node.js
  www/src/utils/get-prev-and-next.js
Labels: bot: merge on green

#21287 refactor(www): Markdown stub list page
  docs/contributing/stub-list.md
  www/src/components/__tests__/stub-list.js
  www/src/components/stub-list.js
  www/src/gatsby-plugin-theme-ui/components.js
  www/src/pages/contributing/stub-list.js
Labels: bot: merge on green

#21200 chore(www): Simplify getting featured starters and plugins
  www/gatsby-config.js
  www/gatsby-node.js
  www/src/pages/ecosystem.js
  www/src/pages/index.js
Labels: bot: merge on green

#21179 fix(docs): fix links to localhost on docs/blog/tutorials ...
  docs/blog/2018-06-07-build-a-gatsby-blog-using-the-cosmic-js-source-plugin/index.md
  docs/blog/2018-11-03-building-an-accessible-lightbox/index.md
  docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
  docs/blog/2019-04-30-how-to-build-a-blog-with-wordpress-and-gatsby-part-2/index.md
  docs/blog/2019-05-02-how-to-build-a-blog-with-wordpress-and-gatsby-part-3/index.md
  docs/blog/2019-11-13-getting-set-up-to-manually-test-web-accessibility/index.md
  docs/blog/2019-11-21-how-to-convert-an-existing-gatsby-blog-to-use-mdx/index.md
  docs/docs/adding-tags-and-categories-to-blog-posts.md
  docs/docs/audit-with-lighthouse.md
  docs/docs/creating-and-modifying-pages.md
  docs/docs/gatsby-cli.md
  docs/docs/local-https.md
  docs/docs/mdx/getting-started.md
  docs/docs/mdx/programmatically-creating-pages.md
  docs/docs/modifying-a-starter.md
  docs/docs/performance-tracing.md
  docs/docs/quick-start.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/setting-up-gatsby-without-gatsby-new.md
  docs/docs/sourcing-from-buttercms.md
  docs/docs/sourcing-from-forestry.md
  docs/docs/sourcing-from-netlify-cms.md
  docs/docs/sourcing-from-wordpress.md
  docs/docs/testing-components-with-graphql.md
  docs/docs/troubleshooting-common-errors.md
  docs/docs/using-graphql-playground.md
  docs/docs/why-gatsby-uses-graphql.md
  docs/tutorial/blog-netlify-cms-tutorial/index.md
  docs/tutorial/building-a-theme.md
  docs/tutorial/ecommerce-tutorial/index.md
  docs/tutorial/part-eight/index.md
  docs/tutorial/part-five/index.md
  docs/tutorial/part-one/index.md
  docs/tutorial/part-zero/index.md
  docs/tutorial/prismic-source-graphql-tutorial.md
  docs/tutorial/wordpress-image-tutorial.md
  docs/tutorial/wordpress-source-plugin-tutorial.md
  examples/using-page-loading-indicator/README.md
  packages/gatsby-graphiql-explorer/README.md
  packages/gatsby-transformer-yaml/README.md
  starters/gatsby-starter-theme-workspace/example/README.md
Labels: bot: merge on green

#21289 refactor(www): Turn contributing/events into markdown
  docs/contributing/events.md
  www/src/components/events/__tests__/event-list.js
  www/src/components/events/event-list.js
  www/src/components/events/events.js
  www/src/gatsby-plugin-theme-ui/components.js
  www/src/pages/contributing/events.js
Labels: bot: merge on green

#21186 Fix config instructions for netlify lambda
  docs/blog/2018-12-17-turning-the-static-dynamic/index.md
Labels: bot: merge on green

#20780 chore(examples): use slash from gatsby-core-utils
  docs/blog/gatsbygram-case-study/index.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/sourcing-from-wordpress.md
  examples/gatsbygram/gatsby-node.js
  examples/gatsbygram/package.json
  examples/hn/gatsby-node.js
  examples/hn/package.json
  examples/sitemap/gatsby-node.js
  examples/sitemap/package.json
  examples/using-asciidoc/gatsby-node.js
  examples/using-asciidoc/package.json
  examples/using-contentful/gatsby-node.js
  examples/using-contentful/package.json
  examples/using-remark/gatsby-node.js
  examples/using-remark/package.json
  examples/using-wordpress-with-acf/gatsby-node.js
  examples/using-wordpress-with-acf/package.json
  examples/using-wordpress/gatsby-node.js
  examples/using-wordpress/package.json
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/utils/path-serializer.js
  packages/gatsby-source-lever/README.md
  packages/gatsby-source-wordpress/README.md
  www/gatsby-node.js
  www/package.json
  yarn.lock
Labels: type: maintenance

#21240 feat(gatsby-design-tokens): v2
  packages/gatsby-design-tokens/README.md
  packages/gatsby-design-tokens/package.json
  packages/gatsby-design-tokens/src/borders.js
  packages/gatsby-design-tokens/src/breakpoints.js
  packages/gatsby-design-tokens/src/colors.js
  packages/gatsby-design-tokens/src/font-sizes.js
  packages/gatsby-design-tokens/src/font-weights.js
  packages/gatsby-design-tokens/src/fonts.js
  packages/gatsby-design-tokens/src/index.js
  packages/gatsby-design-tokens/src/letter-spacings.js
  packages/gatsby-design-tokens/src/line-heights.js
  packages/gatsby-design-tokens/src/media-queries.js
  packages/gatsby-design-tokens/src/radii.js
  packages/gatsby-design-tokens/src/shadows.js
  packages/gatsby-design-tokens/src/sizes.js
  packages/gatsby-design-tokens/src/space.js
  packages/gatsby-design-tokens/src/theme-gatsbyjs-org.js
  packages/gatsby-design-tokens/src/theme.js
  packages/gatsby-design-tokens/src/transition.js
  packages/gatsby-design-tokens/src/z-indices.js
  yarn.lock
Labels: bot: merge on green

#21328 refactor(www): Convert email-capture-form to a function component
  www/src/components/email-capture-form.js
Labels: bot: merge on green

#21325 refactor(www): Turn SearchForm into a function component
  www/src/components/navigation.js
  www/src/components/search-form/algolia-styles.js
  www/src/components/search-form/docsearch.min.js
  www/src/components/search-form/index.js
  www/src/components/search-form/search-form.js
  www/src/components/search-icon.js
Labels: bot: merge on green

#21211 fix(gatsby-plugin-mdx): Pass node API helpers through mdx-loader to remark plugins
  packages/gatsby-plugin-mdx/gatsby/create-webpack-config.js
  packages/gatsby-plugin-mdx/loaders/mdx-loader.js
Labels: topic: MDX

#21318 fix(www): Add slashes to links in features overview
  www/src/pages/features.js
Labels: bot: merge on green

#21317 fix(docs): Set table of contents depth for recipes
  docs/docs/recipes/deploying-your-site.md
  docs/docs/recipes/pages-layouts.md
  docs/docs/recipes/querying-data.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/recipes/styling-css.md
  docs/docs/recipes/transforming-data.md
  docs/docs/recipes/working-with-images.md
  docs/docs/recipes/working-with-starters.md
  docs/docs/recipes/working-with-themes.md
Labels: bot: merge on green

#21337 refactor(www): Reorganize plugin pages layout
  www/gatsby-node.js
  www/src/components/page-with-plugin-searchbar.js
  www/src/layouts/index.js
  www/src/pages/plugins.js
  www/src/templates/template-docs-local-packages.js
  www/src/templates/template-docs-remote-packages.js
Labels: bot: merge on green

#21330 refactor(www): Factor out modal to its own component
  www/src/components/layout.js
  www/src/components/modal.js
  www/src/components/showcase-details.js
  www/src/components/with-color-mode.js
  www/src/templates/template-showcase-details.js
  www/src/templates/template-starter-page.js
Labels: bot: merge on green

#21322 fix(docs): Move "Setting Up Your Local Dev Environment" under "Code Contributions"
  www/src/data/sidebars/contributing-links.yaml
Labels: bot: merge on green

#21316 upload image for creators
  docs/creators/images/app-design-dev.jpeg
Labels: bot: merge on green

#21340 fix(docs): fix links to Example Project
  docs/docs/deploying-to-zeit-now.md
Labels: bot: merge on green, type: documentation

#21171 chore(gatsby): Unpin @reach/router version with latest release
  e2e-tests/development-runtime/package.json
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green

#20763 feat(www): Convert API pages to MDX
  docs/docs/actions.md
  docs/docs/browser-apis.md
  docs/docs/node-api-helpers.md
  docs/docs/node-apis.md
  docs/docs/node-model.md
  docs/docs/ssr-apis.md
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/api-node-helpers-docs.js
  www/gatsby-node.js
  www/src/assets/vendor-logos/codesandbox.svg
  www/src/components/api-reference/index.js
  www/src/pages/docs/actions.js
  www/src/pages/docs/browser-apis.js
  www/src/pages/docs/node-api-helpers.js
  www/src/pages/docs/node-apis.js
  www/src/pages/docs/node-model.js
  www/src/pages/docs/ssr-apis.js
  www/src/templates/template-api-markdown.js
  www/src/utils/normalize-gatsby-api-call.js
Labels: topic: i18n

#21348 feat(www): Add the ability to add custom descriptions to docs
  docs/contributing/docs-contributions.md
  docs/contributing/events.md
  docs/contributing/index.md
  docs/contributing/stub-list.md
  docs/docs/index.md
  www/src/templates/template-docs-markdown.js
Labels: bot: merge on green

#21356 fix(www): get location prop for remote and local package templates
  www/src/pages/plugins.js
  www/src/templates/template-docs-local-packages.js
  www/src/templates/template-docs-remote-packages.js
Labels: bot: merge on green

#21358 fix(www): inherit from layout in ecosystem page and fix weird styling
  www/src/components/layout/layout-with-heading.js
  www/src/components/layout/page-heading.js
  www/src/pages/ecosystem.js
Labels: bot: merge on green

#21359 chore(www): remove unused components
  www/src/components/layout/plugin-library-wrapper.js
  www/src/components/url-query.js
Labels: bot: merge on green

#21353 Update sites.yml to reflect my portfolio site
  docs/sites.yml
Labels: bot: merge on green

#21352 refactor(www): Simplify code for site showcase
  www/src/components/modal.js
  www/src/components/showcase-details.js
  www/src/templates/template-showcase-details.js
Labels: bot: merge on green

#21217 refactor(www): Split up gatsby-node
  www/gatsby-node.js
  www/src/utils/node/creators.js
  www/src/utils/node/docs.js
  www/src/utils/node/features.js
  www/src/utils/node/packages.js
  www/src/utils/node/showcase.js
  www/src/utils/node/starters.js
Labels: bot: merge on green

#21351 (blog)Sustainable open source blog post
  docs/blog/2020-02-11-founding-organizations/index.md
Labels: bot: merge on green, topic: blogpost

#21213 chore(docs): 🔒 Fix missing HTTPS on links
  docs/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/index.md
  docs/docs/graphql-concepts.md
  packages/gatsby-source-mongodb/README.md
  starters/blog/README.md
  starters/gatsby-starter-theme/content/posts/my-second-post.mdx
Labels: topic: blogpost, type: documentation

#21364 fix(www): Add missing reporter
  www/src/utils/node/showcase.js
Labels: bot: merge on green

#21365 fix(gatsby): Use argument for updating cache
  packages/gatsby/src/schema/node-model.js
Labels: bot: merge on green

#21366 fix(gatsby): add onPostBuild activity
  packages/gatsby/src/commands/build.js
Labels: bot: merge on green

#21312 feat(gatsby-transformer-remark): Better timeToRead for Chinese/Japanese texts
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
  packages/gatsby-transformer-remark/src/utils/time-to-read.js
Labels: bot: merge on green

#21367 fix(blog): founding organizations typos
  docs/blog/2020-02-11-founding-organizations/index.md
Labels: bot: merge on green, topic: blogpost

#21216 fix(gatsby): revert auto-adding id field to queries
  packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/query-compiler.js
Labels: bot: merge on green

#21284 [docs] Update Adding React Components
  docs/docs/adding-react-components.md
Labels: type: documentation

#20586 fix(gatsby): Reset graphql runner on certain node events
  packages/gatsby/src/bootstrap/graphql-runner.js
Labels: bot: merge on green, topic: GraphQL

#19286 chore(docs): Include import case to MDX setup
  docs/docs/mdx/programmatically-creating-pages.md
  packages/gatsby-plugin-mdx/README.md
Labels: type: documentation

#21374 chore(gatsby): remove obsolete tests
  packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap
  packages/gatsby/src/query/__tests__/query-compiler.js
Labels: bot: merge on green

#21375 Changes/gatsby e commerce tutorial
  docs/tutorial/ecommerce-tutorial/index.md
Labels: type: documentation, type: maintenance, 🎯 Learning

#21385 fixes typo on the page "prefer-webp"
  examples/using-gatsby-image/src/pages/prefer-webp.js
Labels: type: documentation

#21384 fix a typo
  docs/contributing/using-an-online-dev-environment.md
Labels: bot: merge on green

#21230 chore(docs): GitHub Action information for Cypress
  docs/docs/end-to-end-testing.md
Labels: type: documentation

#21402 (blog) 100daysofGatsby: challenge 7
  docs/blog/100days/pwa/index.md
Labels: topic: blogpost

#21412 fix(gatsby-source-contentful): Remove whitespace from default long text value
  packages/gatsby-source-contentful/src/normalize.js
Labels: bot: merge on green

#21407 fix(blog): Add title to YouTube embed
  docs/blog/100days/pwa/index.md
Labels: topic: blogpost

#21369 chore(gatsby-plugin-benchmark-reporting): Add more meta data
  packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Labels: topic: Performance

#21417 Moving Documentation Order To Match File Structure
  docs/docs/gatsby-project-structure.md
Labels: type: documentation

#20361 chore(docs): Updated with Windows Configuration
  docs/docs/using-graphql-playground.md
Labels: status: awaiting author response, type: documentation

#21387 Added portfolio site to sites.yml
  docs/sites.yml
Labels: topic: showcase

#21424 [showcase] Built with (Cloudflare) Workers
  docs/sites.yml
Labels: topic: showcase

#20702 docs(gatsby-plugin-mdx): consistent backticks
  packages/gatsby-plugin-mdx/README.md
Labels: type: documentation

#21448 fix(www): Fix Gatsby Showcase Details View
  www/src/components/showcase-details.js
Labels: bot: merge on green

#21416 API Specifications Documentation Update
  docs/docs/api-specification.md
Labels: type: documentation

#21078 docs: Creating a Split Test with Gatsby
  docs/docs/ab-testing-with-google-analytics-and-netlify.md
  docs/docs/ab-testing.md
  docs/docs/images/branch-names.png
  docs/docs/images/checking-custom-dimension.gif
  docs/docs/images/create-custom-dimension.gif
  docs/docs/images/custom-dimensions-screenshot.png
  docs/docs/images/gatsby-default-starter-green-button.png
  docs/docs/images/gatsby-default-starter-image.png
  docs/docs/images/gatsby-default-starter-red-button.png
  docs/docs/images/netlify-post-processing.gif
  docs/docs/images/start-split-test.gif
  www/src/data/sidebars/doc-links.yaml
Labels: status: inkteam assigned, type: documentation

#21501 Submitting Multiple Site Showcase Contributions
  docs/sites.yml
  packages/gatsby-transformer-remark/utils/time-to-read.js
Labels: topic: showcase, 🎯 Learning

#21513 fix(www): Fixes broken UI on home page of gatsbyjs.org in landscape orientation
  www/src/components/homepage/homepage-ecosystem.js
Labels: bot: merge on green

#21438 docs/glossary: Continuous deployment article, excerpt
  docs/docs/glossary.md
  docs/docs/glossary/continuous-deployment.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, 🎯 Marketing

#21406 (blog) Learn JavaScript Deeply with Gatsby
  docs/blog/2020-02-17-learn-javascript-deeply/index.md
Labels: topic: blogpost

#21506 chore(showcase): Added Taskade
  docs/sites.yml
Labels: topic: showcase

#21488 chore(showcase): add indrakusuma.web.id/me
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#21545 chore(showcase): Add Matthew's portfolio site to Showcase
  docs/sites.yml
Labels: bot: merge on green

#21477 chore(starter): add gatsby-contentful-blog-portfolio
  docs/starters.yml
Labels: bot: merge on green

#21550 chore(creators): Add Ahmad Awais
  docs/creators/creators.yml
  docs/creators/images/ahmad-awais.jpg
Labels: bot: merge on green

#21547 docs(blog): Gatsby Gazette: The 2019 Recap
  docs/blog/2020-02-18-gazette-2019-recap/index.md
  docs/blog/author.yaml
Labels: bot: merge on green, topic: blogpost

#21549 [showcase]: Add pwd.com.au
  docs/sites.yml
Labels: topic: showcase

#21436 fix(blog)Update 100DaysOfGatsby challenge 7 description
  docs/blog/100days/pwa/index.md
Labels: topic: blogpost

#21491 Add link explaining `styling approach`
  docs/docs/creating-global-styles.md
  docs/docs/css-libraries-and-frameworks.md
Labels: type: documentation

#21450 Add Artem Sapegin’s Blog to showcase
  docs/sites.yml
Labels: topic: showcase

#21524 Add zatsuzen blog
  docs/sites.yml
Labels: topic: showcase

#21285 docs(workflows): new guide about importing and using components in MDX
  docs/docs/mdx/customizing-components.md
  docs/docs/mdx/importing-and-using-components.md
  docs/docs/mdx/writing-pages.md
  www/src/data/sidebars/doc-links.yaml
Labels: status: awaiting author response, type: documentation

#21243 docs/glossary: Add decoupled Drupal glossary entry.
  docs/docs/glossary.md
  docs/docs/glossary/decoupled-drupal.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, 🎯 Marketing

#20141 docs: End-to-end testing improvements
  docs/docs/end-to-end-testing.md
  examples/using-cypress/README.md
  examples/using-cypress/cypress.json
  examples/using-cypress/cypress/e2e/accessibility.test.js
  examples/using-cypress/cypress/fixtures/example.json
  examples/using-cypress/cypress/plugins/index.js
  examples/using-cypress/cypress/support/commands.js
  examples/using-cypress/cypress/support/index.js
  examples/using-cypress/gatsby-config.js
  examples/using-cypress/package.json
  examples/using-cypress/src/components/header.js
  examples/using-cypress/src/components/image.js
  examples/using-cypress/src/components/layout.css
  examples/using-cypress/src/components/layout.js
  examples/using-cypress/src/components/seo.js
  examples/using-cypress/src/images/gatsby-astronaut.png
  examples/using-cypress/src/images/gatsby-icon.png
  examples/using-cypress/src/pages/404.js
  examples/using-cypress/src/pages/index.js
  examples/using-cypress/src/pages/page-2.js
Labels: status: awaiting author response, type: documentation

#21551 fix(gatsby): Fix static query parsing for for a special case
  packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/query/__tests__/file-parser.js
  packages/gatsby/src/query/file-parser.js
Labels: bot: merge on green

#21221 chore (doc): maintaining a plugin guide.
  docs/docs/maintaining-a-plugin.md
  www/src/data/sidebars/doc-links.yaml
Labels: status: awaiting author response, type: documentation

#21570 (docs) Update translation/style-guide.md
  docs/contributing/translation/style-guide.md
Labels: type: documentation

#21584 feat(gatsby): Tweak eslint not to emit no-use-before-define on funcs
  .eslintrc.js
Labels: bot: merge on green, type: feature or enhancement

#21634 fix(www): Fix dot-org build by removing missing starter
  docs/starters.yml
Labels: bot: merge on green

#21638 Ignore more files with typo-ci
  .typo-ci.yml
Labels: bot: merge on green

#21619 feat: add an option to resolve locales in entries referenced by rich text
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/__tests__/plugin-options.js
  packages/gatsby-source-contentful/src/__tests__/rich-text.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/plugin-options.js
  packages/gatsby-source-contentful/src/rich-text.js
  yarn.lock
Labels: bot: merge on green

#21687 fix(docs): GraphQL query indentation
  docs/docs/testing-components-with-graphql.md
Labels: bot: merge on green

#21603 feat(www): update pairing session
  docs/contributing/pair-programming.md
Labels: bot: merge on green, type: documentation

#21654 chore(showcase): add chrisvogt.me to the site showcase list
  docs/sites.yml
Labels: topic: showcase

#21627 feat(gatsby-cli): support for PREFIX_PATHS env variable
  packages/gatsby-cli/README.md
  packages/gatsby-cli/src/create-cli.js
Labels: Gatsby Cloud, topic: cli

#21686 chore(starters): add gatsby-animate-starter
  docs/starters.yml
Labels: topic: showcase

#21666 update sites.yml
  docs/sites.yml
Labels: topic: showcase

#20460 docs(gatsby-plugin-mdx): add shouldBlockNodeFromTransformation to readme
  packages/gatsby-plugin-mdx/README.md
Labels: type: documentation

#20381 chore(docs): Change path to pagePath
  docs/docs/creating-and-modifying-pages.md
Labels: status: awaiting author response, type: documentation

#21696 Add trolleytravel.org to the showcase
  docs/sites.yml
Labels: topic: showcase

#21555 fix(gatsby): Chunk nodes when serializing redux to prevent OOM
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/persist.ts
  packages/gatsby/src/redux/types.ts
Labels: scaling

#21745 (docs): Reference guide for using WooCommerce
  docs/docs/sourcing-from-woocommerce.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#21587 docs/glossary: Add Markdown article.
  docs/docs/glossary.md
  docs/docs/glossary/markdown.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, 🎯 Marketing

#20782 fix(gatsby-transformer-sharp): Warn when using unsupported extension
  packages/gatsby-transformer-sharp/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-sharp/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-sharp/src/create-resolvers.js
  packages/gatsby-transformer-sharp/src/gatsby-node.js
  packages/gatsby-transformer-sharp/src/on-node-create.js
  packages/gatsby-transformer-sharp/src/supported-extensions.js
Labels: type: feature or enhancement

#21763 Add codeful.fi to Gatsby showcase.
  docs/sites.yml
Labels: topic: showcase

#21765 fix(gatsby-source-contentful): prevent unpublished Contentful entries from breaking content sync
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: topic: plugins

#21771 (blog)100daysofgatsby challenge 9
  docs/blog/100days/accessibility/index.md
  docs/blog/100days/seo/index.md
Labels: bot: merge on green, topic: blogpost

#21708 docs: add new guide and example site on plugin options
  docs/docs/configuring-usage-with-plugin-options.md
  examples/using-plugin-options/README.md
  examples/using-plugin-options/gatsby-config.js
  examples/using-plugin-options/package.json
  examples/using-plugin-options/plugins/gatsby-plugin-console-log/gatsby-node.js
  examples/using-plugin-options/plugins/gatsby-plugin-console-log/index.js
  examples/using-plugin-options/plugins/gatsby-plugin-console-log/package.json
  examples/using-plugin-options/src/components/header.js
  examples/using-plugin-options/src/components/layout.css
  examples/using-plugin-options/src/components/layout.js
  examples/using-plugin-options/src/pages/404.js
  examples/using-plugin-options/src/pages/index.js
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#21163 chore(showcase):added problem.studio to sites.yml
  docs/sites.yml
Labels: topic: showcase

#21767 chore(starters): add gatsby-starter-blog-and-cv
  docs/starters.yml
Labels: topic: showcase

#21787 chore(showcase):Add Marathon Oil to the Site Showcase
  docs/sites.yml
Labels: topic: showcase

#21665 Update sites.yml
  docs/sites.yml
Labels: topic: showcase

#21632 feature(www): Create localized versions of all pages
  www/gatsby-config.js
  www/plugins/gatsby-plugin-i18n/gatsby-node.js
  www/plugins/gatsby-plugin-i18n/index.js
  www/plugins/gatsby-plugin-i18n/package.json
  www/src/utils/i18n.js
  www/src/utils/node/docs.js
Labels: topic: i18n

#21793 Add TalentPoint.co to sites.yml
  docs/sites.yml
Labels: topic: showcase

#21801 fix(www): Remove crashing starter
  docs/starters.yml
Labels: bot: merge on green

#21591 fix(*): Remove global namespace hack for a proper workflow
  packages/gatsby-react-router-scroll/src/ScrollBehaviorContext.js
  packages/gatsby/cache-dir/navigation.js
Labels: bot: merge on green

#21822 chore(showcase):Remove category causing danger bot error for showcase
  docs/sites.yml
Labels: bot: merge on green

#21185 Sync script for translation repos
  scripts/i18n/README.md
  scripts/i18n/package.json
  scripts/i18n/sync.js
Labels: topic: i18n

#21770 docs/glossary: Adds MDX entry.
  docs/docs/glossary.md
  docs/docs/glossary/mdx.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, 🎯 Marketing

#21806 chore(www) reorganize contributing section
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contributing/blog-contributions.md
  docs/contributing/code-contributions.md
  docs/contributing/docs-and-blog-components.md
  docs/contributing/docs-contributions.md
  docs/contributing/how-to-open-a-pull-request.md
  docs/contributing/managing-pull-requests.md
  docs/contributing/setting-up-your-local-dev-environment.md
  docs/contributing/website-contributions.md
  www/redirects.yaml
  www/src/data/sidebars/contributing-links.yaml
Labels: bot: merge on green

#21811 (docs) Remove jsdoc for graphql fragments in GraphQL API
  docs/docs/graphql-api.md
  packages/gatsby-image/README.md
  www/src/components/api-reference/doc-static-queries.js
Labels: bot: merge on green

#21781 docs: add egghead embeds for new mdx screencasts
  docs/docs/mdx/getting-started.md
  docs/docs/mdx/importing-and-using-components.md
Labels: type: documentation

#21542 Offer a base Page props type which folks can extend
  packages/gatsby/index.d.ts
Labels: status: awaiting author response

#16726 fix(gatsby): Switching from devcert-san to devcert to fix HTTPS issues
  packages/gatsby/package.json
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/__tests__/get-ssl-cert.js
  packages/gatsby/src/utils/get-ssl-cert.js
  yarn.lock
Labels: status: awaiting reviewer response
