Repository gatsbyjs/gatsby, pull requests merged in 2020-07, with the labels that each got.

#25432 maintenance(www, docs) Remove data fetching example code from the website
  docs/docs/data-fetching.md
  www/gatsby-node.js
  www/package.json
  www/src/components/build-data-example.js
  www/src/components/client-data-example.js
Labels: status: triage needed

#25418 chore(docs): anatomy of graphql query link
  docs/docs/graphql-concepts.md
Labels: type: documentation

#25425 fix(blog): Partner Program - remove markdown links from email
  docs/blog/2020-06-22-Announcing-Gatsby-Partner-Program/index.md
Labels: topic: blogpost

#25401 fix(gatsby): fix typings in resolve-module-exports
  .circleci/config.yml
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js
  packages/gatsby/src/bootstrap/resolve-module-exports.ts
  yarn.lock
Labels: topic: TypeScript migration

#24877 fix(blog): publish multiple sites: change now to vercel
  docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
Labels: topic: blogpost

#25439 tests(gatsby): fix feedback tests
  packages/gatsby/src/utils/feedback.ts
Labels: bot: merge on green, status: needs core review

#25438 refactor(gatsby): Move store assertion into helper
  packages/gatsby/src/services/build-schema.ts
  packages/gatsby/src/services/calculate-dirty-queries.ts
  packages/gatsby/src/services/create-pages.ts
  packages/gatsby/src/services/run-page-queries.ts
  packages/gatsby/src/services/run-static-queries.ts
  packages/gatsby/src/services/source-nodes.ts
  packages/gatsby/src/services/write-out-requires.ts
  packages/gatsby/src/utils/assert-store.ts
Labels: bot: merge on green, status: needs core review

#25305 feat(gatsby): Use state machine for bootstrap in develop
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/services/build-schema.ts
  packages/gatsby/src/services/create-pages-statefully.ts
  packages/gatsby/src/services/create-pages.ts
  packages/gatsby/src/services/customize-schema.ts
  packages/gatsby/src/services/index.ts
  packages/gatsby/src/services/post-bootstrap.ts
  packages/gatsby/src/services/source-nodes.ts
  packages/gatsby/src/services/write-out-redirects.ts
  packages/gatsby/src/state-machines/data-layer/actions.ts
  packages/gatsby/src/state-machines/data-layer/index.ts
  packages/gatsby/src/state-machines/data-layer/services.ts
  packages/gatsby/src/state-machines/data-layer/types.ts
Labels: status: needs core review, topic: develop state machine

#25158 chore: upgrade core-js to version 3
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/index.js
  packages/babel-preset-gatsby-package/package.json
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/dependencies.ts.snap
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/dependencies.ts
  packages/babel-preset-gatsby/src/index.js
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/index.ts
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/__tests__/corejs-resolver.ts
  packages/gatsby/src/utils/webpack/corejs-resolver.ts
  yarn.lock
Labels: breaking change, topic: webpack/babel

#25423 (blog) Draft of June Gatsby Gazette
  docs/blog/gazette-june-2020/index.md
  docs/blog/gazette-june-2020/reflex-examples.jpg
  docs/blog/gazette-june-2020/sanity-benchmark.jpg
  docs/blog/gazette-june-2020/will-it-build-sanity-screenshot.png
Labels: topic: blogpost

#25452 fix(blog): fix linting errors
  dictionary.txt
  docs/blog/gazette-june-2020/index.md
Labels: topic: blogpost

#25301 chore(showcase): add ellingtonhammond.com
  docs/sites.yml
Labels: topic: showcase

#25347 chore(showcase): Add playbook of fidisys
  docs/sites.yml
Labels: topic: showcase

#25337 docs(contributing): Update contributor counts
  docs/contributing/community.md
  docs/contributing/docs-contributions.md
Labels: bot: merge on green, type: documentation

#25247 chore(showcase): Add OnTravelDiary to list of sites
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#25288 maintenance(docs, www): Remove unnecessary overview from frontmatter
  docs/docs/ab-testing.md
  docs/docs/adding-app-and-website-functionality.md
  docs/docs/adding-page-transitions.md
  docs/docs/adding-search.md
  docs/docs/api-reference.md
  docs/docs/conceptual-guide.md
  docs/docs/css-in-js.md
  docs/docs/css-libraries-and-frameworks.md
  docs/docs/customization.md
  docs/docs/debugging.md
  docs/docs/deploying-and-hosting.md
  docs/docs/graphql.md
  docs/docs/guides.md
  docs/docs/headless-cms.md
  docs/docs/partnering-with-gatsby.md
  docs/docs/performance.md
  docs/docs/plugins-themes-and-starters.md
  docs/docs/preparing-for-site-launch.md
  docs/docs/preparing-your-environment.md
  docs/docs/releases-and-migration.md
  docs/docs/styling.md
  docs/docs/testing.md
  docs/docs/themes.md
  docs/docs/using-gatsby-professionally.md
  www/src/templates/template-docs-markdown.js
  www/src/utils/node/docs.js
Labels: topic: website

#24158 chore(gatsby-source-graphql): upgrade to graphql-tools v6
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/__tests__/gatsby-node.js
  packages/gatsby-source-graphql/src/gatsby-node.js
  packages/gatsby-source-graphql/src/transforms.js
  yarn.lock
Labels: bot: merge on green, status: needs core review

#25447 fix(gatsby-source-drupal): end activities if errors are thrown
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: bot: merge on green, topic: Drupal

#25120 feat(gatsby): Track static queries by template
  .circleci/config.yml
  integration-tests/artifacts/LICENSE
  integration-tests/artifacts/README.md
  integration-tests/artifacts/__tests__/static-queries.js
  integration-tests/artifacts/gatsby-browser.js
  integration-tests/artifacts/gatsby-config.js
  integration-tests/artifacts/gatsby-ssr.js
  integration-tests/artifacts/jest.config.js
  integration-tests/artifacts/package.json
  integration-tests/artifacts/src/components/author.js
  integration-tests/artifacts/src/components/github.js
  integration-tests/artifacts/src/components/title.js
  integration-tests/artifacts/src/components/twitter.js
  integration-tests/artifacts/src/hooks/use-title.js
  integration-tests/artifacts/src/pages/dynamic-dynamic.js
  integration-tests/artifacts/src/pages/dynamic-import.js
  integration-tests/artifacts/src/pages/dynamic.js
  integration-tests/artifacts/src/pages/import-dynamic.js
  integration-tests/artifacts/src/pages/import-import.js
  integration-tests/artifacts/src/pages/import.js
  integration-tests/artifacts/src/pages/inline.js
  integration-tests/artifacts/src/pages/jsx.jsx
  integration-tests/artifacts/src/pages/tsx.tsx
  integration-tests/artifacts/src/pages/typescript.ts
  packages/babel-plugin-remove-graphql-queries/src/index.js
  packages/gatsby/src/commands/build-javascript.ts
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/static-queries-by-template.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/map-pages-to-static-query-hashes.ts
  packages/gatsby/src/utils/page-data.ts
Labels: type: feature or enhancement

#25471 chore: chmod +X cli.js
  packages/gatsby-cli/cli.js
  packages/gatsby/cli.js
Labels: bot: merge on green, type: maintenance

#25474 Revert "chore: upgrade core-js to version 3"
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/index.js
  packages/babel-preset-gatsby-package/package.json
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/dependencies.ts.snap
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/dependencies.ts
  packages/babel-preset-gatsby/src/index.js
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/index.ts
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/__tests__/corejs-resolver.ts
  packages/gatsby/src/utils/webpack/corejs-resolver.ts
  yarn.lock
Labels: status: triage needed

#25317 fix(eslint-config): Remove deprecated jsx-a11y/label-has-for rule
  packages/gatsby/src/utils/eslint-config.ts
Labels: bot: merge on green, topic: a11y

#25399 fix(www): remove last updated field on docs pages
  www/gatsby-config.js
  www/package.json
  www/src/components/markdown-page-footer.js
  www/src/utils/node/docs.js
Labels: topic: website

#25483 chore: update xstate and adjust code to not use deprecated transient transitions
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/recipe-machine/index.js
  packages/gatsby-source-filesystem/package.json
  packages/gatsby/package.json
  packages/gatsby/src/redux/machines/page-component.ts
  yarn.lock
Labels: type: maintenance

#25213 chore(showcase): Add Inbound Latino website
  docs/sites.yml
Labels: topic: showcase

#25448 Switch layer-icon to pure SVGs
  www/src/assets/icons/abstract-symbol.svg
  www/src/assets/icons/app-window.svg
  www/src/assets/icons/atomic-symbol.svg
  www/src/assets/icons/graphql-logo.svg
  www/src/assets/icons/layer-icon.js
  www/src/assets/icons/react-logo.svg
  www/src/components/layer-model/layer-model.js
Labels: topic: website

#25488 refactor(www): import layer icons directly
  www/src/assets/icons/layer-icon.js
  www/src/assets/icons/layer-icons.js
  www/src/components/layer-model/component-model/index.js
  www/src/components/layer-model/image-model/index.js
  www/src/components/layer-model/layer-model.js
Labels: status: triage needed

#25486 fix(gatsby-design-tokens): Add border definitions to theme
  packages/gatsby-design-tokens/src/theme-gatsbyjs-org.js
  packages/gatsby-design-tokens/src/theme.js
Labels: topic: website

#25490 chore: remove unused typobot file
  .typo-ci.yml
Labels: type: chore

#25429 fix(blog,www) Remove file copy of mp4 file
  docs/blog/gatsbygram-case-study/gatsbygram.mp4
  docs/blog/gatsbygram-case-study/index.md
  www/gatsby-node.js
Labels: topic: website

#25493 Revert "feat(gatsby): Track static queries by template"
  .circleci/config.yml
  integration-tests/artifacts/LICENSE
  integration-tests/artifacts/README.md
  integration-tests/artifacts/__tests__/static-queries.js
  integration-tests/artifacts/gatsby-browser.js
  integration-tests/artifacts/gatsby-config.js
  integration-tests/artifacts/gatsby-ssr.js
  integration-tests/artifacts/jest.config.js
  integration-tests/artifacts/package.json
  integration-tests/artifacts/src/components/author.js
  integration-tests/artifacts/src/components/github.js
  integration-tests/artifacts/src/components/title.js
  integration-tests/artifacts/src/components/twitter.js
  integration-tests/artifacts/src/hooks/use-title.js
  integration-tests/artifacts/src/pages/dynamic-dynamic.js
  integration-tests/artifacts/src/pages/dynamic-import.js
  integration-tests/artifacts/src/pages/dynamic.js
  integration-tests/artifacts/src/pages/import-dynamic.js
  integration-tests/artifacts/src/pages/import-import.js
  integration-tests/artifacts/src/pages/import.js
  integration-tests/artifacts/src/pages/inline.js
  integration-tests/artifacts/src/pages/jsx.jsx
  integration-tests/artifacts/src/pages/tsx.tsx
  integration-tests/artifacts/src/pages/typescript.ts
  packages/babel-plugin-remove-graphql-queries/src/index.js
  packages/gatsby/src/commands/build-javascript.ts
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/static-queries-by-template.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/map-pages-to-static-query-hashes.ts
  packages/gatsby/src/utils/page-data.ts
Labels: status: triage needed

#25489 refactor(www): Make easy-to-convert class components into function components
  www/src/components/plugin-searchbar-body.js
  www/src/components/stub-list.js
  www/src/pages/creators/agencies.js
  www/src/pages/creators/companies.js
  www/src/pages/creators/index.js
  www/src/pages/creators/people.js
  www/src/pages/ecosystem.js
  www/src/pages/features.js
  www/src/pages/plugins.js
  www/src/pages/showcase.js
  www/src/pages/starters.js
  www/src/templates/template-blog-list.js
  www/src/templates/template-blog-post.js
  www/src/templates/template-creator-details.js
  www/src/templates/template-feature-comparison.js
  www/src/views/creators/creators-header.js
Labels: topic: website

#25279 fix(gatsby-plugin-google-analytics): Separate preconnect and dns-prefetch
  packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js
Labels: topic: analytics plugins, type: bug

#25496 refactor(www): Turn pagination to function component
  www/src/components/pagination/index.js
Labels: topic: website

#24192 fix: incorrect typedef parsing for interfaces
  packages/gatsby-transformer-documentationjs/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-documentationjs/src/__tests__/fixtures/same-name.ts
  packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-documentationjs/src/gatsby-node.js
Labels: bot: merge on green, status: awaiting author response

#24965 fix(www): Fix getting active item when pathname does not end with /
  www/src/components/sidebar/__tests__/sidebar.js
  www/src/utils/sidebar/get-active-item.js
Labels: status: awaiting reviewer response, topic: website

#25494 chore(docs): Fix file name typo
  docs/docs/unit-testing.md
Labels: bot: merge on green, type: documentation

#25339 enhancement(docs): dictionary.txt -> Infer* -> putting all code prefixed with infer into code blocks
  dictionary.txt
  docs/docs/schema-gql-type.md
  docs/docs/schema-input-gql.md
Labels: status: needs docs review, type: dx

#25495 refactor(www): Turn HubspotForm to function component
  docs/blog/2018-08-01-partner-program/index.md
  www/src/components/hubspot-form.js
Labels: topic: website

#23916 Remove micro modules
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/index.ts
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/providers/git/ignore.js
  packages/gatsby-telemetry/package.json
  packages/gatsby/package.json
Labels: bot: merge on green, status: awaiting author response, type: maintenance

#25340 chore(showcase): Showcase addition: Real Estate Shows
  docs/sites.yml
Labels: topic: showcase

#25322 chore(showcase): Removing my site from the showcase
  docs/sites.yml
Labels: topic: showcase

#24893 chore(gatsby-plugin-less): less-loader version 6.1.0 with tests and doc…
  packages/gatsby-plugin-less/README.md
  packages/gatsby-plugin-less/package.json
  packages/gatsby-plugin-less/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-less/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-less/src/gatsby-node.js
  yarn.lock
Labels: breaking change

#25357 chore(showcase): https://lidabox.com website
  docs/sites.yml
Labels: topic: showcase

#25259 chore(showcase): Add mindkit.fr
  docs/sites.yml
Labels: topic: showcase

#25057 refactor(gatsby): use virtual modules for `(a)sync-requires` and `match-paths.json`
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/utils/gatsby-webpack-virtual-modules.ts
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: topic: webpack/babel

#25472 fix(gatsby-source-contentful): dont ship fixtures when publishing
  packages/gatsby-source-contentful/.npmignore
Labels: bot: merge on green, type: chore

#25372 chore(showcase): Add Require Podcast website to the sites showcase
  docs/sites.yml
Labels: topic: showcase

#25410 chore(showcase): LeanyLabs website
  docs/sites.yml
Labels: topic: showcase

#25323 chore(starters): starters.yml -> Fixed many typos, capitalization, and grammatical errors
  docs/starters.yml
Labels: status: needs docs review, topic: starters, type: dx

#25491 chore(showcase): Add ivjose.com
  docs/sites.yml
Labels: topic: showcase

#25350 chore(www): Refactor `homepage-newsletter`
  www/src/components/homepage/homepage-newsletter.js
Labels: bot: merge on green, topic: website

#24987 docs: improve style in Creating & Modifying pages
  docs/docs/creating-and-modifying-pages.md
Labels: bot: merge on green, type: documentation

#25341 docs(contributing): Anonymized contact information for reaching DevRel
  docs/contributing/how-to-contribute.md
  docs/contributing/where-to-participate.md
Labels: bot: merge on green, type: documentation

#25325 fix(gatsby-transformer-sharp): removed unnecessary conversion to webp
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/process-file.js
  packages/gatsby/src/schema/__tests__/fixtures/kitchen-sink.json
Labels: bot: merge on green, topic: images/media

#25296 chore(starters): add gatsby-three-ts-plus
  docs/starters.yml
Labels: topic: showcase

#25278 enhancement(www): custom DocPage node type.
  www/gatsby-node.js
  www/src/components/__tests__/docs-markdown-page.js
  www/src/components/docs-markdown-page.js
  www/src/components/markdown-page-footer.js
  www/src/templates/template-api-markdown.js
  www/src/templates/template-docs-markdown.js
  www/src/utils/node/docs.js
Labels: topic: website

#25514 fix(blog): gazette june - remove local domain, add plugin name in code fences
  docs/blog/gazette-june-2020/index.md
Labels: status: triage needed

#21882 WIP: Implement languages page
  www/src/components/languages/language-thumb.js
  www/src/pages/languages.js
Labels: topic: i18n

#24367 added false as default assignment to isExpanded property
  www/src/components/sidebar/__tests__/sidebar.js
  www/src/components/sidebar/section-title.js
  www/src/components/sidebar/sidebar.js
Labels: topic: website

#25518 fix linting for langauges page
  www/src/components/languages/language-thumb.js
  www/src/pages/languages.js
Labels: status: triage needed

#25543 chore(docs): added some parenthesis
  docs/docs/troubleshooting-common-errors.md
Labels: type: documentation

#25520 fix(gatsby): correctly pass through exit signals from child process
  packages/gatsby/src/commands/develop.ts
Labels: status: needs core review, type: bug

#25528 fix(showcase): 404 link ellingtonhammond.com -> ellington-hammond.com
  docs/sites.yml
Labels: topic: showcase

#25237 chore(showcase): Add tatjanavolbeke.com
  docs/sites.yml
Labels: status: needs dx review, topic: showcase

#25467 perf(gatsby-source-contentful): use internal cache to get nodes by type
  packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js
  packages/gatsby-source-contentful/src/download-contentful-assets.js
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: topic: Contentful, topic: performance, topic: scaling builds

#22618 chore(gatsby-page-utils): Migrate package to TypeScript
  packages/gatsby-page-utils/.babelrc
  packages/gatsby-page-utils/package.json
  packages/gatsby-page-utils/src/__tests__/__snapshots__/create-path.ts.snap
  packages/gatsby-page-utils/src/__tests__/create-path.ts
  packages/gatsby-page-utils/src/__tests__/ignore-path.ts
  packages/gatsby-page-utils/src/__tests__/validate-path.ts
  packages/gatsby-page-utils/src/create-path.js
  packages/gatsby-page-utils/src/create-path.ts
  packages/gatsby-page-utils/src/ignore-path.js
  packages/gatsby-page-utils/src/ignore-path.ts
  packages/gatsby-page-utils/src/index.js
  packages/gatsby-page-utils/src/index.ts
  packages/gatsby-page-utils/src/validate-path.ts
  packages/gatsby-page-utils/src/watch-directory.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.js
  yarn.lock
Labels: topic: TypeScript migration

#25502 chore(showcase): Add DeveloperEcosystem.com
  docs/sites.yml
Labels: topic: showcase

#25473 perf(gatsby-source-contentful): experimental flag to skip id normalization
  packages/gatsby-source-contentful/src/fetch.js
  packages/gatsby-source-contentful/src/normalize.js
Labels: topic: Contentful, topic: performance, topic: scaling builds

#25395 chore(showcase): add Neon Law example
  docs/sites.yml
Labels: topic: showcase

#23922 feat(gatsby-source-shopify): accept custom queries
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/gatsby-node.js
Labels: bot: merge on green, status: inkteam assigned, status: needs core review, topic: Shopify

#25426 Add gatsby-plugin-mdx test coverage
  .circleci/config.yml
  e2e-tests/mdx/.gitignore
  e2e-tests/mdx/cypress.json
  e2e-tests/mdx/cypress/integration/pages.js
  e2e-tests/mdx/cypress/plugins/index.js
  e2e-tests/mdx/cypress/support/index.js
  e2e-tests/mdx/gatsby-config.js
  e2e-tests/mdx/package.json
  e2e-tests/mdx/src/components/example.js
  e2e-tests/mdx/src/components/layout.js
  e2e-tests/mdx/src/pages/index.mdx
Labels: topic: MDX

#24138 chore(starters): add gatsby-typescript-eslint-prettier-starter
  docs/starters.yml
Labels: topic: starters

#25545 Adds react as a peer dependency
  packages/gatsby-recipes/package.json
Labels: topic: recipes, type: maintenance

#25275 fix(docs): Add better messaging on how to add new words to the dictionary for spell-check
  docs/contributing/gatsby-style-guide.md
  package.json
  scripts/update-dictionary.js
Labels: type: documentation, type: dx

#24429 chore(docs): Add 21yunbox for deployment
  docs/docs/deploying-to-21yunbox.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#25555 fix(blog): gatsby days - remove local domain
  docs/blog/2020-06-24-Gatsby-Days-Reconfigured-Makenna-Smutz/index.md
  docs/blog/2020-06-25-Gatsby-Days-Reconfigured-Derek-Murr/index.md
  docs/blog/2020-06-30-Gatsby-Days-Reconfigured-Colby-Fayock/index.md
  docs/blog/2020-07-02-Gatsby-Days-Reconfigured-Sam-Julien/index.md
Labels: status: triage needed

#25527 fix(docs): brand name: AgilityCMS -> Agility CMS
  dictionary.txt
  docs/blog/gazette-june-2020/index.md
  docs/docs/headless-cms.md
Labels: status: needs docs review

#25551 chore(www): tidy breakout component
  www/src/components/breakout.js
Labels: topic: website, type: feature or enhancement

#25563 mainenance(www) Remove console.log statement
  www/src/components/shared/cloud-callout.js
Labels: status: triage needed

#25561 refactor(www): clean up get-prev-and-next
  www/src/utils/get-prev-and-next.js
Labels: status: triage needed

#25564 chore(blog): Uupdate some of my mentions
  docs/blog/2018-07-20-why-we-built-the-site-showcase/index.md
  docs/blog/2018-12-19-gatsby-scales-with-expertise-and-scope/index.md
  docs/blog/2019-07-30-how-i-used-theme-ui-to-build-my-gatsby-themes-library/index.md
  docs/blog/author.yaml
  docs/creators/creators.yml
Labels: topic: blogpost

#25378 feat(gatsby): Use state machine for query running in develop
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/query/index.js
  packages/gatsby/src/query/query-watcher.js
  packages/gatsby/src/query/queue.js
  packages/gatsby/src/services/calculate-dirty-queries.ts
  packages/gatsby/src/services/extract-queries.ts
  packages/gatsby/src/services/rebuild-schema-with-site-pages.ts
  packages/gatsby/src/services/run-page-queries.ts
  packages/gatsby/src/services/run-static-queries.ts
  packages/gatsby/src/services/types.ts
  packages/gatsby/src/services/write-out-redirects.ts
  packages/gatsby/src/services/write-out-requires.ts
  packages/gatsby/src/state-machines/query-running/actions.ts
  packages/gatsby/src/state-machines/query-running/index.ts
  packages/gatsby/src/state-machines/query-running/services.ts
  packages/gatsby/src/state-machines/query-running/types.ts
Labels: status: needs core review, topic: develop state machine

#25334 docs(source-wordpress-experimental): update to wordpress sourcing guide
  docs/docs/headless-cms.md
  docs/docs/sourcing-from-wordpress.md
Labels: bot: merge on green

#25329 chore(gatsby-plugin-mdx): be more explicit in explicit api
  packages/gatsby-plugin-mdx/utils/gen-mdx.js
  packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Labels: topic: MDX, type: chore

#25075 Documentation: Docs changes for blog theme 2.0
  docs/docs/images/gatsby-theme-starter-home.png
  docs/docs/images/gatsby-theme-starter-notes.png
  docs/docs/theme-ui.md
  docs/docs/themes/shadowing.md
  docs/docs/themes/using-a-gatsby-theme.md
  docs/docs/themes/using-multiple-gatsby-themes.md
  docs/tutorial/using-a-theme.md
Labels: topic: themes, type: documentation

#25250 chore(categories): Add Ghost to list of categories
  docs/categories.yml
Labels: topic: showcase

#25457 chore(starters): add gatsby-personal-site-template
  docs/starters.yml
Labels: topic: showcase

#25465 chore(showcase): nitrosign.com
  docs/sites.yml
Labels: topic: showcase

#25076 Documentation: Tutorial changes for blog theme 2.0
  docs/docs/themes/shadowing.md
  docs/tutorial/images/starter-blog-theme-default.png
  docs/tutorial/using-a-theme.md
Labels: topic: themes, type: documentation

#25558 (blog) New WordPress source plugin
  docs/blog/2020-07-07-wordpress-source-beta/Gatsby-Wapuus.png
  docs/blog/2020-07-07-wordpress-source-beta/index.mdx
Labels: topic: blogpost

#25572 Revert "Update API Specification doc"
  docs/docs/api-specification.md
Labels: bot: merge on green

#25574 fix: correct wp blog link
  docs/docs/sourcing-from-wordpress.md
Labels: status: triage needed

#25573 chore(gatsby): update yarn lock file
  yarn.lock
Labels: bot: merge on green, type: chore

#25571 chore(www): drop firebase metrics
  www/gatsby-config.js
  www/plugins/gatsby-plugin-perf-metrics/gatsby-ssr.js
  www/plugins/gatsby-plugin-perf-metrics/index.js
  www/plugins/gatsby-plugin-perf-metrics/package.json
Labels: bot: merge on green, topic: website, type: chore

#25576 chore(doc):update API Specification
  docs/docs/api-specification.md
Labels: type: documentation

#25580 chore(circleci): fix conditional step configuration
  .circleci/config.yml
Labels: type: maintenance

#25579 Update starter theme-ui shadowing file
  starters/gatsby-starter-blog-theme/package-lock.json
  starters/gatsby-starter-blog-theme/package.json
  starters/gatsby-starter-blog-theme/src/gatsby-theme-blog/gatsby-plugin-theme-ui/colors.js
  starters/gatsby-starter-blog-theme/src/gatsby-theme-blog/gatsby-plugin-theme-ui/index.js
Labels: topic: themes

#25509 chore(starters): Add gatsby-ghost-novela-starter to starters
  docs/starters.yml
Labels: topic: starters

#25584 enhancement(docs): dictionary.txt -> .yml -> File names in code blocks
  dictionary.txt
  docs/contributing/site-showcase-submissions.md
  docs/contributing/submit-to-starter-library.md
  docs/docs/sourcing-from-netlify-cms.md
Labels: status: triage needed

#25585 enhancement(docs): dictionary.txt -> .babelrc -> File names in code blocks
  dictionary.txt
  docs/docs/babel.md
  docs/docs/migrating-from-v1-to-v2.md
Labels: status: triage needed

#25586 enhancement(docs): standardising graphQL and Graphql into GraphQL in README files
  docs/blog/2019-05-02-how-to-build-a-blog-with-wordpress-and-gatsby-part-3/index.md
  docs/blog/2019-07-23-google-sheets-gatsby-acroyoga-video-explorer/index.md
  packages/gatsby-source-contentful/README.md
  packages/gatsby-transformer-remark/README.md
Labels: status: triage needed

#25593 refactor(www) factor out common doc page content to a fragment
  www/src/components/docs-markdown-page.js
  www/src/templates/template-api-markdown.js
  www/src/templates/template-docs-markdown.js
Labels: status: triage needed

#25437 perf(gatsby-plugin-mdx): prevent babel parse step at sourcing time
  packages/gatsby-plugin-mdx/gatsby/on-create-node.js
  packages/gatsby-plugin-mdx/utils/__tests__/__snapshots__/import-parser.js.snap
  packages/gatsby-plugin-mdx/utils/__tests__/import-parser.js
  packages/gatsby-plugin-mdx/utils/gen-mdx.js
  packages/gatsby-plugin-mdx/utils/import-parser.js
Labels: topic: MDX, topic: performance, topic: scaling builds

#24734 chore(starters): add bradgarropy/gatsby-starter
  docs/starters.yml
Labels: topic: starters

#25505 chore(showcase): Add jeffjadulco.com
  docs/sites.yml
Labels: topic: showcase

#25444 chore(showcase): Raleigh Bikes
  docs/sites.yml
Labels: topic: showcase

#24986 chore(starters): add circle-packing-personal-homepage
  docs/starters.yml
Labels: topic: starters

#25602 chore(gatsby): fix dirty yarn lock
  yarn.lock
Labels: bot: merge on green, type: chore

#25470 fix(gatsby): end activity if plugin didn't do it
  packages/gatsby/src/utils/__tests__/api-runner-node.js
  packages/gatsby/src/utils/api-runner-node.js
Labels: type: maintenance

#24484 add reference to WP plugin
  packages/gatsby-source-wordpress/README.md
Labels: status: needs core review, topic: WordPress

#25271 chore(starters): add gatsby-typescript-app-starter
  docs/starters.yml
Labels: topic: starters

#25315 fix(docs): adding-pagination.md -> grammar fix
  docs/docs/adding-pagination.md
Labels: type: documentation

#25594 fix(docs): disable error message on docs to re-enable retext linter
  dictionary.txt
  docs/blog/2020-07-08-blog-2.0/index.md
  docs/docs/themes/shadowing.md
  docs/tutorial/using-a-theme.md
  package.json
Labels: type: documentation

#25626 enhancement(docs): dictionary.txt -> grapqhl -> brand name
  dictionary.txt
  docs/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/index.md
  docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md
  docs/blog/2019-02-27-reactiflux-q-and-a/index.md
  docs/blog/2019-06-12-performance-improvements-for-large-sites/index.md
  docs/blog/2019-07-23-google-sheets-gatsby-acroyoga-video-explorer/index.md
  docs/contributing/gatsby-style-guide.md
  docs/docs/api-specification.md
  docs/docs/creating-a-transformer-plugin.md
  docs/docs/creating-dynamic-navigation.md
  docs/docs/gatsby-internals-terminology.md
  docs/docs/gatsby-repl.md
  docs/docs/migrating-from-v0-to-v1.md
  docs/docs/migrating-from-v1-to-v2.md
  docs/docs/query-behind-the-scenes.md
  docs/docs/query-execution.md
  docs/docs/query-extraction.md
  docs/docs/recipes/sourcing-data.md
Labels: status: triage needed

#25355 enhancement(docs): dictionary.txt -> fix brand name -> NPM -> npm
  dictionary.txt
  docs/blog/2017-02-21-1-0-progress-update-where-came-from-where-going/index.md
  docs/blog/2017-09-21-community-roundup-1/index.md
  docs/blog/2017-10-16-making-website-building-fun/index.md
  docs/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/index.md
  docs/blog/2018-05-24-launching-new-gatsby-company/index.md
  docs/blog/2018-07-07-the-gatsby-plugin-page-creator/index.md
  docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
  docs/blog/2019-09-26-announcing-gatsby-15m-series-a-funding-round/index.md
  docs/blog/2020-03-11-netlify-functions-and-gatsby-cloud/index.md
  docs/blog/2020-04-15-announcing-gatsby-recipes/index.md
  docs/blog/2020-06-23-Reconfiguring-Gatsby-Days/index.md
  docs/blog/gatsby-v1.md
  docs/contributing/setting-up-your-local-dev-environment.md
  docs/docs/creating-a-transformer-plugin.md
  docs/docs/debugging-html-builds.md
  docs/docs/deploying-to-clodui.md
  docs/docs/environment-variables.md
  docs/docs/gatsby-lifecycle-apis.md
  docs/docs/gatsby-on-windows.md
  docs/docs/glossary.md
  docs/docs/setting-up-gatsby-without-gatsby-new.md
  docs/docs/using-a-plugin-in-your-site.md
  docs/tutorial/part-three/index.md
  docs/tutorial/remark-plugin-tutorial.md
Labels: type: documentation

#25387 docs: Add a note about `gatsby-image` fragments not working in GraphiQL
  docs/tutorial/gatsby-image-tutorial/index.md
Labels: type: documentation

#25434 Update sourcing-data.md
  docs/docs/recipes/sourcing-data.md
Labels: status: needs docs review

#25386 chore(docs): Add Podcast to Resources
  docs/docs/awesome-gatsby-resources.md
Labels: type: documentation

#25435 Update styling-css.md
  docs/docs/recipes/styling-css.md
Labels: status: needs docs review, type: documentation

#25456 Update adding-page-transitions-with-plugin-transition-link.md
  docs/docs/adding-page-transitions-with-plugin-transition-link.md
Labels: type: documentation

#25461 enhancement(docs): Add documentation on the @childOf and @mimeTypes extensions
  docs/docs/schema-customization.md
Labels: status: needs docs review

#25469 Docs links that start with docs/ rather than /docs/
  docs/blog/2020-06-18-Gatsby-cli-survey-2/index.md
  examples/using-multiple-themes/README.md
Labels: status: needs docs review

#25575 migration docs to css loader v1
  docs/docs/migrating-from-v1-to-v2.md
  packages/gatsby-plugin-less/README.md
  packages/gatsby-plugin-postcss/README.md
  packages/gatsby-plugin-sass/README.md
Labels: type: documentation

#25627 refactor(www): more refactors for get-prev-and-next
  www/src/utils/get-prev-and-next.js
Labels: status: triage needed

#25540 chore(www): refactor, tidy and convert Gatsby homepage to function component
  www/src/components/diagram.js
  www/src/components/homepage/homepage-get-started.js
  www/src/pages/index.js
Labels: status: awaiting reviewer response, topic: website, type: feature or enhancement

#25595 chore: upgrade core-js to version 3
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/index.js
  packages/babel-preset-gatsby-package/package.json
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/dependencies.ts.snap
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/dependencies.ts
  packages/babel-preset-gatsby/src/index.js
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/index.ts
  packages/gatsby-graphiql-explorer/package.json
  packages/gatsby-graphiql-explorer/src/app/webpack.config.js
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-mdx/utils/gen-mdx.js
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/__tests__/corejs-resolver.ts
  packages/gatsby/src/utils/webpack/corejs-resolver.ts
  yarn.lock
Labels: status: needs core review, topic: webpack/babel

#25633 fix(www): Fix homepage ecosystem icons
  www/src/components/homepage/homepage-ecosystem.js
Labels: status: triage needed

#25526 chore(www): cleanup TechWithIcon component
  www/src/components/tech-with-icon.js
Labels: status: awaiting reviewer response, topic: website, type: feature or enhancement

#25159 feat(gatsby): add polyfill chunk to gatsby
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/dependencies.ts.snap
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/__tests__/optimize-hook-destructuring.js
  packages/babel-preset-gatsby/src/dependencies.ts
  packages/babel-preset-gatsby/src/index.js
  packages/gatsby-legacy-polyfills/.gitignore
  packages/gatsby-legacy-polyfills/README.md
  packages/gatsby-legacy-polyfills/package.json
  packages/gatsby-legacy-polyfills/src/__tests__/polyfills.js
  packages/gatsby-legacy-polyfills/src/exclude.js
  packages/gatsby-legacy-polyfills/src/polyfills.js
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/develop-static-entry.js
  packages/gatsby/cache-dir/polyfill-entry.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: status: inkteam assigned

#25248 feat(gatsby-recipes): Add GatsbyPage provider
  packages/gatsby-core-utils/src/service-lock.ts
  packages/gatsby-recipes/src/create-types.test.js
  packages/gatsby-recipes/src/providers/gatsby/page.js
  packages/gatsby-recipes/src/resources.js
  packages/gatsby/src/commands/develop.ts
Labels: topic: recipes

#25597 chore(gatsby-admin): remove all custom color treatment
  packages/gatsby-admin/src/components/navbar.tsx
  packages/gatsby-admin/src/components/providers.tsx
  packages/gatsby-admin/src/pages/index.tsx
Labels: topic: admin

#25634 fix(www) Promise.all for api sections
  www/gatsby-node.js
Labels: topic: website, type: maintenance

#25162 feat(gatsby): shim much used polyfills to noOp
  packages/gatsby/cache-dir/polyfills/fetch.js
  packages/gatsby/cache-dir/polyfills/no-op.js
  packages/gatsby/cache-dir/polyfills/object-assign.js
  packages/gatsby/cache-dir/polyfills/whatwg-fetch.js
  packages/gatsby/src/utils/webpack.config.js
Labels: bot: merge on green, status: inkteam assigned

#25614 fix(gatsby): Check if page data exists when hash matches
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/utils/page-data.ts
Labels: status: needs core review

#25639 fix(gatsby-plugin-mdx): ignore anything after an import in mdx
  packages/gatsby-plugin-mdx/utils/__tests__/__snapshots__/import-parser.js.snap
  packages/gatsby-plugin-mdx/utils/__tests__/import-parser.js
  packages/gatsby-plugin-mdx/utils/import-parser.js
Labels: topic: MDX, type: bug

#25578 chore: Migrate gatsby-starter-mdx-basic to monorepo
  starters/gatsby-starter-mdx-basic/.gitignore
  starters/gatsby-starter-mdx-basic/LICENSE
  starters/gatsby-starter-mdx-basic/README.md
  starters/gatsby-starter-mdx-basic/gatsby-config.js
  starters/gatsby-starter-mdx-basic/package-lock.json
  starters/gatsby-starter-mdx-basic/package.json
  starters/gatsby-starter-mdx-basic/src/components/header.js
  starters/gatsby-starter-mdx-basic/src/components/image.js
  starters/gatsby-starter-mdx-basic/src/components/layout.css
  starters/gatsby-starter-mdx-basic/src/components/layout.js
  starters/gatsby-starter-mdx-basic/src/components/seo.js
  starters/gatsby-starter-mdx-basic/src/images/gatsby-astronaut.png
  starters/gatsby-starter-mdx-basic/src/images/gatsby-icon.png
  starters/gatsby-starter-mdx-basic/src/pages/404.js
  starters/gatsby-starter-mdx-basic/src/pages/index.mdx
  starters/gatsby-starter-mdx-basic/src/pages/page-2.mdx
Labels: topic: MDX, topic: starters

#25646 Blog gatsby days cole bemis
  dictionary.txt
  docs/blog/2020-07-09-Gatsby-Days-Reconfigured-Cole-Bemis/index.md
Labels: topic: blogpost

#25644 Add link to blog theme code
  docs/blog/2020-07-08-blog-2.0/index.md
Labels: topic: blogpost

#25651 fix(docs): tutorial theme - fix url 404
  docs/tutorial/using-a-theme.md
Labels: type: documentation

#25652 fix(docs): internal data bridge - add title to code block
  docs/docs/internal-data-bridge.md
Labels: type: documentation

#25624 Fix(www): scope isOfficialPackage() helper to monorepo to prevent broken links
  www/src/utils/is-official-package.js
Labels: topic: website

#25663 enchancement(scripts) Improve sorting of update-dictionary
  scripts/update-dictionary.js
Labels: status: triage needed

#25664 fix(docs): Proper spelling of GraphiQL
  dictionary.txt
  docs/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/index.md
  docs/blog/2017-12-07-taking-gatsby-for-a-spin/index.md
  docs/docs/running-queries-with-graphiql.md
Labels: status: triage needed

#25665 fix(docs) Add backticks on file extensions in docs
  dictionary.txt
  docs/blog/2017-07-19-creating-a-blog-with-gatsby/index.md
  docs/blog/2018-2-7-jam-out-your-blog/index.md
  docs/blog/2019-02-14-behind-the-scenes-q-and-a/index.md
  docs/docs/creating-a-source-plugin.md
  docs/docs/mdx/getting-started.md
  docs/docs/mdx/programmatically-creating-pages.md
  docs/docs/recipes/styling-css.md
  docs/docs/typescript.md
Labels: status: triage needed

#25604 fix(blog): WordPress V4 -> typos
  docs/blog/2020-07-07-wordpress-source-beta/index.mdx
Labels: topic: blogpost

#25501 refactor(www): Refactor and simplify layer model component
  www/src/components/layer-model/code-wrapper.js
  www/src/components/layer-model/component-model/app-layer-example.js
  www/src/components/layer-model/component-model/component-content-sections.js
  www/src/components/layer-model/component-model/content-source.js
  www/src/components/layer-model/component-model/index.js
  www/src/components/layer-model/image-model/image-content-sections.js
  www/src/components/layer-model/image-model/index.js
  www/src/components/layer-model/layer-model.js
  www/src/components/layer-model/layer-tab.js
  www/src/components/layer-model/model-wrapper.js
Labels: topic: website

#25666 refactor(www) Move API call out to its own file
  www/gatsby-node.js
  www/src/utils/node/api-calls.js
  www/src/utils/node/docs.js
Labels: status: triage needed

#25667 refactor(www): Enable API pages to be stubs as well
  www/src/components/docs-markdown-page.js
  www/src/templates/template-docs-markdown.js
Labels: topic: website, type: maintenance

#25668 refactor(www) Override page object instead of passing in more props to docs-template
  www/src/components/__tests__/docs-markdown-page.js
  www/src/components/docs-markdown-page.js
  www/src/templates/template-api-markdown.js
Labels: topic: website, type: maintenance
