Repository gatsbyjs/gatsby, pull requests merged in 2020-08, with the labels that each got.

#26049 [contributing] add link to swag FAQ's in contributing section
  docs/contributing/contributor-swag.md
Labels: status: needs docs review, type: documentation

#26082 [docs] add redux doc to sidebar
  www/src/data/sidebars/doc-links.yaml
Labels: status: needs docs review

#26026 fix(docs): 404 on to links to headers on the same page
  docs/contributing/translation/maintainers.md
  docs/docs/glossary.md
  docs/docs/node-api-helpers.md
  docs/docs/working-with-video.md
Labels: type: documentation

#26196 chore(docs): Added closing brackets missing in documentation
  docs/docs/scroll-restoration.md
Labels: type: documentation

#26171 (blog) Gatsby Gazette for July
  dictionary.txt
  docs/blog/gazette-july-2020/index.md
  docs/blog/gazette-july-2020/reflex.png
Labels: topic: blogpost

#25771 chore(benchmarks): added benchmark code for agility cms.
  benchmarks/source-agilitycms/.env.development.example
  benchmarks/source-agilitycms/.env.production.example
  benchmarks/source-agilitycms/.gitignore
  benchmarks/source-agilitycms/.prettierrc
  benchmarks/source-agilitycms/CODE_OF_CONDUCT.md
  benchmarks/source-agilitycms/LICENSE
  benchmarks/source-agilitycms/README.md
  benchmarks/source-agilitycms/bin/setup.js
  benchmarks/source-agilitycms/bin/update.js
  benchmarks/source-agilitycms/gatsby-config.js
  benchmarks/source-agilitycms/gatsby-node.js
  benchmarks/source-agilitycms/package.json
  benchmarks/source-agilitycms/src/AgilityPage.js
  benchmarks/source-agilitycms/src/agility/components/AgilityPageTemplate.js
  benchmarks/source-agilitycms/src/agility/components/ContentZone.js
  benchmarks/source-agilitycms/src/agility/components/DynamicPreviewPage.js
  benchmarks/source-agilitycms/src/agility/utils.js
  benchmarks/source-agilitycms/src/components/LayoutTemplate.css
  benchmarks/source-agilitycms/src/components/LayoutTemplate_1.js
  benchmarks/source-agilitycms/src/components/LayoutTemplate_2.js
  benchmarks/source-agilitycms/src/components/PreviewBar.css
  benchmarks/source-agilitycms/src/components/PreviewBar.js
  benchmarks/source-agilitycms/src/components/SEO.js
  benchmarks/source-agilitycms/src/img/logo.svg
  benchmarks/source-agilitycms/src/modules/PostDetails.css
  benchmarks/source-agilitycms/src/modules/PostDetails.js
  benchmarks/source-agilitycms/src/modules/PostListing.css
  benchmarks/source-agilitycms/src/modules/PostListing.js
  benchmarks/source-agilitycms/src/modules/RichTextArea.js
  benchmarks/source-agilitycms/src/pageTemplates/MainTemplate.js
  benchmarks/source-agilitycms/static/favicon.ico
Labels: bot: merge on green, topic: AgilityCMS*, topic: benchmarks

#26198 fix(gatsby-plugin-mdx): support import shorthand syntax
  packages/gatsby-plugin-mdx/utils/__tests__/__snapshots__/import-parser.js.snap
  packages/gatsby-plugin-mdx/utils/__tests__/import-parser.js
  packages/gatsby-plugin-mdx/utils/import-parser.js
Labels: bot: merge on green, topic: MDX, type: bug

#26191 Fix gatsby-plugin-mdx not running plugins on findImports(...)
  packages/gatsby-plugin-mdx/utils/__tests__/fixtures/test-plugin.js
  packages/gatsby-plugin-mdx/utils/__tests__/gen-mdx.js
  packages/gatsby-plugin-mdx/utils/gen-mdx.js
Labels: topic: MDX, type: bug

#24463 RFC: File System Routing Improvements
  rfcs/text/0013-file-system-routing-expanded.md
Labels: type: rfc

#26206 fix(gatsby-recipes): Set node version for recipes babelrc to earliest supported version
  packages/gatsby-recipes/.babelrc.json
Labels: bot: merge on green

#26210 Fixed precondition where it adds perma cache to .json files
  docs/docs/deploying-to-iis.md
Labels: bot: merge on green

#26216 fix(docs): correct ESLint plugin name
  docs/docs/eslint.md
Labels: bot: merge on green, type: documentation

#26217 Adds back peer dependency
  packages/gatsby-recipes/package.json
Labels: topic: recipes

#26145 Create blog post for Recipes Alpha II launch
  docs/blog/2020-08-04-Announcing-Gatsby-Recipes-Alpha-2/index.md
Labels: topic: blogpost

#26142 Update update-notifier package
  packages/gatsby-cli/package.json
  yarn.lock
Labels: bot: merge on green, topic: cli

#26219 fix(gatsby-recipes): Update snapshot to reflect latest recipe text
  packages/gatsby-recipes/src/parser/index.test.js
Labels: bot: merge on green, topic: recipes

#26224 fix(blog): juli gazette: fix links 404
  docs/blog/gazette-july-2020/index.md
Labels: status: triage needed

#26223 Add blog post for Community Permissions Changes
  dictionary.txt
  docs/blog/2020-08-04-GH-Community-Permissions-Changes-GatsbyJS/index.md
Labels: topic: blogpost

#26164 Remove README link to Spectrum
  README.md
Labels: type: chore

#26162 feat(gatsby): Store site metadata
  packages/gatsby-cli/src/init-starter.ts
  packages/gatsby-core-utils/src/service-lock.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop.ts
Labels: bot: merge on green, status: needs core review

#26238 Contentful next cleanup
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__fixtures__/starter-blog-data.js
  packages/gatsby-source-contentful/src/__tests__/fetch.js
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/fetch.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/rich-text.js
Labels: bot: merge on green, status: triage needed

#26102 fix: use content type id by default to create reference gql types
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: bot: merge on green, topic: Contentful

#26241 chore(gatsby): cleanup yarn lock
  yarn.lock
Labels: bot: merge on green, type: chore

#26235 fix(gatsby-recipes): fix prop validation & creation of cache keys during installs
  packages/gatsby-recipes/README.md
  packages/gatsby-recipes/src/cli/index.js
  packages/gatsby-recipes/src/graphql-server/index.js
  packages/gatsby-recipes/src/graphql-server/start-dev-cli-server.js
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
  packages/gatsby-recipes/src/providers/npm/package-json.js
  packages/gatsby-recipes/src/recipe-machine/errors.test.js
  packages/gatsby-recipes/src/recipe-machine/index.js
  packages/gatsby-recipes/src/renderer/render.js
Labels: bot: merge on green

#26232 fix(www): Starter library dark mode set text colors
  www/src/views/starter/details.js
  www/src/views/starter/header.js
  www/src/views/starter/source.js
Labels: status: triage needed

#26245 chore: Add Strapi benchmark
  benchmarks/source-strapi/.env.example
  benchmarks/source-strapi/.gitignore
  benchmarks/source-strapi/.prettierignore
  benchmarks/source-strapi/.prettierrc
  benchmarks/source-strapi/LICENSE
  benchmarks/source-strapi/README.md
  benchmarks/source-strapi/gatsby-browser.js
  benchmarks/source-strapi/gatsby-config.js
  benchmarks/source-strapi/gatsby-node.js
  benchmarks/source-strapi/package.json
  benchmarks/source-strapi/src/components/layout_1.js
  benchmarks/source-strapi/src/components/layout_2.js
  benchmarks/source-strapi/src/images/.gitkeep
  benchmarks/source-strapi/src/pages/404.js
  benchmarks/source-strapi/src/pages/index.js
  benchmarks/source-strapi/src/templates/article.js
  benchmarks/source-strapi/update-post.js
Labels: status: triage needed

#26221 fix(gatsby): enable ipc messaging on develop
  integration-tests/structured-logging/__tests__/ipc-send.js
  packages/gatsby/src/commands/develop.ts
Labels: bot: merge on green, status: needs core review, topic: admin

#26252 fix(gatsby-recipes): Handle string values in NPMPackageJSON + more robust showing of validation errors on install
  packages/gatsby-recipes/src/cli/index.js
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
  packages/gatsby-recipes/src/providers/npm/package-json.js
Labels: bot: merge on green

#26253 fix(gatsby-recipes): also show general errors
  packages/gatsby-recipes/src/cli/index.js
Labels: bot: merge on green

#26258 Add NPMPackageJson Docs
  packages/gatsby-recipes/README.md
Labels: bot: merge on green, topic: recipes

#25048 feat(gatsby-source-graphql): Add transformSchema option
  packages/gatsby-source-graphql/README.md
  packages/gatsby-source-graphql/src/gatsby-node.js
Labels: bot: merge on green, status: inkteam assigned, status: needs core review, status: needs docs review

#25038 feat(gatsby-source-npm-package-search): add Node type NpmPackage
  packages/gatsby-source-npm-package-search/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-source-npm-package-search/src/gatsby-node.js
Labels: bot: merge on green, status: inkteam assigned, status: needs core review

#26264 Improve Strapi benchmark performance
  benchmarks/source-strapi/gatsby-node.js
Labels: topic: benchmarks

#26242 fix(gatsby): Move static queries to page data dir
  packages/babel-plugin-remove-graphql-queries/src/index.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.ts.snap
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/websocket-manager.ts
Labels: topic: StaticQuery

#26248 docs(gatsby-plugin-netlify): update README with more detail for client only routes
  packages/gatsby-plugin-netlify/README.md
Labels: type: documentation

#26186 fix(docs): css-framworks: fix brand name
  docs/docs/other-css-frameworks.md
Labels: status: needs docs review

#26275 chore(gatsby-recipes): Add provider and resource docs
  packages/gatsby-recipes/src/providers/README.md
Labels: topic: recipes

#26254 fix(gatsby-recipes): rename/remove internal fields
  packages/gatsby-recipes/.gitignore
  packages/gatsby-recipes/src/apply-plan.js
  packages/gatsby-recipes/src/cli/index.js
  packages/gatsby-recipes/src/create-plan.js
  packages/gatsby-recipes/src/gui.js
  packages/gatsby-recipes/src/parser/index.js
  packages/gatsby-recipes/src/recipe-machine/errors.test.js
  packages/gatsby-recipes/src/recipe-machine/index.js
  packages/gatsby-recipes/src/recipe-machine/index.test.js
Labels: topic: recipes

#26280 chore(gatsby-recipes): Move recipe resolving to its own step in state machine
  packages/gatsby-recipes/src/parser/index.js
  packages/gatsby-recipes/src/parser/index.test.js
  packages/gatsby-recipes/src/recipe-machine/index.js
  packages/gatsby-recipes/src/recipe-machine/index.test.js
  packages/gatsby-recipes/src/resolve-recipe.js
Labels: bot: merge on green, topic: recipes

#26279 chore(docs): Fix links to gatsby-theme-blog and -core
  docs/docs/configuring-usage-with-plugin-options.md
Labels: type: documentation

#26277 chore(docs): Fix broken link to the gatsby-theme-blog
  docs/docs/naming-a-plugin.md
Labels: type: documentation

#26281 fix(gatsby-recipes): fix for when recipes have multiple NPMPackageJSON resources
  packages/gatsby-recipes/src/cli/index.js
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
  packages/gatsby-recipes/src/providers/npm/package-json.js
  packages/gatsby-recipes/src/renderer/render.js
Labels: topic: recipes

#26291 feat(gatsby): add flag to disable schema rebuilding
  packages/gatsby/src/services/build-schema.ts
Labels: bot: merge on green, topic: internal

#26283 feat(gatsby-recipes): live stream updates from creating resources
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/apply-plan.js
  packages/gatsby-recipes/src/graphql-server/server.js
  packages/gatsby-recipes/src/recipe-machine/index.js
  packages/gatsby-recipes/src/recipe-machine/index.test.js
  packages/gatsby-recipes/src/renderer/index.js
  packages/gatsby-recipes/src/renderer/reconciler.js
  packages/gatsby-recipes/src/renderer/render.js
  packages/gatsby-recipes/src/validate-steps.js
Labels: topic: recipes

#26324 chore(eslint): ignore generated gatsby/gatsby-admin-public folder
  .eslintignore
Labels: bot: merge on green, topic: dev tooling

#26327 chore(gatsby-recipes): add missing ink-box dependency
  packages/gatsby-recipes/package.json
  yarn.lock
Labels: topic: recipes

#26011 Typo in netlify plugin docs
  packages/gatsby-plugin-netlify/README.md
Labels: bot: merge on green

#26329 fix(gatsby-plugin-offline): Update regex to catch new static query results
  packages/gatsby-plugin-offline/src/gatsby-node.js
Labels: bot: merge on green, type: bug

#26295 docs: Updated gatsby-plugin-offline README with correct default workbox config
  packages/gatsby-plugin-offline/README.md
Labels: bot: merge on green, topic: PWA

#24999 docs(gatsby-plugin-sharp): Base64 features
  packages/gatsby-plugin-sharp/README.md
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-sharp/src/__tests__/index.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/plugin-options.js
Labels: topic: sharp

#26020 fix(gatsby): Added { default } to default exports
  packages/gatsby/src/utils/validate-page-component.ts
Labels: type: bug

#26222 Create unlinked reference doc for new file system based route APIs
  docs/docs/file-system-page-creation.md
Labels: type: documentation

#26307 fix(gatsby-recipes): speedup recipe runs for recipes with large numbers of resources
  packages/gatsby-recipes/src/graphql-server/server.js
  packages/gatsby-recipes/src/recipe-machine/index.js
  packages/gatsby-recipes/src/renderer/render.js
Labels: topic: recipes

#26299 mezzoguild showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#26298 chore(starters): add gatsby-starter-netlify-docs
  docs/starters.yml
Labels: bot: merge on green, topic: starters

#26309 docs(gatsby-image): Deprecate `sizes` and `resolutions` props
  docs/tutorial/gatsby-image-tutorial/index.md
  docs/tutorial/wordpress-image-tutorial.md
  packages/gatsby-image/src/index.js
Labels: bot: merge on green, topic: images/media

#26339 Increase verdaccio max_body_size
  packages/gatsby-dev-cli/src/local-npm-registry/verdaccio-config.js
Labels: topic: dev tooling

#24561 chore(showcase): Add narrationbox.com
  docs/sites.yml
Labels: topic: showcase

#26141 Update themes development instructions
  docs/contributing/code-contributions.md
Labels: type: documentation

#26282 Docs update issue templates
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/question.md
Labels: status: needs docs review

#25390 Create governance.md
  docs/contributing/gatsby-governance-model.md
Labels: type: documentation

#25204 feat(gatsby): Experimental unified routes
  e2e-tests/development-runtime/cypress/integration/unified-routing/client-side-routes.js
  e2e-tests/development-runtime/cypress/integration/unified-routing/collection-routing.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/src/pages/client-dynamic-route/[id].js
  e2e-tests/development-runtime/src/pages/client-dynamic-route/splat/[...].js
  e2e-tests/development-runtime/src/pages/collection-routing/root.js
  e2e-tests/development-runtime/src/pages/collection-routing/{ImageSharp.parent__(File)__name}.js
  e2e-tests/development-runtime/src/pages/collection-routing/{MarkdownRemark.fields__slug}.js
  e2e-tests/development-runtime/src/pages/index.js
  e2e-tests/production-runtime/.env.production
  e2e-tests/production-runtime/cypress/integration/unified-routing/client-side-routes.js
  e2e-tests/production-runtime/cypress/integration/unified-routing/collection-routing.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/pages/client-dynamic-route/[id].js
  e2e-tests/production-runtime/src/pages/client-dynamic-route/splat/[...].js
  e2e-tests/production-runtime/src/pages/collection-routing/root.js
  e2e-tests/production-runtime/src/pages/collection-routing/{Product.name}.js
  e2e-tests/production-runtime/src/pages/index.js
  packages/babel-plugin-remove-graphql-queries/src/index.js
  packages/gatsby-plugin-page-creator/package.json
  packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
  packages/gatsby-plugin-page-creator/src/__tests__/extract-query.ts
  packages/gatsby-plugin-page-creator/src/__tests__/get-collection-route-params.ts
  packages/gatsby-plugin-page-creator/src/__tests__/get-match-path.ts
  packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/__tests__/validate-path-query.ts
  packages/gatsby-plugin-page-creator/src/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/create-client-only-page.ts
  packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/derive-path.ts
  packages/gatsby-plugin-page-creator/src/extract-query.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.js
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby-plugin-page-creator/src/get-collection-route-params.ts
  packages/gatsby-plugin-page-creator/src/get-match-path.ts
  packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/path-utils.ts
  packages/gatsby-plugin-page-creator/src/validate-path-query.ts
  packages/gatsby-plugin-page-creator/src/watch-collection-builder.ts
  packages/gatsby-plugin-page-creator/tsconfig.json
  packages/gatsby/cache-dir/__tests__/find-path.js
  packages/gatsby/cache-dir/find-path.js
  packages/gatsby/cache-dir/gatsby-browser-entry.js
  packages/gatsby/cache-dir/page-renderer.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/redux/reducers/components.ts
  packages/gatsby/src/utils/__tests__/js-chunk-names.ts
  packages/gatsby/src/utils/js-chunk-names.ts
  yarn.lock
Labels: type: feature or enhancement

#26341 fix(gatsby-recipes): remove trailing config as we do want it to run again to ensure all resource updates are flushed
  packages/gatsby-recipes/src/renderer/render.js
Labels: bot: merge on green, topic: recipes

#26302 chore(starters): add gatsby-starter-texblog
  docs/starters.yml
Labels: bot: merge on green, topic: starters

#26356 chore(requires-writer): update auto-generated code to not trigger no-mixed-operators eslint warnings/errors
  packages/gatsby/src/bootstrap/requires-writer.ts
Labels: topic: webpack/babel, type: maintenance

#25862 feat(gatsby-cli): Allow setting the server status port
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/socketIo.js
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/restarting-screen.ts
Labels: topic: cli

#26265 benchmarks(mdx): add new baseline mdx benchmark
  benchmarks/mdx-without-images/.gitattributes
  benchmarks/mdx-without-images/.gitignore
  benchmarks/mdx-without-images/.prettierrc.js
  benchmarks/mdx-without-images/LICENSE
  benchmarks/mdx-without-images/README.md
  benchmarks/mdx-without-images/gatsby-browser.js
  benchmarks/mdx-without-images/gatsby-config.js
  benchmarks/mdx-without-images/gatsby-node.js
  benchmarks/mdx-without-images/gen.js
  benchmarks/mdx-without-images/package.json
  benchmarks/mdx-without-images/src/components/layout_1.js
  benchmarks/mdx-without-images/src/components/layout_2.js
  benchmarks/mdx-without-images/src/pages/#index.js#
  benchmarks/mdx-without-images/src/pages/index.js
  benchmarks/mdx-without-images/src/templates/article.js
  benchmarks/mdx-without-images/static/favicon.ico
  benchmarks/mdx-without-images/styles.css
Labels: topic: MDX, topic: benchmarks

#26358 fix(gatsby): set correct content-type header for socket.io.js
  packages/gatsby/src/utils/develop-proxy.ts
Labels: bot: merge on green, topic: admin

#26357 fix(gatsby-plugin-page-creator): juggle reporter dont depend on cli
  packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts
Labels: bot: merge on green, type: bug

#24775 docs(gatsby): Query Filters
  docs/docs/query-filters.md
  docs/docs/schema-sift.md
  www/src/data/sidebars/doc-links.yaml
Labels: status: needs core review, topic: GraphQL, type: documentation

#26355 chore(gatsby-admin): fix built html not having layout wrappers
  packages/gatsby-admin/gatsby-ssr.js
Labels: status: triage needed, topic: admin

#26361 Fix linting in admin
  packages/gatsby-admin/gatsby-ssr.js
Labels: topic: admin

#26360 fix(gatsby): improve the log for service lock issues
  packages/gatsby/src/commands/develop.ts
Labels: bot: merge on green, topic: cli

#26297 enhancement(docs): dictionary.txt -> fix tiwtter name -> AskGatsbyJS
  dictionary.txt
  docs/blog/100days/apps/index.md
  docs/blog/100days/cms/index.md
  docs/blog/100days/comments/index.md
  docs/blog/100days/create-themes/index.md
  docs/blog/100days/free-hosting/index.md
  docs/blog/100days/gatsby-image/index.md
  docs/blog/100days/mdx/index.md
  docs/blog/100days/pwa/index.md
  docs/blog/100days/react-component/index.md
  docs/blog/100days/serverless/index.md
  docs/blog/100days/use-themes/index.md
  docs/blog/2020-03-23-introducing-gatsby-web-creators/index.md
Labels: bot: merge on green, type: documentation

#26269 chore(gatsby): update semver
  packages/gatsby-cli/package.json
  packages/gatsby-plugin-manifest/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby/package.json
Labels: type: maintenance

#26270 Parameterise telemetry constructor
  packages/gatsby-telemetry/src/__tests__/telemetry.ts
  packages/gatsby-telemetry/src/declarations.d.ts
  packages/gatsby-telemetry/src/event-storage.ts
  packages/gatsby-telemetry/src/index.ts
  packages/gatsby-telemetry/src/telemetry.ts
  packages/gatsby-telemetry/tsconfig.json
Labels: bot: merge on green, topic: telemetry*

#26349 fix(gatsby-recipes): fix NPMScript for parallel calls
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/site-metadata.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
  packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
  packages/gatsby-recipes/src/providers/gatsby/site-metadata.js
  packages/gatsby-recipes/src/providers/gatsby/site-metadata.test.js
  packages/gatsby-recipes/src/providers/lock.js
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
  packages/gatsby-recipes/src/providers/npm/__snapshots__/script.test.js.snap
  packages/gatsby-recipes/src/providers/npm/package-json.js
  packages/gatsby-recipes/src/providers/npm/package-json.test.js
  packages/gatsby-recipes/src/providers/npm/script.js
  packages/gatsby-recipes/src/providers/npm/script.test.js
  yarn.lock
Labels: bot: merge on green, topic: recipes

#26347 chore(docs): detailed info on licensing starters
  dictionary.txt
  docs/docs/creating-a-starter.md
Labels: bot: merge on green, type: documentation

#26371 Fix typos and linter dictionary errors
  dictionary.txt
  docs/docs/query-filters.md
Labels: status: needs docs review

#22189 chore(gatsby): Convert jobs-manager to typescript
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/jobs-manager.ts
Labels: bot: merge on green, topic: TypeScript migration

#25504 Stripe eCommerce tutorial prices migration
  docs/tutorial/ecommerce-tutorial/index.md
  examples/ecommerce-tutorial-with-stripe/.env.example
  examples/ecommerce-tutorial-with-stripe/.gitignore
  examples/ecommerce-tutorial-with-stripe/README.md
  examples/ecommerce-tutorial-with-stripe/gatsby-config.js
  examples/ecommerce-tutorial-with-stripe/netlify.toml
  examples/ecommerce-tutorial-with-stripe/package.json
  examples/ecommerce-tutorial-with-stripe/src/components/Products/ProductCard.js
  examples/ecommerce-tutorial-with-stripe/src/components/Products/Products.js
  examples/ecommerce-tutorial-with-stripe/src/components/Products/SkuCard.js
  examples/ecommerce-tutorial-with-stripe/src/components/Products/Skus.js
  examples/ecommerce-tutorial-with-stripe/src/components/checkout.js
  examples/ecommerce-tutorial-with-stripe/src/components/layout.js
  examples/ecommerce-tutorial-with-stripe/src/pages/advanced.js
  examples/ecommerce-tutorial-with-stripe/src/utils/stripejs.js
Labels: bot: merge on green, type: documentation

#26380 fix(structured-logging): fix wrongly reporting status as success when we should still be in pending state
  packages/gatsby-cli/src/reporter/redux/__tests__/integration.ts
  packages/gatsby-cli/src/reporter/redux/__tests__/internal-actions.ts
  packages/gatsby-cli/src/reporter/redux/index.ts
  packages/gatsby-cli/src/reporter/redux/internal-actions.ts
Labels: topic: reporter

#25989 fix(recipes): Install storybook dependencies with development type on typescript recipe
  packages/gatsby-recipes/recipes/storybook-ts.mdx
Labels: topic: recipes

#24767 fix(gatsby-image): Fix typings for fixed and fluid props
  packages/gatsby-image/index.d.ts
  packages/gatsby-image/withIEPolyfill/index.d.ts
Labels: topic: TypeScript migration

#25991 fix(deps): install deps as devDependencies on storybook recipe
  packages/gatsby-recipes/recipes/storybook-js.mdx
Labels: topic: recipes

#26392 fix(gatsby-source-graphql): use the latest version of graphql-tools
  packages/gatsby-source-graphql/package.json
Labels: bot: merge on green, topic: GraphQL

#26397 fix: update yarn.lock after recent gatsby-source-graphql version bump
  yarn.lock
Labels: bot: merge on green

#25243 chore(starters): update gatsby-vapor
  docs/starters.yml
Labels: topic: starters

#25535 chore(starters): add gatsby-starter-catalyst-lithium
  docs/starters.yml
Labels: topic: starters

#25692 chore(starters): add awesome-gatsby-starter-ts
  docs/starters.yml
Labels: topic: starters

#26089 chore(showcase): Add redcentral.co.uk
  docs/sites.yml
Labels: topic: showcase

#25754 chore(showcase): Add Crogic
  docs/sites.yml
Labels: topic: showcase

#26384 chore(showcase): add alexperronnet.io
  docs/sites.yml
Labels: status: awaiting reviewer response, topic: showcase

#25660 update lowmess repo
  docs/sites.yml
Labels: topic: showcase

#26257 chore(showcase): Add Laputan Schools (schools.laputan.com.au)
  docs/sites.yml
Labels: topic: showcase

#26014 chore(starters): add BooGi starter
  docs/starters.yml
Labels: topic: starters

#26374 chore(starters): add gatsby-starter-hoa
  docs/starters.yml
Labels: status: awaiting reviewer response, topic: starters

#25145 chore(starters): add gatsby-typescript-markdown-starter
  docs/starters.yml
Labels: topic: starters

#25026 chore(starters): adding gatsby-starter-github-repositories
  docs/starters.yml
Labels: topic: starters

#24901 chore(starters): Add gatsby-starter-code-notes
  docs/starters.yml
Labels: topic: starters

#25542 chore(starters): add gatsby-starter-testing
  docs/starters.yml
Labels: topic: starters

#25731 chore(starters): Add gatsby-starter-fresh to starters
  docs/starters.yml
Labels: topic: starters

#25697 chore(starters): add gatsby-opinionated-starter
  docs/starters.yml
Labels: topic: starters

#26061 chore(starters): add gatsby-starter-leonids
  docs/starters.yml
Labels: topic: starters

#25772 docs(starters): Add Minimal Portfolio Starter
  docs/starters.yml
Labels: topic: showcase

#26070 chore(starters): add websheets-listing-page
  docs/starters.yml
Labels: topic: starters

#26251 chore(starters): add gatsby-bootstrap-template
  docs/starters.yml
Labels: status: awaiting reviewer response, topic: starters

#25000 chore(starter): add Kentico Kontent Intranet showcase
  docs/starters.yml
Labels: topic: starters

#25893 chore(starters): adds gatsby-starter-emulsify-mdx
  docs/categories.yml
  docs/starters.yml
Labels: status: needs docs review, topic: showcase

#26400 fix(reporter): add missing verbose/debug log handler to yurnalist logger
  packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
Labels: topic: reporter

#25415 chore(starters): add gatsby-starter-emotion-theme
  docs/starters.yml
Labels: topic: starters

#26170 chore(starters): add gatsy-p5-starter
  docs/starters.yml
Labels: topic: showcase

#26317 chore(starters): add gatsby-starter-vadyan
  docs/starters.yml
Labels: topic: starters

#26286 chore(starters): add gatsby-starter-essentials
  docs/starters.yml
Labels: topic: starters

#26180 chore(starters): add gatsby-starter-level-2
  docs/starters.yml
Labels: status: awaiting reviewer response, topic: starters

#25043 Chore(docs): add gatsby-tfs-acme-starter to starter
  docs/starters.yml
Labels: topic: starters

#26331 chore(starters): add gatsby-portfolio
  docs/starters.yml
Labels: topic: starters

#26278 chore(starters): add gatsby-starter-skeleton
  docs/starters.yml
Labels: topic: showcase

#26220 chore(starters): add gatsby-starter-blog-boost
  docs/starters.yml
Labels: topic: showcase, topic: starters

#26288 chore(starters): add gatsby-starter-lamma
  docs/starters.yml
Labels: topic: showcase

#25445 Showcase addition: LANDTX
  docs/sites.yml
Labels: status: awaiting author response, topic: showcase

#26080 chore(showcase): add websheets-listing-page
  docs/sites.yml
Labels: topic: showcase

#25947 fix(gatsby-remark-images-contentful): Support custom Url search params in inline markdown images
  packages/gatsby-remark-images-contentful/src/__tests__/utils/__snapshots__/index.js.snap
  packages/gatsby-remark-images-contentful/src/__tests__/utils/index.js
  packages/gatsby-remark-images-contentful/src/index.js
  packages/gatsby-remark-images-contentful/src/utils/index.js
Labels: bot: merge on green, status: needs core review, topic: Contentful, topic: Markdown/remark

#26107 chore(showcase): add FatihaTV
  docs/sites.yml
Labels: topic: showcase

#26140 Showcase: request to add Oomph to directory
  docs/sites.yml
Labels: topic: showcase

#26261 Update sites.yml
  docs/sites.yml
Labels: topic: showcase

#26260 updated showcase to include webplace.com.au
  docs/creators/creators.yml
  docs/creators/images/webplace.png
  docs/sites.yml
Labels: topic: showcase

#25516 chore(starters): add gatsby-snipcart-eccomerce
  docs/starters.yml
Labels: topic: starters

#25842 chore(showcase) Adds marcuswood.io
  docs/sites.yml
Labels: topic: showcase

#26123 Add UP42 website
  docs/sites.yml
Labels: topic: showcase

#25431 chore(showcase): Prescriptive Solutions
  docs/sites.yml
Labels: topic: showcase

#25781 Added zn.agency to showcase
  docs/sites.yml
Labels: topic: showcase

#26255 chore(showcase): Add "Ámbito Dólar" site.
  docs/sites.yml
Labels: topic: showcase

#26062 chore(showcase): Add Github Profile README Generator
  docs/sites.yml
Labels: topic: showcase

#25826 add conceptclassesindore to site showcase
  docs/sites.yml
Labels: topic: showcase

#25801 Accessible blog + portfolio to site showcase
  docs/sites.yml
Labels: topic: showcase

#26233 add laury.dev to site showcase
  docs/sites.yml
Labels: topic: showcase

#26399 Change to lowercase p on 'About withWebP' header
  docs/docs/gatsby-image.md
Labels: bot: merge on green

#26395 Update index.md
  docs/tutorial/part-seven/index.md
Labels: bot: merge on green

#26396 fix(gatsby): place auto-generated virtual modules in `.cache`
  packages/gatsby/src/utils/__tests__/map-templates-to-static-query-hashes.js
  packages/gatsby/src/utils/gatsby-webpack-virtual-modules.ts
  packages/gatsby/src/utils/map-templates-to-static-query-hashes.ts
Labels: bot: merge on green, topic: webpack/babel

#26386 fix(gatsby-recipe): let resources declare dependencies & validate recipes & ensure dependencies installed first
  packages/gatsby-recipes/README.md
  packages/gatsby-recipes/src/apply-plan.js
  packages/gatsby-recipes/src/cli/index.js
  packages/gatsby-recipes/src/create-plan.js
  packages/gatsby-recipes/src/find-dependency-match.js
  packages/gatsby-recipes/src/graphql-server/server.js
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
  packages/gatsby-recipes/src/recipe-machine/index.js
  packages/gatsby-recipes/src/renderer/render.js
Labels: topic: recipes

#26410 fix(gatsby-recipes): add missing var for the recipes selector
  packages/gatsby-recipes/src/cli/index.js
Labels: bot: merge on green

#26373 chore(gatsby-plugin-page-creator): Standardize error reporting text
  packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
  packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/__tests__/validate-path-query.ts
  packages/gatsby-plugin-page-creator/src/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/derive-path.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/path-utils.ts
  packages/gatsby-plugin-page-creator/src/validate-path-query.ts
  packages/gatsby-plugin-page-creator/src/watch-collection-builder.ts
Labels: status: inkteam assigned

#26415 chore(docs): Update docs/site contributing docs
  docs/contributing/docs-and-blog-components.md
  docs/contributing/docs-contributions.md
  docs/contributing/gatsby-style-guide.md
  docs/contributing/how-to-label-an-issue.md
  docs/contributing/translation/index.md
  docs/contributing/translation/new-translations.md
  docs/contributing/website-contributions.md
  docs/docs/gatsby-agency-partnership.md
  scripts/i18n/create.js
  www/redirects.yaml
  www/src/data/sidebars/contributing-links.yaml
Labels: type: documentation

#26420 fix(gatsby-recipes): some code cleanups + tests
  packages/gatsby-recipes/src/__tests__/__snapshots__/find-dependency-match.js.snap
  packages/gatsby-recipes/src/__tests__/find-dependency-match.js
  packages/gatsby-recipes/src/find-dependency-match.js
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
  packages/gatsby-recipes/src/recipe-machine/index.js
  packages/gatsby-recipes/src/renderer/render.js
Labels: status: triage needed

#25503 feat(docs): Better docs for big chunk of schema stuff
  docs/docs/node-creation.md
  docs/docs/schema-connections.md
  docs/docs/schema-generation.md
  docs/docs/schema-inference.md
  docs/docs/schema-input-gql.md
  docs/docs/schema-root-fields.md
  www/redirects.yaml
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#26442 chore(docs): Update docs to reflect changing showcase/starter submission workflow
  docs/contributing/code-contributions.md
  docs/contributing/community-contributions.md
  docs/contributing/how-to-open-a-pull-request.md
  docs/contributing/site-showcase-submissions.md
  docs/contributing/submit-to-creator-showcase.md
  docs/contributing/submit-to-starter-library.md
  docs/docs/gatsby-agency-partnership.md
  docs/docs/gatsby-vendor-partnership.md
  docs/docs/starters.md
  www/redirects.yaml
  www/src/data/sidebars/contributing-links.yaml
  www/src/data/sidebars/doc-links.yaml
Labels: status: triage needed

#26459 chores(docs): #26449 update logo url in all READMEs
  README.md
  benchmarks/source-agilitycms/README.md
  e2e-tests/development-runtime/README.md
  examples/data-fetching/README.md
  examples/ecommerce-tutorial-with-stripe/README.md
  examples/graphql-reference/README.md
  examples/using-MDX/README.md
  examples/using-jest/README.md
  examples/using-multiple-themes/README.md
  examples/using-shopify/README.md
  examples/using-square-payments/README.md
  examples/using-type-definitions/README.md
  packages/gatsby/README.md
  starters/README-template.md
  starters/README.md
  starters/blog/README.md
  starters/default/README.md
  starters/gatsby-starter-blog-theme-core/README.md
  starters/gatsby-starter-blog-theme/README.md
  starters/gatsby-starter-minimal/README.md
  starters/gatsby-starter-notes-theme/README.md
  starters/gatsby-starter-plugin/README.md
  starters/gatsby-starter-theme-workspace/README.md
  starters/gatsby-starter-theme/README.md
  starters/hello-world/README.md
Labels: type: documentation

#26427 chore(docs): use gatsby.com in doc-writing-process.md
  docs/contributing/docs-writing-process.md
Labels: status: needs docs review

#26418 Bump gatsby to 2.24.42.
  docs/tutorial/part-zero/index.md
  starters/gatsby-starter-theme/package.json
Labels: status: awaiting author response, topic: starters, type: documentation
