Repository gatsbyjs/gatsby, pull requests merged in 2020-12, with the labels that each got.

#28372 fix(gatsby-plugin-image): Fix StaticImage props interface and add propTypes
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/components/static-image.tsx
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-image/src/utils.ts
  packages/gatsby-plugin-image/tsconfig.json
Labels: status: triage needed

#28395 fix(gatsby): move starting dev-ssr listener inside function & only init listeners once
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap
Labels: type: feature or enhancement

#28400 fix(assert-changed-files): don't skip running tests on master
  scripts/assert-changed-files.sh
Labels: topic: automation

#28018 Feat: (gatsby-cli) Add a CLI command for listing plugins
  integration-tests/gatsby-cli/__tests__/plugin.js
  integration-tests/gatsby-cli/gatsby-sites/gatsby-plugin/.eslintrc
  integration-tests/gatsby-cli/gatsby-sites/gatsby-plugin/.gitignore
  integration-tests/gatsby-cli/gatsby-sites/gatsby-plugin/gatsby-config.js
  integration-tests/gatsby-cli/gatsby-sites/gatsby-plugin/package.json
  integration-tests/gatsby-cli/gatsby-sites/gatsby-plugin/src/pages/index.js
  packages/create-gatsby/src/install-plugins.ts
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby-cli/src/handlers/plugin-add.ts
  packages/gatsby-cli/src/handlers/plugin.ts
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
Labels: topic: cli

#28408 Revert "fix(assert-changed-files): don't skip running tests on master"
  scripts/assert-changed-files.sh
Labels: topic: automation

#28381 fix(gatsby): handle in dev-ssr when a page is deleted (#28325)
  integration-tests/ssr/__tests__/ssr.js
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
Labels: type: cherry

#28382 feature(gatsby): Warn when there's unknown flags in gatsby-config.js & suggest fixes to potential typos (#28326)
  examples/using-drupal/gatsby-config.js
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap
  packages/gatsby/src/utils/__tests__/handle-flags.ts
  packages/gatsby/src/utils/handle-flags.ts
Labels: type: cherry

#28383 chore(gatsby): Invite more people to try QUERY_ON_DEMAND (#28327)
  packages/gatsby/src/services/run-page-queries.ts
Labels: type: cherry

#28410 fix(gatsby-plugin-image): Add overflow hidden back to wrapper CSS
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/hooks.ts
Labels: topic: images/media

#28187 chore(gatsby): add StaticQuery to SSR test
  integration-tests/ssr/package.json
  integration-tests/ssr/src/pages/hi.js
  integration-tests/ssr/test-output.js
Labels: type: bug

#28214 feature(gatsby): Add experiment to run source plugins in parallel
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/flags.ts
Labels: topic: scaling builds

#28409 fix(gatsby): Add `FAST_REFRESH` config flag
  packages/gatsby/cache-dir/app.js
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/get-react-hot-loader-strategy.ts
Labels: topic: hot reloading*

#28346 fix(gatsby): re-render route when location state changes
  e2e-tests/development-runtime/cypress/integration/navigation/linking.js
  e2e-tests/development-runtime/src/pages/navigation-effects.js
  packages/gatsby/cache-dir/navigation.js
Labels: bot: merge on green, topic: frontend-core

#28415 fix(gatsby): correct tracing for GraphQL queries
  packages/gatsby/src/query/graphql-runner.ts
Labels: topic: GraphQL

#28417 fix(gatsby-recipes): add isLocal to schema for GatsbyPlugin
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
Labels: bot: merge on green

#27384 fix(gatsby): scroll restoration issue in browser API
  packages/gatsby/cache-dir/navigation.js
Labels: bot: merge on green, status: needs core review, topic: frontend-core

#28416 feature(gatsby): style the SSR error page
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
  packages/gatsby/src/utils/__tests__/__snapshots__/develop-html-route.ts.snap
  packages/gatsby/src/utils/dev-ssr/develop-html-route.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js
Labels: type: feature or enhancement

#28424 docs: note about emotion major bump, slightly restructured notes
  docs/reference/release-notes/v2.28/index.md
Labels: status: triage needed

#28334 feat(gatsby): Add new caching clearing behavior for webpack/file downloads behind flags
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/start-server.ts
Labels: impact: high, topic: scaling builds

#28380 docs: release notes for 2.28
  docs/reference/release-notes/v2.28/index.md
Labels: type: documentation

#28421 Revert "docs: temporary fix to emotion tutorial (#28248)"
  docs/docs/emotion.md
Labels: type: documentation

#28335 chore(benchmarks): upgrade contentful for wib
  benchmarks/source-contentful/package.json
Labels: topic: Contentful, topic: benchmarks

#28365 chore: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/new_translation.md
Labels: type: chore

#28432 chore(gatsby): fold three loops into one
  packages/gatsby/src/query/index.js
Labels: type: chore

#28433 chore(gatsby): remove `async/await` where not needed
  packages/gatsby/src/schema/schema.js
Labels: type: chore

#28437 chore(gatsby-source-contentful): trap base64 disk write
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: Contentful, type: chore

#28439 chore(gatsby-source-contentful): drop unnecessary promise, _.get
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: Contentful, type: chore

#28435 chore(gatsby): refactor into await syntax
  packages/gatsby/src/query/queue.ts
Labels: type: chore

#28440 chore(gatsby-source-contentful): simplify url arg generation
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: Contentful, type: chore

#28441 chore(gatsby-source-contentful): drop last usages of lodash
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: Contentful, type: chore

#28444 chore(gatsby-source-contentful): cache the cache key
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: topic: Contentful, type: chore

#28438 perf(gatsby-source-contentful): prevent redundant fs/remote fetches for base64
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: Contentful, topic: performance, topic: scaling builds

#27640 [docs][guides] improvements to Why Gatsby Uses GraphQL #15235
  docs/docs/why-gatsby-uses-graphql.md
Labels: hacktoberfest-accepted, status: needs docs review, type: documentation

#28405 Tell user to supply BOTH keys in .env.development for Gatsby E-commerce Tutorial.
  docs/tutorial/ecommerce-tutorial/index.md
Labels: type: documentation

#28448 chore(gatsby): specify in description for LAZY_IMAGES min supported version of gatsby-plugin-sharp
  packages/gatsby/src/utils/flags.ts
Labels: bot: merge on green, type: chore

#28459 fix(gatsby-source-graphql): Pin resolution of extract-files
  package.json
  yarn.lock
Labels: topic: dev tooling

#28447 feature(gatsby): add new cache flags to FAST_DEV
  packages/gatsby/src/utils/flags.ts
Labels: type: feature or enhancement

#28401 feat(create-gatsby): Prompt for site name
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/init-starter.ts
  packages/create-gatsby/src/utils.ts
Labels: topic: cli

#28449 fix(gatsby-plugin-sharp): decode URL so it matches the cache key
  packages/gatsby-plugin-sharp/src/gatsby-node.js
Labels: bot: merge on green, topic: sharp

#28464 fix: Back out resolutions, and add ignore-engines to dev cli
  package.json
  packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
  scripts/e2e-test.sh
  yarn.lock
Labels: bot: merge on green, topic: dev tooling

#28458 chore(gatsby-starter-minimal): Add `serve` script
  starters/gatsby-starter-minimal/package.json
Labels: topic: starters

#28456 fix(gatsby): Add bodyComponent to replaceRenderer args
  packages/gatsby/cache-dir/api-ssr-docs.js
  packages/gatsby/index.d.ts
Labels: bot: merge on green

#28457 feat(gatsby-plugin-manifest): Add support for share_target
  packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Labels: bot: merge on green, topic: PWA

#28465 chore: fix publish script
  package.json
Labels: bot: merge on green

#28407 fix(gatsby-plugin-image): don't show hydration warning
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
Labels: bot: merge on green, topic: images/media

#28472 chore(gatsby): use gatsby.dev links in flags.ts
  packages/gatsby/src/utils/flags.ts
Labels: type: chore

#28481 Backport #28459 and #28464 to 2.28 release branch
  packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
  scripts/e2e-test.sh
  yarn.lock
Labels: type: cherry

#28484 fix(create-gatsby): Remove race condition/duplicate render
  packages/create-gatsby/src/components/select.js
Labels: topic: cli

#28112 gatsby-image codemod
  integration-tests/jest.config.js
  jest.config.js
  packages/gatsby-codemods/.gitignore
  packages/gatsby-codemods/package.json
  packages/gatsby-codemods/src/bin/__tests__/gatsby-codemods-test.js
  packages/gatsby-codemods/src/bin/cli.js
  packages/gatsby-codemods/src/bin/gatsby-codemods.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/baseline.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/baseline.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/call-expression.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/call-expression.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/compat.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/compat.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/extends-warn.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/extends-warn.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/ignore.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/ignore.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/mansion.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/mansion.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/multiple.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/multiple.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/no-change.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/no-change.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/no-query-change.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/no-query-change.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/non-component.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/non-component.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/not-data.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/not-data.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/not-object.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/not-object.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/optional-chaining.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/optional-chaining.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/placeholders.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/placeholders.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/stunted-ref.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/stunted-ref.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/styled.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/styled.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/transform-error.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/transform-error.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/typescript.input.tsx
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/typescript.output.tsx
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/uses-src.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/uses-src.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/variable.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/variable.output.js
  packages/gatsby-codemods/src/transforms/__tests__/gatsby-plugin-image-test.js
  packages/gatsby-codemods/src/transforms/gatsby-plugin-image.js
  packages/gatsby-plugin-image/README.md
Labels: topic: images/media

#28463 feat(gatsby-plugin-image): Add helper function to grab src
  packages/gatsby-plugin-image/README.md
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/index.browser.ts
  packages/gatsby-plugin-image/src/index.ts
Labels: topic: images/media

#28490 fix: Push dirty yarn.lock
  yarn.lock
Labels: status: triage needed

#28492 fix(gatsby-codemods): Missing dependency
  packages/gatsby-codemods/package.json
  yarn.lock
Labels: topic: dev tooling

#28493 fix(gatsby-codemods): Need as dependencies and not devDependencies
  packages/gatsby-codemods/package.json
  packages/gatsby-codemods/src/transforms/gatsby-plugin-image.js
  yarn.lock
Labels: topic: dev tooling

#28480 fix(create-gatsby): Fix kebabcase edge cases and tests
  packages/create-gatsby/src/__tests__/init-starter.ts
  packages/create-gatsby/src/__tests__/utils.ts
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/init-starter.ts
  packages/create-gatsby/src/utils.ts
Labels: topic: cli, type: bug

#28494 fix(gatsby): do not fail in develop when eslint loader is removed
  packages/gatsby/src/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.ts
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: webpack/babel

#28460 feat(gatsby): add preload headers for critical resources so those can started fetching before common.js is fetched
  packages/gatsby/src/utils/dev-ssr/develop-html-route.ts
  packages/gatsby/src/utils/develop-preload-headers.ts
  packages/gatsby/src/utils/start-server.ts
Labels: topic: resource loading*

#28519 fix: Update docs for codemod
  packages/gatsby-codemods/README.md
  packages/gatsby-plugin-image/README.md
Labels: topic: dev tooling

#28485 feat(gatsby-plugin-page-creator): Add slugify option
  packages/gatsby-page-utils/package.json
  packages/gatsby-page-utils/src/ignore-path.ts
  packages/gatsby-page-utils/src/index.ts
  packages/gatsby-plugin-page-creator/README.md
  packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
  packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/derive-path.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
Labels: topic: page creation

#28530 fix(gatsby): better text for missing inferred extension
  packages/gatsby/src/schema/infer/__tests__/infer.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/print.js
Labels: bot: merge on green, topic: GraphQL

#27931 feat(gatsby): Expose plugin-specific refresh endpoint in gatsby-serve
  e2e-tests/development-runtime/cypress/integration/gatsby-preview/base-functionality.js
  e2e-tests/development-runtime/cypress/integration/gatsby-preview/refreshing.js
  e2e-tests/development-runtime/cypress/integration/gatsby-preview/updating.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/.gitignore
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/api.js
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/db.json
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/gatsby-node.js
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/index.js
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/package.json
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/reset.js
  e2e-tests/development-runtime/scripts/cms-webhook.js
  e2e-tests/development-runtime/src/pages/preview.js
  packages/gatsby/src/services/source-nodes.ts
  packages/gatsby/src/services/types.ts
  packages/gatsby/src/state-machines/data-layer/types.ts
  packages/gatsby/src/state-machines/develop/actions.ts
  packages/gatsby/src/state-machines/develop/index.ts
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/source-nodes.ts
  packages/gatsby/src/utils/start-server.ts
Labels: topic: internal, topic: plugins

#28532 fix(gatsby): improve deprecation text for missing childOf directive
  packages/gatsby/src/schema/extensions/__tests__/child-relations.js
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green, topic: GraphQL

#28468 feat(create-gatsby): Add -y flag
  packages/create-gatsby/README.md
  packages/create-gatsby/src/index.ts
Labels: topic: cli

#28534 fix(gatsby): Wait for jobs to complete in onPostBuild
  packages/gatsby/src/commands/build.ts
Labels: bot: merge on green

#28450 fix(gatsby): show multiple invites together & at end where people are more likely to see them
  packages/gatsby/package.json
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/services/run-page-queries.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/show-experiment-notice.js.snap
  packages/gatsby/src/utils/__tests__/show-experiment-notice.js
  packages/gatsby/src/utils/show-experiment-notice.ts
  packages/gatsby/src/utils/start-server.ts
Labels: bot: merge on green, topic: cli

#28538 chore(query-on-demand): prerun query for homepage for initial run
  packages/gatsby/src/commands/develop-process.ts
Labels: topic: query on demand*

#28242 fix(gatsby-remark-images): allow tracedSVG to accept object with settings
  packages/gatsby-remark-images/src/__tests__/gatsby-node.js
  packages/gatsby-remark-images/src/gatsby-node.js
Labels: topic: images/media, type: bug

#27365 fix(documentationjs): fix example caption string
  packages/gatsby-transformer-documentationjs/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-documentationjs/src/__tests__/fixtures/code.js
  packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-documentationjs/src/gatsby-node.js
Labels: status: needs core review, topic: transformers

#28525 perf(gatsby): do not force resolvers to be async
  packages/gatsby/src/schema/resolvers.ts
Labels: topic: performance, topic: scaling builds

#28535 fix(query-on-demand): don't resolve get-page-data if query is marked as dirty
  packages/gatsby/src/redux/reducers/__tests__/queries.ts
  packages/gatsby/src/redux/reducers/queries.ts
  packages/gatsby/src/utils/__tests__/get-page-data.ts
  packages/gatsby/src/utils/get-page-data.ts
  packages/gatsby/src/utils/page-data.ts
Labels: topic: query on demand*

#28554 fix(gatsby): Avoid undefined object errors
  packages/babel-plugin-remove-graphql-queries/src/index.ts
  packages/gatsby/src/query/file-parser.js
Labels: type: bug

#28540 fix (create-gatsby): Ignore confirmation prompt
  packages/create-gatsby/src/index.ts
Labels: topic: dev tooling

#27730 fix: improve error handling, always show API response status and message
  packages/gatsby-source-contentful/src/__tests__/fetch.js
  packages/gatsby-source-contentful/src/fetch.js
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: topic: Contentful

#28555 fix(gatsby-react-router-scroll): Respect hash as source of truth for scroll position
  e2e-tests/production-runtime/cypress/integration/scroll-behavior.js
  packages/gatsby-react-router-scroll/src/scroll-handler.tsx
Labels: topic: reach/router and Links

#28563 fix(gatsby): correct GraphQL warning text
  packages/gatsby/src/schema/extensions/__tests__/child-relations.js
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green, topic: GraphQL

#28566 chore(create-gatsby): reorder style options by popularity and change postcss title
  packages/create-gatsby/src/styles.json
Labels: status: triage needed, topic: cli

#28568 Update gatsby-source-wordpress-experimental and fix queries to work with update
  benchmarks/source-wordpress/package.json
  benchmarks/source-wordpress/src/templates/article.js
Labels: bot: merge on green

#28569 chore(develop): don't actually fetch async dummy.js chunk
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/dummy.js
Labels: topic: webpack/babel

#27016 Update kintohub documentation with kintohub V1 deployment
  docs/docs/deploying-to-kintohub.md
Labels: status: awaiting author response, type: documentation

#28544 feat(gatsby): track how long query-on-demand querying takes
  packages/gatsby/src/utils/start-server.ts
Labels: topic: query on demand*

#28573 chore(gatsby-source-contentful): fix output of debug message
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: bot: merge on green, topic: Contentful, type: chore

#28520 feat(gatsby-plugin-image): Add extra props to GatsbyImage
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
Labels: topic: images/media

#28553 chore(gatsyb-source-contentful): move locale filter
  packages/gatsby-source-contentful/src/__tests__/fetch.js
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/fetch.js
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: bot: merge on green, topic: Contentful, type: chore

#28574 feat(gatsby-plugin-sharp): run a single transformation for lazy images
  packages/gatsby-plugin-sharp/src/gatsby-node.js
Labels: topic: sharp

#28562 feat(query-on-demand): loading indicator
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/debug-log.js
  packages/gatsby/cache-dir/loading-indicator/index.js
  packages/gatsby/cache-dir/loading-indicator/indicator.js
  packages/gatsby/cache-dir/loading-indicator/portal.js
  packages/gatsby/cache-dir/loading-indicator/style.js
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/cache-dir/root.js
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/loading-indicator.ts
  packages/gatsby/src/utils/start-server.ts
Labels: topic: query on demand*

#28576 fix(gatsby-plugin-sharp): fix image url decoding for lazy images
  packages/gatsby-plugin-sharp/src/gatsby-node.js
Labels: topic: sharp

#28387 feature(gatsby): Enable partial releases of flags to a % of users
  examples/using-drupal/gatsby-config.js
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap
  packages/gatsby/src/utils/__tests__/handle-flags.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/handle-flags.ts
  packages/gatsby/src/utils/sample-site-for-experiment.ts
Labels: type: feature or enhancement

#28577 feat(gatsby-plugin-image): add keywords to package.json so it shows up in the plugin search
  packages/gatsby-plugin-image/package.json
Labels: bot: merge on green, topic: images/media

#28579 fix(gatsby): correct opt-in percentage for QUERY_ON_DEMAND and LAZY_IMAGES
  packages/gatsby/src/utils/flags.ts
Labels: topic: query on demand*

#28582 chore(gatsby-source-contentful): fix locale debug output, again
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: bot: merge on green, topic: Contentful

#28580 chore(e2e-development): bump cypress version
  e2e-tests/development-runtime/cypress.json
  e2e-tests/development-runtime/cypress/integration/functionality/data-update.js
  e2e-tests/development-runtime/cypress/integration/functionality/query-data-caches.js
  e2e-tests/development-runtime/cypress/integration/gatsby-preview/refreshing.js
  e2e-tests/development-runtime/cypress/integration/gatsby-preview/updating.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/page-queries.js
  e2e-tests/development-runtime/cypress/integration/navigation/linking.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/api.js
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/gatsby-node.js
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/api.js
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/gatsby-node.js
  e2e-tests/development-runtime/scripts/update.js
Labels: type: maintenance

#28607 fix(create-gatsby): Default to gatsby-image until the plugin is GA
  packages/create-gatsby/src/features.json
Labels: bot: merge on green, topic: cli, topic: images/media

#28529 chore(plugin-netlify-cms): update Slack link
  packages/gatsby-plugin-netlify-cms/README.md
Labels: type: documentation

#28611 Fix broken import statement
  benchmarks/source-wordpress/scripts/updater.js
Labels: bot: merge on green, status: triage needed

#28612 Fixed typo brackets in file-system-route-api.md
  docs/docs/file-system-route-api.md
Labels: type: documentation

#28620 fix(gatsby-plugin-sharp): Include default transform options for webp
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on iphone-6.snap.png
  packages/gatsby-plugin-sharp/src/image-data.ts
Labels: bot: merge on green, topic: images/media

#28606 fix(gatsby-plugin-image): Better propType handling for StaticImage
  e2e-tests/gatsby-static-image/src/pages/fluid.js
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/__tests__/babel-utils.ts
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
Labels: topic: images/media

#26190 chore: update ink to v3
  integration-tests/gatsby-cli/test-helpers/invoke-cli.js
  integration-tests/gatsby-cli/test-helpers/matcher.js
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/develop.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/error.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/messages.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/progress-bar.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/spinner.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/utils.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/context.tsx
  packages/gatsby-cli/src/reporter/start-logger.ts
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/cli/index.js
  yarn.lock
Labels: status: needs core review, topic: reporter

#28622 fix(gatsby): correct opt-in percentage for QUERY_ON_DEMAND and LAZY_IMAGES (#28579)
  packages/gatsby/src/utils/flags.ts
Labels: type: cherry

#28618 fix(gatsby-plugin-image): Correctly handle formats in StaticImage
  e2e-tests/gatsby-static-image/src/pages/lazy-loading.js
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-sharp/src/image-data.ts
Labels: topic: images/media

#28614 fix(gatsby-plugin-sharp): catch errors when writing base64 images
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/report-error.js
Labels: topic: sharp

#28623 chore(gatsby-source-contentful): fix locale debug output, again (#28582)
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: type: cherry

#28628 fix(gatsby-plugin-image): Better propType handling for StaticImage (#28606)
  e2e-tests/gatsby-static-image/src/pages/fluid.js
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/__tests__/babel-utils.ts
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
Labels: type: cherry

#28629 fix(gatsby-plugin-sharp): Include default transform options for webp (#28620)
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on iphone-6.snap.png
  packages/gatsby-plugin-sharp/src/image-data.ts
Labels: type: cherry

#28630 fix(gatsby-plugin-image): Correctly handle formats in StaticImage (#28618)
  e2e-tests/gatsby-static-image/src/pages/lazy-loading.js
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-sharp/src/image-data.ts
Labels: type: cherry

#28631 chore: update ink to v3 (#26190)
  integration-tests/gatsby-cli/test-helpers/invoke-cli.js
  integration-tests/gatsby-cli/test-helpers/matcher.js
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/develop.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/error.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/messages.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/progress-bar.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/spinner.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/utils.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/context.tsx
  packages/gatsby-cli/src/reporter/start-logger.ts
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/cli/index.js
  yarn.lock
Labels: type: cherry

#28633 fix(create-gatsby): Default to gatsby-image until the plugin is GA (#28607)
  packages/create-gatsby/src/features.json
Labels: type: cherry

#28634 fix(gatsby): Only set auto optin flags if not in config (#28627)
  packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap
  packages/gatsby/src/utils/__tests__/handle-flags.ts
  packages/gatsby/src/utils/handle-flags.ts
Labels: type: cherry

#28621 feat(gatsby): improve refresh endpoint output
  packages/gatsby/src/utils/start-server.ts
Labels: status: awaiting reviewer response, topic: data sourcing

#28639 chore: Add contributors to 2.26/2.27/2.28 release notes
  docs/reference/release-notes/v2.26/index.md
  docs/reference/release-notes/v2.27/index.md
  docs/reference/release-notes/v2.28/index.md
Labels: type: documentation

#28641 feat(gatsby): improve refresh endpoint output (#28621)
  packages/gatsby/src/utils/start-server.ts
Labels: type: cherry

#28635 fix(create-gatsby): Adds a default icon so plugin-manifest works out of the box
  packages/create-gatsby/src/__tests__/install-plugins.ts
  packages/create-gatsby/src/features.json
  packages/create-gatsby/src/install-plugins.ts
  starters/gatsby-starter-minimal/src/images/icon.png
Labels: status: triage needed

#28605 docs: release notes for 2.29
  docs/reference/release-notes/v2.29/index.md
Labels: type: documentation

#28636 feat(gatsby-starter-minimal): Add 404 to minimal starter
  starters/gatsby-starter-minimal/src/pages/404.js
  starters/gatsby-starter-minimal/src/pages/index.js
Labels: topic: starters

#28638 feat(gatsby): Add AVIF file support to image loader in webpack config
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: webpack/babel

#28572 fix(gatsby): require gatsby-config.js before accessing process.env
  packages/gatsby/src/commands/develop.ts
Labels: topic: cli

#28655 fix(create-gatsby): Switch dependency to sass
  packages/create-gatsby/src/styles.json
Labels: bot: merge on green, topic: cli

#28652 fix(gatsby-plugin-page-creator): add missing telemetry dependency
  packages/gatsby-plugin-page-creator/package.json
Labels: bot: merge on green, topic: telemetry*

#28651 fix(docs): dead links sourcing-data -> querying-data
  docs/docs/add-seo-component.md
  docs/docs/conceptual/building-with-components.md
  docs/docs/conceptual/graphql-concepts.md
  docs/docs/data-fetching.md
  docs/docs/data-storage-redux.md
  docs/docs/glossary/static-site-generator.md
  docs/docs/how-to/plugins-and-themes/theme-conventions.md
  docs/docs/how-to/querying-data/static-query.md
  docs/docs/how-to/querying-data/use-static-query.md
  docs/docs/how-to/sourcing-data/sourcing-from-private-apis.md
  docs/docs/porting-from-create-react-app-to-gatsby.md
  docs/docs/programmatically-create-pages-from-data.md
  docs/docs/recipes/pages-layouts.md
  docs/docs/recipes/querying-data.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/reference/built-in-components/gatsby-image.md
  docs/docs/reference/graphql-data-layer/graphql-api.md
  docs/docs/reference/release-notes/migrating-from-v1-to-v2.md
  docs/docs/sourcing-from-graphcms.md
  docs/docs/static-vs-normal-queries.md
  docs/docs/tutorial/part-four/index.md
Labels: status: triage needed

#28644 fix (creat-gatsby): Remove license information
  packages/create-gatsby/src/init-starter.ts
Labels: topic: cli

#28658 fix(gatsby-plugin-page-creator): add missing telemetry dependency (#28652)
  packages/gatsby-plugin-page-creator/package.json
Labels: type: cherry

#28661 fix(create-gatsby): Adds a default icon so plugin-manifest works out of the box (#28635)
  packages/create-gatsby/src/__tests__/install-plugins.ts
  packages/create-gatsby/src/features.json
  packages/create-gatsby/src/install-plugins.ts
  starters/gatsby-starter-minimal/src/images/icon.png
Labels: type: cherry

#28659 fix(gatsby-plugin-sharp): catch errors when writing base64 images (#28614)
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/report-error.js
Labels: type: cherry

#28660 (gatsby-minimal-starter): Update docs links and style to match relaunch
  starters/gatsby-starter-minimal/src/pages/index.js
Labels: topic: starters

#28648 feat(gatsby): decouple html activities
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/start-server.ts
Labels: topic: SSG*, type: maintenance

#28662 feat(gatsby-plugin-image): Make dimensions optional and default to constrained
  e2e-tests/gatsby-static-image/src/pages/constrained.js
  e2e-tests/gatsby-static-image/src/pages/fixed.js
  e2e-tests/path-prefix/src/pages/index.js
  e2e-tests/production-runtime/src/components/header.js
  e2e-tests/visual-regression/src/pages/static-images/constrained.js
  e2e-tests/visual-regression/src/pages/static-images/fixed.js
  packages/gatsby-plugin-image/README.md
  packages/gatsby-plugin-image/src/__tests__/image-utils.ts
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: topic: images/media

#28665 docs: fix spelling
  docs/docs/reference/release-notes/v2.27/index.md
  docs/docs/reference/release-notes/v2.29/index.md
Labels: type: documentation

#28666 Partially revert "BREAKING(gatsby-plugin-sass): sass-loader to v10 & …"
  docs/docs/how-to/styling/bulma.md
  docs/docs/how-to/styling/sass.md
  docs/docs/how-to/styling/tailwind-css.md
  docs/docs/recipes/styling-css.md
Labels: type: documentation

#28669 perf(gatsby-plugin-image): Handle disabled js, and add preload link
  packages/gatsby-plugin-image/src/components/main-image.tsx
  packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Labels: bot: merge on green, topic: images/media

#28436 chore(gatsby): refactor try/finally to .finally
  packages/gatsby/src/query/query-runner.ts
Labels: bot: merge on green, type: chore

#28643 fix(gatsby): Do not activate inspect if already active
  packages/gatsby/src/commands/develop-process.ts
Labels: type: feature or enhancement

#28670 fix (gatsby-minimal-starter): Make minimal gitignore
  starters/gatsby-starter-minimal/.gitignore
Labels: topic: starters

#28672 fix(deps): Revert postcss upgrade which broke css macro
  packages/gatsby-plugin-image/package.json
Labels: status: triage needed

#28676 fix(gatsby): remove redundant dispatch of query extraction error
  e2e-tests/mdx/gatsby-config.js
  e2e-tests/mdx/plugins/gatsby-plugin-test-regression1/gatsby-node.js
  e2e-tests/mdx/plugins/gatsby-plugin-test-regression1/package.json
  e2e-tests/mdx/src/pages/regressions/index.mdx
  packages/gatsby/src/query/file-parser.js
Labels: bot: merge on green, topic: StaticQuery

#28656 fix(gatsby): always add both `childField` and `childrenField` in GraphQL
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/kitchen-sink.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-node-connections.js
  packages/gatsby/src/schema/__tests__/build-node-types.js
  packages/gatsby/src/schema/__tests__/kitchen-sink.js
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/__tests__/rebuild-schema.js
  packages/gatsby/src/schema/extensions/__tests__/child-relations.js
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green, topic: GraphQL

#28678 fix(gatsby-plugin-image): do not return from preprocessSource if nothing is changed
  packages/gatsby-plugin-image/src/node-apis/preprocess-source.ts
Labels: bot: merge on green

#28647 feat(gatsby-plugin-image): Add remote image support
  packages/gatsby-plugin-image/src/node-apis/image-processing.ts
  packages/gatsby-plugin-image/src/node-apis/preprocess-source.ts
Labels: topic: images/media

#28685 chore(docs): Fix links to release notes
  docs/docs/reference/release-notes/v2.27/index.md
  docs/docs/reference/release-notes/v2.28/index.md
  docs/docs/reference/release-notes/v2.29/index.md
Labels: bot: merge on green, type: documentation

#28683 fix(gatsby-plugin-sass): Nest sassOptions
  packages/gatsby-plugin-sass/README.md
  packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: topic: sass

#28694 fix(gatsby-stater-minimal): 404 Page should not also be IndexPage
  starters/gatsby-starter-minimal/src/pages/404.js
Labels: status: triage needed

#28701 fix(gatsby): use correct stageLabel instead of `undefined`
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-error-utils.ts.snap
  packages/gatsby/src/utils/__tests__/webpack-error-utils.ts
  packages/gatsby/src/utils/webpack-error-utils.ts
Labels: topic: reporter, topic: webpack/babel

#28703 test(cache-resilience): update snapshots
  integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-added/scenario.js
  integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-changed/scenario.js
  integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/source-removed/scenario.js
  integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-added/scenario.js
  integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-changed/scenario.js
  integration-tests/cache-resilience/plugins/source-and-transformers-child-nodes/transformer-removed/scenario.js
Labels: topic: GraphQL

#28725 chore(dev-ssr): don't dispatch CREATE_SERVER_VISITED_PAGE if component is already tracked
  packages/gatsby/src/redux/actions/public.js
Labels: topic: ssr

#28394 feature(gatsby): Pause dev-ssr watching between page loads to avoid slowing down regular develop-js HMR
  integration-tests/ssr/__tests__/ssr.js
  integration-tests/ssr/test-output.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
Labels: type: feature or enhancement

#28690 fix(gatsby-plugin-image): Preload lazy-hydrator
  packages/gatsby-plugin-image/gatsby-browser.js
  packages/gatsby-plugin-image/src/components/later-hydrator.tsx
  packages/gatsby-plugin-image/src/index.browser.ts
Labels: bot: merge on green, topic: images/media

#28642 perf(gatsby-source-contentful): dont re-create nodes
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-contentful/src/normalize.js
Labels: bot: merge on green, topic: Contentful, topic: performance, topic: scaling builds

#28686 chore(gatsby-source-graphql): docs on how to use apollo links
  packages/gatsby-source-graphql/README.md
Labels: bot: merge on green, type: documentation

#28734 chore(telemetry): add valueBoolean
  packages/gatsby-telemetry/src/telemetry.ts
Labels: topic: telemetry*

#28732 chore(telemetry) improve github action and circle detection
  packages/gatsby-core-utils/src/__tests__/ci.ts
  packages/gatsby-core-utils/src/ci.ts
Labels: topic: telemetry*

#28483 fix(gatsby): print childOf directive for implicit child fields
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/print.js
  packages/gatsby/src/schema/extensions/__tests__/child-relations.js
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green, topic: GraphQL

#28742 feat: Add AVIF image support to beta image plugin
  .circleci/config.yml
  e2e-tests/visual-regression/cypress/integration/image.js
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- avif format -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- avif format -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- avif format -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- avif format -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- avif format -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- avif format -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/src/pages/images/avif.js
  e2e-tests/visual-regression/src/pages/static-images/avif.js
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-plugin-manifest/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby-transformer-sharp/src/types.ts
  yarn.lock
Labels: topic: images/media
