Repository gatsbyjs/gatsby, pull requests merged in 2020-11, with the labels that each got.

#27736 feat(gatsby): more `gatsby plugin configure` additions
  packages/gatsby/src/commands/plugin/configure.ts
Labels: status: triage needed

#27708 fix(gatsby): show theme that has faulty config
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/index.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: topic: cli

#27748 chore(docs): Updated Snipcart blog entry
  docs/docs/adding-a-shopping-cart-with-snipcart.md
Labels: type: documentation

#27659 fix(gatsby-remark-prismjs): Handle diff-language styling issue
  packages/gatsby-remark-prismjs/src/__tests__/__snapshots__/highlight-code.js.snap
  packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js
  packages/gatsby-remark-prismjs/src/highlight-code.js
Labels: topic: Markdown/remark

#27437 feat(gatsby): release plugin option validation
  .jestSetup.js
  packages/gatsby-admin/gatsby-config.js
  packages/gatsby-plugin-feed/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-feed/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-feed/src/gatsby-node.js
  packages/gatsby-plugin-google-analytics/src/gatsby-node.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  packages/gatsby-plugin-mdx/gatsby-node.js
  packages/gatsby-plugin-netlify/src/gatsby-node.js
  packages/gatsby-plugin-offline/src/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
  packages/gatsby-plugin-typescript/src/gatsby-node.js
  packages/gatsby-remark-autolink-headers/gatsby-node.js
  packages/gatsby-remark-autolink-headers/src/gatsby-node.js
  packages/gatsby-remark-images/src/gatsby-node.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-filesystem/src/gatsby-node.js
  packages/gatsby-transformer-remark/src/gatsby-node.js
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/src/bootstrap/load-plugins/index.ts
  packages/gatsby/src/utils/api-node-docs.ts
Labels: hacktoberfest-accepted, type: documentation

#27541 docs(plugins): more in-depth pluginOptionsSchema documentation
  docs/docs/configuring-usage-with-plugin-options.md
Labels: topic: plugins

#27780 chore(telemetry) Add isTTY
  packages/gatsby-telemetry/src/telemetry.ts
Labels: bot: merge on green, topic: telemetry*

#27718 fix(gatsby-recipes): Only remove the ".mdx" ending if running local recipe
  packages/gatsby-recipes/src/cli/index.js
Labels: topic: recipes

#27785 fix(gatsby-transformer-remark): add excerpt_separator to plugin options schema
  packages/gatsby-transformer-remark/src/gatsby-node.js
Labels: bot: merge on green, topic: Markdown/remark

#27793 fix(gatsby-plugin-manifest): create directories recursively
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
Labels: bot: merge on green, status: confirmed, type: bug

#27786 fix(gatsby-plugin-sass): add missing options
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: bot: merge on green, topic: sass

#27797 fix(gatsby-source-contentful): default function returned invalid value
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: bot: merge on green, topic: Contentful

#27800 Use NetworkFirst with networkTimeoutSeconds option configured
  packages/gatsby-plugin-offline/src/gatsby-node.js
Labels: bot: merge on green, topic: PWA

#27801 feat(create-gatsby): add wip plugin configuration forms
  packages/create-gatsby/package.json
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/plugin-schemas.json
Labels: topic: cli

#27757 feat(gatsby-telemetry): Track terminal program
  packages/gatsby-core-utils/src/get-term-program.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-telemetry/src/telemetry.ts
Labels: bot: merge on green, topic: telemetry*

#27753 chore(deps): update chalk
  package.json
  packages/gatsby-cli/package.json
  packages/gatsby-plugin-preload-fonts/package.json
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-remark-images/package.json
  packages/gatsby-source-shopify/package.json
  packages/gatsby/package.json
Labels: type: maintenance

#27752 chore(deps): update lint-staged
  package.json
  yarn.lock
Labels: type: maintenance

#27738 Update add-custom-webpack-config.md
  docs/docs/add-custom-webpack-config.md
Labels: type: documentation

#27624 Update adding-analytics.md
  docs/docs/adding-analytics.md
Labels: hacktoberfest-accepted, type: documentation

#27791 chore(gatsby-recipes): upgrade graphql-tools to v7
  packages/gatsby-recipes/package.json
Labels: status: needs core review, topic: GraphQL, topic: recipes

#27099 chore(deps): update p-queue
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-mdx/utils/render-html.js
  packages/gatsby-transformer-sqip/package.json
  packages/gatsby-transformer-sqip/src/generate-sqip.js
  yarn.lock
Labels: topic: automation

#27810 fix(gatsby): feedback test did not reset 7day check
  packages/gatsby/src/utils/__tests__/feedback.ts
  packages/gatsby/src/utils/feedback.ts
Labels: bot: merge on green, topic: analytics plugins, topic: dev tooling, type: bug

#27811 chore: update lerna config for the new release process
  lerna.json
Labels: bot: merge on green

#27817 chore: update yarn.lock
  yarn.lock
Labels: bot: merge on green, topic: npm*

#27821 fix(gatsby-remark-autolink-headers): remove incorrect default value for icon option
  packages/gatsby-remark-autolink-headers/src/gatsby-node.js
Labels: topic: Markdown/remark

#27814 fix(docs): Update gatsby-plugin-guess-js README
  packages/gatsby-plugin-guess-js/README.md
Labels: topic: guess-js

#27812 fix(recipe): add brackets to directory names
  packages/gatsby-recipes/recipes/gatsby-image.mdx
Labels: topic: recipes

#27819 chore: update yarn.lock
  yarn.lock
Labels: bot: merge on green

#27822 fix(gatsby-plugin-sass): fix default output style & allow unknown options
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: topic: sass

#27600 chore(gatsby-plugin-cxs): Add pluginOptionsSchema validation
  packages/gatsby-plugin-cxs/package.json
  packages/gatsby-plugin-cxs/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-cxs/src/gatsby-node.js
Labels: bot: merge on green, topic: plugins

#27824 File System Route API: Remove `collectionGraphql` API
  docs/docs/file-system-route-api.md
  e2e-tests/development-runtime/cypress/integration/unified-routing/collection-routing.js
  e2e-tests/development-runtime/src/pages/collection-routing/{ImageSharp.parent__(File)__name}.js
  e2e-tests/production-runtime/src/pages/collection-routing/{Product.name}.js
  examples/route-api/src/pages/index.js
  examples/route-api/src/pages/parks/{park.name}.js
  packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/babel-remove-collection-graphql.ts
  packages/gatsby-plugin-page-creator/src/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby/cache-dir/gatsby-browser-entry.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
Labels: topic: page creation

#27830 fix(gatsby-remark-autolink-headers): remove incorrect default value for icon option
  packages/gatsby-remark-autolink-headers/src/gatsby-node.js
Labels: type: cherry

#27837 chore(gatsby-plugin-cxs): Fix dependency version
  packages/gatsby-plugin-cxs/package.json
Labels: bot: merge on green

#27831 fix(gatsby-plugin-sass): fix default output style & allow unknown options
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: type: cherry

#27735 fix(docs): Update documentation for createPages
  packages/gatsby/src/utils/api-node-docs.ts
Labels: type: documentation

#27851 fix(gatsby): Remove version annotation in createPages
  packages/gatsby/src/utils/api-node-docs.ts
Labels: bot: merge on green

#27790 fix(gatsby-recipes): fix GatsbyShadowFile resource — don't error if package isn't installed
  packages/gatsby-recipes/rollup.config.js
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/shadow-file.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/shadow-file.js
Labels: topic: recipes

#27835 feat(gatsby-telemetry): adjust how we capture plugins for telemetry
  packages/gatsby-telemetry/src/__tests__/telemetry.ts
  packages/gatsby-telemetry/src/get-dependencies.ts
  packages/gatsby-telemetry/src/index.ts
  packages/gatsby-telemetry/src/telemetry.ts
Labels: bot: merge on green, topic: telemetry*

#27858 chore(gatsby-remark-autolink-headers): gitignore gatsby-node compiled by babel
  packages/gatsby-remark-autolink-headers/.gitignore
  packages/gatsby-remark-autolink-headers/gatsby-node.js
Labels: bot: merge on green, type: chore

#27866 fix(gatsby-plugin-sitemap): fixed missing sitemapSize config entry
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
Labels: bot: merge on green, topic: sitemap

#27868 chore(gatsby): log out when experimental concurrency flag is used
  packages/gatsby/src/query/queue.ts
Labels: bot: merge on green, type: chore

#27849 fix(gatsby-source-filesystem): allow regex and functions for ignore option
  packages/gatsby-source-filesystem/src/gatsby-node.js
Labels: bot: merge on green, topic: plugins

#27850 File System Route API: Support `/{Model.foo}-{Model.bar}`
  packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
  packages/gatsby-plugin-page-creator/src/__tests__/extract-query.ts
  packages/gatsby-plugin-page-creator/src/__tests__/get-collection-route-params.ts
  packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/__tests__/validate-path-query.ts
  packages/gatsby-plugin-page-creator/src/derive-path.ts
  packages/gatsby-plugin-page-creator/src/extract-query.ts
  packages/gatsby-plugin-page-creator/src/get-collection-route-params.ts
  packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/path-utils.ts
Labels: topic: page creation

#27853 chore(gatsby): async refactor in graphql-runner
  packages/gatsby/src/query/graphql-runner.ts
Labels: bot: merge on green, type: chore

#27869 chore(gatsby): small refactor in cache
  packages/gatsby/src/utils/cache.ts
Labels: type: chore

#27854 chore(gatsby): refactor of query-runner.ts
  packages/gatsby/src/query/query-runner.ts
Labels: bot: merge on green, type: chore

#27435 feat(gatsby-cli): Augment plugin errors with plugin name
  packages/gatsby-cli/src/reporter/redux/internal-actions.ts
  packages/gatsby-cli/src/reporter/redux/types.ts
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-cli/src/structured-errors/error-schema.ts
  packages/gatsby/src/utils/api-runner-node.js
Labels: bot: merge on green, topic: cli

#27782 refactor(websocket-manager): handle more variations of page paths
  packages/gatsby/src/utils/__tests__/find-page-by-path.ts
  packages/gatsby/src/utils/__tests__/websocket-manager.ts
  packages/gatsby/src/utils/find-page-by-path.ts
  packages/gatsby/src/utils/normalize-page-path.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/websocket-manager.ts
Labels: topic: resource loading*

#27876 fix(gatsby-plugin-sitemap): fixed missing sitemapSize config entry (#27866)
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
Labels: type: cherry

#27877 fix(gatsby-source-filesystem): allow regex and functions for ignore option (#27849)
  packages/gatsby-source-filesystem/src/gatsby-node.js
Labels: type: cherry

#27836 fix(recipes): Resolve themes relative to root
  packages/gatsby-recipes/package.json
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
Labels: bot: merge on green, topic: recipes

#27457 Add error codes to reporter.panic in Contentful source plugin
  packages/gatsby-source-contentful/src/__tests__/fetch.js
  packages/gatsby-source-contentful/src/fetch.js
  packages/gatsby-source-contentful/src/report.js
Labels: topic: Contentful

#27663 feat(gatsby-source-filesystem): env flag to placeholder remote assets
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
Labels: topic: dev tooling

#27886 fix(gatsby-plugin-google-tagmanager): allow functions for defaultDataLayer option
  packages/gatsby-plugin-google-tagmanager/package.json
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-node.js
Labels: bot: merge on green, topic: analytics plugins

#25249 Refactor Rich Text implementation in gatsby-source-contentful
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/index.d.ts
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/rich-text.d.ts
  packages/gatsby-source-contentful/scripts/generate-fetch-fixtures.js
  packages/gatsby-source-contentful/src/__fixtures__/rich-text-data.js
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/rich-text.js.snap
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/__tests__/rich-text.js
  packages/gatsby-source-contentful/src/extend-node-type.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/rich-text.js
  yarn.lock
Labels: effort: high, impact: high, status: needs core review, topic: Contentful

#27912 fix(gatsby-remark-images): allow strings for the wrapperStyle option
  packages/gatsby-remark-images/src/__tests__/gatsby-node.js
  packages/gatsby-remark-images/src/gatsby-node.js
Labels: hotfix, topic: Markdown/remark

#27101 fix(renovate): move express-graphql and react-reconciler from minor to major update groups
  renovate.json5
Labels: topic: automation

#27916 fix(gatsby-plugin-google-tagmanager): allow functions for defaultDataLayer option (#27886)
  packages/gatsby-plugin-google-tagmanager/package.json
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-node.js
Labels: type: cherry

#27914 fix(gatsby-plugin-google-analytics): add optional options to options schema
  packages/gatsby-plugin-google-analytics/src/gatsby-node.js
Labels: bot: merge on green, hotfix, topic: analytics plugins

#27883 chore(docs): Add required `path` import to modifying-pages doc
  docs/docs/creating-and-modifying-pages.md
Labels: type: documentation

#27920 fix(gatsby-plugin-google-analytics): add optional options to options schema (#27914)
  packages/gatsby-plugin-google-analytics/src/gatsby-node.js
Labels: type: cherry

#27919 fix(gatsby-remark-images): allow strings for the wrapperStyle option (#27912)
  packages/gatsby-remark-images/src/__tests__/gatsby-node.js
  packages/gatsby-remark-images/src/gatsby-node.js
Labels: type: cherry

#27913 fix(gatsby-plugin-offline): add workboxConfig.maximumFileSizeToCacheInBytes to options schema
  packages/gatsby-plugin-offline/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-offline/src/gatsby-node.js
Labels: bot: merge on green, hotfix, topic: PWA

#27921 fix(gatsby-admin): Move `isOfficalPackage` & `GatsbyMonogram` to own components
  packages/gatsby-admin/src/components/gatsby-monogram.tsx
  packages/gatsby-admin/src/pages/plugins.tsx
  packages/gatsby-admin/src/utils/is-official-package.ts
Labels: topic: admin

#27923 fix(gatsby-plugin-google-analytics): add cookieFlags to options schema
  packages/gatsby-plugin-google-analytics/src/gatsby-node.js
Labels: bot: merge on green, hotfix

#27926 fix(gatsby-plugin-google-analytics): add cookieFlags to options schema (#27923)
  packages/gatsby-plugin-google-analytics/src/gatsby-node.js
Labels: type: cherry

#27928 fix(gatsby-plugin-offline): add workboxConfig.maximumFileSizeToCacheInBytes to options schema (#27913)
  packages/gatsby-plugin-offline/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-offline/src/gatsby-node.js
Labels: type: cherry

#27929 fix(gatsby): account for edge case when payload of DELETE_NODE is undefined
  packages/gatsby/src/redux/reducers/__tests__/queries.ts
  packages/gatsby/src/redux/reducers/queries.ts
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green

#27933 chore(telemery): ensure plugin validation errors are captured
  packages/gatsby-cli/src/reporter/reporter.ts
  packages/gatsby-telemetry/src/event-storage.ts
Labels: bot: merge on green, topic: telemetry*

#27937 perf(gatsby-plugin-mdx): lazily fetch file nodes for remark plugins
  packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Labels: topic: MDX, topic: performance, topic: scaling builds

#27871 fix(gatsby-transformer-remark): wait for cache promises before returning
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
  packages/gatsby/src/utils/__tests__/api-runner-node.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/cache.ts
  packages/gatsby/src/utils/get-cache.ts
Labels: bot: merge on green, topic: Markdown/remark, type: chore

#27783 feat(gatsby-transformer-sharp): Resolver API changes
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- fixed image smaller than requested size -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- fixed image -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- fixed image -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- fixed image -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- fixed image smaller than requested size -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- fixed image smaller than requested size -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- fixed image smaller than requested size -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/src/pages/images/constrained.js
  e2e-tests/visual-regression/src/pages/images/fixed-too-big.js
  e2e-tests/visual-regression/src/pages/images/fixed.js
  e2e-tests/visual-regression/src/pages/images/fluid.js
  e2e-tests/visual-regression/src/pages/static-images/constrained.js
  packages/gatsby-plugin-image/README.md
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/utils.ts
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/__tests__/utils.js
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-plugin-sharp/src/safe-sharp.d.ts
  packages/gatsby-plugin-sharp/src/utils.js
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby-transformer-sharp/src/types.ts
  yarn.lock
Labels: topic: sharp

#27943 chore: Remove reporting workflow
  .github/workflows/schedule-reporting-workflow.yml
Labels: bot: merge on green, type: chore

#26570 fix(gatsby): Update TS types to allow Node 'parent' to be nullable
  packages/gatsby/index.d.ts
Labels: topic: TypeScript*

#27011 chore(docs): Add children to styled-components doc
  docs/docs/styled-components.md
Labels: status: needs docs review

#27580 fix(docs): dictionary.txt -> KintoBlock-kintoblock
  dictionary.txt
  docs/docs/deploying-to-kintohub.md
Labels: status: needs docs review

#27945 docs(gatsby-plugin-image): Update readme
  packages/gatsby-plugin-image/README.md
Labels: status: triage needed

#27948 feat(gatsby): enable compression in the dev server
  packages/gatsby/src/utils/start-server.ts
Labels: topic: performance

#27865 fix(gatsby-transformer-asciidoc): fails when doc doesn't have title
  packages/gatsby-transformer-asciidoc/src/gatsby-node.js
Labels: bot: merge on green, hotfix, topic: asciidoc*

#27953 fix(gatsby): don't hide original error if stack-trace point to not existing file
  packages/gatsby/src/utils/api-runner-node.js
Labels: bot: merge on green

#27949 chore(gatsby-telemetry): add two more value placeholders.
  packages/gatsby-telemetry/src/telemetry.ts
Labels: bot: merge on green, topic: telemetry*

#27969 chore(gatsby-transformer-asciidoc): use optional chaining
  packages/gatsby-transformer-asciidoc/src/gatsby-node.js
Labels: bot: merge on green, type: chore

#27965 fix(gatsby-transformer-asciidoc): fails when doc doesn't have title (#27865)
  packages/gatsby-transformer-asciidoc/src/gatsby-node.js
Labels: type: cherry

#27966 fix(gatsby): don't hide original error if stack-trace point to not existing file (#27953)
  packages/gatsby/src/utils/api-runner-node.js
Labels: type: cherry

#27721 feat(gatsby-recipes): add Chakra UI recipe
  packages/gatsby-recipes/recipes/chakra-ui.mdx
Labels: topic: recipes

#27873 perf(gatsby): pull in cache lib and change lock from fs to mem
  packages/gatsby/package.json
  packages/gatsby/src/cache/__tests__/cache-fs.js
  packages/gatsby/src/cache/cache-fs.ts
  packages/gatsby/src/cache/json-file-store.ts
  packages/gatsby/src/cache/wrap-callback.ts
  packages/gatsby/src/utils/cache.ts
  yarn.lock
Labels: topic: Markdown/remark, topic: performance, topic: scaling builds

#27968 chore(gatsby-plugin-mdx): refactor lodash and debug use out
  packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Labels: topic: MDX, type: chore

#27992 fix(gatsby-transformer-sharp): create child nodes only for Files
  packages/gatsby-transformer-sharp/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-sharp/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-sharp/src/on-node-create.js
Labels: bot: merge on green, hotfix, topic: sharp

#27994 fix(gatsby-transformer-sharp): create child nodes only for Files (#27992)
  packages/gatsby-transformer-sharp/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-transformer-sharp/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-sharp/src/on-node-create.js
Labels: type: cherry

#27944 fix(gatsby-remark-images): adding missing plugin options
  packages/gatsby-remark-images/src/__tests__/gatsby-node.js
  packages/gatsby-remark-images/src/gatsby-node.js
Labels: topic: plugins

#27998 fix(gatsby-remark-images): allow showCaptions to accept array of valid strings
  packages/gatsby-remark-images/src/__tests__/gatsby-node.js
  packages/gatsby-remark-images/src/gatsby-node.js
Labels: bot: merge on green, hotfix

#27938 fix(gatsby): allow unknown plugin options
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: topic: plugins

#27955 Fix #26359: Support HTTPS for the develop status server
  packages/gatsby/src/commands/develop.ts
Labels: status: triage needed

#27829 fix(gatsby-plugin-sass): loosely check postCssPlugins
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: topic: sass

#28000 docs(gatsby-source-contentful): clean up changelog
  packages/gatsby-source-contentful/CHANGELOG.md
Labels: bot: merge on green, topic: Contentful

#27995 Add support for plugin dependencies
  packages/create-gatsby/src/features.json
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/install-plugins.ts
  packages/create-gatsby/src/plugin-options-form.ts
  packages/gatsby-cli/src/plugin-add.ts
Labels: topic: cli

#27882 feat(develop): add explicit express handler for page-data requests
  e2e-tests/development-runtime/cypress/integration/navigation/redirect.js
  e2e-tests/development-runtime/cypress/plugins/block-resources.js
  packages/gatsby/src/internal-plugins/prod-404/gatsby-node.js
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/start-server.ts
Labels: topic: resource loading*

#27703 feat(create-gatsby): Add create-gatsby
  packages/create-gatsby/.gitignore
  packages/create-gatsby/README.md
  packages/create-gatsby/package.json
  packages/create-gatsby/scripts/import-options-schema.js
  packages/create-gatsby/src/cli.ts
  packages/create-gatsby/src/cmses.json
  packages/create-gatsby/src/cmses.json.d.ts
  packages/create-gatsby/src/components/form.js
  packages/create-gatsby/src/components/placeholder.js
  packages/create-gatsby/src/components/plugin.js
  packages/create-gatsby/src/components/select.js
  packages/create-gatsby/src/components/spin.ts
  packages/create-gatsby/src/components/text.js
  packages/create-gatsby/src/components/utils.ts
  packages/create-gatsby/src/features.json
  packages/create-gatsby/src/features.json.d.ts
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/init-starter.ts
  packages/create-gatsby/src/install-plugins.ts
  packages/create-gatsby/src/plugin-options-form.ts
  packages/create-gatsby/src/plugin-schemas.json
  packages/create-gatsby/src/reporter.ts
  packages/create-gatsby/src/styles.json
  packages/create-gatsby/src/styles.json.d.ts
  packages/create-gatsby/src/types.d.ts
  packages/create-gatsby/tsconfig.json
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby-cli/src/plugin-add.ts
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
  packages/gatsby/src/commands/plugin-add.ts
  packages/gatsby/src/commands/plugin.ts
  yarn.lock
Labels: topic: cli

#28012 Fix: create-gatsby utils dependency
  packages/create-gatsby/package.json
Labels: topic: cli

#27970 docs: 2.26 release notes
  docs/reference/release-notes/v2.26/index.md
Labels: bot: merge on green, type: documentation

#28014 fix(docs): fix broken link
  docs/reference/release-notes/v2.26/index.md
Labels: bot: merge on green, type: documentation

#28015 Fix: (gatsby-recipes) Disgregard comments in config
  packages/gatsby-recipes/src/providers/gatsby/utils/get-object-from-node.js
Labels: topic: recipes

#28019 Fix: (create-gatsby) missing dependency
  packages/create-gatsby/package.json
Labels: topic: cli

#28021 chore(benchmarks): remove option because it is not yet published
  benchmarks/gabe-fs-mdx/gatsby-config.js
Labels: status: triage needed

#27963 chore(docs): Add GitHub discussions
  docs/contributing/community.md
Labels: type: documentation

#28022 chore(docs): Update add-seo-component
  docs/docs/add-seo-component.md
Labels: type: documentation

#27602 chore(gatsby-plugin-glamor): Add pluginOptionsSchema validation
  packages/gatsby-plugin-glamor/package.json
  packages/gatsby-plugin-glamor/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-glamor/src/gatsby-node.js
Labels: bot: merge on green, topic: plugins

#27601 chore(gatsby-plugin-twitter): Add pluginOptionsSchema validation
  packages/gatsby-plugin-twitter/package.json
  packages/gatsby-plugin-twitter/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-twitter/src/gatsby-node.js
Labels: bot: merge on green, topic: plugins

#28030 chore(create-gatsby): Microbundle package
  packages/create-gatsby/README.md
  packages/create-gatsby/cli.js
  packages/create-gatsby/package.json
  packages/create-gatsby/src/components/placeholder.js
  packages/create-gatsby/src/get-config-store.ts
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/init-starter.ts
  packages/create-gatsby/tsconfig.json
  packages/gatsby-cli/src/plugin-add.ts
Labels: bot: merge on green, topic: cli

#28034 Revert "fix(gatsby): refresh browser when receiving update and runtime errored (#27467)"
  e2e-tests/development-runtime/content/error-recovery/page-query.json
  e2e-tests/development-runtime/content/error-recovery/static-query.json
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/compile-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/page-query-result-runtime-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/query-validation-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/runtime-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/static-query-result-runtime-error.js
  e2e-tests/development-runtime/cypress/support/commands.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/scripts/update.js
  e2e-tests/development-runtime/src/pages/error-handling/compile-error.js
  e2e-tests/development-runtime/src/pages/error-handling/page-query-result-runtime-error.js
  e2e-tests/development-runtime/src/pages/error-handling/query-validation-error.js
  e2e-tests/development-runtime/src/pages/error-handling/runtime-error.js
  e2e-tests/development-runtime/src/pages/error-handling/static-query-result-runtime-error.js
  packages/gatsby/cache-dir/error-overlay-handler.js
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green, hotfix, topic: frontend-core

#28025 chore(telemetry): Add new telemetry field for a generic string array
  packages/gatsby-telemetry/src/telemetry.ts
Labels: bot: merge on green, status: triage needed

#28035 fix(gatsby-remark-images): adding missing plugin options (#27944 and #27998)
  packages/gatsby-remark-images/src/__tests__/gatsby-node.js
  packages/gatsby-remark-images/src/gatsby-node.js
Labels: type: cherry

#28037 fix(gatsby-plugin-sass): loosely check postCssPlugins (#27829)
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: type: cherry

#28036 chore(gatsby-telemetry): add two more value placeholders. (#27949 and #28025)
  packages/gatsby-telemetry/src/telemetry.ts
Labels: type: cherry

#28038 Revert "fix(gatsby): refresh browser when receiving update and runtime errored (#27467)" (#28034)
  e2e-tests/development-runtime/content/error-recovery/page-query.json
  e2e-tests/development-runtime/content/error-recovery/static-query.json
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/compile-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/page-query-result-runtime-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/query-validation-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/runtime-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/static-query-result-runtime-error.js
  e2e-tests/development-runtime/cypress/support/commands.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/scripts/update.js
  e2e-tests/development-runtime/src/pages/error-handling/compile-error.js
  e2e-tests/development-runtime/src/pages/error-handling/page-query-result-runtime-error.js
  e2e-tests/development-runtime/src/pages/error-handling/query-validation-error.js
  e2e-tests/development-runtime/src/pages/error-handling/runtime-error.js
  e2e-tests/development-runtime/src/pages/error-handling/static-query-result-runtime-error.js
  packages/gatsby/cache-dir/error-overlay-handler.js
  packages/gatsby/package.json
  yarn.lock
Labels: type: cherry

#28010 fix(gatsby): allow unknown plugin options (#27938)
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: bot: merge on green, type: cherry

#28039 fix(create-gatsby): Disable emojis on Windows
  packages/create-gatsby/package.json
  packages/create-gatsby/src/components/spin.ts
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/init-starter.ts
  packages/create-gatsby/src/reporter.ts
  yarn.lock
Labels: topic: cli

#27954 feat(gatsby-cli): add GATSBY_EXPERIMENTAL_GATSBY_NEW_FLOW flag to use create-gatsby when no options are provided
  docs/docs/gatsby-cli.md
  integration-tests/gatsby-cli/__tests__/new.js
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/create-cli.ts
Labels: topic: cli

#27843 Make optional SVG favicon come after the fallback
  packages/gatsby-plugin-manifest/src/__tests__/__snapshots__/gatsby-ssr.js.snap
  packages/gatsby-plugin-manifest/src/gatsby-ssr.js
Labels: bot: merge on green, topic: PWA

#28043 fix(create-gatsby): Better subprocess handling
  packages/create-gatsby/package.json
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/init-starter.ts
  packages/create-gatsby/src/reporter.ts
  yarn.lock
Labels: topic: cli

#27951 fix(plugin-manifest): Allow for all valid WebAppManifest properties
  packages/gatsby-plugin-manifest/README.md
  packages/gatsby-plugin-manifest/package.json
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Labels: bot: merge on green, status: triage needed

#28064 fix(create-gatsby): Shim worker_threads
  packages/create-gatsby/package.json
  yarn.lock
Labels: topic: cli

#27756 add query pluginOption for mongodb plugin
  packages/gatsby-source-mongodb/README.md
  packages/gatsby-source-mongodb/src/gatsby-node.js
Labels: topic: MongoDB*, topic: plugins, type: feature or enhancement

#27989 test(gatsby-plugin-image): gatsby-image-server.ts
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
Labels: topic: plugins

#28096 fix(docs): fix lazy-images install instructions
  docs/reference/release-notes/v2.26/index.md
Labels: bot: merge on green, type: documentation

#28032 perf(gatsby): fix performance regression with query dependency cleaning
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/reducers/__tests__/__snapshots__/queries.ts.snap
  packages/gatsby/src/redux/reducers/__tests__/queries.ts
  packages/gatsby/src/redux/reducers/queries.ts
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green, topic: performance, topic: scaling builds

#28060 test(e2e-development-runtime): assert we don't show stale query data
  e2e-tests/development-runtime/content/query-data-caches/page-query-404-to-B-to-404-history.json
  e2e-tests/development-runtime/content/query-data-caches/page-query-404-to-B-to-404-link.json
  e2e-tests/development-runtime/content/query-data-caches/page-query-CO-to-B-to-CO-history.json
  e2e-tests/development-runtime/content/query-data-caches/page-query-CO-to-B-to-CO-link.json
  e2e-tests/development-runtime/content/query-data-caches/page-query-no-trailing-slash-A-to-B-to-A-history.json
  e2e-tests/development-runtime/content/query-data-caches/page-query-no-trailing-slash-A-to-B-to-A-link.json
  e2e-tests/development-runtime/content/query-data-caches/page-query-with-trailing-slash-A-to-B-to-A-history.json
  e2e-tests/development-runtime/content/query-data-caches/page-query-with-trailing-slash-A-to-B-to-A-link.json
  e2e-tests/development-runtime/content/query-data-caches/static-query-404-to-B-to-404-history.json
  e2e-tests/development-runtime/content/query-data-caches/static-query-404-to-B-to-404-link.json
  e2e-tests/development-runtime/content/query-data-caches/static-query-CO-to-B-to-CO-history.json
  e2e-tests/development-runtime/content/query-data-caches/static-query-CO-to-B-to-CO-link.json
  e2e-tests/development-runtime/content/query-data-caches/static-query-no-trailing-slash-A-to-B-to-A-history.json
  e2e-tests/development-runtime/content/query-data-caches/static-query-no-trailing-slash-A-to-B-to-A-link.json
  e2e-tests/development-runtime/content/query-data-caches/static-query-with-trailing-slash-A-to-B-to-A-history.json
  e2e-tests/development-runtime/content/query-data-caches/static-query-with-trailing-slash-A-to-B-to-A-link.json
  e2e-tests/development-runtime/cypress.json
  e2e-tests/development-runtime/cypress/integration/functionality/query-data-caches.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/scripts/update.js
  e2e-tests/development-runtime/src/components/query-data-caches/static-query-404-history.js
  e2e-tests/development-runtime/src/components/query-data-caches/static-query-404-link.js
  e2e-tests/development-runtime/src/components/query-data-caches/view.js
  e2e-tests/development-runtime/src/pages/404.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-404-to-B-to-404-history/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-404-to-B-to-404-link/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-CO-to-B-to-CO-history/[client-only].js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-CO-to-B-to-CO-history/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-CO-to-B-to-CO-link/[client-only].js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-CO-to-B-to-CO-link/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-no-trailing-slash-A-to-B-to-A-history/page-A.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-no-trailing-slash-A-to-B-to-A-history/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-no-trailing-slash-A-to-B-to-A-link/page-A.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-no-trailing-slash-A-to-B-to-A-link/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-with-trailing-slash-A-to-B-to-A-history/page-A.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-with-trailing-slash-A-to-B-to-A-history/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-with-trailing-slash-A-to-B-to-A-link/page-A.js
  e2e-tests/development-runtime/src/pages/query-data-caches/page-query-with-trailing-slash-A-to-B-to-A-link/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-404-to-B-to-404-history/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-404-to-B-to-404-link/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-CO-to-B-to-CO-history/[client-only].js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-CO-to-B-to-CO-history/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-CO-to-B-to-CO-link/[client-only].js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-CO-to-B-to-CO-link/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-no-trailing-slash-A-to-B-to-A-history/page-A.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-no-trailing-slash-A-to-B-to-A-history/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-no-trailing-slash-A-to-B-to-A-link/page-A.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-no-trailing-slash-A-to-B-to-A-link/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-with-trailing-slash-A-to-B-to-A-history/page-A.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-with-trailing-slash-A-to-B-to-A-history/page-B.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-with-trailing-slash-A-to-B-to-A-link/page-A.js
  e2e-tests/development-runtime/src/pages/query-data-caches/static-query-with-trailing-slash-A-to-B-to-A-link/page-B.js
Labels: topic: resource loading*

#28095 docs(docs): correct firebase headers example
  docs/docs/deploying-to-firebase.md
Labels: type: documentation

#28075 refactor(dev-loader): consolidate socket.io and loader caches, remove `getPageData` websocket logic
  packages/gatsby/cache-dir/__tests__/dev-loader.js
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/query-result-store.js
  packages/gatsby/cache-dir/socketIo.js
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/utils/__tests__/websocket-manager.ts
  packages/gatsby/src/utils/websocket-manager.ts
Labels: topic: resource loading*

#28106 chore(gatsby): update yarn.lock
  yarn.lock
Labels: status: triage needed

#28101 test(gatsby-plugin-image): add test for gatsby-plugin-image browser
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx
Labels: topic: images/media

#28013 feat(recipes-list): add chakra-ui
  packages/gatsby-recipes/src/recipes-list.js
Labels: topic: recipes

#28099 fix(plugin-manifest): Allow for all valid WebAppManifest properties (#27951)
  packages/gatsby-plugin-manifest/README.md
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Labels: type: cherry

#28119 chore(gatsby-plugin-sharp): Upgrade sharp
  benchmarks/source-strapi/package.json
  packages/gatsby-plugin-manifest/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-transformer-sharp/package.json
  yarn.lock
Labels: bot: merge on green, topic: sharp

#28123 chore(gatsby-transformer-sharp): Replace alpha warning for gatsbyImageData
  packages/gatsby-plugin-image/README.md
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: bot: merge on green, topic: sharp

#28122 test(e2e-development-runtime): bump timeout for those flaky test that seems to timeout sometimes in CI
  e2e-tests/development-runtime/cypress.json
  packages/gatsby-cypress/src/commands.js
Labels: topic: automation

#28111 feat(state-machine): add query on demand transitions
  packages/gatsby/src/services/listen-for-mutations.ts
  packages/gatsby/src/services/types.ts
  packages/gatsby/src/state-machines/develop/actions.ts
  packages/gatsby/src/state-machines/develop/index.ts
  packages/gatsby/src/state-machines/query-running/actions.ts
  packages/gatsby/src/state-machines/query-running/index.ts
  packages/gatsby/src/state-machines/query-running/types.ts
Labels: topic: state machine

#28124 Add Netlify CMS to create-gatsby
  packages/create-gatsby/src/cmses.json
Labels: topic: cli

#28097 fix(gatsby): fix race condition in cache lock
  packages/gatsby/src/cache/cache-fs.ts
  packages/gatsby/src/cache/json-file-store.ts
Labels: type: bug

#28128 benchmarks(contentful): use the new max pageLimit
  benchmarks/source-contentful/gatsby-config.js
Labels: topic: Contentful, topic: benchmarks

#28120 feat: add utility to show experiment invitation notices
  packages/gatsby/src/utils/show-experiment-notice.ts
Labels: topic: cli

#28132 chore(create-gatsby): Remove alpha warning
  packages/create-gatsby/src/index.ts
Labels: bot: merge on green, topic: cli

#28107 feat(create-gatsby): add telemetry tracking
  packages/create-gatsby/package.json
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/tracking.ts
  packages/create-gatsby/src/types.d.ts
  packages/gatsby-telemetry/src/in-memory-store.ts
Labels: topic: plugins

#28118 chore: update publishing scripts
  lerna.json
  package.json
Labels: bot: merge on green, type: maintenance

#27313 chore(docs): replace typefaces with fontsource
  docs/docs/recipes/styling-css.md
  docs/docs/using-web-fonts.md
Labels: hacktoberfest-accepted, status: needs docs review, type: documentation

#28116 feat(gatsby): invite people with long develop bundling times to try the lazy dev js bundling feature
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/show-experiment-notice.ts
  packages/gatsby/src/utils/start-server.ts
Labels: bot: merge on green, topic: dev tooling

#28127 feat(develop): add query on demand behind feature flag
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/cache-dir/ensure-resources.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/reducers/__tests__/__snapshots__/queries.ts.snap
  packages/gatsby/src/redux/reducers/__tests__/queries.ts
  packages/gatsby/src/redux/reducers/queries.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/calculate-dirty-queries.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/websocket-manager.ts
Labels: bot: merge on green

#28136 feat(create-gatsby): Try adding sitehash to success event
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/tracking.ts
Labels: bot: merge on green, status: triage needed

#27432 feat(gatsby): SSR pages during development
  .circleci/config.yml
  integration-tests/ssr/LICENSE
  integration-tests/ssr/README.md
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
  integration-tests/ssr/__tests__/fixtures/bad-page.js
  integration-tests/ssr/__tests__/ssr.js
  integration-tests/ssr/gatsby-config.js
  integration-tests/ssr/jest.config.js
  integration-tests/ssr/package.json
  integration-tests/ssr/src/pages/hi.js
  integration-tests/ssr/src/pages/hi2.js
  integration-tests/ssr/src/pages/hi3.js
  integration-tests/ssr/src/pages/index.js
  integration-tests/ssr/test-output.js
  packages/babel-plugin-remove-graphql-queries/src/index.ts
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-plugin-typography/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-typography/src/gatsby-ssr.js
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package-json.test.js.snap
  packages/gatsby-recipes/src/providers/npm/fixtures/package-json/package.json
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/develop-html-route.ts.snap
  packages/gatsby/src/utils/__tests__/develop-html-route.ts
  packages/gatsby/src/utils/__tests__/fixtures/blog-post.js
  packages/gatsby/src/utils/__tests__/fixtures/error-object.js
  packages/gatsby/src/utils/dev-ssr/develop-html-route.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/webpack-error-utils.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/worker/render-html.ts
Labels: type: feature or enhancement

#27792 chore(gatsby-source-graphql): upgrade graphql-tools to v7
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/gatsby-node.js
  yarn.lock
Labels: bot: merge on green, topic: GraphQL
