Repository gatsbyjs/gatsby, pull requests merged in 2020-06, with the labels that each got.

#24638 docs(gatsby-source-filesystem): use comma delimiter for object values
  packages/gatsby-source-filesystem/README.md
Labels: bot: merge on green, type: documentation

#24409 i18next: Suspense API and React Hooks are not experimental anymore
  docs/docs/localization-i18n.md
Labels: status: needs docs review, type: documentation

#24648 chore(showcase): Add mobileui.dev
  docs/sites.yml
Labels: topic: showcase

#24683 chore(gatsby): Export and improve types
  packages/gatsby/src/bootstrap/create-graphql-runner.ts
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/utils/wait-until-jobs-complete.ts
  packages/gatsby/src/utils/websocket-manager.ts
Labels: status: inkteam assigned

#24687 fix(gatsby-recipes): move strip-ansi to dependencies
  packages/gatsby-recipes/package.json
Labels: topic: recipes

#21376 Reach skip nav example
  examples/using-reach-skip-nav/README.md
  examples/using-reach-skip-nav/cypress.json
  examples/using-reach-skip-nav/cypress/fixtures/example.json
  examples/using-reach-skip-nav/cypress/integration/skip-nav.test.js
  examples/using-reach-skip-nav/cypress/plugins/index.js
  examples/using-reach-skip-nav/cypress/support/commands.js
  examples/using-reach-skip-nav/cypress/support/index.js
  examples/using-reach-skip-nav/gatsby-browser.js
  examples/using-reach-skip-nav/gatsby-config.js
  examples/using-reach-skip-nav/gatsby-node.js
  examples/using-reach-skip-nav/package.json
  examples/using-reach-skip-nav/src/components/header.css
  examples/using-reach-skip-nav/src/components/header.js
  examples/using-reach-skip-nav/src/components/layout.css
  examples/using-reach-skip-nav/src/components/layout.js
  examples/using-reach-skip-nav/src/components/seo.js
  examples/using-reach-skip-nav/src/images/gatsby-icon.png
  examples/using-reach-skip-nav/src/pages/404.js
  examples/using-reach-skip-nav/src/pages/emergency-kit.js
  examples/using-reach-skip-nav/src/pages/index.js
  examples/using-reach-skip-nav/src/pages/self-care.js
Labels: status: needs docs review

#24662 fix(blog): gatsby days speakers - remove local domain, fix branding
  docs/blog/2020-05-13-virtual-gatsby-day-speakers/index.md
Labels: topic: blogpost

#24627 fix(blog): impossible foods - remove local links
  docs/blog/2020-05-07-gatsby-delivers-impossible-burgers-map/index.md
Labels: status: inkteam assigned, topic: blogpost

#24697 (chore) Fix Strapi link
  docs/blog/2020-05-29-gazette/index.md
Labels: status: triage needed, topic: blogpost

#24699 fix(recipe): Preact - brand name
  packages/gatsby-recipes/recipes/preact.mdx
Labels: bot: merge on green, topic: recipes

#24651 fix(www): cleanup of css in guidelines containers + color and logo page
  www/src/components/guidelines/color/modal.js
  www/src/components/guidelines/containers.js
  www/src/pages/guidelines/color.js
  www/src/pages/guidelines/logo.js
Labels: bot: merge on green, topic: website

#24664 docs: the location prop is only passed to page components
  docs/docs/location-data-from-props.md
Labels: status: needs docs review, type: documentation

#24636 feature(www): convert the class based color component to function component
  www/src/pages/guidelines/color.js
Labels: bot: merge on green, topic: website, type: feature or enhancement

#24637 feature(www): convert the class based swatch component to function component
  www/src/components/guidelines/color/swatch.js
Labels: topic: website, type: feature or enhancement

#23536 Fix typos
  .eslintrc.js
  docs/tutorial/e-commerce-with-datocms-and-snipcart/index.md
  examples/using-i18n/gatsby-node.js
  examples/using-js-search/src/components/SearchContainer.js
  packages/gatsby-dev-cli/src/utils/traverse-package-deps.js
  packages/gatsby-plugin-catch-links/src/__tests__/catch-links.js
  packages/gatsby-recipes/README.md
  packages/gatsby/src/query/query-watcher.js
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/utils/__tests__/api-runner-error-parser.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: bot: merge on green, type: documentation

#23689 Add remark-lint-heading-increment and resolve issues
  .remarkrc.js
  docs/blog/100days/gatsby-image/index.md
  docs/blog/2018-2-7-jam-out-your-blog/index.md
  docs/blog/2019-04-29-component-shadowing/index.md
  docs/blog/2019-11-25-introducing-gatsby-preview-for-cosmic-js/index.md
  docs/blog/2020-01-08-git-workflows/index.md
  docs/docs/production-app.md
Labels: type: documentation

#23153 fix(blog): agility - fix format
  docs/blog/2020-04-13-upgrading-to-jamstack-with-agility/index.md
Labels: topic: blogpost

#24570 fix(www): layout for `/guidelines/typography` + convert to theme-ui
  www/src/components/guidelines/cards/blog.js
  www/src/components/guidelines/cards/starter.js
  www/src/components/guidelines/containers.js
  www/src/pages/guidelines/typography.js
Labels: bot: merge on green, topic: website

#24698 fix(starter): add redirect for previous path
  www/starter-redirects.json
Labels: topic: website

#24700 fix(blog): Little & Big - local domain
  docs/blog/2020-05-19-little-agency-big-impact/index.md
Labels: topic: blogpost

#24690 fix(blog): Theme Catalyst - remove local domain, fix branding
  docs/blog/2020-05-14-introducing-gatsby-theme-catalyst/index.md
Labels: topic: blogpost

#24696 fix(recipe): AVA - fix brand name
  packages/gatsby-recipes/recipes/ava.mdx
  packages/gatsby-recipes/src/cli.js
Labels: topic: recipes

#24694 chore(starter): fix brand names in starters
  docs/starters.yml
Labels: topic: starters

#24659 fix(docs): add trailing slashes to glossary links
  docs/docs/glossary/decoupled-drupal.md
  docs/docs/glossary/headless-cms.md
  docs/docs/glossary/npm.md
Labels: status: triage needed

#24660 fix(blog): a11y - use new a11y email
  docs/blog/2019-04-18-gatsby-commitment-to-accessibility/index.md
Labels: topic: blogpost

#24154 fix(gatsby-plugin-preact): add preact to framework bundle
  packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
Labels: bot: merge on green, status: needs core review

#24613 fix(gatsby-source-filesystem): fix extension guessing on warm cache
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
Labels: status: needs core review, topic: data sourcing

#24378 fix(data-dependency-tracking): clear data dependencies when rerunning dirty queries
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/query/index.js
Labels: topic: StaticQuery

#24608 fix(gatsby-dev-cli): support workspaces in yarn@1.22
  packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
Labels: topic: dev tooling, type: bug

#24054 feat(gatsby): Add support for relative links
  docs/docs/gatsby-link.md
  docs/docs/linking-between-pages.md
  e2e-tests/development-runtime/cypress/integration/navigation/linking.js
  e2e-tests/development-runtime/src/pages/index.js
  e2e-tests/development-runtime/src/pages/subdirectory/index.js
  e2e-tests/development-runtime/src/pages/subdirectory/page-1.js
  e2e-tests/development-runtime/src/pages/subdirectory/page-2.js
  e2e-tests/path-prefix/cypress/integration/navigate.js
  e2e-tests/path-prefix/src/pages/index.js
  e2e-tests/path-prefix/src/pages/subdirectory/index.js
  e2e-tests/path-prefix/src/pages/subdirectory/page-1.js
  e2e-tests/path-prefix/src/pages/subdirectory/page-2.js
  e2e-tests/production-runtime/cypress/integration/1-production.js
  e2e-tests/production-runtime/src/pages/index.js
  e2e-tests/production-runtime/src/pages/subdirectory/index.js
  e2e-tests/production-runtime/src/pages/subdirectory/page-1.js
  e2e-tests/production-runtime/src/pages/subdirectory/page-2.js
  packages/gatsby-link/src/__tests__/index.js
  packages/gatsby-link/src/index.js
  packages/gatsby/cache-dir/__tests__/strip-prefix.js
  packages/gatsby/cache-dir/find-path.js
  packages/gatsby/cache-dir/strip-prefix.js
Labels: topic: reach/router and Links

#23877 chore(gatsby): Migrate reducers/index to TypeScript
  packages/gatsby/src/redux/__tests__/nodes.ts
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/reducers/config.ts
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/last-action.ts
  packages/gatsby/src/redux/reducers/nodes.ts
Labels: status: needs core review, topic: TypeScript migration

#24709 perf(gatsby): drop severe scaling regression caused by analytics
  packages/gatsby/src/query/graphql-runner.ts
Labels: topic: GraphQL, topic: performance, topic: scaling builds

#24718 chore(www): convert swatch component to theme-ui
  www/src/components/guidelines/color/swatch.js
Labels: topic: website

#24714 Update links redirects on Kontent sourcing guide
  docs/docs/sourcing-from-kentico-kontent.md
Labels: type: documentation

#24719 chore(starters): Relinking repo, adjusting features gatsby-starter-payments, gatsby-starter-donations
  docs/starters.yml
Labels: topic: showcase

#24688 chore(showcase): Add nagarjun.co to showcase
  docs/sites.yml
Labels: topic: showcase

#24500 fix(blog): ButterCMS & Car Loans Canada - fix branding
  docs/blog/2020-05-05-Butter-CMS-case-study/index.md
Labels: type: documentation

#24658 change siteURL to siteUrl
  packages/gatsby-theme-blog/README.md
Labels: status: needs docs review, topic: themes

#24723 Actually commit the patch
  benchmarks/source-sanity/update-post.js
Labels: topic: benchmarks*

#24363 fix(docs): deploying to gitlab - missing point in file name
  docs/docs/deploying-to-gitlab-pages.md
Labels: type: documentation

#24362 fix(recipes): CI recipes - change Gitlab to GitLab
  docs/docs/recipes/gitlab-continuous-integration.md
  packages/gatsby-recipes/recipes/gitlab-ci-cd.mdx
Labels: topic: recipes

#24497 fix(docs): fix branding ButterCMS
  docs/docs/sourcing-from-buttercms.md
Labels: type: documentation

#24503 fix(glossary): IaC - fix name for consistency
  docs/docs/glossary.md
Labels: type: documentation

#24508 fix(docs): glossary IaC - fix code language to MDX
  docs/docs/glossary/infrastructure-as-code/index.md
Labels: status: needs dx review

#24507 fix(docs): glossary IaC - brand names
  docs/docs/glossary/infrastructure-as-code/index.md
Labels: status: needs dx review

#24621 fix(docs): node creation - file type
  docs/docs/node-creation.md
Labels: status: inkteam assigned, status: needs dx review

#24710 chore(blog): Fix brand name for WordPress
  docs/blog/2020-04-17-gatsby-survey-goes-command-line/index.md
  docs/blog/2020-05-26-introducing-will-it-build/index.md
Labels: status: triage needed, type: documentation

#24715 chore(docs): Fix brand name for GitHub
  docs/blog/2020-03-11-netlify-functions-and-gatsby-cloud/index.md
  docs/docs/deploying-to-gatsby-cloud.md
  docs/starters.yml
  rfcs/text/0005-docs-decision-tree.md
  rfcs/text/0011-move-rfcs-to-monorepo.md
Labels: status: triage needed

#24628 chore(starters): add gatsby-starter-simple
  docs/starters.yml
Labels: topic: showcase

#24730 chore(blog): 🔒 Fix missing HTTPS on Twitter link
  docs/blog/2017-12-07-taking-gatsby-for-a-spin/index.md
Labels: topic: blogpost

#24732 chore(blog): 🔒 Fix missing HTTPS on gatsbyjs.com links
  docs/blog/2020-04-22-announcing-incremental-builds/index.md
  docs/blog/2020-05-27-announcing-series-b-funding/index.md
Labels: topic: blogpost

#24609 perf(gatsby): be more conservative in when to sort
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/redux/run-sift.js
Labels: status: needs core review, topic: GraphQL, topic: performance, topic: scaling builds

#24708 chore(gatsby): Switch query running to use services
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/query/index.js
  packages/gatsby/src/services/calculate-dirty-queries.ts
  packages/gatsby/src/services/index.ts
  packages/gatsby/src/services/run-page-queries.ts
  packages/gatsby/src/services/run-static-queries.ts
  packages/gatsby/src/services/types.ts
Labels: bot: merge on green, topic: develop state machine

#24745 fix(gatsby-link): Fail gracefully on empty `to` prop
  packages/gatsby-link/src/index.js
Labels: status: triage needed

#24569 fix(www): layout for `/guidelines/design-tokens` + convert to theme-ui
  www/src/components/guidelines/containers.js
  www/src/pages/guidelines/design-tokens.js
Labels: bot: merge on green, topic: website

#24716 fixing some 404 links
  docs/docs/deploying-to-azure.md
Labels: bot: merge on green, status: needs docs review

#24729 chore(docs): Fix typographical error
  docs/tutorial/part-eight/index.md
Labels: type: documentation

#24335 fix(gatsby): Fix develop SSL by moving the SSL setup to the proxy
  packages/gatsby/cache-dir/app.js
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/develop-proxy.ts
  packages/gatsby/src/utils/restarting-screen.ts
Labels: status: needs core review, topic: cli

#24618 chore: add cosmicjs data updating script
  benchmarks/source-cosmicjs/.env.example
  benchmarks/source-cosmicjs/package.json
  benchmarks/source-cosmicjs/update-post.js
Labels: topic: benchmarks*

#24761 fix(gatsby): bind develop-proxy server to host specified by user
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/utils/develop-proxy.ts
Labels: bot: merge on green, topic: cli, type: bug

#24684 chore(gatsby): Optimise create page action validation
  packages/gatsby/src/redux/__tests__/__snapshots__/pages.ts.snap
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/validate-page-component.ts
Labels: status: inkteam assigned

#24769 fix(gatsby): TypeScript typings import error
  packages/gatsby/index.d.ts
Labels: status: needs core review

#24754 fix(gatsby): add connection data dependency on concrete types when abstract type is queried
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
Labels: bot: merge on green, topic: GraphQL

#24743 perf(gatsby): stop using Sift as fallback
  packages/gatsby/src/redux/__tests__/run-sift.js
  packages/gatsby/src/redux/run-sift.js
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/__tests__/run-query.js
Labels: bot: merge on green, topic: GraphQL, topic: performance, topic: scaling builds

#24771 Delete unused timesum.js file with lint errors
  packages/gatsby/src/timesum.js
Labels: bot: merge on green, type: maintenance

#24753 recipes(fix): add docs for Directory resource to gatsby-recipes README
  packages/gatsby-recipes/README.md
Labels: topic: recipes

#24747 chore(starters): add gatsby-starter-woo
  docs/starters.yml
Labels: topic: showcase

#24548 Add form-name hidden field for Netlify Forms
  docs/docs/building-a-contact-form.md
Labels: topic: a11y, topic: i18n

#24610 Gatsby Admin UI cleanup
  packages/gatsby-admin/gatsby-config.js
  packages/gatsby-admin/package.json
  packages/gatsby-admin/src/components/layout.tsx
  packages/gatsby-admin/src/components/navbar.tsx
  packages/gatsby-admin/src/components/providers.tsx
  packages/gatsby-admin/src/pages/index.tsx
  yarn.lock
Labels: topic: admin

#24807 fix(babel-plugin-remove-graphql-queries): Strip ignored characters from query text for better caching and deduping
  packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
  packages/babel-plugin-remove-graphql-queries/src/index.js
  packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/query/__tests__/file-parser.js
Labels: type: bug

#24805 fix(gatsby): Fix issue where inline static query in page gets added to page data
  packages/gatsby/src/query/query-watcher.js
Labels: type: bug

#24813 Fix #24809
  packages/gatsby/src/utils/validate-page-component.ts
Labels: status: inkteam assigned, type: bug

#24788 fix(gatsby-transformer-react-docgen): update react-docgen, fix tests
  packages/gatsby-transformer-react-docgen/package.json
  packages/gatsby-transformer-react-docgen/src/__tests__/displayname-handler.js
  yarn.lock
Labels: bot: merge on green, status: needs core review

#24798 fix(blog): recipes - code block languages, brand names, local links
  docs/blog/2020-05-21-gatsby-recipes/index.md
Labels: topic: blogpost, topic: recipes

#24491 chore(gatsby-recipes): Implement a basic recipes integration test for the cli
  integration-tests/gatsby-cli/__tests__/recipes.js
Labels: topic: recipes

#24642 docs: explain exactly how to add JSON+LD data
  docs/docs/seo.md
Labels: status: needs docs review, type: documentation

#24837 Improved includesDefaultExport Check
  packages/gatsby/src/utils/validate-page-component.ts
Labels: impact: low, status: needs core review

#24797 fix(blog): deploying to azure - code block languages
  docs/docs/deploying-to-azure.md
Labels: status: needs dx review, type: documentation

#24801 fix(docs): surge - remove local domain
  docs/docs/deploying-to-surge.md
Labels: status: needs docs review, type: documentation

#24821 fix(gatsby-remark-embed-snippet): readme - change code language
  packages/gatsby-remark-embed-snippet/README.md
Labels: status: triage needed

#24826 fix(examples): skip nave Readme - code blocks, brand names
  examples/using-reach-skip-nav/README.md
Labels: type: documentation

#24520 fix(docs): Info about required schemas in plugin
  docs/docs/sourcing-from-prismic.md
Labels: status: needs dx review

#24817 chore(www): convert the badge component to theme-ui
  www/src/components/guidelines/badge.js
  www/src/pages/guidelines/color.js
  www/src/pages/guidelines/design-tokens.js
  www/src/pages/guidelines/typography.js
Labels: topic: website, type: feature or enhancement

#24640 fix(babel-preset-gatsby-package): remove explicit `@babel/plugin-proposal-class-properties` and let `@babel/preset-env` add it
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/index.js
  packages/babel-preset-gatsby-package/package.json
Labels: status: needs core review, topic: webpack/babel

#24843 chore(gatsby): validate-page-component - simplify regex
  packages/gatsby/src/utils/validate-page-component.ts
Labels: status: needs core review, topic: page creation, type: maintenance

#24873 Fix typo in gatsby-source-wordpress README
  packages/gatsby-source-wordpress/README.md
Labels: status: needs docs review

#24849 chore(starters): update gatsby-tailwind-emotion-starter
  docs/starters.yml
Labels: topic: showcase

#24904 fix(gatsby): Add null context check
  packages/gatsby/src/redux/actions/public.js
Labels: bot: merge on green

#24918 chore(docs): 🔒 Fix missing HTTPS on github.io links
  docs/blog/2017-11-06-migrate-hugo-gatsby/index.md
  docs/blog/2018-05-24-launching-new-gatsby-company/index.md
  docs/blog/2018-10-26-export-a-drupal-site-to-gatsby/index.md
  docs/docs/ab-testing-with-google-analytics-and-netlify.md
  docs/docs/localization-i18n.md
  docs/starters.yml
  examples/styleguide/src/templates/ComponentPage/components/ComponentPreview/prism-theme.css
  packages/gatsby-source-wordpress/README.md
  packages/gatsby-transformer-toml/README.md
Labels: status: triage needed

#24921 chore(docs): Fix Netlify app links change .com to .app.
  docs/blog/2018-07-07-graphic-design-class/index.md
  docs/docs/using-cloudinary-image-service.md
  docs/tutorial/blog-netlify-cms-tutorial/index.md
  examples/using-javascript-transforms/README.md
Labels: status: triage needed

#24831 chore(starters): Updated starter URLs due to DNS changes and Github Repo Urls
  docs/starters.yml
Labels: topic: starters

#24605 feat(benchmarks): add Kontent benchmark
  benchmarks/source-kontent/.env.template
  benchmarks/source-kontent/.gitignore
  benchmarks/source-kontent/.prettierignore
  benchmarks/source-kontent/.prettierrc
  benchmarks/source-kontent/LICENSE
  benchmarks/source-kontent/README.md
  benchmarks/source-kontent/gatsby-browser.js
  benchmarks/source-kontent/gatsby-config.js
  benchmarks/source-kontent/gatsby-node.js
  benchmarks/source-kontent/package.json
  benchmarks/source-kontent/src/components/layout_1.js
  benchmarks/source-kontent/src/components/layout_2.js
  benchmarks/source-kontent/src/pages/index.js
  benchmarks/source-kontent/src/templates/article.js
  benchmarks/source-kontent/styles.css
  benchmarks/source-kontent/update-article.js
Labels: topic: benchmarks*

#24934 Add blog post about commitment to equity and how we are going to do i…
  docs/blog/2020-06-11-you-belong-here-commitment/index.md
  docs/blog/author.yaml
  docs/blog/avatars/bianca-nedjar.jpg
Labels: topic: blogpost

#24485 Blog Post : "Presenting without sharing my slides" by Sam Larsen-Disney
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/images/button-previews.png
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/images/gesture-control.gif
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/images/gesture-ranges.png
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/images/remote-slides.gif
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/images/slide-previews.png
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/images/tour-preview.png
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/index.md
  docs/blog/author.yaml
  docs/blog/avatars/sam-larsendisney.jpg
Labels: topic: blogpost

#24937 docs(gatsby-transformer-remark): Removed superfluous "an" from README
  packages/gatsby-transformer-remark/README.md
Labels: status: needs docs review

#24882 docs: update Stripe ecommerce tutorial
  docs/tutorial/ecommerce-tutorial/index.md
Labels: type: documentation

#24935 chore(docs): 🔒 Fix missing HTTPS on surge.sh, wordpress.com and react…
  docs/blog/2017-11-09-why-i-created-my-blog-with-gatsby-and-contentful/index.md
  docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md
  docs/docs/sourcing-from-wordpress.md
  docs/tutorial/part-one/index.md
Labels: status: needs docs review

#24942 docs: gatsby-plugin-offline mentions Workbox
  packages/gatsby-plugin-offline/README.md
Labels: status: triage needed, type: documentation

#24957 Adjust frontmatter because errors
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/index.md
Labels: status: triage needed

#24988 refactor(www): convert EcosystemBoard to function component + cleanup
  www/src/components/ecosystem/ecosystem-board.js
Labels: status: triage needed

#24963 refactor(www): convert sticky-responsive-sidebar to function component
  www/src/components/sidebar/sticky-responsive-sidebar.js
Labels: status: triage needed

#24844 refactor(www): convert the class based collapsible to function component
  www/src/views/shared/collapsible.js
Labels: topic: website, type: feature or enhancement

#24810 Remove gatsby-admin dependency from gatsby by packaging it into gatsby
  lerna.json
  packages/gatsby-admin/package.json
  packages/gatsby/.gitignore
  packages/gatsby/package.json
  packages/gatsby/src/utils/develop-proxy.ts
  yarn.lock
Labels: bot: merge on green, topic: admin

#24981 fix(blog): Gatsby Slides - local domain, brand names, code blocks ...
  docs/blog/2020-06-16-Gatsby-slideshow-with-Posenet/index.md
Labels: topic: blogpost

#24991 refactor(www): convert <Banner/> component to theme-ui + cleanup
  www/src/components/banner.js
Labels: topic: website

#24972 refactor(www): cleanup of MarkdownPageFooter + convert to function component
  www/src/components/markdown-page-footer.js
Labels: topic: website

#24960 chore(www): removes unused componentWillUnmount lifecycle method
  www/src/components/react-hubspot-form.js
Labels: topic: website

#24929 chore(www): convert the overview component to theme-ui
  www/src/components/guidelines/color/overview.js
Labels: topic: website

#24847 refactor(www): convert avatar of guidelines to theme-ui
  www/src/components/guidelines/avatar.js
  www/src/components/guidelines/cards/blog.js
Labels: topic: website, type: feature or enhancement

#24836 fix(www): card component imported as ColorSwatch in guidelines/logo page
  www/src/components/guidelines/color/card.js
Labels: topic: website, type: feature or enhancement

#24835 refactor(www): convert EvaluationTable to function component
  www/src/components/features/evaluation-table.js
Labels: topic: website, type: feature or enhancement

#24834 refactor(www): convert SimpleEvaluationTable to function component
  www/src/components/features/simple-evaluation-table.js
Labels: topic: website, type: feature or enhancement

#24990 docs: add forgotten paren to client-only routes
  docs/docs/client-only-routes-and-user-authentication.md
Labels: type: documentation

#24976 fix(blog): you belong here - remove local domain
  docs/blog/2020-06-11-you-belong-here-commitment/index.md
Labels: topic: blogpost

#25014 fix(gatsby-admin): add missing `nodemon` dependency
  packages/gatsby-admin/package.json
  yarn.lock
Labels: bot: merge on green

#25002 docs(gatsby): Update path to slug
  docs/docs/adding-a-list-of-markdown-blog-posts.md
Labels: status: needs docs review, type: dx

#24984 fix(docs): glossary/markdown - change bash to shell
  docs/docs/glossary/markdown.md
Labels: status: needs docs review, type: dx

#24964 docs(gatsby): remove unnecessary abbr tags
  docs/docs/glossary/build.md
  docs/docs/glossary/infrastructure-as-code/index.md
  docs/docs/glossary/jamstack.md
  docs/docs/glossary/npm.md
Labels: status: needs docs review, type: dx

#24966 docs(gatsby): update api-files.md to clarify plugins can implement the same files
  docs/docs/api-files.md
Labels: status: needs docs review, type: dx

#24982 fix(recipe): GitHub Pages - brand names
  packages/gatsby-recipes/recipes/travis-deploy-github-pages.mdx
  packages/gatsby-recipes/src/cli.js
Labels: status: needs docs review, type: dx

#24956 Update index.md with missing word
  docs/blog/2020-06-11-you-belong-here-commitment/index.md
Labels: topic: blogpost

#25015 Start develop proxy before actual develop process
  packages/gatsby/src/commands/develop.ts
Labels: bot: merge on green, topic: cli

#24958 feat(gatsby): allow serving of dotfiles from public folder
  packages/gatsby/src/commands/serve.ts
Labels: topic: cli, type: feature or enhancement

#24750 fix(gatsby-source-filesystem): Update typings for createRemoteFileNode
  packages/gatsby-source-filesystem/index.d.ts
Labels: bot: merge on green, status: needs core review

#24720 chore(gatsby): Add typings for action arrays and thunks
  packages/gatsby/src/redux/index.ts
Labels: status: needs core review, topic: TypeScript migration

#23949 chore: update outdated puppeteer versions
  packages/gatsby-plugin-preload-fonts/package.json
  packages/gatsby-transformer-screenshot/lambda/package.json
Labels: topic: dev tooling, type: chore

#24927 update documentation for PageProps type definition
  packages/gatsby/index.d.ts
Labels: status: needs core review, topic: TypeScript migration, type: bug

#24381 chore(gatsby): convert inference-metadata to typescript
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/inference-metadata.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/schema/infer/inference-metadata.ts
Labels: topic: TypeScript migration

#23991 chore(gatsby): Migrate utils/page-data to TypeScript
  packages/gatsby/src/commands/build-utils.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/utils/page-data.js
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/websocket-manager.ts
  packages/gatsby/src/utils/worker/child.ts
  packages/gatsby/src/utils/worker/page-data.ts
  scripts/check-ts.js
  yarn.lock
Labels: status: needs core review, topic: TypeScript migration

#24259 chore(gatsby): convert schema-customization to typescript
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/schema-customization.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/schema/context.ts
Labels: topic: TypeScript migration

#25034 chore(docs): Update adding-a-list-of-markdown-blog-posts
  docs/docs/adding-a-list-of-markdown-blog-posts.md
Labels: type: documentation

#25042 chore(gatsby): cleanup sift remnants from run-sift.js
  packages/gatsby/src/db/common/__tests__/query.js
  packages/gatsby/src/db/common/query.ts
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/redux/run-sift.js
Labels: bot: merge on green, type: chore

#25046 chore(gatsby): cleanup some sift remnants from tests
  packages/gatsby/src/redux/__tests__/run-sift.js
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/redux/run-sift.js
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/__tests__/run-query.js
Labels: bot: merge on green, type: chore

#25044 fix(gatsby-starter-blog): Move typescript usage to other file
  starters/blog/src/pages/index.js
  starters/blog/src/pages/using-typescript.tsx
Labels: status: needs core review

#24941 refactor(gatsby): convert program reducer to typescript
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/program.js
  packages/gatsby/src/redux/reducers/program.ts
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green, topic: TypeScript migration

#25049 chore(gatsby): remove mentions of sift and refactor
  packages/gatsby/src/db/nodes.js
  packages/gatsby/src/redux/__tests__/run-sift.js
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/redux/run-sift.js
  packages/gatsby/src/schema/__tests__/run-query.js
  packages/gatsby/src/utils/__tests__/__snapshots__/prepare-regex.js.snap
  packages/gatsby/src/utils/__tests__/prepare-regex.js
Labels: bot: merge on green, type: chore

#25045 chore(gatsby): Re-export reporter types from gatsby-cli
  packages/gatsby/index.d.ts
Labels: bot: merge on green, topic: TypeScript migration

#25061 chore(gatsby): remove `sift` as a Gatsby depency
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green, type: chore

#25065 chore(gatsby-cli): delete *.d.ts files before creating new ones
  packages/gatsby-cli/package.json
Labels: topic: TypeScript migration

#25055 chore(gatsby): migrate run-sift to TS
  packages/gatsby/src/db/common/query.ts
  packages/gatsby/src/db/nodes.js
  packages/gatsby/src/redux/__tests__/run-fast-filters.js
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/redux/run-fast-filters.ts
Labels: status: needs core review, topic: TypeScript migration

#25071 chore(CODEOWNERS): define rule for /benchmarks/
  CODEOWNERS
Labels: bot: merge on green, type: maintenance

#24943 maintenance(www): Explicitly type GraphQL fields
  www/gatsby-config.js
  www/gatsby-node.js
  www/src/utils/node/blog.js
  www/src/utils/node/creators.js
  www/src/utils/node/docs.js
  www/src/utils/node/features.js
  www/src/utils/node/packages.js
  www/src/utils/node/showcase.js
  www/src/utils/node/starters.js
Labels: topic: GraphQL, topic: website

#25079 chore(showcase): Add bold.org into showcase
  docs/sites.yml
Labels: topic: showcase

#24808 feat(gatsby): Instrument partial writes to page data
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/query/index.js
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/query/queue.js
  packages/gatsby/src/query/types.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/pending-page-data-writes.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/webpack-status.ts
Labels: bot: merge on green, type: feature or enhancement

#25080 maintenance(www): add environment variables to disable sourcing from docs/plugins
  www/README.md
  www/gatsby-config.js
Labels: topic: website

#25063 perf(gatsby): Lazily re-create GraphQL runner
  packages/gatsby/src/bootstrap/create-graphql-runner.ts
Labels: topic: GraphQL, topic: performance

#24614 fix(gatsby-core-utils): fix hash for buffers
  packages/gatsby-core-utils/src/__tests__/create-content-digest.ts
  packages/gatsby-core-utils/src/create-content-digest.ts
Labels: bot: merge on green, status: needs core review, type: bug

#24740 chore(docs): Update documentation for createNodeField
  packages/gatsby/src/redux/actions/public.js
Labels: bot: merge on green, type: documentation

#24938 fix(gatsby-plugin-offline): versioned import of idb-keyval
  packages/gatsby-plugin-offline/src/gatsby-node.js
  packages/gatsby-plugin-offline/src/sw-append.js
Labels: bot: merge on green, topic: PWA, type: bug

#24940 fix(sw): use NetworkFirst strategy for page-data
  packages/gatsby-plugin-offline/src/gatsby-node.js
Labels: status: awaiting author response, topic: PWA, type: bug
