Repository gatsbyjs/gatsby, pull requests merged in 2020-01, with the labels that each got.

#20315 chore(showcase): Add reeemoter
  docs/creators/creators.yml
  docs/creators/images/ramon-chancay.png
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#20333 chore(showcase): Add borderless
  docs/sites.yml
Labels: topic: showcase

#20322 chore(showcase): Add zatsuzen
  docs/sites.yml
Labels: topic: showcase

#20332 chore(showcase): Add webman.pro
  docs/sites.yml
Labels: topic: showcase

#20401 Update typo from Gatsbyy to Gatsby
  docs/blog/100days/start-blog/index.md
Labels: bot: merge on green, topic: blogpost

#20423 chore(starters): add gatsby-starter-resume-cms
  docs/starters.yml
Labels: bot: merge on green

#20368 chore(showcase): Add PWA Shields
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#20409 chore(showcase): Add Thomas Wang's Blog
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#20424 Add Engleezi site
  docs/sites.yml
Labels: bot: merge on green

#20344 Add some SEO updates to documentation
  docs/docs/seo.md
Labels: type: documentation

#20430 chore(gatsby): bump babel packages
  package.json
  yarn.lock
Labels: bot: merge on green

#20233 webpack glossary/enclyclopedia entry
  docs/docs/glossary.md
  docs/docs/glossary/webpack.md
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green, topic: internal, type: documentation, 🎯 Marketing

#20411 Add Resume Generator Example
  docs/sites.yml
Labels: bot: merge on green

#20452 chore(gatsby): Fix bootstrap CI
  package.json
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.js.snap
Labels: bot: merge on green

#20246 chore(gatsby): Add TS support to eslint and improve speed
  .eslintignore
  .eslintrc.js
  .eslintrc.json
  .gitignore
  package.json
  packages/babel-preset-gatsby-package/__tests__/index.js
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/src/bootstrap/page-hot-reloader.js
  packages/gatsby/src/commands/develop.ts
  yarn.lock
Labels: bot: merge on green, type: maintenance

#20454 chore(gatsby): Prevent eslint from changing type string quotes into backticks
  .eslintrc.js
Labels: bot: merge on green

#20464 chore(github): Disable blank issues and link to Discord and AskGatsbyJS
  .github/ISSUE_TEMPLATE/config.yml
Labels: bot: merge on green, type: maintenance

#20461 chore(showcase): Add Sprucehill
  docs/sites.yml
Labels: bot: merge on green

#20426 Update URL for development dot env file
  docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md
Labels: bot: merge on green

#19847 chore(docs): Fix test ignore patterns
  docs/docs/unit-testing.md
Labels: type: documentation

#20323 chore(showcase): Add Kotoriyama
  docs/sites.yml
Labels: topic: showcase

#20379 chore(showcase): Add ananyaneogi.com
  docs/sites.yml
Labels: bot: merge on green

#20268 chore(showcase): Add bhavaniravi.com
  docs/sites.yml
Labels: topic: showcase

#20470 chore(gatsby-remark-katex): Change to new URL and avoid redirect
  packages/gatsby-remark-katex/README.md
Labels: bot: merge on green

#20392 chore(gatsby-google-tagmanager): Update README
  packages/gatsby-plugin-google-tagmanager/README.md
Labels: bot: merge on green

#20273 chore(showcase): Add Codica
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#20406 chore(showcase): Add Gold Edge Training
  docs/sites.yml
Labels: topic: showcase

#20471 chore(docs): Fix typo in 'eslint-plugin-jsx-a11y'
  docs/docs/making-your-site-accessible.md
Labels: bot: merge on green, type: documentation

#20433 chore(starters): add Felco Gsap
  docs/starters.yml
Labels: bot: merge on green

#20465 docs(pair-programming): Require issue or PR and remove getting started sessions
  docs/contributing/pair-programming.md
Labels: bot: merge on green, type: maintenance

#20407 chore(starters): add gatsby-starter-help-center
  docs/starters.yml
Labels: bot: merge on green

#20478 chore(showcase): Updates according to the validator
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#20360 fix(blog): fixes for the export drupal to gatsby post
  docs/blog/2018-10-26-export-a-drupal-site-to-gatsby/index.md
Labels: bot: merge on green

#20447 Add Rebigulator to Gatsby Showcase
  docs/sites.yml
Labels: topic: showcase

#20480 100DaysOfGatsby - Challenge 2 - Build and Deploy
  docs/blog/100days/free-hosting/index.md
Labels: bot: merge on green, topic: blogpost, 🎯 Marketing

#20314 fix(gatsby-transformer-sharp): define required image fields as non-null in schema
  packages/gatsby-source-contentful/src/extend-node-type.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: bot: merge on green

#20487 chore(docs): fix moment deprecation warning
  docs/blog/100days/free-hosting/index.md
Labels: bot: merge on green

#20383 fix headers and add saved replies references
  docs/contributing/triaging-github-issues/index.md
Labels: type: documentation

#20239 chore: Use createContentDigest helper
  packages/gatsby-plugin-mdx/gatsby/on-create-node.js
  packages/gatsby-plugin-mdx/utils/create-fake-file-node.js
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-theme-blog-core/gatsby-node.js
  packages/gatsby-theme-blog-core/package.json
  yarn.lock
Labels: type: maintenance

#20417 docs: Update gatsby-cli ReadMe for develop PORT env var
  packages/gatsby-cli/README.md
Labels: bot: merge on green, type: documentation

#20466 chore(gatsby-cli): Add notice for Node 8 EOL
  docs/docs/upgrading-node-js.md
  packages/gatsby-cli/src/__tests__/index.js
  packages/gatsby-cli/src/index.ts
Labels: bot: merge on green, type: maintenance

#20503 chore(Doc): What-you-dont-need-plugins-for: Grammar change to aid readability
  docs/docs/what-you-dont-need-plugins-for.md
Labels: bot: merge on green

#20429 fix(netlify-cms-plugin): remove preview styles from global context
  packages/gatsby-plugin-netlify-cms/src/cms.js
Labels: bot: merge on green

#20363 fix(gatsby-remark-autolink-headers): Scroll to document top
  packages/gatsby-remark-autolink-headers/src/gatsby-browser.js
  packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js
Labels: bot: merge on green

#20497 chore(showcase): Add Shivam Sinha portfolio
  docs/sites.yml
Labels: topic: showcase

#20509 fix(babel-preset-gatsby-package): remove node-env check as it's alway…
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/__tests__/index.js
  packages/babel-preset-gatsby-package/index.js
Labels: bot: merge on green

#20508 chore(showcase): Add Monica Powell portfolio
  docs/sites.yml
Labels: bot: merge on green

#20483 chore(showcase): Add kanazawa.js
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#20513 Fixing “100-Day-of-Gatsby” tag to “100-Days-of-Gatsby” on Challenge 1
  docs/blog/100days/start-blog/index.md
Labels: bot: merge on green, topic: blogpost, 🎯 Marketing

#18079 feat(gatsby-source-wordpress): add normalizers option to modify normalizers
  packages/gatsby-source-wordpress/README.md
  packages/gatsby-source-wordpress/src/gatsby-node.js
Labels: topic: WordPress

#20369 feat(gatsby): Supports multiple development proxies
  docs/docs/api-proxy.md
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/joi-schemas/joi.js
Labels: bot: merge on green, type: feature or enhancement

#20522 chore (doc): Update overview-of-the-gatsby-build-process.md
  docs/docs/overview-of-the-gatsby-build-process.md
Labels: bot: merge on green

#20400 docs(writing-documentation-with-docz): Update guide to fix dependencies
  docs/tutorial/writing-documentation-with-docz.md
Labels: bot: merge on green, type: documentation

#20517 fix(gatsby): fix error cannot read referencePath of undefined
  packages/gatsby/src/utils/api-runner-error-parser.js
  packages/gatsby/src/utils/api-runner-node.js
Labels: bot: merge on green

#20553 Fix link to Carbon Design System in documentation
  docs/docs/component-libraries.md
Labels: bot: merge on green

#20499 chore(showcase): Add Nathaniel Ryan Mathew portfolio
  docs/sites.yml
Labels: topic: showcase

#20476 Chore: Updates starters.yml
  docs/starters.yml
Labels: topic: showcase

#20541 chore(docs): Remove whitespace from Markdown link
  docs/docs/what-you-dont-need-plugins-for.md
Labels: type: documentation

#20537 Added Solfej Chord Search To Showcase
  docs/sites.yml
Labels: topic: showcase

#20555 chore(showcase): Add erichowey.dev
  docs/sites.yml
Labels: topic: showcase

#20556 chore(showcase): Add briannasharpe.com
  docs/sites.yml
Labels: topic: showcase

#20519 chore(blog): add tags for 100days
  docs/blog/100days/free-hosting/index.md
  docs/blog/100days/index.md
  docs/blog/100days/start-blog/index.md
  www/src/data/tags-docs.js
Labels: bot: merge on green, status: awaiting reviewer response

#20578 Add ZEIT Now
  docs/blog/100days/free-hosting/index.md
Labels: bot: merge on green, topic: blogpost

#20551 Add dataLayerName check before push in event.
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-browser.js
Labels: bot: merge on green

#20584 Add challenge 3 of 100DaysOfGatsby
  docs/blog/100days/gatsby-image/index.md
Labels: bot: merge on green, topic: blogpost

#20566 docs: improve gatsby-plugin-offline SSR seo
  docs/docs/seo.md
  packages/gatsby-plugin-offline/README.md
Labels: type: documentation

#20520 fix(docs): improve WordPress tutorial
  docs/tutorial/wordpress-source-plugin-tutorial.md
  examples/using-wordpress/README.md
  examples/using-wordpress/gatsby-config.js
  packages/gatsby-source-wordpress/README.md
Labels: type: documentation

#20589 refactor(gatsby-plugin-netlify-cms) preview styles during development using MiniCssExtractPlugin and HMR
  packages/gatsby-plugin-netlify-cms/src/cms.js
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
Labels: bot: merge on green

#20605 perf(gatsby): Use a Map instead of Object for job id lookups
  packages/gatsby/src/query/query-runner.js
Labels: bot: merge on green

#20607 chore(gatsby): Minor refactor in runQuery
  packages/gatsby/src/schema/node-model.js
Labels: bot: merge on green

#20606 perf(gatsby): Create one promise per queue, not one per job
  packages/gatsby/src/query/queue.js
Labels: bot: merge on green

#20398 fix(gatsby-source-contentful): LongText fields require markdown transformer
  packages/gatsby-source-contentful/README.md
Labels: type: documentation

#20612 gatsby-source-shopify Update API version to 2019 07
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/__tests__/fixtures/articles.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/blogs.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/collections.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/products.json
  packages/gatsby-source-shopify/src/create-client.js
  packages/gatsby-source-shopify/src/gatsby-node.js
  packages/gatsby-source-shopify/src/queries.js
Labels: bot: merge on green

#20511 Update index.md
  docs/tutorial/part-one/index.md
Labels: type: documentation

#20457 chore(gatsby): Begin typing the redux code
  jest-transformer.js
  jest.config.js
  package.json
  packages/gatsby-plugin-sitemap/src/__tests__/gatsby-node.js
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/redux/actions/add-page-dependency.js
  packages/gatsby/src/redux/actions/index.js
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/persist.js
  packages/gatsby/src/redux/persist.ts
  packages/gatsby/src/redux/types.ts
  yarn.lock
Labels: type: maintenance

#20550 chore(docs): Add note about `sourceInstanceName`
  docs/docs/sourcing-from-the-filesystem.md
Labels: type: documentation

#20625 fix(gatsby-plugin-sitemap): allow paths with trailing slash in `exclude` option
  packages/gatsby-plugin-sitemap/README.md
  packages/gatsby-plugin-sitemap/src/__tests__/internals.js
  packages/gatsby-plugin-sitemap/src/internals.js
Labels: bot: merge on green

#20629 Makes the ESLint configuration work regardless of the hoisting
  packages/gatsby/src/utils/eslint-config.js
Labels: bot: merge on green

#20456 Docs / Encyclopedia: Adds JAMStack entry.
  docs/docs/glossary.md
  docs/docs/glossary/jamstack.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, 🎯 Marketing

#20540 Update accessibility user testing post
  docs/blog/2019-07-11-user-testing-accessible-client-routing/index.md
Labels: topic: blogpost

#20640 fix: npm permissions check
  scripts/check-publish-access/index.js
  scripts/get-unowned-packages/index.js
Labels: bot: merge on green

#20376 Docs/Creating Nested Layout Components - Changed provided picture so it matches styles from following the tutorial
  docs/tutorial/part-three/index.md
Labels: type: documentation

#20648 Update seo.md
  docs/docs/seo.md
Labels: bot: merge on green

#20347 chore(docs): Add Stripe reference guide
  docs/docs/process-payments-with-stripe.md
  www/src/data/sidebars/doc-links.yaml
Labels: bot: merge on green, type: documentation

#20632 docs(gatsby-theme-blog): Include Blog Post Fields
  packages/gatsby-theme-blog/README.md
Labels: bot: merge on green, type: documentation

#20633 docs(gatsby-theme-blog-core): include Blog Post Fields
  packages/gatsby-theme-blog-core/README.md
Labels: type: documentation

#20662 fix(gatsby): Respect `@dontInfer` directive on `SitePage` type
  packages/gatsby/src/redux/reducers/inference-metadata.js
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
Labels: bot: merge on green

#20667 fix(blog): fix links to .com site
  docs/blog/2020-01-15-website-uptime/index.md
Labels: bot: merge on green

#20669 fix: typo in docs (docs/static-vs-normal-queries)
  docs/docs/static-vs-normal-queries.md
Labels: bot: merge on green

#20673 fix(blog): Fix date in website uptime article
  docs/blog/2020-01-15-website-uptime/index.md
Labels: bot: merge on green, topic: blogpost

#20477 perf(gatsby): cache parsing and validation results in graphql-runner
  packages/gatsby/src/bootstrap/__tests__/graphql-runner.js
  packages/gatsby/src/query/graphql-runner.js
Labels: bot: merge on green

#20515 docs(porting-from-create-react-app-to-gatsby): Add `sessionStorage` to list of common globals
  docs/docs/porting-from-create-react-app-to-gatsby.md
Labels: type: documentation

#20616 Docs: Update shadowing other themes
  docs/docs/themes/shadowing.md
Labels: type: documentation

#20650 fix(blog): broken link
  docs/blog/100days/gatsby-image/index.md
Labels: bot: merge on green, topic: blogpost

#20715 chore(showcase): Add krishnagopinath portfolio site to Showcase
  docs/sites.yml
Labels: topic: showcase

#20679 Update styling-css.md
  docs/docs/recipes/styling-css.md
Labels: type: documentation

#20713 Add site kodingnesia to showcase
  docs/sites.yml
Labels: topic: showcase

#20675 chore(starters): add gatsby-starter-material-emotion
  docs/starters.yml
Labels: topic: showcase

#19940 feat(gatsby-plugin-sharp): move to jobs-api v2
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/process-file.js.snap
  packages/gatsby-plugin-sharp/src/__tests__/gatsby-worker.js
  packages/gatsby-plugin-sharp/src/__tests__/index.js
  packages/gatsby-plugin-sharp/src/__tests__/process-file.js
  packages/gatsby-plugin-sharp/src/__tests__/scheduler.js
  packages/gatsby-plugin-sharp/src/__tests__/worker.js
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-plugin-sharp/src/gatsby-worker.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/plugin-options.js
  packages/gatsby-plugin-sharp/src/process-file.js
  packages/gatsby-plugin-sharp/src/scheduler.js
  packages/gatsby-plugin-sharp/src/sharp-error.js
  packages/gatsby-plugin-sharp/src/worker.js
  yarn.lock
Labels: topic: images/media

#20744 fix(gatsby): use slash from gatsby-core-utils
  packages/gatsby/src/utils/__tests__/jobs-manager.js
  packages/gatsby/src/utils/jobs-manager.js
Labels: bot: merge on green

#20731 feat(gatsby-source-graphql) Execute functions in header.
  packages/gatsby-source-graphql/README.md
  packages/gatsby-source-graphql/src/gatsby-node.js
Labels: bot: merge on green

#20570 feat(gatsby-plugin-google-analytics) Pass additional props to the <OutboundLink>
  packages/gatsby-plugin-google-analytics/src/index.js
Labels: bot: merge on green

#20750 make sure to throw proper errors
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  scripts/gatsby-plugin-checker/index.js
Labels: bot: merge on green

#20521 feat(gatsby-source-lever): use schema customization API (#20069)
  packages/gatsby-source-lever/src/gatsby-node.js
Labels: bot: merge on green

#20752 chore(showcase): labelmake.jp to sites.yml
  docs/sites.yml
Labels: topic: showcase

#20721 fix(blog): fix broken bitly link to kontent/kentico
  docs/blog/2018-12-19-kentico-cloud-and-gatsby-take-you-beyond-static-websites/index.md
Labels: bot: merge on green, type: documentation

#20637 feat(www): Pull in translated gatsby docs (ENABLE_LOCALIZATIONS env var needed)
  www/README.md
  www/gatsby-config.js
  www/gatsby-node.js
  www/i18n.json
  www/package.json
  www/src/components/docs-breadcrumb.js
  www/src/components/layout.js
  www/src/components/localized-link.js
  www/src/components/mdx-link.js
  www/src/components/navigation.js
  www/src/components/prev-and-next.js
  www/src/components/site-metadata.js
  www/src/gatsby-plugin-theme-ui/components.js
  www/src/templates/template-docs-markdown.js
  www/src/utils/i18n.js
  www/src/utils/sidebar/create-link.js
Labels: topic: i18n

#20791 Removed unnecessary component state, used props instead
  docs/blog/2017-10-17-building-i18n-with-gatsby/index.md
Labels: bot: merge on green

#20781 fix: remove 1px line from gatsby-announcer on 100vh pages
  packages/gatsby/cache-dir/navigation.js
Labels: bot: merge on green

#20798 chore(gatsby): Deregister all events to the queue after batch
  packages/gatsby/src/query/queue.js
Labels: bot: merge on green

#20804 chore(showcase): Add Adam bowen personal website to showcase
  docs/sites.yml
Labels: topic: showcase

#20757 fix(chore): remove processing and waiting queue
  packages/gatsby/src/query/queue.js
Labels: bot: merge on green

#20817 chore(doc): Listing new gatsby theme recipe on recipes landing page
  docs/docs/recipes.md
Labels: type: documentation

#20800 (blog) Add challenge 4 of #100DaysOfGatbsy
  docs/blog/100days/react-component/index.md
Labels: bot: merge on green, topic: blogpost

#20751 Curology site submission
  docs/sites.yml
Labels: topic: showcase

#20836 fix(gatsby): revert #19664 fix duplicate runs in develop mode
  packages/gatsby/src/utils/api-runner-node.js
Labels: bot: merge on green

#20660 Docs/Glossary: Headless CMS entry
  docs/docs/glossary.md
  docs/docs/glossary/headless-cms.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal, 🎯 Marketing

#20792 chore(showcase): Add Maarten Afink portfolio site to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#20720 chore: add inline codeblocks around some text for readability
  docs/docs/bulma.md
  docs/docs/post-css.md
  docs/docs/tailwind-css.md
Labels: type: documentation

#20639 Added LBI Financial to the showcase
  docs/sites.yml
Labels: topic: showcase

#20835 feat(gatsby): enable external jobs with ipc
  packages/gatsby/ipc.json
  packages/gatsby/src/utils/__tests__/jobs-manager.js
  packages/gatsby/src/utils/jobs-manager.js
Labels: bot: merge on green

#20827 Site Showcase submission request
  docs/sites.yml
Labels: topic: showcase

#20814 Adds a blog post on why TypeScript is using Gatsby
  docs/blog/2020-01-23-why-typescript-chose-gatsby/index.md
  docs/blog/author.yaml
  docs/blog/avatars/orta-therox.jpg
Labels: bot: merge on green, topic: blogpost

#20857 Add jellypepper.com to showcase
  docs/sites.yml
Labels: topic: showcase

#20868 fixed a typo
  docs/docs/glossary/headless-cms.md
Labels: type: documentation

#20856 Add miyamadojinja.com to the showcase
  docs/sites.yml
Labels: topic: showcase

#20891 chore(starters): Update deps
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/default/package-lock.json
  starters/default/package.json
  starters/gatsby-starter-blog-theme-core/package-lock.json
  starters/gatsby-starter-blog-theme-core/package.json
  starters/gatsby-starter-blog-theme/package-lock.json
  starters/gatsby-starter-blog-theme/package.json
  starters/gatsby-starter-notes-theme/package-lock.json
  starters/gatsby-starter-notes-theme/package.json
  starters/gatsby-starter-theme-workspace/example/package.json
  starters/gatsby-starter-theme/package-lock.json
  starters/gatsby-starter-theme/package.json
  starters/hello-world/package-lock.json
  starters/hello-world/package.json
Labels: bot: merge on green

#20583 Git workflow post
  docs/blog/2020-01-08-git-workflows/1-initial.svg
  docs/blog/2020-01-08-git-workflows/2-additional-work.svg
  docs/blog/2020-01-08-git-workflows/3-rebased.svg
  docs/blog/2020-01-08-git-workflows/4-merge-commit.svg
  docs/blog/2020-01-08-git-workflows/5-more-incremental.svg
  docs/blog/2020-01-08-git-workflows/6-actual-git.svg
  docs/blog/2020-01-08-git-workflows/7-parallel-universes.svg
  docs/blog/2020-01-08-git-workflows/8-double-work.svg
  docs/blog/2020-01-08-git-workflows/base-github.png
  docs/blog/2020-01-08-git-workflows/index.md
  docs/blog/2020-01-08-git-workflows/merge.png
  docs/blog/2020-01-08-git-workflows/rebase-and-merge.png
  docs/blog/author.yaml
  docs/blog/avatars/josh-comeau.jpg
  www/src/components/breakout.js
  www/src/components/visually-hidden.js
  www/src/gatsby-plugin-theme-ui/components.js
  www/src/templates/template-blog-post.js
  www/src/utils/styles/index.js
Labels: bot: merge on green, topic: blogpost

#20864 chore(github-actions): Update dependencies
  .github/actions/gatsby-site-showcase-validator/package.json
  .github/actions/high-priority-prs/package.json
  .github/actions/high-priority-prs/src/__tests__/__snapshots__/process-data.js.snap
  .github/actions/high-priority-prs/src/pr-message.js
  .github/actions/high-priority-prs/src/process-data.js
Labels: bot: merge on green

#20142 fix(gatsby-plugin-manifest): fixes icons not getting asset prefix
  packages/gatsby-plugin-manifest/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  yarn.lock
Labels: topic: plugins, type: bug

#20905 fix(gatsby-plugin-sharp): add output file cache back for non job api
  packages/gatsby-plugin-sharp/src/scheduler.js
Labels: bot: merge on green

#20655 chore(starters): add gatsby-bootstrap-italia-starter
  docs/starters.yml
Labels: bot: merge on green, topic: showcase

#20877 Add calisthenics skills to showcase
  docs/sites.yml
Labels: topic: showcase

#20904 fix: wrap `GraphQLRunner.query` return in Promise.resolve
  packages/gatsby/src/query/graphql-runner.js
Labels: bot: merge on green

#20240 Added source guide for Seams-CMS
  docs/docs/headless-cms.md
  docs/docs/sourcing-from-seams-cms.md
Labels: bot: merge on green, type: documentation

#20910 chore(www): Add labels on TypeScript and TSX code blocks
  www/src/utils/styles/global.js
Labels: bot: merge on green, topic: blogpost

#20909 fix(gatsby): structured error might be a string
  packages/gatsby/src/utils/api-runner-error-parser.js
Labels: bot: merge on green

#20908 chore: sync gatsby deps in starters to latest
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/default/package-lock.json
  starters/default/package.json
  starters/gatsby-starter-blog-theme-core/package-lock.json
  starters/gatsby-starter-blog-theme-core/package.json
  starters/gatsby-starter-blog-theme/package-lock.json
  starters/gatsby-starter-blog-theme/package.json
  starters/gatsby-starter-notes-theme/package-lock.json
  starters/gatsby-starter-notes-theme/package.json
  starters/gatsby-starter-theme-workspace/example/package.json
  starters/gatsby-starter-theme/package-lock.json
  starters/gatsby-starter-theme/package.json
  starters/hello-world/package-lock.json
  starters/hello-world/package.json
Labels: bot: merge on green

#20879 fix(gatsby-plugin-mdx): Pass node API helpers from onCreateNode and sourceNodes to remark plugins
  packages/gatsby-plugin-mdx/gatsby/on-create-node.js
  packages/gatsby-plugin-mdx/gatsby/source-nodes.js
  packages/gatsby-plugin-mdx/utils/gen-mdx.js
  packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js
Labels: topic: MDX

#20921 feat(www): update gatsby-remark-embedder & replace GIPHY embeds
  docs/blog/2017-11-09-why-i-created-my-blog-with-gatsby-and-contentful/index.md
  docs/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/index.md
  docs/blog/2018-2-7-jam-out-your-blog/index.md
  docs/blog/2019-04-26-how-to-build-a-blog-with-wordpress-and-gatsby-part-1/index.md
  docs/blog/2019-04-30-how-to-build-a-blog-with-wordpress-and-gatsby-part-2/index.md
  docs/blog/2019-05-02-how-to-build-a-blog-with-wordpress-and-gatsby-part-3/index.md
  docs/blog/2019-08-14-strivectin-case-study/index.md
  www/package.json
Labels: bot: merge on green

#20924 chore: don't build gatsbyjs.org on CircleCI
  .circleci/config.yml
Labels: bot: merge on green

#20742 docs(sourcing-from-netlify-cms): absolute path for public folder
  docs/docs/sourcing-from-netlify-cms.md
Labels: bot: merge on green

#20936 fix(gatsby): Fix stack overflow on queries with circular fragments
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/query-compiler.js
Labels: bot: merge on green

#20535 chore(gatsby): convert build-html to typescript
  package.json
  packages/gatsby/src/commands/build-html.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.js
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/persist.ts
  packages/gatsby/src/redux/types.ts
  yarn.lock
Labels: bot: merge on green, type: maintenance

#20882 chore(starters): gatsby-london-night-and-day
  docs/starters.yml
Labels: bot: merge on green

#20922 fix failing starter tags
  docs/starters.yml
Labels: bot: merge on green

#20950 chore(blog): fix Markdown syntax
  docs/blog/2020-01-27-announcing-gatsby-builds-and-reports/index.md
Labels: bot: merge on green, topic: blogpost

#20865 [benchmarks] Update dependencies
  benchmarks/create-pages/package.json
  benchmarks/image-processing/.prettierignore
  benchmarks/image-processing/.prettierrc
  benchmarks/image-processing/package.json
  benchmarks/markdown_id/.prettierignore
  benchmarks/markdown_id/.prettierrc
  benchmarks/markdown_id/package.json
  benchmarks/markdown_slug/.prettierignore
  benchmarks/markdown_slug/.prettierrc
  benchmarks/markdown_slug/package.json
  benchmarks/markdown_table/package.json
  benchmarks/plugin-manifest/package.json
  benchmarks/query/package.json
Labels: bot: merge on green

#20980 fix(gatsby): Do not add field `id` to the query when `id` alias exists
  packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/query-compiler.js
Labels: bot: merge on green

#20951 refactor(gatsby): Add built-in GraphQL type for SitePage
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
  packages/gatsby/src/schema/types/built-in-types.js
Labels: bot: merge on green
