Repository gatsbyjs/gatsby, pull requests merged in 2020-05, with the labels that each got.

#21815 refactor(www): Create PageMetadata component
  www/package.json
  www/src/components/__tests__/blog-post-metadata.js
  www/src/components/__tests__/page-metadata.js
  www/src/components/__tests__/site-metadata.js
  www/src/components/blog-post-metadata.js
  www/src/components/guidelines/layout.js
  www/src/components/package-readme.js
  www/src/components/page-metadata.js
  www/src/components/showcase-details.js
  www/src/components/site-metadata.js
  www/src/hooks/use-site-metadata.js
  www/src/pages/blog/tags.js
  www/src/pages/ecosystem.js
  www/src/pages/features.js
  www/src/pages/index.js
  www/src/pages/plugins.js
  www/src/templates/__tests__/template-starter-page.js
  www/src/templates/tags.js
  www/src/templates/template-api-markdown.js
  www/src/templates/template-blog-list.js
  www/src/templates/template-blog-post.js
  www/src/templates/template-contributor-page.js
  www/src/templates/template-creator-details.js
  www/src/templates/template-docs-markdown.js
  www/src/templates/template-feature-comparison.js
  www/src/templates/template-starter-page.js
  www/src/views/creators/index.js
  www/src/views/showcase/index.js
  www/src/views/starter-library/index.js
Labels: topic: website

#23209 enhancement (docs, www): MDX component alias
  docs/blog/100days/index.md
  docs/blog/2018-08-01-partner-program/index.md
  docs/blog/2018-10-11-rise-of-modern-web-development/index.md
  docs/blog/2018-10-16-why-mobile-performance-is-crucial/index.md
  docs/blog/2020-01-08-git-workflows/index.md
  docs/blog/2020-03-09-gatsby-and-jsparty-podcast/index.md
  docs/contributing/community.md
  docs/contributing/docs-and-blog-components.md
  docs/contributing/events.md
  docs/contributing/index.md
  docs/contributing/stub-list.md
  docs/contributing/translation/index.md
  docs/docs/data-fetching.md
  docs/docs/glossary.md
  docs/docs/index.md
  docs/docs/using-gatsby-image.md
  www/gatsby-config.js
  www/package.json
  www/src/gatsby-plugin-theme-ui/components.js
Labels: topic: i18n

#23248 refactor(www): refactor and simplify the sidebar
  www/src/components/docs-breadcrumb.js
  www/src/components/sidebar/__tests__/sidebar.js
  www/src/components/sidebar/accordion.js
  www/src/components/sidebar/item-link.js
  www/src/components/sidebar/item.js
  www/src/components/sidebar/section-title.js
  www/src/components/sidebar/sidebar.js
  www/src/utils/sidebar/get-active-item-parents.js
Labels: topic: i18n, topic: website

#23661 Missing comma in gatsby-transformer-remark README
  packages/gatsby-transformer-remark/README.md
Labels: status: triage needed

#23674 Add gatsby-plugin-eslint to eslint recipe so warnings/errors will print to CLI Learned this was necessary from this issue https://github.com/gatsbyjs/gatsby/issues/23666
  packages/gatsby-recipes/recipes/eslint.mdx
Labels: bot: merge on green, topic: recipes

#23665 add Storybook (js) to recipes
  packages/gatsby-recipes/recipes/storybook-js.mdx
  packages/gatsby-recipes/src/cli.js
Labels: topic: recipes

#23685 chore(doc):Re-record Quick Start video to not reference npx, and remove note on doc
  docs/docs/quick-start.md
Labels: type: documentation

#23693 chore(docs): fix incorrect syntaxis on examples
  docs/blog/2017-10-16-making-website-building-fun/index.md
  docs/blog/2018-06-08-life-after-layouts/index.md
  docs/blog/2019-02-26-getting-started-with-gatsby-themes/index.md
  docs/blog/2019-07-02-extending-components/index.md
  docs/contributing/how-to-write-a-recipe.md
  docs/contributing/translation/style-guide.md
  docs/docs/adding-react-components.md
  docs/docs/creating-prefixed-404-pages-for-different-languages.md
  docs/docs/css-modules.md
  docs/docs/emotion.md
  docs/docs/graphql-concepts.md
  docs/docs/layout-components.md
  docs/docs/linking-between-pages.md
  docs/docs/mdx/importing-and-using-components.md
  docs/docs/mdx/writing-pages.md
  docs/docs/migrating-from-v1-to-v2.md
  docs/docs/porting-an-html-site-to-gatsby.md
  docs/docs/recipes/pages-layouts.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/recipes/styling-css.md
  docs/docs/recipes/working-with-images.md
  docs/docs/static-query.md
  docs/docs/styled-components.md
  docs/docs/themes/shadowing.md
  docs/docs/using-gatsby-without-graphql.md
  docs/docs/working-with-video.md
  docs/tutorial/authentication-tutorial.md
  docs/tutorial/part-four/index.md
  docs/tutorial/part-one/index.md
  docs/tutorial/part-three/index.md
  docs/tutorial/part-two/index.md
  docs/tutorial/using-a-theme.md
  docs/tutorial/using-multiple-themes-together.md
Labels: status: need docs review, status: triage needed, type: documentation

#23726 Revert "feat(gatsby-transformer-remark, gatsby-plugin-mdx) Make timeT…
  packages/gatsby-plugin-mdx/README.md
  packages/gatsby-plugin-mdx/gatsby/source-nodes.js
  packages/gatsby-transformer-remark/README.md
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
  packages/gatsby-transformer-remark/src/utils/time-to-read.js
Labels: bot: merge on green

#23727 chore: fix starters-publish in ci
  .circleci/config.yml
Labels: status: triage needed

#23657 chore(stale): add "status: triage needed" to exempt labels
  .github/workflows/schedule-stale.yml
Labels: status: need core review, type: maintenance

#23716 chore(gatsby): migrate themes reducer to TypeScript
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/themes.js
  packages/gatsby/src/redux/reducers/themes.ts
  packages/gatsby/src/redux/types.ts
Labels: status: triage needed, type: TypeScript migration

#23658 fix(gatsby): Fix dirty check for schema rebuilding
  packages/gatsby/src/schema/infer/__tests__/inference-metadata.ts
  packages/gatsby/src/schema/infer/inference-metadata.ts
Labels: bot: merge on green, topic: GraphQL

#23732 test(e2e_tests_pnp): check if test should run
  .circleci/config.yml
Labels: type: maintenance

#23731 (chore) Update Hashim's description
  docs/blog/author.yaml
Labels: topic: blogpost

#23743 fix(gatsby-plugin-netlify): Fix heuristic for appending redirects
  packages/gatsby-plugin-netlify/src/create-redirects.js
Labels: bot: merge on green

#23752 chore(lint-staged): add `.ts(x)` files to rule running `eslint --fix`
  package.json
Labels: bot: merge on green, type: chore

#23620 fix(gatsby): log config validation errors
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/redux/actions/__tests__/internal.ts
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/reducers/__tests__/__snapshots__/config.js.snap
  packages/gatsby/src/redux/reducers/__tests__/config.js
  packages/gatsby/src/redux/reducers/config.js
  packages/gatsby/src/redux/reducers/config.ts
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green

#23700 chore: update `@mdx-js` deps
  benchmarks/mdx/package.json
  examples/recipes-gatsby-image/package.json
  examples/using-MDX/package.json
  examples/using-i18n/package.json
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-recipes/package.json
  packages/gatsby-theme-blog-core/package.json
  packages/gatsby-theme-blog/package.json
  packages/gatsby-theme-notes/package.json
  starters/gatsby-starter-blog-theme-core/package-lock.json
  starters/gatsby-starter-blog-theme-core/package.json
  www/package.json
  yarn.lock
Labels: topic: MDX, type: maintenance

#23702 chore(showcase): Removing more sites from the showcase
  docs/sites.yml
Labels: topic: showcase

#23739 chore(gatsby): migrate themes reducer to TypeScript
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green

#23735 corrected a typo
  docs/docs/creating-and-modifying-pages.md
Labels: bot: merge on green

#23644 chore(showcase): Update URL for a+ Saúde
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#23609 fix(babel-preset-gatsby): remove prop-types in production for dependencies
  packages/babel-preset-gatsby/src/dependencies.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
  packages/gatsby/src/utils/webpack-utils.ts
Labels: bot: merge on green

#23631 chore(showcase): add St. Jude Cloud to showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#23494 chore(showcase): add www.svgtopng.me
  docs/sites.yml
Labels: topic: showcase

#23568 Add Resistbot to Site Showcase
  docs/sites.yml
Labels: topic: showcase

#23238 add gatsby-typescript-material-starter
  docs/starters.yml
Labels: topic: showcase

#23757 Add featured image
  packages/gatsby-theme-blog-core/gatsby-node.js
  packages/gatsby-theme-blog-core/src/templates/post-query.js
  packages/gatsby-theme-blog/src/components/post-hero.js
  packages/gatsby-theme-blog/src/components/post.js
Labels: topic: themes

#23144 Create new gatsby-theme-ui-preset theme
  packages/gatsby-theme-blog/src/gatsby-plugin-theme-ui/components.js
  packages/gatsby-theme-ui-preset/README.md
  packages/gatsby-theme-ui-preset/gatsby-config.js
  packages/gatsby-theme-ui-preset/index.js
  packages/gatsby-theme-ui-preset/package.json
  packages/gatsby-theme-ui-preset/src/gatsby-plugin-theme-ui/colors.js
  packages/gatsby-theme-ui-preset/src/gatsby-plugin-theme-ui/index.js
  packages/gatsby-theme-ui-preset/src/gatsby-plugin-theme-ui/prism.js
  packages/gatsby-theme-ui-preset/src/gatsby-plugin-theme-ui/styles.js
  packages/gatsby-theme-ui-preset/src/gatsby-plugin-theme-ui/typography.js
Labels: topic: themes

#22458 chore(babel-plugin-remove-graphql-queries): Convert murmur.js
  packages/babel-plugin-remove-graphql-queries/package.json
  packages/babel-plugin-remove-graphql-queries/src/index.js
  packages/babel-plugin-remove-graphql-queries/src/murmur.ts
Labels: type: TypeScript migration

#23695 chore(gatsby): convert build to typescript
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop.ts
Labels: bot: merge on green, status: inkteam assigned, type: TypeScript migration

#23656 chore(gatsby): jaeger-local to TypeScript
  package.json
  packages/gatsby/src/utils/tracer/jaeger-local.ts
  yarn.lock
Labels: status: need core review, type: TypeScript migration

#23754 chore(gatsby): specify the type of store
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/utils/websocket-manager.ts
Labels: type: TypeScript migration

#23738 chore(gatsby): migrate pageData reducer to TypeScript
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/page-data.ts
  packages/gatsby/src/redux/types.ts
Labels: type: TypeScript migration

#23758 fix(i18n/update-source): handle single quotes in commit messages
  scripts/i18n/update-source.js
Labels: type: chore

#23779 fix(www): update jsdoc source for actions after typescript migration
  docs/docs/actions.md
Labels: type: documentation

#23764 (blog) Add Gatsby Cloud callout
  docs/blog/2020-04-29-incredimental-builds/index.md
Labels: bot: merge on green, topic: blogpost

#23782 Bump up graphql-request version to fix deprecation notices
  www/package.json
Labels: topic: website, type: maintenance

#23591 chore(gatsby): migrate schema reducer to TypeScript
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/schema.js
  packages/gatsby/src/redux/reducers/schema.ts
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green, type: TypeScript migration

#23766 Adjust blog title to boost SEO
  docs/blog/2020-04-29-incredimental-builds/index.md
Labels: topic: blogpost

#23774 chore(showcase): added www.prtdomingo.com to sites.yml showcase
  docs/sites.yml
Labels: topic: showcase

#23775 docs: clarify Tutorial Part 7
  docs/tutorial/part-seven/index.md
Labels: type: documentation

#23780 chore(starters): Add gatsby-ghost-balsa-starter to starters
  docs/starters.yml
Labels: topic: showcase

#23788 docs: fix a typo in a Markdown link
  docs/docs/performance.md
Labels: status: triage needed

#23787 Variable excerpt length
  packages/gatsby-theme-blog-core/gatsby-node.js
  packages/gatsby-theme-blog-core/utils/default-options.js
Labels: topic: themes

#23786 Add separate social image field
  packages/gatsby-theme-blog-core/gatsby-node.js
  packages/gatsby-theme-blog-core/src/templates/post-query.js
  packages/gatsby-theme-blog/README.md
  packages/gatsby-theme-blog/src/components/post.js
Labels: topic: themes

#22530 chore(gatsby): Convert redirects-writer to typescript
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/bootstrap/redirects-writer.ts
Labels: type: TypeScript migration

#23783 add buttercms blog post
  docs/blog/2020-05-05-Butter-CMS-case-study/car_loans_canada_web.png
  docs/blog/2020-05-05-Butter-CMS-case-study/index.md
  docs/blog/author.yaml
  docs/blog/avatars/jake-lumetta.jpg
Labels: bot: merge on green, topic: blogpost

#23332 chore(gatsby): Migrate query/redirects-writer to Typescript
  packages/gatsby/src/query/redirects-writer.ts
Labels: bot: merge on green, type: TypeScript migration

#23677 Convert prefer-default and log-line-function to TS
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/bootstrap/load-themes/index.js
  packages/gatsby/src/bootstrap/log-line-function.js
  packages/gatsby/src/bootstrap/log-line-function.ts
  packages/gatsby/src/bootstrap/prefer-default.js
  packages/gatsby/src/bootstrap/prefer-default.ts
  packages/gatsby/src/commands/serve.ts
Labels: status: need core review, type: TypeScript migration

#23807 Update blog start link to resolve cors
  benchmarks/markdown_id/gatsby-config.js
  benchmarks/markdown_slug/gatsby-config.js
  docs/docs/gatsby-repl.md
  docs/docs/starters.md
  docs/starters.yml
  starters/README.md
  starters/blog/gatsby-config.js
Labels: status: triage needed

#23431 Glossary, encyclopedia: Add Infrastructure As Code article.
  docs/docs/glossary.md
  docs/docs/glossary/infrastructure-as-code/index.md
  docs/docs/glossary/infrastructure-as-code/recipes-screenshot.png
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal

#23811 fix(gatsby-recipes): Fix gatsby config all function
  packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap
  packages/gatsby-recipes/src/providers/gatsby/plugin.js
  packages/gatsby-recipes/src/providers/gatsby/plugin.test.js
Labels: topic: recipes

#23717 chore(gatsby): Convert pagination to TypeScript
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/pagination.js
  packages/gatsby/src/schema/types/pagination.ts
Labels: type: TypeScript migration

#23810 chore(source-wikipedia): ugrade dependencies
  packages/gatsby-source-wikipedia/package.json
  packages/gatsby-source-wikipedia/src/fetch.js
Labels: status: inkteam assigned, type: chore

#23649 chore(docs): Updated read-me with punctuation where necessary
  packages/gatsby-image/README.md
Labels: type: documentation

#23805 chore(source-wikipedia): remove unneeded file
  packages/gatsby-source-wikipedia/src/.gitkeep
Labels: status: inkteam assigned, type: chore

#23546 feat(gatsby-transform-remark): populate id to headings from markdownAST
  packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/create-schema-customization.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
  packages/gatsby-transformer-remark/src/utils/get-heading-id.js
Labels: bot: merge on green

#21626 chore(gatsby-react-router-scroll): Remove legacy context
  packages/gatsby-react-router-scroll/package.json
  packages/gatsby-react-router-scroll/src/ScrollBehaviorContext.js
  packages/gatsby-react-router-scroll/src/ScrollContainer.js
Labels: breaking change

#22731 fix(gatsby-plugin-styletron): Styletron to peerDependencies
  packages/gatsby-plugin-styletron/README.md
  packages/gatsby-plugin-styletron/package.json
Labels: breaking change

#23826 chore(benchmark-wordpress): Reuse existing BENCHMARK_WPGRAPHQL_URL env variable
  benchmarks/source-wordpress/README.md
  benchmarks/source-wordpress/scripts/data-update.js
  benchmarks/source-wordpress/scripts/updater.js
Labels: bot: merge on green

#23618 feat(gatsby/dev-404-page): support reading and writing filter to `?filter` query string
  packages/gatsby/package.json
  packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js
Labels: bot: merge on green

#23688 Convert api-browser and api-node docs to TS
  docs/docs/browser-apis.md
  docs/docs/node-apis.md
  packages/gatsby/scripts/output-api-file.js
  packages/gatsby/src/bootstrap/load-plugins/index.js
  packages/gatsby/src/utils/api-browser-docs.ts
  packages/gatsby/src/utils/api-node-docs.ts
Labels: status: inkteam assigned, type: TypeScript migration

#23781 chore(starters): Add gatsby-wordpress-balsa-starter to starters
  docs/starters.yml
Labels: status: awaiting author response, topic: showcase

#23823 chore(gatsby): Migrate source-nodes to TypeScript
  packages/gatsby/src/bootstrap/index.js
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/utils/reach-router-add-basecontext-export-loader.ts
  packages/gatsby/src/utils/source-nodes.ts
Labels: bot: merge on green, type: TypeScript migration

#23835 chore(gatsby-source-contentful): drop noop loop
  packages/gatsby-source-contentful/src/normalize.js
Labels: bot: merge on green, topic: Contentful*

#23833 chore(docs): Update fadeIn prop to bool
  docs/docs/gatsby-image.md
Labels: status: triage needed

#17006 fix(gatsby-image): Fix fluid not respecting maxWidth/maxHeight
  packages/gatsby-image/README.md
  packages/gatsby-image/src/index.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby-transformer-sharp/src/fragments.js
Labels: status: awaiting reviewer response, topic: images/media

#23830 chore(www): Change from react-loadable to loadable-components
  docs/docs/debugging-html-builds.md
Labels: status: triage needed

#23671 perf(gatsby): include node counts in output after sourcing steps
  packages/gatsby/src/bootstrap/index.js
Labels: bot: merge on green, scaling

#23363 docs: new source plugin tutorial
  docs/contributing/docs-contributions.md
  docs/docs/creating-a-source-plugin.md
  docs/docs/gatsby-vendor-partnership.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/schema-gql-type.md
  docs/docs/sourcing-from-private-apis.md
  docs/tutorial/pixabay-source-plugin-tutorial.md
  docs/tutorial/source-plugin-tutorial.md
  examples/using-local-plugins/README.md
  packages/gatsby-cli/src/create-cli.js
  www/redirects.yaml
  www/src/data/sidebars/tutorial-links.yaml
Labels: type: documentation

#23765 Add support for image URLs as well as relative paths
  packages/gatsby-theme-blog-core/gatsby-node.js
Labels: topic: themes

#23845 feat(benchmark-mdx): add script to update 1 mdx article title for benchmarking data updates
  benchmarks/mdx/package.json
  benchmarks/mdx/scripts/data-update.ts
Labels: bot: merge on green, status: inkteam assigned

#23855 feat(benchmark-datocms): Add data update script to update article title
  benchmarks/source-datocms/package.json
  benchmarks/source-datocms/scripts/data-update.ts
  benchmarks/source-datocms/scripts/updater.ts
  benchmarks/source-datocms/tsconfig.json
Labels: bot: merge on green, status: inkteam assigned

#23696 fix(gatsby): use scoped requires for theme plugins
  packages/gatsby/src/bootstrap/load-plugins/load.js
  packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/.gitignore
  packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/gatsby-config.js
  packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/gatsby-config.js
  packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/node_modules/gatsby-theme-parent/gatsby-config.js
  packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/node_modules/gatsby-theme-parent/node_modules/gatsby-plugin-added-by-parent-theme/package.json
  packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/node_modules/gatsby-theme-parent/package.json
  packages/gatsby/src/bootstrap/load-themes/__tests__/fixtures/resolve-from-config-location/node_modules/gatsby-theme-child/package.json
  packages/gatsby/src/bootstrap/load-themes/__tests__/index.js
  packages/gatsby/src/bootstrap/load-themes/index.js
  packages/gatsby/src/utils/__tests__/merge-gatsby-config.js
  packages/gatsby/src/utils/merge-gatsby-config.js
Labels: status: needs core review

#23847 chore(gitkeep): remove useless files
  benchmarks/plugin-manifest/public/.gitkeep
  docs/blog/2019-01-24-swag-store/images/.gitkeep
  packages/gatsby-plugin-flow/src/.gitkeep
  packages/gatsby-plugin-fullstory/src/.gitkeep
  packages/gatsby-plugin-guess-js/src/.gitkeep
  packages/gatsby-plugin-remove-trailing-slashes/src/.gitkeep
  packages/gatsby-plugin-subfont/src/.gitkeep
  packages/gatsby-source-npm-package-search/src/.gitkeep
  rfcs/text/.gitkeep
Labels: type: chore

#23859 fix(docs): add missing comma between properties in code example
  docs/docs/sourcing-from-sanity.md
Labels: bot: merge on green, type: documentation

#23861 Add www.chandraveena.com to Gatsby Site Showcase
  docs/sites.yml
Labels: topic: showcase

#23804 Make ButterCMS all one word in title
  docs/blog/2020-05-05-Butter-CMS-case-study/index.md
Labels: topic: blogpost

#23868 Add Cognifide Tech to Gatsby Showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#23871 fix(gatsby-dev-cli): fix "expected manifest" errors
  packages/gatsby-dev-cli/src/local-npm-registry/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
  packages/gatsby-dev-cli/src/local-npm-registry/publish-package.js
  packages/gatsby-dev-cli/src/local-npm-registry/verdaccio-config.js
  packages/gatsby-dev-cli/src/watch.js
Labels: status: needs core review

#23854 fix(gatsby-remark-images): allow default max-width to be overwritten with `wrapperStyle`
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/index.js
Labels: status: needs core review, topic: images/media

#23824 chore(docs): Fix file extension on TS doc
  docs/docs/typescript.md
Labels: type: documentation

#23874 update(docs) Fix broken links in node-tracking.md
  docs/docs/node-tracking.md
Labels: status: triage needed, type: documentation

#23873 add Impossible Burgers case study
  docs/blog/2020-05-07-gatsby-delivers-impossible-burgers-map/index.md
Labels: topic: blogpost

#23414 fix(gatsby-link): replace current path in history rather than pushing it
  packages/gatsby-link/src/__tests__/index.js
  packages/gatsby-link/src/index.js
Labels: status: needs core review, topic: reach/router*

#23876 chore(gatsby-benchmark-wordpress): update to latest packages
  benchmarks/source-wordpress/package.json
Labels: bot: merge on green, status: inkteam assigned, topic: internal

#23879 Theme blog image resolution
  packages/gatsby-theme-blog-core/gatsby-node.js
Labels: topic: themes

#23863 fix(www): Allow API docs to reference top level TS exports
  www/src/templates/template-api-markdown.js
Labels: topic: website

#23882 fix(gatsby-recipes): Also call telemetry when selecting a recipe from the list
  packages/gatsby-recipes/src/cli.js
Labels: bot: merge on green, topic: recipes

#23664 chore(docs): prevent use of h1s in markdown
  .remarkrc.js
  docs/README.md
  docs/blog/100days/index.md
  docs/blog/2017-05-31-introduction-to-gatsby/index.md
  docs/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/index.md
  docs/blog/2017-10-03-smartive-goes-gatsby/index.md
  docs/blog/2017-10-05-portfolio-site-gatsby-wordpress/index.md
  docs/blog/2017-10-16-making-website-building-fun/index.md
  docs/blog/2018-04-04-gatsby-contentful-starter-tutorial/index.md
  docs/blog/2018-04-25-how-gatsby-changes-teams-website-development-workflow/index.md
  docs/blog/2018-04-27-building-eviction-free-nyc-with-gatsbyjs-and-contentful/index.md
  docs/blog/2018-06-08-gatsby-marketers-managers-agencies-teams/index.md
  docs/blog/2018-08-11-gatsby-pair-programming/index.md
  docs/blog/2018-3-03-case-study-mike-johnston/index.md
  docs/blog/2019-01-09-gatsby-days-talks-are-here.md
  docs/blog/2019-01-16-how-to-build-a-website-with-react/index.md
  docs/blog/2019-01-29-themes-update-child-theming-and-component-shadowing/index.md
  docs/blog/2019-02-20-introducing-use-static-query/index.md
  docs/blog/2019-02-26-getting-started-with-gatsby-themes/index.md
  docs/blog/2019-03-07-sell-gatsby-to-clients/index.md
  docs/blog/2019-03-15-design-code-blog-post/index.md
  docs/blog/2019-03-29-interview-with-david-eads/index.md
  docs/blog/2019-05-07-advanced-sitemap-plugin-for-seo/index.md
  docs/blog/2019-08-27-roll-your-own-comment-system/index.md
  docs/blog/2020-01-27-announcing-gatsby-builds-and-reports/index.md
  docs/blog/2020-02-11-founding-organizations/index.md
  docs/blog/2020-03-20-dropping-support-for-node-8/index.md
  docs/blog/2020-03-26-service-relief-project/index.md
  docs/blog/gatsby-first-beta-release.md
  docs/contributing/contributor-swag.md
  docs/contributing/how-to-file-an-issue.md
  docs/docs/creating-dynamic-navigation.md
  docs/docs/query-execution.md
  docs/docs/query-extraction.md
  docs/docs/recipes/gitlab-continuous-integration.md
  docs/docs/themes/building-themes.md
  docs/tutorial/wordpress-image-tutorial.md
  package.json
  yarn.lock
Labels: type: documentation

#23797 feat(www): Meta title support
  docs/blog/2020-04-29-incredimental-builds/index.md
  docs/contributing/docs-and-blog-components.md
  www/src/components/__tests__/blog-post-metadata.js
  www/src/components/blog-post-metadata.js
  www/src/components/page-metadata.js
  www/src/templates/template-blog-post.js
Labels: topic: website

#23894 update(docs) Fix broken links in "How Queries Work" article
  docs/docs/query-behind-the-scenes.md
Labels: bot: merge on green, type: documentation

#23771 chore(gatsby): Migrate nodes reducer and last-action reducer to TypeScript
  packages/gatsby/src/redux/__tests__/__snapshots__/nodes.ts.snap
  packages/gatsby/src/redux/__tests__/nodes.ts
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/last-action.js
  packages/gatsby/src/redux/reducers/last-action.ts
  packages/gatsby/src/redux/reducers/nodes.ts
  packages/gatsby/src/redux/types.ts
Labels: type: TypeScript migration

#23839 chore: bump yargs parser version to avoid flagged vulnerable dependencies
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/create-cli.js
  packages/gatsby-dev-cli/package.json
  yarn.lock
Labels: topic: cli, type: maintenance

#23899 fix(gatsby-dev-cli): fix `set-path-to-repo` command after yargs bump
  packages/gatsby-dev-cli/src/index.js
Labels: bot: merge on green

#23906 chore(gatsby): cleanup double import of reporter
  packages/gatsby/src/bootstrap/index.js
Labels: bot: merge on green

#23071 chore(starter):update gatsby-starter-typescript-power-blog template
  docs/starters.yml
Labels: bot: merge on green, topic: showcase

#23353 Update blog-core
  packages/gatsby-theme-blog-core/src/components/bio-content.js
  packages/gatsby-theme-blog-core/src/components/bio.js
  packages/gatsby-theme-blog-core/src/components/header.js
  packages/gatsby-theme-blog-core/src/components/headings.js
  packages/gatsby-theme-blog-core/src/components/home-footer.js
  packages/gatsby-theme-blog-core/src/components/layout.js
  packages/gatsby-theme-blog-core/src/components/post-footer.js
  packages/gatsby-theme-blog-core/src/components/post.js
  packages/gatsby-theme-blog-core/src/components/posts.js
  packages/gatsby-theme-blog-core/src/components/seo.js
  packages/gatsby-theme-blog-core/src/templates/post-query.js
  packages/gatsby-theme-blog-core/src/templates/posts-query.js
  packages/gatsby-theme-blog/src/components/post-link.js
  packages/gatsby-theme-blog/src/components/post.js
Labels: topic: themes

#23315 refactor(gatsby-theme-blog): Remove keywords from seo
  packages/gatsby-theme-blog-core/README.md
  packages/gatsby-theme-blog-core/gatsby-node.js
  packages/gatsby-theme-blog-core/src/templates/post-query.js
  packages/gatsby-theme-blog/README.md
  packages/gatsby-theme-blog/src/components/post.js
  packages/gatsby-theme-blog/src/components/seo.js
Labels: breaking change, topic: themes

#23864 feat(benchmarks): Add script to update 1 Contentful article (for benchmarking data updates)
  benchmarks/source-contentful/.env.example
  benchmarks/source-contentful/README.md
  benchmarks/source-contentful/bin/site.js
  benchmarks/source-contentful/package.json
  benchmarks/source-contentful/scripts/data-update.ts
Labels: bot: merge on green, topic: internal

#23911 Errant file deletion broke prism in theme
  packages/gatsby-theme-blog/src/gatsby-plugin-theme-ui/components.js
Labels: topic: themes

#23851 chore(jest/circleci): setup test report for units
  .circleci/config.yml
  package.json
  yarn.lock
Labels: status: needs core review

#23912 (chore) add seoTitle to ButterCMS blog post
  docs/blog/2020-05-05-Butter-CMS-case-study/index.md
Labels: status: triage needed, topic: blogpost

#23277 chore(gatsby): convert page-component to typescript
  packages/gatsby/src/redux/machines/__tests__/page-component.ts
  packages/gatsby/src/redux/machines/page-component.ts
  packages/gatsby/src/redux/reducers/components.js
Labels: type: TypeScript migration

#23537 Table of contents for API reference pages
  www/src/components/__tests__/docs-markdown-page.js
  www/src/components/api-reference/index.js
  www/src/components/docs-markdown-page.js
  www/src/templates/template-api-markdown.js
  www/src/templates/template-docs-markdown.js
Labels: topic: website, type: documentation

#23919 Update data update webhooks env naming
  benchmarks/md/scripts/data-update.ts
  benchmarks/mdx/scripts/data-update.ts
Labels: bot: merge on green

#23914 Adjust frontmatter and add CTA
  docs/blog/2020-05-07-gatsby-delivers-impossible-burgers-map/index.md
Labels: topic: blogpost

#23888 feat(gatsby-recipes): Improve ongoing summary of steps + add end summary
  packages/gatsby-recipes/recipes/tailwindcss.mdx
  packages/gatsby-recipes/src/__snapshots__/recipe-machine.test.js.snap
  packages/gatsby-recipes/src/cli.js
  packages/gatsby-recipes/src/graphql.js
  packages/gatsby-recipes/src/recipe-machine.js
  packages/gatsby-recipes/src/recipe-machine.test.js
Labels: bot: merge on green, topic: recipes

#23867 fix(using-markdown-pages): Example and docs
  docs/docs/adding-markdown-pages.md
  examples/using-markdown-pages/gatsby-node.js
  examples/using-markdown-pages/src/markdown-pages/post-1.md
  examples/using-markdown-pages/src/markdown-pages/post-2.md
  examples/using-markdown-pages/src/pages/index.js
  examples/using-markdown-pages/src/templates/blogTemplate.js
Labels: type: documentation

#23471 maintenance(www): Simplify the way we structure and set up the /packages pages
  www/src/components/plugin-searchbar-body.js
  www/src/templates/template-docs-local-packages.js
  www/src/templates/template-docs-remote-packages.js
  www/src/templates/template-package-readme.js
  www/src/utils/__tests__/is-official-package.js
  www/src/utils/is-official-package.js
  www/src/utils/node/docs.js
  www/src/utils/node/packages.js
Labels: topic: website

#23921 fix(docs): add trainling slash to doc-links.yaml
  www/src/data/sidebars/doc-links.yaml
Labels: status: triage needed

#23858 chore(docs,blog): Cosmic Rebranding
  docs/blog/100days/cms/index.md
  docs/blog/2018-06-07-build-a-gatsby-blog-using-the-cosmic-js-source-plugin/index.md
  docs/blog/2019-11-14-announcing-gatsby-cloud/index.md
  docs/blog/2019-11-25-introducing-gatsby-preview-for-cosmic-js/index.md
  docs/blog/2020-04-22-announcing-incremental-builds/index.md
  docs/blog/2020-04-29-incredimental-builds/index.md
  docs/blog/author.yaml
  docs/categories.yml
  docs/docs/deploying-to-gatsby-cloud.md
  docs/docs/headless-cms.md
  docs/starters.yml
  www/src/data/tags-docs.js
Labels: status: needs docs review

#23930 chore: get rid of weird registry mirrors from lock
  yarn.lock
Labels: type: maintenance

#23767 Quick fix to recipes discoverability
  docs/docs/recipes.md
Labels: topic: recipes

#23939 Add Catalan to languages
  www/i18n.json
Labels: status: triage needed

#23946 Update deploying-to-zeit-now.md
  docs/docs/deploying-to-zeit-now.md
Labels: status: triage needed

#23967 fix(www): allow to tree shake lodash-es
  www/src/components/tags-section.js
Labels: bot: merge on green, topic: website, type: maintenance

#23951 fix(gatsby-cli): don't fail when using `--log-pages` and/or `--write-to-file`
  packages/gatsby-cli/src/create-cli.js
Labels: topic: cli

#23587 chore(docs): add Clodui deployment guide
  docs/docs/deploying-to-clodui.md
  www/src/data/sidebars/doc-links.yaml
Labels: type: documentation

#23708 chore(gatsby): Convert jobsV2 reducer to TS
  packages/gatsby/src/bootstrap/remove-stale-jobs.ts
  packages/gatsby/src/redux/__tests__/jobsv2.js
  packages/gatsby/src/redux/reducers/index.js
  packages/gatsby/src/redux/reducers/jobsv2.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/jobs-manager.js
Labels: bot: merge on green, status: inkteam assigned, type: TypeScript migration

#23956 fix: handle nullish announcementRef to fix client side redirect error
  packages/gatsby/cache-dir/navigation.js
Labels: bot: merge on green, topic: a11y

#23961 Rename ZEIT Now to Vercel
  docs/docs/deploying-to-vercel.md
  www/src/data/diagram/static-hosts.yml
Labels: status: triage needed

#23979 Add redirect for Vercel docs
  www/redirects.yaml
Labels: status: needs docs review

#23938 Update sites.yml
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#23980 chore(showcase): Add Zona Digital to Gatsby Showcase
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#23982 Extend image seo for blog theme
  packages/gatsby-theme-blog/src/components/post.js
  packages/gatsby-theme-blog/src/components/seo.js
Labels: topic: themes

#23981 (chore)Update Incremental Builds blog post with list
  docs/blog/2020-04-22-announcing-incremental-builds/index.md
Labels: topic: blogpost

#22408 chore(gatsby): migrate gatsby-webpack-eslint-graphql-schema-reload-plugin to TS
  packages/gatsby/src/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.ts
  packages/gatsby/src/utils/webpack-utils.ts
Labels: bot: merge on green, type: TypeScript migration

#22404 chore(gatsby): migrate gatsby-webpack-stats-extractor to TypeScript
  package.json
  packages/gatsby/src/utils/gatsby-webpack-stats-extractor.ts
  packages/gatsby/src/utils/webpack-utils.ts
  yarn.lock
Labels: bot: merge on green, type: TypeScript migration

#23280 chore(starters): add dib-gatsby-starter
  docs/starters.yml
Labels: bot: merge on green, topic: showcase

#23284 feat(gatsby): Gatsby config validation should suggest related keys
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.js.snap
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.js
  packages/gatsby/src/bootstrap/load-plugins/load.js
  packages/gatsby/src/redux/actions/__tests__/internal.ts
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/utils/did-you-mean.ts
Labels: bot: merge on green

#23293 chore(starters): update gatsby-gitbook-starter link
  docs/starters.yml
Labels: bot: merge on green, topic: showcase

#23520 Add GP TypeScript starter to starters.yml
  docs/starters.yml
Labels: topic: showcase

#23527 chore(starters): update gatsby-contentful-blog-portfolio
  docs/starters.yml
Labels: topic: showcase

#23578 Add riverscasino.com to showcase.
  docs/sites.yml
Labels: topic: showcase

#23986 add strapi case study and author avatar and bio
  docs/blog/2020-05-12-strapi-instant-content-preview-plugin/gatsby_strapi.jpg
  docs/blog/2020-05-12-strapi-instant-content-preview-plugin/index.md
  docs/blog/author.yaml
  docs/blog/avatars/maxime-castres.jpg
Labels: topic: blogpost

#23548 Request to add Most Recommended Books to features sites
  docs/categories.yml
  docs/sites.yml
Labels: bot: merge on green, topic: showcase

#23849 chore(plugin-react-css-modules): init test
  packages/gatsby-plugin-react-css-modules/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-react-css-modules/src/__tests__/gatsby-node.js
Labels: topic: webpack/babel*, type: chore

#23965 test(source-npm-package-search): init test
  packages/gatsby-source-npm-package-search/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-source-npm-package-search/src/__tests__/gatsby-node.js
  packages/gatsby-source-npm-package-search/src/gatsby-node.js
  packages/gatsby-source-npm-package-search/src/search.js
Labels: type: chore

#23898 feat(gatsby-plugin-benchmark-reporting): allow arbitrary restart
  packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Labels: status: needs core review

#23634 fix(gatsby): allow elemMatch on non-arrays, fix tests
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/redux/run-sift.js
  packages/gatsby/src/schema/__tests__/run-query.js
Labels: scaling, status: needs core review, topic: GraphQL, topic: Performance

#23978 perf(gatsby): enable fast filters for lt and gt
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/redux/run-sift.js
  packages/gatsby/src/schema/__tests__/run-query.js
Labels: bot: merge on green, scaling, status: needs core review, topic: GraphQL, topic: Performance

#23619 docs/glossary: Add a new Progressive Enhancement entry.
  docs/docs/glossary.md
  docs/docs/glossary/progressive-enhancement.md
  www/src/data/sidebars/doc-links.yaml
Labels: topic: internal

#24015 fix(docs): add slashes to links in static host yaml
  www/src/data/diagram/static-hosts.yml
Labels: status: needs docs review

#24021 fix(docs): links in sidebar to vercel
  www/src/data/sidebars/doc-links.yaml
Labels: status: needs docs review

#24031 fix(gatsby-plugin-benchmark-reporting): Fix invalid refernece to var that may be null
  packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
Labels: status: triage needed

#24040 Fix a11y outline on homepage view all posts button
  www/src/components/homepage/homepage-blog-posts.js
Labels: status: triage needed

#23989 Use new a11y email alias & update WCAG version
  docs/accessibility-statement.md
Labels: type: documentation
