Repository gatsbyjs/gatsby, pull requests merged in 2021-10, with the labels that each got.

#33273 feat(gatsby): engines activity
  integration-tests/artifacts/gatsby-config.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build-javascript.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/bundle.ts
  packages/gatsby/src/utils/webpack/plugins/__tests__/corejs-resolver.ts
  packages/gatsby/src/utils/webpack/plugins/cache-folder-resolver.ts
  packages/gatsby/src/utils/webpack/plugins/corejs-resolver.ts
  packages/gatsby/src/utils/webpack/plugins/force-css-hmr-for-edge-cases.ts
  packages/gatsby/src/utils/webpack/plugins/static-query-mapper.ts
  packages/gatsby/src/utils/webpack/plugins/webpack-logging.ts
Labels: gatsby 4

#33343 fix(gatsby): remove DEV_SSR from FAST_DEV
  packages/gatsby/src/utils/flags.ts
Labels: type: maintenance

#33392 docs: fix "(r)esource congestion"
  docs/docs/how-to/performance/improving-site-performance.md
Labels: status: triage needed

#33184 feat(gatsby): Don't crash the build process when in preview mode
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: type: bug

#33408 chore(docs): Fix Grammar Issue
  docs/docs/reference/built-in-components/gatsby-image.md
Labels: status: triage needed

#33406 chore(gatsby-plugin-manifest): Update README links
  packages/gatsby-plugin-manifest/README.md
Labels: type: documentation

#33209 feat(gatsby): handle search params in resource loader
  e2e-tests/development-runtime/cypress/integration/ssr.js
  e2e-tests/development-runtime/src/pages/ssr/param-path/[param].js
  e2e-tests/development-runtime/src/pages/ssr/static-path.js
  e2e-tests/development-runtime/src/pages/ssr/wildcard-path/[...wildcard].js
  e2e-tests/production-runtime/cypress/integration/redirects.js
  e2e-tests/production-runtime/cypress/integration/ssr.js
  e2e-tests/production-runtime/src/pages/ssr/param-path/[param].js
  e2e-tests/production-runtime/src/pages/ssr/static-path.js
  e2e-tests/production-runtime/src/pages/ssr/wildcard-path/[...wildcard].js
  packages/gatsby-link/src/index.js
  packages/gatsby/cache-dir/__tests__/ensure-resources.tsx
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/ensure-resources.js
  packages/gatsby/cache-dir/find-path.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/cache-dir/normalize-page-path.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/root.js
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/utils/develop-preload-headers.ts
  packages/gatsby/src/utils/page-ssr-module/entry.ts
Labels: topic: render-mode

#33401 chore(gatsby-source-contentful): Improve README on rich text ref
  packages/gatsby-source-contentful/README.md
Labels: type: documentation

#33341 feat(gatsby): disable inference for internal types
  packages/gatsby/src/schema/types/built-in-types.ts
Labels: topic: GraphQL

#33411 chore(docs): Update Kentico Kontent references
  docs/docs/how-to/sourcing-data/headless-cms.md
  docs/docs/sourcing-from-kentico-kontent.md
Labels: type: documentation

#33266 fix(gatsby): postcss-svgo - remove plugin removeAttrs
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: core

#33419 feat(gatsby-source-drupal): port hot-fixes for Drupal/Gatsby customer to package
  packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/image-gallary.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: topic: source-drupal

#32544 feat(gatsby-plugin-image): support multiple sources using gatsby-plugin-image
  packages/gatsby-plugin-image/src/gatsby-node.ts
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-source-shopify/src/gatsby-node.ts
  packages/gatsby-source-shopify/src/resolve-gatsby-image-data.ts
Labels: topic: media

#33398 feat(gatsby): hot reload getServerData
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/cache-dir/query-result-store.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/services/recompile.ts
  packages/gatsby/src/services/types.ts
  packages/gatsby/src/state-machines/develop/actions.ts
  packages/gatsby/src/state-machines/develop/index.ts
  packages/gatsby/src/utils/clear-require-cache.ts
  packages/gatsby/src/utils/websocket-manager.ts
Labels: gatsby 4

#33423 fix(gatsby-source-drupal): Add tests for meta.count support & fix bug with i18n
  packages/gatsby-source-drupal/src/__tests__/fixtures/article-meta.count-i18n.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/article-meta.count.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/articlemeta.count-i18n___page%5Blimit%5D=3&page%5Boffset%5D=3.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/articlemeta.count___page%5Blimit%5D=1&page%5Boffset%5D=2.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/articlemeta.count___page%5Blimit%5D=3&page%5Boffset%5D=3.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/articlemeta.count___page%5Blimit%5D=3&page%5Boffset%5D=6.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/i18n-test-article-meta.count-i18n.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/i18n-test-i18n-test-articlemeta.count-i18n___page%5Blimit%5D=3&page%5Boffset%5D=3.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi-meta.count-i18n.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi-meta.count.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: type: bug, topic: source-drupal

#33439 chore: Fix tests for WordPress, Contentful & update CircleCI (#33256)
  .circleci/config.yml
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-wordpress/src/steps/process-and-validate-plugin-options.ts
Labels: type: cherry

#33050 feat(gatsby): Add JSX Runtime options to `gatsby-config.js`
  docs/docs/reference/config-files/gatsby-config.md
  packages/gatsby/index.d.ts
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.ts.snap
  packages/gatsby/src/redux/actions/__tests__/internal.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/babel-loader.js
  packages/gatsby/src/utils/did-you-mean.ts
  packages/gatsby/src/utils/eslint-config.ts
  packages/gatsby/src/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.ts
  packages/gatsby/src/utils/merge-gatsby-config.ts
  packages/gatsby/src/utils/webpack-utils.ts
Labels: bot: merge on green, topic: core, topic: DX

#33740 chore: add GATSBY_CPU_COUNT to tests
  .circleci/config.yml
Labels: type: maintenance

#30468 fix(gatsby-remark-images): GATSBY_EMPTY_ALT figcaption generation
  packages/gatsby-remark-images/src/index.js
Labels: topic: remark/mdx
