Repository gatsbyjs/gatsby, pull requests merged in 2021-08, with the labels that each got.

#32684 fix(docs): Document how to do asset prefix build with env variable
  docs/docs/how-to/previews-deploys-hosting/asset-prefix.md
Labels: bot: merge on green, type: documentation

#32686 feat(gatsby): allow sites to disable the dev 404 page
  packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js
Labels: type: feature or enhancement

#32677 chore(docs): Fix typo
  docs/docs/how-to/adding-common-features/adding-forms.md
Labels: type: documentation

#32676 chore(docs): Fix typo
  docs/docs/how-to/adding-common-features/adding-forms.md
Labels: type: documentation

#32682 chore(docs): Fix URL to sharp
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
Labels: type: documentation

#32549 chore(starters): Update links in README-template
  starters/README-template.md
Labels: type: documentation

#32509 fix(gatsby-plugin-sitemap): Add plugin options forbidden for deprecated `exclude`
  packages/gatsby-plugin-sitemap/src/__tests__/options-validation.js
  packages/gatsby-plugin-sitemap/src/options-validation.js
Labels: topic: plugins

#32674 fix(gatsby-source-shopify): update method of generating published_status when salesChannel parameter is used
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/query-builders/collections-query.ts
  packages/gatsby-source-shopify/src/query-builders/locations-query.ts
  packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
  packages/gatsby-source-shopify/src/query-builders/products-query.ts
Labels: topic: source-shopify

#32680 docs: release notes for v3.11
  docs/docs/reference/release-notes/v3.11/index.md
Labels: type: documentation

#32700 chore(starters): Typo on tsconfig
  starters/blog/src/pages/using-typescript.tsx
  starters/default/src/pages/using-typescript.tsx
Labels: topic: DX

#32710 fix(gatsby-source-shopify): only add inventory fields to product variant when using locations
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
Labels: topic: source-shopify

#32687 feat(babel-preset-gatsby-package): add conditional compilation plugin
  .eslintrc.js
  package.json
  packages/babel-preset-gatsby-package/.babelrc
  packages/babel-preset-gatsby-package/.gitignore
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/__tests__/babel-transform-compiler-flags.js
  packages/babel-preset-gatsby-package/__tests__/fixtures/compiler-flags/default/input.js
  packages/babel-preset-gatsby-package/__tests__/fixtures/compiler-flags/default/output.mjs
  packages/babel-preset-gatsby-package/__tests__/fixtures/compiler-flags/unused/input.js
  packages/babel-preset-gatsby-package/__tests__/fixtures/compiler-flags/unused/options.json
  packages/babel-preset-gatsby-package/__tests__/fixtures/options.js
  packages/babel-preset-gatsby-package/__tests__/index.js
  packages/babel-preset-gatsby-package/package.json
  packages/babel-preset-gatsby-package/src/babel-transform-compiler-flags.ts
  packages/babel-preset-gatsby-package/src/index.js
  packages/babel-preset-gatsby-package/src/resolver.js
  packages/babel-preset-gatsby-package/tsconfig.json
  tsconfig.json
  types/gatsby-monorepo/global.d.ts
  types/gatsby-monorepo/package.json
  yarn.lock
Labels: type: feature or enhancement, topic: core

#32432 fix(gatsby): Worker support in fast-refresh-module
  packages/gatsby/src/utils/fast-refresh-module.ts
Labels: topic: core

#32709 fix(contentful): base64 previews now reflect all query options
  e2e-tests/contentful/cypress/integration/gatsby-image.js
  e2e-tests/contentful/cypress/integration/gatsby-plugin-image.js
  e2e-tests/contentful/snapshots.js
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: status: needs core review, topic: source-contentful

#32530 fix(gatsby-remark-image-contentful): show useful error message for files that can not be rendered as image
  packages/gatsby-remark-images-contentful/src/__tests__/index.js
  packages/gatsby-remark-images-contentful/src/index.js
Labels: topic: plugins

#32713 fix(babel-preset-gatsby): no compile
  packages/babel-preset-gatsby-package/.gitignore
  packages/babel-preset-gatsby-package/lib/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/lib/__tests__/babel-transform-compiler-flags.js
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/compiler-flags/default/input.js
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/compiler-flags/default/output.mjs
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/compiler-flags/unused/input.js
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/compiler-flags/unused/options.json
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/options.js
  packages/babel-preset-gatsby-package/lib/__tests__/index.js
  packages/babel-preset-gatsby-package/lib/babel-transform-compiler-flags.js
  packages/babel-preset-gatsby-package/lib/index.js
  packages/babel-preset-gatsby-package/lib/resolver.js
  packages/babel-preset-gatsby-package/package.json
  packages/babel-preset-gatsby-package/src/babel-transform-compiler-flags.ts
  packages/babel-preset-gatsby-package/tsconfig.json
Labels: topic: webpack/babel

#31717 feat(gatsby-plugin-gatsby-cloud): Reusable preview loader component
  packages/gatsby-plugin-gatsby-cloud/.gitignore
  packages/gatsby-plugin-gatsby-cloud/package.json
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/mocks/handlers.js
  packages/gatsby-plugin-gatsby-cloud/src/components/GatsbyIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/components/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/IndicatorButtonTooltip.js
  packages/gatsby-plugin-gatsby-cloud/src/components/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/LinkIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Style.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/GatsbyIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/LinkIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/index.js
  packages/gatsby-plugin-gatsby-cloud/src/components/icons.js
  packages/gatsby-plugin-gatsby-cloud/src/components/index.d.ts
  packages/gatsby-plugin-gatsby-cloud/src/components/index.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildErrorTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildSuccessTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/IndicatorButtonTooltip.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/index.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-ssr.js
Labels: topic: plugins

#32488 Fix "TypeError: Cannot read property 'databaseId' of null" in gatsby-source-wordpress previews
  packages/gatsby-source-wordpress/src/steps/preview/index.ts
Labels: topic: source-wordpress

#30896 feat(gatsby-source-wordpress): generate webp images
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
Labels: topic: source-wordpress

#32547 feat(gatsby): write node manifests to public dir instead of .cache
  integration-tests/node-manifest/__tests__/create-node-manifest.test.js
  packages/gatsby/src/utils/__tests__/node-manifest.ts
  packages/gatsby/src/utils/node-manifest.ts
Labels: topic: core

#32726 Fixed broken link "Using MDX Plugins"
  docs/docs/how-to/routing/migrate-remark-to-mdx.md
Labels: status: triage needed

#32727 Removed another broken link and fixed
  docs/docs/how-to/routing/migrate-remark-to-mdx.md
Labels: status: triage needed

#32730 chore(docs): fix typo
  docs/docs/how-to/performance/resolving-out-of-memory-issues.md
Labels: type: documentation

#32744 fix(gatsby): Silence process.send Error
  packages/gatsby/src/commands/develop.ts
Labels: topic: core

#32728 fix(gatsby): fix incorrect filtering with experimental LMDB indexes
  packages/gatsby/src/datastore/lmdb/query/__tests__/common.ts
  packages/gatsby/src/datastore/lmdb/query/common.ts
  packages/gatsby/src/datastore/lmdb/query/filter-using-index.ts
  packages/gatsby/src/datastore/lmdb/query/run-query.ts
  packages/gatsby/src/schema/__tests__/run-query.js
Labels: topic: core

#32707 feat(gatsby): add env flag to disable lazy function compilation in develop
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: status: triage needed

#32144 fix(gatsby-source-shopify): env variable to check if on preview or production
  packages/gatsby-source-shopify/__tests__/make-source-from-operation.ts
  packages/gatsby-source-shopify/src/make-source-from-operation.ts
Labels: topic: source-shopify

#32723 feat(gatsby-source-wordpress): process multiple manifest ids on a preview action
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/introspect-remote-schema.js
  packages/gatsby-source-wordpress/src/steps/preview/index.ts
Labels: topic: source-wordpress

#32750 feat(docs): Add note about speeding createPages to build perf doc
  docs/docs/how-to/performance/improving-build-performance.md
Labels: status: triage needed

#32679 fix(wordpress): ensure all file links are rewritten
  packages/gatsby-source-wordpress/__tests__/fetch-referenced-media-items.test.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
Labels: topic: source-wordpress

#32752 fix(gatsby-source-wordpress): not all stored nodes are media items - protect against that
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
Labels: topic: source-wordpress

#32694 chore: add release-cli for next major
  package.json
  scripts/clear-package-dir.js
  scripts/release-next-major.js
  types/gatsby-monorepo/readme.md
Labels: topic: core

#32762 fix(examples): Correct typo in comment
  examples/creating-source-plugins/source-plugin/gatsby-node.js
Labels: type: documentation

#32716 docs(tutorial): add part 7
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-6/index.mdx
  docs/docs/tutorial/part-7/another-post.png
  docs/docs/tutorial/part-7/blog-post-with-hero-image-credit.png
  docs/docs/tutorial/part-7/blog-post-with-hero-image.png
  docs/docs/tutorial/part-7/data-layer-with-imagesharp-nodes.png
  docs/docs/tutorial/part-7/index.mdx
  docs/docs/tutorial/part-7/reorganize-blog-directory.png
  docs/docs/tutorial/part-7/staticimage-vs-gatsbyimage-towns.png
  docs/docs/tutorial/part-7/unsplash.png
  docs/docs/tutorial/part-7/yet-another-post.png
  docs/docs/tutorial/part-eight/icon.png
  docs/docs/tutorial/part-eight/index.md
  docs/docs/tutorial/part-eight/lighthouse-audit-results.png
  docs/docs/tutorial/part-eight/lighthouse-audit.png
  docs/docs/tutorial/part-seven/blog-post.png
  docs/docs/tutorial/part-seven/hello-world-blog-post.png
  docs/docs/tutorial/part-seven/index.md
  docs/docs/tutorial/part-seven/markdown-relative-path.png
  docs/docs/tutorial/part-seven/new-pages.png
  docs/docs/tutorial/part-seven/query-markdown-slugs.png
  docs/docs/tutorial/whats-next/index.mdx
Labels: type: documentation

#32708 feat(gatsby-plugin-gatsby-cloud): setup path-prefix for cloud
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/create-redirects.js.snap
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-redirects.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-site-config.js
  packages/gatsby-plugin-gatsby-cloud/src/constants.js
  packages/gatsby-plugin-gatsby-cloud/src/create-redirects.js
  packages/gatsby-plugin-gatsby-cloud/src/create-site-config.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
Labels: topic: core

#32751 feat(gatsby): measure how long GraphQL takes to run in createPages and warn if > 10s
  packages/gatsby/src/services/create-pages.ts
Labels: topic: DX

#32335 fix(gatsby-plugin-image): only log missing plugin error in development
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
Labels: bot: merge on green, topic: media

#32765 chore(docs): Improved getSavedScrollPosition API desc
  packages/gatsby/src/utils/api-browser-docs.ts
Labels: type: documentation

#32775 fix(gatsby-source-shopify): coerce variable to boolean
  packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
Labels: topic: source-shopify

#32774 fix(gatsby-source-shopify): update api version to fix metafield type issue
  packages/gatsby-source-shopify/src/client.ts
  packages/gatsby-source-shopify/src/create-schema-customization.ts
  packages/gatsby-source-shopify/src/query-builders/collections-query.ts
  packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
  packages/gatsby-source-shopify/src/query-builders/products-query.ts
Labels: topic: source-shopify

#32784 chore(docs): Fix typo
  packages/gatsby-plugin-image/README.md
Labels: type: documentation

#32787 chore(gatsby-plugin-gatsby-cloud): update copy script for windows
  packages/gatsby-plugin-gatsby-cloud/package.json
Labels: type: maintenance

#32797 Fix typo of wether to whether
  packages/gatsby-source-wordpress/docs/plugin-options.md
Labels: status: triage needed

#32783 feat(gatsby): Add `defer` to createPage
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/commands/build-utils.ts
  packages/gatsby/src/query/index.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/page-data.ts
Labels: topic: core

#32796 feat(gatsby-source-drupal): log value of lastFetched
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: topic: source-drupal

#32812 add intro paragraph
  docs/docs/how-to/adding-common-features/localization-i18n.md
Labels: type: documentation, bot: merge on green

#32811 Update deploying-to-gatsby-cloud.md
  docs/docs/how-to/previews-deploys-hosting/deploying-to-gatsby-cloud.md
Labels: type: documentation, bot: merge on green

#32814 Update adding-analytics.md
  docs/docs/how-to/adding-common-features/adding-analytics.md
Labels: type: documentation, bot: merge on green

#32548 feat(gatsby-source-drupal): Default language when non translatable.
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/normalize.js
Labels: topic: source-drupal, type: feature or enhancement

#32793 chore(docs): Update Storybook guide with Addon
  docs/docs/how-to/testing/visual-testing-with-storybook.md
Labels: type: documentation

#32822 chore(docs): Remark plugin, add tip for gatsby clean
  docs/tutorial/remark-plugin-tutorial.md
Labels: type: documentation

#32803 chore(docs): Add title for image-plugin-architecture
  docs/docs/conceptual/image-plugin-architecture.md
Labels: type: documentation

#32813 chore(docs): Update security-in-gatsby
  docs/docs/conceptual/security-in-gatsby.md
Labels: type: documentation, bot: merge on green

#32777 docs(gatsby-source-contentful) provide a code example for rendering rich-text embedded assets images
  packages/gatsby-source-contentful/README.md
Labels: type: documentation, bot: merge on green, topic: source-contentful

#32827 fix(create-gatsby): Clarify multi-choice instructions
  packages/create-gatsby/src/index.ts
Labels: bot: merge on green, topic: DX

#32829 feat(gatsby): Opt in 20% of users to webpack dev server caching
  packages/gatsby/src/utils/flags.ts
Labels: bot: merge on green, topic: core, topic: DX

#32808 gatsby-plugin-image: bump do-sync to v3
  packages/gatsby-plugin-image/package.json
  yarn.lock
Labels: topic: media

#32834 fix(gatsby): Remove `removeDimensions` from svgo config
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: core

#32764 chore(docs): Change Jamstack Article
  docs/docs/glossary/jamstack.md
Labels: type: documentation

#32823 chore(docs): 3.12 Release Notes
  docs/docs/reference/release-notes/v3.12/index.md
Labels: type: documentation

#32844 chore(docs): Fix typo in v3.0 release notes
  docs/docs/reference/release-notes/v3.0/index.md
Labels: type: documentation

#32846 chore(docs): Add formatting for changed docs
  docs/docs/how-to/adding-common-features/localization-i18n.md
  docs/docs/how-to/previews-deploys-hosting/deploying-to-gatsby-cloud.md
Labels: type: documentation

#32849 chore(docs): Remove outdated information from Theme Guide
  docs/tutorial/building-a-theme.md
Labels: type: documentation

#32850 fix(gatsby): Hashes and anchors in redirects also work in production
  e2e-tests/production-runtime/cypress/integration/redirects.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/pages/index.js
  e2e-tests/production-runtime/src/pages/redirect-search-hash.js
  packages/gatsby/cache-dir/navigation.js
Labels: topic: core

#32856 fix(gatsby-source-wordpress): generate plugin options docs
  packages/gatsby-source-wordpress/__tests__/docs-generation.test.js
  packages/gatsby-source-wordpress/generate-plugin-options-docs.js
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
Labels: type: documentation

#32854 chore(docs): Fix typo in part 5 of the tutorial
  docs/docs/tutorial/part-5/index.mdx
Labels: type: documentation

#32853 fix(gatsby): Correct server type
  packages/gatsby/src/utils/start-server.ts
Labels: topic: TypeScript

#32859 chore(docs): Fixes typo in tutorial part 4
  docs/docs/tutorial/part-4/index.mdx
Labels: type: documentation

#32833 docs(tutorial): finishing touches
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-6/index.mdx
  docs/docs/tutorial/part-7/folder-structure-with-images.png
  docs/docs/tutorial/part-7/index.mdx
Labels: type: documentation

#32851 feat(gatsby-plugin-sharp): reduce encoding time and install size
  docs/docs/conceptual/image-plugin-architecture.md
  packages/gatsby-plugin-manifest/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/process-file.js
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-source-shopify/package.json
  packages/gatsby-transformer-sharp/package.json
  yarn.lock
Labels: topic: media

#32845 fix(gatsby-plugin-gatsby-cloud): Always create redirects.json
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/create-redirects.js.snap
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-redirects.js
  packages/gatsby-plugin-gatsby-cloud/src/create-redirects.js
Labels: topic: plugins

#32874 chore(docs): Change example for using async in Remark plugin
  docs/tutorial/remark-plugin-tutorial.md
Labels: type: documentation

#32872 chore(docs): Update Gallery example in tutorial part 2
  docs/docs/tutorial/part-2/index.mdx
Labels: type: documentation

#32869 chore(docs): Fix CSS Modules extension typo
  docs/docs/tutorial/part-2/index.mdx
Labels: type: documentation

#32866 chore(docs): Fix typo in tutorial part 6
  docs/docs/tutorial/part-6/index.mdx
Labels: type: documentation

#32861 feat(gatsby-core-utils): Move page-data & HTML utils to package
  e2e-tests/development-runtime/cypress/plugins/block-resources.js
  e2e-tests/development-runtime/package.json
  e2e-tests/production-runtime/cypress/plugins/block-resources.js
  e2e-tests/production-runtime/package.json
  integration-tests/ssr/package.json
  integration-tests/ssr/test-output.js
  packages/gatsby-core-utils/src/__tests__/page-data.ts
  packages/gatsby-core-utils/src/__tests__/page-html.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-core-utils/src/page-data.ts
  packages/gatsby-core-utils/src/page-html.ts
  packages/gatsby-plugin-gatsby-cloud/package.json
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
  packages/gatsby-plugin-netlify/package.json
  packages/gatsby-plugin-netlify/src/build-headers-program.js
  packages/gatsby/src/commands/build-utils.ts
  packages/gatsby/src/utils/__tests__/get-page-data.ts
  packages/gatsby/src/utils/develop-preload-headers.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: topic: core

#32885 fix(gatsby-source-wordpress): make sure remoteUrl exists before using it
  packages/gatsby-source-wordpress/src/steps/preview/index.ts
Labels: topic: source-wordpress

#32868 chore(gatsby-remark-images): Only convert supported image extensions
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/index.js
Labels: topic: remark/mdx

#32884 chore(docs): Update Building eCom with Shopify to work with latest versions
  docs/docs/building-an-ecommerce-site-with-shopify.md
Labels: type: documentation

#32847 feat(gatsby-plugin-gatsby-cloud): IPC events for routes, redirects, rewrites, and headers
  packages/gatsby-core-utils/src/page-html.ts
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-redirects.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/routes.js
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/create-redirects.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
  packages/gatsby-plugin-gatsby-cloud/src/ipc.js
Labels: topic: plugins

#32879 feat(gatsby-plugin-gatsby-cloud): Files manifest
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
  packages/gatsby-plugin-gatsby-cloud/src/ipc.js
Labels: topic: core

#32733 feat(gatsby-plugin-google-tagmanager): add option for selfHostedOrigin
  packages/gatsby-plugin-google-tagmanager/README.md
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-node.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-ssr.js
Labels: bot: merge on green, type: feature or enhancement, topic: plugins-analytics

#32960 tests(gatsby-source-contentful): fix snapshot
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
Labels: type: maintenance, topic: source-contentful

#32949 fix(gatsby): Set staticQueryResultHash to new hash
  packages/gatsby/src/redux/reducers/html.ts
Labels: status: triage needed

#32959 chore: fix patches for v4 to be compatible again
  patches/v4/0-node-version.patch
  patches/v4/1-lmdb-default.patch
  patches/v4/2-gatsby-peerdeps.patch
  scripts/release-next-major.js
Labels: type: maintenance

#32954 chore: add missing `@babel/runtime` dependencies
  packages/babel-plugin-remove-graphql-queries/package.json
  packages/babel-preset-gatsby-package/package.json
  packages/create-gatsby/package.json
  packages/gatsby-admin/package.json
  packages/gatsby-cli/package.json
  packages/gatsby-core-utils/package.json
  packages/gatsby-design-tokens/package.json
  packages/gatsby-legacy-polyfills/package.json
  packages/gatsby-plugin-benchmark-reporting/package.json
  packages/gatsby-plugin-graphql-config/package.json
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-no-sourcemaps/package.json
  packages/gatsby-plugin-page-creator/package.json
  packages/gatsby-plugin-preact/package.json
  packages/gatsby-plugin-preload-fonts/package.json
  packages/gatsby-plugin-schema-snapshot/package.json
  packages/gatsby-plugin-styletron/package.json
  packages/gatsby-plugin-subfont/package.json
  packages/gatsby-plugin-utils/package.json
  packages/gatsby-recipes/package.json
  packages/gatsby-source-shopify/package.json
  packages/gatsby-source-wikipedia/package.json
  packages/gatsby-transformer-screenshot/package.json
  packages/gatsby-worker/package.json
Labels: type: maintenance

#32939 docs: Remove cloud plugin from `gatsby new` and tutorial
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-4/index.mdx
  packages/create-gatsby/src/features.json
Labels: type: maintenance

#32961 fix(gatsby): don't log FAST_DEV message for each worker
  packages/gatsby/src/services/initialize.ts
Labels: topic: core

#32962 fix(gatsby): Proper cache status event
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/index.ts
Labels: topic: core

#32965 chore: enable changelog updates on releases
  .circleci/config.yml
Labels: type: maintenance, bot: merge on green

#32964 chore(docs): 3.13 Release Notes
  docs/docs/reference/release-notes/v3.13/index.md
Labels: type: documentation
