Repository gatsbyjs/gatsby, pull requests merged in 2021-09, with the labels that each got.

#32928 chore: upgrade got package
  package.json
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/__tests__/create-remote-file-node-integration.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
  packages/gatsby-dev-cli/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node-integration.js
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby-source-npm-package-search/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby/package.json
  packages/gatsby/src/utils/start-server.ts
  yarn.lock
Labels: type: maintenance

#33013 chore: fix broken recipes test
  packages/gatsby-legacy-polyfills/package.json
  packages/gatsby-legacy-polyfills/src/__tests__/polyfills.js
  packages/gatsby-recipes/src/providers/npm/__snapshots__/package.test.js.snap
  renovate.json5
  scripts/renovate-config-generator.js
  yarn.lock
Labels: type: maintenance, bot: merge on green

#33014 fix(gatsby): add missing built-in types
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/types/built-in-types.ts
Labels: bot: merge on green

#32941 refactor: replace better-queue with fastq
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby-transformer-screenshot/package.json
  packages/gatsby-transformer-screenshot/src/gatsby-node.js
Labels: type: maintenance, bot: merge on green

#33024 fix(contentful): asset download retry
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: bot: merge on green, topic: source-contentful

#33027 test(CTF): ensure changing base64 previews don't break rich text tests
  e2e-tests/contentful/cypress/integration/rich-text.js
  e2e-tests/contentful/snapshots.js
Labels: topic: source-contentful

#32971 fix(gatsby-source-drupal): delete relationships to now deleted nodes
  packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/article.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: type: bug, topic: source-drupal

#33032 feat(gatsby): catch webpack chunk loading errors and completely reload the app
  packages/gatsby/cache-dir/navigation.js
Labels: topic: core

#33034 docs(ch37501): fix broken links from docs contribution page
  docs/contributing/docs-and-blog-components.md
  docs/contributing/docs-contributions/index.md
  docs/contributing/docs-writing-process.md
  docs/contributing/how-to-open-a-pull-request.md
  docs/docs/modifying-a-starter.md
Labels: type: documentation

#32940 chore(docs): Update docs about "Headless CMSs"
  docs/docs/glossary/decoupled-drupal.md
  docs/docs/glossary/headless-cms.md
  docs/docs/glossary/headless-wordpress.md
Labels: type: documentation

#33022 chore(docs): Update "Making your site accessible"
  docs/docs/conceptual/making-your-site-accessible.md
Labels: type: documentation

#33037 fix(sqip): ensure failed asset downloads do not break build
  packages/gatsby-transformer-sqip/src/extend-node-type.js
Labels: status: triage needed

#33029 feat(gatsby-plugin-sharp): Use file streams instead of file paths
  packages/gatsby-plugin-sharp/src/__tests__/trace-svg.js
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/process-file.js
  packages/gatsby-plugin-sharp/src/trace-svg.js
  packages/gatsby-plugin-sharp/src/utils.js
Labels: topic: media

#32929 feat(gatsby-source-wordpress): replace lazynodes option for v4
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  packages/gatsby-source-wordpress/docs/features/media-item-processing.md
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/generate-plugin-options-docs.js
  packages/gatsby-source-wordpress/src/models/gatsby-api.ts
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/transform-object.js
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
  packages/gatsby-source-wordpress/src/steps/process-and-validate-plugin-options.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-nodes.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
  packages/gatsby-source-wordpress/src/utils/gatsby-version.ts
  packages/gatsby-source-wordpress/tsconfig.json
Labels: topic: source-wordpress

#33044 chore: correct messages for auto-changelog PRs
  scripts/gatsby-changelog-generator/generate.js
  scripts/gatsby-changelog-generator/update-and-open-pr.js
Labels: type: maintenance, bot: merge on green

#33057 fix(starters): Formats for StaticImage
  starters/blog/src/components/bio.js
  starters/default/src/pages/index.js
Labels: topic: DX

#33051 fix(gatsby): reduce page-renderer-size
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/package.json
  packages/gatsby/src/internal-plugins/bundle-optimisations/gatsby-node.js
  packages/gatsby/src/utils/webpack.config.js
Labels: type: maintenance, topic: webpack/babel

#33062 fix(gatsby): Add TS type/v4 patches for `unstable_onPluginInit`
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts
  patches/v4/3-onplugininit.patch
Labels: topic: core, topic: TypeScript

#31837 fix: add missing dependencies
  .circleci/config.yml
  packages/babel-plugin-remove-graphql-queries/package.json
  packages/gatsby-plugin-gatsby-cloud/package.json
  starters/blog/package.json
  starters/default/package.json
  starters/gatsby-starter-wordpress-blog/package.json
  starters/hello-world/package.json
Labels: type: maintenance, bot: merge on green, status: needs core review

#33071 fix(gatsby-telemetry): don't require gatsby-cli
  packages/gatsby-telemetry/src/telemetry.ts
Labels: type: maintenance, bot: merge on green

#31247 chore(docs): Fix links in perf doc
  docs/docs/how-to/performance/improving-site-performance.md
Labels: type: documentation

#29031 chore(docs): Update GitHub Pages doc
  docs/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages.md
Labels: type: documentation

#33067 feat(gatsby): page engine
  packages/gatsby/cache-dir/page-ssr/index.d.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/client-assets-for-template.ts
  packages/gatsby/src/utils/page-data-helpers.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
  packages/gatsby/src/utils/page-ssr-module/entry.ts
  packages/gatsby/src/utils/static-query-utils.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: bot: merge on green

#33077 chore: remove gatsby-cloud-gatsby-plugin
  starters/blog/gatsby-config.js
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/default/gatsby-config.js
  starters/default/package-lock.json
  starters/default/package.json
Labels: type: maintenance

#33040 feat(gatsby-plugin-mdx): use subplugin annotation to use automatic subplugin module loading
  patches/v4/3-gatsby-plugin-mdx-subplugin.patch
Labels: bot: merge on green, topic: remark/mdx

#33039 feat(gatsby-transformer-remark): use subplugin annotation to use automatic subplugin module loading
  packages/gatsby-transformer-remark/src/create-schema-customization.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
  packages/gatsby-transformer-remark/src/gatsby-node.js
Labels: bot: merge on green, topic: remark/mdx

#32048 chore(gatsby-source-drupal): Document filtering temporary files
  packages/gatsby-source-drupal/README.md
Labels: topic: source-drupal

#33080 feat(gatsby-source-wordpress): Support on plugin init
  packages/gatsby-source-wordpress/src/constants.ts
  packages/gatsby-source-wordpress/src/gatsby-node.ts
Labels: topic: source-wordpress

#33081 chore: Reorder package.json entries & fix patches
  packages/babel-plugin-remove-graphql-queries/package.json
  packages/gatsby-plugin-no-sourcemaps/package.json
  packages/gatsby-plugin-schema-snapshot/package.json
  packages/gatsby-plugin-styletron/package.json
  patches/v4/1-lmdb-default.patch
  patches/v4/2-gatsby-peerdeps.patch
  patches/v4/4-gatsby-plugin-mdx-subplugin.patch
Labels: type: maintenance

#33083 chore: Update peril settings & delete unused rules
  peril.settings.json
  peril/README.md
  peril/rules/invite-collaborator.ts
  peril/rules/pull-request-on-starter.ts
  peril/rules/validate-yaml.ts
Labels: bot: merge on green, topic: automation

#33085 chore: Fix premajor script to find nvm
  scripts/release-next-major.js
Labels: topic: automation

#32896 feat(gatsby): enable SSR mode in develop & serve
  packages/gatsby/package.json
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/constants.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/query/types.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/arrow-fn/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/arrow-fn/output.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/combined-export/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/combined-export/output.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/function/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/function/output.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/options.json
  packages/gatsby/src/utils/babel/__tests__/index.js
  packages/gatsby/src/utils/babel/babel-plugin-remove-api.ts
  packages/gatsby/src/utils/find-page-by-path.ts
  packages/gatsby/src/utils/get-server-data.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/page-ssr-module/entry.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/webpack-error-utils.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/websocket-manager.ts
Labels: topic: render-mode

#33079 fix(gatsby-source-drupal): validate webhook bodies & updated node data
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: type: bug, topic: source-drupal

#33090 fix(gatsby): fix client-only-paths rendering in page engine
  packages/gatsby/src/utils/page-ssr-module/entry.ts
Labels: topic: render-mode

#33094 fix(patches): fix applying v4 patches
  patches/v4/0-node-version.patch
Labels: type: maintenance, bot: merge on green

#33088 fix(gatsby): Update redirects warning
  packages/gatsby/src/bootstrap/__tests__/redirects-writer.ts
  packages/gatsby/src/bootstrap/redirects-writer.ts
Labels: topic: core

#33099 fix(gatsby-source-drupal): guard against already deleted nodes
  packages/gatsby-source-drupal/src/utils.js
Labels: type: bug, topic: source-drupal

#33098 fix(gatsby): fix nesting of tracing spans + add docs for OpenTelemetry
  docs/docs/performance-tracing.md
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/query/file-parser.js
  packages/gatsby/src/query/query-compiler.js
Labels: type: bug, type: documentation, bot: merge on green

#33092 fix(gatsby): Don't bundle moment locale files
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: core

#32909 feat(gatsby-source-shopify): v4 compatibility through onPluginInit
  packages/gatsby-source-shopify/package.json
  packages/gatsby-source-shopify/src/error-map.ts
  packages/gatsby-source-shopify/src/gatsby-node.ts
  packages/gatsby-source-shopify/types/interface.d.ts
Labels: topic: source-shopify

#33114 fix(gatsby): fix onPluginInit api calls in engine
  packages/gatsby/src/schema/graphql-engine/entry.ts
Labels: status: triage needed

#33117 fix(gatsby): prevent stack overflow when writing page-data with DSG
  packages/gatsby/src/utils/page-data.ts
Labels: bot: merge on green

#32533 feat(gatsby): Add aggregation resolvers to group
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/__tests__/rebuild-schema.js
  packages/gatsby/src/schema/types/pagination.ts
Labels: topic: GraphQL, type: feature or enhancement

#33118 chore(docs): Correct gatsby-cloud plugin in tutorial part 3
  docs/docs/tutorial/part-3/index.mdx
Labels: type: documentation

#33125 chore: add other peerdeps to correct version Gatsby 4
  patches/v4/2-gatsby-peerdeps.patch
Labels: type: maintenance, gatsby 4

#33124 chore(gatsby-plugin-netlify): move to new repository
  packages/gatsby-plugin-netlify/.babelrc
  packages/gatsby-plugin-netlify/.gitignore
  packages/gatsby-plugin-netlify/.npmignore
  packages/gatsby-plugin-netlify/README.md
  packages/gatsby-plugin-netlify/index.js
  packages/gatsby-plugin-netlify/package.json
  packages/gatsby-plugin-netlify/src/__tests__/__snapshots__/build-headers-program.js.snap
  packages/gatsby-plugin-netlify/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-netlify/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-netlify/src/build-headers-program.js
  packages/gatsby-plugin-netlify/src/constants.js
  packages/gatsby-plugin-netlify/src/create-redirects.js
  packages/gatsby-plugin-netlify/src/gatsby-node.js
  packages/gatsby-plugin-netlify/src/plugin-data.js
  patches/v4/0-node-version.patch
  patches/v4/2-gatsby-peerdeps.patch
Labels: type: maintenance

#33136 fix(gatsby-plugin-gatsby-cloud): Emit CREATE_FILE_NODE in onPostBootstrap
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
Labels: bot: merge on green

#32291 fix(gatsby): Deprecate schema-related APIs in sourceNodes
  packages/gatsby/src/redux/actions/__tests__/restricted.js
  packages/gatsby/src/redux/actions/restricted.ts
Labels: topic: core

#33120 feat(gatsby-plugin-page-creator): Fix gatsby plugin page creator v4
  packages/gatsby-plugin-page-creator/package.json
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/bootstrap/load-config-and-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts
Labels: gatsby 4

#33127 chore(docs): Add note to Storybook guide about StaticImage
  docs/docs/how-to/testing/visual-testing-with-storybook.md
Labels: type: documentation

#33143 fix(gatsby-source-drupal): handle edge case with deleting nodes
  packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/article.json
  packages/gatsby-source-drupal/src/utils.js
Labels: type: bug, bot: merge on green, topic: source-drupal

#32513 chore(gatsby): add environment variable for setting tracing config file
  docs/docs/performance-tracing.md
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop-process.ts
Labels: bot: merge on green

#33147 feat(gatsby-plugin-styled-components): Add ability to disable vendor prefixes
  packages/gatsby-plugin-styled-components/README.md
  packages/gatsby-plugin-styled-components/src/gatsby-browser.js
  packages/gatsby-plugin-styled-components/src/gatsby-node.js
  packages/gatsby-plugin-styled-components/src/gatsby-ssr.js
Labels: bot: merge on green, topic: plugins-styling

#33149 feat(gatsby-transformer-documentationjs): move createTypes to createSchemaCustomization
  packages/gatsby-transformer-documentationjs/src/gatsby-node.js
Labels: gatsby 4

#33150 Remove <title> from inside <main>
  examples/functions-hello-world/src/pages/index.js
Labels: status: triage needed

#33156 chore(gatsby-plugin-gatsby-cloud): fix copy type file
  packages/gatsby-plugin-gatsby-cloud/package.json
  yarn.lock
Labels: type: maintenance, bot: merge on green

#33148 docs: Fix broken link on Getting Started with MDX page
  docs/docs/mdx/getting-started.md
Labels: type: documentation, bot: merge on green

#33134 fix(gatsby): fix hydration flicker on initial render of ssr page
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/build-headers-program.js.snap
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/utils/page-ssr-module/entry.ts
Labels: topic: render-mode

#33126 chore(gatsby): add webpack file to export same version
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  packages/gatsby/webpack.d.ts
  packages/gatsby/webpack.js
  patches/v4/5-plugins-use-webpack-from-gatsby.patch
Labels: type: maintenance

#33142 feat(gatsby-source-drupal): Add tracing for full/delta fetches and http requests
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby/src/utils/api-runner-node.js
  yarn.lock
Labels: type: bug, topic: source-drupal

#33122 fix(gatsby): Assign parentSpan to activities that were missing them
  packages/gatsby/index.d.ts
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
  packages/gatsby/src/redux/plugin-runner.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/create-pages.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/services/source-nodes.ts
  packages/gatsby/src/state-machines/query-running/actions.ts
  packages/gatsby/src/utils/page-data.ts
Labels: type: bug

#33159 feat(gatsby): let serve use getServerData headers
  packages/gatsby/cache-dir/page-ssr/index.d.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/utils/page-ssr-module/entry.ts
Labels: topic: render-mode

#33164 fix(gatsby): add webpack export to npm
  packages/gatsby/package.json
Labels: type: maintenance, bot: merge on green

#33173 fix(gatsby): only show peerdep warnings outside of workers
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: type: maintenance

#33171 test: adjust tests after the bump
  .circleci/config.yml
  packages/babel-preset-gatsby-package/lib/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/package.json
  packages/gatsby-cli/src/index.ts
  packages/gatsby-plugin-mdx/__tests__/gatsby-node.js
  packages/gatsby-plugin-mdx/utils/__tests__/gen-mdx.js
  packages/gatsby-plugin-utils/src/test-plugin-options-schema.ts
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/src/bootstrap/__tests__/redirects-writer.ts
  packages/gatsby/src/bootstrap/__tests__/requires-writer.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/commands/__tests__/build-utils.ts
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/__tests__/__snapshots__/pages.ts.snap
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/__tests__/pages.ts
  packages/gatsby/src/services/__tests__/create-pages.ts
  packages/gatsby/src/utils/__tests__/get-page-data.ts
Labels: status: blocked

#33180 fix: make sure we emit ENGINES_READY after build-ssr
  packages/gatsby/src/commands/build.ts
Labels: topic: render-mode

#33168 chore: update tutorial for v4
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/whats-next/index.mdx
Labels: type: documentation

#33181 fix(gatsby-source-drupal): check relationships type exists on node before filtering
  packages/gatsby-source-drupal/src/utils.js
Labels: type: bug, topic: source-drupal

#33054 feat(gatsby): split page-renderer per route
  docs/docs/html-generation.md
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/develop-static-entry.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/constants.ts
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
  packages/gatsby/src/utils/page-ssr-module/entry.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/webpack-error-utils.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: type: maintenance, topic: webpack/babel

#33161 feat(gatsby-core-utils): add fetch mutex for PQR
  .eslintrc.js
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
  packages/gatsby/index.d.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/pool.ts
  types/gatsby-monorepo/global.d.ts
Labels: topic: data, gatsby 4

#33187 feat(pqr): print message pointing to pqr feedback if running queries throws
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/utils/worker/pool.ts
Labels: topic: GraphQL

#33189 chore(gatsby): move to DSG instead of DSR
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/routes.js
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/types.ts
Labels: type: maintenance

#33155 feat(gatsby): provide fetch in ssr bundle by default
  packages/gatsby/package.json
  packages/gatsby/src/internal-plugins/bundle-optimisations/gatsby-node.js
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: gatsby 4, topic: render-mode

#33193 fix(eslint): don't warn about getServerData exports
  packages/gatsby/src/utils/eslint-rules/__tests__/limited-exports-page-templates.ts
  packages/gatsby/src/utils/eslint-rules/limited-exports-page-templates.ts
Labels: topic: render-mode

#33188 feat(gatsby-cli): enable gatsby pages output
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/pageTree.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/context.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/index.tsx
  packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
  packages/gatsby-cli/src/util/generate-page-tree.ts
  yarn.lock
Labels: type: feature or enhancement

#33196 fix(gatsby): fix hydration flicker on initial render of ssr page for more cases
  packages/gatsby/cache-dir/loader.js
Labels: topic: render-mode

#33177 chore(docs): create v4 source plugin migration guide
  docs/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4.mdx
Labels: type: documentation

#33201 chore: use zz-next as prerelease id to make sure it's last
  package.json
Labels: status: triage needed

#33200 fix(gatsby-cli): fix pagetree global cli
  packages/gatsby-cli/src/reporter/constants.ts
  packages/gatsby-cli/src/reporter/loggers/ink/components/develop.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/pageTree.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/context.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/index.tsx
  packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
  packages/gatsby-cli/src/reporter/redux/actions.ts
  packages/gatsby-cli/src/reporter/redux/index.ts
  packages/gatsby-cli/src/reporter/redux/internal-actions.ts
  packages/gatsby-cli/src/reporter/redux/reducers/logs.ts
  packages/gatsby-cli/src/reporter/redux/reducers/page-tree.ts
  packages/gatsby-cli/src/reporter/redux/types.ts
  packages/gatsby-cli/src/reporter/reporter.ts
  packages/gatsby-cli/src/reporter/types.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/redux/reducers/index.ts
Labels: status: triage needed

#33113 chore(docs): How-To DSG
  docs/docs/how-to/rendering-options/using-deferred-static-generation.md
Labels: type: documentation

#33111 chore(docs): How-To SSR
  docs/docs/how-to/rendering-options/using-server-side-rendering.md
Labels: type: documentation

#33128 chore(docs): Reference guides on SSR & DSG
  docs/docs/reference/rendering-options/deferred-static-generation.md
  docs/docs/reference/rendering-options/server-side-rendering.md
Labels: type: documentation

#33129 chore(docs): Rendering Options Conceptual Guide
  docs/docs/conceptual/rendering-options.mdx
  docs/docs/images/dsg-diagram.jpg
  docs/docs/images/ssg-diagram.jpg
  docs/docs/images/ssr-diagram.jpg
Labels: type: documentation

#33108 chore(docs): v4 Migration Guide
  docs/docs/reference/release-notes/migrating-from-v3-to-v4.md
Labels: type: documentation

#33227 fix(gatsby): allow null plugin option values on build
  packages/gatsby/src/schema/graphql-engine/print-plugins.ts
Labels: topic: render-mode

#33234 test(structured-logging): adjust for v4
  integration-tests/structured-logging/__tests__/to-do.js
  packages/gatsby/src/commands/build.ts
Labels: topic: automation

#33235 test(cache-resilience): adjust for v4/lmdb
  integration-tests/cache-resilience/gatsby-node.js
Labels: topic: automation

#33231 chore(docs): Release notes for 3.14
  docs/docs/reference/release-notes/v3.14/index.md
Labels: type: documentation

#33240 chore(docs): fix formatting
  docs/docs/reference/release-notes/v3.14/index.md
Labels: type: documentation

#33225 fix(gatsby-source-drupal): some entities don't have attributes so add tests with this
  packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/image-gallary.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: type: bug, topic: source-drupal

#33244 chore(gatsby): upgrade lmbd to 1.6.8
  packages/gatsby/package.json
  yarn.lock
Labels: status: triage needed

#33202 fix(gatsby-cli): make sure to put all yurnalist logs in one log
  packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
Labels: type: bug, bot: merge on green

#33252 chore(starters): Make `theme_color` optional
  starters/blog/gatsby-config.js
  starters/default/gatsby-config.js
Labels: topic: DX

#33255 fix(gatsby): fix codeframe generation for html errors
  packages/gatsby-cli/src/reporter/prepare-stack-trace.ts
Labels: topic: cli

#33236 fix(contentful): createUrl now enforces https protocol
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/extend-node-type.js.snap
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-contentful/src/download-contentful-assets.js
  packages/gatsby-source-contentful/src/extend-node-type.js
  yarn.lock
Labels: bot: merge on green, topic: source-contentful

#33258 tests: fix functions integration tests
  packages/gatsby/src/utils/start-server.ts
Labels: type: maintenance

#33261 chore(gatsby-source-contentful): Fix RichText example
  packages/gatsby-source-contentful/README.md
Labels: type: documentation

#33259 fix(gatsby): correct the definition for getNode
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#33270 chore(gatsby-telemetry): remove deps that are global
  packages/gatsby-telemetry/src/__tests__/telemetry.ts
Labels: type: maintenance

#33263 feature(docs): Document how functions work in plugins/themes
  docs/docs/reference/functions/getting-started.md
Labels: type: documentation, status: needs docs review

#33256 chore: Fix tests for WordPress, Contentful & update CircleCI
  .circleci/config.yml
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-wordpress/src/steps/process-and-validate-plugin-options.ts
Labels: topic: source-wordpress

#33280 chore(docs): Grammar fix in using-deferred-static-generation
  docs/docs/how-to/rendering-options/using-deferred-static-generation.md
Labels: type: documentation

#33279 fix(docs): Remove unneeded/wrong fields from createNode example
  docs/docs/creating-a-source-plugin.md
Labels: type: documentation

#33268 feat(gatsby): don't infer pageContext
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
  packages/gatsby/src/schema/types/built-in-types.ts
Labels: type: maintenance, topic: GraphQL

#33214 feat(gatsby): add webpack-logging plugin to Gatsby for debugging
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/webpack-logging.ts
  tsconfig.json
Labels: topic: webpack/babel

#33289 fix(gatsby-source-shopify): inconsistencies in shopify docs
  docs/docs/building-an-ecommerce-site-with-shopify.md
  packages/gatsby-source-shopify/README.md
Labels: topic: source-shopify

#33237 feat(gatsby-source-wordpress): allow 401 option
  packages/gatsby-source-wordpress/docs/features/media-item-processing.md
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/src/models/gatsby-api.ts
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-local-file-node.js
Labels: bot: merge on green

#33138 feat(gatsby-source-wordpress): Add gatsby plugin image
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/gatsby-source-wordpress/test-fns/gatsby-image.js
  packages/gatsby-source-wordpress/.babelrc.js
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/gatsby-browser.js
  packages/gatsby-source-wordpress/gatsby-config.js
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-source-wordpress/src/gatsby-browser.ts
  packages/gatsby-source-wordpress/src/models/gatsby-api.ts
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
  packages/gatsby-source-wordpress/style.css
  packages/gatsby-source-wordpress/tsconfig.json
  yarn.lock
Labels: topic: source-wordpress

#33287 gatsby-plugin-feed: Make `feeds` & `serialize` required
  packages/gatsby-plugin-feed/README.md
  packages/gatsby-plugin-feed/src/plugin-options.js
Labels: topic: plugins

#33294 chore(docs): fix typo in site perfomance guide
  docs/docs/how-to/performance/improving-site-performance.md
Labels: type: documentation

#33298 chore(docs): Improve Shopify guide
  docs/docs/building-an-ecommerce-site-with-shopify.md
Labels: type: documentation

#33296 chore(gatsby-source-wordpress): refactor logic for supported node api names
  packages/gatsby-source-wordpress/src/constants.ts
  packages/gatsby-source-wordpress/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/utils/run-steps.ts
Labels: status: triage needed

#33286 gatsby: Remove deprecation warnings for touchNode/deleteNode
  packages/gatsby/src/datastore/__tests__/nodes.js
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/redux/__tests__/nodes.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/schema/infer/__tests__/infer.js
Labels: topic: core

#33295 feat(gatsby-transformer-remark): Remove two obsolete options & improve README
  packages/gatsby-transformer-remark/README.md
  packages/gatsby-transformer-remark/src/gatsby-node.js
Labels: topic: remark/mdx

#33275 feat: move away from old default uuid
  packages/create-gatsby/package.json
  packages/create-gatsby/src/tracking.ts
  packages/create-gatsby/src/types.d.ts
  packages/gatsby-cli/src/reporter/redux/internal-actions.ts
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/__tests__/uuid.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-core-utils/src/uuid.ts
  packages/gatsby-plugin-benchmark-reporting/package.json
  packages/gatsby-plugin-benchmark-reporting/src/gatsby-node.js
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/gatsby-node.js
  packages/gatsby-telemetry/package.json
  packages/gatsby-telemetry/src/__tests__/telemetry.ts
  packages/gatsby-telemetry/src/in-memory-store.ts
  packages/gatsby-telemetry/src/telemetry.ts
  packages/gatsby/package.json
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/redux/__tests__/jobsv2.js
  packages/gatsby/src/utils/create-node-id.ts
  packages/gatsby/src/utils/jobs/__tests__/manager.js
  packages/gatsby/src/utils/jobs/manager.ts
  packages/gatsby/src/utils/start-server.ts
  yarn.lock
Labels: type: maintenance

#33310 fix(gatsby-source-graphql): support Gatsby 4
  packages/gatsby-source-graphql/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-source-graphql/src/__tests__/gatsby-node.js
  packages/gatsby-source-graphql/src/gatsby-node.js
Labels: topic: GraphQL

#33291 chore(docs): Tutorial walkthrough feedback tweaks
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-6/index.mdx
Labels: type: documentation

#33319 feat(gatsby): drop SitePage inference and schema update
  integration-tests/gatsby-cli/__tests__/build.js
  integration-tests/gatsby-cli/__tests__/develop.js
  integration-tests/gatsby-cli/__tests__/repl.js
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/__tests__/rebuild-schema.js
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
  packages/gatsby/src/schema/graphql-engine/entry.ts
  packages/gatsby/src/schema/index.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/built-in-types.ts
  packages/gatsby/src/services/index.ts
  packages/gatsby/src/services/rebuild-schema-with-site-pages.ts
  packages/gatsby/src/state-machines/data-layer/index.ts
  packages/gatsby/src/state-machines/data-layer/services.ts
  packages/gatsby/src/state-machines/query-running/services.ts
  packages/gatsby/src/utils/worker/child/schema.ts
Labels: topic: GraphQL

#33278 feat(gatsby): remove gatsby-admin
  deprecated-packages/gatsby-admin/.eslintignore
  deprecated-packages/gatsby-admin/CHANGELOG.md
  deprecated-packages/gatsby-admin/README.md
  deprecated-packages/gatsby-admin/gatsby-browser.js
  deprecated-packages/gatsby-admin/gatsby-config.js
  deprecated-packages/gatsby-admin/gatsby-node.js
  deprecated-packages/gatsby-admin/gatsby-ssr.js
  deprecated-packages/gatsby-admin/index.js
  deprecated-packages/gatsby-admin/package.json
  deprecated-packages/gatsby-admin/src/bolt.svg
  deprecated-packages/gatsby-admin/src/components/error-tracker.tsx
  deprecated-packages/gatsby-admin/src/components/gatsby-monogram.tsx
  deprecated-packages/gatsby-admin/src/components/instantsearch-provider.tsx
  deprecated-packages/gatsby-admin/src/components/layout.tsx
  deprecated-packages/gatsby-admin/src/components/navbar.tsx
  deprecated-packages/gatsby-admin/src/components/pageview-tracker.tsx
  deprecated-packages/gatsby-admin/src/components/plugin-search.tsx
  deprecated-packages/gatsby-admin/src/components/providers.tsx
  deprecated-packages/gatsby-admin/src/components/recipes-gui/code-diff.js
  deprecated-packages/gatsby-admin/src/components/recipes-gui/index.js
  deprecated-packages/gatsby-admin/src/components/recipes-gui/recipe-step.js
  deprecated-packages/gatsby-admin/src/components/recipes-gui/resource-message.js
  deprecated-packages/gatsby-admin/src/components/recipes-gui/utils.js
  deprecated-packages/gatsby-admin/src/components/recipes-gui/welcome-message.js
  deprecated-packages/gatsby-admin/src/components/services-provider.tsx
  deprecated-packages/gatsby-admin/src/external-link.svg
  deprecated-packages/gatsby-admin/src/github.svg
  deprecated-packages/gatsby-admin/src/graphql.svg
  deprecated-packages/gatsby-admin/src/pages/index.tsx
  deprecated-packages/gatsby-admin/src/pages/pages.tsx
  deprecated-packages/gatsby-admin/src/pages/plugins.tsx
  deprecated-packages/gatsby-admin/src/pages/recipe.js
  deprecated-packages/gatsby-admin/src/pages/recipes.tsx
  deprecated-packages/gatsby-admin/src/prism-theme.tsx
  deprecated-packages/gatsby-admin/src/skaterboi.svg
  deprecated-packages/gatsby-admin/src/sparkles.svg
  deprecated-packages/gatsby-admin/src/svg.d.ts
  deprecated-packages/gatsby-admin/src/urql-client.ts
  deprecated-packages/gatsby-admin/src/utils/algolia-config.ts
  deprecated-packages/gatsby-admin/src/utils/is-official-package.ts
  deprecated-packages/gatsby-admin/src/utils/use-develop-logs.ts
  deprecated-packages/gatsby-admin/src/utils/use-npm-data.tsx
  deprecated-packages/gatsby-admin/src/utils/use-telemetry.tsx
  deprecated-packages/gatsby-admin/static/favicon.ico
  deprecated-packages/gatsby-admin/tsconfig.json
  packages/gatsby-admin/gatsby-browser.js
  packages/gatsby-admin/gatsby-node.js
  packages/gatsby-admin/index.js
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby/package.json
  packages/gatsby/src/utils/develop-proxy.ts
  yarn.lock
Labels: type: maintenance, bot: merge on green

#33328 fix(gatsby-source-drupal): Clone nodes before adding back references so Gatsby knows the node has changed (so knows to re-run queries)
  packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: type: bug, topic: source-drupal

#33322 chore(gatsby): Fix static query types, document useStaticQuery
  packages/gatsby/index.d.ts
Labels: topic: GraphQL, topic: TypeScript

#33331 fix(gatsby): Fix typos in build output
  packages/gatsby-cli/src/reporter/loggers/ink/components/pageTree.tsx
  packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
Labels: status: triage needed
