Repository gatsbyjs/gatsby, pull requests merged in 2021-05, with the labels that each got.

#31173 Update Cloudflare Workers Sites deployment documentation
  docs/docs/deploying-to-cloudflare-workers.md
Labels: bot: merge on green, type: documentation

#31130 Allows sitemap output on root of public folder
  packages/gatsby-plugin-sitemap/src/__tests__/__snapshots__/gatsby-ssr.js.snap
  packages/gatsby-plugin-sitemap/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-sitemap/src/gatsby-ssr.js
Labels: status: awaiting reviewer response, topic: sitemap, type: bug

#31069 Don't remove gatsby-source-filesystem
  packages/gatsby/src/services/initialize.ts
Labels: topic: scaling builds

#31175 add on initial client render to the docs
  docs/docs/how-to/performance/improving-site-performance.md
Labels: status: triage needed

#31177 fix(gatsby-plugin-netlify-cms): Fix typo in semver
  packages/gatsby-plugin-netlify-cms/package.json
  yarn.lock
Labels: type: maintenance

#31136 chore(docs): GATSBY_ACTIVE_ENV is undefined by default
  docs/docs/how-to/local-development/environment-variables.md
Labels: type: documentation

#31186 chore: Fix grammar error in README
  README.md
  packages/gatsby/README.md
Labels: type: documentation

#31182 fix(gatsby): add generic type to GatsbyFunctionResponse
  packages/gatsby/index.d.ts
Labels: topic: TypeScript, topic: functions

#31188 fix(gatsby-plugin-image): add @babel/core peer dependency
  packages/gatsby-plugin-image/package.json
Labels: topic: images/media

#31176 fix(gatsby): upgrade css-minimizer-webpack-plugin to v2
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#30581 fix(gatsby): rehydration issue in Dev404Page with DEV_SSR
  packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js
Labels: topic: ssr

#31134 feat(gatsby): speedup cli startup by lazily requiring modules
  packages/gatsby-cli/src/create-cli.ts
Labels: topic: scaling builds

#31142 chore(gatsby-source-wordpress): run incremental tests where values change based on the WARM_CACHE env…
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/__tests__/index.js
  integration-tests/gatsby-source-wordpress/docker/seed/backup.sql
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/filtered-type-defs.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/increment-remote-data.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/incremental-it.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/queries.js
Labels: bot: merge on green, topic: WordPress

#31196 fix(gatsby-telemetry): Read installedGatsbyVersion correctly for workspaces
  packages/gatsby-telemetry/src/telemetry.ts
Labels: status: triage needed

#31198 docs: Updates file name suggestion in babel.md
  docs/docs/how-to/custom-configuration/babel.md
Labels: status: triage needed

#31210 fix(gatsby-plugin-mdx): Img w/ lessBabel option in src/pages not working
  packages/gatsby-plugin-mdx/loaders/mdx-loader.js
Labels: topic: MDX

#31234 test: unskip eslint rules for fast refresh tests
  e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
  e2e-tests/development-runtime/cypress/integration/eslint-rules/no-anonymous-exports-page-templates.js
Labels: topic: hot reloading

#31236 just testing changes to 31104
  packages/gatsby/src/internal-plugins/prod-404/gatsby-node.js
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/api-runner-node.js
Labels: status: blocked

#31104 perf(gatsby): Create page object & SitePage node in same action creator
  benchmarks/create-pages/package.json
  integration-tests/artifacts/.gitignore
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/internal-plugins/prod-404/gatsby-node.js
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/__tests__/pages.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/plugin-runner.ts
  packages/gatsby/src/redux/reducers/pages.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/api-runner-node.js
Labels: topic: scaling builds

#31250 chore(gatsby-source-wordpress): restore plugin tests
  integration-tests/gatsby-source-wordpress/.env.test
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/docker/seed/backup.sql
  integration-tests/gatsby-source-wordpress/docker/wordpress/install-wp-graphql-plugins.sh
  integration-tests/gatsby-source-wordpress/docker/wp-cli/start.sh
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/queries.js
Labels: topic: WordPress

#31258 test: Conditionally test ESLint rules
  e2e-tests/development-runtime/.eslintignore
  e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
  e2e-tests/development-runtime/cypress/integration/eslint-rules/no-anonymous-exports-page-templates.js
  e2e-tests/development-runtime/src/pages/eslint-rules/limited-exports-page-templates.js
  e2e-tests/development-runtime/src/pages/eslint-rules/no-anonymous-exports-page-templates-function.js
  e2e-tests/development-runtime/src/pages/eslint-rules/no-anonymous-exports-page-templates.js
Labels: topic: automation

#31261 feat(benchmarks): add filters and sorting benchmark
  benchmarks/query-filters-sort/README.md
  benchmarks/query-filters-sort/gatsby-config.js
  benchmarks/query-filters-sort/gatsby-node.js
  benchmarks/query-filters-sort/package.json
  benchmarks/query-filters-sort/src/pages/index.js
  benchmarks/query-filters-sort/src/templates/elemMatch-eq.js
  benchmarks/query-filters-sort/src/templates/eq.js
  benchmarks/query-filters-sort/src/templates/gt-lt.js
  benchmarks/query-filters-sort/src/templates/gt.js
  benchmarks/query-filters-sort/src/templates/in.js
  benchmarks/query-filters-sort/src/templates/lt.js
  benchmarks/query-filters-sort/src/templates/ne.js
  benchmarks/query-filters-sort/src/templates/nin.js
  benchmarks/query-filters-sort/src/templates/regex.js
Labels: topic: benchmarks

#31122 refactor: align Rich Text field structure to Contentful GraphQL API
  e2e-tests/contentful/src/pages/rich-text.js
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__tests__/rich-text.js
  packages/gatsby-source-contentful/src/generate-schema.js
  packages/gatsby-source-contentful/src/rich-text.js
  yarn.lock
Labels: breaking change, topic: Contentful

#30451 fix(gatsby-plugin-image): Breakpoints prop not being passed to StaticImage component
  packages/gatsby-plugin-image/src/babel-helpers.ts
Labels: topic: images/media

#31115 refactor: flatten Contentful asset data structure to match GraphQL API schema
  e2e-tests/contentful/src/pages/gatsby-image.js
  e2e-tests/contentful/src/pages/gatsby-plugin-image.js
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/cache-image.js
  packages/gatsby-source-contentful/src/extend-node-type.js
  packages/gatsby-source-contentful/src/generate-schema.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-transformer-sqip/src/extend-node-type.js
Labels: breaking change

#31265 feat(gatsby): Don't send error for function errors if headers are already sent
  integration-tests/functions/package.json
  integration-tests/functions/src/api/error-send-function-twice.js
  integration-tests/functions/test-helpers.js
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: topic: functions

#31257 chore(docs): Add Plugin updates discussion to "maintaining a plugin"
  docs/docs/how-to/plugins-and-themes/maintaining-a-plugin.md
Labels: type: documentation

#28848 chore(docs): Update 21yunbox guide
  docs/docs/deploying-to-21yunbox.md
  docs/docs/preparing-for-deployment.md
Labels: type: documentation

#29237 chore(docs): Update sourcing-from-prismic
  docs/docs/how-to/sourcing-data/sourcing-from-prismic.md
Labels: status: needs docs review

#29737 docs: Update example to apollo-client v3
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: status: needs docs review, type: documentation

#30819 fix(gatsby): update plugin api types
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#30590 feat(gatsby-plugin-image): Export ImageDataLike type
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/index.ts
Labels: topic: images/media

#31269 perf(gatsby): use fastq instead of better-queue + refactor
  packages/gatsby/package.json
  packages/gatsby/src/query/__tests__/better-queue-custom-store.ts
  packages/gatsby/src/query/better-queue-custom-store.ts
  packages/gatsby/src/query/index.js
  packages/gatsby/src/query/queue.ts
Labels: topic: scaling builds

#31096 docs: Add image plugin architecture doc
  docs/docs/conceptual/image-plugin-architecture.md
Labels: type: documentation

#29798 chore(docs): Update MDX frontmatter for programmatic pages
  docs/docs/mdx/programmatically-creating-pages.md
Labels: topic: MDX, type: documentation

#29460 chore(docs): Update "Adding Search with Algolia" guide
  docs/docs/adding-search-with-algolia.md
Labels: type: documentation

#30417 fix(gatsby-plugin-image): print error details
  packages/gatsby-plugin-image/src/node-apis/image-processing.ts
Labels: topic: images/media

#30344 docs(gatsby-plugin-image): Add docs for customizing default options
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
  packages/gatsby-plugin-image/README.md
Labels: topic: images/media, type: documentation

#31285 chore: run yarn deduplicate
  yarn.lock
Labels: bot: merge on green, type: maintenance

#31287 Updates Shopify README
  packages/gatsby-source-shopify/README.md
Labels: status: triage needed

#31289 chore: update renovatebot config to support more packages
  renovate.json5
Labels: type: maintenance

#31298 fix(tests): update cheerio snapshots
  packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-remark-copy-linked-files/package.json
  packages/gatsby-remark-graphviz/package.json
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-remark-images-contentful/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/package.json
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/package.json
  packages/gatsby-remark-responsive-iframe/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby/src/bootstrap/__tests__/__snapshots__/resolve-module-exports.js.snap
  yarn.lock
Labels: type: maintenance

#31299 fix(gatsby): don't print out flag suggestions if none are enabled or opted-in
  packages/gatsby/src/utils/__tests__/handle-flags.ts
  packages/gatsby/src/utils/handle-flags.ts
Labels: topic: cli

#31061 feat(gatsby): New overlay for DEV_SSR
  e2e-tests/development-runtime/cypress/integration/navigation/redirect.js
  e2e-tests/development-runtime/cypress/integration/page-not-found/404.js
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
  integration-tests/ssr/__tests__/ssr.js
  integration-tests/ssr/jest.config.js
  integration-tests/ssr/package.json
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/fast-refresh-overlay/components/dev-ssr-error.js
  packages/gatsby/cache-dir/fast-refresh-overlay/components/overlay.js
  packages/gatsby/cache-dir/fast-refresh-overlay/index.js
  packages/gatsby/cache-dir/fast-refresh-overlay/style.js
  packages/gatsby/cache-dir/fast-refresh-overlay/utils.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/package.json
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/utils/dev-ssr/__tests__/develop-html-route.ts
  packages/gatsby/src/utils/dev-ssr/__tests__/fixtures/error-object.js
  packages/gatsby/src/utils/dev-ssr/develop-html-route.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/start-server.ts
Labels: topic: ssr

#31345 fix(gatsby): only load gatsby-plugin-gatsby-cloud on cloud
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/load.ts
Labels: type: maintenance

#31354 feat(docs): Add notice that functions need flag enabled + simplify description of req/res
  docs/docs/how-to/functions/getting-started.md
Labels: topic: functions

#31353 feat(gatsby): Functions aren't GA but they're not longer EXPERIMENTAL
  packages/gatsby/src/utils/flags.ts
Labels: topic: functions

#31352 feat(gatsby): change bgcolor of 'EXPERIMENTAL' label so it does look like an error
  packages/gatsby/src/utils/handle-flags.ts
Labels: type: maintenance

#31358 fix(gatsby): Fixes incorrect type
  packages/gatsby/index.d.ts
  packages/gatsby/package.json
  tsconfig.json
Labels: topic: TypeScript

#31373 docs(tutorial): rewrite part 2
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/deployment-workflow.png
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/about-page-with-layout.png
  docs/docs/tutorial/part-2/about-page-with-link.png
  docs/docs/tutorial/part-2/about-page.png
  docs/docs/tutorial/part-2/children-example.png
  docs/docs/tutorial/part-2/component-with-props.png
  docs/docs/tutorial/part-2/component-without-props.png
  docs/docs/tutorial/part-2/index-page-container-styled.png
  docs/docs/tutorial/part-2/index-page-styled.png
  docs/docs/tutorial/part-2/index-page-with-layout.png
  docs/docs/tutorial/part-2/index-page-with-link.png
  docs/docs/tutorial/part-2/index-page.png
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-2/ui-built-from-components.png
Labels: type: documentation

#30843 docs: v3 Tutorial
  docs/docs/tutorial/part-0/05-gatsby-help.png
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/01-create-a-site-button.png
  docs/docs/tutorial/part-1/02-import-a-git-repo.png
  docs/docs/tutorial/part-1/03-select-a-git-provider.png
  docs/docs/tutorial/part-1/04-select-destination.png
  docs/docs/tutorial/part-1/05-github-gatsby-cloud-permissions.png
  docs/docs/tutorial/part-1/06-select-repository.png
  docs/docs/tutorial/part-1/07-add-site-details.png
  docs/docs/tutorial/part-1/08-optional-integrations.png
  docs/docs/tutorial/part-1/09-setup.png
  docs/docs/tutorial/part-1/10-site-page.png
  docs/docs/tutorial/part-1/deployment-workflow.png
  docs/docs/tutorial/part-1/gatsby-new-cli.png
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-1/localhost-new-site.png
  docs/docs/tutorial/part-1/new-repo-button.png
  docs/docs/tutorial/part-1/new-repo-options.png
  docs/docs/tutorial/part-1/turn-on-hosting.png
  docs/docs/tutorial/part-2/about-page-with-layout.png
  docs/docs/tutorial/part-2/about-page-with-link.png
  docs/docs/tutorial/part-2/about-page.png
  docs/docs/tutorial/part-2/children-example.png
  docs/docs/tutorial/part-2/component-with-props.png
  docs/docs/tutorial/part-2/component-without-props.png
  docs/docs/tutorial/part-2/index-page-container-styled.png
  docs/docs/tutorial/part-2/index-page-styled.png
  docs/docs/tutorial/part-2/index-page-with-layout.png
  docs/docs/tutorial/part-2/index-page-with-link.png
  docs/docs/tutorial/part-2/index-page.png
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-2/ui-built-from-components.png
Labels: type: documentation

#31376 feat(docs): Add examples to functions getting started page
  docs/docs/how-to/functions/getting-started.md
Labels: type: documentation

#31400 feat(docs): Add more links to examples
  docs/docs/how-to/adding-common-features/adding-forms.md
  docs/docs/how-to/functions/getting-started.md
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
Labels: type: documentation

#31318 fix(wordpress-source-plugin): create nodes properly for images who exceed maxFileSizeBytes
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/docker/seed/backup.sql
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/get-gatsby-process.js
  packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md
  packages/gatsby-source-wordpress/docs/tests.md
  packages/gatsby-source-wordpress/docs/tutorials/transforming-data.md
  packages/gatsby-source-wordpress/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/models/gatsby-api.ts
  packages/gatsby-source-wordpress/src/models/index.ts
  packages/gatsby-source-wordpress/src/models/post-build-warning-logs.ts
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/type-filters.js
  packages/gatsby-source-wordpress/src/steps/index.ts
  packages/gatsby-source-wordpress/src/steps/log-post-build-warnings.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-local-file-node.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
Labels: topic: WordPress

#31404 chore(docs): Fix missing closing ```
  docs/docs/tutorial/part-2/index.mdx
Labels: status: triage needed

#31405 Update typo in docs
  packages/gatsby-source-wordpress/docs/tutorials/configuring-wp-gatsby.md
Labels: status: triage needed

#31401 feat(gatsby): Only load gatsby-recipes in develop if Admin is enabled
  packages/gatsby-cli/src/create-cli.ts
Labels: topic: recipes

#31396 fix(gatsby-plugin-mdx): fix gatsby develop on windows
  packages/gatsby-plugin-mdx/loaders/mdx-loader.js
Labels: topic: MDX, topic: windows*

#31359 chore(docs): Correct image guide on CSS-in-JS usage
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
Labels: topic: images/media, type: documentation

#31426 fix(gatsby-cli): Switch host env to GATSBY_ prefix
  packages/gatsby-cli/README.md
  packages/gatsby-cli/src/create-cli.ts
Labels: topic: cli

#31429 chore(docs): Update "choosing a CMS"
  docs/docs/conceptual/choosing-a-cms.md
Labels: type: documentation

#31431 chore(gatsby-plugin-google-gtag): Fix typo
  packages/gatsby-plugin-google-gtag/README.md
Labels: topic: analytics plugins, type: documentation

#31422 docs(tutorial): add UTM param to Gatsby Cloud links
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
Labels: type: documentation

#31446 fix(gatsby-plugin-netlify-cms): use friendly-errors-webpack-plugin package that satisfies webpack@5 peerDependency
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  yarn.lock
Labels: topic: netlify

#31184 fix(gatsby-plugin-sitemap): Sitemap path bug
  packages/gatsby-plugin-sitemap/package.json
  packages/gatsby-plugin-sitemap/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
  yarn.lock
Labels: topic: sitemap, type: bug

#31448 fix(gatsby-plugin-sitemap): Remove reporter.verbose calls
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
Labels: bot: merge on green, topic: sitemap

#31366 fix(gatsby): preload and prefetches check for in-browser redirects
  e2e-tests/development-runtime/cypress/integration/navigation/redirect.js
  e2e-tests/production-runtime/cypress/integration/redirects.js
  e2e-tests/production-runtime/src/pages/redirect-links.js
  packages/gatsby/cache-dir/find-path.js
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/cache-dir/redirect-utils.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/__tests__/redirects-writer.ts
  packages/gatsby/src/bootstrap/redirects-writer.ts
Labels: topic: reach/router and navigation

#31453 feat(docs): Add sample form/function code to the function docs
  docs/docs/how-to/functions/getting-started.md
Labels: topic: functions, type: documentation

#31413 fix(gatsby-source-wordpress): Remove search and replace regex literal recommendation
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.ts
Labels: topic: WordPress

#31460 chore(docs): Fixing JSON in configuration options
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
Labels: type: documentation

#31447 chore: Remove `gatsby-starter-mdx-basic`
  starters/gatsby-starter-mdx-basic/.gitignore
  starters/gatsby-starter-mdx-basic/LICENSE
  starters/gatsby-starter-mdx-basic/README.md
  starters/gatsby-starter-mdx-basic/gatsby-config.js
  starters/gatsby-starter-mdx-basic/package-lock.json
  starters/gatsby-starter-mdx-basic/package.json
  starters/gatsby-starter-mdx-basic/src/components/header.js
  starters/gatsby-starter-mdx-basic/src/components/image.js
  starters/gatsby-starter-mdx-basic/src/components/layout.css
  starters/gatsby-starter-mdx-basic/src/components/layout.js
  starters/gatsby-starter-mdx-basic/src/components/seo.js
  starters/gatsby-starter-mdx-basic/src/images/gatsby-astronaut.png
  starters/gatsby-starter-mdx-basic/src/images/gatsby-icon.png
  starters/gatsby-starter-mdx-basic/src/pages/404.js
  starters/gatsby-starter-mdx-basic/src/pages/index.mdx
  starters/gatsby-starter-mdx-basic/src/pages/page-2.mdx
Labels: type: maintenance

#31466 feat(gatsby): Support Functions in plugins
  e2e-tests/contentful/schema.gql
  integration-tests/functions/gatsby-config.js
  integration-tests/functions/package.json
  integration-tests/functions/plugins/gatsby-plugin-cool/package.json
  integration-tests/functions/plugins/gatsby-plugin-cool/src/api/gatsby-plugin-cool/not-shadowed.js
  integration-tests/functions/plugins/gatsby-plugin-cool/src/api/gatsby-plugin-cool/shadowed.js
  integration-tests/functions/plugins/gatsby-plugin-cool/src/api/i-will-not-work-cause-namespacing.js
  integration-tests/functions/src/api/gatsby-plugin-cool/shadowed.js
  integration-tests/functions/test-helpers.js
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/dev-404-page/raw_dev-404-page.js
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/types/built-in-types.ts
Labels: topic: functions

#31350 Fixes a bug related to filters appended onto next links for gatsby-source-drupal.
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: topic: Drupal

#26720 feat(gatsby-source-drupal): Add toggleable multilingual support by prefixing nodes with their langcode
  packages/gatsby-source-drupal/.gitignore
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/normalize.js
  packages/gatsby-source-drupal/src/plugin-options.js
  packages/gatsby-source-drupal/src/utils.js
  yarn.lock
Labels: status: needs core review

#31468 feat(gatsby-source-drupal): Add option validation
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: topic: Drupal

#31470 feat(gatsby): Support uploading files as part of forms
  integration-tests/functions/__tests__/__snapshots__/functions-dev.js.snap
  integration-tests/functions/__tests__/__snapshots__/functions-prod.js.snap
  integration-tests/functions/src/api/parser.js
  integration-tests/functions/test-helpers.js
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: topic: functions

#31473 feat(gatsby): Speedup building Functions by disabling minification
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: topic: functions

#31483 fix(tests): update cheerio snapshots (#31298)
  packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-remark-copy-linked-files/package.json
  packages/gatsby-remark-graphviz/package.json
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-remark-images-contentful/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/package.json
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-prismjs/package.json
  packages/gatsby-remark-responsive-iframe/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby/src/bootstrap/__tests__/__snapshots__/resolve-module-exports.js.snap
  yarn.lock
Labels: type: cherry

#31491 feat(docs): add para to top of themes doc to illustrate purpose
  docs/docs/how-to/plugins-and-themes/using-a-gatsby-theme.md
Labels: status: triage needed

#31425 fix(gatsby-source-drupal): Filenames imported from Drupal via jsonapi are saved URL encoded
  packages/gatsby-source-drupal/src/normalize.js
Labels: topic: Drupal

#31073 update Contentful e2e test snapshots
  e2e-tests/contentful/cypress.json
  e2e-tests/contentful/cypress/integration/gatsby-image.js
  e2e-tests/contentful/cypress/integration/gatsby-plugin-image.js
  e2e-tests/contentful/cypress/integration/rich-text.js
  e2e-tests/contentful/package.json
  e2e-tests/contentful/schema.gql
  e2e-tests/contentful/snapshots.js
Labels: bot: merge on green, topic: Contentful

#31497 fix(gatsby-plugin-image): Extra "margin" on CONSTRAINED
  e2e-tests/visual-regression/cypress/plugins/index.js
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- avif format -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- avif format -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- avif format -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- constrained image -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- constrained image -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/GatsbyImage -- constrained image -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- avif format -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- avif format -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- avif format -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- constrained image -- renders correctly on 1027x768.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- constrained image -- renders correctly on ipad-2.snap.png
  e2e-tests/visual-regression/cypress/snapshots/image.js/StaticImage -- constrained image -- renders correctly on iphone-6.snap.png
  e2e-tests/visual-regression/package.json
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Labels: topic: images/media

#31347 feat(gatsby-plugin-gatsby-cloud): enable preview status indicator and tooltip
  jest.config.js
  packages/gatsby-plugin-gatsby-cloud/.gitignore
  packages/gatsby-plugin-gatsby-cloud/package.json
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/mocks/handlers.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/mocks/server.js
  packages/gatsby-plugin-gatsby-cloud/src/components/GatsbyIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/components/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/IndicatorButtonTooltip.js
  packages/gatsby-plugin-gatsby-cloud/src/components/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/LinkIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Style.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/getBuildInfo.js
  yarn.lock
Labels: bot: merge on green, status: needs core review

#31487 feat(gatsby): Resolve typescript files in functions without needing to add the extension
  integration-tests/functions/src/api/extensions.js
  integration-tests/functions/src/lib/handler.ts
  integration-tests/functions/test-helpers.js
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: topic: functions

#31511 fix(gatsby-transformer-sharp): Dereference symlinks when copying files
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: bot: merge on green, topic: sharp

#31512 chore(docs): Update adding-search
  docs/docs/how-to/adding-common-features/adding-search.md
Labels: type: documentation

#31506 fix(gatsby-plugin-gatsby-cloud): only load indicator code when enabled
  packages/babel-preset-gatsby-package/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/index.js
  packages/gatsby-plugin-gatsby-cloud/.babelrc
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
Labels: type: maintenance

#31508 feat(gatsby): lazily compile functions in development
  integration-tests/functions/package.json
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: topic: functions

#31526 feat(gatsby-source-wordpress): auto-alias any field named `fields` to prevent conflicts with Gatsby core
  packages/gatsby-source-wordpress/src/models/remoteSchema.ts
Labels: status: triage needed

#31492 fix(gatsby-source-contentful): use correct name for crop parameter in query string
  packages/gatsby-source-contentful/src/cache-image.js
Labels: topic: Contentful

#31477 fix(gatsby): better detection of Babel rules for HMR when customizing the Webpack config
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: hot reloading, topic: webpack/babel

#31527 fix content wrapping style issue
  packages/gatsby-plugin-gatsby-cloud/src/components/Style.js
Labels: topic: frontend-general

#31540 feat(docs): add examples to site
  docs/docs/adding-search-with-js-search.md
  docs/docs/building-an-ecommerce-site-with-shopify.md
  docs/docs/conceptual/making-your-site-accessible.md
  docs/docs/creating-a-local-plugin.md
  docs/docs/how-to/adding-common-features/adding-an-rss-feed.md
  docs/docs/how-to/adding-common-features/adding-page-transitions-with-plugin-transition-link.md
  docs/docs/how-to/adding-common-features/creating-a-sitemap.md
  docs/docs/how-to/adding-common-features/localization-i18n.md
  docs/docs/how-to/adding-common-features/processing-payments-with-stripe.md
  docs/docs/how-to/custom-configuration/typescript.md
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
  docs/docs/how-to/images-and-media/working-with-video.md
  docs/docs/how-to/plugins-and-themes/configuring-usage-with-plugin-options.md
  docs/docs/how-to/previews-deploys-hosting/path-prefix.md
  docs/docs/how-to/querying-data/using-gatsby-without-graphql.md
  docs/docs/how-to/routing/adding-markdown-pages.md
  docs/docs/how-to/routing/client-only-routes-and-user-authentication.md
  docs/docs/how-to/routing/creating-routes.md
  docs/docs/how-to/routing/mdx.md
  docs/docs/how-to/sourcing-data/sourcing-from-contentful.md
  docs/docs/how-to/sourcing-data/sourcing-from-drupal.md
  docs/docs/how-to/sourcing-data/sourcing-from-wordpress.md
  docs/docs/how-to/styling/css-modules.md
  docs/docs/how-to/styling/emotion.md
  docs/docs/how-to/styling/sass.md
  docs/docs/how-to/styling/styled-components.md
  docs/docs/how-to/testing/end-to-end-testing.md
  docs/docs/how-to/testing/unit-testing.md
Labels: status: triage needed

#31394 feat(gatsby): enable concurrent features
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/src/utils/flags.ts
Labels: topic: frontend-core

#31547 fix(gatsby): add componentChunkName to components list so don't need to loop over pages
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/plugin-data.js
  packages/gatsby-plugin-netlify/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-netlify/src/build-headers-program.js
  packages/gatsby-plugin-netlify/src/plugin-data.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/reducers/components.ts
  packages/gatsby/src/redux/types.ts
Labels: type: bug

#31524 chore(docs): Release Notes for 3.6
  docs/docs/reference/release-notes/v3.6/index.md
Labels: type: documentation

#31490 chore(docs): Update links to official Shopify starter demo
  docs/docs/building-an-ecommerce-site-with-shopify.md
  docs/docs/conceptual/gatsby-for-ecommerce.md
Labels: type: documentation

#31594 fix(gatsby): prevent infinite loop in fast-refresh-overlay
  packages/gatsby/cache-dir/fast-refresh-overlay/components/hooks.js
Labels: topic: hot reloading

#31518 Update adding-an-rss-feed.md
  docs/docs/how-to/adding-common-features/adding-an-rss-feed.md
Labels: type: documentation

#31595 chore(docs): Add title to release notes
  docs/docs/reference/release-notes/v2.26/index.md
  docs/docs/reference/release-notes/v2.27/index.md
  docs/docs/reference/release-notes/v2.28/index.md
  docs/docs/reference/release-notes/v2.29/index.md
  docs/docs/reference/release-notes/v2.30/index.md
  docs/docs/reference/release-notes/v2.31/index.md
  docs/docs/reference/release-notes/v2.32/index.md
  docs/docs/reference/release-notes/v3.0/index.md
  docs/docs/reference/release-notes/v3.1/index.md
  docs/docs/reference/release-notes/v3.2/index.md
  docs/docs/reference/release-notes/v3.3/index.md
  docs/docs/reference/release-notes/v3.4/index.md
  docs/docs/reference/release-notes/v3.5/index.md
  docs/docs/reference/release-notes/v3.6/index.md
Labels: type: documentation

#31600 chore(gatsby-source-wordpress): Fix typos
  packages/gatsby-source-wordpress/docs/features/compatibility-api.md
Labels: type: documentation

#31604 fix(gatsby-plugin-gatsby-cloud): fix cloud being bundled
  packages/gatsby-plugin-gatsby-cloud/package.json
Labels: topic: frontend-general

#31467 fix(gatsby-source-contentful): fix progress bar
  packages/gatsby-source-contentful/src/fetch.js
Labels: topic: Contentful

#31519 chore: Properly typecheck `gatsby`
  packages/gatsby/src/bootstrap/schema-hot-reloader.ts
  packages/gatsby/src/cache/cache-fs.ts
  packages/gatsby/src/cache/json-file-store.ts
  packages/gatsby/src/cache/wrap-callback.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
  packages/gatsby/src/redux/reducers/functions.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/schema/types/pagination.ts
  packages/gatsby/src/utils/cache.ts
  packages/gatsby/src/utils/develop-proxy.ts
  packages/gatsby/src/utils/eslint-rules/limited-exports-page-templates.ts
  packages/gatsby/src/utils/gatsby-webpack-stats-extractor.ts
  packages/gatsby/src/utils/telemetry-server.ts
  packages/gatsby/src/utils/webpack-plugins.ts
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack/force-css-hmr-for-edge-cases.ts
  packages/gatsby/src/utils/worker/render-html.ts
  packages/gatsby/src/utils/worker/worker.d.ts
  packages/gatsby/tsconfig.json
Labels: topic: TypeScript

#31608 fix(contentful): pass reporter to retry function
  packages/gatsby-source-contentful/src/cache-image.js
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: source-contentful

#31636 Fixed syntax error in example
  examples/creating-source-plugins/source-plugin/gatsby-node.js
Labels: status: triage needed

#31612 feat(gatsby-source-wordpress): Fix false positive error if the URL and the responsePath are the same
  packages/gatsby-source-wordpress/src/utils/fetch-graphql.ts
Labels: topic: source-wordpress

#31640 Fix typos in improving-build-performance.md
  docs/docs/how-to/performance/improving-build-performance.md
Labels: status: triage needed

#31639 Fix typo in adding-search.md
  docs/docs/how-to/adding-common-features/adding-search.md
Labels: status: triage needed

#31649 chore(docs): Update Jest instructions for v27
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#31651 chore(docs): Correct nginx spelling
  docs/docs/how-to/routing/client-only-routes-and-user-authentication.md
Labels: type: documentation

#31533 chore: Add translations and validations to Contentful test
  e2e-tests/contentful/cypress/integration/boolean.js
  e2e-tests/contentful/cypress/integration/content-reference.js
  e2e-tests/contentful/cypress/integration/date.js
  e2e-tests/contentful/cypress/integration/gatsby-image.js
  e2e-tests/contentful/cypress/integration/gatsby-plugin-image.js
  e2e-tests/contentful/cypress/integration/json.js
  e2e-tests/contentful/cypress/integration/location.js
  e2e-tests/contentful/cypress/integration/media-reference.js
  e2e-tests/contentful/cypress/integration/number.js
  e2e-tests/contentful/cypress/integration/rich-text.js
  e2e-tests/contentful/cypress/integration/text.js
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/english-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/fixed-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/fixed-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/fluid-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/fluid-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/german-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/sqip-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/sqip-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/traced-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/traced-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/webp-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/webp-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/blurred-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/blurred-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/constrained-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/constrained-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/dominant-color-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/dominant-color-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/english-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/fixed-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/fixed-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/full-width-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/full-width-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/german-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/sqip-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/sqip-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/traced-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-plugin-image.js/traced-1.snap.png
  e2e-tests/contentful/cypress/support/index.js
  e2e-tests/contentful/schema.gql
  e2e-tests/contentful/snapshots.js
  e2e-tests/contentful/src/components/grid.js
  e2e-tests/contentful/src/components/header.js
  e2e-tests/contentful/src/components/layout.js
  e2e-tests/contentful/src/components/references/number.js
  e2e-tests/contentful/src/components/references/text.js
  e2e-tests/contentful/src/pages/boolean.js
  e2e-tests/contentful/src/pages/content-reference.js
  e2e-tests/contentful/src/pages/date.js
  e2e-tests/contentful/src/pages/gatsby-image.js
  e2e-tests/contentful/src/pages/gatsby-plugin-image.js
  e2e-tests/contentful/src/pages/json.js
  e2e-tests/contentful/src/pages/location.js
  e2e-tests/contentful/src/pages/media-reference.js
  e2e-tests/contentful/src/pages/number.js
  e2e-tests/contentful/src/pages/rich-text.js
  e2e-tests/contentful/src/pages/text.js
Labels: status: needs core review, topic: source-contentful

#31620 fix(gatsby): Correct config for svgo plugins whitelist
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: webpack/babel
