Repository gatsbyjs/gatsby, pull requests merged in 2021-06, with the labels that each got.

#31710 fix(gatsby): merge resolveType when merging abstract types
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/schema.js
Labels: topic: GraphQL

#31537 feat(gatsby-source-wordpress: architecture.md
  packages/gatsby-source-wordpress/ARCHITECTURE.md
  packages/gatsby-source-wordpress/docs/contributing.md
Labels: topic: source-wordpress

#31713 fix(gatsby-source-wordpress): Prevent "EADDRINUSE: address already in use 127.0.0.1" error
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/content-update-interval.js
Labels: topic: source-wordpress

#31558 feat(gatsby-remark-images): Add decoding prop to img elements
  packages/gatsby-remark-images/README.md
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/__tests__/gatsby-node.js
  packages/gatsby-remark-images/src/constants.js
  packages/gatsby-remark-images/src/gatsby-node.js
  packages/gatsby-remark-images/src/index.js
Labels: status: needs core review, topic: media, topic: remark/mdx

#31371 feat(gatsby): node persistence
  .circleci/config.yml
  packages/gatsby/package.json
  packages/gatsby/src/datastore/datastore.ts
  packages/gatsby/src/datastore/in-memory/in-memory-datastore.ts
  packages/gatsby/src/datastore/index.ts
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
  packages/gatsby/src/datastore/lmdb/updates/nodes-by-type.ts
  packages/gatsby/src/datastore/lmdb/updates/nodes.ts
  packages/gatsby/src/datastore/types.ts
  packages/gatsby/src/db/__tests__/nodes.js
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/query/__tests__/graphql-runner.ts
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/__tests__/run-fast-filters.js
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/redux/persist.ts
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/__tests__/run-query.js
  packages/gatsby/src/schema/index.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/services/create-pages.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/source-nodes.ts
  yarn.lock
Labels: topic: data

#31731 fix(tutorial): add trailing slashes to 'next part' links
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
Labels: type: documentation

#31732 fix(gatsby): fix PNP resolving from the .cache folder
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/cache-folder-resolver.ts
Labels: type: maintenance

#31664 refactor(gatsby): consolidate data layer
  integration-tests/cache-resilience/gatsby-node.js
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/repl.ts
  packages/gatsby/src/datastore/__tests__/nodes.js
  packages/gatsby/src/datastore/__tests__/run-fast-filters.js
  packages/gatsby/src/datastore/common/__tests__/query.js
  packages/gatsby/src/datastore/common/query.ts
  packages/gatsby/src/datastore/in-memory/indexing.ts
  packages/gatsby/src/datastore/in-memory/run-fast-filters.ts
  packages/gatsby/src/datastore/index.ts
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/redux/__tests__/nodes.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/save-state.js
  packages/gatsby/src/schema/__tests__/run-query.js
  packages/gatsby/src/schema/index.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/infer/index.js
  packages/gatsby/src/schema/infer/is-file.ts
  packages/gatsby/src/schema/node-model.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/state-machines/develop/actions.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/sanitize-node.js.snap
  packages/gatsby/src/utils/__tests__/sanitize-node.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/nodes.ts
  packages/gatsby/src/utils/sanitize-node.js
  packages/gatsby/src/utils/source-nodes.ts
Labels: topic: data

#31642 feat(gatsby-plugin-gatsby-cloud): Track user engagement in preview UI
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/components/GatsbyIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/components/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/LinkIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/trackEvent.js
Labels: bot: merge on green, topic: plugins, type: feature or enhancement

#31127 feat(gatsby): add createNodeManifest action
  .circleci/config.yml
  integration-tests/node-manifest/__tests__/create-node-manifest.test.js
  integration-tests/node-manifest/gatsby-node.js
  integration-tests/node-manifest/package.json
  integration-tests/node-manifest/src/pages/{TestFsRouteType.id}.js
  integration-tests/node-manifest/src/templates/one.js
  integration-tests/node-manifest/src/templates/three.js
  integration-tests/node-manifest/src/templates/two.js
  integration-tests/node-manifest/utils/get-gatsby-process.js
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-source-wordpress/src/steps/preview/index.ts
  packages/gatsby-source-wordpress/src/utils/gatsby-types.ts
  packages/gatsby/src/query/query-watcher.ts
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/node-manifest.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/create-pages.ts
  packages/gatsby/src/services/run-page-queries.ts
  packages/gatsby/src/utils/__tests__/node-manifest.ts
  packages/gatsby/src/utils/node-manifest.ts
Labels: topic: core, type: feature or enhancement

#31596 fix(gatsby-remark-katex): fix compatibility with remark 13
  packages/gatsby-remark-katex/package.json
  packages/gatsby-remark-katex/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-katex/src/index.js
  yarn.lock
Labels: bot: merge on green, status: needs core review, topic: remark/mdx

#31751 docs(gatsby-plugin-image): Fix minor typo
  docs/docs/conceptual/using-gatsby-image.md
Labels: bot: merge on green, type: documentation

#31752 docs(tutorial): fix import typo
  docs/docs/tutorial/part-2/index.mdx
Labels: type: documentation

#31761 docs(tutorial): replace plugin process image with higher fidelity graphic
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-3/plugin-process.png
Labels: type: documentation

#31770 chore(gatsby): Add umbrellaIssue to lmdb
  packages/gatsby/src/utils/flags.ts
Labels: topic: core

#31750 fix(gatsby): fix signature for latest experimental version of react-dom
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/src/utils/flags.ts
Labels: topic: core

#31768 chore(gatsby): type exposed workerpool functions
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/services/types.ts
  packages/gatsby/src/state-machines/data-layer/types.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/worker/pool.ts
  packages/gatsby/src/utils/worker/render-html.ts
  packages/gatsby/src/utils/worker/types.ts
  packages/gatsby/src/utils/worker/worker.d.ts
Labels: topic: TypeScript

#31774 refactor(gatsby-plugin-gatsby-cloud): Render indicator in shadow root
  packages/gatsby-plugin-gatsby-cloud/.babelrc
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Style.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-browser.js
Labels: topic: frontend

#31749 tests: move pnp to tmp
  .circleci/config.yml
Labels: topic: automation

#31790 chore(docs): Update gatsby-plugin-image typos
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: type: documentation

#31796 chore(docs): Update digitalocean certbot instructions
  docs/docs/deploying-to-digitalocean-droplet.md
Labels: type: documentation

#31793 chore(docs): Add `testEnvironment` to RTL doc
  docs/docs/how-to/testing/testing-react-components.md
Labels: type: documentation

#31798 chore(docs): Add link to latest migration doc
  docs/docs/reference/release-notes/upgrade-gatsby-and-dependencies.md
Labels: type: documentation

#31368 fix(gatsby): do not use domready package
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green, status: needs core review, topic: core

#31803 chore(gatsby): Bump `PRESERVE_WEBPACK_CACHE` flag to 20%
  packages/gatsby/src/utils/flags.ts
Labels: topic: core

#31780 fix(gatsby-remark-copy-linked-files): replace checking parent node type to 'dir'
  packages/gatsby-remark-copy-linked-files/src/__tests__/index.js
  packages/gatsby-remark-copy-linked-files/src/index.js
Labels: bot: merge on green, topic: remark/mdx

#31813 fix(gatsby): do not add global id to style tag
  integration-tests/ssr/test-output.js
  packages/gatsby/cache-dir/static-entry.js
Labels: bot: merge on green, topic: core

#31807 feat(gatsby): Turn on Functions experiment for everybody
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/load.ts
  packages/gatsby/src/internal-plugins/functions/package.json
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/utils/flags.ts
Labels: bot: merge on green

#31778 docs(tutorial): delete old parts of the tutorial (parts 0-3)
  docs/docs/tutorial/part-one/01-hello-world-vscode.png
  docs/docs/tutorial/part-one/02-demo-hot-reloading.mp4
  docs/docs/tutorial/part-one/03-more-hot-reloading.png
  docs/docs/tutorial/part-one/04-add-image.png
  docs/docs/tutorial/part-one/05-about-page.png
  docs/docs/tutorial/part-one/06-header-component.png
  docs/docs/tutorial/part-one/07-pass-data-header.png
  docs/docs/tutorial/part-one/08-duplicate-header.png
  docs/docs/tutorial/part-one/09-dev-404.png
  docs/docs/tutorial/part-one/10-linking-between-pages.mp4
  docs/docs/tutorial/part-one/index.md
  docs/docs/tutorial/part-one/surge-deployment.png
  docs/docs/tutorial/part-three/about-uncentered.png
  docs/docs/tutorial/part-three/index.md
  docs/docs/tutorial/part-three/no-layout.png
  docs/docs/tutorial/part-three/typography-centered.png
  docs/docs/tutorial/part-three/typography-not-centered.png
  docs/docs/tutorial/part-three/typography-styles.png
  docs/docs/tutorial/part-three/with-layout2.png
  docs/docs/tutorial/part-three/with-navigation.png
  docs/docs/tutorial/part-three/with-navigation2.png
  docs/docs/tutorial/part-three/with-title.png
  docs/docs/tutorial/part-two/css-modules-basic.png
  docs/docs/tutorial/part-two/css-modules-console.png
  docs/docs/tutorial/part-two/css-modules-userlist.png
  docs/docs/tutorial/part-two/global-css.png
  docs/docs/tutorial/part-two/index.md
  docs/docs/tutorial/part-two/pexels-daniel-xavier-1102341.jpg
  docs/docs/tutorial/part-two/pexels-guilherme-almeida-1858175.jpg
  docs/docs/tutorial/part-zero/01-node-npm-versions.png
  docs/docs/tutorial/part-zero/02-gatsby-version.png
  docs/docs/tutorial/part-zero/03-create-site.mp4
  docs/docs/tutorial/part-zero/04-home-page.png
  docs/docs/tutorial/part-zero/05-gatsby-help.png
  docs/docs/tutorial/part-zero/index.md
  docs/tutorial/index.md
Labels: type: documentation

#31815 docs(functions): move functions docs from how-to section to reference section
  docs/docs/reference/functions/getting-started.md
  docs/docs/reference/functions/middleware-and-helpers.md
  docs/docs/reference/functions/routing.md
Labels: type: documentation

#31816 docs(functions): update links in functions docs
  docs/docs/reference/functions/getting-started.md
Labels: type: documentation

#31818 feat(gatsby): remove concurrent-features flag and depend on export
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/src/utils/flags.ts
Labels: bot: merge on green, topic: core

#31809 chore(docs): Clean up documentation for Functions
  docs/docs/reference/functions/getting-started.md
  docs/docs/reference/functions/routing.md
Labels: type: documentation

#31771 test(gatsby): check if worker can access node created in different process
  jest.config.js
  packages/gatsby/package.json
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
  packages/gatsby/src/utils/worker/__tests__/datastore.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/create-test-worker.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/index.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/jest-helpers.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/wrapper-for-tests.js
Labels: topic: data

#31808 docs: release notes for 3.7
  docs/docs/reference/release-notes/v3.7/index.md
Labels: type: documentation

#31832 docs: fix broken link in the 3.7 release notes
  docs/docs/reference/release-notes/v3.7/index.md
Labels: bot: merge on green

#31836 chore: remove subscription recommendation
  docs/docs/creating-a-source-plugin.md
Labels: status: triage needed

#31833 fix(gatsby-telemetry): Export captureEvent via module.exports as well
  packages/gatsby-telemetry/src/index.ts
Labels: topic: plugins

#31811 chore: generate renovate config
  .circleci/config.yml
  renovate.json5
  scripts/renovate-config-generator.js
Labels: type: maintenance

#31831 feat(gatsby-plugin-gatsby-cloud): Add telemetry event for `GATSBY_CLOUD_METADATA`
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
Labels: topic: plugins

#31718 feat(gatsby): switch from arrays to node iterators
  packages/gatsby/src/datastore/common/iterable.ts
  packages/gatsby/src/datastore/in-memory/in-memory-datastore.ts
  packages/gatsby/src/datastore/in-memory/indexing.ts
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
  packages/gatsby/src/datastore/types.ts
  packages/gatsby/src/schema/index.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/infer/index.js
  packages/gatsby/src/schema/infer/inference-metadata.ts
  packages/gatsby/src/schema/node-model.js
  packages/gatsby/src/schema/schema.js
Labels: topic: data

#31864 Fixes bug where datum have no attributes and attributes have no langcode.
  packages/gatsby-source-drupal/src/normalize.js
Labels: status: triage needed

#31870 docs(tutorial): add missing export to part 3 code example
  docs/docs/tutorial/part-3/index.mdx
Labels: status: triage needed

#31822 feat(gatsby): Main process can save slices of state & worker can access it
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/persist.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/worker/__tests__/share-state.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/create-test-worker.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/wrapper-for-tests.js
  packages/gatsby/src/utils/worker/child/render-html.ts
  packages/gatsby/src/utils/worker/child/state.ts
Labels: topic: core

#31286 CTF-v6: Rename schema types
  e2e-tests/contentful/schema.gql
  e2e-tests/contentful/snapshots.js
  e2e-tests/contentful/src/components/references/content-reference.js
  e2e-tests/contentful/src/components/references/index.js
  e2e-tests/contentful/src/components/references/location.js
  e2e-tests/contentful/src/components/references/number.js
  e2e-tests/contentful/src/components/references/text.js
  e2e-tests/contentful/src/pages/boolean.js
  e2e-tests/contentful/src/pages/content-reference.js
  e2e-tests/contentful/src/pages/date.js
  e2e-tests/contentful/src/pages/json.js
  e2e-tests/contentful/src/pages/location.js
  e2e-tests/contentful/src/pages/media-reference.js
  e2e-tests/contentful/src/pages/number.js
  e2e-tests/contentful/src/pages/rich-text.js
  e2e-tests/contentful/src/pages/text.js
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-contentful/src/generate-schema.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/report.js
Labels: breaking change, topic: source-contentful

#31869 gatsby(docs): Document Activity Timer
  packages/gatsby/src/utils/api-node-helpers-docs.js
Labels: status: triage needed

#31847 fix(gatsby-source-wordpress) Use send property for timeout (#31737)
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js
Labels: bot: merge on green, topic: source-wordpress

#31489 fix(gatsby): infer shape of warning object
  packages/gatsby/src/utils/webpack-error-utils.ts
Labels: topic: webpack/babel

#31896 fix(gatsby): Update eslint a11y config
  packages/gatsby/src/utils/eslint-config.ts
Labels: topic: core

#31852 feat(gatsby): PQR workers can access page & static queries
  .circleci/config.yml
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/utils/worker/__tests__/share-state.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/child/schema.ts
Labels: topic: core

#31858 feat(gatsby): PQR workers can access inference metadata
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/utils/worker/__tests__/share-state.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/child/schema.ts
Labels: topic: core

#31879 fix(gatsby-source-contentful): improve error message when dominant color can't be generated
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: source-contentful

#31665 feat(gatsby-plugin-google-analytics): enable core webvitals tracking
  packages/gatsby-plugin-google-analytics/.babelrc
  packages/gatsby-plugin-google-analytics/README.md
  packages/gatsby-plugin-google-analytics/package.json
  packages/gatsby-plugin-google-analytics/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-google-analytics/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-google-analytics/src/gatsby-browser.js
  packages/gatsby-plugin-google-analytics/src/gatsby-node.js
  packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js
  packages/gatsby-plugin-google-tagmanager/.babelrc
  packages/gatsby-plugin-google-tagmanager/README.md
  packages/gatsby-plugin-google-tagmanager/package.json
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-google-tagmanager/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-browser.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-node.js
  packages/gatsby-plugin-google-tagmanager/src/gatsby-ssr.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  yarn.lock
Labels: topic: frontend, topic: plugins-analytics

#31937 chore(docs): Fix grammar issue
  benchmarks/gabe-fs-markdown/README.md
Labels: status: triage needed

#31862 BREAKING(gatsby-source-shopify): Replace with new plugin
  .eslintignore
  packages/gatsby-source-shopify/.babelrc
  packages/gatsby-source-shopify/.gitignore
  packages/gatsby-source-shopify/.npmignore
  packages/gatsby-source-shopify/.prettierignore
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/__tests__/fixtures.ts
  packages/gatsby-source-shopify/__tests__/get-shopify-image.ts
  packages/gatsby-source-shopify/__tests__/make-source-from-operation.ts
  packages/gatsby-source-shopify/__tests__/node-builder.ts
  packages/gatsby-source-shopify/__tests__/tsconfig.json
  packages/gatsby-source-shopify/package.json
  packages/gatsby-source-shopify/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-source-shopify/src/__tests__/create-client.js
  packages/gatsby-source-shopify/src/__tests__/fixtures/articles.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/blogs.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/collections.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/pages.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/products.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/shop-details.json
  packages/gatsby-source-shopify/src/__tests__/fixtures/shop-policies.json
  packages/gatsby-source-shopify/src/__tests__/index.js
  packages/gatsby-source-shopify/src/client.ts
  packages/gatsby-source-shopify/src/constants.js
  packages/gatsby-source-shopify/src/create-client.js
  packages/gatsby-source-shopify/src/create-schema-customization.ts
  packages/gatsby-source-shopify/src/errors.ts
  packages/gatsby-source-shopify/src/events.ts
  packages/gatsby-source-shopify/src/gatsby-node.js
  packages/gatsby-source-shopify/src/gatsby-node.ts
  packages/gatsby-source-shopify/src/get-shopify-image.ts
  packages/gatsby-source-shopify/src/index.js
  packages/gatsby-source-shopify/src/index.ts
  packages/gatsby-source-shopify/src/lib.js
  packages/gatsby-source-shopify/src/make-source-from-operation.ts
  packages/gatsby-source-shopify/src/node-builder.ts
  packages/gatsby-source-shopify/src/nodes.js
  packages/gatsby-source-shopify/src/operations.ts
  packages/gatsby-source-shopify/src/processors/collections.ts
  packages/gatsby-source-shopify/src/processors/incremental-products.ts
  packages/gatsby-source-shopify/src/processors/index.ts
  packages/gatsby-source-shopify/src/queries.js
  packages/gatsby-source-shopify/src/query-builders/bulk-query.ts
  packages/gatsby-source-shopify/src/query-builders/collections-query.ts
  packages/gatsby-source-shopify/src/query-builders/orders-query.ts
  packages/gatsby-source-shopify/src/query-builders/products-query.ts
  packages/gatsby-source-shopify/src/resolve-gatsby-image-data.ts
  packages/gatsby-source-shopify/src/rest.ts
  packages/gatsby-source-shopify/src/static-queries.ts
  packages/gatsby-source-shopify/tsconfig.json
  packages/gatsby-source-shopify/types/interface.d.ts
  renovate.json5
  yarn.lock
Labels: breaking change, topic: source-shopify

#31946 chore(docs): Fix multiple grammar issues
  packages/gatsby-cli/README.md
  packages/gatsby-codemods/README.md
  packages/gatsby-design-tokens/README.md
  packages/gatsby-dev-cli/README.md
  packages/gatsby-plugin-gatsby-cloud/README.md
Labels: type: documentation

#31961 docs: Fix missing commas in plugin-image defaults
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: type: documentation

#31958 fix: do not hang on schema in worker unit tests
  packages/gatsby/src/utils/worker/__tests__/schema.ts
Labels: status: blocked

#31968 chore(gatsby-source-shopify): remove prepublish script from package json
  packages/gatsby-source-shopify/package.json
Labels: bot: merge on green

#31963 fix(gatsby-plugin-sitemap): Properly throw error on missing siteUrl
  packages/gatsby-plugin-sitemap/README.md
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
  packages/gatsby-plugin-sitemap/src/internals.js
  starters/default/gatsby-config.js
  starters/gatsby-starter-minimal/gatsby-config.js
Labels: topic: plugins

#31514 feat(gatsby-source-drupal): Use Got instead of Axios for retries & caching support + restrict to 20 concurrent requests
  benchmarks/source-drupal/package.json
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  renovate.json5
  yarn.lock
Labels: bot: merge on green, topic: source-drupal

#31919 feat(gatsby): PQR worker can create schema
  packages/gatsby/src/bootstrap/load-config-and-plugins.ts
  packages/gatsby/src/utils/source-nodes.ts
  packages/gatsby/src/utils/worker/__tests__/fixtures/sample-site/plugins/gatsby-plugin-test/gatsby-node.js
  packages/gatsby/src/utils/worker/__tests__/schema.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/jest-helpers.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/child/schema.ts
  packages/gatsby/src/utils/worker/child/state.ts
Labels: topic: core

#31997 chore: Delete profile.js
  packages/gatsby/src/utils/profile.js
Labels: type: maintenance

#32003 fix shopify source store url check
  packages/gatsby-source-shopify/src/gatsby-node.ts
Labels: topic: source-shopify

#31988 fix(docs): rewrite environment variables docs to simplify explanations and focus on the essentials
  docs/docs/how-to/local-development/environment-variables.md
Labels: type: documentation

#32000 feat(gatsby): PQR worker can run static queries
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/__tests__/schema.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts
  packages/gatsby/src/utils/worker/child/queries.ts
  packages/gatsby/src/utils/worker/child/schema.ts
Labels: topic: core

#24288 fix(gatsby-source-contentful): Don't ignore errors thrown when fetching assets
  packages/gatsby-source-contentful/src/download-contentful-assets.js
Labels: bot: merge on green, not stale, topic: source-contentful

#31986 fix(contentful): reenable support for gif images
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: source-contentful

#30662 feat(gatsby-design-tokens): palette update
  packages/gatsby-design-tokens/src/colors.js
Labels: bot: merge on green

#32018 feat(gatsby): enable webpack caching for all
  packages/gatsby/src/utils/flags.ts
Labels: topic: core

#32024 feat(gatsby-source-shopify): removed apikey references/usage from shopify plugin
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/__tests__/make-source-from-operation.ts
  packages/gatsby-source-shopify/__tests__/node-builder.ts
  packages/gatsby-source-shopify/src/gatsby-node.ts
  packages/gatsby-source-shopify/types/interface.d.ts
Labels: topic: source-shopify

#32021 feat(gatsby-plugin-mdx): swap sourceNodes to createSchemaCustomization
  packages/gatsby-plugin-mdx/gatsby-node.js
  packages/gatsby-plugin-mdx/gatsby/create-schema-customization.js
Labels: bot: merge on green, topic: remark/mdx

#32012 feat(gatsby-source-drupal): Disable caching + add http/2 agent
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/gatsby-node.js
  yarn.lock
Labels: bot: merge on green, topic: source-drupal

#32026 chore(docs): Remove extraneous h1 headings from release notes
  docs/docs/reference/release-notes/v2.26/index.md
  docs/docs/reference/release-notes/v2.27/index.md
  docs/docs/reference/release-notes/v2.28/index.md
  docs/docs/reference/release-notes/v2.29/index.md
  docs/docs/reference/release-notes/v2.30/index.md
  docs/docs/reference/release-notes/v2.31/index.md
  docs/docs/reference/release-notes/v2.32/index.md
  docs/docs/reference/release-notes/v3.0/index.md
  docs/docs/reference/release-notes/v3.1/index.md
  docs/docs/reference/release-notes/v3.2/index.md
  docs/docs/reference/release-notes/v3.3/index.md
  docs/docs/reference/release-notes/v3.4/index.md
  docs/docs/reference/release-notes/v3.5/index.md
  docs/docs/reference/release-notes/v3.6/index.md
  docs/docs/reference/release-notes/v3.7/index.md
Labels: type: documentation

#32038 feat(gatsby-source-drupal): Disable caching + add http/2 agent (#32012)
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/gatsby-node.js
  yarn.lock
Labels: type: cherry

#32001 docs: 3.8 release notes
  docs/docs/reference/release-notes/v3.8/index.md
Labels: bot: merge on green

#32041 docs: remove TODO from release notes
  docs/docs/reference/release-notes/v3.8/index.md
Labels: bot: merge on green

#32044 fix(gatsby-source-shopify): set default salesChannel to empty string
  packages/gatsby-source-shopify/src/gatsby-node.ts
Labels: topic: source-shopify

#32047 fix(gatsby-plugin-gatsby-cloud): add gatsby-telemetry as a dependency
  packages/gatsby-plugin-gatsby-cloud/package.json
Labels: bot: merge on green

#32050 chore(docs): Fix typo in tutorial
  docs/docs/tutorial/part-1/index.mdx
Labels: type: documentation

#32045 fix(gatsby-source-drupal): Comment out http2-wrapper
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: bot: merge on green, topic: source-drupal

#31954 chore(examples): Add loadable components
  examples/using-loadable-components/README.md
  examples/using-loadable-components/gatsby-config.js
  examples/using-loadable-components/package.json
  examples/using-loadable-components/src/components/header.js
  examples/using-loadable-components/src/components/layout.css
  examples/using-loadable-components/src/components/layout.js
  examples/using-loadable-components/src/components/seo.js
  examples/using-loadable-components/src/images/gatsby-astronaut.png
  examples/using-loadable-components/src/images/gatsby-icon.png
  examples/using-loadable-components/src/pages/404.js
  examples/using-loadable-components/src/pages/index.js
Labels: topic: DX

#31953 chore(examples): Fix functions examples + add google oauth
  examples/functions-airtable-form/.env.example
  examples/functions-airtable-form/README.md
  examples/functions-airtable-form/gatsby-config.js
  examples/functions-airtable-form/package.json
  examples/functions-auth0/.env.example
  examples/functions-auth0/LICENSE
  examples/functions-auth0/README.md
  examples/functions-auth0/gatsby-browser.js
  examples/functions-auth0/gatsby-config.js
  examples/functions-auth0/package.json
  examples/functions-basic-form/.gitignore
  examples/functions-basic-form/README.md
  examples/functions-basic-form/gatsby-config.js
  examples/functions-basic-form/package.json
  examples/functions-google-auth/.env.development
  examples/functions-google-auth/LICENSE
  examples/functions-google-gmail/.env.example
  examples/functions-google-gmail/README.md
  examples/functions-google-gmail/gatsby-config.js
  examples/functions-google-gmail/package.json
  examples/functions-google-gmail/src/api/labels.js
  examples/functions-google-gmail/src/images/icon.png
  examples/functions-google-gmail/src/pages/404.js
  examples/functions-google-gmail/src/pages/index.css
  examples/functions-google-gmail/src/pages/index.js
  examples/functions-google-oauth/.env.example
  examples/functions-google-oauth/README.md
  examples/functions-google-oauth/gatsby-config.js
  examples/functions-google-oauth/localhost_8000.png
  examples/functions-google-oauth/package.json
  examples/functions-google-oauth/src/api/googleAccessToken.js
  examples/functions-google-oauth/src/api/login.js
  examples/functions-google-oauth/src/api/logout.js
  examples/functions-google-oauth/src/components/privateRoute.js
  examples/functions-google-oauth/src/pages/app.js
  examples/functions-google-oauth/src/pages/app.module.scss
  examples/functions-google-oauth/src/pages/auth-redirect.js
  examples/functions-google-oauth/src/pages/auth-redirect.module.scss
  examples/functions-google-oauth/src/pages/index.js
  examples/functions-google-oauth/src/pages/index.module.scss
  examples/functions-google-oauth/src/pages/logged-out.js
  examples/functions-google-sheets/.env.example
  examples/functions-google-sheets/.gitignore
  examples/functions-google-sheets/LICENSE
  examples/functions-google-sheets/README.md
  examples/functions-google-sheets/gatsby-config.js
  examples/functions-google-sheets/package.json
  examples/functions-hello-world/README.md
  examples/functions-hello-world/gatsby-config.js
  examples/functions-hello-world/package.json
  examples/functions-sendgrid-email/.env.example
  examples/functions-sendgrid-email/README.md
  examples/functions-sendgrid-email/gatsby-config.js
  examples/functions-sendgrid-email/package.json
  examples/functions-twilio-text/.env.example
  examples/functions-twilio-text/LICENSE
  examples/functions-twilio-text/README.md
  examples/functions-twilio-text/gatsby-config.js
  examples/functions-twilio-text/package.json
Labels: topic: DX

#31928 chore(examples): Add two redux examples
  examples/using-redux-w-interaction-code-splitting/README.md
  examples/using-redux-w-interaction-code-splitting/gatsby-browser.js
  examples/using-redux-w-interaction-code-splitting/gatsby-config.js
  examples/using-redux-w-interaction-code-splitting/gatsby-node.js
  examples/using-redux-w-interaction-code-splitting/gatsby-ssr.js
  examples/using-redux-w-interaction-code-splitting/package.json
  examples/using-redux-w-interaction-code-splitting/src/components/header.js
  examples/using-redux-w-interaction-code-splitting/src/components/layout.css
  examples/using-redux-w-interaction-code-splitting/src/components/layout.js
  examples/using-redux-w-interaction-code-splitting/src/components/redux-button.js
  examples/using-redux-w-interaction-code-splitting/src/components/seo.js
  examples/using-redux-w-interaction-code-splitting/src/images/gatsby-icon.png
  examples/using-redux-w-interaction-code-splitting/src/pages/404.js
  examples/using-redux-w-interaction-code-splitting/src/pages/index.js
  examples/using-redux-w-interaction-code-splitting/src/redux/data/dummy.json
  examples/using-redux-w-interaction-code-splitting/src/redux/reducerRegistry.js
  examples/using-redux-w-interaction-code-splitting/src/redux/reducers/darkMode.js
  examples/using-redux-w-interaction-code-splitting/src/redux/reducers/dummy.js
  examples/using-redux-w-interaction-code-splitting/src/redux/reduxWrapper.js
  examples/using-redux-w-interaction-code-splitting/src/redux/store.js
  examples/using-redux-w-interaction-code-splitting/src/redux/utils.js
  examples/using-redux-w-interaction-code-splitting/static/background.svg
  examples/using-redux-w-interaction-code-splitting/static/screenshot.png
  examples/using-redux-w-page-code-splitting/README.md
  examples/using-redux-w-page-code-splitting/gatsby-config.js
  examples/using-redux-w-page-code-splitting/package.json
  examples/using-redux-w-page-code-splitting/plugins/gatsby-plugin-my-expensive-page/gatsby-node.js
  examples/using-redux-w-page-code-splitting/plugins/gatsby-plugin-my-expensive-page/index.js
  examples/using-redux-w-page-code-splitting/plugins/gatsby-plugin-my-expensive-page/package.json
  examples/using-redux-w-page-code-splitting/src/components/header.js
  examples/using-redux-w-page-code-splitting/src/components/layout.css
  examples/using-redux-w-page-code-splitting/src/components/layout.js
  examples/using-redux-w-page-code-splitting/src/components/redux-button.js
  examples/using-redux-w-page-code-splitting/src/components/seo.js
  examples/using-redux-w-page-code-splitting/src/data/pages.json
  examples/using-redux-w-page-code-splitting/src/images/gatsby-icon.png
  examples/using-redux-w-page-code-splitting/src/pages/404.js
  examples/using-redux-w-page-code-splitting/src/pages/index.js
  examples/using-redux-w-page-code-splitting/src/redux/data/dummy.json
  examples/using-redux-w-page-code-splitting/src/redux/reducers.js
  examples/using-redux-w-page-code-splitting/src/redux/reducers/darkMode.js
  examples/using-redux-w-page-code-splitting/src/redux/reducers/dummy.js
  examples/using-redux-w-page-code-splitting/src/redux/reduxWrapper.js
  examples/using-redux-w-page-code-splitting/src/redux/store.js
  examples/using-redux-w-page-code-splitting/src/templates/other-page.js
  examples/using-redux-w-page-code-splitting/src/templates/post.js
  examples/using-redux-w-page-code-splitting/static/background.svg
  examples/using-redux-w-page-code-splitting/static/screenshot.png
Labels: topic: DX

#32027 Break variants into separate operation
  packages/gatsby-source-shopify/.babelrc
  packages/gatsby-source-shopify/__tests__/fixtures.ts
  packages/gatsby-source-shopify/__tests__/make-source-from-operation.ts
  packages/gatsby-source-shopify/src/gatsby-node.ts
  packages/gatsby-source-shopify/src/node-builder.ts
  packages/gatsby-source-shopify/src/operations.ts
  packages/gatsby-source-shopify/src/processors/incremental-products.ts
  packages/gatsby-source-shopify/src/processors/index.ts
  packages/gatsby-source-shopify/src/processors/product-variants.ts
  packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
  packages/gatsby-source-shopify/src/query-builders/products-query.ts
Labels: status: triage needed

#32017 feat(gatsby): PQR worker can run page queries
  jest.config.js
  package.json
  packages/gatsby/src/query/index.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/query/types.ts
  packages/gatsby/src/redux/persist.ts
  packages/gatsby/src/services/calculate-dirty-queries.ts
  packages/gatsby/src/services/run-page-queries.ts
  packages/gatsby/src/services/types.ts
  packages/gatsby/src/state-machines/data-layer/types.ts
  packages/gatsby/src/state-machines/query-running/types.ts
  packages/gatsby/src/utils/worker/__tests__/fixtures/sample-site/plugins/gatsby-plugin-test/gatsby-node.js
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/__tests__/schema.ts
  packages/gatsby/src/utils/worker/child/queries.ts
  packages/gatsby/src/utils/worker/pool.ts
  yarn.lock
Labels: topic: core

#32113 chore(gatsby-plugin-sitemap): Clarify language on entryLimit
  packages/gatsby-plugin-sitemap/README.md
Labels: topic: plugins

#31926 chore(gatsby-plugin-image): Add duotone, grayscale, rotate and trim options in transformOptions TS type
  packages/gatsby-plugin-image/src/image-utils.ts
Labels: bot: merge on green, topic: media

#31891 docs: Fix typos in tutorial 4
  docs/docs/tutorial/part-4/index.mdx
Labels: type: documentation

#32124 chore(gatsby-source-shopify): add keywords
  packages/gatsby-source-shopify/package.json
Labels: status: triage needed

#32139 fix(gatsby): correct args type in createParentChildLink
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#32128 chore(gatsby-plugin-mdx): Add comment why rehype-slug is required
  packages/gatsby-plugin-mdx/README.md
Labels: topic: remark/mdx

#32125 fix(gatsby-source-drupal): getNext no longer returns a value
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: bot: merge on green, topic: source-drupal, type: bug

#32015 chore(telemetry): Flush more often with gatsby develop
  packages/gatsby-telemetry/src/index.ts
  packages/gatsby/src/commands/develop.ts
Labels: topic: plugins

#32123 fix(gatsby): leave `xmlns` element when optimizing SVGs
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: webpack/babel

#31987 feat(gatsby): Add activity for writing out page-data.json files to the public directory
  packages/gatsby/src/utils/__tests__/get-page-data.ts
  packages/gatsby/src/utils/page-data.ts
Labels: topic: core

#32151 chore(docs) remove UTM parameter from Tutorial links
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-4/index.mdx
Labels: status: triage needed

#32054 refactor(jobs): make it possible to start running job from internalJob
  packages/gatsby/src/bootstrap/__tests__/__snapshots__/remove-stale-jobs.ts.snap
  packages/gatsby/src/bootstrap/__tests__/remove-stale-jobs.ts
  packages/gatsby/src/bootstrap/remove-stale-jobs.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/jobsv2.js.snap
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/reducers/jobsv2.ts
  packages/gatsby/src/redux/types.ts
Labels: topic: core

#32106 fix(plugin-netlify-cms): exclude cms.css from index.html
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  yarn.lock
Labels: topic: plugins

#31993 feat(gatsby): Prevent generation of polyfill bundle if not needed
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/develop-static-entry.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/src/utils/__tests__/browserslist.js
  packages/gatsby/src/utils/__tests__/webpack.config.js
  packages/gatsby/src/utils/browserslist.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: bot: merge on green, topic: core, topic: webpack/babel

#32155 fix(gatsby-source-contentful): force base64 previews to be formatted as JPEG
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: bot: merge on green, status: needs core review, topic: source-contentful

#32120 feat: worker pool that can execute tasks on all workers
  integration-tests/gatsby-cli/package.json
  packages/gatsby-worker/.babelrc
  packages/gatsby-worker/.gitignore
  packages/gatsby-worker/.npmignore
  packages/gatsby-worker/README.md
  packages/gatsby-worker/package.json
  packages/gatsby-worker/src/__tests__/fixtures/test-child.ts
  packages/gatsby-worker/src/__tests__/fixtures/ts-register.js
  packages/gatsby-worker/src/__tests__/integration.ts
  packages/gatsby-worker/src/__tests__/task-queue.ts
  packages/gatsby-worker/src/child.ts
  packages/gatsby-worker/src/index.ts
  packages/gatsby-worker/src/task-queue.ts
  packages/gatsby-worker/src/types.ts
  packages/gatsby-worker/src/utils.ts
  packages/gatsby-worker/tsconfig.json
  packages/gatsby/package.json
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/worker/__tests__/config.ts
  packages/gatsby/src/utils/worker/__tests__/datastore.ts
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/__tests__/reporter.ts
  packages/gatsby/src/utils/worker/__tests__/schema.ts
  packages/gatsby/src/utils/worker/__tests__/share-state.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/create-test-worker.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/ts-register.js
  packages/gatsby/src/utils/worker/__tests__/test-helpers/wrapper-for-tests.js
  packages/gatsby/src/utils/worker/pool.ts
  packages/gatsby/src/utils/worker/types.ts
  renovate.json5
Labels: topic: core

#31998 chore(gatsby): Migrate schema-composer.js to TS
  packages/gatsby/src/schema/schema-composer.js
  packages/gatsby/src/schema/schema-composer.ts
Labels: bot: merge on green, topic: TypeScript

#32157 chore: Use Issue Forms templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/DOCUMENTATION.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
Labels: type: maintenance

#32169 chore(docs): Fix environment variables example
  docs/docs/how-to/local-development/environment-variables.md
Labels: type: documentation

#32158 chore(starters): Add a Gatsby CLI instructions link
  starters/README-template.md
Labels: topic: DX

#32135 refactor(gatsby): refactor pagination in preparation to querying lmdb directly
  packages/gatsby/src/datastore/__tests__/run-fast-filters.js
  packages/gatsby/src/datastore/in-memory/run-fast-filters.ts
  packages/gatsby/src/datastore/types.ts
  packages/gatsby/src/schema/__tests__/pagination.js
  packages/gatsby/src/schema/__tests__/run-query.js
  packages/gatsby/src/schema/node-model.js
  packages/gatsby/src/schema/resolvers.ts
  packages/gatsby/src/schema/type-definitions.ts
Labels: bot: merge on green

#31882 refactor(gatsby): simplified materialization a bit
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
Labels: bot: merge on green
