Repository gatsbyjs/gatsby, pull requests merged in 2021-12, with the labels that each got.

#34158 fix(gatsby-plugin-sitemap): fix pathPrefix handling
  packages/gatsby-plugin-sitemap/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sitemap/src/gatsby-node.js
Labels: topic: plugins

#34166 chore(docs): update createNodeManifest action updatedAt description
  packages/gatsby/src/redux/actions/public.js
Labels: type: documentation

#34165 chore(gatsby-source-wordpress): remove log for manifests created
  packages/gatsby-source-wordpress/src/steps/preview/index.ts
Labels: bot: merge on green

#34161 chore(docs): remove reference to outdated example site
  docs/docs/sourcing-from-sanity.md
Labels: type: documentation

#34174 fix(gatsby-plugin-manifest): consider path prefix when getting localized manifest
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-manifest/src/gatsby-browser.js
  packages/gatsby-plugin-manifest/src/get-manifest-pathname.js
Labels: bot: merge on green, topic: plugins-PWA

#34100 feat(gatsby-source-contentful): Update contenful nodemanifest api
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/normalize.js
Labels: topic: source-contentful

#34176 feat(gatsby-source-drupal): update drupal to use latest nodemanifest api
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: status: triage needed

#34203 Clarify html.js vs. onPreRenderHTML
  docs/docs/how-to/performance/improving-site-performance.md
Labels: type: documentation, bot: merge on green

#34186 fix(gatsby-source-filesystem): Ensure fastq concurrency parameter of the correct type
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
Labels: topic: core

#34208 Add missing Comma to Plugin Options page
  docs/docs/how-to/plugins-and-themes/configuring-usage-with-plugin-options.md
Labels: status: triage needed

#34207 fix(gatsby): Reword warning about long running queries
  packages/gatsby/src/query/query-runner.ts
Labels: topic: core

#34217 chore(docs): Update navigate helper w/ query params
  docs/docs/reference/built-in-components/gatsby-link.md
Labels: type: documentation

#34204 feat(gatsby): Allow external systems to setup tracing for builds
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/source-nodes.ts
Labels: topic: build

#34085 feat(gatsby-plugin-emotion): Use correct babel preset with `jsxRuntime`
  packages/gatsby-plugin-emotion/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-emotion/src/gatsby-node.js
Labels: topic: plugins-styling

#34222 chore(docs): Add missing comma to code example
  docs/docs/how-to/plugins-and-themes/adding-gatsby-image-support.md
Labels: type: documentation

#34226 chore(gatsby): Update documentation around pathPrefix and assetPrefix combination
  docs/docs/how-to/previews-deploys-hosting/path-prefix.md
  packages/gatsby/index.d.ts
  packages/gatsby/src/utils/api-node-docs.ts
  packages/gatsby/src/utils/api-node-helpers-docs.js
Labels: type: documentation

#34234 Hotfix: use HTML entities for MDX content
  docs/docs/how-to/previews-deploys-hosting/path-prefix.md
Labels: status: triage needed

#34235 Hotfix: Add backticks to inline code comments
  packages/gatsby/index.d.ts
  packages/gatsby/src/utils/api-node-helpers-docs.js
Labels: status: triage needed

#34229 chore(gatsby-plugin-offline): Replace cpx with cpy-cli
  packages/gatsby-plugin-offline/package.json
Labels: bot: merge on green, topic: plugins-PWA

#34242 fix(gatsby-cli): make `--inspect-brk` work
  packages/gatsby-cli/src/create-cli.ts
Labels: topic: cli

#34249 fix(gatsby-source-filesystem): Replace special filename characters
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/__tests__/filename-utils.ts
  packages/gatsby-core-utils/src/filename-utils.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-source-filesystem/README.md
  packages/gatsby-source-filesystem/src/__tests__/create-file-node-from-buffer.js
  packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/utils.js
Labels: topic: core

#34227 chore(docs): Release notes for v4.4
  docs/docs/reference/release-notes/v4.4/index.md
Labels: type: documentation

#33979 fix(gatsby): Update mini-css-extract-plugin to fix inc builds issue
  e2e-tests/production-runtime/cypress/integration/assets.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/files/pdf-example.pdf
  e2e-tests/production-runtime/src/images/gatsby-astronaut.png
  e2e-tests/production-runtime/src/index.css
  e2e-tests/production-runtime/src/pages/assets.js
  e2e-tests/production-runtime/static/gatsby-astronaut.png
  integration-tests/artifacts/gatsby-browser.js
  integration-tests/artifacts/imported.css
  packages/gatsby-plugin-less/src/gatsby-node.js
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-postcss/src/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
  packages/gatsby-plugin-stylus/src/gatsby-node.js
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack-utils.ts
  yarn.lock
Labels: topic: core

#34030 fix(gatsby): Reorder head tags
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: core

#34225 fix(gatsby): handle case of html and data files mismatch
  e2e-tests/production-runtime/cypress/integration/compilation-hash.js
  e2e-tests/production-runtime/cypress/plugins/compilation-hash.js
  e2e-tests/production-runtime/cypress/plugins/index.js
  packages/gatsby-plugin-offline/src/gatsby-node.js
  packages/gatsby-plugin-offline/src/sw-append.js
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
  packages/gatsby/src/utils/page-ssr-module/entry.ts
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: topic: frontend

#34284 tests(circleci): merge base e2e env vars in all e2e tests
  .circleci/config.yml
Labels: type: maintenance, bot: merge on green

#34276 fix(gatsby-source-contentful): don't rely on getNodesByType
  packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/download-contentful-assets.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: bot: merge on green, topic: data

#34250 chore(docs): add content sync to source plugin author guide
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: type: documentation

#34277 fix(gatsby): resolve createNode promise when datastore is ready
  packages/gatsby/src/redux/actions/public.js
Labels: topic: data

#33533 fix(gatsby-source-contentful): fix base64 aspect ratio
  packages/gatsby-source-contentful/src/__fixtures__/contentful-base64.jpg
  packages/gatsby-source-contentful/src/__fixtures__/contentful-base64.png
  packages/gatsby-source-contentful/src/__tests__/gatsby-plugin-image.js
  packages/gatsby-source-contentful/src/gatsby-plugin-image.js
Labels: status: needs core review, topic: source-contentful

#33484 feat(gatsby): remove unused exports from query-engine
  packages/gatsby/src/schema/graphql-engine/print-plugins.ts
  packages/gatsby/src/schema/graphql-engine/webpack-remove-apis-loader.ts
Labels: gatsby 4

#34285 chore(gatsby-transformer-screenshot): Update old name
  packages/gatsby-transformer-screenshot/package.json
Labels: status: triage needed

#34300 docs: fix typo in gatsby-image
  docs/docs/why-gatsby-uses-graphql.md
Labels: status: triage needed

#34326 docs: Add links to gatsby cloud docs for env variables
  docs/docs/how-to/local-development/environment-variables.md
Labels: status: triage needed

#34318 docs: use en-US version mdn links
  docs/docs/conceptual/security-in-gatsby.md
Labels: status: triage needed

#34315 docs: Match egghead.io video instructions
  docs/tutorial/building-a-theme.md
Labels: status: triage needed

#34337 fix(gatsby-plugin-preact): fix exports resolution webpack
  packages/gatsby-plugin-preact/.babelrc
  packages/gatsby-plugin-preact/package.json
  packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-browser.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
  yarn.lock
Labels: bot: merge on green

#34340 docs(gatsby-remark-prismjs): Update http links to use https
  packages/gatsby-remark-prismjs/README.md
Labels: status: triage needed

#34322 docs: Add shell code block & remove starter link for sass
  docs/docs/how-to/styling/sass.md
Labels: status: triage needed

#34347 docs: fix typo gatby-node.js -> gatsby-node.js
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: status: triage needed
