Repository gatsbyjs/gatsby, pull requests merged in 2021-03, with the labels that each got.

#29819 fix(docs): update library link in docs
  examples/using-page-transitions/README.md
Labels: type: documentation

#29846 chore: fix spelling, remove whitespace and fix link
  docs/docs/conceptual/choosing-a-cms.md
  docs/docs/conceptual/gatsby-for-ecommerce.md
  docs/docs/glossary/npm.md
  docs/docs/how-to/performance/improving-site-performance.md
  packages/gatsby-plugin-schema-snapshot/README.md
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-source-wordpress/docs/getting-started.md
  packages/gatsby-source-wordpress/src/models/image-nodes.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
  rfcs/README.md
  rfcs/text/0004-native-graphql-source.md
Labels: type: documentation

#29793 chore: upgrade postcss & plugins
  packages/gatsby-plugin-sass/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#29855 fix(gatsby): Improve Fast Refresh overlay styles
  packages/gatsby/cache-dir/fast-refresh-overlay/style.js
Labels: topic: hot reloading

#29831 fix(gatsby-plugin-preact): fix fast-refresh
  packages/gatsby/cache-dir/fast-refresh-overlay/index.js
Labels: topic: preact*

#29839 fix(gatsby): fix some css HMR edge cases
  e2e-tests/development-runtime/cypress/integration/styling/plain-css.js
  e2e-tests/development-runtime/src/pages/styling/not-visited-plain-css-not-imported-initially.css
  e2e-tests/development-runtime/src/pages/styling/not-visited-plain-css.css
  e2e-tests/development-runtime/src/pages/styling/not-visited-plain-css.js
  e2e-tests/development-runtime/src/pages/styling/plain-css-not-imported-initially.css
  e2e-tests/development-runtime/src/pages/styling/plain-css.js
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/force-css-hmr-for-edge-cases.ts
Labels: topic: webpack/babel

#27272 chore(docs): updated doc for payment using square
  docs/docs/processing-payments-with-square.md
Labels: bot: merge on green, hacktoberfest-accepted, type: documentation

#26933 fix(gatsby-react-router-scroll): debounce function for scollListener
  e2e-tests/production-runtime/cypress/integration/scroll-behavior.js
  packages/gatsby-react-router-scroll/src/scroll-handler.tsx
Labels: bot: merge on green, topic: reach/router and navigation

#29791 chore: update core-js
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/dependencies.ts.snap
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-legacy-polyfills/package.json
  packages/gatsby-legacy-polyfills/src/exclude.js
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#29792 chore(gatsby): move to latest joi
  integration-tests/structured-logging/__tests__/to-do.js
  integration-tests/structured-logging/package.json
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/structured-errors/__tests__/error-schema.ts
  packages/gatsby-cli/src/structured-errors/construct-error.ts
  packages/gatsby-cli/src/structured-errors/error-schema.ts
  packages/gatsby/package.json
  packages/gatsby/src/joi-schemas/__tests__/__snapshots__/joi.ts.snap
  packages/gatsby/src/joi-schemas/__tests__/joi.ts
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/actions/public.js
  yarn.lock
Labels: type: maintenance

#29853 fix(gatsby-source-contentful): use reporter progressbar instead of own
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js
  packages/gatsby-source-contentful/src/download-contentful-assets.js
Labels: topic: Contentful, type: maintenance

#29856 fix(create-gatsby): Use legacy peer deps
  packages/create-gatsby/src/__tests__/init-starter.ts
  packages/create-gatsby/src/init-starter.ts
Labels: bot: merge on green, topic: cli

#29857 chore: update peerdeps to latest major versions
  packages/gatsby-plugin-gatsby-cloud/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-remark-embed-snippet/package.json
  packages/gatsby-remark-images/package.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-transformer-javascript-frontmatter/package.json
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby-transformer-sqip/package.json
Labels: type: maintenance

#29720 fix(gatsby): Fix various small DEV_SSR bugs exposed in development_runtime tests
  packages/gatsby/cache-dir/app.js
  packages/gatsby/src/utils/dev-ssr/develop-html-route.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/develop-preload-headers.ts
Labels: topic: ssr

#29859 docs(gatsby-plugin-image): Point people to the new plugin
  docs/docs/conceptual/gatsby-core-philosophy.md
  docs/docs/images-and-files.md
  docs/docs/plugins.md
  docs/docs/porting-an-html-site-to-gatsby.md
  docs/docs/porting-from-create-react-app-to-gatsby.md
  docs/docs/reference/built-in-components/gatsby-image.md
  docs/docs/working-with-images.md
Labels: status: needs docs review

#28029 chore(docs): add paths to unit-testing using typescript
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#29402 chore(docs): Update headless WordPress article
  docs/docs/glossary/headless-wordpress.md
Labels: topic: WordPress, type: documentation

#29696 chore(docs): Add twitter links to tutorial
  docs/docs/tutorial/part-seven/index.md
Labels: status: needs docs review

#29864 fix(gatsby): Remove `react-hot-loader` deps & other unused deps
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#29885 fix(gatsby): with some custom babel configs array spreading with Set is not safe
  packages/gatsby/cache-dir/fast-refresh-overlay/components/graphql-errors.js
  packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js
Labels: topic: hot reloading

#29898 Update migrating-from-v2-to-v3.md
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: bot: merge on green, type: documentation

#29897 fix(gatsby-transformer-sharp): Fix options override
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: topic: images/media

#29893 docs: remove the deprecated gatsby-image tutorial
  docs/tutorial/gatsby-image-tutorial/ErrorMessage.png
  docs/tutorial/gatsby-image-tutorial/index.md
Labels: type: documentation

#29900 fix(gatsby): Add dir=ltr to Fast Refresh overlay
  packages/gatsby/cache-dir/fast-refresh-overlay/components/overlay.js
Labels: topic: hot reloading

#29837 chore(docs): update readme
  README.md
  packages/gatsby/README.md
Labels: type: documentation

#29863 chore(docs): Update hosting instructions in OSS page for Cloud
  docs/docs/how-to/previews-deploys-hosting/deploying-to-gatsby-cloud.md
Labels: type: documentation

#29899 fix(gatsby): Update example sites to build with Gatsby v3
  examples/gatsbygram/gatsby-config.js
  examples/using-contentful/src/pages/image-api.js
  examples/using-emotion-prismjs/package.json
  examples/using-emotion-prismjs/src/components/layout.js
  examples/using-emotion-prismjs/src/pages/index.js
  examples/using-emotion-prismjs/src/prism-styles.js
  examples/using-emotion-prismjs/src/templates/blog-post.js
  examples/using-emotion/package.json
  examples/using-emotion/src/pages/index.js
  examples/using-gatsby-image/package.json
  examples/using-gatsby-image/src/components/image-gallery.js
  examples/using-gatsby-image/src/components/navigation.js
  examples/using-gatsby-image/src/components/page-title.js
  examples/using-gatsby-image/src/pages/index.js
  examples/using-remark-copy-linked-files/gatsby-config.js
  examples/using-shopify/src/components/image-picker.js
  examples/using-shopify/src/components/product-list.js
  examples/using-shopify/src/components/product.js
  examples/using-square-payments/package.json
  examples/using-stylus/src/pages/css-modules.js
Labels: type: maintenance

#29762 chore(docs): v3 Release Notes
  docs/docs/reference/built-in-components/layouts.mp4
  docs/docs/reference/release-notes/v3.0/compile-graphql-runtime-errors.jpg
  docs/docs/reference/release-notes/v3.0/graphql-deprecation-warnings.png
  docs/docs/reference/release-notes/v3.0/incremental-builds-in-oss.jpg
  docs/docs/reference/release-notes/v3.0/index.md
Labels: type: documentation

#29747 chore(docs): Migrating from v2 to v3
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: type: documentation

#29805 chore(starters): Upgrade minimal starter and add link to cloud
  starters/gatsby-starter-minimal/package.json
  starters/gatsby-starter-minimal/src/pages/index.js
Labels: bot: merge on green

#29910 chore(docs): Improve `fs` section of release notes
  docs/docs/reference/release-notes/v3.0/index.md
Labels: type: documentation

#29912 docs(gatsby-plugin-image): remove beta
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: status: needs docs review

#29914 chore(docs): Add code blocks to headings in release notes
  docs/docs/reference/release-notes/v3.0/index.md
Labels: bot: merge on green, type: documentation

#29802 docs (gatsby-plugin-image): Remove filesystem from config
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: status: needs docs review

#29919 chore: Update default & blog starter to v3
  starters/blog/README.md
  starters/blog/content/assets/profile-pic.jpg
  starters/blog/gatsby-config.js
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/blog/src/components/bio.js
  starters/blog/src/components/layout.js
  starters/blog/src/components/seo.js
  starters/blog/src/images/gatsby-icon.png
  starters/blog/src/images/profile-pic.png
  starters/blog/src/pages/404.js
  starters/blog/src/pages/index.js
  starters/blog/src/pages/using-typescript.tsx
  starters/blog/src/templates/blog-post.js
  starters/default/README.md
  starters/default/gatsby-config.js
  starters/default/package-lock.json
  starters/default/package.json
  starters/default/src/components/header.js
  starters/default/src/components/image.js
  starters/default/src/components/layout.js
  starters/default/src/components/seo.js
  starters/default/src/pages/404.js
  starters/default/src/pages/index.js
  starters/default/src/pages/page-2.js
  starters/default/src/pages/using-typescript.tsx
Labels: topic: starters

#29920 chore(docs): Make note about cloud plugin more precise
  docs/docs/reference/release-notes/v3.0/index.md
Labels: type: documentation

#29921 docs(migrating-from-v2-to-v3): drop "work-in-progress" note
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: type: documentation

#29922 chore(starters): Update hello-world and AVIF
  starters/blog/src/components/bio.js
  starters/default/src/pages/index.js
  starters/hello-world/README.md
  starters/hello-world/package-lock.json
  starters/hello-world/package.json
Labels: topic: starters

#29925 fix(publish-starters): don't presume 'master' is default branch
  scripts/publish-starters.sh
Labels: topic: automation

#29926 fix(publish-starters): fix syntax
  scripts/publish-starters.sh
Labels: topic: automation

#29930 chore(docs): Fix link to /docs/conceptual/using-gatsby-image
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: status: triage needed

#29936 chore(starters): update template to use hosting
  starters/README-template.md
Labels: topic: starters

#29941 feat(gatsby-source-wordpress): Log when nodes are duplicates
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js
Labels: topic: WordPress

#29934 chore(docs): update css modules docs
  docs/docs/how-to/styling/css-modules.md
  docs/docs/recipes/styling-css.md
  docs/docs/reference/release-notes/migrating-from-v1-to-v2.md
  docs/docs/tutorial/part-two/index.md
Labels: type: documentation, v3migration

#29950 chore(docs): Update features table
  docs/features/gatsby-jamstack-specs.csv
Labels: type: documentation

#29638 refactor(gatsby-transformer-remark): Refactors out Bluebird usage in transformer-remark
  packages/gatsby-transformer-remark/package.json
  packages/gatsby-transformer-remark/src/__tests__/on-node-create.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: topic: Markdown/remark

#29935 fix(gatsby): fix routing for paths with characters like `@` etc
  e2e-tests/development-runtime/cypress/integration/navigation/linking.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/pages/index.js
  e2e-tests/production-runtime/cypress/integration/1-production.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/src/pages/index.js
  packages/gatsby/package.json
  yarn.lock
Labels: topic: reach/router and navigation

#29957 fix(gatsby-plugin-image): Use template from core package
  packages/gatsby-plugin-image/src/babel-plugin-parse-static-images.ts
Labels: topic: images/media

#29942 chore(gatsby-source-wordpress): Test html link transforms
  packages/gatsby-source-wordpress/__tests__/process-node.test.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
Labels: topic: WordPress

#29954 fix(gatsby): change browserlist to web/es5
  packages/gatsby/src/utils/webpack.config.js
Labels: status: needs core review, topic: webpack/babel

#29965 chore(gatsby-plugin-sass): Update README
  packages/gatsby-plugin-sass/README.md
Labels: topic: sass, type: documentation

#29748 fix(gatsby): Fix various small DEV_SSR bugs exposed in development_runtime tests
  packages/gatsby/cache-dir/app.js
  packages/gatsby/src/utils/dev-ssr/develop-html-route.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/develop-preload-headers.ts
Labels: topic: ssr, type: cherry

#29986 fix(gatsby-plugin-sass): Change `modules` option around
  packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: topic: sass

#29881 fix(gatsby-source-wordpress): image fixes (#29813)
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
Labels: type: cherry

#29953 fix(gatsby): handle case of removing trailing slash in inc builds
  integration-tests/artifacts/__tests__/index.js
  integration-tests/artifacts/gatsby-node.js
  integration-tests/artifacts/src/pages/page-that-will-have-trailing-slash-removed.js
  packages/gatsby/src/commands/__tests__/build-utils.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build-utils.ts
  packages/gatsby/src/redux/reducers/html.ts
  packages/gatsby/src/redux/types.ts
Labels: topic: conditional page builds*

#30013 docs: clarify env variable prefix in gatsby-source-filesystem docs
  packages/gatsby-source-filesystem/README.md
Labels: topic: filesystem, type: documentation

#29980 fix(gatsby-source-contentful): Remove image beta warning
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: Contentful

#30028 chore(docs): Remove unused features files
  docs/features/gatsby-cms-specs.csv
  docs/features/gatsby-features-specs.csv
  docs/features/gatsby-jamstack-specs.csv
Labels: type: documentation

#30012 chore: fix spelling, remove whitespace and fix links
  dictionary.txt
  docs/docs/deploying-to-digitalocean-droplet.md
  docs/docs/deploying-to-gitlab-pages.md
  docs/docs/glossary/continuous-deployment.md
  docs/docs/glossary/headless-wordpress.md
  docs/docs/how-to/adding-common-features/adding-search.md
  docs/docs/how-to/local-development/gatsby-on-linux.md
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
  docs/docs/sourcing-from-forestry.md
  docs/docs/tutorial/part-zero/index.md
  packages/gatsby-source-wordpress/docker/wordpress/install-wp-graphql-plugins.sh
  packages/gatsby/src/redux/nodes.ts
  packages/gatsby/src/schema/__tests__/run-query.js
Labels: type: documentation

#29994 docs(gatsby-plugin-image): fixing a typo.
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
Labels: status: triage needed

#29972 feat(gatsby-source-wordpress): Improve 50* error messages
  packages/gatsby-source-wordpress/__tests__/fetch-graphql.test.js
  packages/gatsby-source-wordpress/src/steps/check-plugin-requirements.ts
  packages/gatsby-source-wordpress/src/utils/fetch-graphql.ts
  packages/gatsby-source-wordpress/src/utils/report.ts
Labels: topic: WordPress

#30032 chore: add process information to migration guide
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: type: documentation

#30033 chore: adjust @reach/router imports to not rely just on webpack alias
  packages/gatsby-link/src/index.js
  packages/gatsby-react-router-scroll/src/scroll-handler.tsx
  packages/gatsby-react-router-scroll/src/use-scroll-restoration.ts
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/root.js
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: reach/router and navigation

#30044 chore(docs): Rm empty code block
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: status: triage needed

#30038 Revert "fix(gatsby-plugin-sass): Change `modules` option around"
  packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: topic: sass

#30047 fix(gatsby): always pass `stage` option to `babel-preset-gatsby`
  packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.ts.snap
  packages/gatsby/src/redux/__tests__/babelrc.ts
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/babel-loader.js
Labels: topic: webpack/babel

#30065 fix(gatsby-plugin-image): broken documentation links
  packages/gatsby-plugin-image/README.md
Labels: topic: images/media, type: documentation

#30056 chore(gatsby-source-wordpress): Remove version from README
  packages/gatsby-source-wordpress/README.md
Labels: topic: WordPress, type: documentation

#30041 chore(docs): Add link to art direction docs
  docs/docs/reference/release-notes/image-migration-guide.md
Labels: topic: images/media, type: documentation

#30035 chore(gatsby-plugin-postcss): Update README to show correct usage
  packages/gatsby-plugin-postcss/README.md
Labels: type: documentation

#30091 chore(docs): Add version mismatch info to migration guide
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: type: documentation

#30092 fix(gatsby): Fix broken reporter call
  packages/gatsby/src/utils/api-runner-node.js
Labels: bot: merge on green, topic: reporter

#30090 chore: adjust npm release dist tag for v2
  package.json
Labels: type: maintenance

#29981 feat(gatsby-plugin-image): Better error message for missing alt
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
Labels: bot: merge on green, topic: a11y

#30103 fix(gatsby-source-contentful): Set image source format
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: Contentful

#30102 chore: make ./starters/upgrade-starters.sh executable
  starters/upgrade-starters.sh
Labels: topic: starters

#30127 fix(gatsby): don't ignore SOURCE_FILE_CHANGED event
  packages/gatsby/src/state-machines/develop/index.ts
Labels: topic: state machine

#30098 test(e2e): add test suite for sass, less and stylus
  e2e-tests/development-runtime/cypress/integration/styling/less.js
  e2e-tests/development-runtime/cypress/integration/styling/sass.js
  e2e-tests/development-runtime/cypress/integration/styling/stylus.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/src/pages/styling/less-plain.less
  e2e-tests/development-runtime/src/pages/styling/less.js
  e2e-tests/development-runtime/src/pages/styling/less.module.less
  e2e-tests/development-runtime/src/pages/styling/sass-plain.scss
  e2e-tests/development-runtime/src/pages/styling/sass.js
  e2e-tests/development-runtime/src/pages/styling/sass.module.scss
  e2e-tests/development-runtime/src/pages/styling/stylus-plain.styl
  e2e-tests/development-runtime/src/pages/styling/stylus.js
  e2e-tests/development-runtime/src/pages/styling/stylus.module.styl
  e2e-tests/production-runtime/cypress/integration/styling/less.js
  e2e-tests/production-runtime/cypress/integration/styling/sass.js
  e2e-tests/production-runtime/cypress/integration/styling/stylus.js
  e2e-tests/production-runtime/gatsby-config.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/pages/styling/less-plain.less
  e2e-tests/production-runtime/src/pages/styling/less.js
  e2e-tests/production-runtime/src/pages/styling/less.module.less
  e2e-tests/production-runtime/src/pages/styling/sass-plain.scss
  e2e-tests/production-runtime/src/pages/styling/sass.js
  e2e-tests/production-runtime/src/pages/styling/sass.module.scss
  e2e-tests/production-runtime/src/pages/styling/stylus-plain.styl
  e2e-tests/production-runtime/src/pages/styling/stylus.js
  e2e-tests/production-runtime/src/pages/styling/stylus.module.styl
Labels: topic: automation

#30025 feat(gatsby): Add darkmode support to Fast Refresh overlay
  packages/gatsby/cache-dir/fast-refresh-overlay/style.js
Labels: topic: hot reloading

#30123 fix(gatsby): set program.verbose when VERBOSE env var is used
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop-process.ts
Labels: topic: reporter

#30132 fix(gatsby): freeze the schema only after rebuilding with SitePage
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
  packages/gatsby/src/schema/schema.js
Labels: topic: GraphQL

#30140 docs(gatsby-plugin-image): Add a troubleshooting section
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: status: needs docs review

#30016 feat(gatsby-source-wordpress): Add WP_GATSBY_PREVIEW_DEBUG env var to enable preview debug mode
  packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md
  packages/gatsby-source-wordpress/src/steps/preview/index.ts
Labels: topic: WordPress

#30128 chore(docs): Update "Upgrading NodeJS"
  docs/docs/upgrading-node-js.md
Labels: type: documentation

#30141 fix(gatsby-plugin-image): Handle placeholder in plugin toolkit
  packages/gatsby-plugin-image/src/__tests__/image-utils.ts
  packages/gatsby-plugin-image/src/image-utils.ts
Labels: topic: images/media

#30160 chore(docs): set process polyfill correctly
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: type: documentation

#30158 fix(gatsby-plugin-mdx): fix html field resolver to work with webpack@5
  e2e-tests/mdx/cypress/integration/html-field.js
  e2e-tests/mdx/gatsby-node.js
  e2e-tests/mdx/package.json
  e2e-tests/mdx/src/pages/html.mdx
  packages/gatsby-plugin-mdx/utils/render-html.js
Labels: topic: MDX, topic: webpack/babel

#29675 contentful <3 gatsby v3
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: bot: merge on green, topic: Contentful

#30172 fix(gatsby-plugin-mdx): fix html field resolver to work with webpack@5 (#30158)
  e2e-tests/mdx/cypress/integration/html-field.js
  e2e-tests/mdx/gatsby-node.js
  e2e-tests/mdx/package.json
  e2e-tests/mdx/src/pages/html.mdx
  packages/gatsby-plugin-mdx/utils/render-html.js
Labels: type: cherry

#30031 fix(gatsyby): improve error messages for errors outside of react"
  packages/gatsby/cache-dir/__tests__/ensure-resources.tsx
  packages/gatsby/cache-dir/ensure-resources.js
  packages/gatsby/cache-dir/loader.js
Labels: topic: frontend-core

#30175 fix(docs): update conceptual gatsby image doc
  docs/docs/conceptual/using-gatsby-image.md
Labels: type: documentation

#30161 chore(docs): Update deploying-to-digitalocean-droplet
  docs/docs/deploying-to-digitalocean-droplet.md
Labels: type: documentation

#30146 chore(docs): Adding maintenance window for v2
  README.md
  packages/gatsby/README.md
Labels: type: documentation

#30155 fix(gatsby-plugin-netlify): Add an allow list for redirect options
  packages/gatsby-plugin-netlify/src/create-redirects.js
Labels: topic: netlify

#30197 chore(docs): Fix typo in migration guide
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: status: triage needed

#30193 fix(gatsby): workaround some webpack issues causing first save after running gatsby develop to not have any effect
  packages/gatsby/src/bootstrap/__tests__/requires-writer.js
  packages/gatsby/src/utils/gatsby-webpack-virtual-modules.ts
  packages/gatsby/src/utils/start-server.ts
Labels: topic: hot reloading

#30222 Use a parameter in express middleware and ignore function extension
  packages/gatsby-plugin-functions/src/gatsby-node.ts
Labels: status: triage needed

#30209 chore(starters): Update WordPress blog README
  starters/gatsby-starter-wordpress-blog/README.md
Labels: type: documentation

#30243 chore(docs): Update using-web-fonts
  docs/docs/how-to/styling/using-web-fonts.md
Labels: type: documentation

#30239 chore(docs): Fix link to markdown-syntax
  docs/docs/glossary/markdown.md
Labels: type: documentation

#30205 chore(dosc): Update deploying-to-digitalocean-droplet
  docs/docs/deploying-to-digitalocean-droplet.md
Labels: type: documentation

#30162 chore: Add Fast Refresh/Hot Reloading E2E tests
  e2e-tests/development-runtime/.eslintrc
  e2e-tests/development-runtime/content/error-recovery/page-query.json
  e2e-tests/development-runtime/content/error-recovery/static-query.json
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/compile-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/page-query-result-runtime-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/query-validation-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/runtime-error.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/error-handling/static-query-result-runtime-error.js
  e2e-tests/development-runtime/cypress/support/commands.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/src/components/image.js
  e2e-tests/development-runtime/src/pages/error-handling/compile-error.js
  e2e-tests/development-runtime/src/pages/error-handling/page-query-result-runtime-error.js
  e2e-tests/development-runtime/src/pages/error-handling/query-validation-error.js
  e2e-tests/development-runtime/src/pages/error-handling/runtime-error.js
  e2e-tests/development-runtime/src/pages/error-handling/static-query-result-runtime-error.js
Labels: topic: automation, topic: hot reloading

#30216 fix(gatsby): be less aggressive when marking builtin methods as unsafe
  packages/gatsby/cache-dir/ssr-builtin-trackers/http.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/https.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/tracking-unsafe-module-wrapper.js
Labels: topic: conditional page builds*

#30253 chore(docs): Add example to link directive
  docs/docs/reference/graphql-data-layer/schema-customization.md
Labels: type: documentation

#30217 fix(gatsby-plugin-netlify): upgrade webpack-assets-manifest for compatibility with webpack@5
  packages/create-gatsby/tsconfig.json
  packages/gatsby-plugin-netlify/package.json
  packages/gatsby-source-wordpress/tsconfig.json
  yarn.lock
Labels: topic: netlify

#30266 chore(docs): Update deploying-to-digitalocean-droplet
  docs/docs/deploying-to-digitalocean-droplet.md
Labels: type: documentation

#30263 chore(docs): Updated tutorial deployment step.
  docs/docs/tutorial/part-one/index.md
Labels: type: documentation

#30268 docs: release notes for v3.1
  docs/docs/reference/release-notes/v3.1/index.md
Labels: type: documentation

#30283 chore: use 2 for release instead of 1
  docs/docs/reference/release-notes/v3.1/index.md
Labels: type: documentation

#30271 fix(gatsby-plugin-image): Better StaticImage errors
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/node-apis/image-processing.ts
  packages/gatsby-plugin-image/src/node-apis/parser.ts
  packages/gatsby-plugin-image/src/node-apis/preprocess-source.ts
  yarn.lock
Labels: topic: images/media

#30287 fix(gatsby): be less aggressive when marking builtin methods as unsafe (#30216)
  packages/gatsby/cache-dir/ssr-builtin-trackers/http.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/https.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/tracking-unsafe-module-wrapper.js
Labels: type: cherry

#30286 docs: Update beta/deprecation status of image plugins
  docs/docs/how-to/images-and-media/using-gatsby-image.md
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: status: needs docs review, topic: images/media

#30277 Set a default functions directory path
  packages/gatsby-plugin-functions/src/gatsby-node.ts
Labels: status: triage needed

#30027 chore(docs): Remove duplicate "releases & migration" doc
  docs/docs/releases-and-migration.md
Labels: type: documentation

#30133 chore(docs): Add Fast Refresh entry
  docs/docs/glossary.md
  docs/docs/reference/local-development/fast-refresh.md
  docs/docs/reference/release-notes/v3.0/index.md
Labels: type: documentation

#30327 docs: Fixes to image CDN doc
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: type: documentation

#30326 fix(gatsby-plugin-image): Better StaticImage errors (#30271)
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/node-apis/image-processing.ts
  packages/gatsby-plugin-image/src/node-apis/parser.ts
  packages/gatsby-plugin-image/src/node-apis/preprocess-source.ts
  yarn.lock
Labels: type: cherry

#30330 docs: Add background images docs
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: status: needs docs review, topic: images/media

#30334 chore: Update styling READMEs CSS modules info
  packages/gatsby-plugin-less/README.md
  packages/gatsby-plugin-postcss/README.md
  packages/gatsby-plugin-sass/README.md
  packages/gatsby-plugin-stylus/README.md
Labels: type: documentation

#30318 fix(gatsby): do not fail on 3rd-party schemas with relay-classic support
  packages/gatsby/src/schema/__tests__/rebuild-schema.js
  packages/gatsby/src/schema/schema.js
Labels: topic: GraphQL

#30221 fix(gatsby-plugin-image): image partial rendering
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/intersection-observer.ts
  packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Labels: topic: images/media

#30328 fix(gatsby-plugin-image): Only use default breakpoints for fullwidth
  packages/gatsby-plugin-image/src/components/__tests__/hooks.ts
  packages/gatsby-plugin-image/src/components/hooks.ts
Labels: topic: images/media

#30348 feat(gatsby-plugin-image): data-srcset should be used to prevent overly eager loading on chrome
  integration-tests/images/__tests__/images.ts
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
  packages/gatsby-plugin-image/src/components/picture.tsx
  packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Labels: topic: images/media

#30351 docs(gatsby-plugin-image): Add GraphCMS to supported list
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: status: triage needed

#30343 chore(docs): Fix typo in createPages doc
  packages/gatsby/src/utils/api-node-docs.ts
Labels: type: documentation

#29640 fix(gatsby): Add reporter.panic in empty catch in load-themes
  packages/gatsby/src/bootstrap/load-themes/index.js
Labels: topic: reporter, topic: themes

#30389 fix(gatsby): Fix wrong resolve id for CommentJson type
  examples/using-type-definitions/gatsby-node.js
Labels: type: maintenance

#30356 fix(gatsby-source-wordpress): improve error message for folks who've never used WP_DEBUG
  packages/gatsby-source-wordpress/src/utils/fetch-graphql.ts
Labels: topic: WordPress

#30396 chore(gatsby-source-contentful): updates to downloadLocal description
  packages/gatsby-source-contentful/README.md
Labels: bot: merge on green, topic: Contentful

#29289 fix(drupal): Support forward revisions for Drupal paragraphs
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/src/__tests__/fixtures/article-includes.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi-includes.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/text.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/normalize.js
  packages/gatsby-source-drupal/src/utils.js
Labels: bot: merge on green, topic: Drupal

#30329 chore(docs): Add "Debugging Incremental Builds"
  docs/docs/debugging-incremental-builds.md
  docs/docs/debugging-the-build-process.md
  docs/docs/reference/gatsby-cli.md
Labels: type: documentation

#30331 fix(gatsby,gatsby-cli): Correct behavior for reporter.error with pluginName
  packages/gatsby-cli/src/reporter/__tests__/__snapshots__/index.ts.snap
  packages/gatsby-cli/src/reporter/__tests__/index.ts
  packages/gatsby-cli/src/reporter/reporter.ts
  packages/gatsby-cli/src/structured-errors/__tests__/error-map.ts
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-cli/src/structured-errors/types.ts
  packages/gatsby/src/utils/__tests__/api-runner-node.js
  packages/gatsby/src/utils/api-runner-node.js
Labels: topic: cli, topic: reporter

#30419 chore(docs): Fix typo in using-gatsby-image-plugin
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: type: documentation

#30418 fix(gatsby-remark-images): fix unresolved promise
  packages/gatsby-remark-images/src/index.js
Labels: topic: Markdown/remark

#30426 fix(gatsby): update nested input types when rebuilding SitePage
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
  packages/gatsby/src/schema/types/derived-types.ts
Labels: topic: GraphQL

#29787 fix(gatsby): validate local plugin options schema
  integration-tests/structured-logging/README.md
  integration-tests/structured-logging/__tests__/validate-options.js
  integration-tests/structured-logging/gatsby-config.js
  integration-tests/structured-logging/local-plugin-with-path/gatsby-node.js
  integration-tests/structured-logging/local-plugin-with-path/index.js
  integration-tests/structured-logging/local-plugin-with-path/package.json
  integration-tests/structured-logging/plugins/local-plugin/gatsby-node.js
  integration-tests/structured-logging/plugins/local-plugin/index.js
  integration-tests/structured-logging/plugins/local-plugin/package.json
  packages/gatsby/src/bootstrap/load-plugins/__tests__/fixtures/local-plugin/gatsby-node.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/fixtures/local-plugin/index.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/fixtures/local-plugin/package.json
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: topic: plugins

#30023 fix(gatsby): Add `allowNamespace` option to ESLint config
  packages/gatsby/package.json
  packages/gatsby/src/utils/eslint-config.ts
  yarn.lock
Labels: topic: internal

#30349 fix(gatsby-source-wordpress): requestConcurrency
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js
Labels: topic: WordPress

#30345 docs(gatsby-plugin-image): Warn about `styled(StaticImage)` usage
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
Labels: status: needs docs review, topic: images/media

#30457 perf(gatsby): Optimise `distinct` queries
  packages/gatsby/src/schema/resolvers.ts
Labels: bot: merge on green

#30491 fix(gatsby-plugin-image): Force render if props have changed
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Labels: topic: images/media

#30281 chore(gatsby-source-wordpress): updates for gatsby v3
  packages/gatsby-source-wordpress/docs/tutorials/transforming-data.md
  packages/gatsby-source-wordpress/src/steps/persist-cached-images.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/before-change-node/menu.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/fetch-node-updates.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/delete.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
Labels: topic: WordPress

#30460 fix(gatsby): Handle arrays of dates in distinct
  packages/gatsby/src/schema/__tests__/connection-input-fields.js
  packages/gatsby/src/schema/resolvers.ts
Labels: bot: merge on green

#30466 fix(gatsby-plugin-image): Correctly calculate aspect ratio when width and height are both set
  packages/gatsby-plugin-image/src/__tests__/image-utils.ts
  packages/gatsby-plugin-image/src/image-utils.ts
Labels: topic: images/media

#30489 fix(gatsby-plugin-mdx): timeToRead returns NaN when word count is undefined
  packages/gatsby-plugin-mdx/gatsby/source-nodes.js
Labels: topic: MDX

#30501 fix(gatsby): merge inherited interfaces when merging types
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/schema.js
Labels: topic: GraphQL

#30496 chore(gatsby-source-wordpress): use node interface inheritance instead of @nodeInterface
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/build-types.js
Labels: topic: WordPress

#30520 chore(README): Adjust heading hierarchy
  README.md
Labels: type: maintenance

#30257 fix(gatsby-source-contentful): Improve network error handling
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/src/__tests__/fetch-network-errors.js
  packages/gatsby-source-contentful/src/fetch.js
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: bot: merge on green, topic: Contentful

#30414 chore(contentful): create compiled files in dist instead of .
  packages/gatsby-source-contentful/.npmignore
Labels: bot: merge on green, topic: Contentful
