Repository gatsbyjs/gatsby, pull requests merged in 2021-01, with the labels that each got.

#28826 fix(gatsby-plugin-sharp): Pass format-specific options in image data resolver
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-sharp/src/image-data.ts
Labels: topic: images/media

#28750 Update Fontsource Documentation
  docs/docs/recipes/styling-css.md
Labels: type: documentation

#28756 chore(docs): fix a broken url
  docs/docs/how-to/plugins-and-themes/using-a-gatsby-theme.md
Labels: type: documentation

#28761 chore: Fix spelling
  e2e-tests/production-runtime/cypress/integration/types/site-data.js
  examples/creating-source-plugins/source-plugin/gatsby-node.js
  packages/create-gatsby/src/__tests__/init-starter.ts
  packages/gatsby-cli/CHANGELOG.md
  packages/gatsby-plugin-image/README.md
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-plugin-page-creator/src/path-utils.ts
  packages/gatsby-plugin-utils/src/utils/plugin-options-schema-joi-type.ts
  packages/gatsby-recipes/src/graphql-server/index.js
  packages/gatsby-recipes/src/renderer/render.js
  packages/gatsby-remark-autolink-headers/README.md
  packages/gatsby-source-filesystem/src/__tests__/create-file-node.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby/CHANGELOG.md
  packages/gatsby/src/cache/__tests__/cache-fs.js
  packages/gatsby/src/cache/cache-fs.ts
  packages/gatsby/src/utils/__tests__/jobs-manager.js
  packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js
  packages/gatsby/src/utils/start-server.ts
  rfcs/text/000-cli-redesign.md
  rfcs/text/0004-native-graphql-source.md
  rfcs/text/0006-node-8-minimum-version.md
Labels: status: triage needed

#28763 chore(gatsby-transformer-csv): fix whitespace
  packages/gatsby-transformer-csv/README.md
Labels: type: documentation

#28767 chore(docs): Fixing broken link
  docs/docs/mdx/writing-pages.md
Labels: type: documentation

#28782 chore(docs): Updated Twin + Gatsby + Emotion link
  docs/docs/how-to/styling/tailwind-css.md
Labels: type: documentation

#28785 chore(docs): Update lighthouse instructions in tutorial
  docs/docs/tutorial/part-eight/index.md
Labels: type: documentation

#28741 fix(gatsby-plugin-image): Better error logging
  packages/gatsby-plugin-image/src/node-apis/image-processing.ts
  packages/gatsby-plugin-image/src/node-apis/watcher.ts
Labels: topic: images/media

#28834 fix(gatsby-plugin-image): Correct image styles
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
Labels: bot: merge on green, topic: images/media

#28811 chore(docs): Update migrate-remark-to-mdx
  docs/docs/how-to/routing/migrate-remark-to-mdx.md
Labels: type: documentation

#28837 fix(lint): ran formatter
  docs/docs/tutorial/part-eight/index.md
Labels: status: triage needed

#28842 docs: Add avif and remote image release notes
  docs/docs/reference/release-notes/v2.30/index.md
Labels: bot: merge on green

#28471 feature(gatsby): Extract non-css-in-js css and add add to <head> when SSRing in dev
  integration-tests/ssr/__mocks__/styleMock.js
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
  integration-tests/ssr/__tests__/ssr.js
  integration-tests/ssr/gatsby-browser.js
  integration-tests/ssr/gatsby-config.js
  integration-tests/ssr/jest.config.js
  integration-tests/ssr/package.json
  integration-tests/ssr/postcss.config.js
  integration-tests/ssr/sample.css
  integration-tests/ssr/src/pages/index.js
  integration-tests/ssr/src/pages/usingtailwind.js
  integration-tests/ssr/src/styles/tailwind.css
  integration-tests/ssr/src/test.css
  integration-tests/ssr/src/test.js
  integration-tests/ssr/tailwind.config.js
  integration-tests/ssr/test-output.js
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: ssr, type: feature or enhancement

#28844 feat(gatsby): Partially release develop SSR to 5%
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/flags.ts
Labels: topic: ssr

#28843 chore(release): Add dev-ssr to the release notes for 2.30
  docs/docs/reference/release-notes/v2.30/index.md
Labels: bot: merge on green

#28684 fix(gatsby-cli): fix timers on progress bar
  packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
Labels: bot: merge on green, topic: cli, type: bug

#28835 fix(gatsby-plugin-image): Fix handling of sizes prop in SSR
  e2e-tests/gatsby-static-image/cypress/integration/constrained.js
  e2e-tests/gatsby-static-image/cypress/integration/fixed.js
  e2e-tests/gatsby-static-image/cypress/integration/fluid.js
  e2e-tests/gatsby-static-image/src/pages/constrained.js
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
Labels: bot: merge on green, topic: images/media

#28864 fix(create-gatsby) the sessionId is supposed to be the same for the whole duration of the session
  packages/create-gatsby/src/tracking.ts
Labels: bot: merge on green, topic: cli

#28845 fix(gatsby-plugin-sharp): PathPrefix isn't being passed/set for GatsbyImage
  e2e-tests/path-prefix/cypress/integration/path-prefix.js
  e2e-tests/path-prefix/gatsby-config.js
  e2e-tests/path-prefix/package.json
  e2e-tests/path-prefix/src/images/citrus-fruits.jpg
  e2e-tests/path-prefix/src/pages/index.js
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: topic: images/media

#27974 perf(gatsby-plugin-mdx): Stop clobbering the same file over and over again
  packages/gatsby-plugin-mdx/gatsby/on-create-node.js
Labels: topic: MDX, topic: performance, topic: scaling builds

#28875 docs: Add caveat for avif support
  docs/docs/reference/release-notes/v2.30/index.md
Labels: bot: merge on green

#28871 fix(gatsby-plugin-sharp): Add avif to pipeline
  packages/gatsby-plugin-sharp/src/process-file.js
Labels: bot: merge on green, topic: images/media

#28836 docs: release notes for v2.30
  docs/docs/reference/release-notes/v2.30/index.md
Labels: type: documentation

#28840 docs: update gatsby develop overview for query on demand
  docs/docs/conceptual/overview-of-the-gatsby-build-process.md
Labels: topic: query on demand*, type: documentation

#28885 fix(gatsby,gatsby-admin): Pin socket.io version to 2.3.0
  packages/gatsby-admin/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#28896 chore(docs): add http to localhost
  docs/docs/how-to/plugins-and-themes/creating-a-generic-plugin.md
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
  docs/tutorial/using-multiple-themes-together.md
  examples/creating-source-plugins/README.md
  packages/gatsby-admin/README.md
  packages/gatsby-design-tokens/README.md
Labels: type: documentation

#28887 chore(gatsby): Add `flags` to GatsbyConfig interface
  packages/gatsby/index.d.ts
Labels: topic: TypeScript*

#28895 chore(docs): fix code block language to shell
  benchmarks/source-strapi/README.md
  docs/docs/how-to/styling/using-web-fonts.md
  packages/gatsby-admin/README.md
  packages/gatsby-recipes/CONTRIBUTING.md
  starters/gatsby-starter-mdx-basic/README.md
Labels: type: documentation

#28888 fix(gatsby): show stack trace for non-graphql errors
  packages/gatsby/src/bootstrap/create-graphql-runner.ts
  packages/gatsby/src/query/__tests__/__snapshots__/error-parser.ts.snap
  packages/gatsby/src/query/__tests__/error-parser.ts
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/error-parser.ts
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/query/query-runner.ts
Labels: topic: cli, topic: dev tooling, type: bug

#28841 Fix(gatsby-plugin-image): Render LayoutWrapper prior to loading of lazy-hydrate
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
Labels: topic: images/media

#28749 gatsby image conceptual guide
  docs/docs/conceptual/using-gatsby-image.md
  docs/docs/images/gatsby-image-gif.gif
Labels: type: documentation

#28755 ecommerce conceptual guide
  docs/docs/conceptual/gatsby-for-ecommerce.md
Labels: type: documentation

#28905 docs(readme): add file extension, fix code block, fix link, fix code
  packages/gatsby-plugin-utils/README.md
Labels: type: documentation

#28907 fix(gatsby-plugin-netlify): fix typo
  packages/gatsby-plugin-netlify/src/gatsby-node.js
Labels: type: maintenance

#28908 fix(gatsby-plugin-sass): fix brand name, code block around names
  packages/gatsby-plugin-sass/CHANGELOG.md
  packages/gatsby-plugin-sass/README.md
  packages/gatsby-plugin-sass/package.json
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: topic: sass

#28912 doc(node-creation): fix brand name
  docs/docs/node-creation.md
Labels: type: documentation

#28915 chore(docs): plugin contentful - fix brand name, code blocks for names
  packages/gatsby-source-contentful/README.md
Labels: type: documentation

#28906 readme(gatsby-plugin-emotion): fix table
  packages/gatsby-plugin-emotion/README.md
Labels: type: documentation

#28918 chore(docs): google plugin analytics - upgrade to gtag, fix code
  packages/gatsby-plugin-google-analytics/README.md
Labels: type: documentation

#28910 fix(gatsby): rewrite a spread that would break at scale
  packages/gatsby/src/schema/node-model.js
Labels: topic: scaling builds, type: bug

#28913 fix(gatsby-source-filesystem): fix broken stream with gzipped files
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node-integration.js
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/__tests__/fixtures/dog-thumbnail.jpg
  packages/gatsby-source-filesystem/src/__tests__/fixtures/gatsby-logo.svg
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  yarn.lock
Labels: status: needs core review, topic: filesystem

#28891 perf(gatsby): do not call and iterate getAllNodes(File) for each file
  packages/gatsby/src/schema/resolvers.ts
Labels: topic: performance

#28927 Add avif format support to gatsby remark images package
  packages/gatsby-remark-images/README.md
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/constants.js
  packages/gatsby-remark-images/src/index.js
Labels: status: triage needed

#28958 chore(default-starter): format code using prettier
  starters/default/src/components/layout.js
  starters/default/src/pages/using-typescript.tsx
Labels: topic: starters

#28936 chore(docs): realease notes - code fences, code language
  docs/docs/reference/release-notes/v2.26/index.md
  docs/docs/reference/release-notes/v2.27/index.md
  docs/docs/reference/release-notes/v2.28/index.md
  docs/docs/reference/release-notes/v2.29/index.md
  docs/docs/reference/release-notes/v2.30/index.md
Labels: type: documentation

#28933 chore(docs): Change cd path to "my-gatsby-site"
  docs/docs/quick-start.md
Labels: type: documentation

#28931 chore(docs): typography - brand name
  docs/docs/using-typography-js.md
Labels: type: documentation

#28929 chore(docs): routing - brand name, code language, code block
  docs/docs/reference/routing/file-system-route-api.md
Labels: type: documentation

#28940 chore: remove unused code (page-hot-reloader)
  packages/gatsby/src/bootstrap/page-hot-reloader.ts
  packages/gatsby/src/query/__tests__/data-tracking.js
Labels: type: maintenance

#28957 perf(develop): don't use debug config for bluebird
  packages/gatsby/src/utils/api-runner-node.js
Labels: topic: scaling builds

#28975 docs: restore the most actual docs for gatsby-plugin-sass
  docs/docs/how-to/styling/bulma.md
  docs/docs/how-to/styling/sass.md
  docs/docs/how-to/styling/tailwind-css.md
  docs/docs/recipes/styling-css.md
Labels: type: documentation

#28976 docs: update GraphQL docs for child fields
  docs/docs/reference/graphql-data-layer/schema-customization.md
  docs/docs/schema-generation.md
Labels: bot: merge on green, type: documentation

#28921 fix(gatsby-plugin-image): Conditionally require dependencies and give better warnings
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/node-apis/image-processing.ts
  packages/gatsby-plugin-image/src/node-apis/watcher.ts
Labels: topic: images/media

#28941 feat: Add support for aspectRatio
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/utils.ts
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: topic: images/media

#28978 chore(gatsby): remove unused await
  packages/gatsby/src/schema/node-model.js
Labels: bot: merge on green, type: chore

#28953 chore(telemetry): allow sharing tags in a file and read it only when things change
  packages/gatsby-telemetry/src/__tests__/telemetry.ts
  packages/gatsby-telemetry/src/telemetry.ts
Labels: bot: merge on green, topic: telemetry*

#23840 feat(gatsby-source-shopify): download images option
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/gatsby-node.js
  packages/gatsby-source-shopify/src/nodes.js
Labels: status: needs core review, topic: Shopify, type: feature or enhancement

#28986 fix(gatsby): fix stale query results on data updates
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/schema/node-model.js
Labels: bot: merge on green, topic: GraphQL, topic: data sourcing

#28923 chore(gatsby): Improve type safety of ShouldUpdateScrollArgs
  packages/gatsby/index.d.ts
Labels: topic: TypeScript*, topic: reach/router and Links

#28981 chore(docs): Add Tina in list of Headless CMS
  docs/docs/how-to/sourcing-data/headless-cms.md
Labels: type: documentation

#28926 perf(gatsby-source-contentful): prevent redundant fs/remote fetches for tracedSVG
  packages/gatsby-source-contentful/src/cache-image.js
Labels: bot: merge on green, topic: Contentful

#28985 chore: Update image API to remove maxWidth/maxHeight
  e2e-tests/gatsby-static-image/src/pages/constrained.js
  e2e-tests/gatsby-static-image/src/pages/fluid.js
  e2e-tests/visual-regression/src/pages/images/avif.js
  e2e-tests/visual-regression/src/pages/images/constrained.js
  e2e-tests/visual-regression/src/pages/images/fluid.js
  e2e-tests/visual-regression/src/pages/static-images/avif.js
  e2e-tests/visual-regression/src/pages/static-images/constrained.js
  e2e-tests/visual-regression/src/pages/static-images/fluid.js
  packages/gatsby-plugin-image/README.md
  packages/gatsby-plugin-image/src/__tests__/image-utils.ts
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-image/src/index.ts
  packages/gatsby-plugin-image/src/node-apis/image-processing.ts
  packages/gatsby-plugin-image/src/node-apis/parser.ts
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-plugin-image/src/utils.ts
  packages/gatsby-plugin-sharp/safe-sharp.d.ts
  packages/gatsby-plugin-sharp/src/__tests__/utils.js
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-plugin-sharp/src/utils.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: topic: images/media

#28868 fix(gatsby-plugin-image): do not show placeholder if image already lo…
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Labels: status: needs core review, topic: images/media

#28987 chore: change fluid to fullWidth
  e2e-tests/gatsby-static-image/cypress/integration/fullWidth.js
  e2e-tests/gatsby-static-image/cypress/integration/image.js
  e2e-tests/gatsby-static-image/src/pages/fullWidth.js
  e2e-tests/visual-regression/cypress/integration/image.js
  e2e-tests/visual-regression/src/pages/images/fullWidth.js
  e2e-tests/visual-regression/src/pages/index.js
  e2e-tests/visual-regression/src/pages/static-images/fullWidth.js
  packages/gatsby-plugin-image/README.md
  packages/gatsby-plugin-image/compat.browser.js
  packages/gatsby-plugin-image/compat.browser.modern.js
  packages/gatsby-plugin-image/compat.browser.module.js
  packages/gatsby-plugin-image/compat.js
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/__tests__/image-utils.ts
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/compat.browser.tsx
  packages/gatsby-plugin-image/src/components/compat.tsx
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-plugin-sharp/src/__tests__/utils.js
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-plugin-sharp/src/utils.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby-transformer-sharp/src/types.ts
Labels: bot: merge on green, topic: images/media

#28998 fix(gatsby-plugin-image): Remove preload tag
  packages/gatsby-plugin-image/src/components/main-image.tsx
Labels: topic: images/media

#28911 feat(gatsby): add required eslint rules even if user has custom eslint config
  packages/gatsby/src/utils/__tests__/eslint-config.ts
  packages/gatsby/src/utils/eslint-config.ts
  packages/gatsby/src/utils/eslint/required.js
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: hot reloading*

#29019 fix: broken tutorial image links
  docs/docs/tutorial/part-two/css-modules-1.png
  docs/docs/tutorial/part-two/css-modules-final.png
  docs/docs/tutorial/part-two/css-modules-userlist.png
  docs/docs/tutorial/part-two/glamor-example.png
  docs/docs/tutorial/part-two/index.md
  docs/docs/tutorial/part-two/pexels-daniel-xavier-1102341.jpg
  docs/docs/tutorial/part-two/pexels-guilherme-almeida-1858175.jpg
  docs/docs/tutorial/part-two/typography-bootstrap.png
  docs/docs/tutorial/part-two/typography-lawton.png
  docs/docs/tutorial/part-zero/index.md
Labels: type: bug, type: documentation

#29020 Revert "fix: broken tutorial image links"
  docs/docs/tutorial/part-two/css-modules-1.png
  docs/docs/tutorial/part-two/css-modules-final.png
  docs/docs/tutorial/part-two/css-modules-userlist.png
  docs/docs/tutorial/part-two/glamor-example.png
  docs/docs/tutorial/part-two/index.md
  docs/docs/tutorial/part-two/pexels-daniel-xavier-1102341.jpg
  docs/docs/tutorial/part-two/pexels-guilherme-almeida-1858175.jpg
  docs/docs/tutorial/part-two/typography-bootstrap.png
  docs/docs/tutorial/part-two/typography-lawton.png
  docs/docs/tutorial/part-zero/index.md
Labels: status: triage needed

#29021 fix: broken tutorial avatar image links (take 2)
  docs/docs/tutorial/part-two/css-modules-1.png
  docs/docs/tutorial/part-two/css-modules-final.png
  docs/docs/tutorial/part-two/css-modules-userlist.png
  docs/docs/tutorial/part-two/glamor-example.png
  docs/docs/tutorial/part-two/index.md
  docs/docs/tutorial/part-two/pexels-daniel-xavier-1102341.jpg
  docs/docs/tutorial/part-two/pexels-guilherme-almeida-1858175.jpg
  docs/docs/tutorial/part-two/typography-bootstrap.png
  docs/docs/tutorial/part-two/typography-lawton.png
Labels: status: triage needed

#29018 chore(docs): Updating Chakra UI docs
  docs/docs/how-to/styling/other-css-frameworks.md
Labels: type: documentation

#28878 feat(gatsby-graphiql-explorer): add support for magic fragments
  e2e-tests/development-runtime/cypress/integration/functionality/implicit-fragments.js
  e2e-tests/development-runtime/src/utils/fragments.js
  packages/gatsby-graphiql-explorer/README.md
  packages/gatsby-graphiql-explorer/package.json
  packages/gatsby-graphiql-explorer/src/app/app.js
  packages/gatsby-graphiql-explorer/src/app/webpack.config.js
  packages/gatsby-graphiql-explorer/src/index.js
  packages/gatsby/src/utils/start-server.ts
  yarn.lock
Labels: topic: GraphiQL*

#28649 fix(gatsbu-source-contentful): apply useNameForId when creating the g…
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: topic: Contentful

#29028 Fix/contentful add header
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/fetch.js
Labels: bot: merge on green, status: needs core review

#29002 feat(gatsby-plugin-image): Change fullWidth to use breakpoints
  e2e-tests/visual-regression/src/pages/images/fullWidth.js
  e2e-tests/visual-regression/src/pages/static-images/fullWidth.js
  packages/gatsby-plugin-image/README.md
  packages/gatsby-plugin-image/src/__tests__/image-utils.ts
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-sharp/src/__tests__/utils.js
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-plugin-sharp/src/utils.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: topic: images/media

#29029 chore(docs): adjust Contentful Rich Text example codes
  packages/gatsby-source-contentful/README.md
Labels: bot: merge on green, type: documentation

#29032 chore(gatsby-plugin-image): Unflag remote images
  packages/gatsby-plugin-image/src/node-apis/image-processing.ts
Labels: bot: merge on green, topic: images/media

#29016 feat(gatsby): Hydrate in development when the page was server rendered
  packages/gatsby/cache-dir/app.js
Labels: type: feature or enhancement

#28645 fix(sharp) wrap sharp calls in try/catch to avoid crashing on bad images
  packages/gatsby-plugin-sharp/src/duotone.js
  packages/gatsby-plugin-sharp/src/image-data.ts
Labels: topic: sharp

#28737 Edit search documentation
  docs/docs/how-to/adding-common-features/adding-search.md
Labels: type: documentation

#28545 fix(security): update vulnerable packages, include React 17 in peerDeps
  package.json
  packages/gatsby-admin/package.json
  packages/gatsby-cli/package.json
  packages/gatsby-link/package.json
  packages/gatsby-plugin-google-analytics/package.json
  packages/gatsby-plugin-lodash/package.json
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-styletron/package.json
  packages/gatsby-plugin-subfont/package.json
  packages/gatsby-plugin-typography/package.json
  packages/gatsby-react-router-scroll/package.json
  packages/gatsby-recipes/package.json
  packages/gatsby-remark-copy-linked-files/package.json
  packages/gatsby-remark-images-contentful/package.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-hacker-news/package.json
  packages/gatsby-source-lever/package.json
  packages/gatsby-source-medium/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-transformer-documentationjs/package.json
  packages/gatsby-transformer-screenshot/package.json
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby-transformer-sqip/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#29034 fix(gatsby-source-contentful): Improve base64 placeholders
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: status: needs core review, topic: Contentful

#29043 fix(gatsby-plugin-image): Handle imgStyle in SSR
  packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
Labels: topic: images/media

#28689 feat(gatsby): Add eslint rules to warn against bad patterns in pageTemplates (for Fast Refresh)
  e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
  e2e-tests/development-runtime/cypress/integration/eslint-rules/no-anonymous-exports-page-templates.js
  e2e-tests/development-runtime/src/pages/eslint-rules/limited-exports-page-templates.js
  e2e-tests/development-runtime/src/pages/eslint-rules/no-anonymous-exports-page-templates-function.js
  e2e-tests/development-runtime/src/pages/eslint-rules/no-anonymous-exports-page-templates.js
  packages/gatsby/src/utils/__tests__/eslint-config.ts
  packages/gatsby/src/utils/eslint-config.ts
  packages/gatsby/src/utils/eslint-rules-helpers.ts
  packages/gatsby/src/utils/eslint-rules/__tests__/limited-exports-page-templates.ts
  packages/gatsby/src/utils/eslint-rules/__tests__/no-anonymous-exports-page-templates.ts
  packages/gatsby/src/utils/eslint-rules/limited-exports-page-templates.ts
  packages/gatsby/src/utils/eslint-rules/no-anonymous-exports-page-templates.ts
  packages/gatsby/src/utils/eslint/required.js
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: hot reloading*

#28930 fix(gatsby): Use fast-refresh for React 17
  packages/gatsby/src/utils/get-react-hot-loader-strategy.ts
Labels: topic: hot reloading*

#29015 fix(gatsby): fix broken GraphQL resolver tracing
  packages/gatsby/src/schema/resolvers.ts
Labels: bot: merge on green, topic: GraphQL

#28995 fix(gatsby-source-filesystem): fix broken stream with gzipped files (#28913)
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node-integration.js
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/__tests__/fixtures/dog-thumbnail.jpg
  packages/gatsby-source-filesystem/src/__tests__/fixtures/gatsby-logo.svg
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  yarn.lock
Labels: bot: merge on green, type: cherry

#29009 benchmark(gabe-fs-markdown-images): add img benchmark
  benchmarks/gabe-fs-markdown-images/.gitignore
  benchmarks/gabe-fs-markdown-images/LICENSE
  benchmarks/gabe-fs-markdown-images/README.md
  benchmarks/gabe-fs-markdown-images/gatsby-config.js
  benchmarks/gabe-fs-markdown-images/gatsby-node.js
  benchmarks/gabe-fs-markdown-images/gen.js
  benchmarks/gabe-fs-markdown-images/package.json
  benchmarks/gabe-fs-markdown-images/src/components/bio.js
  benchmarks/gabe-fs-markdown-images/src/components/layout.js
  benchmarks/gabe-fs-markdown-images/src/pages/404.js
  benchmarks/gabe-fs-markdown-images/src/pages/index.js
  benchmarks/gabe-fs-markdown-images/src/templates/blog-post.js
  benchmarks/gabe-fs-markdown-images/static/favicon.ico
  benchmarks/gabe-fs-markdown-images/static/robots.txt
Labels: topic: benchmarks

#29064 fix(gatsby-plugin-image): Fix onload race condition
  packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Labels: bot: merge on green, topic: images/media

#29010 fix(gatsby-plugin-mdx): Add `root` to plugin validation
  packages/gatsby-plugin-mdx/__tests__/gatsby-node.js
  packages/gatsby-plugin-mdx/gatsby-node.js
  packages/gatsby-plugin-mdx/utils/default-options.js
Labels: topic: MDX

#29066 fix(gatsby-plugin-typescript): add missing options validations
  packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-typescript/src/gatsby-node.js
Labels: topic: TypeScript

#29046 feat(gatsby-codemods): Handle or warn on nested options changes
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/fluid.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/transform-options.input.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/transform-options.output.js
  packages/gatsby-codemods/src/transforms/__tests__/gatsby-plugin-image-test.js
  packages/gatsby-codemods/src/transforms/gatsby-plugin-image.js
Labels: topic: images/media

#29075 feat(gatsby): bump opt-in % to dev-ssr to 20%
  packages/gatsby/src/utils/flags.ts
Labels: bot: merge on green

#29077 fix(gatsby): Always render the body component to ensure needed head & pre/post body components are added
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
Labels: bot: merge on green

#29078 chore: update yarn.lock
  yarn.lock
Labels: type: maintenance

#29079 chore(docs): Fix grammar in add-404-page
  docs/docs/how-to/adding-common-features/add-404-page.md
Labels: type: documentation

#29073 Add image notes
  docs/docs/reference/release-notes/v2.31/index.md
Labels: type: documentation

#29089 Update 2.31 release notes
  docs/docs/reference/release-notes/v2.31/index.md
Labels: bot: merge on green

#29068 docs: Release notes for 2.31
  docs/docs/reference/release-notes/v2.31/index.md
Labels: bot: merge on green, type: documentation

#28935 docs: Initial gatsby-plugin-image reference guide
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
  docs/docs/reference/built-in-components/layouts.mp4
Labels: topic: images/media, type: documentation

#28917 docs: Add gatsby-plugin-image How-To guide
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: topic: images/media, type: documentation

#29091 docs: fix broken link in 2.31 release notes
  docs/docs/reference/release-notes/v2.31/index.md
Labels: bot: merge on green, type: documentation

#29072 feat(gatsby-plugin-image): object-fit polyfill for IE
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
  yarn.lock
Labels: bot: merge on green, topic: images/media

#29094 fix: swap StaticImage restrictions explanation and callout
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
Labels: topic: images/media, type: documentation

#29092 fix(gatsby-plugin-image): pass down missing sizes attribute to <sources> (fixes #29093)
  packages/gatsby-plugin-image/src/components/picture.tsx
Labels: status: triage needed

#29088 tests: Add image visual comparison and srcset snapshot tests
  .circleci/config.yml
  .gitignore
  integration-tests/images/LICENSE
  integration-tests/images/README.md
  integration-tests/images/__tests__/__snapshots__/images.ts.snap
  integration-tests/images/__tests__/images.ts
  integration-tests/images/gatsby-config.js
  integration-tests/images/package.json
  integration-tests/images/src/images/sighisoara.jpg
  integration-tests/images/src/pages/index.js
  integration-tests/jest.config.js
Labels: bot: merge on green, topic: images/media

#29102 Revert "fix(gatsby-source-contentful): Add header"
  packages/gatsby-source-contentful/package.json
  yarn.lock
Labels: bot: merge on green, topic: Contentful

#28072 Update creating-a-local-plugin.md
  docs/docs/creating-a-local-plugin.md
Labels: bot: merge on green, type: documentation

#29087 chore(telemetry): Add total pages count to the schema
  packages/gatsby-telemetry/src/telemetry.ts
Labels: bot: merge on green, status: triage needed, topic: telemetry*

#29109 fix(eslint-config): don't use .eslintrc and set parser settings
  packages/gatsby/src/utils/eslint-config.ts
Labels: topic: webpack/babel

#28904 Update plugin option schema validation code sample
  docs/docs/how-to/plugins-and-themes/configuring-usage-with-plugin-options.md
Labels: bot: merge on green, type: documentation

#29125 fix(gatsby): Add missing prev location TS property for RouteUpdateArgs
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#29144 fix(babel-plugin-remove-graphql-queries): make sure imports are posix
  packages/babel-plugin-remove-graphql-queries/package.json
  packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
  packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js
  packages/babel-plugin-remove-graphql-queries/src/index.ts
Labels: bot: merge on green, status: needs core review, type: maintenance

#29117 docs: fix a small typo
  docs/docs/how-to/testing/testing-react-components.md
Labels: type: documentation

#29141 feat(gatsby-plugin-image): Add support for backgroundColor in sharp
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: bot: merge on green, topic: images/media

#29147 feat(gatsby-plugin-sharp): Add image plugin defaults
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/__tests__/plugin-options.ts
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-plugin-sharp/src/plugin-options.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
  yarn.lock
Labels: bot: merge on green, topic: images/media

#29095 fix(gatsby-plugin-styled-components): add `namespace` option
  packages/gatsby-plugin-styled-components/src/gatsby-node.js
Labels: topic: styled-components

#29162 chore(docs): Netlify CMS added branch to backend settings
  docs/docs/how-to/sourcing-data/sourcing-from-netlify-cms.md
Labels: type: documentation

#29163 docs: fix broken link
  docs/docs/conditional-page-builds.md
Labels: type: documentation

#29067 chore(docs): Update debugging-the-build-process
  docs/docs/debugging-the-build-process.md
Labels: type: documentation

#29137 chore(docs): Add cassandra to list of database sources
  docs/docs/how-to/sourcing-data/sourcing-from-databases.md
Labels: type: documentation

#29185 fix(gatsby-plugin-image): Add missing files
  packages/gatsby-plugin-image/graphql-utils.d.ts
  packages/gatsby-plugin-image/graphql-utils.js
  packages/gatsby-plugin-image/package.json
Labels: bot: merge on green, topic: images/media

#29187 fix(gatsby-plugin-image): Handle breakpoints and auto-format in plugin utils
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/image-utils.ts
Labels: topic: images/media

#29148 fix(gatsby-plugin-image): Use inline-block in class so users can override
  e2e-tests/gatsby-static-image/cypress/integration/image.js
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/gatsby-ssr.tsx
Labels: bot: merge on green, topic: images/media

#28999 fix(gatsby-plugin-sharp): ignore incorrect duotone options
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-plugin-sharp/src/index.js
Labels: bot: merge on green, topic: images/media

#29036 docs(gatsby-plugin-image): Initial migration guide
  docs/docs/reference/release-notes/image-migration-guide.md
Labels: bot: merge on green, type: documentation

#29193 fix(gatsby-plugin-manifest): Add `webapp` key
  packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Labels: topic: PWA

#29192 fix(gatsby-plugin-image): Pass sizes for source
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/picture.tsx
  yarn.lock
Labels: topic: images/media

#29204 fix(gatsby-plugin-image): Fixes to plugin utils types
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/image-utils.ts
Labels: topic: images/media

#29076 docs(gatsby-plugin-image): Update readme
  packages/gatsby-plugin-image/README.md
Labels: bot: merge on green, topic: images/media, type: documentation

#29149 feat(gatsby): distinguish total number of pages from number of written html files
  packages/gatsby-telemetry/src/telemetry.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/develop-process.ts
Labels: topic: telemetry*

#29212 fix(gatsby-source-contentful): sync crash with error response
  packages/gatsby-source-contentful/src/fetch.js
Labels: bot: merge on green, topic: Contentful

#28533 chore: update e2e tests to use node-fetch & fix windows
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/scripts/cms-webhook.js
  e2e-tests/development-runtime/scripts/webhook.js
Labels: bot: merge on green, topic: internal, type: maintenance

#29198 choosing a CMS
  docs/docs/conceptual/choosing-a-cms.md
  docs/docs/images/use-case-landing-page-screenshot.jpg
Labels: status: triage needed

#29225 chore: Dirty yarn.lock
  yarn.lock
Labels: type: maintenance

#29226 fix(gatsby-plugin-image): Update types
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/image-utils.ts
Labels: topic: images/media

#29227 chore(docs): Update TypeScript Unit Testing Docs
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#29219 fix(gatsby): queue fs writes so event loop not overwhelmed on large sites
  packages/gatsby/package.json
  packages/gatsby/src/utils/page-data.ts
  yarn.lock
Labels: topic: scaling builds

#29228 fix(gatsby-source-contentful): validation with environment
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: topic: Contentful

#29242 fix(gatsby-plugin-manifest): Fix `or` Joi assertion
  packages/gatsby-plugin-manifest/src/pluginOptionsSchema.js
Labels: bot: merge on green, topic: PWA

#29244 fix(gatsby): Upgrade v8-compile-cache
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green, type: maintenance

#29235 fix(gatsby-plugin-image): Use ESM for gatsby-browser
  packages/gatsby-plugin-image/gatsby-browser.js
Labels: topic: images/media

#29240 feat(gatsby): cache/memoize hot functions in runAPI
  packages/gatsby/package.json
  packages/gatsby/src/utils/api-runner-node.js
  yarn.lock
Labels: topic: scaling builds

#29231 feat(gatsby-plugin-image): Add useArtDirection hook
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/index.browser.ts
  packages/gatsby-plugin-image/src/index.ts
Labels: topic: images/media

#28236 feat(gatsby-source-contentful): Add gatsbyImageData resolver
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/utils.js
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: bot: merge on green, status: needs core review, topic: Contentful, topic: images/media

#29246 fix(gatsby-plugin-sharp): Sanitize tmp filename
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/trace-svg.js
  yarn.lock
Labels: topic: images/media

#29262 chore(docs): Fix typo in contributing style guide
  docs/contributing/gatsby-style-guide.md
Labels: type: documentation

#29265 fix(gatsby-source-contentful): validation with environment (#29228)
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: type: cherry

#29254 make sure to pass the failOnError option to base64 generation
  packages/gatsby-plugin-sharp/src/index.js
Labels: topic: sharp
