Repository gatsbyjs/gatsby, pull requests merged in 2021-07, with the labels that each got.

#32175 chore(netlify-cms): Bump webpack version to match gatsby
  packages/gatsby-plugin-netlify-cms/package.json
  yarn.lock
Labels: topic: plugins

#31178 chore(gatsby): Bumped express-graphql to v0.12.0
  packages/gatsby-recipes/package.json
  packages/gatsby/package.json
  packages/gatsby/src/utils/start-server.ts
  yarn.lock
Labels: type: maintenance

#32183 chore: Install python in various CircleCI job to get them running
  .circleci/config.yml
Labels: type: maintenance

#32189 fix(gatsby): update async requires in dev loader
  e2e-tests/development-runtime/cypress/integration/hot-reloading/new-file.js
  e2e-tests/development-runtime/src/pages/index.js
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/dev-loader.js
Labels: bot: merge on green

#32172 refactor(gatsby): use GatsbyIterable + extract common tools for querying
  packages/gatsby/src/datastore/__tests__/run-fast-filters.js
  packages/gatsby/src/datastore/common/__tests__/iterable.ts
  packages/gatsby/src/datastore/common/iterable.ts
  packages/gatsby/src/datastore/common/query.ts
  packages/gatsby/src/datastore/in-memory/in-memory-datastore.ts
  packages/gatsby/src/datastore/in-memory/indexing.ts
  packages/gatsby/src/datastore/in-memory/run-fast-filters.ts
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
  packages/gatsby/src/datastore/types.ts
  packages/gatsby/src/schema/__tests__/run-query.js
  packages/gatsby/src/schema/node-model.js
  packages/gatsby/src/schema/resolvers.ts
Labels: bot: merge on green

#32180 fix(gatsby-source-drupal): Fix Drupal webhook delete issues
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: topic: source-drupal

#32195 fix(gatsby): add fallback for resolveType
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/schema.js
Labels: bot: merge on green, topic: GraphQL

#32159 feat(gatsby-worker): add messaging api
  .eslintignore
  .prettierignore
  packages/gatsby-worker/README.md
  packages/gatsby-worker/src/__tests__/fixtures/test-child.ts
  packages/gatsby-worker/src/__tests__/integration.ts
  packages/gatsby-worker/src/child.ts
  packages/gatsby-worker/src/index.ts
  packages/gatsby-worker/src/types.ts
Labels: topic: core

#32201 chore: renovate - don't include monorepo packages in preMinors
  .circleci/config.yml
  renovate.json5
  scripts/renovate-config-generator.js
Labels: type: maintenance

#32204 chore: enforce publish access check before publishing
  package.json
Labels: topic: automation

#32191 Wrong post ids in example author name filter
  docs/docs/query-filters.md
Labels: status: triage needed

#32182 feat(gatsby): enable replaceRenderer to be async
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
  integration-tests/ssr/__tests__/ssr.js
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/api-runner-ssr.js
  packages/gatsby/cache-dir/develop-static-entry.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: topic: core

#32188 feat(gatsby): enable async rendering with react 18
  packages/gatsby/cache-dir/server-utils/writable-as-promise.js
  packages/gatsby/cache-dir/static-entry.js
Labels: bot: merge on green, topic: frontend

#32209 Update SECURITY.md
  SECURITY.md
Labels: bot: merge on green

#32208 chore(gatsby): Update PostCSS to 8.3.5 and unfix the version
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green, topic: plugins-styling

#32199 docs(tutorial): copy edits for parts 1, 2, 4
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-4/index.mdx
Labels: type: documentation

#32212 feat(docs): edit file system route API docs page
  docs/docs/reference/routing/file-system-route-api.md
Labels: status: triage needed

#32223 chore: ignore gatsby-interface to test renovate
  renovate.json5
  scripts/renovate-config-generator.js
Labels: type: maintenance

#31653 chore(docs): Update Storybook guide to v6
  docs/docs/how-to/testing/visual-testing-with-storybook.md
Labels: type: documentation

#32181 feat(gatsby): swap createRoot to new hydrateRoot
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/production-app.js
Labels: bot: merge on green, topic: core

#32224 chore: disable babel packages upgrades per package
  renovate.json5
  scripts/renovate-config-generator.js
Labels: type: maintenance

#32234 fix: don't import from other package src (even just types)
  packages/gatsby/package.json
  packages/gatsby/scripts/check-declaration.js
  packages/gatsby/src/utils/node-manifest.ts
Labels: bot: merge on green

#32253 fix(gatsby-source-shopify): add tags to schema
  packages/gatsby-source-shopify/src/create-schema-customization.ts
Labels: status: triage needed

#32251 fix(gatsby-source-wordpress): Move the remote url !== options url check earlier in previews
  packages/gatsby-source-wordpress/src/steps/preview/index.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/index.ts
Labels: topic: source-wordpress

#32259 fix: added missing parentheses in creating a source plugin tutorial
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: status: triage needed

#32260 fix(gatsby-telemetry): reduce save to config
  packages/gatsby-telemetry/src/telemetry.ts
Labels: bot: merge on green, topic: core

#32162 feat(gatsby): forward jobs to main process from workers
  packages/gatsby/src/bootstrap/__tests__/remove-stale-jobs.ts
  packages/gatsby/src/bootstrap/remove-stale-jobs.ts
  packages/gatsby/src/redux/__tests__/jobsv2.js
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/jobs/__tests__/fixtures/input1.jpg
  packages/gatsby/src/utils/jobs/__tests__/fixtures/input2.jpg
  packages/gatsby/src/utils/jobs/__tests__/manager.js
  packages/gatsby/src/utils/jobs/manager.ts
  packages/gatsby/src/utils/jobs/types.ts
  packages/gatsby/src/utils/jobs/worker-messaging.ts
  packages/gatsby/src/utils/wait-until-jobs-complete.ts
  packages/gatsby/src/utils/worker/__tests__/fixtures/sample-site/plugins/gatsby-plugin-test/gatsby-node.js
  packages/gatsby/src/utils/worker/__tests__/fixtures/sample-site/plugins/gatsby-plugin-test/gatsby-worker.js
  packages/gatsby/src/utils/worker/__tests__/jobs.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/create-test-worker.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/messaging.ts
  packages/gatsby/src/utils/worker/pool.ts
  packages/gatsby/src/utils/worker/types.ts
Labels: topic: core

#32213 feat(docs): rewrite adding forms documentation
  docs/docs/how-to/adding-common-features/adding-forms.md
  docs/docs/how-to/adding-common-features/creating-a-form-in-react.md
Labels: type: documentation

#32270 feat(docs): add additional resource links
  docs/docs/how-to/adding-common-features/seo.md
  docs/docs/how-to/performance/improving-build-performance.md
Labels: status: triage needed

#32282 chore: allow thunks to be dispatched
  packages/gatsby/src/redux/index.ts
Labels: bot: merge on green, topic: TypeScript

#31036 fix(gatsby-plugin-gtag): replace google analytics domain with google tag manager
  packages/gatsby-plugin-google-gtag/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-google-gtag/src/gatsby-ssr.js
Labels: bot: merge on green, topic: plugins-analytics

#32187 feat(gatsby): Add PQR to bootstrap
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/worker/child/schema.ts
  packages/gatsby/src/utils/worker/pool.ts
Labels: topic: core

#32281 feat(gatsby): PQR worker saves queries state to disk
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/persist.ts
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/__tests__/schema.ts
  packages/gatsby/src/utils/worker/__tests__/share-state.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/child/queries.ts
  packages/gatsby/src/utils/worker/child/schema.ts
  packages/gatsby/src/utils/worker/child/state.ts
Labels: topic: core

#32304 fix(gatsby): Delete `.cache/worker` before each run
  packages/gatsby/src/services/initialize.ts
Labels: bot: merge on green, topic: core

#32289 feat(pqr): handle structured logs
  packages/gatsby-cli/src/reporter/redux/actions.ts
  packages/gatsby-cli/src/reporter/reporter-phantom.ts
  packages/gatsby-cli/src/reporter/reporter-progress.ts
  packages/gatsby-cli/src/reporter/reporter-timer.ts
  packages/gatsby-cli/src/reporter/reporter.ts
  packages/gatsby-cli/src/reporter/types.ts
  packages/gatsby/src/utils/worker/__tests__/reporter.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/create-test-worker.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/messaging.ts
  packages/gatsby/src/utils/worker/pool.ts
  packages/gatsby/src/utils/worker/reporter.ts
Labels: topic: core

#32261 feat(gatsby): experimental secondary indexes in lmdb
  .circleci/config.yml
  packages/gatsby/package.json
  packages/gatsby/src/datastore/common/query.ts
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
  packages/gatsby/src/datastore/lmdb/query/README.md
  packages/gatsby/src/datastore/lmdb/query/__tests__/filter-using-index.ts
  packages/gatsby/src/datastore/lmdb/query/__tests__/suggest-index.ts
  packages/gatsby/src/datastore/lmdb/query/common.ts
  packages/gatsby/src/datastore/lmdb/query/create-index.ts
  packages/gatsby/src/datastore/lmdb/query/filter-using-index.ts
  packages/gatsby/src/datastore/lmdb/query/run-query.ts
  packages/gatsby/src/datastore/lmdb/query/suggest-index.ts
  packages/gatsby/src/datastore/types.ts
  packages/gatsby/src/schema/__tests__/connection-filter-on-linked-nodes.js
  packages/gatsby/src/schema/__tests__/kitchen-sink.js
  packages/gatsby/src/schema/__tests__/run-query.js
  packages/gatsby/src/schema/extensions/__tests__/interfaces.js
  yarn.lock
Labels: bot: merge on green, topic: core

#32307 fix(gatsby): delay 'unstable_onPluginInit' lifecycle to after cache is initialized
  packages/gatsby/src/bootstrap/load-plugins/index.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts
Labels: bot: merge on green, topic: core

#32303 fix(gatsby-source-wordpress): don't leak auth details
  integration-tests/gatsby-source-wordpress/.env.test
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/__tests__/index.js
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/env-browser.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/authed-wpgql-request.js
  packages/gatsby-source-wordpress/src/steps/process-and-validate-plugin-options.ts
Labels: topic: source-wordpress

#32315 fix(gatsby-source-wordpress): Backporting auth leak fix
  packages/gatsby-source-wordpress/src/steps/process-and-validate-plugin-options.ts
Labels: type: cherry

#32306 chore(docs): Mention Functions in v3 migration guide
  docs/docs/reference/functions/getting-started.md
  docs/docs/reference/gatsby-project-structure.md
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: type: documentation

#32323 fix(gatsby): Pass search/hash to location after swUpdated
  packages/gatsby/cache-dir/navigation.js
Labels: topic: core, topic: plugins-PWA

#32311 Avoid UNHANDLED REJECTION error on ctrl-C
  packages/gatsby/src/commands/develop.ts
Labels: bot: merge on green, type: bug

#32328 Docs | Update Community.md and contributing/translation (#31883)
  docs/contributing/community.md
  docs/contributing/translation/index.md
  docs/contributing/translation/maintainers.md
  docs/contributing/translation/new-translations.md
  docs/contributing/translation/style-guide.md
  docs/contributing/translation/sync-guide.md
  docs/contributing/translation/translators.md
Labels: bot: merge on green, type: documentation

#32301 feat(gatsby): add page data for failed page to logs
  packages/gatsby/src/commands/build-html.ts
Labels: topic: core

#32337 fix(gatsby-plugin-gatsby-cloud): lower peak memory usage by stream writing the _header.json file
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
Labels: bot: merge on green, topic: build, topic: performance

#32334 feat(gatsby): Redirect passes search & hash parameter to final URL
  e2e-tests/development-runtime/cypress/integration/navigation/redirect.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/pages/index.js
  e2e-tests/development-runtime/src/pages/redirect-search-hash.js
  packages/gatsby/cache-dir/navigation.js
Labels: topic: core

#32339 fix(gatsby-source-wordprepss): delete auth details earlier v2
  packages/gatsby-source-wordpress/src/gatsby-node.ts
Labels: topic: source-wordpress

#32338 fix(gatsby-source-wordpress): run setGatsbyApiToState in onPreInit to delete auth options
  packages/gatsby-source-wordpress/src/gatsby-node.ts
Labels: topic: source-wordpress

#32192 feat(gatsby): Track persistence time of save-state
  packages/gatsby/src/redux/save-state.js
Labels: topic: core

#32347 chore(gatsby): Add PQR feature flag
  packages/gatsby/src/utils/flags.ts
Labels: bot: merge on green, topic: core

#32352 fix(gatsby): freeze the schema in workers
  packages/gatsby/src/schema/index.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/utils/worker/child/schema.ts
Labels: topic: core

#32355 fix(gatsby): Use shared gql runner in PQR workers
  benchmarks/query-filters-sort/gatsby-config.js
  benchmarks/query-filters-sort/package.json
  packages/gatsby/src/utils/worker/child/queries.ts
Labels: topic: core

#32344 docs(tutorial): add Part 5
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/blog-page-with-frontmatter.png
  docs/docs/tutorial/part-5/blog-page-with-full-posts.png
  docs/docs/tutorial/part-5/data-layer-with-nodes.png
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-five/allfile-query.png
  docs/docs/tutorial/part-five/data-in-console.png
  docs/docs/tutorial/part-five/filesystem-autocomplete.png
  docs/docs/tutorial/part-five/filesystem-explorer-options.png
  docs/docs/tutorial/part-five/filesystem-query.png
  docs/docs/tutorial/part-five/graphiql-filesystem.png
  docs/docs/tutorial/part-five/index.md
  docs/docs/tutorial/part-five/my-files-page.png
  docs/docs/tutorial/part-four/index.md
  docs/docs/tutorial/part-four/pandas-eating-lots-titles.png
  docs/docs/tutorial/part-four/site-metadata-title.png
  docs/docs/tutorial/part-four/site-metadata-two-titles.png
  docs/docs/tutorial/part-four/start.png
Labels: type: documentation

#32357 chore(docs): Update building-a-theme to latest Theme UI
  docs/tutorial/building-a-theme.md
Labels: type: documentation

#32361 fix(gatsby): Hide page/static queries activities for PQR
  packages/gatsby/src/services/run-page-queries.ts
  packages/gatsby/src/services/run-static-queries.ts
Labels: topic: core

#32365 feat(gatsby): restart worker pool after query running in workers
  packages/gatsby-worker/src/__tests__/fixtures/test-child.ts
  packages/gatsby-worker/src/__tests__/integration.ts
  packages/gatsby-worker/src/index.ts
  packages/gatsby-worker/src/utils.ts
  packages/gatsby/src/commands/build.ts
Labels: topic: core

#32366 fix(gatsby): shut down worker pool after html generation
  packages/gatsby/src/commands/build.ts
Labels: topic: core

#32369 fix(gatsby-source-wordpress): WPGraphQL pageInfo is nullable, make sure we're not accessing hasNextPage on null
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js
Labels: bot: merge on green, topic: source-wordpress

#32368 chore(docs): Correct JavaScript spelling
  docs/docs/ab-testing.md
Labels: type: documentation

#32333 feat(contentful): add support image corner radius
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/extend-node-type.js.snap
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: status: needs core review, topic: source-contentful, type: feature or enhancement

#31746 feat(contentful): add support for tags
  e2e-tests/contentful/cypress/integration/tags.js
  e2e-tests/contentful/gatsby-config.js
  e2e-tests/contentful/src/pages/index.js
  e2e-tests/contentful/src/pages/tags.js
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__fixtures__/restricted-content-type.js
  packages/gatsby-source-contentful/src/__fixtures__/rich-text-data.js
  packages/gatsby-source-contentful/src/__fixtures__/starter-blog-data.js
  packages/gatsby-source-contentful/src/__tests__/fetch.js
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/fetch.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/plugin-options.js
  packages/gatsby-source-contentful/src/report.js
  yarn.lock
Labels: status: needs core review, topic: source-contentful, type: feature or enhancement

#32373 feat(gatsby): Add cache-lmdb implementation
  packages/gatsby/src/utils/__tests__/cache-lmdb.ts
  packages/gatsby/src/utils/cache-lmdb.ts
  packages/gatsby/src/utils/get-cache.ts
Labels: topic: core

#31652 fix(wordpress): ensure all file links are rewritten
  packages/gatsby-source-wordpress/__tests__/fetch-referenced-media-items.test.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
Labels: bot: merge on green, topic: source-wordpress

#32264 feat(gatsby): Add webpack fs caching for development flag
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: DX

#32319 fix(gatsby): correct hasNextPage pagination info when resultOffset is provided
  packages/gatsby/src/schema/__tests__/pagination.js
  packages/gatsby/src/schema/resolvers.ts
Labels: bot: merge on green, topic: GraphQL

#32378 fix(gatsby,gatsby-plugin-image): fix createRoot on React 18
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
  packages/gatsby/cache-dir/app.js
Labels: topic: core, type: maintenance

#32398 Revert "fix(wordpress): ensure all file links are rewritten"
  packages/gatsby-source-wordpress/__tests__/fetch-referenced-media-items.test.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
Labels: status: triage needed

#32381 fix(gatsby-source-wordpress): fetch referenced media items during single node updates
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/__tests__/index.js
  integration-tests/gatsby-source-wordpress/docker/wordpress/Dockerfile
  integration-tests/gatsby-source-wordpress/docker/wordpress/plugins/wp-gatsby-test-plugin/wp-gatsby-test-plugin.php
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/increment-remote-data.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/queries.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-nodes.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
Labels: topic: source-wordpress

#32417 fix(gatsby): handle errors thrown when importing html renderer
  packages/gatsby/src/commands/build-html.ts
Labels: bot: merge on green, topic: core

#32391 fix(gatsby): Add `directory` to GatsbyCacheLmdb
  packages/gatsby/src/utils/__tests__/cache-lmdb.ts
  packages/gatsby/src/utils/cache-lmdb.ts
  packages/gatsby/src/utils/get-cache.ts
Labels: topic: core

#32390 chore(docs): modified file-mock path for typescript config on unit-te…
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#32394 feat(gatsby): display message about unfit flags found in config
  packages/gatsby/src/bootstrap/load-config-and-plugins.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap
  packages/gatsby/src/utils/__tests__/handle-flags.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/handle-flags.ts
Labels: topic: core

#32305 feat(gatsby): PQR: merge data dependencies from workers to the main process
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/child/queries.ts
  packages/gatsby/src/utils/worker/pool.ts
Labels: topic: core

#32433 chore(docs): SEO remove typos & outdated information
  docs/docs/how-to/adding-common-features/seo.md
Labels: type: documentation

#32434 docs(tutorial): add livestream links to parts 2-5, update start time for part 1
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/index.mdx
Labels: type: documentation

#32388 chore(docs): 3.10 Release Notes
  docs/docs/reference/release-notes/v3.10/index.md
Labels: type: documentation

#32457 fix(gatsby-plugin-image): Switch react-dom import to remove createRoot warning
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Labels: topic: media

#32459 fix: expose ".del" function on lmdb cache
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/utils/api-node-helpers-docs.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/cache-lmdb.ts
  packages/gatsby/src/utils/cache.ts
Labels: topic: core

#32450 34701/productvariants query is missing inventoryitem
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/create-schema-customization.ts
  packages/gatsby-source-shopify/src/gatsby-node.ts
  packages/gatsby-source-shopify/src/operations.ts
  packages/gatsby-source-shopify/src/processors/product-variants.ts
  packages/gatsby-source-shopify/src/query-builders/locations-query.ts
  packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
Labels: topic: source-shopify

#32466 fix(gatsby): Add encoding option to GatsbyCacheLmdb
  packages/gatsby/src/utils/cache-lmdb.ts
Labels: topic: core

#32431 feat: store partial page-data results in lmdb
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/utils/__tests__/get-page-data.ts
  packages/gatsby/src/utils/__tests__/page-data.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/worker/__tests__/queries.ts
Labels: topic: core

#32486 chore(gatsby-admin): add allowlist of files
  packages/gatsby-admin/package.json
Labels: bot: merge on green, type: maintenance

#32470 chore(validate-starters): Remove `npm audit` step
  scripts/validate-starters.sh
Labels: bot: merge on green, type: maintenance

#32487 fix(gatsby): Configurable PQR chunksize by env var
  packages/gatsby/src/utils/worker/pool.ts
Labels: topic: core

#32491 chore(docs): Fix a minor typo "with" > "will"
  docs/docs/reference/markdown-syntax.md
Labels: type: documentation

#32462 fix(gatsby-plugin-mdx): generate mdx once when multiple mdx fields requested
  packages/gatsby-plugin-mdx/gatsby/create-schema-customization.js
Labels: topic: performance, topic: remark/mdx

#32440 fix(gatsby): merge data deps state instead of replaying actions
  packages/gatsby-worker/src/index.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/reducers/__tests__/queries.ts
  packages/gatsby/src/redux/reducers/queries.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/child/queries.ts
  packages/gatsby/src/utils/worker/pool.ts
Labels: bot: merge on green, topic: core

#32496 fix(gatsby): correct pagination logic
  packages/gatsby/src/schema/__tests__/pagination.js
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/resolvers.ts
Labels: bot: merge on green, topic: GraphQL

#32499 chore(docs): Fix typo in assetPrefix doc
  docs/docs/how-to/previews-deploys-hosting/asset-prefix.md
Labels: type: documentation

#32519 chore(docs): Put _that image_ through https://imageoptim.com/
  docs/docs/tutorial/part-5/blog-page-with-frontmatter.png
Labels: status: triage needed

#32517 chore(docs): Fix typo in File System Route API doc
  docs/docs/reference/routing/file-system-route-api.md
Labels: type: documentation

#32520 fix(gatsby): PQR - Wait for Jobs to be Completed before restarting
  packages/gatsby/src/commands/build.ts
Labels: topic: core

#32527 docs(tutorial): add part 6
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-6/404-page-with-routes.png
  docs/docs/tutorial/part-6/blog-page-with-links.png
  docs/docs/tutorial/part-6/file-system-routes-with-blog-subdirectory.png
  docs/docs/tutorial/part-6/file-system-routes.png
  docs/docs/tutorial/part-6/graphiql-with-query-variables.png
  docs/docs/tutorial/part-6/index.mdx
  docs/docs/tutorial/part-6/my-first-post.png
  docs/docs/tutorial/part-6/post-page-template-hardcoded.png
  docs/docs/tutorial/part-six/frontpage.png
  docs/docs/tutorial/part-six/index.md
  docs/docs/tutorial/part-six/markdown-autocomplete.png
  docs/docs/tutorial/part-six/markdown-query.png
  docs/docs/tutorial/part-six/two-posts.png
Labels: type: documentation

#32535 fix(gatsby-plugin-gatsby-cloud): Use fs instead of require to get webpack stats because require is cached
  packages/gatsby-plugin-gatsby-cloud/src/plugin-data.js
Labels: status: triage needed

#32406 fix(gatsby): correct results for multiple range filters with indexes
  packages/gatsby/src/datastore/lmdb/query/__tests__/filter-using-index.ts
  packages/gatsby/src/datastore/lmdb/query/__tests__/suggest-index.ts
  packages/gatsby/src/datastore/lmdb/query/create-index.ts
  packages/gatsby/src/datastore/lmdb/query/filter-using-index.ts
  packages/gatsby/src/datastore/lmdb/query/run-query.ts
  packages/gatsby/src/datastore/lmdb/query/suggest-index.ts
  packages/gatsby/src/schema/__tests__/run-query.js
Labels: topic: core

#32539 docs(tutorial): improve a11y of layout component
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-4/index.mdx
Labels: type: documentation

#32543 Docs: fix GraphQL Reference
  docs/docs/graphql-reference.md
Labels: status: triage needed
