Repository gatsbyjs/gatsby, pull requests merged in 2021-11, with the labels that each got.

#33720 chore(docs): Upgrade guides about file linking
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
  docs/docs/reference/release-notes/migrating-from-v3-to-v4.md
  docs/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4.md
Labels: type: documentation

#33737 chore(docs): Improve "Adding a service worker"
  docs/docs/add-a-service-worker.md
Labels: type: documentation

#33799 chore(docs): Update mapping node types after v4 breaking changes
  docs/docs/reference/config-files/gatsby-config.md
Labels: type: documentation

#33805 chore(gatsby): Fix index.d.ts file
  packages/gatsby/index.d.ts
  scripts/check-ts.js
Labels: topic: TypeScript

#33795 fix(gatsby): Don't warn about `config` in ESLint
  e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
  packages/gatsby/src/utils/eslint-rules/__tests__/limited-exports-page-templates.ts
  packages/gatsby/src/utils/eslint-rules/limited-exports-page-templates.ts
Labels: topic: DX

#33802 chore(gatsby-plugin-mdx): Add commonmark to pluginOptionsSchema
  packages/gatsby-plugin-mdx/__tests__/gatsby-node.js
  packages/gatsby-plugin-mdx/gatsby-node.js
Labels: topic: remark/mdx

#33808 chore(examples): Fix Gatsbygram
  examples/gatsbygram/data/posts.json
  examples/gatsbygram/src/components/Avatar.js
Labels: type: maintenance

#33819 chore: fix changelog auto-updates in ci
  scripts/gatsby-changelog-generator/update-and-open-pr.js
Labels: type: maintenance

#33788 chore(docs): Release notes for 4.1
  docs/docs/reference/release-notes/v4.1/index.md
Labels: type: documentation

#33793 chore(docs): Update docs for DSG in FS Routes
  docs/docs/how-to/rendering-options/using-deferred-static-generation.md
  docs/docs/reference/rendering-options/deferred-static-generation.md
  docs/docs/reference/rendering-options/server-side-rendering.md
  docs/docs/reference/routing/file-system-route-api.md
Labels: type: documentation

#33810 fix(gatsby): apply getServerData response header in develop
  packages/gatsby/src/utils/start-server.ts
Labels: topic: render-mode

#33823 chore: make structured logs tests less flaky
  integration-tests/structured-logging/__tests__/to-do.js
Labels: type: maintenance

#33826 feat(gatsby): let Gatsby clear the module cache in workers for `render-page.js`
  packages/gatsby/src/utils/worker/child/index.ts
Labels: topic: core

#33843 chore: error handling for update changelogs script
  scripts/gatsby-changelog-generator/update-and-open-pr.js
Labels: type: maintenance

#33834 feat(gatsby): Exclude tests in Gatsby Functions
  docs/docs/reference/functions/getting-started.md
  integration-tests/functions/plugins/gatsby-plugin-cool/src/api/gatsby-plugin-cool/shadowed.test.js
  integration-tests/functions/src/api/ignore/.config.js
  integration-tests/functions/src/api/ignore/__tests__/hello.js
  integration-tests/functions/src/api/ignore/foo.d.ts
  integration-tests/functions/src/api/ignore/hello.test.js
  integration-tests/functions/test-helpers.js
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: topic: DX

#33829 chore(docs): fix issues in 0009-telemetry RFC
  rfcs/text/0009-telemetry.md
Labels: type: documentation

#33595 fix(gatsby): Reuse readPageData
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: topic: core

#33861 fix(gatsby-source-drupal): Add missing `params` from options to API urls
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: topic: source-drupal

#33865 fix(gatsby): TS type for `unstable_createNodeManifest` action
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#33683 feat(gatsby-source-drupal): Add node manifest support for previews
  packages/gatsby-source-drupal/src/utils.js
Labels: topic: source-drupal

#33839 chore(gatsby): Update inference-metadata type
  packages/gatsby/src/schema/infer/inference-metadata.ts
Labels: topic: TypeScript

#33848 chore(docs): Update `createPage` documentation w/ Content Sync
  docs/docs/creating-and-modifying-pages.md
Labels: type: documentation

#33867 fix(gatsby): API doc about `unstable_createNodeManifest`
  packages/gatsby/src/redux/actions/public.js
Labels: type: documentation

#31846 chore: Use upstream stale github action
  .github/workflows/schedule-stale.yml
Labels: type: maintenance

#33690 fix(gatsby): Allow all env vars in `getServerData`
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/arrow-fn/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/arrow-fn/output.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/function/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/function/output.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/options.json
  packages/gatsby/src/utils/babel/__tests__/index.js
  packages/gatsby/src/utils/babel/babel-plugin-env-vars.ts
Labels: topic: core

#33528 breaking(gatsby-source-contentful): remove gatsby-image support
  e2e-tests/contentful/cypress/integration/gatsby-image.js
  e2e-tests/contentful/cypress/integration/rich-text.js
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/english-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/fixed-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/fixed-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/fluid-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/fluid-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/german-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/sqip-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/sqip-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/traced-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/traced-1.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/webp-0.snap.png
  e2e-tests/contentful/cypress/snapshots/gatsby-image.js/webp-1.snap.png
  e2e-tests/contentful/snapshots.js
  e2e-tests/contentful/src/pages/gatsby-image.js
  e2e-tests/contentful/src/pages/index.js
  e2e-tests/contentful/src/pages/rich-text.js
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/src/__tests__/extend-node-type.js
  packages/gatsby-source-contentful/src/__tests__/gatsby-plugin-image.js
  packages/gatsby-source-contentful/src/__tests__/image-helpers.js
  packages/gatsby-source-contentful/src/download-contentful-assets.js
  packages/gatsby-source-contentful/src/extend-node-type.js
  packages/gatsby-source-contentful/src/fragments.js
  packages/gatsby-source-contentful/src/gatsby-plugin-image.js
  packages/gatsby-source-contentful/src/image-helpers.js
  packages/gatsby-transformer-sqip/src/extend-node-type.js
Labels: topic: source-contentful

#33588 fix(gatsby): TS type for `createTypes` action arrays
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#33866 chore(docs): Add conceptual guide on content sync
  docs/docs/conceptual/content-sync.md
  docs/docs/creating-and-modifying-pages.md
  docs/docs/images/content-sync-diagram.png
  docs/docs/images/content-sync-error.png
  docs/docs/images/content-sync-loading.png
Labels: type: documentation

#33901 chore(gatsby-plugin-gatsby-google-analytics): Highlight the plugin we recommend
  packages/gatsby-plugin-google-analytics/README.md
Labels: type: documentation

#33461 feat(gatsby-core-utils): Add retry on HTTP status codes to `fetchRemoteFile`
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
Labels: bot: merge on green, topic: core

#33864 fix(gatsby-source-drupal): Ensure all new nodes are created before creating relationships
  packages/gatsby-source-drupal/src/__tests__/fixtures/1593545806.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/webhook-body-multiple-nodes.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: topic: source-drupal

#33908 chore(docs): Update "Creating a Source Plugin" guides
  docs/docs/creating-a-source-plugin.md
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: type: documentation

#33917 fix(gatsby-plugin-gatsby-cloud): Preview UI tooltip
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/IndicatorButtonTooltip.js
Labels: topic: plugins

#33825 chore(docs): Update Gatsby framework version support information
  README.md
  docs/docs/reference/release-notes/gatsby-version-support.md
  docs/docs/reference/release-notes/v2-maintenance-plan.md
Labels: type: documentation

#33912 chore(gatsby): Correct fromNode TS type
  packages/gatsby/src/schema/resolvers.ts
  packages/gatsby/src/schema/type-definitions.ts
  packages/gatsby/src/schema/types/date.ts
Labels: topic: TypeScript

#33915 chore(docs): remove slug generation from MDX doc
  docs/docs/mdx/programmatically-creating-pages.md
Labels: type: documentation

#33903 feat(contentful): modifying schemes to add support for AVIF images
  e2e-tests/contentful/cypress/integration/gatsby-plugin-image.js
  e2e-tests/contentful/src/pages/gatsby-plugin-image.js
  packages/gatsby-source-contentful/src/gatsby-plugin-image.js
  packages/gatsby-source-contentful/src/image-helpers.js
  packages/gatsby-source-contentful/src/schemes.js
Labels: bot: merge on green, topic: source-contentful

#33932 fix(gatsby-core-utils): fix fetchRemoteFile when called in main process after being called in worker
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
Labels: topic: core

#33853 fix(gatsby): ensure that writing node manifests to disk does not break on Windows
  packages/gatsby/src/utils/__tests__/node-manifest.ts
  packages/gatsby/src/utils/node-manifest.ts
Labels: topic: core

#33964 fix(docs): incorrect link "programmatically creating pages from data"
  docs/docs/recipes/pages-layouts.md
Labels: status: triage needed

#33971 chore: Typo in BUG_REPORT
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: type: documentation

#33967 chore(docs): Update client-only doc
  docs/docs/how-to/routing/client-only-routes-and-user-authentication.md
Labels: type: documentation

#33975 fix(gatsby-core-utils): handle 304 correctly between builds
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
Labels: topic: core, topic: source-plugins

#33977 fix(gatsby-source-graphql): Use default export from node-fetch
  packages/gatsby-source-graphql/src/fetch.js
Labels: topic: source-plugins

#33970 chore(gatsby-source-graphql): warn people that source-graphql is slow for larger sites
  packages/gatsby-source-graphql/README.md
Labels: type: documentation

#33896 chore: CircleCI updates
  .circleci/config.yml
Labels: type: maintenance

#33991 fix(gatsby-source-wordpress): fixes createRoot not exists warning
  packages/gatsby-source-wordpress/src/gatsby-browser.ts
Labels: bot: merge on green, topic: source-wordpress

#33989 fix(gatsby-source-wordpress): always hydrate in develop for images
  packages/gatsby-source-wordpress/src/gatsby-browser.ts
Labels: bot: merge on green, topic: source-wordpress

#34001 chore(docs): Typo in docs/processing-payments-with-square
  docs/docs/processing-payments-with-square.md
Labels: type: documentation

#34000 chore(examples): Typo in creating-source-plugins
  examples/creating-source-plugins/README.md
Labels: type: documentation

#33984 chore(gatsby): add `getCache` helper to `NodePluginArgs`
  packages/gatsby/index.d.ts
  packages/gatsby/src/utils/api-node-helpers-docs.js
Labels: topic: TypeScript

#34003 chore(gatsby): Add `getServerData` to PageProps type
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#33966 fix(gatsby-plugin-manifest): Delete `cacheDigest` from generated webmanifest
  packages/gatsby-plugin-manifest/src/gatsby-node.js
Labels: topic: plugins-PWA

#34004 chore: Improve Stale Slack Message
  .github/actions/format-stale-output/.gitignore
  .github/actions/format-stale-output/README.md
  .github/actions/format-stale-output/action.yml
  .github/actions/format-stale-output/dist/index.js
  .github/actions/format-stale-output/dist/licenses.txt
  .github/actions/format-stale-output/index.js
  .github/actions/format-stale-output/package.json
  .github/actions/format-stale-output/slack-message.js
  .github/workflows/schedule-stale.yml
Labels: topic: automation

#34031 fix(gatsby): use new `renderToPipeableStream`
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: core

#34044 fix(gatsby-source-shopify): Correct `gatsby-plugin-image` peerDep
  packages/gatsby-source-shopify/package.json
Labels: type: maintenance, topic: source-shopify

#34038 feat(gatsby-plugin-nprogress): Replace `nprogress` with `accessible-nprogress`
  packages/gatsby-plugin-nprogress/README.md
  packages/gatsby-plugin-nprogress/package.json
  packages/gatsby-plugin-nprogress/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-nprogress/src/gatsby-browser.js
  yarn.lock
Labels: topic: plugins

#34045 perf(gatsby-cli): dont retain logs in memory in non-ink loggers
  packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/context.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/index.tsx
  packages/gatsby-cli/src/reporter/redux/internal-actions.ts
  packages/gatsby-cli/src/reporter/redux/reducers/logs.ts
  packages/gatsby-cli/src/reporter/redux/types.ts
Labels: topic: cli

#34053 chore(docs): remove mention of willitbuild.com
  docs/docs/how-to/performance/improving-build-performance.md
Labels: bot: merge on green

#34056 chore(docs): Update webpack fs resolution
  docs/docs/how-to/local-development/troubleshooting-common-errors.md
Labels: type: documentation

#34048 perf(gatsby): remove unnecessary code from engines
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
Labels: topic: build, gatsby 4

#34057 fix(create-gatsby): Order inputs alphabetically
  packages/create-gatsby/src/cmses.json
  packages/create-gatsby/src/features.json
  packages/create-gatsby/src/styles.json
Labels: topic: plugins

#34058 chore(docs): Note about engine bundling
  docs/docs/reference/release-notes/migrating-from-v3-to-v4.md
  docs/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4.md
Labels: type: documentation

#34064 fix(gatsby-recipes): Pin `remark-mdx` to `2.0.0-next.7`
  packages/gatsby-recipes/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: topic: core

#34075 Simplify plugin docs
  docs/docs/conceptual/choosing-a-cms.md
  docs/docs/conceptual/plugins-themes-and-starters.md
  docs/docs/plugins.md
  docs/docs/what-is-a-plugin.md
  docs/docs/what-you-dont-need-plugins-for.md
Labels: status: triage needed

#34076 fix typos
  docs/docs/conceptual/choosing-a-cms.md
  docs/docs/plugins.md
Labels: status: triage needed

#33692 feat(gatsby): Reduce cost of sourcing after the initial
  packages/gatsby/src/utils/source-nodes.ts
Labels: bot: merge on green, topic: performance, gatsby 4, gatsby 3

#34079 fix(gatsby-cli): fix stuck warnings not showing all the in-progress activities
  packages/gatsby-cli/src/reporter/redux/diagnostics.ts
  packages/gatsby-cli/src/reporter/redux/index.ts
Labels: topic: cli

#34067 chore: Remove obsolete resolutions
  package.json
  yarn.lock
Labels: type: maintenance

#34083 chore(gatsby-source-contentful): Add note to Rich Text docs
  packages/gatsby-source-contentful/README.md
Labels: type: documentation, topic: source-contentful

#34024 feat(gatsby): Node manifest api v2
  integration-tests/node-manifest/__tests__/create-node-manifest.test.js
  integration-tests/node-manifest/gatsby-node.js
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/index.d.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/reducers/node-manifest.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/__tests__/node-manifest.ts
  packages/gatsby/src/utils/node-manifest.ts
  packages/gatsby/src/utils/page-data-helpers.ts
  packages/gatsby/src/utils/page-data.ts
Labels: topic: core

#34086 fix(gatsby): node manifests v2 inc builds
  packages/gatsby/src/utils/node-manifest.ts
  packages/gatsby/src/utils/page-data.ts
Labels: bot: merge on green

#34084 fix(gatsby-transformer-json): Fix high memory consumption
  packages/gatsby-transformer-json/src/gatsby-node.js
Labels: topic: plugins

#34089 fix(gatsby): create placeholder interface if it doesn't exist yet when merging SDL type
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/schema.js
Labels: topic: GraphQL

#34091 chore(docs): Add missing permission for Shopify Admin API
  docs/docs/building-an-ecommerce-site-with-shopify.md
Labels: type: documentation

#31395 CTF-next: use union for reference fields with validation
  e2e-tests/contentful/schema.gql
  e2e-tests/contentful/snapshots.js
  e2e-tests/contentful/src/pages/content-reference.js
  e2e-tests/contentful/src/pages/rich-text.js
  packages/gatsby-source-contentful/src/__fixtures__/content-types.js
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/create-schema-customization.js.snap
  packages/gatsby-source-contentful/src/__tests__/create-schema-customization.js
  packages/gatsby-source-contentful/src/generate-schema.js
  packages/gatsby-source-contentful/src/normalize.js
Labels: breaking change, topic: source-contentful

#34095 feat: add job type to progress label, so each job type has separate progress bar
  packages/gatsby/src/utils/jobs/manager.ts
Labels: topic: cli

#34061 fix(gatsby): Add back an activity for jobs
  packages/gatsby-cli/src/reporter/reporter-progress.ts
  packages/gatsby/src/utils/jobs/__tests__/manager.js
  packages/gatsby/src/utils/jobs/manager.ts
Labels: topic: core, gatsby 4

#34102 chore(gatsby): log pending jobs when build is stuck
  packages/gatsby-cli/src/reporter/redux/diagnostics.ts
  packages/gatsby-cli/src/reporter/reporter.ts
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/services/initialize.ts
Labels: topic: cli
