Repository gatsbyjs/gatsby, pull requests merged in 2021-02, with the labels that each got.

#29290 fix(gatsby-plugin-sharp): make sure to pass the failOnError option to base64 generation (#29254)
  packages/gatsby-plugin-sharp/src/index.js
Labels: type: cherry

#29201 feat(gatsby): speed up createPages
  benchmarks/create-pages/gatsby-node.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/internal-plugins/prod-404/gatsby-node.js
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/plugin-runner.ts
  packages/gatsby/src/redux/reducers/components.ts
  packages/gatsby/src/redux/reducers/pages.ts
  packages/gatsby/src/redux/reducers/queries.ts
  packages/gatsby/src/services/create-pages.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/services/rebuild-schema-with-site-pages.ts
  packages/gatsby/src/utils/__tests__/handle-flags.ts
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/handle-flags.ts
  packages/gatsby/src/utils/js-chunk-names.ts
  packages/gatsby/src/utils/validate-page-component.ts
Labels: topic: performance, topic: scaling builds

#29295 Add note about build perf benefits
  docs/docs/reference/release-notes/v2.32/index.md
Labels: status: triage needed

#29298 fix(gatsby-plugin-image): Correct layout proptypes in StaticImage
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
Labels: bot: merge on green, topic: images/media

#29299 fix(gatsby-plugin-image): Correct layout proptypes in StaticImage (#29298)
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
Labels: type: cherry

#29297 docs(gatsby-source-contentful): Add info to readme on use with new image plugin
  packages/gatsby-source-contentful/README.md
Labels: status: needs docs review

#29301 docs(gatsby-source-contentful): Add info to readme on use with new image plugin (#29297)
  packages/gatsby-source-contentful/README.md
Labels: type: cherry

#29253 docs: release notes for v2.32
  docs/docs/reference/release-notes/v2.32/index.md
Labels: type: documentation

#29302 chore: fix mdx for release notes with backticks around <sources>
  docs/docs/reference/release-notes/v2.32/index.md
Labels: status: triage needed

#29306 refactor(gatsby-plugin-manifest): don't import fs in ssr code
  packages/gatsby-plugin-manifest/src/__tests__/common.js
  packages/gatsby-plugin-manifest/src/__tests__/node-helpers.js
  packages/gatsby-plugin-manifest/src/common.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  packages/gatsby-plugin-manifest/src/node-helpers.js
Labels: status: awaiting author response, topic: frontend-general

#29103 gatsby-link: remove deprecated APIs
  packages/gatsby-link/index.d.ts
  packages/gatsby-link/src/__tests__/index.js
  packages/gatsby-link/src/index.js
  packages/gatsby-link/src/parse-path.js
  packages/gatsby/index.d.ts
Labels: topic: reach/router and Links

#29294 Updates links to gatsby cloud docs.
  docs/docs/how-to/previews-deploys-hosting/deploying-to-gatsby-cloud.md
Labels: status: triage needed

#29268 feat(contentful): add retry logic to asset downloading
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__tests__/download-with-retry.js
  packages/gatsby-source-contentful/src/cache-image.js
  packages/gatsby-source-contentful/src/download-with-retry.js
  packages/gatsby-source-contentful/src/extend-node-type.js
  yarn.lock
Labels: status: needs core review, topic: Contentful

#29322 fix(assert-changed-files): reset to PR branch and not to some history that might not have been changed
  scripts/assert-changed-files.sh
Labels: type: maintenance

#29328 chore: fix reset hard in assert-changed-files
  .circleci/config.yml
  scripts/assert-changed-files.sh
Labels: status: needs core review

#29321 chore: deprecate gatsby-plugin-guess-js
  deprecated-packages/gatsby-plugin-guess-js/.babelrc
  deprecated-packages/gatsby-plugin-guess-js/.gitignore
  deprecated-packages/gatsby-plugin-guess-js/.npmignore
  deprecated-packages/gatsby-plugin-guess-js/CHANGELOG.md
  deprecated-packages/gatsby-plugin-guess-js/README.md
  deprecated-packages/gatsby-plugin-guess-js/index.js
  deprecated-packages/gatsby-plugin-guess-js/package.json
  deprecated-packages/gatsby-plugin-guess-js/src/__tests__/gatsby-node.js
  deprecated-packages/gatsby-plugin-guess-js/src/__tests__/gatsby-ssr.js
  deprecated-packages/gatsby-plugin-guess-js/src/gatsby-browser.js
  deprecated-packages/gatsby-plugin-guess-js/src/gatsby-node.js
  deprecated-packages/gatsby-plugin-guess-js/src/gatsby-ssr.js
  jest.config.js
  yarn.lock
Labels: type: maintenance

#29333 fix(gatsby-plugin-image): Hide placeholder on hydrated components with loaded images
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Labels: topic: images/media

#29354 fix(gatsby-plugin-image): Fix blur up on navigate issue (#29333)
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Labels: type: cherry

#29346 fix(babel-preset-gatsby): remove spread operator from node builds
  packages/babel-preset-gatsby/package.json
  packages/babel-preset-gatsby/src/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby/src/__tests__/index.js
  packages/babel-preset-gatsby/src/index.js
Labels: status: needs core review, topic: webpack/babel

#29359 chore: update mdx starter & docs
  docs/docs/glossary/mdx.md
  docs/docs/how-to/routing/mdx.md
  docs/docs/mdx/getting-started.md
  starters/gatsby-starter-mdx-basic/package-lock.json
  starters/gatsby-starter-mdx-basic/package.json
Labels: topic: starters, type: documentation

#29356 chore(create-gatsby): Use new image plugin
  packages/create-gatsby/src/features.json
Labels: topic: cli

#29353 chore(gatsby-source-wordpress): Update querying-data tutorial
  packages/gatsby-source-wordpress/docs/tutorials/querying-data.md
Labels: topic: WordPress, type: documentation

#29292 chore(docs): Fix product slugs for building-an-ecommerce-site-with-shopify page
  docs/docs/building-an-ecommerce-site-with-shopify.md
Labels: type: documentation

#29389 docs(wordpress): fix broken assets link after migration
  packages/gatsby-source-wordpress/docs/tutorials/configuring-wp-gatsby.md
Labels: topic: WordPress, type: documentation

#29395 fix(tests): Update SSR error page snapshot
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
Labels: bot: merge on green, topic: automation

#29394 fix(gatsby-plugin-offline): Cache avif images
  packages/gatsby-plugin-offline/src/gatsby-node.js
Labels: bot: merge on green

#29360 docs(gatsby-source-wordpress): Update using-self-signed-certificates.md tutorial
  packages/gatsby-source-wordpress/docs/tutorials/using-self-signed-certificates.md
Labels: topic: WordPress

#29397 chore(tests): Enable node 14 tests
  .circleci/config.yml
Labels: bot: merge on green, type: maintenance

#29127 chore(gatsby): Remove __experimentalThemes
  packages/gatsby/src/bootstrap/load-themes/index.js
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/gatsby-node.js
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/themes.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/did-you-mean.ts
  packages/gatsby/src/utils/get-static-dir.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: themes

#29405 chore(docs): Remove extra curly brace
  docs/docs/creating-and-modifying-pages.md
Labels: type: documentation

#29386 chore(gatsby-source-wordpress): Add v3 docs link
  packages/gatsby-source-wordpress/README.md
Labels: topic: WordPress, type: documentation

#29186 gatsby: Remove pathContext
  e2e-tests/production-runtime/cypress/integration/1-production.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/src/pages/index.js
  e2e-tests/production-runtime/src/pages/path-context.js
  packages/gatsby/cache-dir/page-renderer.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/utils/print-deprecation-warnings.ts
Labels: topic: frontend-core, topic: internal

#29248 chore(gatsby): Remove deprecated `gatsby-browser` APIs
  docs/docs/resource-handling-and-service-workers.md
  packages/gatsby/cache-dir/api-runner-browser.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/page-renderer.js
  packages/gatsby/index.d.ts
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/src/utils/api-browser-docs.ts
Labels: topic: frontend-core, topic: internal

#29090 chore: bump graphql and graphql-compose major versions
  packages/gatsby-codemods/package.json
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/transform-options.output.js
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-recipes/package.json
  packages/gatsby-source-graphql/src/__tests__/__snapshots__/transforms.js.snap
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby/index.d.ts
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/create-graphql-runner.ts
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/infer/__tests__/infer-input.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/schema-composer.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/__tests__/filter-input.js
  packages/gatsby/src/schema/types/__tests__/sort-and-filter.js
  packages/gatsby/src/schema/types/derived-types.ts
  packages/gatsby/src/schema/types/filter.ts
  packages/gatsby/src/schema/types/sort.ts
  packages/gatsby/src/schema/types/type-builders.ts
  yarn.lock
Labels: breaking change, topic: GraphQL

#29401 docs(gatsby-source-wordpress): add migration from experimental instructions
  packages/gatsby-source-wordpress/docs/migrating-from-other-wp-source-plugins.md
Labels: topic: WordPress, type: documentation

#29247 gatsby-transformer-sharp: Remove `sizes` and `resolutions` node
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby-transformer-sharp/src/fragments.js
  packages/gatsby/src/query/__tests__/fixtures/query-compiler-schema.graphql
Labels: topic: images/media, topic: sharp

#29208 chore(gatsby): Remove hasNodeChanged
  packages/gatsby-source-hacker-news/src/gatsby-node.js
  packages/gatsby-source-mongodb/src/gatsby-node.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/utils/api-node-helpers-docs.js
  packages/gatsby/src/utils/api-runner-node.js
Labels: topic: internal, topic: plugins

#29368 chore(gatsby): remove `many` argument from `childOf` directive
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/schema.js
Labels: breaking change, topic: GraphQL

#29369 chore(gatsby): no implicit `childOf` with `dontInfer`
  packages/gatsby/src/schema/extensions/__tests__/child-relations.js
  packages/gatsby/src/schema/schema.js
Labels: breaking change, topic: GraphQL

#29399 chore(gatsby): do not add __typename to GraphQL query
  packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/query-compiler.js
Labels: breaking change, topic: GraphQL

#29392 feat(gatsby): track connections by default in runQuery and getAllNodes
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
Labels: topic: GraphQL

#29367 chore(gatsby): remove noDefaultResolvers argument from infer extension
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/rebuild-sitepage-type.js
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/infer/__tests__/infer.js
  packages/gatsby/src/schema/infer/__tests__/merge-types.js
  packages/gatsby/src/schema/infer/add-inferred-fields.js
  packages/gatsby/src/schema/infer/index.js
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/type-defs.js
Labels: breaking change, topic: GraphQL

#29403 docs(gatsby-source-wordpress): Add preview caveats
  packages/gatsby-source-wordpress/docs/features/preview.md
Labels: topic: WordPress, type: documentation

#29194 feat(gatsby): Remove deleteNodes
  packages/gatsby/index.d.ts
  packages/gatsby/src/bootstrap/create-graphql-runner.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/reducers/inference-metadata.ts
  packages/gatsby/src/redux/reducers/nodes-by-type.ts
  packages/gatsby/src/redux/reducers/nodes.ts
  packages/gatsby/src/redux/reducers/resolved-nodes.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/schema/__tests__/rebuild-schema.js
  packages/gatsby/src/utils/api-runner-node.js
Labels: topic: internal, topic: plugins

#29207 feat(gatsby): Remove fieldName & fieldValue from createNodeField
  packages/gatsby/index.d.ts
  packages/gatsby/src/redux/actions/public.js
Labels: topic: internal, topic: plugins

#29291 feat(gatsby): Remove possibility to use global graphql tag for queries
  packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap
  packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js
  packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/query/__tests__/file-parser.js
  packages/gatsby/src/query/file-parser.js
Labels: topic: GraphQL, topic: internal

#29424 fix: add common-tags to package.jsons
  packages/gatsby-plugin-image/package.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby-transformer-sharp/package.json
Labels: status: needs core review, type: maintenance

#29245 feat(gatsby): Remove old touchNode signature
  docs/docs/creating-a-source-plugin.md
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
  examples/creating-source-plugins/source-plugin/gatsby-node.js
  packages/gatsby-source-contentful/src/download-contentful-assets.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-shopify/src/gatsby-node.js
  packages/gatsby-source-shopify/src/nodes.js
  packages/gatsby-source-wordpress/src/steps/persist-cached-images.ts
  packages/gatsby-transformer-screenshot/src/gatsby-node.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/db/__tests__/nodes.js
  packages/gatsby/src/redux/actions/public.js
Labels: topic: internal, topic: plugins

#29425 chore(gatsby-source-contentful): Remove deprecated image resolvers
  packages/gatsby-source-contentful/src/extend-node-type.js
  packages/gatsby-source-contentful/src/fragments.js
Labels: topic: Contentful

#29205 feat(gatsby): Remove deleteNode with ID arg
  docs/docs/creating-a-source-plugin.md
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
  e2e-tests/development-runtime/plugins/gatsby-source-fake-data/gatsby-node.js
  e2e-tests/development-runtime/plugins/gatsby-source-pinc-data/gatsby-node.js
  examples/creating-source-plugins/source-plugin/gatsby-node.js
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-filesystem/src/gatsby-node.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/db/__tests__/nodes.js
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/source-nodes.ts
Labels: topic: internal, topic: plugins

#29342 feat(gatsby-plugin-image): Add resolver helper and improve custom hook
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-image/src/index.browser.ts
  packages/gatsby-plugin-image/src/index.ts
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: images/media

#29431 fix: clear tracked queries when deleting stale page-data files
  packages/gatsby/src/redux/reducers/queries.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/page-data.ts
Labels: topic: stale-artifacts*

#29429 fix(gatsby-plugin-offline): Cache avif images (#29394)
  packages/gatsby-plugin-offline/src/gatsby-node.js
Labels: type: cherry

#29413 Address todos for major release
  packages/babel-preset-gatsby/src/index.js
  packages/gatsby-plugin-feed/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-feed/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-feed/src/gatsby-node.js
  packages/gatsby-plugin-google-analytics/src/gatsby-node.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
Labels: status: needs core review

#29129 feat(gatsby): Remove boundActionCreators
  packages/gatsby-plugin-sharp/src/__tests__/index.js
  packages/gatsby-plugin-sharp/src/__tests__/scheduler.js
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/scheduler.js
  packages/gatsby-source-npm-package-search/src/__tests__/gatsby-node.js
  packages/gatsby-source-npm-package-search/src/gatsby-node.js
  packages/gatsby-source-shopify/README.md
  packages/gatsby/index.d.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/internal-plugins/prod-404/gatsby-node.js
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/query/file-parser.js
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/query/query-watcher.ts
  packages/gatsby/src/redux/actions/index.ts
  packages/gatsby/src/redux/actions/internal.ts
  packages/gatsby/src/services/create-pages.ts
  packages/gatsby/src/services/post-bootstrap.ts
  packages/gatsby/src/state-machines/develop/actions.ts
  packages/gatsby/src/utils/api-node-helpers-docs.js
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/changed-pages.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/print-deprecation-warnings.ts
  packages/gatsby/src/utils/source-nodes.ts
Labels: topic: internal, topic: plugins

#29398 feat(gatsby-source-contentful): improve Contentful image handling
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: bot: merge on green, topic: Contentful, topic: images/media

#29427 feat(gatsby): support interface inheritance
  docs/docs/reference/graphql-data-layer/schema-customization.md
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/__tests__/print.js
  packages/gatsby/src/schema/extensions/__tests__/child-relations.js
  packages/gatsby/src/schema/extensions/__tests__/interfaces.js
  packages/gatsby/src/schema/extensions/index.js
  packages/gatsby/src/schema/print.js
  packages/gatsby/src/schema/schema.js
Labels: topic: GraphQL

#29437 chore: remove scroll container
  docs/docs/how-to/routing/scroll-restoration.md
  packages/gatsby-react-router-scroll/src/index.ts
  packages/gatsby-react-router-scroll/src/scroll-container.tsx
Labels: status: needs core review

#29414 todos part 2
  packages/gatsby-plugin-google-gtag/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-google-gtag/src/gatsby-ssr.js
  packages/gatsby-plugin-mdx/utils/default-options.js
  packages/gatsby-plugin-netlify/src/__tests__/__snapshots__/build-headers-program.js.snap
  packages/gatsby-plugin-netlify/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-netlify/src/build-headers-program.js
Labels: status: needs core review

#29436 chore: remove progress bar
  packages/gatsby-plugin-sharp/src/__tests__/utils.js
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-plugin-sharp/src/scheduler.js
  packages/gatsby-plugin-sharp/src/utils.js
Labels: status: needs core review

#29462 fix(gatsby-plugin-image): Rename hooks
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/index.browser.ts
  packages/gatsby-plugin-image/src/index.ts
Labels: status: triage needed

#29464 chore(gatsby-source-wordpress): remove multiple h1s from README
  packages/gatsby-source-wordpress/README.md
Labels: status: triage needed

#29472 fix: drop terminal-link
  packages/gatsby/package.json
  packages/gatsby/src/utils/__tests__/handle-flags.ts
  packages/gatsby/src/utils/__tests__/show-experiment-notice.js
  packages/gatsby/src/utils/handle-flags.ts
  packages/gatsby/src/utils/show-experiment-notice.ts
Labels: topic: cli

#29468 docs(gatsby-source-wordpress): fix back to readme.md link
  packages/gatsby-source-wordpress/docs/tutorials/index.md
Labels: status: triage needed

#29465 chore: remove multiple h1s from official plugin docs
  packages/gatsby-plugin-styled-components/README.md
  packages/gatsby-source-graphql/README.md
Labels: status: triage needed

#29452 chore: remove progressbar
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/__tests__/utils.js
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/utils.js
Labels: status: needs core review

#29474 remove generateSideEffects API
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/src/utils/api-node-docs.ts
Labels: status: needs core review

#29463 chore: address core package todos
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/persist.ts
Labels: status: needs core review

#29477 fix: drop terminal-link (#29472)
  packages/gatsby/package.json
  packages/gatsby/src/utils/__tests__/handle-flags.ts
  packages/gatsby/src/utils/__tests__/show-experiment-notice.js
  packages/gatsby/src/utils/handle-flags.ts
  packages/gatsby/src/utils/show-experiment-notice.ts
Labels: type: cherry

#29479 fix(gatsby): skip unions in input types
  packages/gatsby-recipes/package.json
  packages/gatsby/package.json
  packages/gatsby/src/schema/types/__tests__/filter-input.js
  packages/gatsby/src/schema/types/sort.ts
  yarn.lock
Labels: topic: GraphQL

#29450 feat(gatsby): display GraphQL deprecations as CLI warnings
  packages/gatsby/src/query/__tests__/graphql-runner.ts
  packages/gatsby/src/query/graphql-runner.ts
  packages/gatsby/src/query/query-runner.ts
Labels: topic: GraphQL

#29168 docs(gatsby-plugin-netlify): Update readme
  packages/gatsby-plugin-netlify/README.md
Labels: bot: merge on green, type: documentation

#29484 chore(docs): Update adding-markdown-pages
  docs/docs/how-to/routing/adding-markdown-pages.md
Labels: status: triage needed

#29485 Update index.js to stop React errors in console about the 'key'
  starters/gatsby-starter-minimal/src/pages/index.js
Labels: topic: starters

#29488 chore(docs): Update sourcing-from-json-or-yaml
  docs/docs/how-to/sourcing-data/sourcing-from-json-or-yaml.md
Labels: type: documentation

#29494 docs: fix spelling
  benchmarks/gabe-fs-markdown-images/README.md
  dictionary.txt
  docs/docs/conceptual/using-gatsby-image.md
  docs/docs/reference/routing/creating-routes.md
  packages/gatsby-source-wordpress/README.md
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/docs/tutorials/querying-data.md
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.ts
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/recursively-transform-fields.js
  packages/gatsby-source-wordpress/src/utils/cache.ts
Labels: type: documentation

#29519 chore(gatsby): pin graphql-compose version to patch
  packages/gatsby-recipes/package.json
  packages/gatsby/package.json
Labels: topic: GraphQL

#29396 refactor(html-ssr): remove fs from ssr bundle, remove static queries from ssr bundle
  packages/babel-plugin-remove-graphql-queries/src/index.ts
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/api-runner-ssr.js
  packages/gatsby/cache-dir/develop-static-entry.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/worker/child.ts
  packages/gatsby/src/utils/worker/render-html.ts
Labels: breaking change, topic: SSG*, topic: conditional page builds*

#29525 tests: Fix cli integration test
  integration-tests/gatsby-cli/__tests__/new.js
Labels: bot: merge on green

#29530 Fix URL typo in sass recipe
  packages/gatsby-recipes/recipes/sass.mdx
Labels: status: triage needed

#29482 feat(conditional-page-builds): track ssr compilation hash
  integration-tests/artifacts/__tests__/index.js
  integration-tests/artifacts/gatsby-node.js
  integration-tests/artifacts/gatsby-ssr.js
  integration-tests/artifacts/src/components/post-body-components-ssr.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/reducers/html.ts
  packages/gatsby/src/redux/types.ts
Labels: topic: SSG*, topic: conditional page builds*

#29486 feat(conditional-page-builds): track static query results
  docs/docs/conditional-page-builds.md
  integration-tests/artifacts/__tests__/index.js
  integration-tests/artifacts/gatsby-node.js
  integration-tests/artifacts/src/pages/static-query-result-tracking/rerun-query-but-dont-recreate-html.js
  integration-tests/artifacts/src/pages/static-query-result-tracking/should-invalidate.js
  integration-tests/artifacts/src/pages/static-query-result-tracking/stable.js
  packages/gatsby/src/commands/build-utils.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/reducers/html.ts
  packages/gatsby/src/redux/types.ts
Labels: topic: SSG*, topic: conditional page builds*

#29538 webpack 5: ensure static query hashes array has deterministic order, only dispatch actions if that list changed
  packages/gatsby/src/utils/webpack/static-query-mapper.ts
Labels: status: triage needed

#29537 hack: overwrite contenthash set by mini-css-extract-plugin
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/tmp-mini-css-extract-contenthash-overwrite.ts
Labels: status: triage needed

#29544 fix(gatsby-plugin-styled-components): Support `topLevelImportPaths` option
  packages/gatsby-plugin-styled-components/src/gatsby-node.js
Labels: topic: styled-components

#29499 chore(build): move html generation to separate function
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
Labels: topic: SSG*, topic: conditional page builds*

#29145 feat(gatsby): upgrade webpack to version 5
  e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
  e2e-tests/development-runtime/cypress/integration/eslint-rules/no-anonymous-exports-page-templates.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/src/components/static-query/use-static-query/destructuring.js
  integration-tests/artifacts/gatsby-browser.js
  integration-tests/gatsby-cli/__tests__/build-errors.js
  integration-tests/gatsby-cli/__tests__/build-ssr-errors.js
  package.json
  packages/gatsby-admin/gatsby-node.js
  packages/gatsby-admin/package.json
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/create-react-context.js
  packages/gatsby/cache-dir/develop-static-entry.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/package.json
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build-javascript.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/__tests__/__snapshots__/develop-html-route.ts.snap
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
  packages/gatsby/src/utils/__tests__/develop-html-route.ts
  packages/gatsby/src/utils/__tests__/map-templates-to-static-query-hashes.js
  packages/gatsby/src/utils/__tests__/webpack-error-utils.ts
  packages/gatsby/src/utils/__tests__/webpack-utils.ts
  packages/gatsby/src/utils/dev-ssr/__tests__/develop-html-route.ts
  packages/gatsby/src/utils/dev-ssr/__tests__/fixtures/error-object.js
  packages/gatsby/src/utils/dev-ssr/render-dev-html-child.js
  packages/gatsby/src/utils/eslint-rules-helpers.ts
  packages/gatsby/src/utils/map-templates-to-static-query-hashes.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/webpack-error-utils.ts
  packages/gatsby/src/utils/webpack-plugins.ts
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/static-query-mapper.ts
  packages/gatsby/src/utils/webpack/tmp-mini-css-extract-contenthash-overwrite.ts
  packages/gatsby/src/utils/worker/render-html.ts
  yarn.lock
Labels: topic: webpack/babel

#29533 chore(docs): Update Directus plugin link
  docs/docs/how-to/sourcing-data/headless-cms.md
Labels: type: documentation

#29518 feat(gatsby-plugin-image): Add getLowResolutionImageURL plugin helper
  packages/gatsby-plugin-image/src/__tests__/image-utils.ts
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-image/src/index.browser.ts
  packages/gatsby-plugin-image/src/index.ts
Labels: bot: merge on green, topic: images/media

#29483 docs(gatsby-plugin-image): Add image plugin toolkit docs
  docs/docs/how-to/plugins-and-themes/adding-gatsby-image-support.md
Labels: topic: images/media, type: documentation

#29558 Update graphql-wordpress-and-gatsby.md
  packages/gatsby-source-wordpress/docs/features/graphql-wordpress-and-gatsby.md
Labels: bot: merge on green, topic: WordPress

#29522 fix(contentful): fix import
  packages/gatsby-source-contentful/src/cache-image.js
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: status: needs core review, topic: Contentful

#29458 fix(gatsby-source-shopify): Don't remove version string from Shopify image URLs
  packages/gatsby-source-shopify/src/nodes.js
Labels: topic: Shopify

#29548 feat(conditional-page-builds): make it default
  .circleci/config.yml
  docs/docs/conceptual/overview-of-the-gatsby-build-process.md
  docs/docs/conditional-page-builds.md
  integration-tests/artifacts/__tests__/index.js
  integration-tests/gatsby-cli/__tests__/build.js
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/services/initialize.ts
Labels: topic: SSG*, topic: conditional page builds*

#29562 fix(gatsby-source-contentful): Correct supported image formats
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-source-contentful/src/extend-node-type.js
  packages/gatsby-source-contentful/src/schemes.js
Labels: topic: Contentful

#29563 fix(gatsby): fix deprecation export messages
  packages/gatsby/cache-dir/gatsby-browser-entry.js
Labels: topic: reach/router and navigation

#29540 feat: remove react-hot-loader
  .circleci/config.yml
  docs/docs/conceptual/gatsby-lifecycle-apis.md
  e2e-tests/development-runtime/cypress/integration/eslint-rules/limited-exports-page-templates.js
  e2e-tests/development-runtime/cypress/integration/eslint-rules/no-anonymous-exports-page-templates.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/arrow-functions.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/class-component.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/hooks.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/new-file.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/non-js-file.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/page-component.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/page-queries.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/static-queries.js
  e2e-tests/development-runtime/cypress/integration/hot-reloading/template-component.js
  e2e-tests/development-runtime/cypress/integration/navigation/linking.js
  e2e-tests/development-runtime/cypress/support/commands.js
  e2e-tests/development-runtime/package.json
  packages/gatsby-plugin-preact/src/gatsby-node.js
  packages/gatsby/cache-dir/__tests__/error-overlay-handler.js
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/error-overlay-handler.js
  packages/gatsby/cache-dir/root.js
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/eslint/required.js
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/get-react-hot-loader-strategy.ts
  packages/gatsby/src/utils/webpack-hmr-hooks-patch.js
  packages/gatsby/src/utils/webpack.config.js
Labels: status: needs core review, type: maintenance

#29564 fix(gatsby-plugin-sharp): Fix defaults handling
  packages/gatsby-plugin-sharp/README.md
  packages/gatsby-plugin-sharp/src/__tests__/plugin-options.ts
  packages/gatsby-plugin-sharp/src/plugin-options.js
Labels: topic: images/media

#29453 V3/remark todo
  packages/gatsby-transformer-remark/README.md
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: status: needs core review

#29575 fix(gatsby): prevent errors when backwards compat node.nodeId is for a deleted node in touchNode
  packages/gatsby/src/redux/actions/public.js
Labels: bot: merge on green

#29582 docs: remove unneeded whitespace from Markdown link
  packages/gatsby-source-wordpress/docs/community-and-support.md
Labels: type: documentation

#29581 docs: fix spelling
  docs/docs/how-to/plugins-and-themes/adding-gatsby-image-support.md
Labels: type: documentation

#29580 docs: fix case of GitHub, JavaScript, TypeScript and WordPress
  docs/docs/conceptual/choosing-a-cms.md
  docs/docs/conceptual/gatsby-for-ecommerce.md
  docs/docs/conceptual/using-gatsby-image.md
  packages/gatsby-remark-embed-snippet/README.md
  packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md
  packages/gatsby/CHANGELOG.md
Labels: type: documentation

#29578 chore(docs): Fix caching typo
  docs/docs/caching.md
Labels: type: documentation

#29594 tests: Fix cli integration test (#29525)
  integration-tests/gatsby-cli/__tests__/new.js
Labels: topic: automation, type: cherry

#29539 Add gatsby-plugin-gatsby-cloud 1.0
  packages/gatsby-plugin-gatsby-cloud/.babelrc
  packages/gatsby-plugin-gatsby-cloud/.gitignore
  packages/gatsby-plugin-gatsby-cloud/README.md
  packages/gatsby-plugin-gatsby-cloud/index.js
  packages/gatsby-plugin-gatsby-cloud/package.json
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/build-headers-program.js.snap
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/create-redirects.js.snap
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-redirects.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/is-sibling.js
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/constants.js
  packages/gatsby-plugin-gatsby-cloud/src/create-redirects.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
  packages/gatsby-plugin-gatsby-cloud/src/is-sibling.js
  packages/gatsby-plugin-gatsby-cloud/src/plugin-data.js
Labels: bot: merge on green

#29596 fix(css-modules): fix webpack config for css modules
  e2e-tests/development-runtime/cypress/integration/styling/css-modules.js
  e2e-tests/development-runtime/cypress/integration/styling/plain-css.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/src/pages/styling/css-modules.js
  e2e-tests/development-runtime/src/pages/styling/css-modules.module.css
  e2e-tests/development-runtime/src/pages/styling/plain-css.css
  e2e-tests/development-runtime/src/pages/styling/plain-css.js
  e2e-tests/production-runtime/cypress/integration/styling/css-modules.js
  e2e-tests/production-runtime/cypress/integration/styling/plain-css.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/pages/styling/css-modules.js
  e2e-tests/production-runtime/src/pages/styling/css-modules.module.css
  e2e-tests/production-runtime/src/pages/styling/plain-css.css
  e2e-tests/production-runtime/src/pages/styling/plain-css.js
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: webpack/babel

#29579 Update the changelog of Contentful plugin to show a working example
  packages/gatsby-source-contentful/CHANGELOG.md
Labels: bot: merge on green, topic: Contentful

#29603 fix(gatsby-plugin-image): Apply inline styles and img size
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
Labels: bot: merge on green, topic: images/media

#29454 chore(docs): Remove Pair Programming docs
  docs/contributing/docs-writing-process.md
  docs/contributing/gatsby-governance-model.md
  docs/contributing/how-to-contribute.md
  docs/contributing/how-to-write-a-stub.md
  docs/contributing/pair-programming.md
  docs/contributing/why-contribute-to-gatsby.md
  docs/docs/conceptual/gatsby-core-philosophy.md
Labels: type: documentation

#29599 fix: make minicss-extract-plugin compatible with plugins
  packages/gatsby-plugin-less/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-less/src/gatsby-node.js
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  packages/gatsby-plugin-postcss/src/__tests__/__snapshots__/gatsby-node.test.js.snap
  packages/gatsby-plugin-postcss/src/gatsby-node.js
  packages/gatsby-plugin-sass/package.json
  packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-sass/src/gatsby-node.js
  packages/gatsby-plugin-stylus/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-stylus/src/gatsby-node.js
  yarn.lock
Labels: topic: webpack/babel

#29607 fix(gatsby-plugin-image): Correct default enum value
  packages/gatsby-plugin-image/src/resolver-utils.ts
Labels: bot: merge on green, topic: images/media

#29587 chore: Fix typos
  packages/gatsby-recipes/src/recipes-list.js
Labels: type: documentation

#29615 fix(npm-package-search): declare mimeType so markdown trasformer children are added
  packages/gatsby-source-npm-package-search/src/gatsby-node.js
Labels: topic: GraphQL

#29373 Improving site performance doc
  docs/docs/how-to/performance/improving-site-performance.md
Labels: type: documentation

#29531 feat(gatsby-core-utils): Add file download functions
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/__tests__/create-remote-file-node-integration.js
  packages/gatsby-core-utils/src/__tests__/fixtures/dog-thumbnail.jpg
  packages/gatsby-core-utils/src/__tests__/fixtures/file.json
  packages/gatsby-core-utils/src/__tests__/fixtures/gatsby-logo.svg
  packages/gatsby-core-utils/src/fetch-remote-file.ts
  packages/gatsby-core-utils/src/filename-utils.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/utils.js
  packages/gatsby/index.d.ts
  tsconfig.json
  yarn.lock
Labels: topic: filesystem

#29630 chore(gatsby): bump mini-css-extract-plugin
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/tmp-mini-css-extract-contenthash-overwrite.ts
  yarn.lock
Labels: topic: webpack/babel

#29648 chore(build): use params from yargs and don't check process.argv
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
Labels: topic: conditional page builds*

#29646 chore(html): add context about not handling page query result directly in html reducer
  packages/gatsby/src/redux/reducers/html.ts
Labels: topic: conditional page builds*

#29645 chore(conditional-page-builds): remove dead `setPageData` action
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/types.ts
Labels: topic: conditional page builds*

#29576 fix(gatsby): cleanup fullySpecified resolving
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: webpack/babel

#29631 fix(gatsby): fix fs empty webpack5 deprecation
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/webpack-error-utils.ts
Labels: topic: webpack/babel

#29642 feat(gatsby-plugin-netlify-cms): fix compatibility for webpack5
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  yarn.lock
Labels: topic: netlify

#29662 chore(gatsby): drop unused friendly-errors-webpack-plugin dep
  packages/gatsby/package.json
Labels: type: maintenance

#29560 feat(conditional-page-builds): track potentially unsafe Node.js builtin modules usage
  integration-tests/artifacts/__tests__/index.js
  integration-tests/artifacts/css-to-inline.css
  integration-tests/artifacts/gatsby-ssr.js
  integration-tests/artifacts/src/components/post-body-components-ssr.js
  packages/gatsby-cli/src/reporter/errors.ts
  packages/gatsby-cli/src/reporter/prepare-stack-trace.ts
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/ssr-builtin-trackers/child_process.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/fs.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/http.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/http2.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/https.js
  packages/gatsby/cache-dir/ssr-builtin-trackers/tracking-unsafe-module-wrapper.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build-utils.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/reducers/html.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/worker/render-html.ts
Labels: topic: SSG*, topic: conditional page builds*

#29589 fix(gatsby-plugin-sharp): Fix defaults handling (#29564)
  packages/gatsby-plugin-sharp/README.md
  packages/gatsby-plugin-sharp/src/__tests__/plugin-options.ts
  packages/gatsby-plugin-sharp/src/plugin-options.js
Labels: topic: sharp, type: cherry

#29391 feat(gatsby): move sync-requires to async-requires in develop
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
  integration-tests/ssr/__tests__/ssr.js
  packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
  packages/gatsby/cache-dir/__tests__/__snapshots__/dev-loader.js.snap
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/__tests__/dev-loader.js
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/cache-dir/develop-static-entry.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: frontend-core

#29663 fix(webpack): don't disable webpack's cache
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: topic: webpack/babel

#29627 fix(gatsby-source-wordpress): remove hard tabs from Markdown
  packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md
  packages/gatsby-source-wordpress/docs/migrating-from-other-wp-source-plugins.md
Labels: topic: WordPress, type: documentation

#29629 chore(docs): remove unneeded whitespace before commas and full stops
  docs/docs/how-to/images-and-media/using-cloudinary-image-service.md
  packages/gatsby-plugin-sharp/README.md
  packages/gatsby-remark-smartypants/README.md
Labels: type: documentation

#29613 chore(docs): Add note on reloading bash configuration.
  docs/docs/tutorial/part-zero/index.md
Labels: type: documentation

#29605 chore(starters): Add Gatsby Cloud plugin to default & blog
  starters/blog/gatsby-config.js
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/default/gatsby-config.js
  starters/default/package-lock.json
  starters/default/package.json
Labels: topic: starters

#29625 feat(gatsby-plugin-image): Allow image helpers to take other node types
  packages/gatsby-plugin-image/src/components/__tests__/hooks.ts
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/index.browser.ts
  packages/gatsby-plugin-image/src/index.ts
Labels: topic: images/media

#29664 fix(contentful): retry on network errors when checking credentials
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/gatsby-node.js
  yarn.lock
Labels: status: needs core review, topic: Contentful

#29667 chore: Deprecate gatsby-image and old image resolvers
  packages/gatsby-image/README.md
  packages/gatsby-plugin-image/README.md
  packages/gatsby-transformer-sharp/src/customize-schema.js
Labels: bot: merge on green, topic: images/media

#29677 chore: fix reset hard in assert-changed-files (#29328)
  .circleci/config.yml
  scripts/assert-changed-files.sh
Labels: type: cherry

#29670 chore: improve description of placeholder parameter
  packages/gatsby-plugin-image/src/resolver-utils.ts
Labels: bot: merge on green, topic: images/media

#29681 fix(develop): add blank .css to ensure mini-css-extract-plugin always has something to extract
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/blank.css
Labels: topic: webpack/babel

#29688 feat(gatsby-plugin-canonical-urls): Add plugin validation
  packages/gatsby-plugin-canonical-urls/src/gatsby-node.js
Labels: status: triage needed

#29620 fix(DEV_SSR): set NODE_ENV to production for render-html worker process instead of pointing externals to production react
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: ssr

#29406 feat(gatsby-source-wordpress): Add missing tests
  .circleci/config.yml
  integration-tests/gatsby-source-wordpress/.env.test
  integration-tests/gatsby-source-wordpress/.gitignore
  integration-tests/gatsby-source-wordpress/.wordpress-cache/wp-content/uploads/2020/03/84-1000x1000-1.jpg
  integration-tests/gatsby-source-wordpress/.wordpress-cache/wp-content/uploads/2020/08/1001-5616x3744-1-scaled.jpg
  integration-tests/gatsby-source-wordpress/.wordpress-cache/wp-content/uploads/2020/08/1002-4312x2868-1-scaled.jpg
  integration-tests/gatsby-source-wordpress/.wordpress-cache/wp-content/uploads/2020/08/1003-1181x1772-1.jpg
  integration-tests/gatsby-source-wordpress/.wordpress-cache/wp-content/uploads/2020/08/file-sample_1MB.doc
  integration-tests/gatsby-source-wordpress/.wordpress-cache/wp-content/uploads/2020/10/sample.doc
  integration-tests/gatsby-source-wordpress/.wordpress-cache/wp-content/uploads/2020/10/sample.pdf
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/__tests__/index.js
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  integration-tests/gatsby-source-wordpress/jest.config.js
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/gatsby-source-wordpress/src/assets/images/fake.png
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/filtered-type-defs.js
  integration-tests/gatsby-source-wordpress/test-fns/gatsby-image.js
  integration-tests/gatsby-source-wordpress/test-fns/index.js
  integration-tests/gatsby-source-wordpress/test-fns/integrity.js
  integration-tests/gatsby-source-wordpress/test-fns/plugin-options.js
  integration-tests/gatsby-source-wordpress/test-fns/query-generation.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/authed-wpgql-request.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/get-gatsby-process.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/increment-remote-data.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/incremental-it.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/queries.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/test-resolved-data.js
  packages/gatsby-source-wordpress/__tests__/plugin-options-schema.test.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/transform-object.js
Labels: topic: WordPress

#29669 feat: shim reporter from gatsby
  packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
  packages/gatsby-plugin-page-creator/src/__tests__/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/derive-path.ts
  packages/gatsby-plugin-page-creator/src/error-utils.ts
  packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-sharp/src/__tests__/index.js
  packages/gatsby-plugin-sharp/src/__tests__/utils.js
  packages/gatsby-plugin-sharp/src/image-data.ts
  packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/__tests__/utils.js
  packages/gatsby-source-wordpress/src/models/logger.ts
  packages/gatsby-source-wordpress/src/steps/preview/index.ts
  packages/gatsby-source-wordpress/src/steps/temp-prevent-multiple-instances.ts
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby/package.json
  packages/gatsby/reporter.d.ts
  packages/gatsby/reporter.js
Labels: topic: reporter

#29697 fix(gatsby): Fix snapshot for integration-tests/ssr tests
  integration-tests/ssr/__tests__/__snapshots__/ssr.js.snap
  integration-tests/ssr/gatsby-config.js
Labels: status: triage needed

#29693 fix(gatsby): re-add prefetch/preload links for child assets
  integration-tests/artifacts/__tests__/index.js
  integration-tests/artifacts/src/components/magic-comments/prefetch.js
  integration-tests/artifacts/src/components/magic-comments/preload.js
  integration-tests/artifacts/src/pages/dynamic-imports-magic-comments.js
  packages/gatsby/src/utils/gatsby-webpack-stats-extractor.ts
  packages/gatsby/src/utils/worker/render-html.ts
Labels: topic: webpack/babel

#29388 chore: Upgrade typescript
  .eslintignore
  .eslintrc.js
  e2e-tests/development-runtime/src/components/class-component.js
  package.json
  packages/create-gatsby/package.json
  packages/create-gatsby/src/utils.ts
  packages/create-gatsby/tsconfig.json
  packages/gatsby-admin/package.json
  packages/gatsby-admin/src/components/instantsearch-provider.tsx
  packages/gatsby-admin/src/components/layout.tsx
  packages/gatsby-admin/src/components/plugin-search.tsx
  packages/gatsby-admin/src/pages/plugins.tsx
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby-core-utils/package.json
  packages/gatsby-design-tokens/package.json
  packages/gatsby-legacy-polyfills/package.json
  packages/gatsby-page-utils/package.json
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/components/later-hydrator.tsx
  packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/components/static-image.tsx
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/extract-query.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby-plugin-page-creator/src/is-valid-collection-path-implementation.ts
  packages/gatsby-plugin-page-creator/src/path-utils.ts
  packages/gatsby-plugin-utils/package.json
  packages/gatsby-react-router-scroll/src/use-scroll-restoration.ts
  packages/gatsby-telemetry/package.json
  packages/gatsby-telemetry/src/get-dependencies.ts
  packages/gatsby-telemetry/src/store.ts
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/db/common/query.ts
  packages/gatsby/src/redux/actions/restricted.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/schema/infer/__tests__/inference-metadata.ts
  packages/gatsby/src/schema/infer/inference-metadata.ts
  packages/gatsby/src/utils/__tests__/get-page-data.ts
  packages/gatsby/src/utils/dev-ssr/render-dev-html.ts
  packages/gatsby/src/utils/get-value-at.ts
  packages/gatsby/src/utils/jobs-manager.ts
  packages/gatsby/src/utils/mett.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/wait-until-jobs-complete.ts
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack/__tests__/corejs-resolver.ts
  yarn.lock
Labels: topic: TypeScript

#29686 chore(docs): Update debugging-html-builds
  docs/docs/debugging-html-builds.md
Labels: type: documentation

#29706 chore: remove --cache from eslint
  package.json
Labels: type: maintenance

#29707 chore(gatsby-core-utils): Move isTruthy to gatsby-core-utils
  packages/gatsby-core-utils/src/__tests__/is-truthy.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-core-utils/src/is-truthy.ts
  packages/gatsby-telemetry/src/event-storage.ts
Labels: bot: merge on green

#29676 chore(docs): Updated gatsby-for-ecommerce
  docs/docs/conceptual/gatsby-for-ecommerce.md
Labels: type: documentation

#28171 fix(e2e): don't double run cypress tests
  e2e-tests/development-runtime/package.json
  e2e-tests/gatsby-image/package.json
  e2e-tests/gatsby-static-image/package.json
  e2e-tests/mdx-less-babel/package.json
  e2e-tests/mdx/package.json
  e2e-tests/path-prefix/package.json
  e2e-tests/production-runtime/package.json
  e2e-tests/themes/development-runtime/package.json
  e2e-tests/themes/production-runtime/package.json
  e2e-tests/visual-regression/package.json
  scripts/cypress-run-with-conditional-record-flag.js
Labels: type: maintenance
