Repository gatsbyjs/gatsby, pull requests merged in 2022-07, with the labels that each got.

#36012 feat: Publish some packages as ESM & CJS
  packages/create-gatsby/package.json
  packages/gatsby-design-tokens/package.json
  packages/gatsby-legacy-polyfills/package.json
  packages/gatsby-link/.babelrc
  packages/gatsby-link/package.json
  packages/gatsby-link/src/index.js
  packages/gatsby-link/src/prefix-helpers.js
  packages/gatsby-link/src/rewrite-link-path.js
  packages/gatsby-link/tsconfig.json
  packages/gatsby-plugin-image/package.json
  packages/gatsby-script/.babelrc
  packages/gatsby-script/package.json
  yarn.lock
Labels: type: maintenance

#36011 fix(gatsby-source-contentful): Add `proxy.protocol` to Joi schema
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: topic: source-contentful

#36043 fix(gatsby-source-contentful): remove faulty parent
  packages/gatsby-source-contentful/src/normalize.js
  yarn.lock
Labels: topic: source-contentful

#35983 MDXv2: remove default layouts and add support for pageQueries
  benchmarks/gabe-fs-mdx/gatsby-config.js
  benchmarks/gabe-fs-mdx/gatsby-node.js
  benchmarks/gabe-fs-mdx/src/templates/blog-post.js
  packages/gatsby-cli/src/reporter/loggers/ink/components/pageTree.tsx
  packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-core-utils/src/parse-component-path.ts
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-mdx/src/compile-mdx.ts
  packages/gatsby-plugin-mdx/src/frontmatter.ts
  packages/gatsby-plugin-mdx/src/gatsby-layout-loader.ts
  packages/gatsby-plugin-mdx/src/gatsby-mdx-loader.ts
  packages/gatsby-plugin-mdx/src/gatsby-node.ts
  packages/gatsby-plugin-mdx/src/get-source-plugins-as-remark-plugins.ts
  packages/gatsby-plugin-mdx/src/plugin-options.ts
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js
  packages/gatsby/src/query/file-parser.js
  packages/gatsby/src/query/query-watcher.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/__tests__/__snapshots__/pages.ts.snap
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/utils/__tests__/js-chunk-names.ts
  packages/gatsby/src/utils/js-chunk-names.ts
  packages/gatsby/src/utils/validate-page-component.ts
  yarn.lock
Labels: topic: remark/mdx

#36020 fix(gatsby-core-utils): add tree-shake (esm) to core-utils
  packages/gatsby-core-utils/.babelrc
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: type: maintenance

#36025 chore(docs): Release notes for 4.18
  docs/docs/reference/release-notes/v4.18/index.md
Labels: type: documentation

#36070 chore(renovate): Move lmdb into its own group
  renovate.json5
  scripts/renovate-config-generator.js
Labels: topic: automation

#36023 MDXv2: update e2e and benchmark
  .circleci/config.yml
  benchmarks/gabe-fs-mdx/src/templates/blog-post.js
  e2e-tests/mdx-less-babel/cypress/fixtures/file-to-attempt-rce-on.txt
  e2e-tests/mdx-less-babel/cypress/integration/frontmatter.js
  e2e-tests/mdx-less-babel/gatsby-node.js
  e2e-tests/mdx-less-babel/src/pages/frontmatter-graphql-query.js
  e2e-tests/mdx-less-babel/src/pages/frontmatter-javascript.mdx
  e2e-tests/mdx-less-babel/src/pages/frontmatter-js.mdx
  e2e-tests/mdx-less-babel/src/pages/frontmatter-json.mdx
  e2e-tests/mdx-less-babel/src/pages/frontmatter-yaml.mdx
  e2e-tests/mdx-less-babel/src/pages/mdx-query-js-frontmatter.js
  e2e-tests/mdx-less-babel/src/posts/frontmatter-engine/javascript-frontmatter.mdx
  e2e-tests/mdx-less-babel/src/posts/frontmatter-engine/js-frontmatter.mdx
  e2e-tests/mdx/cypress/integration/frontmatter.js
  e2e-tests/mdx/gatsby-node.js
  e2e-tests/mdx/src/pages/frontmatter-graphql-query.js
  e2e-tests/mdx/src/pages/frontmatter-javascript.mdx
  e2e-tests/mdx/src/pages/frontmatter-js.mdx
  e2e-tests/mdx/src/pages/frontmatter-json.mdx
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/__tests__/__snapshots__/pages.ts.snap
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/__tests__/pages.ts
  packages/gatsby/src/utils/__tests__/js-chunk-names.ts
Labels: topic: automation

#36074 feat(gatsby): Sanitize redux page state
  packages/gatsby/src/redux/actions/public.js
Labels: topic: core

#36082 fix(gatsby): Show error, exit process on SSR error
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: core

#36088 fix(docs): Remove unused docs & update node.js upgrade doc
  docs/docs/awesome-gatsby-resources.md
  docs/docs/creating-global-styles.md
  docs/docs/how-to/adding-common-features/creating-a-form-in-react.md
  docs/docs/prpl-pattern.md
  docs/docs/upgrading-node-js.md
Labels: status: needs docs review

#36089 fix(docs): remove pages not linked from anywhere
  docs/docs/add-a-service-worker.md
  docs/docs/conceptual/choosing-analytics-systems.md
  docs/docs/glamor.md
  docs/docs/how-to/sourcing-data/headless-cms.md
  docs/docs/partnering-with-gatsby.md
  docs/docs/preparing-for-site-launch.md
  docs/docs/recipes/gitlab-continuous-integration.md
  docs/docs/sourcing-from-seams-cms.md
  docs/docs/using-gatsby-professionally/answering-it-security.md
  docs/docs/using-gatsby-professionally/best-practices-for-orgs.md
  docs/docs/using-gatsby-professionally/component-libraries.md
  docs/docs/using-gatsby-professionally/convincing-others.md
  docs/docs/using-gatsby-professionally/different-organization-types.md
  docs/docs/using-gatsby-professionally/faster-recruiting.md
  docs/docs/using-gatsby-professionally/first-professional-project.md
  docs/docs/using-gatsby-professionally/gatsby-for-agencies.md
  docs/docs/using-gatsby-professionally/gatsby-for-companies.md
  docs/docs/using-gatsby-professionally/gatsby-for-freelancers.md
  docs/docs/using-gatsby-professionally/gatsby-in-the-enterprise.md
  docs/docs/using-gatsby-professionally/going-gatsby-only.md
  docs/docs/using-gatsby-professionally/how-gatsby-boosts-career.md
  docs/docs/using-gatsby-professionally/lower-bids-more-profit.md
  docs/docs/using-gatsby-professionally/making-components-discoverable.md
  docs/docs/using-gatsby-professionally/sanitize-your-stack.md
  docs/docs/using-gatsby-professionally/setting-up-gatsby-without-gatsby-new.md
  docs/docs/using-gatsby-professionally/sharing-components-across-websites.md
  docs/docs/using-gatsby-professionally/using-gatsby-professionally.md
  docs/docs/using-gatsby-professionally/winning-over-clients.md
  docs/docs/using-gatsby-professionally/winning-over-content-creators.md
  docs/docs/using-gatsby-professionally/winning-over-developers.md
  docs/docs/using-gatsby-professionally/winning-over-engineering-leaders.md
  docs/docs/using-gatsby-professionally/winning-over-executives.md
  docs/docs/using-gatsby-professionally/winning-over-marketers.md
  docs/docs/using-gatsby-professionally/winning-over-stakeholders.md
Labels: status: triage needed

#36083 fix(gatsby): hydration issues when load is low enough to show indicator
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
Labels: topic: frontend

#36076 chore(docs): Add `gatsby-link` to `transformIgnorePatterns`
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#36081 docs(gatsby-plugin-mdx): fix a typo in v3 to v4 migration guide
  packages/gatsby-plugin-mdx/README.md
Labels: type: documentation

#36077 MDXv2: docs: add steps to migrate
  packages/gatsby-plugin-mdx/README.md
Labels: type: documentation

#35675 chore(gatsby): remove other services
  integration-tests/node-manifest/__tests__/create-node-manifest.test.js
  integration-tests/node-manifest/package.json
  integration-tests/node-manifest/utils/get-gatsby-process.js
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
  packages/gatsby/cache-dir/app.js
  packages/gatsby/package.json
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/develop-proxy.ts
  packages/gatsby/src/utils/graphql-typegen/file-writes.ts
  packages/gatsby/src/utils/restarting-screen.ts
  packages/gatsby/src/utils/telemetry-server.ts
  yarn.lock
Labels: type: maintenance

#36049 chore(docs): update jest.config.js
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#36114 fix(head-function-export): Make tsx pages work
  packages/gatsby-plugin-typescript/src/gatsby-node.js
Labels: topic: core

#36116 fix(parcel-namer-relative-to-cwd): move @parcel/namer-default from peerDeps to deps
  packages/gatsby-parcel-namer-relative-to-cwd/package.json
Labels: type: maintenance

#36026 fix(gatsby-source-drupal): Ensure node updates are handled sequentially to avoid race conditions when saving nodes
  packages/gatsby-source-drupal/src/__tests__/fixtures/paragraph-v1.json
  packages/gatsby-source-drupal/src/__tests__/fixtures/paragraph-v2.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: topic: source-drupal, topic: source-plugins

#36110 feat(gatsby-graphiql-explorer): Amend Query name if available
  packages/gatsby-graphiql-explorer/src/app/__tests__/snippets.js
  packages/gatsby-graphiql-explorer/src/app/snippets.js
Labels: topic: GraphQL, topic: DX

#36136 fix(gatsby): Allow script in Gatsby Head
  e2e-tests/development-runtime/cypress/integration/head-function-export/html-insertion.js
  e2e-tests/development-runtime/cypress/integration/head-function-export/navigation.js
  e2e-tests/development-runtime/cypress/integration/head-function-export/warnings.js
  e2e-tests/development-runtime/shared-data/head-function-export.js
  e2e-tests/development-runtime/src/components/head-function-export.js
  e2e-tests/development-runtime/src/pages/head-function-export/basic.js
  e2e-tests/development-runtime/src/pages/head-function-export/warnings.js
  e2e-tests/production-runtime/cypress/integration/head-function-export/html-insertion.js
  e2e-tests/production-runtime/cypress/integration/head-function-export/navigation.js
  e2e-tests/production-runtime/shared-data/head-function-export.js
  e2e-tests/production-runtime/src/components/head-function-export.js
  e2e-tests/production-runtime/src/pages/head-function-export/basic.js
  integration-tests/head-function-export/__tests__/ssr-html-output.js
  integration-tests/head-function-export/shared-data/head-function-export.js
  integration-tests/head-function-export/src/components/head-function-export.js
  integration-tests/head-function-export/src/pages/head-function-export/basic.js
  packages/gatsby/cache-dir/head/constants.js
  packages/gatsby/cache-dir/head/utils.js
Labels: topic: core

#35514 fix(gatsby-source-drupal): Add langcode to manifest ID
  packages/gatsby-source-drupal/src/utils.js
Labels: topic: source-drupal, topic: source-plugins

#36145 chore(docs): fix outdated link
  docs/docs/mdx/writing-pages.md
Labels: bot: merge on green, status: triage needed

#36153 chore(docs): Update to Basic Hardware and Software Requirements
  docs/docs/basic-hardware-software-requirements.md
Labels: type: documentation

#36086 fix(gatsby-plugin-sass): Add support for additionalData option
  packages/gatsby-plugin-sass/README.md
  packages/gatsby-plugin-sass/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
Labels: topic: plugins-styling

#36134 feat(gatsby-source-contentful): skip expensive touchNode step when unnecessary
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: topic: source-contentful

#36158 fix(gatsby): Keep order in moved meta tags
  packages/gatsby/cache-dir/__tests__/static-entry.js
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: core

#36160 fix(gatsby): Wrap Head with <Location>
  e2e-tests/production-runtime/cypress/integration/head-function-export/use-location.js
  e2e-tests/production-runtime/shared-data/head-function-export.js
  e2e-tests/production-runtime/src/pages/head-function-export/page-with-uselocation.js
  packages/gatsby/cache-dir/head/head-export-handler-for-browser.js
Labels: topic: DX

#36125 chore(docs): Add Gatsby Head
  docs/docs/add-page-metadata.md
  docs/docs/add-seo-component.md
  docs/docs/how-to/adding-common-features/adding-seo-component.md
  docs/docs/how-to/adding-common-features/seo.md
  docs/docs/how-to/custom-configuration/typescript.md
  docs/docs/reference/built-in-components/gatsby-head.md
  examples/using-gatsby-head/README.md
  examples/using-gatsby-head/gatsby-config.ts
  examples/using-gatsby-head/gatsby-node.ts
  examples/using-gatsby-head/gatsby-ssr.tsx
  examples/using-gatsby-head/package.json
  examples/using-gatsby-head/src/components/seo.tsx
  examples/using-gatsby-head/src/hooks/use-site-metadata.tsx
  examples/using-gatsby-head/src/pages/404.tsx
  examples/using-gatsby-head/src/pages/index.tsx
  examples/using-gatsby-head/src/pages/parks/{Park.name}.tsx
  examples/using-gatsby-head/static/gatsby-icon.png
  examples/using-gatsby-head/tsconfig.json
Labels: type: documentation, topic: DX

#36166 chore(gatsby-plugin-react-helmet): Add deprecation notice
  packages/gatsby-plugin-react-helmet/README.md
  packages/gatsby-plugin-react-helmet/src/gatsby-node.js
Labels: topic: plugins

#36130 chore(docs): Release Notes 4.19
  docs/docs/reference/release-notes/v4.19/index.md
Labels: type: documentation

#36169 fix(gatsby-plugin-image): Correct type for getImage
  packages/gatsby-plugin-image/src/components/hooks.ts
Labels: bot: merge on green, topic: media

#36172 fix(gatsby): add GATSBY_CLOUD_IMAGE_CDN
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
Labels: topic: render-mode

#36141 feat(gatsby-source-wordpress): use env var to disable catch links
  packages/gatsby-source-wordpress/docs/features/gatsby-link.md
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/gatsby-config.js
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
Labels: topic: source-wordpress, topic: source-plugins

#36176 chore(docs): Typo in 4.19 release notes
  docs/docs/reference/release-notes/v4.19/index.md
Labels: type: documentation

#35946 chore: Deploy Button Changes
  e2e-tests/contentful/README.md
  e2e-tests/development-runtime/README.md
  e2e-tests/path-prefix/README.md
  e2e-tests/production-runtime/README.md
  examples/ecommerce-tutorial-with-stripe/README.md
  examples/using-shopify/README.md
  examples/using-square-payments/README.md
  examples/using-type-definitions/README.md
Labels: type: documentation

#36185 chore(gatsby-parcel-config): Adjust peerDep
  packages/gatsby-parcel-config/package.json
Labels: type: maintenance

#36174 fix(gatsby): prevent escaping textContent for scripts
  packages/gatsby/cache-dir/head/head-export-handler-for-ssr.js
Labels: topic: DX

#36188 chore: Improve docs around minimal reproduction
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  docs/contributing/how-to-make-a-reproducible-test-case.md
  docs/contributing/rfc-process.md
Labels: type: documentation

#36184 chore(docs): Add section about `navigate(-1)`
  docs/docs/reference/built-in-components/gatsby-link.md
Labels: type: documentation

#36132 fix(gatsby): content sync connection and static query page tracking
  integration-tests/node-manifest/__tests__/create-node-manifest.test.js
  integration-tests/node-manifest/gatsby-node.js
  integration-tests/node-manifest/src/pages/connection-list-query-page.js
  integration-tests/node-manifest/src/pages/static-query-list-query.js
  packages/gatsby/src/query/query-watcher.ts
  packages/gatsby/src/utils/node-manifest.ts
Labels: bot: merge on green, topic: core

#36199 fix(gatsby-link): Publish types
  packages/gatsby-link/package.json
Labels: topic: core

#36179 fix(gatsby-plugin-utils): fix encoding issue for image-cdn
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/public-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/dispatchers.ts
Labels: topic: media

#29553 fix(gatsby): Allow `export { default }` named exports in page templates
  packages/gatsby/src/utils/eslint-rules/__tests__/limited-exports-page-templates.ts
  packages/gatsby/src/utils/eslint-rules/limited-exports-page-templates.ts
Labels: bot: merge on green, topic: DX

#36050 chore(docs): Add dependency for TypeScript testing
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#36219 Grammar typo fixed
  docs/docs/tutorial/part-1/index.mdx
Labels: status: triage needed

#36228 chore(docs): Typo fix in debugging-html-builds
  docs/docs/debugging-html-builds.md
Labels: type: documentation

#36224 chore(docs): Clarify note in "local font" how-to
  docs/docs/how-to/styling/using-local-fonts.md
Labels: type: documentation

#36221 chore(docs): Instruct to install v2 of `unist-util-visit` in remark tutorial
  docs/tutorial/remark-plugin-tutorial.md
Labels: type: documentation

#36216 chore(docs): Add `react-helmet` note in Gatsby Head reference
  docs/docs/reference/built-in-components/gatsby-head.md
Labels: type: documentation

#36204 chore(docs): Upgrade Cypress to v10 in E2E Testing
  docs/docs/how-to/testing/end-to-end-testing.md
  examples/using-cypress/README.md
  examples/using-cypress/cypress.config.js
  examples/using-cypress/cypress.json
  examples/using-cypress/cypress/e2e/accessibility.test.js
  examples/using-cypress/cypress/plugins/index.js
  examples/using-cypress/cypress/support/e2e.js
  examples/using-cypress/gatsby-config.js
  examples/using-cypress/gatsby-ssr.js
  examples/using-cypress/package.json
  examples/using-cypress/src/components/image.js
  examples/using-cypress/src/components/layout.js
  examples/using-cypress/src/components/seo.js
  examples/using-cypress/src/images/gatsby-astronaut.png
  examples/using-cypress/src/images/gatsby-icon.png
  examples/using-cypress/src/pages/404.js
  examples/using-cypress/src/pages/index.js
  examples/using-cypress/src/pages/page-2.js
Labels: type: documentation

#36229 fix(gatsby-link): Update resolve import
  packages/gatsby-link/src/rewrite-link-path.js
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#36222 chore(create-gatsby): Remove gatsby-plugin-react-helmet
  packages/create-gatsby/src/questions/features.json
Labels: topic: DX

#36118 MDX v2: Support FS routes
  packages/gatsby-core-utils/src/parse-component-path.ts
  packages/gatsby-plugin-mdx/src/gatsby-node.ts
  packages/gatsby-plugin-page-creator/src/__tests__/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/__tests__/extract-query.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/extract-query.ts
  packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js
  packages/gatsby/index.d.ts
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/scripts/output-api-file.js
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/types/node-interface.ts
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/js-chunk-names.ts
  packages/gatsby/src/utils/webpack/plugins/__tests__/static-query-mapper.ts
  packages/gatsby/src/utils/webpack/plugins/static-query-mapper.ts
Labels: topic: core, topic: remark/mdx

#35501 chore(gatsby-source-contentful): migrate to latest Contentful SDK
  e2e-tests/contentful/snapshots.js
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__tests__/fetch-network-errors.js
  packages/gatsby-source-contentful/src/fetch.js
  yarn.lock
Labels: type: maintenance, status: needs core review, topic: source-contentful

#36231 fix(gatsby): use pathPrefix for SSR/DSG page-data requests with `gatsby serve`
  e2e-tests/path-prefix/cypress/integration/navigate.js
  e2e-tests/path-prefix/cypress/integration/path-prefix.js
  e2e-tests/path-prefix/package.json
  e2e-tests/path-prefix/scripts/serve.js
  e2e-tests/path-prefix/src/pages/index.js
  e2e-tests/path-prefix/src/pages/ssr.js
  packages/gatsby/src/commands/serve.ts
Labels: topic: render-mode

#35914 fix(gatsby-plugin-sharp): Ensure min 1px height for `BLURRED` placeholder
  packages/gatsby-plugin-sharp/src/__tests__/images/wide-aspect-ratio.png
  packages/gatsby-plugin-sharp/src/__tests__/index.js
  packages/gatsby-plugin-sharp/src/image-data.ts
Labels: topic: media

#36239 chore: update peril settings for starters
  peril.settings.json
  starters/gatsby-starter-wordpress-blog/package.json
Labels: type: maintenance

#36240 MDX v2: e2e tests for fs routing api
  e2e-tests/mdx/cypress/integration/fs-api.js
  e2e-tests/mdx/src/pages/fs-api/{Mdx.fields__slug}.js
Labels: topic: remark/mdx, topic: automation

#36238 MDX v2: fix e2e tests
  e2e-tests/mdx/cypress/integration/frontmatter.js
  e2e-tests/mdx/cypress/integration/fs-api.js
  e2e-tests/mdx/gatsby-browser.js
  e2e-tests/mdx/gatsby-config.js
  e2e-tests/mdx/gatsby-node.js
  e2e-tests/mdx/gatsby-ssr.js
  e2e-tests/mdx/package.json
  e2e-tests/mdx/src/pages/frontmatter-graphql-query.js
  e2e-tests/mdx/src/pages/frontmatter-javascript.mdx
  e2e-tests/mdx/src/pages/frontmatter-js.mdx
  e2e-tests/mdx/src/pages/fs-api/{Mdx.fields__slug}.js
  e2e-tests/mdx/src/pages/list.js
Labels: topic: remark/mdx, topic: automation

#36235 chore: Move packages to deprecated-packages folder
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/.babelrc
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/.gitignore
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/.npmignore
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/CHANGELOG.md
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/README.md
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/index.js
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/package.json
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/src/__tests__/gatsby-node.js
  deprecated-packages/gatsby-plugin-remove-trailing-slashes/src/gatsby-node.js
  packages/gatsby-plugin-netlify/CHANGELOG.md
  packages/gatsby-plugin-netlify/README.md
Labels: type: maintenance

#36009 MDXv2: update example using-mdx
  docs/docs/how-to/routing/mdx.md
  docs/docs/mdx/importing-and-using-components.md
  examples/using-MDX/README.md
  examples/using-MDX/gatsby-config.js
  examples/using-MDX/package.json
  examples/using-MDX/src/components/image.js
  examples/using-MDX/src/images/gatsby-icon.png
  examples/using-MDX/src/pages/chart-info.mdx
  examples/using-MDX/src/pages/index.js
  examples/using-mdx/.prettierignore
  examples/using-mdx/README.md
  examples/using-mdx/content/posts/blog-1.mdx
  examples/using-mdx/content/posts/blog-2.mdx
  examples/using-mdx/content/posts/gatsby-astronaut.png
  examples/using-mdx/gatsby-browser.jsx
  examples/using-mdx/gatsby-config.js
  examples/using-mdx/gatsby-node.js
  examples/using-mdx/gatsby-ssr.jsx
  examples/using-mdx/package.json
  examples/using-mdx/src/components/header.jsx
  examples/using-mdx/src/components/layout.css
  examples/using-mdx/src/components/layout.jsx
  examples/using-mdx/src/components/shortcodes.jsx
  examples/using-mdx/src/pages/404.jsx
  examples/using-mdx/src/pages/chart-info.mdx
  examples/using-mdx/src/pages/index.jsx
  examples/using-mdx/src/templates/posts.jsx
  packages/gatsby-plugin-mdx/src/gatsby-node.ts
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/mdx/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/mdx/output.mjs
Labels: topic: remark/mdx

#36248 fix(gatsby): fix --https option for develop
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/utils/get-ssl-cert.ts
  packages/gatsby/src/utils/start-server.ts
Labels: type: bug

#36244 fix(gatsby): refactor sourceNodes api and add I&C/CFLOW as a codeowner
  CODEOWNERS
  packages/gatsby/src/utils/source-nodes-api-runner.ts
  packages/gatsby/src/utils/source-nodes.ts
Labels: topic: core

#36255 fix(gatsby): add `webhookBody` to `SourceNodesArgs` interface
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#36253 fix(gatsby): move require out of hot function
  packages/gatsby/src/schema/node-model.js
Labels: topic: performance

#36142 feat(gatsby-source-shopify): Add query runtime warning for CI environments
  packages/gatsby-source-shopify/src/create-operations.ts
Labels: topic: source-shopify

#36268 fix(docs): remove outdated docs
  docs/docs/adding-page-transitions.md
  docs/docs/api-files.md
  docs/docs/api-specification.md
  docs/docs/babel-plugin-macros.md
  docs/docs/basic-hardware-software-requirements.md
  docs/docs/building-an-e-commerce-site.md
  docs/docs/conceptual-guide.md
  docs/docs/customization.md
  docs/docs/data-storage-redux.md
  docs/docs/debugging-replace-renderer-api.md
  docs/docs/deploying-to-bip.md
  docs/docs/files-gatsby-looks-for-in-a-plugin.md
  docs/docs/gatsby-internals.md
  docs/docs/gatsby-repl.md
  docs/docs/glossary/decoupled-drupal.md
  docs/docs/glossary/graphql.md
  docs/docs/how-plugins-apis-are-run.md
  docs/docs/how-to/routing/mdx-plugins.md
  docs/docs/loading-plugins-from-your-local-plugins-folder.md
  docs/docs/node-tracking.md
  docs/docs/optimizing-site-performance-with-guessjs.md
  docs/docs/page-creation.md
  docs/docs/page-node-dependencies.md
  docs/docs/performance.md
  docs/docs/preparing-your-environment.md
  docs/docs/processing-payments-with-square.md
  docs/docs/query-behind-the-scenes.md
  docs/docs/query-execution.md
  docs/docs/query-extraction.md
  docs/docs/recipes/sourcing-data.md
  docs/docs/recipes/working-with-plugins.md
  docs/docs/recipes/working-with-themes.md
  docs/docs/schema-root-fields.md
  docs/docs/webpack-and-ssr.md
  docs/docs/working-with-fonts-and-typography.md
Labels: type: documentation
