Repository gatsbyjs/gatsby, pull requests merged in 2022-03, with the labels that each got.

#34946 chore(examples): Update TS example
  examples/using-typescript/.eslintrc.js
  examples/using-typescript/README.md
  examples/using-typescript/gatsby-browser.tsx
  examples/using-typescript/gatsby-config.js
  examples/using-typescript/gatsby-config.ts
  examples/using-typescript/gatsby-ssr.tsx
  examples/using-typescript/package.json
  examples/using-typescript/src/components/layout.tsx
  examples/using-typescript/src/components/source.tsx
  examples/using-typescript/src/declarations.d.ts
  examples/using-typescript/src/pages/404.tsx
  examples/using-typescript/src/pages/index.tsx
  examples/using-typescript/src/utils/typography.d.ts
  examples/using-typescript/src/utils/typography.js
  examples/using-typescript/styles.css
  examples/using-typescript/tsconfig.json
Labels: topic: TypeScript

#34951 fix(gatsby-core-utils): fix caching when using remote-file
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
Labels: topic: core

#34997 chore: Update renovate config for Parcel
  renovate.json5
  scripts/renovate-config-generator.js
Labels: type: maintenance

#35000 chore(examples): Update vanilla-extract
  examples/using-vanilla-extract/README.md
  examples/using-vanilla-extract/gatsby-config.ts
  examples/using-vanilla-extract/package.json
  examples/using-vanilla-extract/tsconfig.json
Labels: type: maintenance, bot: merge on green

#34943 chore(gatsby-parcel-config): stabilize ts compilation parcel output
  packages/gatsby-parcel-config/lib/index.json
  packages/gatsby-parcel-config/package.json
  packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/ts-only-in-local-plugin/plugins/gatsby-plugin-local/gatsby-config.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/ts-only-in-local-plugin/plugins/gatsby-plugin-local/gatsby-node.ts
  yarn.lock
Labels: topic: TypeScript

#34999 chore(docs): 4.9 Release Notes
  docs/docs/how-to/custom-configuration/typescript.md
  docs/docs/reference/release-notes/v4.9/index.md
Labels: type: documentation

#35002 feat(docs): add doc on choosing analytics systems
  docs/docs/conceptual/choosing-analytics-systems.md
Labels: type: documentation

#34825 feat(gatsby): add support for image-cdn
  docs/docs/how-to/testing/unit-testing.md
  e2e-tests/development-runtime/cypress/integration/remote-file/gatsby-plugin-image.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/pages/remote-file.js
  e2e-tests/production-runtime/cypress/integration/remote-file.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/src/pages/remote-file.js
  examples/using-jest/jest.config.js
  integration-tests/gatsby-pipeline/gatsby-node.js
  integration-tests/gatsby-source-wordpress/jest.config.js
  jest.config.js
  package.json
  packages/gatsby-core-utils/src/fetch-remote-file.ts
  packages/gatsby-core-utils/src/remote-file-utils/fetch-file.ts
  packages/gatsby-plugin-manifest/package.json
  packages/gatsby-plugin-utils/.babelrc
  packages/gatsby-plugin-utils/README.md
  packages/gatsby-plugin-utils/package.json
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/__fixtures__/dog-landscape.jpg
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/__fixtures__/dog-portrait.jpg
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/public-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/resize-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/get-remote-file-enums.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/public-url-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/resize-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/utils.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/http-routes.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/index.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/__tests__/gatsby-worker.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/dispatchers.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/gatsby-worker.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/placeholder-handler.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/transform-images.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/types.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/cache.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/get-gatsby-version.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/mime-type-helpers.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/strip-indent.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/url-generator.ts
  packages/gatsby-sharp/.babelrc.js
  packages/gatsby-sharp/package.json
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby/index.d.ts
  packages/gatsby/package.json
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/scripts/output-api-file.js
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/__tests__/fixtures/node-model.js
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/schema/graphql-engine/lmdb-bundling-patch.ts
  packages/gatsby/src/schema/schema-composer.ts
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/__tests__/remote-file-interface.ts
  packages/gatsby/src/schema/types/remote-file-interface.ts
  packages/gatsby/src/utils/start-server.ts
  yarn.lock
Labels: topic: media

#34831 feat(gatsby-source-contentful): enable image-cdn
  e2e-tests/contentful/cypress/integration/gatsby-image-cdn.js
  e2e-tests/contentful/cypress/snapshots/gatsby-image-cdn.js/gatsby-image-cdn-0.snap.png
  e2e-tests/contentful/package.json
  e2e-tests/contentful/src/pages/gatsby-image-cdn.js
  e2e-tests/contentful/src/pages/index.js
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/create-schema-customization.js
  packages/gatsby-source-contentful/src/extend-node-type.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-contentful/src/normalize.js
Labels: topic: source-contentful

#34832 feat(gatsby-source-wordpress): enable image-cdn
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/__tests__/index.js
  integration-tests/gatsby-source-wordpress/docker-compose.yml
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  packages/gatsby-source-wordpress/__tests__/process-node.fixture.js
  packages/gatsby-source-wordpress/__tests__/process-node.test.js
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-source-wordpress/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/models/gatsby-api.ts
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/index.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/type-filters.js
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
  packages/gatsby-source-wordpress/src/steps/image-routes.ts
  packages/gatsby-source-wordpress/src/steps/index.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
  packages/gatsby-source-wordpress/src/utils/gatsby-types.ts
Labels: topic: source-wordpress

#35017 chore(docs): Clarify wording on governance doc
  docs/contributing/gatsby-governance-model.md
Labels: type: documentation

#35024 fix(gatsby-plugin-utils): make sure avif, webp are sorted correctly
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
Labels: bot: merge on green, topic: media

#35026 fix(gatsby): fix pnp for lmdb
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/schema/graphql-engine/lmdb-bundling-patch.ts
Labels: bot: merge on green, topic: core

#35040 chore(docs): typo in typescript documentation
  docs/docs/how-to/custom-configuration/typescript.md
Labels: type: documentation

#35047 fix(gatsby-source-wordpress): default options build integration test
  integration-tests/gatsby-source-wordpress/__tests__/index.js
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/env-browser.js
  integration-tests/gatsby-source-wordpress/test-fns/plugin-options.js
Labels: status: triage needed

#35065 hotfix(gatsby): don't lock lmdb
  packages/gatsby/package.json
  yarn.lock
Labels: topic: core

#35045 chore(docs): Update query-extraction link to relay
  docs/docs/query-extraction.md
Labels: type: documentation

#35009 fix(gatsby-plugin-sharp): Upgrade `probe-image-size` to fix memory leak warning
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-remark-copy-linked-files/package.json
  packages/gatsby-transformer-sharp/package.json
  yarn.lock
Labels: topic: media

#35050 fix(gatsby-transformer-excel): Use `readFile` Buffer
  packages/gatsby-transformer-excel/package.json
  packages/gatsby-transformer-excel/src/gatsby-node.js
  yarn.lock
Labels: topic: plugins

#35051 chore(docs): Add image CDN enablement docs
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: type: documentation

#35071 chore(docs): Fix broken link
  docs/docs/starters.md
Labels: type: documentation

#34816 fix(gatsby): fix issue with decoding URl
  e2e-tests/development-runtime/cypress/integration/navigation/query-string.js
  e2e-tests/development-runtime/src/pages/query-params.js
  e2e-tests/production-runtime/cypress/integration/query-string.js
  e2e-tests/production-runtime/src/pages/query-params.js
  packages/gatsby/cache-dir/find-path.js
Labels: topic: core

#35070 fix(gatsby): Misspelled cacheIdentifier key
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
  packages/gatsby/src/utils/babel-loader.js
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: webpack/babel

#35080 chore: Remove GatsbyConf 2022 banner from README
  README.md
Labels: type: documentation

#35076 fix(gatsby): make sure node-gyp gets replaced
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/schema/graphql-engine/lmdb-bundling-patch.ts
Labels: topic: core

#35043 fix(gatsby-core-utils): multiple requests with different outputdir (#35039)
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
Labels: type: cherry

#35068 feat(gatsby-source-contentful): improve gatsby-plugin-image errors
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/create-schema-customization.js
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-contentful/src/report.js
Labels: bot: merge on green, topic: source-contentful

#35056 chore(docs): Conditionally sourcing files using environment variables
  docs/docs/how-to/performance/improving-build-performance.md
  docs/docs/how-to/sourcing-data/sourcing-from-the-filesystem.md
Labels: type: documentation

#35067 chore(docs): Update query-extraction.md to point to TS file instead of old JS
  docs/docs/query-extraction.md
Labels: type: documentation

#35100 docs(gatsby): Update `query-watcher` to reference TS file
  docs/docs/query-extraction.md
Labels: type: documentation

#35098 fix(gatsby): fix schema printing for gatsby-transformer-json
  packages/gatsby/src/schema/print.ts
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/built-in-types.ts
Labels: topic: GraphQL

#35023 feat(gatsby): Capture number of compiled TS files in Telemetry
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
  packages/gatsby/src/utils/worker/__tests__/config.ts
  packages/gatsby/src/utils/worker/__tests__/datastore.ts
  packages/gatsby/src/utils/worker/__tests__/jobs.ts
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/__tests__/schema.ts
  packages/gatsby/src/utils/worker/__tests__/share-state.ts
Labels: topic: core

#35096 fix(gatsby): null check for context
  packages/gatsby/src/schema/resolvers.ts
Labels: topic: core

#35107 fix(create-gatsby): Update wordpress deps in schema
  packages/create-gatsby/src/questions/cmses.json
Labels: topic: cli

#34925 fix(gatsby): use lmdb for resultHash cache so shared across workers
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/pages.ts.snap
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/reducers/pending-page-data-writes.ts
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green, topic: core

#35119 chore(docs): Fix typos
  docs/docs/how-to/adding-common-features/adding-forms.md
  docs/docs/how-to/performance/improving-build-performance.md
  docs/docs/performance-tracing.md
  docs/docs/reference/release-notes/v2.31/index.md
  docs/docs/reference/release-notes/v3.1/index.md
  docs/docs/reference/release-notes/v3.12/index.md
  docs/docs/reference/release-notes/v3.5/index.md
  docs/docs/reference/release-notes/v4.0/index.md
  docs/docs/reference/release-notes/v4.2/index.md
  docs/docs/reference/release-notes/v4.6/index.md
Labels: type: documentation

#35118 docs(gh-pages): improve separate repository instructions
  docs/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages.md
Labels: type: documentation

#35115 chore(docs): Update query-execution.md
  docs/docs/query-execution.md
Labels: type: documentation

#35124 chore(plugins): Deprecate create client paths plugin
  deprecated-packages/gatsby-plugin-create-client-paths/.babelrc
  deprecated-packages/gatsby-plugin-create-client-paths/.gitignore
  deprecated-packages/gatsby-plugin-create-client-paths/.npmignore
  deprecated-packages/gatsby-plugin-create-client-paths/CHANGELOG.md
  deprecated-packages/gatsby-plugin-create-client-paths/README.md
  deprecated-packages/gatsby-plugin-create-client-paths/index.js
  deprecated-packages/gatsby-plugin-create-client-paths/package.json
  deprecated-packages/gatsby-plugin-create-client-paths/src/__tests__/gatsby-node.js
  deprecated-packages/gatsby-plugin-create-client-paths/src/gatsby-node.js
  packages/gatsby-dev-cli/src/__tests__/watch.js
  renovate.json5
Labels: type: maintenance, topic: plugins

#35074 feat(gatsby-core-utils,gatsby-cli): Allow write to gatsby-config.ts
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/__tests__/handlers/__snapshots__/plugin-add.ts.snap
  packages/gatsby-cli/src/__tests__/handlers/plugin-add.ts
  packages/gatsby-cli/src/handlers/plugin-add-utils.ts
  packages/gatsby-cli/src/handlers/plugin-add.ts
  packages/gatsby-cli/src/handlers/plugin-babel-utils.ts
  packages/gatsby-core-utils/src/__tests__/fixtures/gatsby-config.js
  packages/gatsby-core-utils/src/__tests__/site-metadata.ts
  packages/gatsby-core-utils/src/site-metadata.ts
  packages/gatsby-core-utils/src/utils.ts
  starters/gatsby-starter-minimal-ts/gatsby-config.js
  starters/gatsby-starter-minimal/gatsby-config.js
  yarn.lock
Labels: topic: cli, type: feature or enhancement, topic: TypeScript

#35029 chore(gatsby): add generic to GatsbyFunctionRequest
  docs/docs/reference/functions/getting-started.md
  packages/gatsby/index.d.ts
Labels: topic: TypeScript, topic: DX

#35075 fix(gatsby-plugin-sharp): Handle diff duotone settings
  packages/gatsby-plugin-sharp/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-plugin-sharp/src/__tests__/index.js
  packages/gatsby-plugin-sharp/src/index.js
Labels: topic: media

#35129 chore(docs): update documentation for node-fetch to use CommonJS
  docs/docs/conceptual/data-fetching.md
Labels: type: documentation, bot: merge on green

#35105 chore(docs): Update migration guide to add more info about image resolvers
  docs/docs/reference/graphql-data-layer/schema-customization.md
  docs/docs/reference/release-notes/migrating-from-v3-to-v4.md
Labels: type: documentation

#35134 chore(docs): Clarify TS release doc
  docs/docs/how-to/custom-configuration/typescript.md
  docs/docs/reference/release-notes/v4.9/index.md
Labels: type: documentation

#35139 fix(gatsby-core-utils): move package.json check to try catch
  packages/gatsby-core-utils/src/utils/get-lmdb.ts
Labels: bot: merge on green, topic: core

#33820 feat(gatsby-source-mongodb): Add option name to overwrite node middle…
  packages/gatsby-source-mongodb/README.md
  packages/gatsby-source-mongodb/src/gatsby-node.js
Labels: status: triage needed

#34772 feat(gatsby-source-graphql): upgrade apollo & graphql-tools deps
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
  examples/creating-source-plugins/source-plugin/gatsby-node.js
  examples/creating-source-plugins/source-plugin/package.json
  packages/gatsby-source-graphql/README.md
  packages/gatsby-source-graphql/package.json
  packages/gatsby-source-graphql/src/__tests__/gatsby-node.js
  packages/gatsby-source-graphql/src/batching/__tests__/dataloader-link.js
  packages/gatsby-source-graphql/src/batching/dataloader-link.js
  packages/gatsby-source-graphql/src/gatsby-node.js
  yarn.lock
Labels: topic: source-plugins

#35144 fix(create-gatsby): update deps for cms source plugins
  packages/create-gatsby/src/questions/cmses.json
Labels: topic: cli

#35135 chore(docs): 4.10 Release Notes
  docs/docs/reference/release-notes/v4.10/index.md
Labels: type: documentation

#35153 fix(gatsby-cli): Resolve babel preset ts explicitly
  packages/gatsby-cli/src/handlers/plugin-add-utils.ts
Labels: topic: cli

#35163 chore(docs): Add context to useScrollRestoration usage
  docs/docs/how-to/routing/scroll-restoration.md
Labels: type: documentation

#35162 chore(docs): remove outdated doc
  docs/docs/scaling-issues.md
Labels: type: documentation

#35159 fix(gatsby-plugin-gatsby-cloud): Lowered `INTERACTIONS_BEFORE_FEEDBACK` value to 3
  packages/gatsby-plugin-gatsby-cloud/src/constants.js
Labels: topic: plugins

#35165 fix(gatsby-plugin-utils): Add missing fs-extra dep
  packages/gatsby-plugin-utils/package.json
Labels: bot: merge on green, topic: core

#35156 fix(gatsby-plugin-preact): fix preact alias
  packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
Labels: topic: plugins

#35172 chore(docs): Add Deferred Static Generation to glossary
  docs/docs/glossary.md
Labels: status: triage needed

#35128 feat(starters): Minimal TS starter gatsby-config.ts
  packages/gatsby-cli/src/__tests__/handlers/plugin-add.ts
  starters/gatsby-starter-minimal-ts/gatsby-config.js
  starters/gatsby-starter-minimal-ts/gatsby-config.ts
Labels: type: feature or enhancement

#35184 chore(gatsby-plugin-google-gtag): Update broken link
  packages/gatsby-plugin-google-gtag/README.md
Labels: type: documentation, bot: merge on green

#35154 fix(gatsby): fix eperm when cache getting cleared
  packages/gatsby/package.json
  packages/gatsby/src/services/initialize.ts
  yarn.lock
Labels: type: bug

#35196 fix(gatsby): Improve functions compilation error
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: topic: core

#35116 chore(docs): Move `loadable-components` instructions
  docs/docs/using-client-side-only-packages.md
  packages/gatsby/src/utils/api-node-docs.ts
Labels: type: documentation

#35087 feat(gatsby-plugin-utils): support aspect ratio for Image Service
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/resize-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/utils.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/types.ts
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
Labels: bot: merge on green, topic: media

#35205 refactor: replace deprecated String.prototype.substr()
  examples/using-remark/src/utils/typography.js
  packages/gatsby-cli/src/reporter/prepare-stack-trace.ts
  packages/gatsby-graphiql-explorer/src/app/app.js
  packages/gatsby-link/src/parse-path.js
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-sharp/src/process-file.js
  packages/gatsby-remark-embed-snippet/src/index.js
  packages/gatsby-transformer-react-docgen/src/doclets.js
  packages/gatsby/src/bootstrap/redirects-writer.ts
  packages/gatsby/src/cache/cache-fs.ts
  packages/gatsby/src/utils/webpack.config.js
  scripts/gatsby-changelog-generator/generate.js
  scripts/gatsby-changelog-generator/render.js
  scripts/i18n/sync.js
Labels: type: maintenance

#35206 chore: fix dependencies
  packages/gatsby-plugin-benchmark-reporting/package.json
  packages/gatsby-transformer-sqip/package.json
Labels: type: maintenance, bot: merge on green

#35218 chore(docs): Update prismic source graphql tutorial docs
  docs/tutorial/prismic-source-graphql-tutorial.md
Labels: type: documentation

#35208 chore(README): Add quickstart & reorder value props
  README.md
  packages/gatsby/README.md
Labels: type: documentation

#35240 chore(docs): add conditions to createRedirect api docs
  packages/gatsby/src/redux/actions/public.js
Labels: type: documentation

#35231 chore(docs): Release Notes for v4.11
  docs/docs/reference/release-notes/v4.11/index.md
Labels: type: documentation

#35249 docs: update react 18 notes
  docs/docs/reference/release-notes/v4.11/index.md
Labels: status: triage needed

#35246 fix(gatsby-plugin-sharp,gatsby-core-utils): windows quirks
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
  packages/gatsby-plugin-sharp/src/__tests__/trace-svg.js
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-plugin-sharp/src/gatsby-worker.js
  packages/gatsby-plugin-sharp/src/index.js
  packages/gatsby-plugin-sharp/src/process-file.js
  packages/gatsby-plugin-sharp/src/trace-svg.js
Labels: type: maintenance

#35251 chore(gatsby-source-drupal): Delete .Rhistory
  packages/gatsby-source-drupal/.Rhistory
Labels: status: triage needed

#35243 fix(gatsby-source-filesystem): use correct hash when using createFileNodeFromBuffer
  packages/gatsby-source-filesystem/README.md
  packages/gatsby-source-filesystem/src/__tests__/create-file-node-from-buffer.js
  packages/gatsby-source-filesystem/src/create-file-node-from-buffer.js
Labels: status: triage needed

#35257 chore(docs): Add Typesense as a search engine option
  docs/docs/how-to/adding-common-features/adding-search.md
Labels: type: documentation

#35256 chore(docs): Add note to tailwind doc
  docs/docs/how-to/styling/tailwind-css.md
Labels: type: documentation

#35263 fix(gatsby): use gatsby root instead of process.cwd
  packages/gatsby/src/utils/__tests__/cache.ts
  packages/gatsby/src/utils/cache.ts
Labels: type: maintenance

#35274 fix(gatsby-core-utils): fix exports map
  packages/gatsby-core-utils/package.json
Labels: type: maintenance, bot: merge on green

#35275 chore(docs): Fix Meilisearch spelling
  docs/docs/how-to/adding-common-features/adding-search.md
Labels: type: documentation
