Repository gatsbyjs/gatsby, pull requests merged in 2022-04, with the labels that each got.

#35069 chore(babel-preset-gatsby): Updated README to include babel presets
  docs/docs/reference/config-files/gatsby-config.md
  packages/babel-preset-gatsby/README.md
Labels: type: documentation

#35271 fix(gatsby): fix intermittent wrong sort results when sorting on materialized field
  packages/gatsby/src/datastore/in-memory/indexing.ts
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
Labels: topic: GraphQL, topic: core

#35314 chore(docs): Update config files TS refs
  docs/docs/api-files.md
  docs/docs/glossary.md
  docs/docs/how-to/custom-configuration/typescript.md
  docs/docs/reference/config-files/gatsby-browser.md
  docs/docs/reference/config-files/gatsby-config.md
  docs/docs/reference/config-files/gatsby-node.md
  docs/docs/reference/config-files/gatsby-ssr.md
  docs/docs/reference/gatsby-project-structure.md
Labels: type: documentation

#35272 fix(create-gatsby): fix missing site title
  packages/create-gatsby/src/__tests__/run.ts
  packages/create-gatsby/src/index.ts
Labels: topic: cli

#35319 fix(gatsby): React 18 Hydration with offline plugin
  packages/gatsby/cache-dir/production-app.js
Labels: topic: core, topic: plugins-PWA

#35334 chore(docs): Update Node installation instructions
  docs/docs/how-to/local-development/gatsby-on-linux.md
  docs/docs/tutorial/part-0/index.mdx
Labels: type: documentation

#35324 fix(gatsby-source-wordpress): logic for matching image nodes
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
Labels: topic: source-wordpress

#35349 chore(docs): typo in 4.11 release notes
  docs/docs/reference/release-notes/v4.11/index.md
Labels: type: documentation

#35320 chore: e2e/integration with React 17 & 18
  .circleci/config.yml
  e2e-tests/contentful/package.json
  e2e-tests/development-runtime/package.json
  e2e-tests/gatsby-image/package.json
  e2e-tests/gatsby-static-image/package.json
  e2e-tests/mdx-less-babel/package.json
  e2e-tests/mdx/package.json
  e2e-tests/path-prefix/package.json
  e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/utils/instrument-page.js
  e2e-tests/themes/development-runtime/package.json
  e2e-tests/themes/gatsby-theme-about/package.json
  e2e-tests/themes/production-runtime/package.json
  integration-tests/artifacts/package.json
  integration-tests/cache-resilience/package.json
  integration-tests/functions/package.json
  integration-tests/images/package.json
  integration-tests/long-term-caching/package.json
  integration-tests/ssr/package.json
  integration-tests/structured-logging/package.json
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js
  scripts/upgrade-react.js
Labels: type: maintenance, topic: automation

#35336 fix(gatsby): fix DSG special char 404 issue
  e2e-tests/production-runtime/cypress/integration/1-production.js
  e2e-tests/production-runtime/gatsby-node.js
  e2e-tests/production-runtime/src/pages/index.js
  packages/gatsby/src/utils/find-page-by-path.ts
Labels: topic: core, topic: render-mode

#35346 fix(gatsby): fix decoding issue in SSR
  e2e-tests/development-runtime/cypress/integration/ssr.js
  e2e-tests/production-runtime/cypress/integration/ssr.js
  packages/gatsby/src/utils/page-ssr-module/entry.ts
Labels: topic: core, topic: render-mode

#35367 fix(gatsby): add missing `ownerNodeId` prop to Page type
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#35375 chore: renovate - add cypress
  renovate.json5
  scripts/renovate-config-generator.js
Labels: type: maintenance, topic: automation

#35371 chore(docs): Update `.gitlab-ci.yml` deploy
  docs/docs/deploying-to-gitlab-pages.md
Labels: type: documentation

#35399 fix(gatsby-source-wordpress): fix integration tests
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/docker/seed/backup.sql
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  packages/gatsby-source-wordpress/docs/tests.md
Labels: status: triage needed

#35376 chore(docs): Release Notes for 4.12
  docs/docs/reference/release-notes/v4.12/index.md
Labels: type: documentation

#35365 fix(gatsby-plugin-netlify-cms): react18-compatible require resolve
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
Labels: bot: merge on green, topic: plugins

#35359 fix(gatsby): limit node manifest creation limit
  integration-tests/node-manifest/__tests__/create-node-manifest.test.js
  integration-tests/node-manifest/gatsby-node.js
  integration-tests/node-manifest/package.json
  integration-tests/node-manifest/utils/get-gatsby-process.js
  packages/gatsby/src/utils/node-manifest.ts
Labels: topic: core

#35423 fix(gatsby-source-wordpress): localFile id
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/type-filters.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
Labels: topic: source-wordpress

#35416 test(gatsby-script): e2e tests
  .circleci/config.yml
  e2e-tests/gatsby-script/.gitignore
  e2e-tests/gatsby-script/LICENSE
  e2e-tests/gatsby-script/README.md
  e2e-tests/gatsby-script/cypress.json
  e2e-tests/gatsby-script/cypress/fixtures/example.json
  e2e-tests/gatsby-script/cypress/integration/strategies.ts
  e2e-tests/gatsby-script/cypress/plugins/index.ts
  e2e-tests/gatsby-script/cypress/support/index.ts
  e2e-tests/gatsby-script/cypress/tsconfig.json
  e2e-tests/gatsby-script/gatsby-browser.ts
  e2e-tests/gatsby-script/gatsby-config.ts
  e2e-tests/gatsby-script/gatsby-ssr.ts
  e2e-tests/gatsby-script/package.json
  e2e-tests/gatsby-script/resource-records.ts
  e2e-tests/gatsby-script/scripts.ts
  e2e-tests/gatsby-script/src/components/script-resource-records.tsx
  e2e-tests/gatsby-script/src/hooks/use-occupy-main-thread.ts
  e2e-tests/gatsby-script/src/pages/404.tsx
  e2e-tests/gatsby-script/src/pages/index.tsx
  e2e-tests/gatsby-script/src/styles/global.css
  e2e-tests/gatsby-script/tsconfig.json
  packages/gatsby-script/package.json
Labels: topic: performance, topic: frontend

#35443 feat(gatsby-script): Inline scripts
  e2e-tests/gatsby-script/README.md
  e2e-tests/gatsby-script/cypress/integration/inline-scripts.ts
  e2e-tests/gatsby-script/cypress/integration/scripts-with-sources.ts
  e2e-tests/gatsby-script/cypress/integration/strategies.ts
  e2e-tests/gatsby-script/cypress/support/index.ts
  e2e-tests/gatsby-script/gatsby-browser.tsx
  e2e-tests/gatsby-script/gatsby-ssr.tsx
  e2e-tests/gatsby-script/package.json
  e2e-tests/gatsby-script/records.ts
  e2e-tests/gatsby-script/resource-records.ts
  e2e-tests/gatsby-script/scripts.ts
  e2e-tests/gatsby-script/src/components/script-mark-records.tsx
  e2e-tests/gatsby-script/src/components/script-resource-records.tsx
  e2e-tests/gatsby-script/src/pages/index.tsx
  e2e-tests/gatsby-script/src/utils/trim.ts
  packages/gatsby-script/README.md
  packages/gatsby-script/src/__tests__/gatsby-script.tsx
  packages/gatsby-script/src/gatsby-script.tsx
Labels: topic: performance, type: feature or enhancement, topic: frontend

#35438 chore(docs): Typo on "Adding forms"
  docs/docs/how-to/adding-common-features/adding-forms.md
Labels: type: documentation

#35444 fix(gatsby-link): modify relative links based on trailing slash option
  e2e-tests/trailing-slash/cypress/integration/always.js
  e2e-tests/trailing-slash/src/pages/index.js
  packages/gatsby-link/src/rewrite-link-path.js
Labels: topic: frontend

#35425 fix(gatsby-transformer-screenshot): finished migration from better-queue to fastq
  packages/gatsby-transformer-screenshot/src/gatsby-node.js
Labels: topic: plugins

#35451 docs(gatsby): image cdn author docs tweak
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: status: triage needed

#35455 chore(gatsby-source-wordpress): Fix typo in `presets[].options`
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
Labels: type: documentation, topic: source-wordpress, topic: source-plugins

#35328 feat(gatsby-plugin-utils): enable tracedsvg
  e2e-tests/development-runtime/cypress/integration/remote-file/gatsby-plugin-image.js
  e2e-tests/development-runtime/src/pages/remote-file.js
  e2e-tests/production-runtime/cypress/integration/remote-file.js
  e2e-tests/production-runtime/src/pages/remote-file.js
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/trace-svg.js
  packages/gatsby-plugin-utils/package.json
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/get-remote-file-enums.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/placeholder-handler.ts
  packages/gatsby-remark-images/package.json
  packages/gatsby-remark-images/src/__tests__/gatsby-node.js
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/gatsby-node.js
  packages/gatsby-remark-images/src/index.js
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby-transformer-sharp/src/types.ts
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  yarn.lock
Labels: topic: media

#35370 feat(gatsby-source-wordpress): bring back defaults before image_cdn
  integration-tests/gatsby-source-wordpress/__tests__/index.js
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
  packages/gatsby-source-wordpress/__tests__/process-node.test.js
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
Labels: topic: source-wordpress, topic: source-plugins

#35447 fix(gatsby-dev-cli): use package name not directory name
  packages/gatsby-dev-cli/src/__tests__/watch.js
  packages/gatsby-dev-cli/src/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/publish-package.js
  packages/gatsby-dev-cli/src/utils/__tests__/get-dependant-packages.js
  packages/gatsby-dev-cli/src/utils/__tests__/traverse-package-deps.js
  packages/gatsby-dev-cli/src/utils/check-deps-changes.js
  packages/gatsby-dev-cli/src/utils/get-monorepo-package-json-path.js
  packages/gatsby-dev-cli/src/utils/traverse-package-deps.js
  packages/gatsby-dev-cli/src/watch.js
Labels: type: maintenance

#35462 chore(docs):Update Link URL
  docs/docs/how-to/previews-deploys-hosting/deploying-to-s3-cloudfront.md
Labels: type: documentation

#35464 feat(gatsby-script): On load callback, cache
  e2e-tests/gatsby-script/cypress/integration/inline-scripts.ts
  e2e-tests/gatsby-script/cypress/integration/scripts-with-sources.ts
  e2e-tests/gatsby-script/cypress/support/index.ts
  e2e-tests/gatsby-script/scripts.ts
  e2e-tests/gatsby-script/src/components/script-mark-records.tsx
  e2e-tests/gatsby-script/src/components/script-resource-records.tsx
  e2e-tests/gatsby-script/src/pages/index.tsx
  e2e-tests/gatsby-script/src/pages/inline-scripts.tsx
  e2e-tests/gatsby-script/src/pages/scripts-with-sources.tsx
  e2e-tests/gatsby-script/src/utils/on-load.ts
  packages/gatsby-script/.eslintrc.yaml
  packages/gatsby-script/src/__tests__/gatsby-script.tsx
  packages/gatsby-script/src/gatsby-script.tsx
Labels: topic: performance, type: feature or enhancement, topic: frontend

#35466 feat(gatsby-script): On error callback
  e2e-tests/gatsby-script/cypress/integration/inline-scripts.ts
  e2e-tests/gatsby-script/cypress/integration/scripts-with-sources.ts
  e2e-tests/gatsby-script/src/pages/index.tsx
  e2e-tests/gatsby-script/src/pages/inline-scripts.tsx
  e2e-tests/gatsby-script/src/pages/scripts-with-sources.tsx
  e2e-tests/gatsby-script/src/utils/callbacks.ts
  e2e-tests/gatsby-script/src/utils/on-load.ts
  packages/gatsby-script/src/gatsby-script.tsx
Labels: topic: performance, type: feature or enhancement, topic: frontend

#35244 fix(gatsby-source-contentful): Prevent null pointer exception
  packages/gatsby-source-contentful/src/__fixtures__/unpublished-fields-delivery.js
  packages/gatsby-source-contentful/src/__fixtures__/unpublished-fields-preview.js
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/normalize.js
Labels: bot: merge on green, topic: source-contentful

#35381 fix(gatsby-plugin-preload-fonts): defer checking for write access
  packages/gatsby-plugin-preload-fonts/src/__tests__/cache.test.js
  packages/gatsby-plugin-preload-fonts/src/prepare/cache.js
Labels: bot: merge on green, topic: frontend

#35265 feat(gatsby-source-drupal): Image CDN support
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/normalize.js
  packages/gatsby-source-drupal/src/utils.js
Labels: topic: media, topic: source-drupal, topic: source-plugins

#35248 test: fix pipeline test
  e2e-tests/production-runtime/cypress/integration/compilation-hash.js
  integration-tests/gatsby-cli/__tests__/develop.js
  integration-tests/gatsby-cli/package.json
  integration-tests/gatsby-cli/test-helpers/invoke-cli.js
  integration-tests/gatsby-pipeline/__tests__/fetch-remote-file/index.js
  integration-tests/gatsby-pipeline/__tests__/lazy-image-build/develop.js
  integration-tests/gatsby-pipeline/package.json
  integration-tests/gatsby-pipeline/utils/create-devserver.js
Labels: type: maintenance

#35473 chore(docs): Update version support page
  docs/docs/reference/release-notes/gatsby-version-support.md
Labels: type: documentation

#35470 feat(gatsby-source-drupal): image cdn tests
  packages/gatsby-source-drupal/src/__tests__/fixtures/file.json
  packages/gatsby-source-drupal/src/__tests__/index.js
Labels: status: triage needed

#35465 chore(docs): Add note about optimizing GitHub publish
  docs/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages.md
Labels: type: documentation

#35474 chore(docs): Corrected the version end dates
  docs/docs/reference/release-notes/gatsby-version-support.md
Labels: type: documentation

#35478 fix(gatsby): Improve warning when a source plugin doesn't create a node
  packages/gatsby/src/utils/source-nodes.ts
Labels: topic: core

#35408 perf(gatsby,gatsby-plugin-gatsby-cloud): prioritize content/asset fetching early, drop script preloads so js doesn't compete with assets
  e2e-tests/path-prefix/cypress/integration/asset-prefix.js
  e2e-tests/production-runtime/cypress/integration/preload.js
  e2e-tests/production-runtime/cypress/integration/scripts.js
  integration-tests/artifacts/__tests__/index.js
  integration-tests/artifacts/gatsby-browser.js
  integration-tests/artifacts/src/components/magic-comments/app-prefetch.js
  integration-tests/artifacts/src/components/magic-comments/app-preload.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/build-headers-program.js.snap
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
  packages/gatsby/cache-dir/__tests__/__snapshots__/static-entry.js.snap
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/src/utils/client-assets-for-template.ts
Labels: topic: frontend

#35486 chore(starters): Update `tsconfig.json`
  starters/gatsby-starter-minimal-ts/tsconfig.json
Labels: topic: DX

#35493 chore(docs): Release notes for 4.13
  docs/docs/reference/release-notes/v4.13/index.md
Labels: type: documentation

#35496 chore(docs): Release notes typo
  docs/docs/reference/release-notes/v4.13/index.md
Labels: type: documentation

#35497 chore(docs): remove git.io urls
  docs/docs/how-to/local-development/gatsby-on-linux.md
  packages/gatsby-transformer-excel/README.md
Labels: type: documentation

#35475 fix(gatsby-source-drupal): Image CDN fixes
  packages/gatsby-source-drupal/src/normalize.js
Labels: topic: source-drupal, topic: source-plugins

#35204 feat(gatsby-source-contentful): Add `contentTypeFilter`
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/create-schema-customization.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/plugin-options.js
  packages/gatsby-source-contentful/src/report.js
Labels: status: needs core review, topic: source-contentful

#35485 feat(gatsby-plugin-gatsby-cloud): Remove X-Frame-Options: DENY for preview
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/build-headers-program.js.snap
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/constants.js
Labels: topic: plugins

#35477 feat(starters): Update default starter
  starters/default/package.json
  starters/default/src/components/header.js
  starters/default/src/components/index.module.css
  starters/default/src/components/layout.css
  starters/default/src/components/layout.js
  starters/default/src/components/seo.js
  starters/default/src/images/example.png
  starters/default/src/images/gatsby-astronaut.png
  starters/default/src/pages/index.js
  starters/default/src/pages/using-ssr.js
  starters/default/src/pages/using-typescript.tsx
  starters/default/src/templates/using-dsg.js
Labels: topic: DX

#35494 fix(gatsby-plugin-gatsby-cloud): apply caching headers to all produced assets
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/__snapshots__/build-headers-program.js.snap
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/build-headers-program.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
Labels: topic: plugins

#35323 feat(gatsby-source-drupal): Persist backreference data individually in cache so cheaper to get/set
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/utils.js
Labels: topic: source-drupal, type: feature or enhancement, topic: source-plugins

#35503 fix(gatsby-core-utils): fix Source and destination must not be the same
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
Labels: topic: source-plugins

#35513 fix(gatsby): wait for worker jobs to complete
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/jobs/worker-messaging.ts
Labels: topic: core

#35393 feat(gatsby): api functions config
  integration-tests/functions/src/api/config/body-parser-json-limit.ts
  integration-tests/functions/src/api/config/body-parser-json-type.js
  integration-tests/functions/src/api/config/body-parser-raw-limit.js
  integration-tests/functions/src/api/config/body-parser-raw-type.js
  integration-tests/functions/src/api/config/body-parser-text-limit.js
  integration-tests/functions/src/api/config/body-parser-text-type.js
  integration-tests/functions/src/api/config/body-parser-urlencoded-limit.js
  integration-tests/functions/src/api/config/body-parser-urlencoded-type.js
  integration-tests/functions/src/api/config/defaults.js
  integration-tests/functions/src/api/function-throw.js
  integration-tests/functions/src/api/no-function-export.js
  integration-tests/functions/test-helpers.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/functions/__tests__/config.ts
  packages/gatsby/src/internal-plugins/functions/config.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
  packages/gatsby/src/internal-plugins/functions/middleware.ts
Labels: topic: core

#35533 fix(gatsby-source-wordpress): Prevent throwing errors when item is undefined
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/transform-union.js
Labels: topic: source-wordpress
