Repository gatsbyjs/gatsby, pull requests merged in 2022-10, with the labels that each got.

#36714 chore(tests): setup circleci to run unit tests againt v5
  .circleci/config.yml
  packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js
  packages/babel-preset-gatsby-package/lib/__tests__/__snapshots__/index.js.snap
  packages/babel-preset-gatsby-package/lib/__tests__/index.js
  packages/gatsby-cli/src/__tests__/index.ts
  packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/query/__tests__/file-parser.js
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-schema.js
  packages/gatsby/src/schema/__tests__/kitchen-sink.js
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/types/sort.ts
  packages/gatsby/src/utils/__tests__/browserslist.js
  packages/gatsby/src/utils/parcel/__tests__/__snapshots__/compile-gatsby-files.ts.snap
  packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
Labels: type: maintenance, topic: automation

#36702 chore(docs): Update storybook main.js examples to be consistant
  docs/docs/how-to/testing/visual-testing-with-storybook.md
Labels: type: documentation

#36731 chore: Update old placehold.it URLs
  examples/using-redux-w-interaction-code-splitting/src/redux/data/dummy.json
  examples/using-redux-w-page-code-splitting/src/redux/data/dummy.json
  starters/blog/content/blog/hello-world/index.md
Labels: type: maintenance

#36738 chore(v5): insert datetime string as postfix in version when releasing v5 canaries
  scripts/release-next-major.js
Labels: type: maintenance

#36739 fix(gatsby): Don't fail build on missing gatsby-plugin-image for Partial Hydration
  packages/gatsby/src/commands/build-html.ts
Labels: topic: core

#36677 fix(gatsby): create abstraction around use of createServerContext
  packages/gatsby/cache-dir/context-utils.js
  packages/gatsby/cache-dir/gatsby-browser-entry.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/cache-dir/static-query.js
  packages/gatsby/src/utils/worker/child/render-html.ts
  patches/v5/3-remove-static-query-component.patch
Labels: topic: core

#36749 fix(partial-hydration): move client components to separate chunks
  packages/gatsby/src/utils/gatsby-webpack-stats-extractor.ts
  packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts
Labels: topic: frontend

#36741 chore(docs): Update tutorial part 5 with a better fitting screenshot
  docs/docs/tutorial/part-5/blog-page-with-excerpt-posts.png
  docs/docs/tutorial/part-5/blog-page-with-full-posts.png
  docs/docs/tutorial/part-5/index.mdx
Labels: type: documentation

#36753 chore: v5 TS Types Updates
  patches/v5/3-remove-static-query-component.patch
  patches/v5/5-slices-public-ts-types.patch
Labels: topic: TypeScript

#36694 chore(docs): Slices API Reference Doc
  docs/docs/reference/built-in-components/gatsby-slice.md
Labels: type: documentation

#36721 chore(docs): Slices API Technical Docs
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/actions/restricted.ts
Labels: type: documentation

#36690 chore(gatsby-plugin-sitemap): Document `excludes` glob matching
  packages/gatsby-plugin-sitemap/README.md
Labels: type: documentation

#36773 fix: define process.env.GATSBY_SLICE so produced engines use conditional slices paths
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
Labels: topic: core, topic: render-mode

#36771 fix(gatsby): cache clear when upgrading from version without slices support cache
  packages/gatsby/src/redux/reducers/html.ts
Labels: topic: core

#36766 fix(gatsby-page-utils): path creation on windows filesystem
  packages/gatsby-page-utils/src/__tests__/create-path.ts
  packages/gatsby-page-utils/src/create-path.ts
Labels: topic: core

#36780 fix(gatsby-codemods): fix spawning jscodeshift process
  packages/gatsby-codemods/src/bin/__tests__/gatsby-codemods-test.js
  packages/gatsby-codemods/src/bin/cli.js
Labels: topic: automation

#36784 chore(gatsby): Deprecate static query component
  packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js
  packages/babel-plugin-remove-graphql-queries/src/index.ts
  packages/gatsby/cache-dir/static-query.js
  packages/gatsby/src/query/__tests__/file-parser.js
  packages/gatsby/src/query/file-parser.js
  patches/v5/3-remove-static-query-component.patch
  patches/v5/3-upgrade-reach-router.patch
  patches/v5/4-slices-api.patch
Labels: topic: core

#36779 fix(gatsby): support slices containing static queries during SSR/DSG
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/page-ssr-module/entry.ts
Labels: topic: core

#36793 chore: Create apply patches script
  scripts/apply-patches.js
Labels: type: maintenance

#36786 chore(gatsby): add types for SliceComponentProps, rename SliceProps to SlicePlaceholderProps, add jsdocs for those types
  patches/v5/4-slices-api.patch
Labels: topic: TypeScript

#36795 chore(gatsby-codemods): Add `sort-and-aggr-graphql` to README
  packages/gatsby-codemods/README.md
Labels: type: documentation

#36800 fix: add more meaningful error message when nested slices are used
  packages/gatsby/cache-dir/slice.js
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: core

#36807 chore(docs): Update v4 to v5 migration to use `next`
  docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
Labels: type: documentation

#36803 feat(gatsby): Support more syntax for Slices props
  packages/gatsby/package.json
  packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/query/__tests__/file-parser.js
  packages/gatsby/src/query/file-parser.js
  packages/gatsby/src/utils/babel/find-slices.ts
Labels: topic: core

#36801 feat(gatsby,gatsby-cli): Slice component validation
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/redux/__tests__/__snapshots__/pages.ts.snap
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/actions/restricted.ts
  packages/gatsby/src/utils/__tests__/fixtures/empty.js
  packages/gatsby/src/utils/__tests__/fixtures/has-default-export-2.js
  packages/gatsby/src/utils/__tests__/fixtures/has-default-export.js
  packages/gatsby/src/utils/__tests__/fixtures/no-default-export.js
  packages/gatsby/src/utils/__tests__/validate-component.ts
  packages/gatsby/src/utils/validate-component.ts
  packages/gatsby/src/utils/validate-page-component.ts
Labels: topic: core

#36812 BREAKING(gatsby-plugin-sitemap): Change `output` default to `/`
  docs/docs/how-to/adding-common-features/creating-a-sitemap.md
  docs/docs/how-to/plugins-and-themes/using-a-plugin-in-your-site.md
  packages/gatsby-plugin-sitemap/README.md
  packages/gatsby-plugin-sitemap/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sitemap/src/__tests__/options-validation.js
  packages/gatsby-plugin-sitemap/src/options-validation.js
Labels: topic: plugins

#36651 chore(docs): added Dialoguewise to headless cms list
  docs/docs/how-to/sourcing-data/headless-cms.md
Labels: type: documentation

#36821 docs(v5): Unified page props
  docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
Labels: type: documentation

#36822 feat(gatsby,gatsby-cli): Slice HTML rendering error handling
  integration-tests/gatsby-cli/__tests__/build-ssr-errors.js
  packages/gatsby-cli/src/reporter/__tests__/__snapshots__/index.ts.snap
  packages/gatsby-cli/src/reporter/__tests__/index.ts
  packages/gatsby-cli/src/structured-errors/__tests__/construct-error.ts
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/utils/__tests__/extract-undefined-global.ts
  packages/gatsby/src/utils/extract-undefined-global.ts
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: topic: core

#36820 chore(docs): TypeScript and Gatsby: add info for CSS Modules
  docs/docs/how-to/custom-configuration/typescript.md
Labels: type: documentation

#36818 chore(docs): Tutorial Part 2 - add exports and imports for component example
  docs/docs/tutorial/part-2/index.mdx
Labels: type: documentation

#36815 chore: Revert "responselike" resolutions
  .circleci/config.yml
  e2e-tests/contentful/package.json
  e2e-tests/development-runtime/package.json
  e2e-tests/mdx/package.json
  e2e-tests/path-prefix/package.json
  e2e-tests/production-runtime/package.json
  e2e-tests/themes/package.json
  e2e-tests/trailing-slash/package.json
  e2e-tests/visual-regression/package.json
  integration-tests/artifacts/package.json
  integration-tests/cache-resilience/package.json
  integration-tests/functions/package.json
  integration-tests/gatsby-cli/package.json
  integration-tests/gatsby-pipeline/package.json
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/head-function-export/package.json
  integration-tests/images/package.json
  integration-tests/long-term-caching/package.json
  integration-tests/node-manifest/package.json
  integration-tests/ssr/package.json
  integration-tests/structured-logging/package.json
Labels: topic: automation

#36814 chore(gatsby-plugin-typescript): Remove obsolete `onCreateWebpackConfig`
  packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-typescript/src/gatsby-node.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
Labels: topic: TypeScript

#36826 chore(docs): Slices docs updates + slice queries
  docs/docs/how-to/performance/using-slices.md
  docs/docs/reference/built-in-components/gatsby-slice.md
  docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
Labels: type: documentation

#36839 fix(gatsby-plugin-gatsby-cloud): Re-add constant LINK_REGEX
  packages/gatsby-plugin-gatsby-cloud/src/constants.js
Labels: topic: plugins

#36838 chore(gatsby-core-utils): Update README with correct cpuCoreCount args
  packages/gatsby-core-utils/README.md
Labels: type: documentation

#36434 chore(gatsby): upgrade latest-version
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/compiler-flags/options.js
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/keep-dynamic-import/default/input.js
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/keep-dynamic-import/default/output.js
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/keep-dynamic-import/options.js
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/keep-dynamic-import/with-override/input.js
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/keep-dynamic-import/with-override/output.js
  packages/babel-preset-gatsby-package/lib/__tests__/plugins.js
  packages/babel-preset-gatsby-package/lib/babel-transform-mark-to-keep-dynamic-import.js
  packages/babel-preset-gatsby-package/lib/index.js
  packages/gatsby/babel.config.js
  packages/gatsby/package.json
  packages/gatsby/src/utils/feedback.ts
  yarn.lock
Labels: type: maintenance

#36541 feat: GraphiQL v2
  e2e-tests/development-runtime/cypress/integration/functionality/graphql-endpoint.js
  e2e-tests/development-runtime/cypress/integration/functionality/implicit-fragments.js
  e2e-tests/development-runtime/package.json
  packages/gatsby-cli/package.json
  packages/gatsby-graphiql-explorer/.gitignore
  packages/gatsby-graphiql-explorer/.npmignore
  packages/gatsby-graphiql-explorer/README.md
  packages/gatsby-graphiql-explorer/assets/gatsby-graphiql-explorer.png
  packages/gatsby-graphiql-explorer/index.js
  packages/gatsby-graphiql-explorer/package.json
  packages/gatsby-graphiql-explorer/src/app.css
  packages/gatsby-graphiql-explorer/src/app.jsx
  packages/gatsby-graphiql-explorer/src/app/__tests__/snippets.js
  packages/gatsby-graphiql-explorer/src/app/app.css
  packages/gatsby-graphiql-explorer/src/app/app.js
  packages/gatsby-graphiql-explorer/src/code-exporter/code-exporter.css
  packages/gatsby-graphiql-explorer/src/code-exporter/plugin.jsx
  packages/gatsby-graphiql-explorer/src/code-exporter/snippets.js
  packages/gatsby-graphiql-explorer/src/constants.js
  packages/gatsby-graphiql-explorer/src/index.html.ejs
  packages/gatsby-graphiql-explorer/src/index.js
  packages/gatsby-graphiql-explorer/src/logo.jsx
  packages/gatsby-graphiql-explorer/src/toolbar.jsx
  packages/gatsby-graphiql-explorer/src/utils.js
  packages/gatsby-graphiql-explorer/src/webpack.config.js
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-typography/package.json
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/rich-text.js.snap
  packages/gatsby/package.json
  yarn.lock
Labels: topic: DX

#36367 fix(gatsby-cli): Remove `update-notifier`
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/index.ts
  yarn.lock
Labels: type: maintenance, topic: cli

#36810 chore(gatsby): Remove LOCKED_IN feature flags
  .circleci/config.yml
  benchmarks/query-filters-sort/gatsby-config.js
  docs/docs/how-to/local-development/debugging-missing-data.md
  e2e-tests/development-runtime/package.json
  integration-tests/gatsby-cli/__tests__/build.js
  integration-tests/node-manifest/package.json
  packages/gatsby/cache-dir/app.js
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/src/bootstrap/index.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/datastore/datastore.ts
  packages/gatsby/src/datastore/index.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/persist.ts
  packages/gatsby/src/redux/reducers/queries.ts
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/__tests__/run-query.js
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/services/calculate-dirty-queries.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/services/run-page-queries.ts
  packages/gatsby/src/services/run-static-queries.ts
  packages/gatsby/src/utils/__tests__/cache-lmdb.ts
  packages/gatsby/src/utils/__tests__/get-page-data.ts
  packages/gatsby/src/utils/__tests__/page-data.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/get-cache.ts
  packages/gatsby/src/utils/loading-indicator.ts
  packages/gatsby/src/utils/node-manifest.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/websocket-manager.ts
  packages/gatsby/src/utils/worker/__tests__/datastore.ts
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/__tests__/schema.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/jest-helpers.ts
Labels: topic: core

#36837 chore(docs): GraphiQL v2
  docs/docs/graphql-reference.md
  docs/docs/how-to/adding-common-features/adding-comments.md
  docs/docs/how-to/images-and-media/preprocessing-external-images.md
  docs/docs/how-to/querying-data/page-query.md
  docs/docs/how-to/querying-data/running-queries-with-graphiql.md
  docs/docs/how-to/sourcing-data/sourcing-from-prismic.md
  docs/docs/how-to/sourcing-data/sourcing-from-the-filesystem.md
  docs/docs/images/allfile-query.png
  docs/docs/images/disqus-logo.svg
  docs/docs/images/filesystem-autocomplete.png
  docs/docs/images/filesystem-query.png
  docs/docs/images/graphcms-query.png
  docs/docs/images/graphcms-schema.png
  docs/docs/images/graphiql-docs.png
  docs/docs/images/graphiql-filesystem.png
  docs/docs/images/graphiql-overview.png
  docs/docs/images/playground-schema.png
  docs/docs/images/prismic-categories-query.jpg
  docs/docs/images/prismic-index-query.jpg
  docs/docs/images/recipe-sourcing-contentful-graphql.png
  docs/docs/images/remote-file-node-graphiql-preview.png
  docs/docs/images/why-gql-playground.png
  docs/docs/reference/graphql-data-layer/schema-customization.md
  docs/docs/sourcing-from-graphcms.md
  docs/docs/tutorial/part-4/graphiql-explorer.png
  docs/docs/tutorial/part-4/graphiql.png
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-6/graphiql-with-query-variables.png
  docs/docs/using-graphql-playground.md
  docs/docs/why-gatsby-uses-graphql.md
Labels: type: documentation

#36846 chore(docs): Add slices diagrams and switch example to Header
  docs/docs/how-to/custom-configuration/typescript.md
  docs/docs/how-to/performance/using-slices.md
  docs/docs/images/using-slices-alias-flow.png
  docs/docs/images/using-slices-build.png
  docs/docs/images/using-slices-common-build.png
  docs/docs/reference/built-in-components/gatsby-slice.md
Labels: type: documentation

#36844 fix: handle 'fields' field edge case in sort/aggr codemod
  packages/gatsby-codemods/src/transforms/__tests__/sort-and-aggr-graphql.ts
  packages/gatsby-codemods/src/transforms/sort-and-aggr-graphql.ts
  packages/gatsby/src/query/__tests__/transform-documents.ts
  packages/gatsby/src/query/transform-document.ts
Labels: topic: GraphQL

#36813 chore(gatsby): Update to GraphQL 16
  packages/gatsby-codemods/package.json
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/baseline.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/call-expression.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/fluid.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/multiple.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/placeholders.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/transform-options.output.js
  packages/gatsby-codemods/src/transforms/__testfixtures__/gatsby-plugin-image/typescript.output.tsx
  packages/gatsby-codemods/src/transforms/__tests__/sort-and-aggr-graphql.ts
  packages/gatsby-plugin-utils/package.json
  packages/gatsby-source-contentful/src/__tests__/23df7612602d69edfc3eaf89c8c02248/347966-contentful-logo-wordmark-dark (1)-4cd185-original-1582664935 (1).png
  packages/gatsby-source-contentful/src/__tests__/47098b484f55425af2625391283f7f32/347966-contentful-logo-wordmark-dark (1)-4cd185-original-1582664935 (1).png
  packages/gatsby-source-contentful/src/__tests__/85c405f72e68f1e90176d3220d41c5bf/347966-contentful-logo-wordmark-dark (1)-4cd185-original-1582664935 (1).png
  packages/gatsby-source-contentful/src/__tests__/baec3798e6d3e16f3183ed0feb8a4023/347966-contentful-logo-wordmark-dark__1_-4cd185-original-1582664935__1_.png
  packages/gatsby-source-contentful/src/__tests__/df7930af6b8c743c76c43b86ffe5af75/347966-contentful-logo-wordmark-dark (1)-4cd185-original-1582664935 (1).png
  packages/gatsby-source-contentful/src/__tests__/f6853f3e258800aa68463fa9565a9d80/347966-contentful-logo-wordmark-dark (1)-4cd185-original-1582664935 (1).png
  packages/gatsby-source-graphql/src/__tests__/__snapshots__/transforms.js.snap
  packages/gatsby-transformer-remark/src/__tests__/extend-node.js
  packages/gatsby-transformer-remark/src/__tests__/on-node-create.js
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby/package.json
  packages/gatsby/src/commands/repl.ts
  packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/__tests__/transform-documents.ts
  packages/gatsby/src/schema/__tests__/__snapshots__/build-schema.js.snap
  packages/gatsby/src/schema/__tests__/__snapshots__/rebuild-schema.js.snap
  packages/gatsby/src/schema/__tests__/build-node-connections.js
  packages/gatsby/src/schema/__tests__/build-node-types.js
  packages/gatsby/src/schema/__tests__/connection-filter-on-linked-nodes.js
  packages/gatsby/src/schema/__tests__/connection-input-fields.js
  packages/gatsby/src/schema/__tests__/context.js
  packages/gatsby/src/schema/__tests__/kitchen-sink.js
  packages/gatsby/src/schema/__tests__/queries-file.js
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/extensions/__tests__/child-relations.js
  packages/gatsby/src/schema/extensions/__tests__/field-extensions.js
  packages/gatsby/src/schema/extensions/__tests__/interfaces.js
  packages/gatsby/src/schema/infer/__tests__/infer-input.js
  packages/gatsby/src/schema/infer/__tests__/infer.js
  packages/gatsby/src/schema/print.ts
  packages/gatsby/src/schema/types/type-builders.ts
  packages/gatsby/src/utils/__tests__/prepare-regex.js
  packages/gatsby/src/utils/graphql-typegen/file-writes.ts
  packages/gatsby/src/utils/start-server.ts
  packages/gatsby/src/utils/worker/__tests__/test-helpers/child-for-tests.ts
  yarn.lock
Labels: type: maintenance

#36849 feat: inject source location data to Slice usage and show errors in places where user renders them and not in gatsby internals
  packages/gatsby-cli/src/reporter/errors.ts
  packages/gatsby/cache-dir/fast-refresh-overlay/components/hooks.js
  packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js
  packages/gatsby/cache-dir/fast-refresh-overlay/utils.js
  packages/gatsby/cache-dir/slice.js
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/query/__tests__/__snapshots__/file-parser.js.snap
  packages/gatsby/src/utils/babel-loader-helpers.ts
  packages/gatsby/src/utils/babel/babel-plugin-add-slice-placeholder-location.ts
  packages/gatsby/src/utils/babel/find-slices.ts
  packages/gatsby/src/utils/dev-ssr/parse-error.ts
  packages/gatsby/src/utils/start-server.ts
Labels: topic: core, topic: DX

#36516 chore(packages): make unstable_shouldOnCreateNode stable
  benchmarks/gabe-csv-markdown/gatsby-node.js
  benchmarks/gabe-fs-text/gatsby-node.js
  packages/gatsby-plugin-mdx/src/gatsby-node.ts
  packages/gatsby-transformer-asciidoc/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-asciidoc/src/gatsby-node.js
  packages/gatsby-transformer-csv/src/gatsby-node.js
  packages/gatsby-transformer-documentationjs/src/gatsby-node.js
  packages/gatsby-transformer-excel/src/gatsby-node.js
  packages/gatsby-transformer-hjson/src/gatsby-node.js
  packages/gatsby-transformer-javascript-frontmatter/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-javascript-frontmatter/src/gatsby-node.js
  packages/gatsby-transformer-javascript-static-exports/src/gatsby-node.js
  packages/gatsby-transformer-json/src/gatsby-node.js
  packages/gatsby-transformer-pdf/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-pdf/src/gatsby-node.js
  packages/gatsby-transformer-react-docgen/src/gatsby-node.js
  packages/gatsby-transformer-react-docgen/src/on-node-create.js
  packages/gatsby-transformer-remark/src/gatsby-node.js
  packages/gatsby-transformer-remark/src/on-node-create.js
  packages/gatsby-transformer-screenshot/src/gatsby-node.js
  packages/gatsby-transformer-sharp/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-sharp/src/gatsby-node.js
  packages/gatsby-transformer-sharp/src/on-node-create.js
  packages/gatsby-transformer-toml/src/gatsby-node.js
  packages/gatsby-transformer-xml/src/gatsby-node.js
  packages/gatsby-transformer-yaml/src/gatsby-node.js
  packages/gatsby/index.d.ts
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/src/utils/api-node-docs.ts
  packages/gatsby/src/utils/api-runner-node.js
Labels: topic: core

#36798 fix(gatsby): Set trailingSlash default to "always"
  e2e-tests/development-runtime/cypress/integration/functionality/client-only-paths.js
  e2e-tests/development-runtime/cypress/integration/functionality/query-data-caches.js
  e2e-tests/development-runtime/cypress/integration/navigation/linking.js
  e2e-tests/development-runtime/cypress/integration/navigation/redirect.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/pages/index.js
  e2e-tests/path-prefix/cypress/integration/navigate.js
  e2e-tests/production-runtime/cypress/integration/1-production.js
  e2e-tests/production-runtime/cypress/integration/redirects.js
  e2e-tests/production-runtime/gatsby-node.ts
  e2e-tests/production-runtime/src/pages/index.js
  e2e-tests/trailing-slash/cypress-legacy.json
  e2e-tests/trailing-slash/cypress/integration/always.js
  e2e-tests/trailing-slash/cypress/integration/ignore.js
  e2e-tests/trailing-slash/cypress/integration/legacy.js
  e2e-tests/trailing-slash/cypress/integration/never.js
  e2e-tests/trailing-slash/gatsby-config.js
  e2e-tests/trailing-slash/package.json
  integration-tests/artifacts/__tests__/index.js
  integration-tests/node-manifest/__tests__/create-node-manifest.test.js
  packages/gatsby-link/src/__tests__/rewrite-link-path.js
  packages/gatsby-link/src/rewrite-link-path.js
  packages/gatsby-page-utils/src/__tests__/apply-trailing-slash-option.ts
  packages/gatsby-page-utils/src/__tests__/create-path.ts
  packages/gatsby-page-utils/src/apply-trailing-slash-option.ts
  packages/gatsby-page-utils/src/create-path.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby/index.d.ts
  packages/gatsby/src/bootstrap/__tests__/redirects-writer.ts
  packages/gatsby/src/joi-schemas/__tests__/joi.ts
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/redux/actions/__tests__/internal.ts
  packages/gatsby/src/services/__tests__/create-pages.ts
  packages/gatsby/src/utils/__tests__/gatsby-cloud-config.ts
  packages/gatsby/src/utils/gatsby-cloud-config.ts
Labels: topic: core

#36855 fix(gatsby): remove jsx from comment
  packages/gatsby/src/utils/babel/babel-plugin-add-slice-placeholder-location.ts
Labels: type: bug

#36856 fix(gatsby-plugin-mdx): Unwrap images
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-mdx/src/plugin-options.ts
  yarn.lock
Labels: topic: remark/mdx

#36859 fix(gatsby): Remove runQuery & getAllNodes from nodeModel
  benchmarks/source-agilitycms/src/agility/utils.js
  examples/using-type-definitions/gatsby-node.js
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/node-model.js
Labels: topic: core

#36862 fix(docs): Update the create a source plugin tutorial
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: type: documentation

#36866 fix(gatsby-plugin-mdx): Better AST error
  packages/gatsby-plugin-mdx/src/error-utils.ts
  packages/gatsby-plugin-mdx/src/gatsby-layout-loader.ts
Labels: topic: remark/mdx

#36869 Revert "chore(gatsby-plugin-typescript): Remove obsolete `onCreateWebpackConfig` (#36814)"
  packages/gatsby-plugin-typescript/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-typescript/src/gatsby-node.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
Labels: topic: TypeScript

#36867 fix(gatsby): track multiple root nodes and not just one
  packages/gatsby/src/schema/__tests__/fixtures/node-model.js
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
Labels: type: bug, topic: core

#36857 chore: Wordpress Tests with Node 18
  .circleci/config.yml
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/queries.js
Labels: topic: automation

#36823 chore: Slight update to CircleCI config
  .circleci/config.yml
  jest.config.js
Labels: topic: automation

#36881 adjust v4 release branch tests
  e2e-tests/contentful/package.json
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/gatsby-script-scripts.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/playwright.config.ts
  e2e-tests/development-runtime/playwright/gatsby-script-off-main-thread.spec.ts
  e2e-tests/development-runtime/serve-static-files.mjs
  e2e-tests/development-runtime/static/j-query.js
  e2e-tests/development-runtime/static/marked.js
  e2e-tests/development-runtime/static/popper.js
  e2e-tests/development-runtime/static/three.js
  e2e-tests/mdx/package.json
  e2e-tests/path-prefix/package.json
  e2e-tests/production-runtime/gatsby-config.js
  e2e-tests/production-runtime/gatsby-script-scripts.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/playwright.config.ts
  e2e-tests/production-runtime/playwright/gatsby-script-off-main-thread.spec.ts
  e2e-tests/production-runtime/serve-static-files.mjs
  e2e-tests/production-runtime/static/j-query.js
  e2e-tests/production-runtime/static/marked.js
  e2e-tests/production-runtime/static/popper.js
  e2e-tests/production-runtime/static/three.js
  e2e-tests/themes/development-runtime/package.json
  e2e-tests/themes/gatsby-theme-about/package.json
  e2e-tests/themes/production-runtime/package.json
  e2e-tests/trailing-slash/package.json
  e2e-tests/visual-regression/package.json
  integration-tests/artifacts/package.json
  integration-tests/functions/package.json
  integration-tests/gatsby-cli/package.json
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/head-function-export/package.json
  integration-tests/images/package.json
  integration-tests/long-term-caching/package.json
  integration-tests/node-manifest/package.json
  integration-tests/ssr/package.json
  integration-tests/structured-logging/package.json
Labels: type: maintenance

#36868 feat: Update partial hydration directive
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-link/package.json
  packages/gatsby-plugin-image/package.json
  packages/gatsby-script/package.json
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/cjs-exports.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/cjs-module-exports.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-aggregation.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-declaration.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-class-anonymous.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-class-named.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-expression.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-function-anonymous.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-function-named.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-list.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/no-client-export-no-export.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/no-client-export.js
  packages/gatsby/src/utils/webpack/loaders/partial-hydration-reference-loader.ts
  packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts
Labels: topic: core

#36882 fix: Move murmurhash to gatsby-core-utils
  integration-tests/artifacts/__tests__/index.js
  packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.ts.snap
  packages/babel-plugin-remove-graphql-queries/src/__tests__/index.ts
  packages/babel-plugin-remove-graphql-queries/src/index.ts
  packages/gatsby-core-utils/src/__tests__/murmurhash.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-core-utils/src/murmurhash.ts
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby/src/redux/__tests__/index.js
  packages/gatsby/src/redux/__tests__/pages.ts
  packages/gatsby/src/utils/__tests__/js-chunk-names.ts
  packages/gatsby/src/utils/js-chunk-names.ts
  packages/gatsby/src/utils/sample-site-for-experiment.ts
Labels: topic: core

#36840 fix(gatsby-source-wordpress): exclude field name when set for __all
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/recursively-transform-fields.js
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/is-excluded.js
Labels: topic: source-wordpress

#36817 fix(gatsby-source-wordpress): check for camelCase single field name
  packages/gatsby-source-wordpress/src/steps/source-nodes/helpers.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
Labels: topic: source-wordpress

#36889 chore(gatsby-plugin-typescript): Remove version check
  packages/gatsby-plugin-typescript/src/gatsby-node.js
Labels: topic: TypeScript

#36825 chore(docs): Tutorial Part 2 - Fix import
  docs/docs/tutorial/part-2/index.mdx
Labels: type: documentation

#36893 chore(gatsby-transformer-remark): Update sanitize-html
  packages/gatsby-transformer-remark/package.json
  packages/gatsby-transformer-remark/src/utils/time-to-read.js
  yarn.lock
Labels: topic: remark/mdx

#36896 Typo: changed useNavitate to useNavigate
  docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
Labels: type: documentation

#36888 chore(gatsby,gatsby-link): Export Link as named export
  packages/gatsby-link/index.d.ts
  packages/gatsby-link/package.json
  packages/gatsby-link/src/__tests__/index.js
  packages/gatsby-link/src/index-cjs.js
  packages/gatsby-link/src/index.js
  packages/gatsby/cache-dir/gatsby-browser-entry.js
  packages/gatsby/index.d.ts
Labels: topic: frontend

#36901 chore(docs): v5 tutorial
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-6/index.mdx
  docs/docs/tutorial/part-7/index.mdx
  docs/docs/tutorial/whats-next/index.mdx
Labels: type: documentation

#36905 feat(gatsby-cli): Fancier Slices Tree
  packages/gatsby-cli/src/reporter/loggers/ink/cli.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/components/trees.tsx
  packages/gatsby-cli/src/reporter/loggers/ink/index.tsx
  packages/gatsby-cli/src/reporter/loggers/yurnalist/index.ts
  packages/gatsby-cli/src/util/generate-trees.ts
Labels: topic: cli

#36913 fix(gatsby): Also clear cache on gatsby version change
  packages/gatsby/src/services/initialize.ts
Labels: status: needs core review, topic: core

#36751 chore(docs): Partial Hydration How-To
  docs/docs/adding-app-and-website-functionality.md
  docs/docs/conceptual/image-plugin-architecture.md
  docs/docs/conceptual/making-your-site-accessible.md
  docs/docs/conceptual/partial-hydration.md
  docs/docs/conceptual/plugins-themes-and-starters.md
  docs/docs/conceptual/react-hydration.md
  docs/docs/glossary.md
  docs/docs/glossary/hydration.md
  docs/docs/how-to/performance/partial-hydration.md
  docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
Labels: type: documentation
