Repository gatsbyjs/gatsby, pull requests merged in 2022-12, with the labels that each got.

#37133 chore(docs): Wrap proxy redirect with createPages
  docs/docs/how-to/cloud/working-with-redirects-and-rewrites.md
Labels: type: documentation

#37120 feat(gatsby): Add `documentSearchPaths` option to `graphqlTypegen`
  docs/docs/how-to/local-development/graphql-typegen.md
  docs/docs/reference/config-files/gatsby-config.md
  packages/gatsby/index.d.ts
  packages/gatsby/src/joi-schemas/__tests__/joi.ts
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/graphql-typegen/ts-codegen.ts
Labels: topic: TypeScript

#37140 chore(docs): Add pnpm to Cloud monorepos
  docs/docs/reference/cloud/monorepos.md
Labels: type: documentation

#37141 chore(docs): Add Slice placeholder to unit testing mocks
  docs/docs/how-to/performance/using-slices.md
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#37148 fix(create-gatsby): Update questionare
  docs/docs/how-to/styling/theme-ui.md
  examples/using-vanilla-extract/package.json
  packages/create-gatsby/src/questions/features.json
  packages/create-gatsby/src/questions/styles.json
Labels: topic: DX

#37134 fix(gatsby-source-wordpress): WPGraphQL 1.13.0 compatibility
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/__tests__/index.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/queries.js
  packages/gatsby-source-wordpress/src/models/remoteSchema.ts
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/build-types.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/helpers.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/index.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/default-resolver.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/field-transformers.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/index.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/transform-object.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/transform-fields/transform-union.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/type-filters.js
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/build-node-queries.js
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/build-query-on-field-name.js
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/generate-queries-from-ingestable-types.js
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/recursively-transform-fields.js
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/identify-and-store-ingestable-types.js
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/is-excluded.js
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/write-queries-to-disk.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/helpers.js
Labels: topic: source-wordpress, topic: source-plugins

#37146 chore(gatsby-source-wordpress): use wpgql 1.13 in itests
  integration-tests/gatsby-source-wordpress/.env.test
  integration-tests/gatsby-source-wordpress/.wordpress-cache/wp-content/uploads/2020/08/file-sample_1MB.doc
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/increment-remote-data.js
  packages/gatsby-source-wordpress/src/models/remoteSchema.ts
Labels: topic: source-wordpress, topic: source-plugins

#37176 fix: Remove obsolete `unstable_onPluginInit` codepaths
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby-source-shopify/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/utils/run-steps.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
Labels: topic: core

#36772 feat(gatsby-plugin-utils): add path prefix to image cdn urls
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/public-url-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/resize-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/dispatchers.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/__tests__/url-generator.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/url-generator.ts
Labels: bot: merge on green, topic: media

#37128 refactor(gatsby): gatsby-node.mjs cleanup
  integration-tests/esm-in-gatsby-files/package.json
  packages/gatsby/babel.config.js
  packages/gatsby/src/bootstrap/__mocks__/import/exports.js
  packages/gatsby/src/bootstrap/__mocks__/import/module-error.js
  packages/gatsby/src/bootstrap/__mocks__/import/unusual-exports.js
  packages/gatsby/src/bootstrap/__mocks__/resolve-js-file-path/both/gatsby-config.js
  packages/gatsby/src/bootstrap/__mocks__/resolve-js-file-path/both/gatsby-config.mjs
  packages/gatsby/src/bootstrap/__mocks__/resolve-js-file-path/cjs/gatsby-config.js
  packages/gatsby/src/bootstrap/__mocks__/resolve-js-file-path/esm/gatsby-config.mjs
  packages/gatsby/src/bootstrap/__tests__/resolve-config-file-path.ts
  packages/gatsby/src/bootstrap/__tests__/resolve-js-file-path.ts
  packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.ts
  packages/gatsby/src/bootstrap/get-config-file.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/index.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
  packages/gatsby/src/bootstrap/resolve-config-file-path.ts
  packages/gatsby/src/bootstrap/resolve-js-file-path.ts
  packages/gatsby/src/bootstrap/resolve-module-exports.ts
  packages/gatsby/src/schema/graphql-engine/entry.ts
  packages/gatsby/src/schema/graphql-engine/print-plugins.ts
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/import-gatsby-plugin.ts
  packages/gatsby/src/utils/jobs/__tests__/fixtures/.gitignore
  packages/gatsby/src/utils/jobs/__tests__/fixtures/gatsby-plugin-local/gatsby-worker.js
  packages/gatsby/src/utils/jobs/__tests__/fixtures/node_modules/gatsby-plugin-test/gatsby-worker.js
  packages/gatsby/src/utils/jobs/__tests__/manager.js
  packages/gatsby/src/utils/jobs/manager.ts
  packages/gatsby/src/utils/module-resolver.ts
  packages/gatsby/src/utils/require-gatsby-plugin.ts
Labels: topic: core

#37111 fix(gatsby,gatsby-plugin-page-creator): Materialize nodes in gatsbyPath
  e2e-tests/development-runtime/cypress/integration/unified-routing/collection-routing.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/pages/collection-routing/{GatsbyPathMaterializedParent.childType__name}/{GatsbyPathMaterializedParent.name}.js
  packages/gatsby-plugin-page-creator/src/__tests__/derive-path.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-changed-nodes.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/derive-path.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby-plugin-page-creator/src/tracked-nodes-state.ts
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
  packages/gatsby/src/schema/resolvers.ts
Labels: topic: GraphQL

#37195 feat(gatsby): Better renderHtml Preview Error
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: topic: DX

#37202 fix(gatsby): Use path prefix when loading slice data
  e2e-tests/path-prefix/cypress/integration/asset-prefix.js
  e2e-tests/path-prefix/gatsby-node.js
  e2e-tests/path-prefix/src/components/layout.js
  packages/gatsby/cache-dir/loader.js
Labels: topic: frontend

#37212 fix(gatsby-source-wordpress): Add back nodeType field that was removed in last version
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/index.js
  packages/gatsby-source-wordpress/src/steps/create-schema-customization/type-filters.js
Labels: bot: merge on green, topic: source-wordpress

#37217 fix(deps): Update parcel to v2.8.1
  packages/gatsby-parcel-config/package.json
  packages/gatsby-parcel-namer-relative-to-cwd/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#37206 feat(gatsby-worker): Show original stack trace
  packages/gatsby-worker/package.json
  packages/gatsby-worker/src/__tests__/fixtures/test-child.ts
  packages/gatsby-worker/src/__tests__/integration.ts
  packages/gatsby-worker/src/child.ts
  packages/gatsby-worker/src/index.ts
  packages/gatsby-worker/src/types.ts
  packages/gatsby/src/utils/jobs/types.ts
  packages/gatsby/src/utils/jobs/worker-messaging.ts
  packages/gatsby/src/utils/worker/__tests__/jobs.ts
  packages/gatsby/src/utils/worker/messaging.ts
Labels: topic: core

#37220 fix(gatsby): Improve readability of page data / long running query warnings
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/utils/__tests__/page-data.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: topic: core

#36628 chore(docs): Switch to `Announcement` shortcode
  docs/docs/conceptual/gatsby-for-ecommerce.md
  docs/docs/conceptual/rendering-options.md
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
  docs/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4.md
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-6/index.mdx
  docs/docs/tutorial/part-7/index.mdx
Labels: type: documentation

#37222 chore(docs): Add auto config change for `react-dom` in Storybook
  docs/docs/how-to/testing/visual-testing-with-storybook.md
Labels: type: documentation

#37243 chore(gatsby-plugin-gatsby-cloud): Update README
  packages/gatsby-plugin-gatsby-cloud/README.md
Labels: topic: plugins

#37255 Revert "fix(deps): update dependency lmdb to v2.7.1 (#37160)"
  packages/gatsby-core-utils/package.json
  packages/gatsby/package.json
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
  packages/gatsby/src/utils/cache-lmdb.ts
  yarn.lock
Labels: topic: core

#37257 fix(gatsby): use file:// protocol when importing gatsby-config/node
  packages/gatsby/src/bootstrap/get-config-file.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/resolve-js-file-path.ts
  packages/gatsby/src/bootstrap/resolve-module-exports.ts
  packages/gatsby/src/utils/import-gatsby-plugin.ts
Labels: type: bug, topic: core

#37262 fix(gatsby-plugin-image): Normalize filename for correct hashing
  packages/gatsby-plugin-image/src/babel-plugin-parse-static-images.ts
  packages/gatsby-plugin-image/src/node-apis/parser.ts
Labels: topic: media

#37264 chore(docs): Update SECURITY.md to reflect supported versions
  SECURITY.md
Labels: type: documentation

#37265 chore(docs): Update unified hosting and slice api docs for cloud
  docs/docs/how-to/cloud/slices-optimization.md
  docs/docs/how-to/cloud/unified-hosting.md
  docs/docs/images/slices-api-optimization.png
Labels: type: documentation

#37244 fix(gatsby-transformer-remark): Disallow JS frontmatter by default
  packages/gatsby-transformer-remark/README.md
  packages/gatsby-transformer-remark/src/__tests__/gatsby-node.js
  packages/gatsby-transformer-remark/src/gatsby-node.js
Labels: topic: remark/mdx

#37272 chore(gatsby): bump socket.io
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#37275 chore(docs): Add version hints to `graphqlTypegen`
  docs/docs/reference/config-files/gatsby-config.md
Labels: type: documentation

#37276 chore(gatsby-plugin-google-analytics): Fix typo in README
  packages/gatsby-plugin-google-analytics/README.md
Labels: type: documentation, topic: plugins-analytics

#37280 fix(create-gatsby,gatsby-cli): Always use `--legacy-peer-deps`
  packages/create-gatsby/src/__tests__/init-starter.ts
  packages/create-gatsby/src/init-starter.ts
  packages/gatsby-cli/src/init-starter.ts
Labels: topic: cli

#37282 fix(gatsby): [rendering engines] use results of exports removal if sourceMap was not generated alongside transformed code
  packages/gatsby/src/schema/graphql-engine/standalone-regenerate.ts
  packages/gatsby/src/utils/webpack/loaders/webpack-remove-exports-loader.ts
Labels: topic: render-mode

#37284 fix(gatsby): don't output file-loader assets to .cache
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: render-mode

#37320 fix(gatsby): extract queries from .mjs files
  e2e-tests/production-runtime/cypress/integration/static-query.js
  e2e-tests/production-runtime/src/components/static-query/use-static-query/index.js
  e2e-tests/production-runtime/src/components/static-query/use-static-query/mjs.mjs
  e2e-tests/production-runtime/src/pages/static-query.js
  packages/gatsby/src/query/query-compiler.js
Labels: topic: GraphQL

#37325 test(gatsby-worker): increase jest timeout
  packages/gatsby-worker/src/__tests__/integration.ts
Labels: type: maintenance

#37326 docs: Add src dir limitation to slices and useStaticQuery
  docs/docs/how-to/querying-data/use-static-query.md
  docs/docs/reference/built-in-components/gatsby-slice.md
Labels: type: documentation
