Repository gatsbyjs/gatsby, pull requests merged in 2022-08, with the labels that each got.

#36263 chore: add docs on `gatsby-provision`
  docs/docs/reference/config-files/gatsby-provision.md
Labels: type: documentation

#36295 fix(gatsby): Add DEV_SSR note to 95312 error
  docs/docs/debugging-html-builds.md
  docs/docs/glossary/server-side-rendering.md
  docs/docs/how-to/local-development/troubleshooting-common-errors.md
  integration-tests/gatsby-cli/__tests__/build-ssr-errors.js
  packages/gatsby-cli/src/reporter/__tests__/__snapshots__/index.ts.snap
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/utils/flags.ts
Labels: topic: core

#36203 fix(gatsby-plugin-image): Add `outputPixelDensities` to `SHARP_ATTRIBUTES`
  e2e-tests/visual-regression/cypress/integration/image.js
  e2e-tests/visual-regression/src/pages/static-images/sharp-props.js
  packages/gatsby-plugin-image/src/babel-helpers.ts
  packages/gatsby-plugin-image/src/components/static-image.server.tsx
  packages/gatsby-plugin-image/src/image-utils.ts
Labels: topic: media

#36261 chore(docs): Release Notes for 4.20
  docs/docs/reference/release-notes/v4.20/index.md
Labels: type: documentation

#36305 chore(docs): Update `gatsby --help` screenshot in Part 5
  docs/docs/tutorial/part-0/05-gatsby-help.png
Labels: type: documentation

#36302 chore(starters): Remove unused stuff & updates
  starters/blog/gatsby-config.js
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/blog/src/pages/index.js
  starters/blog/src/pages/using-typescript.tsx
  starters/default/gatsby-config.js
  starters/default/package-lock.json
  starters/default/package.json
  starters/default/src/pages/index.js
  starters/default/src/pages/using-typescript.tsx
  starters/gatsby-starter-minimal-ts/src/pages/404.tsx
  starters/gatsby-starter-minimal-ts/src/pages/index.tsx
  starters/gatsby-starter-minimal/src/pages/404.js
  starters/gatsby-starter-minimal/src/pages/index.js
Labels: type: maintenance

#36251 MDX v2: unit tests
  jest.config.js
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-mdx/src/__fixtures__/example.mdx
  packages/gatsby-plugin-mdx/src/__fixtures__/test-utils.ts
  packages/gatsby-plugin-mdx/src/__tests__/cache-helpers.ts
  packages/gatsby-plugin-mdx/src/__tests__/compile-mdx.ts
  packages/gatsby-plugin-mdx/src/__tests__/frontmatter.ts
  packages/gatsby-plugin-mdx/src/__tests__/gatsby-layout-loader.ts
  packages/gatsby-plugin-mdx/src/__tests__/gatsby-mdx-loader.ts
  packages/gatsby-plugin-mdx/src/__tests__/gatsby-node.ts
  packages/gatsby-plugin-mdx/src/__tests__/get-source-plugins-as-remark-plugins.ts
  packages/gatsby-plugin-mdx/src/__tests__/rehype-metadata-extractor.ts
  packages/gatsby-plugin-mdx/src/__tests__/remark-infer-toc-meta.ts
  packages/gatsby-plugin-mdx/src/__tests__/remark-mdx-html-plugin.ts
  packages/gatsby-plugin-mdx/src/__tests__/remark-path-prefix-plugin.ts
  packages/gatsby-plugin-mdx/src/compile-mdx.ts
  packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts
  yarn.lock
Labels: topic: remark/mdx

#36237 chore(gatsby): convert babel-loader-helpers to typescript
  packages/gatsby/package.json
  packages/gatsby/src/redux/__tests__/__snapshots__/babelrc.ts.snap
  packages/gatsby/src/redux/__tests__/babelrc.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/babel-loader-helpers.ts
  packages/gatsby/src/utils/babel-loader.js
  yarn.lock
Labels: topic: TypeScript

#36301 chore(starters): update starters docs page
  docs/docs/starters.md
  starters/README.md
Labels: type: documentation

#36303 fix(gatsby-plugin-react-helment): stop appending empty title tags
  packages/gatsby-plugin-react-helmet/src/__mocks__/react-helmet.js
  packages/gatsby-plugin-react-helmet/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-react-helmet/src/gatsby-ssr.js
Labels: topic: DX

#36319 chore(docs): Remove unused files
  docs/creators/creators.yml
  docs/creators/images/3merge.png
  docs/creators/images/adaltas.png
  docs/creators/images/ahmad-awais.jpg
  docs/creators/images/ajonp.png
  docs/creators/images/amruth-pillai.png
  docs/creators/images/annie-taylor-chen.jpg
  docs/creators/images/app-design-dev.jpeg
  docs/creators/images/arvind-kumar.jpg
  docs/creators/images/bare-advertising-communications.png
  docs/creators/images/bejamas.jpg
  docs/creators/images/brew-digital.jpg
  docs/creators/images/coletiv.jpg
  docs/creators/images/corey-ward.jpg
  docs/creators/images/desarol.png
  docs/creators/images/endormi.png
  docs/creators/images/epic-awesome.jpg
  docs/creators/images/eric-howey.jpeg
  docs/creators/images/fabian-schultz.jpg
  docs/creators/images/gerald-martinez.jpg
  docs/creators/images/iron-cove-solutions.jpg
  docs/creators/images/jamchefs.png
  docs/creators/images/john-kavanagh.jpg
  docs/creators/images/kaordica.jpg
  docs/creators/images/kevin-legrand.jpg
  docs/creators/images/kris-hedstrom.jpg
  docs/creators/images/lekoarts.jpg
  docs/creators/images/liferay-design.png
  docs/creators/images/mahipat-jadav.jpg
  docs/creators/images/mangoart.png
  docs/creators/images/marc-antoine-ruel.jpg
  docs/creators/images/michael-mcquade.jpg
  docs/creators/images/michael-uloth.jpg
  docs/creators/images/origen-studio.jpg
  docs/creators/images/pagepro.jpg
  docs/creators/images/piotr-fedorczyk.jpeg
  docs/creators/images/ramon-chancay.png
  docs/creators/images/sankarsan-kampa.jpg
  docs/creators/images/softblues.png
  docs/creators/images/somo.jpg
  docs/creators/images/spacetime.jpg
  docs/creators/images/ste-oneill.jpg
  docs/creators/images/steven-natera.jpg
  docs/creators/images/thijs-koerselman.jpg
  docs/creators/images/twteam.jpg
  docs/creators/images/usama-liaquat.jpg
  docs/creators/images/ventura-digitalagentur.jpg
  docs/creators/images/web-hart.jpg
  docs/creators/images/webplace.png
  docs/creators/images/wp-spark.jpg
  docs/gatsby-explanation.png
Labels: type: documentation

#36312 fix(gatsby-link): Correctly export default for CJS
  packages/gatsby-link/package.json
  packages/gatsby-link/src/index-cjs.js
Labels: topic: core

#36322 MDX v2: turn mdast from gatsby-remark plugins into hast
  e2e-tests/mdx/cypress/integration/pages.js
  e2e-tests/mdx/gatsby-config.js
  e2e-tests/mdx/package.json
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-mdx/src/__tests__/remark-mdx-html-plugin.ts
  packages/gatsby-plugin-mdx/src/plugin-options.ts
  packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
  packages/gatsby-remark-autolink-headers/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-autolink-headers/src/__tests__/index.js
  packages/gatsby-remark-autolink-headers/src/index.js
  yarn.lock
Labels: topic: remark/mdx

#36328 fix(gatsby-plugin-typescript): only use resourceQuery for supported version of gatsby
  packages/gatsby-plugin-typescript/src/gatsby-node.js
Labels: topic: TypeScript, topic: plugins

#36308 fix(gatsby): Panic on gatsby-node.jsx/gatsby-node.tsx
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/bootstrap/__mocks__/get-config/tsx-dir/gatsby-confi.tsx
  packages/gatsby/src/bootstrap/__tests__/get-config-file.ts
  packages/gatsby/src/bootstrap/get-config-file.ts
  packages/gatsby/src/utils/__tests__/is-near-match.ts
  packages/gatsby/src/utils/is-near-match.ts
  packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/misnamed-js/gatsby-node.jsx
  packages/gatsby/src/utils/parcel/__tests__/fixtures/misnamed-ts/gatsby-node.tsx
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
Labels: topic: core, topic: TypeScript

#36218 chore(docs): Add first batch of Cloud docs
  docs/docs/how-to/cloud/adding-a-custom-domain.md
  docs/docs/how-to/cloud/configuring-log-drains.md
  docs/docs/how-to/cloud/working-with-redirects-and-rewrites.md
  docs/docs/images/check-domain-status.png
  docs/docs/images/click-add-domain.png
  docs/docs/images/configure-subdomain.png
  docs/docs/images/confirm-site-is-connected.png
  docs/docs/images/copy-ip-address-for-a-record.png
  docs/docs/images/domain-validation-failed.png
  docs/docs/images/edit_vars.png
  docs/docs/images/env_var_bulk.png
  docs/docs/images/env_vars.png
  docs/docs/images/generate-ssl-certificate.png
  docs/docs/images/hosting-domain-modal.png
  docs/docs/images/image-cdn-enable.png
  docs/docs/images/log-drains-datadog-api-key.png
  docs/docs/images/main-branch-builds-overview.png
  docs/docs/images/production-builds-overview.png
  docs/docs/images/pull-request-build.png
  docs/docs/images/see-latest-build-status.png
  docs/docs/images/site-is-still-building.png
  docs/docs/reference/cloud/gatsby-cloud-environment-variables.md
  docs/docs/reference/cloud/managing-environment-variables.md
  docs/docs/reference/cloud/production-builds-and-pull-request-builds.md
Labels: type: documentation

#36325 chore(docs): Pre-encoded unicode characters can't be used in paths
  docs/docs/reference/routing/creating-routes.md
  packages/gatsby/src/redux/actions/public.js
Labels: type: documentation

#36337 fix(gatsby-source-contentful): Correctly overwrite field type on Assets
  e2e-tests/contentful/package.json
  packages/gatsby-source-contentful/src/extend-node-type.js
Labels: topic: source-contentful

#36351 chore(gatsby): Make `plugins` in `PluginOptions` type optional
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#36355 Refactor `meta.state` access in `gatsby-source-filesystem`
  packages/gatsby-source-filesystem/src/gatsby-node.js
Labels: topic: plugins

#36358 chore(gatsby-telemetry): upgrade git-up
  packages/gatsby-telemetry/package.json
  yarn.lock
Labels: type: maintenance

#36359 chore(gatsby): upgrade multer
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#36363 chore: Fix pipeline tests
  integration-tests/gatsby-pipeline/__tests__/fetch-remote-file/index.js
Labels: topic: automation

#36365 fix(gatsby): Make runtime error overlay work in non-v8 browsers
  packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js
  packages/gatsby/cache-dir/fast-refresh-overlay/utils.js
  packages/gatsby/package.json
  yarn.lock
Labels: topic: core, topic: DX

#36366 chore: Update `got`
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-filesystem/package.json
  packages/gatsby/package.json
  scripts/gatsby-plugin-checker/.env
  scripts/gatsby-plugin-checker/README.md
  scripts/gatsby-plugin-checker/index.js
  scripts/gatsby-plugin-checker/package.json
  scripts/gatsby-plugin-checker/plugins.json
  yarn.lock
Labels: type: maintenance

#36352 feat(gatsby): Telemetry tracking for Head API
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/engines-helpers.ts
Labels: topic: core

#36318 chore(gatsby): convert babel-loaders to typescript
  packages/gatsby/src/utils/babel-loader-helpers.ts
  packages/gatsby/src/utils/babel-loader.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: TypeScript

#36368 chore: Remove unused deps
  packages/create-gatsby/package.json
  packages/gatsby-cli/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/__tests__/utils.js
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-telemetry/package.json
  yarn.lock
Labels: type: maintenance

#36375 fix(gatsby-plugin-image): Make onLoad callback work on first load
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
Labels: topic: plugins

#36376 chore(docs): Remove outdated image doc
  docs/docs/working-with-images.md
Labels: type: documentation

#36385 fix(gatsby-script): Reach router import
  packages/gatsby-script/package.json
  packages/gatsby-script/src/gatsby-script.tsx
Labels: topic: DX

#36386 chore(docs): Add fragments to GraphQL typegen
  docs/docs/how-to/local-development/graphql-typegen.md
  examples/using-graphql-typegen/src/components/info.tsx
Labels: type: documentation

#36387 fix(gatsby-plugin-mdx): Hashing and pluginOptions
  packages/gatsby-plugin-mdx/src/get-source-plugins-as-remark-plugins.ts
  packages/gatsby-plugin-mdx/src/plugin-options.ts
  packages/gatsby-plugin-utils/src/types.ts
  packages/gatsby/src/utils/js-chunk-names.ts
Labels: topic: remark/mdx

#36360 chore(gatsby): upgrade @pmmmwh/react-refresh-webpack-plugin
  packages/gatsby-plugin-preact/package.json
  packages/gatsby/cache-dir/app.js
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#35893 chore(docs): MDX v2
  docs/docs/glossary/mdx.md
  docs/docs/how-to/plugins-and-themes/configuring-usage-with-plugin-options.md
  docs/docs/how-to/plugins-and-themes/using-a-plugin-in-your-site.md
  docs/docs/how-to/querying-data/page-query.md
  docs/docs/how-to/routing/customizing-components.md
  docs/docs/how-to/routing/mdx.md
  docs/docs/how-to/routing/migrate-remark-to-mdx.md
  docs/docs/mdx/getting-started.md
  docs/docs/mdx/importing-and-using-components.md
  docs/docs/mdx/index.md
  docs/docs/mdx/programmatically-creating-pages.md
  docs/docs/mdx/writing-pages.md
  docs/docs/reference/markdown-syntax.md
  docs/docs/sourcing-from-forestry.md
  docs/docs/tutorial/part-0/index.mdx
  docs/docs/tutorial/part-1/index.mdx
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-6/file-system-routes-with-blog-subdirectory.png
  docs/docs/tutorial/part-6/file-system-routes.png
  docs/docs/tutorial/part-6/index.mdx
  docs/docs/tutorial/part-7/index.mdx
  docs/docs/working-with-images-in-markdown.md
Labels: type: documentation, topic: remark/mdx

#36372 chore(docs): Release Notes for 4.21
  docs/docs/reference/release-notes/v4.21/index.md
Labels: type: documentation

#36398 chore: pin xstate
  packages/gatsby-source-filesystem/package.json
  packages/gatsby/package.json
  packages/gatsby/src/state-machines/__tests__/query-running.ts
  packages/gatsby/src/state-machines/data-layer/services.ts
  packages/gatsby/src/state-machines/develop/services.ts
  packages/gatsby/src/state-machines/query-running/services.ts
  packages/gatsby/src/utils/state-machine-logging.ts
  yarn.lock
Labels: type: maintenance

#36401 chore(docs): Remove outdated note on compatibility with with `react-helmet`
  docs/docs/reference/built-in-components/gatsby-head.md
Labels: type: documentation

#36400 chore: add prefixPaths field on IProgram type
  packages/gatsby/src/commands/types.ts
  packages/gatsby/src/utils/get-public-path.ts
Labels: topic: TypeScript

#36399 fix(gatsby-cli): preserve verbosity in spawned child processes
  packages/gatsby-cli/src/reporter/reporter.ts
Labels: topic: cli

#36377 fix(gatsby): close parcel cache db before clearing cache and retrying
  packages/gatsby/package.json
  packages/gatsby/src/utils/parcel/__tests__/__snapshots__/compile-gatsby-files.ts.snap
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
Labels: topic: TypeScript

#36402 fix(gatsby): Prevent errors if `Head` has root text node
  e2e-tests/development-runtime/src/pages/head-function-export/basic.js
  e2e-tests/production-runtime/src/pages/head-function-export/basic.js
  packages/gatsby/cache-dir/head/head-export-handler-for-browser.js
  packages/gatsby/cache-dir/head/head-export-handler-for-ssr.js
Labels: topic: DX

#36405 feat(gatsby): Add option to emit TS types during build
  docs/docs/how-to/local-development/graphql-typegen.md
  docs/docs/reference/config-files/gatsby-config.md
  packages/gatsby/index.d.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/joi-schemas/__tests__/joi.ts
  packages/gatsby/src/joi-schemas/joi.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/initialize.ts
Labels: topic: TypeScript

#36413 chore: Use GCS for pipeline tests
  integration-tests/gatsby-pipeline/__tests__/fetch-remote-file/index.js
  integration-tests/gatsby-pipeline/gatsby-node.js
Labels: bot: merge on green, topic: automation

#36419 fix(gatsby-plugin-react-helmet): Typo in `onPreInit` warning
  packages/gatsby-plugin-react-helmet/src/gatsby-node.js
Labels: topic: plugins

#36378 chore(docs): Update tutorial to Head API
  docs/docs/glossary/server-side-rendering.md
  docs/docs/tutorial/part-2/index.mdx
  docs/docs/tutorial/part-3/index.mdx
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/index.mdx
  docs/docs/tutorial/part-6/index.mdx
  docs/docs/tutorial/part-7/index.mdx
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/facebook.png
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/google.png
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/seo.jpg
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/slack.png
  docs/tutorial/seo-and-social-sharing-cards-tutorial/images/twitter.png
  docs/tutorial/seo-and-social-sharing-cards-tutorial/index.md
Labels: type: documentation

#36364 chore(gatsby): drop eslint-plugin-graphql
  packages/gatsby/package.json
  packages/gatsby/src/utils/eslint-config.ts
  packages/gatsby/src/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.ts
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: type: maintenance, bot: merge on green

#36421 chore: update using-image-processing example
  examples/using-gatsby-image/plugins/gatsby-source-remote-images/gatsby-node.js
Labels: type: maintenance

#36388 feat(docs): add webiny to headless cms list
  docs/docs/how-to/sourcing-data/headless-cms.md
Labels: status: triage needed

#36423 docs: plugin image / image cdn
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: type: documentation

#36443 chore(gatsby-plugin-sharp,gatsby-plugin-utils,gatsby-remark-images,gatsby-transformer-sharp): bump min potrace version
  .jestSetup.js
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-utils/package.json
  packages/gatsby-remark-images/package.json
  packages/gatsby-transformer-sharp/package.json
  yarn.lock
Labels: type: maintenance

#36439 fix(gatsby): remove resource query from warnings
  packages/gatsby/src/utils/webpack-error-utils.ts
Labels: topic: DX

#36431 chore(docs): Fix some typos
  docs/docs/reference/config-files/gatsby-config.md
  examples/functions-google-gmail/README.md
  examples/functions-google-oauth/README.md
Labels: type: documentation

#36437 chore(docs): Fix page link to page 6 of remark tutorial
  docs/tutorial/remark-plugin-tutorial.md
Labels: type: documentation

#36455 chore(docs): Update plugin count in part 3 of the tutorial
  docs/docs/tutorial/part-3/index.mdx
Labels: type: documentation

#36459 chore(docs): fix incorrect closing tag in tutorial
  docs/docs/tutorial/part-2/index.mdx
Labels: type: documentation

#36112 fix(gatsby-source-graphql): add dataLoaderOptions validation to gatsby-source-graphql
  packages/gatsby-source-graphql/src/gatsby-node.js
Labels: topic: source-plugins

#36436 feat(gatsby): add partial hydration flag
  packages/gatsby/src/utils/flags.ts
Labels: type: feature or enhancement

#36462 chore(gatsby): Add env log for build and remove incorrect log for functions
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
Labels: topic: core

#36463 chore(docs): Fix path to components in part 6
  docs/docs/tutorial/part-6/index.mdx
Labels: type: documentation

#36469 chore(gatsby-source-graphql): soft deprecate this plugin
  docs/docs/glossary/wpgraphql.md
  docs/docs/third-party-graphql.md
  packages/gatsby-source-graphql/README.md
Labels: type: documentation, bot: merge on green

#36447 fix(gatsby-source-wordpress): match full urls when replacing media item links to static
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/docker/seed/backup.sql
  integration-tests/gatsby-source-wordpress/docker/wp-cli/start.sh
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/index.js
  integration-tests/gatsby-source-wordpress/test-fns/static-file-transformation.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
Labels: topic: source-wordpress

#36471 chore(docs): Fix `gatsby-source-filesystem` typo
  packages/gatsby-plugin-mdx/README.md
Labels: type: documentation

#36479 fix(docs): fix creating routes code snippet
  docs/docs/reference/routing/creating-routes.md
Labels: status: triage needed

#36468 fix(gatsby): fix partial hydration constraints
  packages/gatsby/src/utils/flags.ts
Labels: type: bug

#36484 fix(gatsby): improve import/export in gatsby-browser-entry
  packages/gatsby/cache-dir/gatsby-browser-entry.js
Labels: type: maintenance

#36445 chore(gatsby-plugin-sharp): upgrade svgo
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-sharp/src/trace-svg.js
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/gatsby-plugin-image.js.snap
Labels: type: maintenance

#36389 chore(docs): migrate cloud docs to .com
  docs/docs/how-to/cloud/create-site-from-repository.md
  docs/docs/how-to/cloud/create-site-from-template.md
  docs/docs/how-to/cloud/deploying-to-gatsby-cloud-hosting.md
  docs/docs/how-to/cloud/outgoing-notifications.md
  docs/docs/how-to/cloud/set-node-version.md
  docs/docs/images/add-a-site.png
  docs/docs/images/add-notification.png
  docs/docs/images/add-site.png
  docs/docs/images/add-webhook-to-workspace.png
  docs/docs/images/basic-configuration.png
  docs/docs/images/cloud-cms-webhook.png
  docs/docs/images/cloud-webhook-image.png
  docs/docs/images/cloud-webhooks-settings.png
  docs/docs/images/configure-repository.png
  docs/docs/images/connect-integrations.png
  docs/docs/images/create-git-repo.png
  docs/docs/images/create-slack-app.png
  docs/docs/images/default-domain-link.png
  docs/docs/images/default-domain.png
  docs/docs/images/default-starter.png
  docs/docs/images/enable-gatsby-cloud-hosting.png
  docs/docs/images/first-deploy-page.png
  docs/docs/images/gatsby-domain-redirect.png
  docs/docs/images/hosting-domain-default.png
  docs/docs/images/import-from-repo.png
  docs/docs/images/incoming-webhook.png
  docs/docs/images/install-gatsby-cloud-app.png
  docs/docs/images/make-primary.png
  docs/docs/images/netlify-asset-optimization-settings.png
  docs/docs/images/no-environment-variables.png
  docs/docs/images/no-integrations.png
  docs/docs/images/notification-list.png
  docs/docs/images/primary-domain.png
  docs/docs/images/private-build-link.png
  docs/docs/images/remove-from-redirect.png
  docs/docs/images/setup-summary.png
  docs/docs/images/site-overview.png
  docs/docs/images/slack-app-permissoin.png
  docs/docs/images/use-this-template.png
  docs/docs/images/webhook-notification.png
  docs/docs/images/webhook-url.png
  docs/docs/reference/cloud/apex-and-subdomains.md
  docs/docs/reference/cloud/build-and-preview-webhooks.md
Labels: type: documentation

#36486 chore(gatsby, gatsby-transformer-remark, gatsby-plugin-sharp): Cleanup v4 compile flag conditions
  packages/gatsby-plugin-sharp/src/gatsby-node.js
  packages/gatsby-transformer-remark/src/create-schema-customization.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
  packages/gatsby-transformer-remark/src/gatsby-node.js
  packages/gatsby/src/bootstrap/load-plugins/load-internal-plugins.ts
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build-utils.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/constants.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/schema/graphql-engine/entry.ts
  packages/gatsby/src/schema/index.js
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/babel-loader-helpers.ts
  packages/gatsby/src/utils/page-data.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/worker/child/load-config-and-plugins.ts
Labels: type: maintenance

#36474 fix(gatsby-source-wordpress): match more urls wp on delta
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/static-file-transformation.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/increment-remote-data.js
  packages/gatsby-source-wordpress/__tests__/fetch-referenced-media-items.test.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js
Labels: bot: merge on green, topic: source-wordpress
