Repository gatsbyjs/gatsby, pull requests merged in 2022-05, with the labels that each got.

#28093 fix(gatsby-remark-images): support resolving markdown images from child nodes
  .circleci/config.yml
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/index.js
Labels: topic: remark/mdx

#35515 fix(starters): Remove duplicate UTM params
  starters/default/src/pages/index.js
Labels: topic: DX

#35575 chore(gatsby): Pin event-source-polyfill
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#35487 feat(gatsby): Initial GraphQL Typegen Implementation
  e2e-tests/development-runtime/.gitignore
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/fragments-file.js
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/graphql-config.js
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/schema-file.js
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/ts-types.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/src/pages/collection-routing/hogwarts/{FakeData.uuid}.js
  e2e-tests/development-runtime/src/pages/collection-routing/prefix-{FakeData.uuid}.js
  e2e-tests/development-runtime/src/pages/collection-routing/{FakeData.title}/{FakeData.uuid}.js
  e2e-tests/development-runtime/src/pages/collection-routing/{FakeData.uuid}-postfix.js
  e2e-tests/development-runtime/src/pages/collection-routing/{FakeData.uuid}.js
  packages/gatsby/package.json
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/query/query-watcher.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/schema/print.ts
  packages/gatsby/src/schema/types/built-in-types.ts
  packages/gatsby/src/services/graphql-typegen.ts
  packages/gatsby/src/services/index.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/services/types.ts
  packages/gatsby/src/state-machines/data-layer/index.ts
  packages/gatsby/src/state-machines/data-layer/services.ts
  packages/gatsby/src/state-machines/data-layer/types.ts
  packages/gatsby/src/state-machines/develop/index.ts
  packages/gatsby/src/state-machines/develop/services.ts
  packages/gatsby/src/state-machines/query-running/index.ts
  packages/gatsby/src/state-machines/query-running/services.ts
  packages/gatsby/src/state-machines/query-running/types.ts
  packages/gatsby/src/state-machines/waiting/index.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/graphql-typegen/file-writes.ts
  packages/gatsby/src/utils/graphql-typegen/ts-codegen.ts
  packages/gatsby/src/utils/graphql-typegen/utils.ts
  yarn.lock
Labels: topic: GraphQL, topic: core, topic: TypeScript

#35507 feat(gatsby-plugin-image): add check for node.gatsbyImage in the getImage helper
  packages/gatsby-plugin-image/src/components/__tests__/hooks.ts
  packages/gatsby-plugin-image/src/components/hooks.ts
Labels: topic: media

#35573 feat(gatsby-source-wordpress): always include draft slugs
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
Labels: topic: source-wordpress

#35529 feat(gatsby-source-wordpress): use image cdn for non-resizable images in html (svgs/gifs mainly)
  integration-tests/gatsby-source-wordpress/.env.test
  integration-tests/gatsby-source-wordpress/__tests__/__snapshots__/index.js.snap
  integration-tests/gatsby-source-wordpress/docker/seed/backup.sql
  integration-tests/gatsby-source-wordpress/docker/wordpress/Dockerfile
  integration-tests/gatsby-source-wordpress/docker/wordpress/wp-content/uploads/2022/05/gaussian2.svg
  integration-tests/gatsby-source-wordpress/docker/wp-cli/start.sh
  integration-tests/gatsby-source-wordpress/gatsby-config.js
  integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js
  integration-tests/gatsby-source-wordpress/test-fns/gatsby-image.js
  integration-tests/gatsby-source-wordpress/test-fns/test-utils/queries.js
  packages/gatsby-source-wordpress/__tests__/fixtures/media.js
  packages/gatsby-source-wordpress/__tests__/process-node.test.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
Labels: topic: source-wordpress, topic: source-plugins

#35505 chore(gatsby): Expose `serverDataStatus` field in SSR type declaration file
  packages/gatsby/cache-dir/page-ssr/index.d.ts
Labels: topic: TypeScript

#35578 perf(gatsby): Minify page-data
  packages/gatsby/src/utils/page-data-helpers.ts
Labels: topic: performance

#35581 feat(gatsby): Improvements to GraphQL TypeScript Generation
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/files-existence.js
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/fragments-file.js
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/graphql-config.js
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/schema-file.js
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/ts-types.js
  e2e-tests/development-runtime/cypress/integration/graphql-typegen/updates.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/plugins/gatsby-node-typegen/gatsby-node.ts
  e2e-tests/development-runtime/plugins/gatsby-node-typegen/package.json
  e2e-tests/development-runtime/src/pages/graphql-typegen.tsx
  e2e-tests/development-runtime/tsconfig.json
  packages/gatsby/src/services/graphql-typegen.ts
  packages/gatsby/src/services/listen-for-mutations.ts
  packages/gatsby/src/state-machines/data-layer/index.ts
  packages/gatsby/src/state-machines/data-layer/services.ts
  packages/gatsby/src/state-machines/develop/actions.ts
  packages/gatsby/src/state-machines/develop/index.ts
  packages/gatsby/src/state-machines/query-running/index.ts
  packages/gatsby/src/state-machines/query-running/services.ts
  packages/gatsby/src/state-machines/query-running/types.ts
  packages/gatsby/src/utils/graphql-typegen/file-writes.ts
  packages/gatsby/src/utils/graphql-typegen/ts-codegen.ts
Labels: topic: GraphQL

#35226 fix(gatsby-plugin-image): fix image flickers
  e2e-tests/contentful/cypress/integration/rich-text.js
  e2e-tests/contentful/package.json
  e2e-tests/contentful/snapshots.js
  e2e-tests/production-runtime/cypress/integration/gatsby-plugin-image.js
  e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js
  e2e-tests/production-runtime/src/pages/gatsby-plugin-image-page-1.js
  e2e-tests/production-runtime/src/pages/gatsby-plugin-image-page-2.js
  packages/gatsby-plugin-image/gatsby-browser.js
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/components/__tests__/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx
  packages/gatsby-plugin-image/src/components/gatsby-image.server.tsx
  packages/gatsby-plugin-image/src/components/hooks.ts
  packages/gatsby-plugin-image/src/components/intersection-observer.ts
  packages/gatsby-plugin-image/src/components/later-hydrator.tsx
  packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
  packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx
  packages/gatsby-plugin-image/src/components/main-image.tsx
  packages/gatsby-plugin-image/src/components/picture.tsx
  packages/gatsby-plugin-image/src/components/placeholder.tsx
  packages/gatsby-plugin-image/src/gatsby-node.ts
  packages/gatsby-plugin-image/src/gatsby-ssr.tsx
  packages/gatsby-plugin-image/src/global.d.ts
  packages/gatsby-plugin-image/src/global.ts
  packages/gatsby-plugin-image/src/image-utils.ts
  packages/gatsby-plugin-image/src/index.browser.ts
  packages/gatsby-plugin-image/src/index.ts
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-plugin-image/tsconfig.json
Labels: topic: media

#35594 fix(gatsby): Better TS compilation error
  packages/gatsby-cli/src/structured-errors/error-map.ts
Labels: topic: TypeScript

#33870 feat(contentful): add support for tables in Rich Text
  e2e-tests/contentful/cypress/integration/rich-text.js
  e2e-tests/contentful/snapshots.js
  packages/gatsby-source-contentful/package.json
  yarn.lock
Labels: status: needs core review, topic: source-contentful, topic: core

#35569 chore(docs): Add ability to configure body parsing in Gatsby Functions
  docs/docs/reference/functions/middleware-and-helpers.md
Labels: type: documentation

#35596 chore(docs): Release Notes for 4.14
  docs/docs/reference/release-notes/v4.14/index.md
Labels: type: documentation

#35617 fix(gatsby-source-contentful): Add RemoteFile interface
  packages/gatsby-source-contentful/src/create-schema-customization.js
Labels: status: triage needed

#35595 chore: workaround lerna + npm-run-all weirdness
  package.json
  packages/gatsby-cli/package.json
  packages/gatsby-graphiql-explorer/package.json
  packages/gatsby-legacy-polyfills/package.json
  packages/gatsby-plugin-image/package.json
  packages/gatsby-sharp/package.json
Labels: type: maintenance

#35632 chore(docs): Update Unit Testing for Jest 28
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#35633 fix(gatsby): use correct types for the response headers
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#35635 fix(gatsby-plugin-image): fix race condition
  packages/gatsby-plugin-image/src/components/layout-wrapper.tsx
Labels: topic: media

#35644 fix(gatsby-source-drupal): add placeholder style name plugin option to the options schema
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: status: triage needed

#35619 fix(gatsby-source-drupal): Image cdn fixes
  packages/gatsby-source-drupal/src/gatsby-node.js
  packages/gatsby-source-drupal/src/normalize.js
Labels: topic: source-drupal

#35648 feat(gatsby): Support for off-main-thread in develop
  packages/gatsby-script/src/gatsby-script.tsx
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/partytown/gatsby-browser.tsx
  packages/gatsby/src/internal-plugins/partytown/gatsby-node.ts
  packages/gatsby/src/internal-plugins/partytown/proxy.ts
Labels: type: feature or enhancement, topic: core

#35659 sitemap plugin readme has incorrect array name reference
  packages/gatsby-plugin-sitemap/README.md
Labels: status: needs docs review

#35664 test(gatsby-script): SSR and browser APIs
  e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-ssr-browser-apis.js
  e2e-tests/development-runtime/gatsby-browser.js
  e2e-tests/development-runtime/gatsby-script-scripts.js
  e2e-tests/development-runtime/src/pages/gatsby-script-navigation.js
  e2e-tests/development-runtime/src/pages/gatsby-script-ssr-browser-apis.js
  e2e-tests/development-runtime/src/wrap-page-element.js
  e2e-tests/development-runtime/src/wrap-root-element.js
  e2e-tests/production-runtime/cypress/integration/gatsby-script-ssr-browser-apis.js
  e2e-tests/production-runtime/gatsby-browser.js
  e2e-tests/production-runtime/gatsby-script-scripts.js
  e2e-tests/production-runtime/gatsby-ssr.js
  e2e-tests/production-runtime/src/pages/gatsby-script-navigation.js
  e2e-tests/production-runtime/src/pages/gatsby-script-ssr-browser-apis.js
  e2e-tests/production-runtime/src/wrap-page-element.js
  e2e-tests/production-runtime/src/wrap-root-element.js
Labels: type: maintenance

#32522 fix(gatsby): correct the types of `createNode` action return
  packages/gatsby/index.d.ts
Labels: type: documentation

#35666 chore: bump glob to 7.2.3
  benchmarks/md/package.json
  benchmarks/mdx/package.json
  package.json
  packages/gatsby-page-utils/package.json
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#35670 test(gatsby): Attempt to deflake assets.js e2e test
  e2e-tests/production-runtime/cypress/integration/assets.js
Labels: type: maintenance

#35672 test(gatsby): Give one compilation-hash test 2 more retries
  e2e-tests/production-runtime/cypress/integration/compilation-hash.js
Labels: type: maintenance

#35673 test(gatsby): Add buffer time to failing react 18 e2e tests
  e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js
Labels: type: maintenance, bot: merge on green

#35665 test(gatsby-script): Off main thread e2e
  e2e-tests/development-runtime/.gitignore
  e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-inline-scripts.js
  e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-scripts-with-sources.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/playwright.config.ts
  e2e-tests/development-runtime/playwright/gatsby-script-off-main-thread.spec.ts
  e2e-tests/development-runtime/src/pages/gatsby-script-off-main-thread.js
  e2e-tests/development-runtime/src/pages/gatsby-script-scripts-with-sources.js
  e2e-tests/production-runtime/.gitignore
  e2e-tests/production-runtime/cypress/integration/gatsby-script-inline-scripts.js
  e2e-tests/production-runtime/cypress/integration/gatsby-script-scripts-with-sources.js
  e2e-tests/production-runtime/gatsby-config.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/playwright.config.ts
  e2e-tests/production-runtime/playwright/gatsby-script-off-main-thread.spec.ts
  e2e-tests/production-runtime/src/pages/gatsby-script-off-main-thread.js
  e2e-tests/production-runtime/src/pages/gatsby-script-scripts-with-sources.js
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
Labels: type: maintenance

#35611 feat(gatby-script): Shim requestIdleCallback
  e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-shimmed-req-idle-callback.js
  e2e-tests/production-runtime/cypress/integration/gatsby-script-shimmed-req-idle-callback.js
  packages/gatsby-script/src/__tests__/gatsby-script.tsx
  packages/gatsby-script/src/gatsby-script.tsx
  packages/gatsby-script/src/request-idle-callback-shim.ts
Labels: type: feature or enhancement

#35681 fix(gatsby): Apply `never` trailing slash to xml & pdf
  packages/gatsby-page-utils/src/apply-trailing-slash-option.ts
Labels: topic: core

#35682 chore(docs): Update RFC template
  docs/contributing/rfc-process.md
Labels: type: documentation

#35693 feat(gatsby-cli): Apply production node env to gatsby serve
  packages/gatsby-cli/src/create-cli.ts
Labels: topic: cli

#35695 chore: Update contentful e2e snapshots
  e2e-tests/contentful/snapshots.js
Labels: bot: merge on green, topic: automation

#35683 fix(gatsby): Throw Typegen errors & add `IGatsbyImageData` to output
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-image/src/resolver-utils.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/types.ts
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby-transformer-sharp/src/customize-schema.js
  packages/gatsby/index.d.ts
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/scripts/output-api-file.js
  packages/gatsby/src/schema/__tests__/__snapshots__/print.js.snap
  packages/gatsby/src/schema/schema-composer.ts
  packages/gatsby/src/schema/types/built-in-types.ts
  packages/gatsby/src/schema/types/media.ts
  packages/gatsby/src/services/graphql-typegen.ts
  packages/gatsby/src/state-machines/develop/actions.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/graphql-typegen/ts-codegen.ts
Labels: topic: TypeScript

#35696 chore: Deprecate `gatsby-plugin-graphql-config`
  deprecated-packages/gatsby-plugin-graphql-config/.babelrc
  deprecated-packages/gatsby-plugin-graphql-config/.gitignore
  deprecated-packages/gatsby-plugin-graphql-config/.npmignore
  deprecated-packages/gatsby-plugin-graphql-config/CHANGELOG.md
  deprecated-packages/gatsby-plugin-graphql-config/README.md
  deprecated-packages/gatsby-plugin-graphql-config/package.json
  deprecated-packages/gatsby-plugin-graphql-config/src/gatsby-node.ts
  deprecated-packages/gatsby-plugin-graphql-config/src/index.ts
  deprecated-packages/gatsby-plugin-graphql-config/tsconfig.json
  renovate.json5
Labels: topic: plugins

#35641 perf(gatsby): speedups for webpack compilation (develop)
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
  packages/gatsby/src/services/start-webpack-server.ts
  packages/gatsby/src/utils/print-deprecation-warnings.ts
Labels: topic: performance

#35700 Updated hosting links
  examples/using-shopify/README.md
  examples/using-square-payments/README.md
  examples/using-type-definitions/README.md
Labels: type: documentation

#35586 feat(gatsby-plugin-gatsby-cloud): Remove preview UI
  packages/gatsby-plugin-gatsby-cloud/.babelrc
  packages/gatsby-plugin-gatsby-cloud/.gitignore
  packages/gatsby-plugin-gatsby-cloud/README.md
  packages/gatsby-plugin-gatsby-cloud/package.json
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Style.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/GatsbyIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/LinkIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/index.js
  packages/gatsby-plugin-gatsby-cloud/src/components/icons.js
  packages/gatsby-plugin-gatsby-cloud/src/components/index.d.ts
  packages/gatsby-plugin-gatsby-cloud/src/components/index.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildErrorTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildSuccessTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/FeedbackTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/IndicatorButtonTooltip.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/index.js
  packages/gatsby-plugin-gatsby-cloud/src/constants.js
  packages/gatsby-plugin-gatsby-cloud/src/context/indicatorContext.js
  packages/gatsby-plugin-gatsby-cloud/src/context/indicatorProvider.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
  packages/gatsby-plugin-gatsby-cloud/src/models/enums/build-status.ts
  packages/gatsby-plugin-gatsby-cloud/src/models/enums/index.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/getBuildInfo.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/index.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/trackEvent.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/constants.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/index.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/types.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/utils.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/useCookie.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/useFeedback.js
  yarn.lock
Labels: topic: plugins

#35699 chore: `yarn_pnp` tests uses `gatsby-dev-cli` instead of portals
  .circleci/config.yml
  packages/gatsby-dev-cli/README.md
  packages/gatsby-dev-cli/src/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
  packages/gatsby-dev-cli/src/watch.js
Labels: topic: automation

#35711 chore(gatsby): Update `IPluginRefObject` type
  packages/gatsby/index.d.ts
Labels: bot: merge on green, topic: TypeScript

#35708 feat(gatsby-script): Handle duplicate script callbacks
  e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-duplicate-scripts.js
  e2e-tests/development-runtime/src/pages/gatsby-script-duplicate-scripts.js
  e2e-tests/production-runtime/cypress/integration/gatsby-script-duplicate-scripts.js
  e2e-tests/production-runtime/src/pages/gatsby-script-duplicate-scripts.js
  packages/gatsby-script/src/gatsby-script.tsx
Labels: topic: performance, type: feature or enhancement, topic: frontend

#35710 refactor(gatsby,gatsby-script): Misc review comments
  packages/gatsby-script/.babelrc
  packages/gatsby-script/src/gatsby-script.tsx
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/partytown/gatsby-browser.tsx
  packages/gatsby/src/internal-plugins/partytown/gatsby-node.ts
  packages/gatsby/src/internal-plugins/partytown/proxy.ts
Labels: topic: core, topic: frontend

#35446 feat: Add `gatsby-parcel-namer-relative-to-cwd` to monorepo & update Parcel to 2.5.0
  .circleci/config.yml
  packages/gatsby-parcel-config/package.json
  packages/gatsby-parcel-namer-relative-to-cwd/.babelrc
  packages/gatsby-parcel-namer-relative-to-cwd/.gitignore
  packages/gatsby-parcel-namer-relative-to-cwd/README.md
  packages/gatsby-parcel-namer-relative-to-cwd/package.json
  packages/gatsby-parcel-namer-relative-to-cwd/src/index.ts
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#35707 fix(gatsby-source-wordpress): html image hydration for React 17 & 18
  packages/gatsby-source-wordpress/src/gatsby-browser.ts
Labels: topic: source-wordpress

#33536 Contentful: respect gatsby-plugin-image defaults and extend tests
  e2e-tests/contentful/cypress/integration/gatsby-plugin-image.js
  e2e-tests/contentful/gatsby-config.js
  packages/gatsby-source-contentful/src/__fixtures__/contentful-logo-256.png
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/gatsby-plugin-image.js.snap
  packages/gatsby-source-contentful/src/__tests__/gatsby-plugin-image.js
  packages/gatsby-source-contentful/src/__tests__/image-helpers.js
  packages/gatsby-source-contentful/src/extend-node-type.js
  packages/gatsby-source-contentful/src/gatsby-plugin-image.js
Labels: bot: merge on green, topic: source-contentful

#35719 fix(gatsby-source-drupal): Add a check for data prop
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: topic: source-drupal, topic: source-plugins

#35584 chore(docs): Add GraphQL Typegen
  docs/docs/how-to/custom-configuration/typescript.md
  docs/docs/how-to/local-development/graphql-typegen.md
  docs/docs/how-to/local-development/javascript-tooling.md
  examples/using-graphql-typegen/.eslintrc.js
  examples/using-graphql-typegen/.gitignore
  examples/using-graphql-typegen/README.md
  examples/using-graphql-typegen/gatsby-config.ts
  examples/using-graphql-typegen/gatsby-node.ts
  examples/using-graphql-typegen/graphql.config.js
  examples/using-graphql-typegen/package.json
  examples/using-graphql-typegen/src/components/info.tsx
  examples/using-graphql-typegen/src/layout.css
  examples/using-graphql-typegen/src/pages/404.tsx
  examples/using-graphql-typegen/src/pages/index.tsx
  examples/using-graphql-typegen/tsconfig.json
  packages/gatsby-cli/src/structured-errors/error-map.ts
Labels: type: documentation

#35713 chore(stale-action): Add GitHub token permissions
  .github/workflows/schedule-stale.yml
Labels: topic: automation

#35720 chore(docs): Release Notes for 4.15
  docs/docs/reference/release-notes/v4.15/index.md
Labels: type: documentation

#35647 chore(docs): Gatsby script component
  docs/docs/how-to/performance/improving-site-performance.md
  docs/docs/reference/built-in-components/gatsby-script.md
Labels: type: documentation

#35744 chore(docs): Add gatsby-script to transformIgnorePatterns in Jest config
  docs/docs/how-to/testing/unit-testing.md
  docs/docs/reference/release-notes/v4.15/index.md
Labels: type: documentation

#35502 chore: clean up yarn.lock
  .yarnrc
  yarn.lock
Labels: type: maintenance

#29263 feat(contentful): new useContentfulHook to create images on client side
  e2e-tests/contentful/src/pages/gatsby-plugin-image.js
  packages/gatsby-source-contentful/README.md
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/hooks.js.snap
  packages/gatsby-source-contentful/src/__tests__/hooks.js
  packages/gatsby-source-contentful/src/hooks.js
  packages/gatsby-source-contentful/src/image-helpers.js
Labels: bot: merge on green, topic: source-contentful

#35760 fix(gatsby-script): Make load callback work when both load and error callbacks defined
  e2e-tests/development-runtime/cypress/integration/gatsby-script/gatsby-script-both-callbacks.js
  e2e-tests/development-runtime/src/pages/gatsby-script-both-callbacks.js
  e2e-tests/development-runtime/src/pages/gatsby-script-duplicate-scripts.js
  e2e-tests/production-runtime/cypress/integration/gatsby-script-both-callbacks.js
  e2e-tests/production-runtime/src/pages/gatsby-script-both-callbacks.js
  e2e-tests/production-runtime/src/pages/gatsby-script-duplicate-scripts.js
  packages/gatsby-script/src/gatsby-script.tsx
Labels: topic: core

#35759 chore(docs): Improve gatsby-script reference docs
  docs/docs/reference/built-in-components/gatsby-script.md
Labels: type: documentation

#35766 chore(gatsby-plugin-gatsby-cloud): add note about auto installation
  packages/gatsby-plugin-gatsby-cloud/README.md
Labels: topic: plugins

#35755 chore(docs): Fix `videoSourceURL` markdown key mismatch
  docs/docs/how-to/images-and-media/working-with-video.md
Labels: type: documentation

#35743 chore: Update starters to React 18
  starters/blog/package-lock.json
  starters/blog/package.json
  starters/default/package-lock.json
  starters/default/package.json
  starters/gatsby-starter-blog-theme-core/package-lock.json
  starters/gatsby-starter-blog-theme-core/package.json
  starters/gatsby-starter-blog-theme/package-lock.json
  starters/gatsby-starter-blog-theme/package.json
  starters/gatsby-starter-minimal-ts/package-lock.json
  starters/gatsby-starter-minimal-ts/package.json
  starters/gatsby-starter-minimal/package-lock.json
  starters/gatsby-starter-minimal/package.json
  starters/hello-world/package-lock.json
  starters/hello-world/package.json
Labels: type: maintenance, topic: DX

#35752 mdx-v2: remove mdx from graphql
  benchmarks/gabe-fs-mdx/src/templates/blog-post.js
  packages/gatsby-plugin-mdx/src/gatsby-node.ts
Labels: topic: remark/mdx

#35781 chore(starters): Add GraphQL Typegen option
  starters/gatsby-starter-minimal-ts/.gitignore
  starters/gatsby-starter-minimal-ts/gatsby-config.ts
  starters/gatsby-starter-minimal-ts/src/pages/index.tsx
Labels: topic: DX

#35749 fix(gatsby): remove exports first before using asset relocator
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/schema/graphql-engine/print-plugins.ts
Labels: topic: render-mode

#35780 fix(function): prioritize raw body parser
  integration-tests/functions/test-helpers.js
  packages/gatsby/src/internal-plugins/functions/middleware.ts
Labels: topic: core

#34633 fix(gatsby-plugin-preload-fonts): disable cache
  packages/gatsby-plugin-preload-fonts/src/__tests__/index.test.js
  packages/gatsby-plugin-preload-fonts/src/prepare/index.js
Labels: type: bug, bot: merge on green, topic: frontend

#35782 chore(gatsby): Update to Parcel 2.6.0
  packages/gatsby-parcel-config/package.json
  packages/gatsby-parcel-namer-relative-to-cwd/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#35788 fix(gatsby): Remove `removeOffCanvasPaths` svgo option
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: core

#35776 fix(gatsby): Improve get-config-file error handling
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/bootstrap/__mocks__/get-config/compiled-dir/compiled/gatsby-config.js
  packages/gatsby/src/bootstrap/__mocks__/get-config/gatsby-config.js
  packages/gatsby/src/bootstrap/__mocks__/get-config/near-match-dir/gatsby-confi.js
  packages/gatsby/src/bootstrap/__mocks__/get-config/src-dir/src/gatsby-config.js
  packages/gatsby/src/bootstrap/__mocks__/get-config/ts-dir/gatsby-config.ts
  packages/gatsby/src/bootstrap/__mocks__/get-config/user-require-dir/compiled/gatsby-config.js
  packages/gatsby/src/bootstrap/__tests__/get-config-file.ts
  packages/gatsby/src/bootstrap/get-config-file.ts
Labels: topic: core

#35751 mdx-v2: feat: add support for remark, rehype and gatsby-remark plugins
  e2e-tests/mdx/gatsby-config.js
  e2e-tests/mdx/package.json
  e2e-tests/mdx/src/pages/gatsby-logo.png
  e2e-tests/mdx/src/pages/index.mdx
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-mdx/src/compile-mdx.ts
  packages/gatsby-plugin-mdx/src/gatsby-layout-loader.ts
  packages/gatsby-plugin-mdx/src/gatsby-mdx-loader.ts
  packages/gatsby-plugin-mdx/src/gatsby-node.ts
  packages/gatsby-plugin-mdx/src/get-source-plugins-as-remark-plugins.ts
  packages/gatsby-plugin-mdx/src/plugin-options.ts
  packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
  packages/gatsby-plugin-mdx/src/remark-path-prefix-plugin.ts
  packages/gatsby-plugin-mdx/src/types.ts
  packages/gatsby-plugin-utils/src/types.ts
  packages/gatsby-plugin-utils/src/utils/plugin-options-schema-joi-type.ts
  yarn.lock
Labels: topic: remark/mdx
