Repository gatsbyjs/gatsby, pull requests merged in 2022-02, with the labels that each got.

#34666 fix(gatsby-plugin-preact): Adding missing alias for `react/jsx-runtime`
  packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
Labels: topic: plugins

#34584 test: clean up and refactor Contentful unit tests
  packages/gatsby-source-contentful/src/__fixtures__/starter-blog-data.js
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/normalize.js.snap
  packages/gatsby-source-contentful/src/__tests__/data.json
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/create-schema-customization.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: topic: source-contentful

#34680 fix(gatsby-plugin-gatsby-cloud): Preview UI race condition
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/index.ts
Labels: status: triage needed

#34667 chore(example): add vanilla-extract example
  examples/using-vanilla-extract/README.md
  examples/using-vanilla-extract/gatsby-config.js
  examples/using-vanilla-extract/package.json
  examples/using-vanilla-extract/src/components/ColorModeToggle.tsx
  examples/using-vanilla-extract/src/components/color-mode-button.css.ts
  examples/using-vanilla-extract/src/icons/vanilla-extract.tsx
  examples/using-vanilla-extract/src/pages/404.tsx
  examples/using-vanilla-extract/src/pages/index.tsx
  examples/using-vanilla-extract/src/styles/404.css.ts
  examples/using-vanilla-extract/src/styles/global.css.ts
  examples/using-vanilla-extract/src/styles/index.css.ts
Labels: topic: DX

#34675 chore: Update trailing-slash static E2E test
  e2e-tests/trailing-slash/cypress/integration/static.js
Labels: type: maintenance

#34595 tests(gatsby): Create docker container and test site for future memory usage tests and benchmarks
  benchmarks/memory/.dockerignore
  benchmarks/memory/Dockerfile
  benchmarks/memory/README.md
  benchmarks/memory/gatsby-config.js
  benchmarks/memory/gatsby-node.js
  benchmarks/memory/package.json
  benchmarks/memory/scripts/docker-connect
  benchmarks/memory/scripts/docker-get-id
  benchmarks/memory/scripts/docker-start
  benchmarks/memory/scripts/docker-stats
  benchmarks/memory/scripts/docker-stop
  benchmarks/memory/scripts/enforce-docker
  benchmarks/memory/src/pages/index.js
  benchmarks/memory/src/templates/eq_field.js
  benchmarks/memory/src/templates/eq_field_with_resolver.js
  benchmarks/memory/src/templates/eq_id.js
  benchmarks/memory/src/templates/ne_field_collection_sort_skip_limit.js
Labels: topic: core

#34694 fix(gatsby-plugin-preact): Fix alias for react-dom/server
  packages/gatsby-plugin-preact/src/gatsby-node.js
Labels: topic: plugins

#34426 chore(docs): Update gatsby-plugin-image to mention local data source
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: type: documentation

#34699 fix(gatsby): Local file lookups in `eq: $id` queries
  packages/gatsby/src/schema/__tests__/fixtures/queries.js
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/node-model.js
Labels: bot: merge on green, topic: GraphQL, topic: core

#34710 fix(create-gatsby): Use MDX v1
  packages/create-gatsby/src/questions/features.json
Labels: topic: cli

#34678 Fix: Contentful warm builds
  .circleci/config.yml
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: type: bug, status: needs core review, topic: source-contentful

#34687 feat(create-gatsby): Add vanilla extract to stying options
  packages/create-gatsby/src/questions/styles.json
Labels: topic: cli

#34712 fix(gatsby-plugin-gatsby-cloud) Fix polling logic for non eager redirected urls.
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
Labels: status: triage needed

#34631 chore(docs): Update "Debugging HTML builds" to include `getServerData`
  docs/docs/debugging-html-builds.md
Labels: type: documentation

#34716 chore(docs): Added required `type` attribute to resolver
  docs/docs/reference/graphql-data-layer/schema-customization.md
Labels: type: documentation

#34713 chore(docs): Update `transformOptions` defaults
  docs/docs/reference/built-in-components/gatsby-plugin-image.md
Labels: type: documentation

#34725 fix(gatsby-plugin-gatsby-cloud) Force click-only behavior for SUCCESS and ERROR statuses.
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
Labels: status: triage needed

#34672 chore(gatsby): remove v8-compile-cache
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack.config.js
  yarn.lock
Labels: topic: core

#34746 chore: Update TS minimal starter
  starters/gatsby-starter-minimal-ts/gatsby-config.js
  starters/gatsby-starter-minimal-ts/package-lock.json
  starters/gatsby-starter-minimal-ts/package.json
Labels: type: maintenance

#34754 test(ssr): Remove flake
  integration-tests/ssr/__tests__/ssr.js
  integration-tests/ssr/test-output.js
Labels: type: maintenance

#34749 chore(examples): Typo fix
  examples/route-api/src/pages/index.js
Labels: status: triage needed

#34751 chore(docs): Add Prismic to `using-gatsby-plugin-image`
  docs/docs/how-to/images-and-media/using-gatsby-plugin-image.md
Labels: type: documentation

#34732 chore(docs): Update "building a theme" tutorial
  docs/tutorial/building-a-theme.md
Labels: type: documentation

#34745 chore(docs): Release Notes for 4.7
  docs/docs/reference/release-notes/v4.7/index.md
Labels: type: documentation

#34765 fix(gatsby-link): trailing slash undefined check for prod env
  packages/gatsby-link/src/rewrite-link-path.js
Labels: topic: frontend

#34768 chore(docs): Updated release notes for trailing slash
  docs/docs/reference/release-notes/v4.7/index.md
Labels: status: triage needed

#34748 feat(gatsby,gatsby-plugin-utils): feature toggle and availability
  packages/gatsby-plugin-utils/README.md
  packages/gatsby-plugin-utils/src/__tests__/has-feature.ts
  packages/gatsby-plugin-utils/src/has-feature.ts
  packages/gatsby-plugin-utils/src/index.ts
  packages/gatsby-plugin-utils/tsconfig.json
  packages/gatsby/index.d.ts
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/scripts/output-api-file.js
  packages/gatsby/src/utils/api-node-docs.ts
Labels: status: triage needed

#34774 chore(gatsby-plugin-mdx): Use MDX v1 for install instructions
  packages/gatsby-plugin-mdx/README.md
Labels: type: maintenance, topic: remark/mdx

#34775 chore(docs): Update Unit Testing instructions to update `moduleNameMapper`
  docs/docs/how-to/testing/unit-testing.md
  docs/docs/reference/release-notes/v4.7/index.md
  examples/using-jest/jest.config.js
Labels: type: documentation

#34727 fix(gatsby-source-wordpress): patch safari bug in source-wordpress' gatsby-browser
  packages/gatsby-source-wordpress/src/gatsby-browser.ts
Labels: status: triage needed

#34782 chore: Add GatsbyConf 2022 banner to README
  README.md
Labels: type: documentation

#34779 feat(gatsby-parcel-config): create parcel config package
  packages/gatsby-parcel-config/README.md
  packages/gatsby-parcel-config/lib/index.json
  packages/gatsby-parcel-config/package.json
  packages/gatsby/package.json
  packages/gatsby/src/utils/parcel/compile-gatsby-config.ts
  yarn.lock
Labels: topic: core, topic: TypeScript

#34773 refactor(core): Polish ahead of time ts implementation
  integration-tests/gatsby-cli/__tests__/build.js
  integration-tests/gatsby-cli/__tests__/develop.js
  integration-tests/gatsby-cli/__tests__/repl.js
  packages/gatsby/src/bootstrap/load-config-and-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/load.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/schema/graphql-engine/print-plugins.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/parcel/__tests__/__snapshots__/compile-gatsby-files.ts.snap
  packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/js/gatsby-config.js
  packages/gatsby/src/utils/parcel/__tests__/fixtures/js/gatsby-node.js
  packages/gatsby/src/utils/parcel/__tests__/fixtures/ts/gatsby-config.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/ts/gatsby-node.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/utils/create-pages-ts.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/utils/create-pages.js
  packages/gatsby/src/utils/parcel/__tests__/fixtures/utils/more-data-config-ts.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/utils/more-data-config.js
  packages/gatsby/src/utils/parcel/__tests__/fixtures/utils/say-what-ts.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/utils/say-what.js
  packages/gatsby/src/utils/parcel/__tests__/fixtures/utils/site-metadata-ts.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/utils/site-metadata.js
  packages/gatsby/src/utils/parcel/compile-gatsby-config.ts
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
  packages/gatsby/src/utils/worker/__tests__/config.ts
  packages/gatsby/src/utils/worker/__tests__/jobs.ts
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  packages/gatsby/src/utils/worker/__tests__/schema.ts
Labels: topic: core

#34790 feat(gatsby): Match node manifest pages by page context slug
  integration-tests/node-manifest/__tests__/create-node-manifest.test.js
  integration-tests/node-manifest/gatsby-node.js
  integration-tests/node-manifest/src/templates/four.js
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/types.ts
  packages/gatsby/src/utils/node-manifest.ts
Labels: topic: core

#34805 docs: update typo Forestry
  docs/docs/conceptual/choosing-a-cms.md
Labels: status: triage needed

#34747 fix(core): Make filter/sort query only hold onto node properties it needs
  benchmarks/memory/README.md
  packages/gatsby/src/datastore/__tests__/run-fast-filters.js
  packages/gatsby/src/datastore/in-memory/indexing.ts
  packages/gatsby/src/datastore/in-memory/run-fast-filters.ts
Labels: topic: performance, topic: core

#34576 chore(gatsby): upgrade from lmdb-store to lmdb
  integration-tests/cache-resilience/gatsby-node.js
  packages/gatsby/package.json
  packages/gatsby/src/commands/__tests__/build-utils.ts
  packages/gatsby/src/commands/build-utils.ts
  packages/gatsby/src/datastore/common/iterable.ts
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
  packages/gatsby/src/datastore/lmdb/updates/nodes.ts
  packages/gatsby/src/datastore/types.ts
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/schema/graphql-engine/lmdb-bundling-patch.ts
  packages/gatsby/src/utils/cache-lmdb.ts
  yarn.lock
Labels: bot: merge on green, topic: core, topic: data

#34761 feat(gatsby-core-utils): create proper mutex
  docs/docs/how-to/testing/unit-testing.md
  examples/using-jest/jest.config.js
  jest.config.js
  packages/gatsby-core-utils/README.md
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/__tests__/mutex.ts
  packages/gatsby-core-utils/src/mutex.ts
  packages/gatsby-core-utils/src/utils/get-lmdb.ts
  packages/gatsby-core-utils/src/utils/get-storage.ts
  packages/gatsby/src/services/initialize.ts
  yarn.lock
Labels: topic: core

#34821 chore(gatsby): cache shouldn't reference nodes strongly
  packages/gatsby/src/datastore/lmdb/lmdb-datastore.ts
Labels: topic: core

#34820 docs(gatsby): Add Third Party Schema
  packages/gatsby/src/redux/actions/restricted.ts
Labels: type: documentation

#34810 test(gatsby): Add a memory test suite command to the memory benchmark
  benchmarks/memory/.gitignore
  benchmarks/memory/Dockerfile
  benchmarks/memory/README.md
  benchmarks/memory/gatsby-node.js
  benchmarks/memory/package.json
  benchmarks/memory/scripts/docker-start
  benchmarks/memory/scripts/docker-write-memory
  benchmarks/memory/scripts/test-suite.js
  benchmarks/memory/scripts/test.js
Labels: topic: performance

#34829 refactor(gatsby-source-contentful): remove unnecessary check for existing node
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/normalize.js
Labels: topic: source-contentful

#34830 fix(gatsby-source-contentful): avoid confusion of Gatsby node and Contentful node count in logs
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: topic: source-contentful

#34758 feat(gatsby-core-utils): improve fetch-remote-file
  integration-tests/gatsby-pipeline/__tests__/fetch-remote-file/index.js
  integration-tests/gatsby-pipeline/gatsby-node.js
  integration-tests/gatsby-pipeline/src/pages/fetch-remote-a.js
  integration-tests/gatsby-pipeline/src/pages/fetch-remote-b.js
  integration-tests/gatsby-pipeline/src/pages/fetch-remote-c.js
  integration-tests/gatsby-pipeline/src/pages/fetch-remote-d.js
  integration-tests/gatsby-source-wordpress/jest.config.js
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
  packages/gatsby-core-utils/src/remote-file-utils/fetch-file.ts
  packages/gatsby-core-utils/src/utils/get-storage.ts
  packages/gatsby-source-contentful/src/__tests__/gatsby-plugin-image.js
  packages/gatsby-source-contentful/src/gatsby-plugin-image.js
  packages/gatsby-source-filesystem/src/__tests__/create-remote-file-node.js
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
  packages/gatsby-source-shopify/src/resolve-gatsby-image-data.ts
  packages/gatsby-transformer-sqip/src/extend-node-type.js
Labels: bot: merge on green, topic: core

#34838 feat(docs): new architecture and analytics docs
  docs/docs/conceptual/building-architecture.md
  docs/docs/conceptual/choosing-analytics-systems.md
  docs/docs/images/project-architecture.png
  docs/docs/images/systems-workflows.png
Labels: status: triage needed

#34848 fix(docs): small typo error
  rfcs/text/0011-move-rfcs-to-monorepo.md
Labels: type: documentation

#34847 chore(gatsby-plugin-image): update readme typo
  packages/gatsby-plugin-image/README.md
Labels: type: documentation

#34854 fix(gatsby): Remove double enhanced-resolve dep
  packages/gatsby/package.json
  yarn.lock
Labels: topic: core

#34860 fix(gatsby-source-contentful): Don't use unique/personal info in activity labels
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: topic: source-contentful

#34885 fix(create-gatsby): Add required deps for theme-ui option
  packages/create-gatsby/src/questions/styles.json
Labels: bot: merge on green, topic: cli

#34827 feat(core): TS compilation of local plugin gatsby files
  docs/docs/how-to/custom-configuration/typescript.md
  docs/docs/scaling-issues.md
  integration-tests/gatsby-cli/__tests__/build.js
  integration-tests/gatsby-cli/__tests__/develop.js
  integration-tests/gatsby-cli/__tests__/repl.js
  packages/gatsby/src/bootstrap/load-config/index.ts
  packages/gatsby/src/bootstrap/load-plugins/load-internal-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/resolve-plugin.ts
  packages/gatsby/src/bootstrap/load-plugins/types.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/schema/graphql-engine/print-plugins.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/flags.ts
  packages/gatsby/src/utils/parcel/__tests__/__snapshots__/compile-gatsby-files.ts.snap
  packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
  packages/gatsby/src/utils/require-gatsby-plugin.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: core

#34853 fix(gatsby): wait for LMDB upserts to finish before emitting ENGINES_READY
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/page-mode.ts
Labels: topic: render-mode

#34855 chore(gatsby): Update North Star in README
  README.md
  packages/gatsby/README.md
Labels: type: documentation, bot: merge on green

#34890 chore(docs): update main tutorial to incorporate TS Updates to create-gatsby
  docs/docs/tutorial/part-1/index.mdx
Labels: type: documentation

#34850 chore(docs): Release notes for 4.8
  docs/docs/reference/release-notes/v4.8/index.md
Labels: type: documentation

#34892 chore(gatsby): compile only TS files
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
  packages/gatsby/src/bootstrap/load-plugins/load-internal-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/resolve-plugin.ts
  packages/gatsby/src/bootstrap/load-plugins/types.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
  packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js
  packages/gatsby/src/utils/parcel/__tests__/__snapshots__/compile-gatsby-files.ts.snap
  packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
  packages/gatsby/src/utils/require-gatsby-plugin.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: TypeScript

#34898 chore(docs): Update `trailingSlash` default wording
  docs/docs/reference/config-files/gatsby-config.md
Labels: type: documentation

#34905 fix(gatsby): Lock yarn version to previous for tests
  .circleci/config.yml
Labels: type: maintenance

#34834 chore(gatsby): Cache date formatting in lmdb cache
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/schema/types/date.ts
Labels: topic: core

#34895 chore(docs): Add search details
  docs/docs/how-to/adding-common-features/adding-search.md
Labels: type: documentation

#34913 chore: Fix changelog generator script failing lint
  scripts/gatsby-changelog-generator/generate.js
Labels: type: maintenance

#34924 Update typo in gatsby-config.js
  starters/gatsby-starter-minimal-ts/gatsby-config.js
Labels: topic: TypeScript

#34930 fix(gatsby-core-utils): fix urls without extension
  packages/gatsby-core-utils/src/__tests__/fetch-remote-file.js
  packages/gatsby-core-utils/src/fetch-remote-file.ts
Labels: type: bug, bot: merge on green, topic: core

#34933 docs(gatsby): Specify trailingSlash is pages only
  docs/docs/reference/config-files/gatsby-config.md
Labels: type: documentation

#34942 chore(starters): Remove unnecessary main keys from package.json
  starters/blog/package.json
  starters/gatsby-starter-theme-workspace/example/package.json
  starters/gatsby-starter-theme-workspace/package.json
  starters/gatsby-starter-wordpress-blog/package.json
Labels: type: maintenance

#34937 chore(docs): Update link to "How to create a Gatsby Starter"
  docs/docs/creating-a-starter.md
Labels: status: triage needed

#34945 docs: specify gatsby versions supporting particular TS features
  docs/docs/how-to/custom-configuration/typescript.md
Labels: type: documentation

#34947 [docs] update writing pages in MDX link to correct url
  docs/docs/mdx/importing-and-using-components.md
Labels: type: documentation
