Repository gatsbyjs/gatsby, pull requests merged in 2022-01, with the labels that each got.

#34378 chore(docs): Update localization doc
  docs/docs/how-to/adding-common-features/localization-i18n.md
Labels: type: documentation

#34351 chore(examples): use mobx v6 in using-mobx example
  examples/using-mobx/package.json
  examples/using-mobx/src/components/Counter.js
  examples/using-mobx/src/models/CounterModel.js
  examples/using-mobx/wrap-with-provider.js
Labels: type: maintenance

#34349 chore: Fix typo
  README.md
Labels: type: documentation

#34330 chore(docs): Fix links to shared layout component
  docs/docs/how-to/styling/global-css.md
  docs/docs/recipes/pages-layouts.md
  docs/docs/recipes/styling-css.md
Labels: type: documentation

#34388 chore(docs): Update processing external images guide
  docs/docs/how-to/images-and-media/preprocessing-external-images.md
Labels: type: documentation

#34070 fix(gatsby): Wrong route resolved by findPageByPath function
  e2e-tests/production-runtime/cypress/integration/ssr.js
  e2e-tests/production-runtime/src/pages/ssr/path-ranking/[...].js
  e2e-tests/production-runtime/src/pages/ssr/path-ranking/[p1]/[p2].js
  e2e-tests/production-runtime/src/pages/ssr/path-ranking/[p1]/page.js
  packages/gatsby/src/utils/__tests__/find-page-by-path.ts
  packages/gatsby/src/utils/find-page-by-path.ts
Labels: topic: core

#34350 chore(docs): Clean up Headless CMS documentation links
  docs/docs/conceptual/building-with-components.md
  docs/docs/how-to/sourcing-data/headless-cms.md
Labels: type: documentation

#34406 chore(gatsby): Add types for `getServerData`
  packages/gatsby/index.d.ts
Labels: bot: merge on green, topic: TypeScript

#34413 Revert "fix(gatsby): Update mini-css-extract-plugin to fix inc builds issue (#33979)"
  integration-tests/artifacts/gatsby-browser.js
  packages/gatsby-plugin-less/src/gatsby-node.js
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-postcss/src/gatsby-node.js
  packages/gatsby-plugin-sass/src/gatsby-node.js
  packages/gatsby-plugin-stylus/src/gatsby-node.js
  packages/gatsby/package.json
  packages/gatsby/src/utils/webpack-utils.ts
  yarn.lock
Labels: topic: core

#34416 chore(gatsby): Give option to ignore output from workers and silence validate-engines
  packages/gatsby-worker/README.md
  packages/gatsby-worker/src/index.ts
  packages/gatsby/src/utils/validate-engines/index.ts
Labels: topic: cli

#34397 Update plugins.md to have correct URL for gatsby-plugin-segment-js
  docs/docs/plugins.md
Labels: status: triage needed

#34402 chore(docs): Old occurrences of gatbyjs.org
  docs/contributing/gatsby-style-guide.md
  docs/contributing/managing-pull-requests.md
  docs/contributing/where-to-participate.md
  docs/docs/how-to/styling/using-web-fonts.md
  docs/docs/using-gatsby-professionally/winning-over-marketers.md
  packages/gatsby-source-wordpress/docs/community-and-support.md
  packages/gatsby-source-wordpress/docs/getting-started.md
  packages/gatsby-source-wordpress/docs/migrating-from-other-wp-source-plugins.md
  packages/gatsby-source-wordpress/docs/problems-with-v3.md
  packages/gatsby-source-wordpress/docs/tutorials/building-a-new-site-wordpress-and-gatsby.md
  packages/gatsby-source-wordpress/docs/tutorials/configuring-previews-legacy.md
  packages/gatsby-source-wordpress/docs/why-use-this-plugin.md
  scripts/i18n/README.md
Labels: type: documentation

#34422 chore: Remove deprecated client paths plugin references
  examples/functions-auth0/gatsby-config.js
  examples/functions-auth0/package.json
Labels: type: maintenance

#34423 chore(gatsby-plugin-create-client-paths): Update client paths plugin readme with migration info
  packages/gatsby-plugin-create-client-paths/README.md
Labels: topic: plugins

#34383 Upgrade to strip-ansi ^6.0.1
  deprecated-packages/gatsby-recipes/package.json
  integration-tests/gatsby-cli/package.json
  integration-tests/ssr/package.json
  packages/gatsby-cli/package.json
  packages/gatsby/package.json
Labels: type: maintenance

#34392 chore(docs): Update static-folder doc
  docs/docs/how-to/images-and-media/static-folder.md
Labels: type: documentation

#34424 chore(docs): Adjust doc mentions of gatsby-plugin-create-client-paths
  docs/docs/gatsby-internals-terminology.md
  docs/docs/page-creation.md
  docs/tutorial/authentication-tutorial.md
Labels: type: documentation

#34428 Fix misspelling of "precedence" in log message
  packages/gatsby/src/bootstrap/__tests__/redirects-writer.ts
  packages/gatsby/src/bootstrap/redirects-writer.ts
Labels: type: documentation

#34331 fix(gatsby-plugin-manifest): generate icons sequentially
  packages/gatsby-plugin-manifest/.babelrc
  packages/gatsby-plugin-manifest/src/gatsby-browser.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
Labels: status: needs core review, topic: plugins-PWA

#34384 Revert "docs: Match egghead.io video instructions (#34315)"
  docs/tutorial/building-a-theme.md
Labels: type: documentation

#34443 test(ssr): Fix flakes
  integration-tests/ssr/__tests__/ssr.js
  integration-tests/ssr/test-output.js
Labels: type: maintenance, topic: automation

#34411 feat(gatsby): Send config keys over IPC
  integration-tests/structured-logging/__tests__/to-do.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/create-site-config.js
  packages/gatsby-plugin-gatsby-cloud/src/constants.js
  packages/gatsby-plugin-gatsby-cloud/src/create-site-config.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/__tests__/gatsby-cloud-config.ts
  packages/gatsby/src/utils/gatsby-cloud-config.ts
Labels: topic: core

#34429 chore(docs): Update localization doc
  docs/docs/how-to/adding-common-features/localization-i18n.md
Labels: type: documentation

#34434 chore(gatsby-source-wordpress): Fix typo
  packages/gatsby-source-wordpress/docs/features/media-item-processing.md
Labels: type: documentation

#33695 perf(gatsby): reuse rootNode & trackedRootNodes caches across instances of graphqlRunner
  packages/gatsby/src/query/graphql-runner.ts
  packages/gatsby/src/schema/node-model.js
Labels: topic: performance

#34439 chore(docs) : Typo fix GatbsyImage -> GatsbyImage
  docs/docs/conceptual/image-plugin-architecture.md
Labels: status: triage needed

#34445 chore(docs): Update quick-start guide
  docs/docs/quick-start.md
Labels: type: documentation

#34425 chore(docs): Release Notes v4.5
  docs/docs/reference/release-notes/v4.5/index.md
Labels: type: documentation

#34440 preview 2.0 UI changes
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/GatsbyIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/icons.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildErrorTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildSuccessTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/IndicatorButtonTooltip.js
Labels: status: triage needed

#34427 Update tutorial part 1 to reflect changes to add site flow
  docs/docs/tutorial/part-1/02-import-a-git-repo.png
  docs/docs/tutorial/part-1/03-github-gatsby-cloud-permissions.png
  docs/docs/tutorial/part-1/03-select-a-git-provider.png
  docs/docs/tutorial/part-1/04-select-destination.png
  docs/docs/tutorial/part-1/04-select-repository.png
  docs/docs/tutorial/part-1/05-add-site-details.png
  docs/docs/tutorial/part-1/06-integrations-and-environment-variables.png
  docs/docs/tutorial/part-1/06-select-repository.png
  docs/docs/tutorial/part-1/07-add-site-details.png
  docs/docs/tutorial/part-1/07-site-page.png
  docs/docs/tutorial/part-1/08-optional-integrations.png
  docs/docs/tutorial/part-1/09-setup.png
  docs/docs/tutorial/part-1/10-site-page.png
  docs/docs/tutorial/part-1/index.mdx
Labels: type: documentation

#34458 fix(gatsby): Revert #33786
  package.json
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#34461 fix(gatsby-dev-cli): Do not ignore engines
  packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
Labels: topic: automation, topic: DX

#34462 fix(gatsby-core-utils): Re-Export updateSiteMetadata
  packages/gatsby-core-utils/src/site-metadata.ts
Labels: topic: core

#34182 fix(gatsby): don't throw on warnings in `pluginOptionsSchema`
  packages/gatsby-plugin-cxs/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-flow/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sass/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-sitemap/src/__tests__/options-validation.js
  packages/gatsby-plugin-sitemap/src/options-validation.js
  packages/gatsby-plugin-twitter/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-utils/src/__tests__/index.ts
  packages/gatsby-plugin-utils/src/test-plugin-options-schema.ts
  packages/gatsby-plugin-utils/src/utils/plugin-options-schema-joi-type.ts
  packages/gatsby-plugin-utils/src/validate.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: status: awaiting author response, topic: core

#34470 chore(docs): webpack branding guidelines updated
  docs/contributing/gatsby-style-guide.md
Labels: type: documentation

#34469 chore(docs): Fix broken link to `gatsby-plugin-guess.js`
  docs/docs/how-code-splitting-works.md
Labels: type: documentation

#34476 chore(gatsby-plugin-utils): Override changelog for incorrect release
  scripts/gatsby-changelog-generator/generate.js
Labels: type: maintenance

#34478 chore(docs): Add MeiliSearch
  docs/docs/how-to/adding-common-features/adding-search.md
Labels: type: documentation

#34447 fix(gatsby): Fix issue with env variables not being passed to getServerData
  e2e-tests/production-runtime/__tests__/env-vars.js
  e2e-tests/production-runtime/cypress/integration/env-vars.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/src/pages/ssr/error-path.js
  e2e-tests/production-runtime/src/pages/ssr/param-path/[param].js
  e2e-tests/production-runtime/src/pages/ssr/path-ranking/[...].js
  e2e-tests/production-runtime/src/pages/ssr/path-ranking/[p1]/[p2].js
  e2e-tests/production-runtime/src/pages/ssr/path-ranking/[p1]/page.js
  e2e-tests/production-runtime/src/pages/ssr/static-path.js
  e2e-tests/production-runtime/src/pages/ssr/wildcard-path/[...wildcard].js
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/arrow-fn/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/arrow-fn/output.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/function/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/function/output.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/env-vars/options.json
  packages/gatsby/src/utils/babel/babel-plugin-env-vars.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: core

#34480 fix(contentful): enable tag support for assets
  e2e-tests/contentful/cypress/integration/tags.js
  e2e-tests/contentful/src/pages/tags.js
  packages/gatsby-source-contentful/src/__tests__/download-contentful-assets.js
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: status: needs core review, topic: source-contentful

#34488 fix(gatsby): handle loaded page being potentially undefined
  packages/gatsby/cache-dir/production-app.js
Labels: topic: frontend

#34474 chore: Update issue/PR templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/DOCUMENTATION.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: maintenance

#34494 chore: make dirty yarn.lock message more actionable
  scripts/check-lockfile.sh
Labels: type: maintenance

#34482 fix(gatsby-cli): Re-Add plugin-add functionality
  packages/create-gatsby/README.md
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/handlers/plugin-add-utils.ts
  packages/gatsby-cli/src/handlers/plugin-add.ts
  packages/gatsby-cli/src/handlers/plugin-babel-utils.ts
  packages/gatsby-core-utils/src/index.ts
  renovate.json5
  yarn.lock
Labels: topic: cli

#34495 fix(create-gatsby): Respect telemetry disable
  packages/create-gatsby/src/__tests__/tracking.ts
  packages/create-gatsby/src/is-truthy.ts
  packages/create-gatsby/src/tracking.ts
Labels: type: bug, topic: cli

#34479 chore(docs): Update links on plugins overview doc
  docs/docs/plugins.md
Labels: type: documentation

#34487 feat(gatsby): content sync debugging tweaks
  docs/docs/conceptual/content-sync.md
  packages/gatsby/src/utils/node-manifest.ts
Labels: status: triage needed

#34339 feat(gatsby-sharp): create more resilient wrapper around sharp
  jest-transformer.js
  packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-manifest/src/gatsby-node.js
  packages/gatsby-plugin-manifest/src/safe-sharp.js
  packages/gatsby-remark-images-contentful/src/__tests__/index.js
  packages/gatsby-remark-images-contentful/src/index.js
  packages/gatsby-remark-images-contentful/src/safe-sharp.js
  packages/gatsby-sharp/.babelrc.js
  packages/gatsby-sharp/package.json
  packages/gatsby-sharp/src/__tests__/index.ts
  packages/gatsby-sharp/src/index.ts
  packages/gatsby-sharp/tsconfig.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby/package.json
  packages/gatsby/sharp.d.ts
  packages/gatsby/sharp.js
  yarn.lock
Labels: bot: merge on green, topic: media

#34520 perf: move id: eq fast path handling to node-model so it's shared between query running strategies
  packages/gatsby/src/datastore/lmdb/query/run-query.ts
  packages/gatsby/src/schema/__tests__/queries.js
  packages/gatsby/src/schema/node-model.js
Labels: topic: GraphQL

#34525 fix(gatsby): handle session storage not being available
  packages/gatsby/cache-dir/production-app.js
Labels: status: triage needed

#34536 chore(circleci): pin renovate cli version
  .circleci/config.yml
Labels: type: maintenance

#34433 fix(gatsby-remark-images): regenerate markdown when used image changes
  e2e-tests/development-runtime/content/md-image.md
  e2e-tests/development-runtime/cypress/integration/hot-reloading/non-js-file.js
  e2e-tests/development-runtime/cypress/integration/unified-routing/collection-routing.js
  e2e-tests/development-runtime/cypress/plugins/index.js
  e2e-tests/development-runtime/cypress/snapshots/hot-reloading/non-js-file.js/non-js-file--image-new-0.snap.png
  e2e-tests/development-runtime/cypress/snapshots/hot-reloading/non-js-file.js/non-js-file--image-original-0.snap.png
  e2e-tests/development-runtime/cypress/support/commands.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/scripts/update.js
  e2e-tests/development-runtime/snapshots.js
  e2e-tests/development-runtime/src/images/image.png
  e2e-tests/development-runtime/src/images/new.png
  e2e-tests/development-runtime/src/images/original.png
  e2e-tests/development-runtime/src/pages/collection-routing/index.js
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/__tests__/index.js
  packages/gatsby-remark-images/src/index.js
  packages/gatsby-transformer-remark/src/extend-node-type.js
Labels: topic: remark/mdx

#34542 docs(migrating-from-v2-to-v3): correct getNode snippet
  docs/docs/reference/release-notes/migrating-from-v2-to-v3.md
Labels: type: documentation

#34543 docs(migrating-from-v3-to-v4): correct getNode snippet
  docs/docs/reference/release-notes/migrating-from-v3-to-v4.md
Labels: type: documentation

#34527 fix(plugin-schema-snapshot): unlink file on init
  packages/gatsby-plugin-schema-snapshot/gatsby-node.js
Labels: topic: GraphQL

#34460 chore: Removate validate-renovate from v3-latest branch
  .circleci/config.yml
Labels: type: maintenance

#28759 fix: add missing dependencies
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-react-router-scroll/package.json
Labels: type: maintenance

#34517 chore(docs): Update links on gatsby-for-ecommerce
  docs/docs/conceptual/gatsby-for-ecommerce.md
Labels: type: documentation

#34546 chore(docs): Update FS route api client only splat description
  docs/docs/reference/routing/file-system-route-api.md
Labels: type: documentation

#34537 chore(docs): Update client-only self-hosting instructions
  docs/docs/how-to/routing/client-only-routes-and-user-authentication.md
Labels: type: documentation

#34471 feat(gatsby-plugin-gatsby-cloud): request customer feedback
  packages/gatsby-plugin-gatsby-cloud/.gitignore
  packages/gatsby-plugin-gatsby-cloud/package.json
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Style.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/GatsbyIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/LinkIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/index.js
  packages/gatsby-plugin-gatsby-cloud/src/components/icons.js
  packages/gatsby-plugin-gatsby-cloud/src/components/index.d.ts
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildErrorTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildSuccessTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/FeedbackTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/IndicatorButtonTooltip.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/index.js
  packages/gatsby-plugin-gatsby-cloud/src/constants.js
  packages/gatsby-plugin-gatsby-cloud/src/context/indicatorContext.js
  packages/gatsby-plugin-gatsby-cloud/src/context/indicatorProvider.js
  packages/gatsby-plugin-gatsby-cloud/src/index.js
  packages/gatsby-plugin-gatsby-cloud/src/models/enums/build-status.ts
  packages/gatsby-plugin-gatsby-cloud/src/models/enums/index.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/index.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/trackEvent.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/useCookie.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/useFeedback.js
  yarn.lock
Labels: status: triage needed, type: feature or enhancement, topic: plugins

#34558 fix(gatsby): don't remove onPluginInit in graphql-engine
  packages/gatsby/src/schema/graphql-engine/webpack-remove-apis-loader.ts
Labels: bot: merge on green, topic: render-mode

#34565 chore(docs): typo fix
  docs/docs/conceptual/content-sync.md
  docs/docs/how-to/testing/visual-testing-with-storybook.md
Labels: status: triage needed

#34547 feat(gatsby): clear cache when trailing slash option changes
  e2e-tests/trailing-slash/package.json
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/services/initialize.ts
Labels: type: feature or enhancement

#34581 fix(gatsby): Handle export const syntax in babel-remove-api plugin
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/destructured-export/input.mjs
  packages/gatsby/src/utils/babel/__tests__/fixtures/remove-apis/destructured-export/output.mjs
  packages/gatsby/src/utils/babel/__tests__/index.js
  packages/gatsby/src/utils/babel/babel-module-exports-helpers.ts
  packages/gatsby/src/utils/babel/babel-plugin-remove-api.ts
Labels: topic: core

#34557 chore(docs): Release Notes for 4.6
  docs/docs/reference/release-notes/v4.6/index.md
Labels: type: documentation

#34540 chore(gatsby): use lazy iterable instead of fully realized arrays for detecting stale nodes
  packages/gatsby/src/utils/source-nodes.ts
Labels: topic: core

#34562 fix(gatsby-plugin-gatsby-cloud): usability updates for the info and link indicator buttons
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/LinkIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/IndicatorButtonTooltip.js
Labels: status: triage needed

#34606 refactor(create-gatsby): Decouple package functions
  packages/create-gatsby/src/__tests__/init-starter.ts
  packages/create-gatsby/src/__tests__/install-plugins.ts
  packages/create-gatsby/src/__tests__/tracking.ts
  packages/create-gatsby/src/__tests__/utils/make-npm-safe.ts
  packages/create-gatsby/src/cmses.json.d.ts
  packages/create-gatsby/src/features.json.d.ts
  packages/create-gatsby/src/index.ts
  packages/create-gatsby/src/init-starter.ts
  packages/create-gatsby/src/install-plugins.ts
  packages/create-gatsby/src/plugin-options-form.ts
  packages/create-gatsby/src/questions/cmses.json
  packages/create-gatsby/src/questions/cmses.json.d.ts
  packages/create-gatsby/src/questions/features.json
  packages/create-gatsby/src/questions/features.json.d.ts
  packages/create-gatsby/src/questions/styles.json
  packages/create-gatsby/src/questions/styles.json.d.ts
  packages/create-gatsby/src/styles.json.d.ts
  packages/create-gatsby/src/tracking.ts
  packages/create-gatsby/src/utils/clear-line.ts
  packages/create-gatsby/src/utils/emoji.ts
  packages/create-gatsby/src/utils/get-config-store.ts
  packages/create-gatsby/src/utils/hash.ts
  packages/create-gatsby/src/utils/is-truthy.ts
  packages/create-gatsby/src/utils/make-npm-safe.ts
  packages/create-gatsby/src/utils/question-helpers.ts
  packages/create-gatsby/src/utils/reporter.ts
  packages/create-gatsby/src/utils/require-utils.ts
  packages/create-gatsby/src/utils/site-metadata.ts
Labels: topic: cli

#34583 fix(gatsby-plugin-fullstory): update snippet
  packages/gatsby-plugin-fullstory/src/__tests__/__snapshots__/gatsby-ssr.js.snap
  packages/gatsby-plugin-fullstory/src/gatsby-ssr.js
Labels: bot: merge on green, topic: plugins

#34582 fix(gatsby): Scope remove api babel plugin to page templates
  e2e-tests/development-runtime/cypress/integration/functionality/modified-exports.js
  e2e-tests/development-runtime/src/components/unmodified-exports.js
  e2e-tests/development-runtime/src/pages/modified-exports.js
  e2e-tests/production-runtime/cypress/integration/modified-exports.js
  e2e-tests/production-runtime/src/components/unmodified-exports.js
  e2e-tests/production-runtime/src/pages/modified-exports.js
  packages/gatsby/src/utils/__tests__/__snapshots__/webpack-utils.ts.snap
  packages/gatsby/src/utils/__tests__/webpack-utils.ts
  packages/gatsby/src/utils/babel-loader-helpers.js
  packages/gatsby/src/utils/babel-loader.js
  packages/gatsby/src/utils/webpack-utils.ts
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: core

#34577 feature(gatsby-plugin-gatsby-cloud): Page data comparisons Preview 2.0
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/gatsby-browser.js
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/mocks/handlers.js
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildErrorTooltipContent.js
Labels: status: triage needed

#34608 chore(docs): Update doc
  docs/docs/how-to/previews-deploys-hosting/deploying-to-netlify.md
Labels: type: documentation

#34609 chore(gatsby-source-wordpress): Add WPGraphQL WPML
  packages/gatsby-source-wordpress/docs/usage-with-popular-wp-graphql-extensions.md
Labels: type: documentation

#34504 feat(gatsby): upgrade graphql-compose to latest for speed improvements
  packages/gatsby/package.json
  packages/gatsby/src/query/__tests__/graphql-runner.ts
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/derived-types.ts
  yarn.lock
Labels: topic: GraphQL

#34612 chore(gatsby): Add `defer` to `createPage` type
  packages/gatsby/index.d.ts
Labels: bot: merge on green, topic: TypeScript

#34599 fix(gatsby-source-contentful): remove duplicate resolving
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/gatsby-node.js.snap
  packages/gatsby-source-contentful/src/__tests__/data.json
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/create-schema-customization.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: bot: merge on green, topic: source-contentful

#34414 fix: ensure remote file downloads are queued in all cases
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/fetch-remote-file.ts
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/create-remote-file-node.js
Labels: bot: merge on green, topic: core

#34352 feat(gatsby-plugin-google-gtag): add selfHostedOrigin option
  packages/gatsby-plugin-google-gtag/README.md
  packages/gatsby-plugin-google-gtag/src/__tests__/gatsby-ssr.js
  packages/gatsby-plugin-google-gtag/src/gatsby-ssr.js
Labels: topic: plugins-analytics

#34603 feat(gatsby-plugin-gatsby-cloud): add eager redirects to preview UI
  packages/gatsby-plugin-gatsby-cloud/src/components/Indicator.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/IndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
  packages/gatsby-plugin-gatsby-cloud/src/components/tooltips/BuildSuccessTooltipContent.js
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/constants.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/index.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/types.ts
  packages/gatsby-plugin-gatsby-cloud/src/utils/use-poll-for-node-manifest/utils.ts
Labels: status: triage needed

#33712 fix(gatsby): fixes stacktraces from async functions break error reporting
  packages/gatsby/src/utils/api-runner-node.js
Labels: topic: core

#34629 chore(docs): fix links to repo instructions
  docs/contributing/how-to-open-a-pull-request.md
  docs/docs/glossary.md
Labels: type: documentation

#34390 chore(docs): fix links on styling-css page
  docs/docs/recipes/styling-css.md
Labels: type: documentation

#34585 fix(contentful): support Content Types named Tag
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/create-schema-customization.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: bot: merge on green, topic: source-contentful
