Repository gatsbyjs/gatsby, pull requests merged in 2022-09, with the labels that each got.

#36498 fix(gatsby-dev-cli): adjust setup to 'just work' with npm 8.5
  packages/gatsby-dev-cli/src/local-npm-registry/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/publish-package.js
  packages/gatsby-dev-cli/src/watch.js
Labels: type: maintenance

#36506 feat(gatsby): support node: protocol when bundling engines
  e2e-tests/production-runtime/cypress/integration/ssr.js
  e2e-tests/production-runtime/gatsby-config.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/plugins/gatsby-plugin-node-protocol-test/gatsby-node.js
  e2e-tests/production-runtime/plugins/gatsby-plugin-node-protocol-test/index.js
  e2e-tests/production-runtime/plugins/gatsby-plugin-node-protocol-test/package.json
  e2e-tests/production-runtime/polyfill-node-protocol-imports.js
  e2e-tests/production-runtime/src/pages/ssr/using-node-protocol.js
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
Labels: topic: render-mode

#36502 chore(docs): update url of `deleteNode`
  packages/gatsby/index.d.ts
Labels: type: documentation

#36452 chore(docs): migrate cloud docs to dotcom(1)
  docs/docs/how-to/cloud/create-a-deploy-to-gatsby-cloud-button.md
  docs/docs/how-to/cloud/deploying-functions-on-gatsby-cloud.md
  docs/docs/how-to/cloud/deploying-to-firebase.md
  docs/docs/how-to/cloud/managing-workspace-members.md
  docs/docs/how-to/cloud/new-account-signup.md
  docs/docs/how-to/cloud/npm-7-peer-dependencies.md
  docs/docs/images/add-members-pop-out.png
  docs/docs/images/build-log-title-link.png
  docs/docs/images/build-sharing-link.png
  docs/docs/images/cms-preview.png
  docs/docs/images/contentful-connected-integration.png
  docs/docs/images/contentful-quick-connect.png
  docs/docs/images/deploy-to-gatsby-cloud.png
  docs/docs/images/error-and-warning-logs.png
  docs/docs/images/firebase-hosting.png
  docs/docs/images/function-invocation-count.png
  docs/docs/images/function-invocation-log.png
  docs/docs/images/gatsby-cloud-app-permissions.png
  docs/docs/images/gatsby-cloud-dashboard.png
  docs/docs/images/gatsby-cloud-data-sources.png
  docs/docs/images/gatsby-cloud-signup-details.png
  docs/docs/images/idle-preview.png
  docs/docs/images/incremental-preview-cloud-badge.png
  docs/docs/images/invite-members.png
  docs/docs/images/manage-existing-members.png
  docs/docs/images/preview-build-link.png
  docs/docs/images/raw-logs.png
  docs/docs/images/sample-env-var.png
  docs/docs/images/sign-up-page.png
  docs/docs/images/structured-logs.png
  docs/docs/images/workspace-members-tab.png
  docs/docs/reference/cloud/build-logs.md
  docs/docs/reference/cloud/cms-previews.md
  docs/docs/reference/cloud/hosting-and-data-source-integrations.md
  docs/docs/reference/cloud/platform-limits.md
  docs/docs/reference/cloud/quick-connect.md
  docs/docs/reference/cloud/what-is-gatsby-cloud.md
Labels: type: documentation

#36544 fix: ci pipeline
  .circleci/config.yml
  e2e-tests/contentful/package.json
  e2e-tests/development-runtime/package.json
  e2e-tests/mdx/package.json
  e2e-tests/path-prefix/package.json
  e2e-tests/production-runtime/package.json
  e2e-tests/themes/package.json
  e2e-tests/trailing-slash/package.json
  e2e-tests/visual-regression/package.json
  integration-tests/artifacts/package.json
  integration-tests/cache-resilience/package.json
  integration-tests/functions/package.json
  integration-tests/gatsby-cli/package.json
  integration-tests/gatsby-pipeline/package.json
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/head-function-export/package.json
  integration-tests/images/package.json
  integration-tests/long-term-caching/package.json
  integration-tests/node-manifest/package.json
  integration-tests/ssr/package.json
  integration-tests/structured-logging/package.json
  packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts
  packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts
  packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
  packages/gatsby-plugin-mdx/src/remark-path-prefix-plugin.ts
  packages/gatsby/src/utils/webpack/bundle.ts
  yarn.lock
Labels: type: maintenance

#36548 chore(gatsby): perfect `GatsbyConfig.proxy` type
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#36545 feat(gatsby): split up head & page component loading
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/src/bootstrap/requires-writer.ts
Labels: topic: core

#36555 fix(gatsby): Handle renderToPipeableStream errors
  packages/gatsby/cache-dir/server-utils/writable-as-promise.js
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: core

#36552 fix(gatsby): pass custom graphql context provided by createResolverContext to materialization executor
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
Labels: topic: GraphQL, topic: data

#36504 chore(docs): monorepos support
  docs/docs/reference/cloud/monorepos.md
Labels: type: documentation

#36553 chore(gatsby): Update `react-refresh` to `^0.14.0`
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#36540 chore: setup v5 release channel
  package.json
  patches/v4/0-node-version.patch
  patches/v4/1-lmdb-default.patch
  patches/v4/3-onplugininit.patch
  patches/v4/4-gatsby-plugin-mdx-subplugin.patch
  patches/v4/5-plugins-use-webpack-from-gatsby.patch
  patches/v5/0-gatsby-peerdeps.patch
  scripts/release-next-major.js
Labels: type: maintenance

#36522 fix(gatsby): Remove default support for non ESM browsers
  packages/gatsby/src/utils/__tests__/browserslist.js
  packages/gatsby/src/utils/browserslist.ts
Labels: topic: performance

#36562 chore(docs): Remove `content` from sourcing guide
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: type: documentation

#36566 fix(create-gatsby): Missing "plugins" in cmses.json
  packages/create-gatsby/src/questions/cmses.json
Labels: topic: cli

#36542 fix(gatsby-link): Correct handling of trailingSlash & pathPrefix
  packages/gatsby-link/src/__tests__/rewrite-link-path.js
  packages/gatsby-link/src/rewrite-link-path.js
Labels: topic: core

#36465 chore(gatsby): Create release notes template script
  scripts/create-release-notes.js
  scripts/create-release-notes.template.md
Labels: topic: automation

#36568 fix: ci pipeline (#36544)
  .circleci/config.yml
  e2e-tests/contentful/package.json
  e2e-tests/development-runtime/package.json
  e2e-tests/mdx/package.json
  e2e-tests/path-prefix/package.json
  e2e-tests/production-runtime/package.json
  e2e-tests/themes/package.json
  e2e-tests/trailing-slash/package.json
  e2e-tests/visual-regression/package.json
  integration-tests/artifacts/package.json
  integration-tests/cache-resilience/package.json
  integration-tests/functions/package.json
  integration-tests/gatsby-cli/package.json
  integration-tests/gatsby-pipeline/package.json
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/head-function-export/package.json
  integration-tests/images/package.json
  integration-tests/long-term-caching/package.json
  integration-tests/node-manifest/package.json
  integration-tests/ssr/package.json
  integration-tests/structured-logging/package.json
  packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts
  packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts
  packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
  packages/gatsby-plugin-mdx/src/remark-path-prefix-plugin.ts
  packages/gatsby/src/utils/webpack/bundle.ts
  yarn.lock
Labels: type: cherry

#36560 chore: Bump min Node version to 18
  patches/v5/1-node-engine.patch
  patches/v5/2-gatsby-cli-rollup-node-target.patch
Labels: topic: core

#36572 chore(docs): Update "Layout components" related links
  docs/docs/how-to/routing/layout-components.md
Labels: type: documentation

#36575 chore(gatsby): Add required base param to create PR call
  scripts/create-release-notes.js
Labels: topic: automation

#36593 chore(gatsby-plugin-mdx): Update "headings" instructions
  examples/using-mdx/content/posts/blog-1.mdx
  examples/using-mdx/content/posts/blog-2.mdx
  examples/using-mdx/gatsby-config.js
  examples/using-mdx/gatsby-node.js
  packages/gatsby-plugin-mdx/README.md
Labels: topic: remark/mdx

#36587 chore(docs): Fix `Seo` imports in tutorial
  docs/docs/tutorial/part-4/index.mdx
  docs/docs/tutorial/part-5/index.mdx
Labels: type: documentation

#36582 chore(gatsby-plugin-sitemap): Add info about `page` object to README
  packages/gatsby-plugin-sitemap/README.md
Labels: type: documentation

#36570 chore(gatsby): Track when SlicesAPI is used
  packages/gatsby/src/redux/actions/restricted.ts
Labels: topic: core

#36492 chore(gatsby): Add `loadPageDataSync` property to `onRenderBody` TS type
  packages/gatsby/index.d.ts
Labels: bot: merge on green, topic: TypeScript

#36595 fix(gatsby-plugin-mdx): Add React import when not defined
  packages/gatsby-plugin-mdx/src/__tests__/gatsby-layout-loader.ts
  packages/gatsby-plugin-mdx/src/gatsby-layout-loader.ts
Labels: bot: merge on green, topic: remark/mdx

#36496 fix(gatsby): Pass hostname to detect-port
  packages/gatsby/src/commands/develop-process.ts
  packages/gatsby/src/commands/develop.ts
  packages/gatsby/src/commands/serve.ts
  packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts
Labels: topic: core

#36606 chore: modify patch peer-deps for v5 after release
  patches/v5/0-gatsby-peerdeps.patch
  patches/v5/1-node-engine.patch
Labels: type: maintenance

#36604 chore(gatsby): copy edit on initialize.ts comment
  packages/gatsby/src/services/initialize.ts
Labels: type: maintenance

#36533 chore: allow react/react-dom@experimental
  e2e-tests/themes/gatsby-theme-about/package.json
  packages/gatsby-link/package.json
  packages/gatsby-plugin-cxs/package.json
  packages/gatsby-plugin-feed/package.json
  packages/gatsby-plugin-fullstory/package.json
  packages/gatsby-plugin-google-analytics/package.json
  packages/gatsby-plugin-google-gtag/package.json
  packages/gatsby-plugin-google-tagmanager/package.json
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-jss/package.json
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-netlify-cms/package.json
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-plugin-sitemap/package.json
  packages/gatsby-plugin-styled-components/package.json
  packages/gatsby-plugin-typography/package.json
  packages/gatsby-react-router-scroll/package.json
  packages/gatsby-remark-autolink-headers/package.json
  packages/gatsby-script/package.json
  packages/gatsby/package.json
Labels: type: maintenance

#36613 chore(docs): Fix Partytown forward events examples
  docs/docs/reference/built-in-components/gatsby-script.md
Labels: status: triage needed

#36615 chore(docs): Improve Gatsby Link reference doc
  docs/docs/reference/built-in-components/gatsby-link.md
Labels: type: documentation

#36546 chore(docs): Add "Payments Managing" & "Deploying to Fastly"
  docs/docs/how-to/cloud/deploying-to-fastly.md
  docs/docs/how-to/cloud/managing-invoices-and-payments.md
  docs/docs/images/billing-information-screen.png
  docs/docs/images/billing-portal-screen.png
  docs/docs/images/credit-card-details-screen.png
  docs/docs/images/dashboard-vcs-link.png
  docs/docs/images/fastly-logo.png
  docs/docs/images/git-provider-authentication-settings.png
  docs/docs/images/invoice-history-section.png
  docs/docs/images/invoice-payment-portal.png
  docs/docs/images/update-payment-method.png
  docs/docs/images/visit-portal.png
  docs/docs/images/workspace-settings-tab.png
  docs/docs/reference/cloud/cms-previews.md
  docs/docs/reference/cloud/supported-git-providers.md
Labels: type: documentation

#36618 chore(docs): Swap mobile url for regular url
  docs/docs/conceptual/react-hydration.md
Labels: type: documentation

#36619 chore(docs): Improve Gatsby CLI reference doc
  docs/docs/glossary.md
  docs/docs/reference/gatsby-cli.md
  packages/gatsby-cli/README.md
Labels: type: documentation

#36620 chore(docs): Use React 18 APIs in replaceHydrateFunction example
  packages/gatsby/src/utils/api-browser-docs.ts
Labels: type: documentation

#36622 chore(docs): Recipes cleanup & Fonts guides
  docs/docs/cheat-sheet.md
  docs/docs/how-to/cloud/working-with-redirects-and-rewrites.md
  docs/docs/how-to/images-and-media/importing-assets-into-files.md
  docs/docs/how-to/previews-deploys-hosting/deploying-to-s3-cloudfront.md
  docs/docs/how-to/styling/using-local-fonts.md
  docs/docs/how-to/styling/using-web-fonts.md
  docs/docs/porting-an-html-site-to-gatsby.md
  docs/docs/recipes/pages-layouts.md
  docs/docs/recipes/querying-data.md
  docs/docs/reference/gatsby-project-structure.md
  docs/docs/reference/graphql-data-layer/graphql-api.md
  docs/docs/using-typography-js.md
Labels: type: documentation

#36621 chore(gatsby-source-wordpress): Fix license link
  packages/gatsby-source-wordpress/README.md
Labels: topic: source-wordpress

#36534 fix(gatsby): fix bundling image cdn tools
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/cache.ts
  packages/gatsby-script/package.json
  packages/gatsby-script/tsconfig.json
  packages/gatsby-sharp/package.json
  packages/gatsby-sharp/src/sharp.ts
  packages/gatsby/src/schema/graphql-engine/bootstrap.ts
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/schema/graphql-engine/entry.ts
  packages/gatsby/src/schema/graphql-engine/shims/gatsby-sharp.js
  types/gatsby-monorepo/global.d.ts
Labels: topic: render-mode

#36630 fix(docs): tiny grammatical correction
  docs/docs/conceptual/rendering-options.md
Labels: status: triage needed

#36636 chore(docs): Fix run script glossary link
  docs/docs/glossary.md
  docs/docs/reference/gatsby-cli.md
  packages/gatsby-cli/README.md
Labels: type: documentation

#36580 chore(docs): Add `wrapRootElement` + Head API limitation
  docs/docs/reference/built-in-components/gatsby-head.md
Labels: type: documentation

#36525 fix(gatsby): Multiple root query error
  docs/docs/how-to/routing/mdx.md
  e2e-tests/mdx/src/pages/fs-api/{Mdx.fields__slug}.js
  packages/gatsby-plugin-mdx/README.md
  packages/gatsby/src/query/__tests__/__snapshots__/query-compiler.js.snap
  packages/gatsby/src/query/__tests__/query-compiler.js
  packages/gatsby/src/query/query-compiler.js
Labels: topic: core

#36583 fix(gatsby-parcel-config): Adjust dependencies
  packages/gatsby-parcel-config/lib/index.json
  packages/gatsby-parcel-config/package.json
  yarn.lock
Labels: topic: core

#36640 chore: More Node 18 bumps
  packages/gatsby-cli/src/__tests__/index.ts
  packages/gatsby-cli/src/index.ts
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
Labels: type: maintenance

#36450 feat(gatsby): Enable source maps when compiling Gatsby files in development
  docs/docs/debugging-the-build-process.md
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
Labels: topic: DX

#36556 feat(gatsby,gatsby-cli): Partial hydration error handling
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/utils/worker/child/render-html.ts
Labels: topic: core

#36612 Add docs for Slices API
  docs/docs/reference/built-in-components/gatsby-slice.md
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/actions/restricted.ts
Labels: type: documentation

#36646 chore(docs): Update monorepo docs
  docs/docs/reference/cloud/monorepos.md
Labels: status: triage needed

#36647 chore(gatsby): minor typo fix
  packages/gatsby/src/redux/persist.ts
Labels: type: maintenance

#36648 fix(gatsby-core-utils): Use `grep -E` instead of `egrep`
  packages/gatsby-core-utils/src/physical-cpu-count.ts
Labels: topic: core

#36627 chore(docs): Update storybook main.js docs
  docs/docs/how-to/testing/visual-testing-with-storybook.md
Labels: type: documentation

#36654 chore: Partytown CDN URL
  e2e-tests/development-runtime/gatsby-script-scripts.js
Labels: topic: automation

#36485 feat(gatsby): add partial hydration
  jest.config.js
  packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby-plugin-mdx/src/__tests__/compile-mdx.ts
  packages/gatsby-plugin-mdx/src/__tests__/gatsby-layout-loader.ts
  packages/gatsby-plugin-mdx/src/__tests__/gatsby-mdx-loader.ts
  packages/gatsby-plugin-mdx/src/__tests__/remark-mdx-html-plugin.ts
  packages/gatsby-worker/src/index.ts
  packages/gatsby/cache-dir/gatsby-browser-entry.js
  packages/gatsby/cache-dir/loader.js
  packages/gatsby/cache-dir/page-renderer.js
  packages/gatsby/cache-dir/production-app.js
  packages/gatsby/cache-dir/static-entry.js
  packages/gatsby/package.json
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/commands/build.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/__snapshots__/partial-hydration-reference-loader.ts.snap
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/cjs-exports.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/cjs-module-exports.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-aggregation.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-declaration.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-class-anonymous.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-class-named.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-expression.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-function-anonymous.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-default-function-named.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/esm-list.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/no-client-export-no-export.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/fixtures/no-client-export.js
  packages/gatsby/src/utils/webpack/loaders/__tests__/partial-hydration-reference-loader.ts
  packages/gatsby/src/utils/webpack/loaders/partial-hydration-reference-loader.ts
  packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts
  packages/gatsby/src/utils/worker/child/index.ts
  packages/gatsby/src/utils/worker/child/render-html.ts
  yarn.lock
Labels: topic: core, topic: frontend

#36623 fix(gatsby-plugin-page-creator): update pages when nodes change
  e2e-tests/development-runtime/cypress/integration/unified-routing/collection-routing.js
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/plugins/gatsby-source-fs-route-mutations/gatsby-node.ts
  e2e-tests/development-runtime/plugins/gatsby-source-fs-route-mutations/index.js
  e2e-tests/development-runtime/plugins/gatsby-source-fs-route-mutations/package.json
  e2e-tests/development-runtime/src/pages/collection-routing/mutations/child-{FilesystemRoutesMutationChild.computed}.js
  e2e-tests/development-runtime/src/pages/collection-routing/mutations/child-{FilesystemRoutesMutationChild.slug}.js
  e2e-tests/development-runtime/src/pages/collection-routing/mutations/{FilesystemRoutesMutation.computed}.js
  e2e-tests/development-runtime/src/pages/collection-routing/mutations/{FilesystemRoutesMutation.slug}.js
  packages/gatsby-plugin-page-creator/src/__tests__/extract-query.ts
  packages/gatsby-plugin-page-creator/src/collection-extract-query-string.ts
  packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-changed-nodes.ts
  packages/gatsby-plugin-page-creator/src/create-pages-from-collection-builder.ts
  packages/gatsby-plugin-page-creator/src/extract-query.ts
  packages/gatsby-plugin-page-creator/src/gatsby-node.ts
  packages/gatsby-plugin-page-creator/src/tracked-nodes-state.ts
  packages/gatsby-plugin-page-creator/src/types.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/__snapshots__/load-plugins.ts.snap
Labels: topic: core, topic: data, topic: DX

#36585 feat(gatsby-plugin-utils): Encrypt image cdn image/file urls when env vars are present
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/__tests__/url-generator.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/url-generator.ts
Labels: topic: media

#36652 chore(gatsby-telemetry): Bump git-up to v7
  packages/gatsby-telemetry/package.json
  yarn.lock
Labels: type: maintenance

#36569 chore(gatsby): Remove <StaticQuery> component
  packages/babel-plugin-remove-graphql-queries/src/index.ts
  packages/gatsby/cache-dir/gatsby-browser-entry.js
  packages/gatsby/cache-dir/static-query.js
  packages/gatsby/src/query/file-parser.js
  packages/gatsby/src/query/query-watcher.ts
  packages/gatsby/src/redux/actions/internal.ts
  patches/v5/3-remove-static-query-component.patch
Labels: topic: core

#36662 chore(gatsby): Update react-refresh again
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#36664 fix(gatsby): Regression in shared chunks
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: core

#36668 feat(gatsby-plugin-gatsby-cloud): add total page count ipc
  packages/gatsby-plugin-gatsby-cloud/src/__tests__/routes.js
  packages/gatsby-plugin-gatsby-cloud/src/gatsby-node.js
  packages/gatsby-plugin-gatsby-cloud/src/ipc.js
Labels: topic: plugins

#36670 chore(gatsby-source-contentful): Correct image embed code sample
  packages/gatsby-source-contentful/README.md
Labels: topic: source-contentful

#36674 chore: Create static file server for e2e tests
  e2e-tests/development-runtime/gatsby-config.js
  e2e-tests/development-runtime/gatsby-script-scripts.js
  e2e-tests/development-runtime/package.json
  e2e-tests/development-runtime/playwright.config.ts
  e2e-tests/development-runtime/playwright/gatsby-script-off-main-thread.spec.ts
  e2e-tests/development-runtime/serve-static-files.mjs
  e2e-tests/development-runtime/static/j-query.js
  e2e-tests/development-runtime/static/marked.js
  e2e-tests/development-runtime/static/popper.js
  e2e-tests/development-runtime/static/three.js
  e2e-tests/production-runtime/gatsby-config.js
  e2e-tests/production-runtime/gatsby-script-scripts.js
  e2e-tests/production-runtime/package.json
  e2e-tests/production-runtime/playwright.config.ts
  e2e-tests/production-runtime/playwright/gatsby-script-off-main-thread.spec.ts
  e2e-tests/production-runtime/serve-static-files.mjs
  e2e-tests/production-runtime/static/j-query.js
  e2e-tests/production-runtime/static/marked.js
  e2e-tests/production-runtime/static/popper.js
  e2e-tests/production-runtime/static/three.js
Labels: type: maintenance

#36661 fix(gatsby): Wrap `WrapRootElement` before rendering slice
  packages/gatsby/cache-dir/static-entry.js
Labels: type: feature or enhancement

#36649 chore(gatsby-dev-cli): Upgrade to verdaccio v5
  packages/gatsby-dev-cli/package.json
  yarn.lock
Labels: type: maintenance

#36676 fix(gatsby): Add back missing partial hydration error handling change
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/commands/build-html.ts
Labels: topic: core

#36644 feat(gatsby): Normalize module keys between webpack plugin and loader
  packages/gatsby/src/utils/webpack/loaders/partial-hydration-reference-loader.ts
  packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts
  packages/gatsby/src/utils/webpack/utils/__tests__/__snapshots__/create-normalized-module-key.ts.snap
  packages/gatsby/src/utils/webpack/utils/__tests__/create-normalized-module-key.ts
  packages/gatsby/src/utils/webpack/utils/create-normalized-module-key.ts
Labels: topic: core

#36701 fix(gatsby): Use hex hash for CSS modules
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: webpack/babel, topic: core

#36705 chore(docs): add showcase link to 4.24 release notes
  docs/docs/reference/release-notes/v4.24/index.md
Labels: type: documentation

#36707 update react peer deps patch
  patches/v5/0-gatsby-peerdeps.patch
Labels: status: triage needed

#36693 fix(gatsby): Persist manifest on cached builds
  packages/gatsby-cli/src/structured-errors/error-map.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts
Labels: topic: webpack/babel, topic: core

#36616 feat(gatsby): Partial hydration router integration
  packages/gatsby-link/index.d.ts
  packages/gatsby/cache-dir/navigation.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/index.d.ts
  packages/gatsby/src/commands/build-html.ts
  packages/gatsby/src/utils/get-server-data.ts
  packages/gatsby/src/utils/webpack.config.js
  packages/gatsby/src/utils/worker/child/render-html.ts
  patches/v5/4-upgrade-reach-router.patch
  yarn.lock
Labels: topic: core

#36708 feat: [v5 breaking change] change sort and aggregation fields API
  packages/gatsby-codemods/package.json
  packages/gatsby-codemods/src/bin/__tests__/gatsby-codemods-test.js
  packages/gatsby-codemods/src/bin/cli.js
  packages/gatsby-codemods/src/transforms/__tests__/sort-and-aggr-graphql.ts
  packages/gatsby-codemods/src/transforms/sort-and-aggr-graphql.ts
  packages/gatsby/src/query/__tests__/transform-documents.ts
  packages/gatsby/src/query/graphql-runner.ts
  packages/gatsby/src/query/query-compiler.js
  packages/gatsby/src/query/transform-document.ts
  packages/gatsby/src/schema/resolvers.ts
  packages/gatsby/src/schema/schema.js
  packages/gatsby/src/schema/types/filter.ts
  packages/gatsby/src/schema/types/pagination.ts
  packages/gatsby/src/schema/types/sort.ts
  packages/gatsby/src/schema/types/utils.ts
  yarn.lock
Labels: topic: GraphQL

#36718 chore: regen v5 patches
  packages/gatsby-codemods/package.json
  patches/v5/4-upgrade-reach-router.patch
Labels: type: maintenance
