Repository gatsbyjs/gatsby, pull requests merged in 2023-07, with the labels that each got.

#38337 fix(gatsby): copy slices overrides to 404.html copy
  e2e-tests/development-runtime/cypress/integration/slices/slice-via-create-page.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/src/components/mapped-slice.js
  e2e-tests/development-runtime/src/pages/404.js
  e2e-tests/production-runtime/cypress/integration/slices/slice-via-create-page.js
  e2e-tests/production-runtime/gatsby-node.ts
  e2e-tests/production-runtime/src/components/mapped-slice.js
  e2e-tests/production-runtime/src/pages/404.js
  packages/gatsby/src/internal-plugins/prod-404-500/gatsby-node.js
Labels: topic: core

#38341 fix(gatsby-source-wordpress): Set empty default alt tag for inline images
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
Labels: topic: source-wordpress, topic: source-plugins

#38373 docs: update `npm-cache` directory location
  docs/docs/how-to/local-development/gatsby-on-windows.md
Labels: type: documentation
