Repository gatsbyjs/gatsby, pull requests merged in 2023-01, with the labels that each got.

#37331 test(validate-starters): use `npm ci --legacy-peer-deps` and fail the test if npm fails
  scripts/validate-starters.sh
Labels: type: maintenance

#37347 chore(docs): fix typo in reference guide
  docs/docs/reference/built-in-components/gatsby-slice.md
Labels: type: documentation

#37341 docs(how-to): remove unecessary decomposition
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: type: documentation

#37395 fix(gatsby-remark-images): Do not fallback title value to alt value
  packages/gatsby-remark-images/src/__tests__/__snapshots__/index.js.snap
  packages/gatsby-remark-images/src/index.js
Labels: topic: remark/mdx

#37332 chore(docs): Add `--legacy-peer-deps` flag for experimental React
  docs/docs/how-to/performance/partial-hydration.md
Labels: type: documentation

#37321 chore(docs): Update Storybook instructions
  docs/docs/how-to/testing/visual-testing-with-storybook.md
Labels: type: documentation

#37402 chore(docs): Add wrapRootElement limitation to off-main-thread
  docs/docs/reference/built-in-components/gatsby-script.md
Labels: type: documentation

#37336 chore: Update `.gitpod` to use correct Node version
  .gitpod.Dockerfile
Labels: topic: automation

#37403 fix(gatsby-source-contentful): Add contentTypeFilter to Joi schema
  packages/gatsby-source-contentful/src/gatsby-node.js
Labels: topic: source-contentful

#37407 chore(deps): Bump yaml-loader (#37401)
  packages/gatsby/package.json
  yarn.lock
Labels: type: cherry

#36712 fix(gatsby): Allow "gatsby-node" directory for Parcel Compilation
  packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/gatsby-node-as-directory/gatsby-node.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/gatsby-node-as-directory/gatsby-node/on-pre-init.ts
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
Labels: topic: TypeScript

#37409 chore(gatsby): Improve SlicePlaceholderProps type
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#37411 chore(docs): Fix `ts-jest` import statement in Unit Testing Guide
  docs/docs/how-to/testing/unit-testing.md
Labels: type: documentation

#37424 fix(gatsby-source-wordpress): Force removal of types
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/write-queries-to-disk.js
Labels: topic: source-wordpress

#37421 chore(deps): Bump partytown
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#37423 fix(gatsby-plugin-mdx): Default remark node to span
  packages/gatsby-plugin-mdx/src/__tests__/remark-mdx-html-plugin.ts
  packages/gatsby-plugin-mdx/src/remark-mdx-html-plugin.ts
Labels: topic: remark/mdx

#37231 chore(docs): Update "Minimal Reproduction" instructions
  docs/contributing/how-to-make-a-reproducible-test-case.md
Labels: type: documentation

#37408 chore: Upgrade to Jest 29
  .jestSetup.js
  docs/docs/how-to/testing/testing-react-components.md
  docs/docs/how-to/testing/unit-testing.md
  integration-tests/artifacts/jest.config.js
  integration-tests/artifacts/package.json
  integration-tests/cache-resilience/jest.config.js
  integration-tests/cache-resilience/package.json
  integration-tests/esm-in-gatsby-files/package.json
  integration-tests/functions/jest.config.js
  integration-tests/functions/package.json
  integration-tests/gatsby-cli/package.json
  integration-tests/gatsby-pipeline/package.json
  integration-tests/gatsby-source-wordpress/jest.config.js
  integration-tests/gatsby-source-wordpress/package.json
  integration-tests/head-function-export/package.json
  integration-tests/images/jest.config.js
  integration-tests/images/package.json
  integration-tests/long-term-caching/package.json
  integration-tests/node-manifest/package.json
  integration-tests/ssr/jest.config.js
  integration-tests/ssr/package.json
  integration-tests/structured-logging/jest.config.js
  integration-tests/structured-logging/package.json
  jest.config.js
  jest.environment.ts
  package.json
  packages/gatsby-cli/src/reporter/__tests__/__snapshots__/index.ts.snap
  packages/gatsby-plugin-google-analytics/src/__tests__/gatsby-browser.js
  packages/gatsby-source-wordpress/__tests__/plugin-options-schema.test.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js
  packages/gatsby/src/utils/__tests__/get-page-data.ts
  yarn.lock
Labels: type: maintenance, topic: automation

#37406 chore: Upgrade some non-breaking major versions
  integration-tests/artifacts/package.json
  integration-tests/esm-in-gatsby-files/package.json
  package.json
  packages/create-gatsby/package.json
  packages/gatsby-cli/package.json
  packages/gatsby-codemods/package.json
  packages/gatsby-core-utils/package.json
  packages/gatsby-dev-cli/package.json
  packages/gatsby-legacy-polyfills/package.json
  packages/gatsby-plugin-emotion/package.json
  packages/gatsby-plugin-feed/package.json
  packages/gatsby-plugin-gatsby-cloud/package.json
  packages/gatsby-plugin-image/package.json
  packages/gatsby-plugin-mdx/package.json
  packages/gatsby-plugin-offline/package.json
  packages/gatsby-plugin-page-creator/package.json
  packages/gatsby-plugin-preload-fonts/package.json
  packages/gatsby-plugin-sharp/package.json
  packages/gatsby-plugin-utils/package.json
  packages/gatsby-remark-copy-linked-files/package.json
  packages/gatsby-source-contentful/package.json
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-telemetry/package.json
  packages/gatsby-transformer-screenshot/lambda/package.json
  packages/gatsby-transformer-sharp/package.json
  packages/gatsby-transformer-sqip/package.json
  packages/gatsby-transformer-yaml/package.json
  packages/gatsby-worker/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: type: maintenance

#37429 fix(gatsby): Restore asset, path prefix for file-loader handled files
  e2e-tests/path-prefix/cypress/integration/asset-prefix.js
  e2e-tests/path-prefix/cypress/integration/path-prefix.js
  e2e-tests/path-prefix/package.json
  e2e-tests/path-prefix/src/pages/file-loader.js
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: render-mode

#37435 fix(gatsby-source-drupal): await async handleDeletedNode
  packages/gatsby-source-drupal/src/gatsby-node.js
Labels: bot: merge on green, topic: source-drupal

#37410 fix(gatsby): Prevent escape on style tags content
  integration-tests/head-function-export/__tests__/ssr-html-output.js
  integration-tests/head-function-export/shared-data/head-function-export.js
  integration-tests/head-function-export/src/pages/head-function-export/basic.js
  packages/gatsby/cache-dir/head/head-export-handler-for-ssr.js
Labels: topic: core

#37397 fix(gatsby-source-shopify): Use `id` as cacheKey for base64 image
  packages/gatsby-source-shopify/src/resolve-gatsby-image-data.ts
Labels: topic: source-shopify, topic: source-plugins

#37337 fix(gatsby): Update `loader.loadPage` to return a Promise on error
  packages/gatsby/cache-dir/loader.js
Labels: topic: core

#37440 fix(gatsby): Support ESM-only `gatsby-remark-*` plugins
  integration-tests/esm-in-gatsby-files/.gitignore
  integration-tests/esm-in-gatsby-files/__tests__/fixtures/gatsby-config.js
  integration-tests/esm-in-gatsby-files/__tests__/fixtures/gatsby-config.mjs
  integration-tests/esm-in-gatsby-files/__tests__/fixtures/plugins/gatsby-remark-cjs/index.js
  integration-tests/esm-in-gatsby-files/__tests__/fixtures/plugins/gatsby-remark-cjs/package.json
  integration-tests/esm-in-gatsby-files/__tests__/fixtures/plugins/gatsby-remark-esm/index.js
  integration-tests/esm-in-gatsby-files/__tests__/fixtures/plugins/gatsby-remark-esm/package.json
  integration-tests/esm-in-gatsby-files/__tests__/gatsby-config.test.js
  integration-tests/esm-in-gatsby-files/package.json
  packages/gatsby/babel.config.js
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: topic: core

#37445 feat(gatsby-source-drupal): drupal langcode as notlangcode
  packages/gatsby-source-drupal/.babelrc
  packages/gatsby-source-drupal/.eslintrc
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.ts
  packages/gatsby-source-drupal/src/normalize.ts
  packages/gatsby-source-drupal/src/plugin-options.js
  packages/gatsby-source-drupal/src/plugin-options.ts
  packages/gatsby-source-drupal/src/utils.ts
Labels: bot: merge on green, topic: source-drupal

#37444 chore(gatsby-plugin-preload-fonts): don't transpile mocks
  packages/gatsby-plugin-preload-fonts/package.json
Labels: type: maintenance

#35081 fix(gatsby): Multi-environment browserslist configs
  packages/gatsby/src/utils/__tests__/browserslist.js
  packages/gatsby/src/utils/browserslist.ts
Labels: topic: core

#37443 fix(gatsby): pluginOptionsSchema in local TS plugin
  e2e-tests/development-runtime/plugins/gatsby-node-typegen/gatsby-node.ts
  packages/gatsby/src/bootstrap/load-plugins/__tests__/load-plugins.ts
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: topic: TypeScript

#37442 fix(gatsby-source-contentful): maintain back reference map between runs
  packages/gatsby-source-contentful/src/__fixtures__/preserve-back-links.js
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/source-nodes.js
Labels: topic: source-contentful

#37454 fix(gatsby): Use correct settings for yaml-loader
  e2e-tests/development-runtime/cypress/integration/functionality/yaml.js
  e2e-tests/development-runtime/src/pages/webpack-loader/yaml.js
  e2e-tests/development-runtime/src/test-files/input.yaml
  packages/gatsby/src/utils/webpack-utils.ts
Labels: topic: webpack/babel

#37451 fix(gatsby): Check rawPath in loadPage
  packages/gatsby/cache-dir/loader.js
Labels: topic: core

#37465 docs: fix v5 release notes slice example
  docs/docs/reference/release-notes/v5.0/index.md
Labels: type: documentation

#37462 feat(gatsby-source-drupal): drupal langcode as notlangcode (#37445)
  packages/gatsby-source-drupal/.babelrc
  packages/gatsby-source-drupal/.eslintrc
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.ts
  packages/gatsby-source-drupal/src/normalize.ts
  packages/gatsby-source-drupal/src/plugin-options.js
  packages/gatsby-source-drupal/src/plugin-options.ts
  packages/gatsby-source-drupal/src/utils.ts
Labels: type: cherry

#37459 feat(gatsby-source-drupal): drupal langcode as notlangcode (#37445)
  packages/gatsby-source-drupal/.babelrc
  packages/gatsby-source-drupal/.eslintrc
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/package.json
  packages/gatsby-source-drupal/src/__tests__/index.js
  packages/gatsby-source-drupal/src/gatsby-node.ts
  packages/gatsby-source-drupal/src/normalize.ts
  packages/gatsby-source-drupal/src/plugin-options.js
  packages/gatsby-source-drupal/src/plugin-options.ts
  packages/gatsby-source-drupal/src/utils.ts
  yarn.lock
Labels: type: cherry

#37433 feat(gatsby-core-utils): Add hashing methods from `hash-wasm`
  packages/gatsby-core-utils/README.md
  packages/gatsby-core-utils/package.json
  packages/gatsby-core-utils/src/hash.ts
  packages/gatsby-core-utils/src/index.ts
  packages/gatsby-core-utils/src/md5-file.ts
  packages/gatsby/package.json
  packages/gatsby/src/bootstrap/load-plugins/utils/create-hash.ts
  packages/gatsby/src/bootstrap/redirects-writer.ts
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/query/file-parser.js
  packages/gatsby/src/query/graphql-runner.ts
  packages/gatsby/src/query/query-runner.ts
  packages/gatsby/src/services/initialize.ts
  packages/gatsby/src/utils/worker/__tests__/queries.ts
  yarn.lock
Labels: topic: performance, topic: core

#37476 chore(docs): Adds Kinsta Application hosting to other services
  docs/docs/how-to/previews-deploys-hosting/deploying-to-other-services.md
Labels: type: documentation

#37477 fix(gatsby): nodeModel.findAll supports v5 sort argument structure
  packages/gatsby/src/schema/__tests__/node-model.js
  packages/gatsby/src/schema/node-model.js
  packages/gatsby/src/schema/resolvers.ts
  packages/gatsby/src/schema/utils.ts
Labels: topic: GraphQL

#37464 feat(gatsby-source-filesystem): Only generate hashes when a file has changed, and add an option for skipping hashing
  packages/gatsby-source-filesystem/README.md
  packages/gatsby-source-filesystem/package.json
  packages/gatsby-source-filesystem/src/__tests__/create-file-node.js
  packages/gatsby-source-filesystem/src/create-file-node.js
  packages/gatsby-source-filesystem/src/gatsby-node.js
Labels: topic: source-plugins

#37480 chore(gatsby-source-filesystem): Improve README
  packages/gatsby-source-filesystem/README.md
Labels: type: documentation, topic: source-plugins

#37492 fix(gatsby-source-wordpress): fix preview issues
  packages/gatsby-source-wordpress/src/steps/source-nodes/index.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
Labels: topic: source-wordpress

#37485 chore(docs): Improve v5 migration guide around MDX
  docs/docs/reference/release-notes/migrating-from-v4-to-v5.md
  packages/gatsby-plugin-mdx/README.md
Labels: type: documentation

#37497 chore(gatsby): bump socket.io (#37272)
  packages/gatsby/package.json
  yarn.lock
Labels: type: cherry

#37449 feat(gatsby): Allow `<html>` and `<body>` attributes to be updated from `Head`
  e2e-tests/development-runtime/cypress/integration/head-function-export/html-and-body-attributes.js
  e2e-tests/development-runtime/shared-data/head-function-export.js
  e2e-tests/development-runtime/src/pages/head-function-export/html-and-body-attributes.js
  e2e-tests/production-runtime/cypress/integration/head-function-export/html-and-body-attributes.js
  e2e-tests/production-runtime/cypress/integration/head-function-export/html-insertion.js
  e2e-tests/production-runtime/shared-data/head-function-export.js
  e2e-tests/production-runtime/src/pages/head-function-export/html-and-body-attributes.js
  integration-tests/head-function-export/__tests__/ssr-html-output.js
  integration-tests/head-function-export/shared-data/head-function-export.js
  integration-tests/head-function-export/src/pages/head-function-export/html-and-body-attributes.js
  integration-tests/ssr/__tests__/ssr.js
  integration-tests/ssr/src/pages/head-function-export.js
  packages/gatsby/cache-dir/head/constants.js
  packages/gatsby/cache-dir/head/head-export-handler-for-browser.js
  packages/gatsby/cache-dir/head/head-export-handler-for-ssr.js
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: DX

#37498 fix(gatsby-react-router-scroll): fix issues with anchor links
  packages/gatsby-react-router-scroll/src/scroll-handler.tsx
Labels: topic: frontend

#37500 fix(gatsby): pass serverData to Head
  e2e-tests/development-runtime/cypress/integration/head-function-export/html-insertion.js
  e2e-tests/development-runtime/shared-data/head-function-export.js
  e2e-tests/development-runtime/src/pages/head-function-export/ssr.js
  e2e-tests/production-runtime/cypress/integration/head-function-export/html-insertion.js
  e2e-tests/production-runtime/shared-data/head-function-export.js
  e2e-tests/production-runtime/src/pages/head-function-export/ssr.js
  packages/gatsby/cache-dir/__tests__/head/utils.js
  packages/gatsby/cache-dir/head/utils.js
  packages/gatsby/index.d.ts
Labels: topic: DX

#37478 feat(gatsby): add initial webhook body env var to bootstrap context
  packages/gatsby/src/services/initialize.ts
Labels: topic: source-plugins

#37503 chore(docs): set the timestamp for the lastFetch to when the fetch starts
  docs/docs/how-to/plugins-and-themes/creating-a-source-plugin.md
Labels: type: documentation

#37510 chore(docs): Update slices how-to to reference enterprise tier
  docs/docs/how-to/performance/using-slices.md
Labels: type: documentation

#37521 chore(docs): Clarify Unified Hosting is built on top of Gatsby Cloud Hosting
  docs/docs/how-to/cloud/unified-hosting.md
Labels: type: documentation

#37520 fix(gatsby): Use windows import helper for validate
  packages/gatsby/src/bootstrap/load-plugins/validate.ts
Labels: topic: core

#37484 chore(docs): Update "Sourcing from Kontent.ai"
  docs/docs/how-to/sourcing-data/sourcing-from-kontent-ai.md
  docs/docs/sourcing-from-kentico-kontent.md
Labels: type: documentation

#37508 fix(gatsby): Move "react-dom-server" out of framework chunk
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: webpack/babel

#37525 chore(docs): Update gatsby-slice.md to reference styled components non-support
  docs/docs/reference/built-in-components/gatsby-slice.md
Labels: type: documentation

#37491 chore(docs): Update Head API about `<html>` and `<body>` attributes
  docs/docs/reference/built-in-components/gatsby-head.md
  examples/using-gatsby-head/gatsby-ssr.tsx
  examples/using-gatsby-head/src/components/seo.tsx
Labels: type: documentation

#37439 feat(gatsby): Safely wrap `Head` with `wrapRootElement`
  e2e-tests/development-runtime/cypress/integration/head-function-export/correct-props.js
  e2e-tests/development-runtime/cypress/integration/head-function-export/head-with-wrap-root-element.js
  e2e-tests/development-runtime/cypress/integration/head-function-export/warnings.js
  e2e-tests/development-runtime/gatsby-node.js
  e2e-tests/development-runtime/shared-data/head-function-export.js
  e2e-tests/development-runtime/src/app-context.js
  e2e-tests/development-runtime/src/components/footer.js
  e2e-tests/development-runtime/src/context-for-slices.js
  e2e-tests/development-runtime/src/pages/head-function-export/head-with-wrap-root-element.js
  e2e-tests/development-runtime/src/wrap-root-element.js
  e2e-tests/production-runtime/cypress/integration/head-function-export/head-with-wrap-root-element.js
  e2e-tests/production-runtime/shared-data/head-function-export.js
  e2e-tests/production-runtime/src/app-context.js
  e2e-tests/production-runtime/src/components/footer.js
  e2e-tests/production-runtime/src/context-for-slices.js
  e2e-tests/production-runtime/src/pages/head-function-export/head-with-wrap-root-element.js
  e2e-tests/production-runtime/src/wrap-root-element.js
  integration-tests/head-function-export/__tests__/ssr-html-output.js
  integration-tests/head-function-export/gatsby-browser.js
  integration-tests/head-function-export/gatsby-ssr.js
  integration-tests/head-function-export/shared-data/head-function-export.js
  integration-tests/head-function-export/src/contexts.js
  integration-tests/head-function-export/src/pages/head-function-export/head-with-wrap-root-element.js
  packages/gatsby/cache-dir/head/head-export-handler-for-browser.js
  packages/gatsby/cache-dir/head/head-export-handler-for-ssr.js
  packages/gatsby/cache-dir/head/utils.js
Labels: topic: DX

#37532 fix(gatsby-plugin-utils): Export two `IRemoteFile` utility types
  packages/gatsby-plugin-utils/src/index.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/types.ts
Labels: topic: TypeScript

#37534 fix(gatsby): Render to pipeable stream in dev SSR
  packages/gatsby/cache-dir/ssr-develop-static-entry.js
Labels: topic: frontend

#37452 chore: Adjust jest environment conditionally for OS
  jest.environment.ts
Labels: type: maintenance

#37546 chore: Update using-remark example
  examples/using-remark/src/pages/author.yaml
Labels: type: maintenance

#37544 fix(gatsby): fix static query mapping when contentFilePath contains a space
  e2e-tests/mdx/cypress/integration/fs-api.js
  e2e-tests/mdx/src/pages/file with space.mdx
  e2e-tests/mdx/src/pages/file+with+plus.mdx
  e2e-tests/mdx/src/pages/fs-api/plus+and+static+query/{Mdx.fields__slug}.js
  e2e-tests/mdx/src/pages/fs-api/space and static query/{Mdx.fields__slug}.js
  packages/gatsby/src/utils/webpack/plugins/__tests__/static-query-mapper.ts
  packages/gatsby/src/utils/webpack/plugins/static-query-mapper.ts
Labels: topic: GraphQL

#37547 chore(gatsby): bump @gatsbyjs/reach-router
  packages/gatsby-script/package.json
  packages/gatsby/package.json
  yarn.lock
Labels: bot: merge on green, topic: frontend

#37486 chore(gatsby-source-wordpress): Fix apostrophe typos
  packages/gatsby-source-wordpress/docs/plugin-options.md
  packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.js
Labels: type: documentation, topic: source-wordpress, topic: source-plugins
