Repository gatsbyjs/gatsby, pull requests merged in 2023-12, with the labels that each got.

#38733 chore: bump caniuse-lite
  yarn.lock
Labels: type: maintenance

#38735 feat: provide custom FILE_CDN url generator from adapter
  .circleci/config.yml
  e2e-tests/adapters/cypress/e2e/remote-file.cy.ts
  e2e-tests/adapters/gatsby-node.ts
  e2e-tests/adapters/package.json
  e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
  e2e-tests/adapters/src/pages/index.jsx
  e2e-tests/adapters/src/pages/routes/remote-file.jsx
  e2e-tests/adapters/src/pages/routes/ssr/remote-file.jsx
  e2e-tests/adapters/src/templates/remote-file-from-context.jsx
  packages/gatsby-adapter-netlify/package.json
  packages/gatsby-adapter-netlify/src/__tests__/file-cdn-url-generator.ts
  packages/gatsby-adapter-netlify/src/__tests__/image-cdn-url-generator.ts
  packages/gatsby-adapter-netlify/src/file-cdn-handler.ts
  packages/gatsby-adapter-netlify/src/file-cdn-url-generator.ts
  packages/gatsby-adapter-netlify/src/index.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/public-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/public-url-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/dispatchers.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/types.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/__tests__/url-generator.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/url-generator.ts
  packages/gatsby/index.d.ts
  packages/gatsby/src/utils/adapter/manager.ts
  packages/gatsby/src/utils/adapter/types.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
  packages/gatsby/src/utils/page-ssr-module/lambda.ts
  types/gatsby-monorepo/global.d.ts
  yarn.lock
Labels: topic: media

#38716 fix(contentful): rich text linked asset filter
  packages/gatsby-source-contentful/src/create-schema-customization.ts
Labels: topic: source-contentful

#38719 feat: allow adding remote file allowed url patterns
  e2e-tests/adapters/cypress/e2e/remote-file.cy.ts
  e2e-tests/adapters/gatsby-node.ts
  e2e-tests/adapters/src/pages/routes/remote-file.jsx
  e2e-tests/adapters/src/pages/routes/ssr/remote-file.jsx
  e2e-tests/adapters/src/templates/remote-file-from-context.jsx
  packages/gatsby-adapter-netlify/.babelrc
  packages/gatsby-adapter-netlify/package.json
  packages/gatsby-adapter-netlify/src/allowed-remote-urls.ts
  packages/gatsby-adapter-netlify/src/file-cdn-handler.ts
  packages/gatsby-adapter-netlify/src/file-cdn-url-generator.ts
  packages/gatsby-adapter-netlify/src/index.ts
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-drupal/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/steps/add-remote-file-allowed-url.ts
  packages/gatsby-source-wordpress/src/steps/index.ts
  packages/gatsby/index.d.ts
  packages/gatsby/package.json
  packages/gatsby/src/redux/actions/restricted.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/remote-file-allowed-urls.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/adapter/manager.ts
  packages/gatsby/src/utils/adapter/types.ts
  yarn.lock
Labels: topic: media

#38685 feat: image and file cdn url generator adapter implementation
  .circleci/config.yml
  e2e-tests/adapters/cypress/e2e/remote-file.cy.ts
  e2e-tests/adapters/gatsby-config.ts
  e2e-tests/adapters/gatsby-node.ts
  e2e-tests/adapters/netlify.toml
  e2e-tests/adapters/package.json
  e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
  e2e-tests/adapters/src/pages/index.jsx
  e2e-tests/adapters/src/pages/routes/remote-file.jsx
  e2e-tests/adapters/src/pages/routes/ssr/remote-file.jsx
  e2e-tests/adapters/src/templates/remote-file-from-context.jsx
  e2e-tests/production-runtime/cypress/integration/remote-file.js
  packages/gatsby-adapter-netlify/.babelrc
  packages/gatsby-adapter-netlify/README.md
  packages/gatsby-adapter-netlify/package.json
  packages/gatsby-adapter-netlify/src/__tests__/file-cdn-url-generator.ts
  packages/gatsby-adapter-netlify/src/__tests__/image-cdn-url-generator.ts
  packages/gatsby-adapter-netlify/src/allowed-remote-urls.ts
  packages/gatsby-adapter-netlify/src/file-cdn-handler.ts
  packages/gatsby-adapter-netlify/src/file-cdn-url-generator.ts
  packages/gatsby-adapter-netlify/src/image-cdn-url-generator.ts
  packages/gatsby-adapter-netlify/src/index.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/public-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/__tests__/resize-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/public-url-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/resize-resolver.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/jobs/dispatchers.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/types.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/__tests__/url-generator.ts
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/url-generator.ts
  packages/gatsby-source-contentful/src/gatsby-node.js
  packages/gatsby-source-drupal/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/steps/add-remote-file-allowed-url.ts
  packages/gatsby-source-wordpress/src/steps/index.ts
  packages/gatsby/index.d.ts
  packages/gatsby/package.json
  packages/gatsby/src/redux/actions/restricted.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/remote-file-allowed-urls.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/adapter/manager.ts
  packages/gatsby/src/utils/adapter/types.ts
  packages/gatsby/src/utils/page-ssr-module/bundle-webpack.ts
  packages/gatsby/src/utils/page-ssr-module/lambda.ts
  types/gatsby-monorepo/global.d.ts
  yarn.lock
Labels: topic: media

#38758 fix(gatsby): allow gatsby-adapter-netlify@">=1.0.0 <=1.0.3" for gatsby@<5.12.10
  packages/gatsby/adapters.js
Labels: bot: merge on green, topic: adapters

#38759 chore(docs): Release Notes for 5.13
  docs/docs/reference/release-notes/v5.13/index.md
Labels: type: documentation

#38763 chore(adapters): update readme
  e2e-tests/adapters/README.md
Labels: type: documentation, type: maintenance, bot: merge on green

#38764 fix(gatsby): Restore asset, path prefix for file-loader handled files
  e2e-tests/path-prefix/cypress/integration/asset-prefix.js
  e2e-tests/path-prefix/cypress/integration/path-prefix.js
  e2e-tests/path-prefix/package.json
  e2e-tests/path-prefix/src/pages/file-loader.js
  packages/gatsby/src/utils/webpack-utils.ts
Labels: type: cherry

#38775 chore(gatsby-cli,gatsby-source-wordpress): bump clipboardy
  packages/gatsby-cli/.babelrc
  packages/gatsby-cli/package.json
  packages/gatsby-cli/src/create-cli.ts
  packages/gatsby-source-wordpress/.babelrc.js
  packages/gatsby-source-wordpress/package.json
  packages/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/generate-queries-from-ingestable-types.js
  packages/gatsby-source-wordpress/src/utils/fetch-graphql.ts
  yarn.lock
Labels: type: maintenance, bot: merge on green
