Repository gatsbyjs/gatsby, pull requests merged in 2023-04, with the labels that each got.

#37813 chore(docs): update broken relay compiler link
  docs/docs/conceptual/graphql-concepts.md
Labels: type: documentation

#37812 chore(gatsby-remark-autolink-headers): Fix typo in README
  packages/gatsby-remark-autolink-headers/README.md
Labels: topic: plugins

#37911 fix(gatsby-transformer-sqip): Use correct cache location
  packages/gatsby-transformer-sqip/src/extend-node-type.js
Labels: topic: plugins

#37912 chore(examples): remove outdated wordpress examples
  examples/using-wordpress-with-acf/README.md
  examples/using-wordpress-with-acf/gatsby-config.js
  examples/using-wordpress-with-acf/gatsby-node.js
  examples/using-wordpress-with-acf/package.json
  examples/using-wordpress-with-acf/src/components/post-icons.js
  examples/using-wordpress-with-acf/src/layouts/index.js
  examples/using-wordpress-with-acf/src/pages/index.js
  examples/using-wordpress-with-acf/src/templates/page.js
  examples/using-wordpress-with-acf/src/templates/post.js
  examples/using-wordpress-with-acf/src/utils/typography.js
  examples/using-wordpress/README.md
  examples/using-wordpress/gatsby-config.js
  examples/using-wordpress/gatsby-node.js
  examples/using-wordpress/package.json
  examples/using-wordpress/src/pages/index.js
  examples/using-wordpress/src/templates/page.js
  examples/using-wordpress/src/templates/post.js
Labels: type: maintenance

#37782 feat(gatsby, gatsby-source-contentful): add public action to disable stale node checks
  docs/docs/node-creation.md
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/normalize.js
  packages/gatsby-source-contentful/src/source-nodes.js
  packages/gatsby/index.d.ts
  packages/gatsby/scripts/__tests__/api.js
  packages/gatsby/scripts/output-api-file.js
  packages/gatsby/src/datastore/__tests__/nodes.js
  packages/gatsby/src/query/__tests__/data-tracking.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/__tests__/nodes.ts
  packages/gatsby/src/redux/actions/public.js
  packages/gatsby/src/redux/index.ts
  packages/gatsby/src/redux/reducers/index.ts
  packages/gatsby/src/redux/reducers/stateful-source-plugins.ts
  packages/gatsby/src/redux/reducers/type-owners.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/services/__tests__/source-nodes.ts
  packages/gatsby/src/utils/api-runner-node.js
  packages/gatsby/src/utils/source-nodes.ts
  yarn.lock
Labels: topic: source-contentful, topic: source-plugins, topic: data

#37924 chore(docs): Update "Set Node.js version" cloud
  docs/docs/how-to/cloud/set-node-version.md
Labels: type: documentation

#37916 fix(gatsby-plugin-sitemap): remove splice for default filter
  packages/gatsby-plugin-sitemap/src/__tests__/internals.js
  packages/gatsby-plugin-sitemap/src/internals.js
Labels: topic: plugins

#37932 feat(gatsby-plugin-utils): make image cdn urls configurable
  packages/gatsby-plugin-utils/src/polyfill-remote-file/utils/url-generator.ts
Labels: topic: core

#37811 CTF-next: reverse references via linkedFrom field
  e2e-tests/contentful/snapshots.js
  e2e-tests/contentful/src/pages/content-reference.js
  packages/gatsby-source-contentful/jest.config.js
  packages/gatsby-source-contentful/src/__tests__/__snapshots__/create-schema-customization.js.snap
  packages/gatsby-source-contentful/src/__tests__/gatsby-node.js
  packages/gatsby-source-contentful/src/__tests__/normalize.js
  packages/gatsby-source-contentful/src/config.ts
  packages/gatsby-source-contentful/src/create-schema-customization.ts
  packages/gatsby-source-contentful/src/normalize.ts
  packages/gatsby-source-contentful/src/source-nodes.ts
  packages/gatsby-source-contentful/src/types/contentful.ts
Labels: status: triage needed

#37934 chore(docs): Add "ESM and Gatsby"
  docs/docs/how-to/custom-configuration/es-modules.md
  docs/docs/reference/config-files/gatsby-config.md
  docs/docs/reference/config-files/gatsby-node.md
  examples/using-mdx/gatsby-config.mjs
  examples/using-mdx/gatsby-node.mjs
  examples/using-mdx/package.json
  examples/using-mdx/remark-headings-plugin.js
  examples/using-mdx/remark-headings-plugin.mjs
  packages/gatsby-plugin-mdx/README.md
Labels: type: documentation

#37920 feat(gatsby-source-wordpress): opt out of stale node checks
  packages/gatsby-source-wordpress/src/steps/persist-cached-images.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/fetch-and-create-non-node-root-fields.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/index.ts
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/fetch-node-updates.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/delete.js
  packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
  packages/gatsby-source-wordpress/src/utils/gatsby-features.ts
Labels: topic: source-wordpress, topic: source-plugins

#37938 fix(gatsby): Shadowing with resourceQuery
  .circleci/config.yml
  e2e-tests/themes/development-runtime/content/posts/dune.mdx
  e2e-tests/themes/development-runtime/package.json
  e2e-tests/themes/gatsby-theme-about/gatsby-config.js
  e2e-tests/themes/gatsby-theme-about/gatsby-node.js
  e2e-tests/themes/gatsby-theme-about/package.json
  e2e-tests/themes/gatsby-theme-about/src/templates/post.jsx
  e2e-tests/themes/production-runtime/content/posts/dune.mdx
  e2e-tests/themes/production-runtime/cypress/integration/pages.js
  e2e-tests/themes/production-runtime/package.json
  e2e-tests/themes/production-runtime/src/gatsby-theme-about/templates/post.jsx
  packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js
Labels: topic: core

#37941 chore(docs): doc update on Gatsby functions
  docs/docs/reference/functions/getting-started.md
Labels: type: documentation

#37953 fix(gatsby-plugin-google-gtag): Add plugin options
  packages/gatsby-plugin-google-gtag/README.md
  packages/gatsby-plugin-google-gtag/package.json
  packages/gatsby-plugin-google-gtag/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-google-gtag/src/gatsby-node.js
Labels: topic: plugins-analytics

#37958 fix(gatsby-source-contentful): don't call `createNode` on `null`
  packages/gatsby-source-contentful/src/normalize.js
Labels: topic: source-contentful

#37962 fix(gatsby-plugin-netlify-cms): ignore PartialHydrationPlugin
  packages/gatsby-plugin-netlify-cms/src/gatsby-node.js
Labels: topic: plugins

#37961 feat(gatsby): apply default webpack split chunking config to html gen bundle
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: render-mode

#37975 fix(gatsby): Correct `stitching slices` build activity name
  packages/gatsby/src/commands/build-html.ts
Labels: topic: core

#37967 feat(gatsby-source-drupal): add `typePrefix` option
  examples/using-drupal/gatsby-config.js
  examples/using-drupal/src/pages/index.js
  examples/using-drupal/src/pages/recipes.js
  examples/using-drupal/src/pages/{DrupalRecipes.title}.js
  packages/babel-preset-gatsby-package/package.json
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/src/gatsby-node.ts
  packages/gatsby-source-drupal/src/normalize.ts
  packages/gatsby-source-drupal/src/utils.ts
Labels: topic: source-drupal, topic: source-plugins

#37980 fix(gatsby): avoid plus2space conversion using json encoded options
  packages/gatsby/src/utils/webpack/plugins/partial-hydration.ts
Labels: topic: core

#37984 fix(gatsby-cypress): Add TS types & improve README
  docs/docs/how-to/testing/end-to-end-testing.md
  e2e-tests/development-runtime/cypress/support/e2e.ts
  e2e-tests/production-runtime/cypress/support/e2e.ts
  examples/using-cypress/cypress.config.js
  examples/using-cypress/cypress.config.ts
  examples/using-cypress/cypress/e2e/accessibility.cy.ts
  examples/using-cypress/cypress/e2e/smoke.cy.ts
  examples/using-cypress/cypress/support/commands.js
  examples/using-cypress/cypress/support/e2e.ts
  examples/using-cypress/cypress/tsconfig.json
  examples/using-cypress/gatsby-config.ts
  examples/using-cypress/gatsby-ssr.js
  examples/using-cypress/package.json
  examples/using-cypress/src/components/header.js
  examples/using-cypress/src/components/layout.js
  examples/using-cypress/src/pages/404.js
  examples/using-cypress/src/pages/index.js
  examples/using-cypress/src/pages/page-2.js
  packages/gatsby-cypress/README.md
  packages/gatsby-cypress/index.d.ts
  packages/gatsby-cypress/package.json
  packages/gatsby-cypress/src/commands.js
Labels: type: documentation, type: feature or enhancement, topic: automation

#36349 fix(gatsby): encode window.pagePath to get valid JS code
  packages/gatsby/cache-dir/static-entry.js
Labels: topic: core, topic: frontend
