Repository gatsbyjs/gatsby, pull requests merged in 2023-08, with the labels that each got.

#38463 Fix tiny typo (1 letter)
  docs/docs/reference/built-in-components/gatsby-script.md
Labels: status: triage needed

#38453 fix(gatsby): disable prettier for results of graphql typegen
  packages/gatsby/src/utils/graphql-typegen/ts-codegen.ts
Labels: bot: merge on green

#38461 fix: GatsbyNodeAPI types
  packages/gatsby/src/redux/types.ts
Labels: bot: merge on green

#38469 chore(docs): Update managing-environment-variables.md
  docs/docs/reference/cloud/managing-environment-variables.md
Labels: status: triage needed

#38233 chore(docs): Adapters
  docs/docs/how-to/previews-deploys-hosting/adapters.md
  docs/docs/how-to/previews-deploys-hosting/caching.md
  docs/docs/how-to/previews-deploys-hosting/creating-an-adapter.md
  docs/docs/how-to/previews-deploys-hosting/headers.md
  docs/docs/how-to/previews-deploys-hosting/zero-configuration-deployments.md
  docs/docs/reference/config-files/gatsby-config.md
  docs/docs/reference/gatsby-cli.md
  packages/gatsby/src/redux/actions/public.js
Labels: type: documentation

#38477 Docs update.
  docs/docs/tutorial/getting-started/part-0/index.mdx
  docs/docs/tutorial/getting-started/part-1/index.mdx
Labels: status: triage needed

#38489 fix(gatsby): fix api function compilation on Windows
  packages/gatsby/src/internal-plugins/functions/api-function-webpack-loader.ts
Labels: bot: merge on green, topic: core

#38495 Update README.md
  starters/gatsby-starter-wordpress-blog/README.md
Labels: status: triage needed
