Repository gatsbyjs/gatsby, pull requests merged in 2023-02, with the labels that each got.

#37611 chore(docs): Fix typo in adding common features
  docs/docs/how-to/adding-common-features/adding-forms.md
  docs/docs/how-to/adding-common-features/localization-i18n.md
  docs/docs/how-to/adding-common-features/processing-payments-with-stripe.md
Labels: type: documentation

#37615 chore(docs): Update MDX layout template instructions
  docs/docs/how-to/routing/mdx.md
Labels: type: documentation

#37551 chore(docs): Update Vercel hosting information
  docs/docs/how-to/previews-deploys-hosting/deploying-to-vercel.md
Labels: type: documentation

#37619 perf(gatsby): don't create Head modules in develop if it's not used
  packages/gatsby/cache-dir/dev-loader.js
  packages/gatsby/src/bootstrap/__tests__/requires-writer.js
  packages/gatsby/src/bootstrap/requires-writer.ts
  packages/gatsby/src/query/__tests__/file-parser.js
  packages/gatsby/src/query/file-parser.js
  packages/gatsby/src/redux/__tests__/__snapshots__/index.js.snap
  packages/gatsby/src/redux/reducers/components.ts
  packages/gatsby/src/redux/types.ts
  packages/gatsby/src/utils/worker/__tests__/share-state.ts
Labels: topic: performance, topic: core

#37624 chore(gatsby): Remove `navigate` from `PageProps`
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#37630 chore(docs): Fix typo in Head API reference
  docs/docs/reference/built-in-components/gatsby-head.md
Labels: type: documentation

#37637 chore: Fix typo in error message
  packages/gatsby-cli/src/structured-errors/error-map.ts
Labels: topic: cli

#37647 fix(gatsby): fix types for printTypeDefinitions action
  packages/gatsby/index.d.ts
Labels: topic: TypeScript

#37652 chore(docs): update cloud docs
  docs/docs/how-to/cloud/adding-a-custom-domain.md
  docs/docs/reference/cloud/gatsby-cloud-environment-variables.md
Labels: type: documentation

#37658 fix(gatsby-plugin-preact): Adjust framework chunk overwrite
  packages/gatsby-plugin-preact/src/__tests__/gatsby-node.js
  packages/gatsby-plugin-preact/src/gatsby-node.js
  packages/gatsby/src/utils/webpack.config.js
Labels: topic: plugins

#37659 chore: Add "Tests" section to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: maintenance

#37660 fix(deps): Pin `@babel/plugin-transform-modules-commonjs` to 7.18.6
  e2e-tests/contentful/cypress/integration/engines.js
  e2e-tests/contentful/src/pages/ssr.js
  package.json
  packages/babel-preset-gatsby-package/lib/__tests__/fixtures/keep-dynamic-import/default/output.js
  yarn.lock
Labels: topic: source-contentful, topic: source-plugins

#37671 chore: Update READMEs to included "Deploy to Netlify"
  markdown.config.js
  starters/README-template.md
  starters/README.md
  starters/blog/README.md
  starters/default/README.md
  starters/gatsby-starter-minimal-ts/README.md
  starters/gatsby-starter-minimal/README.md
  starters/gatsby-starter-theme-workspace/README.md
  starters/gatsby-starter-wordpress-blog/README.md
  starters/hello-world/README.md
Labels: type: maintenance

#37669 fix(gatsby): Use optional chaining in `onHeadRendered`
  packages/gatsby/cache-dir/head/head-export-handler-for-browser.js
Labels: topic: frontend

#37675 chore(docs): fix dead link on gatsby-cli doc
  docs/docs/reference/gatsby-cli.md
Labels: type: documentation

#37605 feat(gatsby-source-shopify): Add `apiVersion` option
  packages/gatsby-source-shopify/README.md
  packages/gatsby-source-shopify/src/clients.ts
  packages/gatsby-source-shopify/src/plugin-options-schema.ts
  packages/gatsby-source-shopify/types/interface.d.ts
Labels: topic: source-shopify, topic: source-plugins

#37685 chore(docs): Update `path.resolve` example to include leading `./`
  docs/docs/how-to/custom-configuration/typescript.md
Labels: type: documentation

#37687 fix(gatsby): hide absolute path of __contentFilePath in component chunk name
  packages/gatsby/src/utils/__tests__/js-chunk-names.ts
  packages/gatsby/src/utils/js-chunk-names.ts
Labels: topic: core

#37684 feat(gatsby-source-drupal): filter api requests by languages
  packages/gatsby-source-drupal/README.md
  packages/gatsby-source-drupal/src/gatsby-node.ts
  packages/gatsby-source-drupal/src/plugin-options.ts
Labels: bot: merge on green, topic: source-drupal

#37698 fix(gatsby): Change backdrop position to `fixed`
  packages/gatsby/cache-dir/fast-refresh-overlay/style.js
Labels: topic: DX

#37703 chore(docs): Update "Adding search"
  docs/docs/how-to/adding-common-features/adding-search.md
Labels: type: documentation
