Repository gatsbyjs/gatsby, pull requests merged in 2023-10, with the labels that each got.

#38480 Update gatsby-contentful-plugin README
  packages/gatsby-source-contentful/README.md
Labels: status: triage needed

#38619 chore(source-npm-package-search): bespoke treatment for `plugin-gatsby-cloud` and `source-contentful`
  packages/gatsby-source-npm-package-search/src/gatsby-node.js
Labels: bot: merge on green

#38631 fix(gatsby): open lmdb instances in writeable locations in generated ssr/dsg function
  packages/gatsby/src/utils/cache-lmdb.ts
  packages/gatsby/src/utils/page-ssr-module/lambda.ts
Labels: topic: render-mode

#38639 fix(gatsby): don't force leading slash for external paths in routes manifest
  packages/gatsby/src/utils/adapter/__tests__/__snapshots__/manager.ts.snap
  packages/gatsby/src/utils/adapter/__tests__/fixtures/state.ts
  packages/gatsby/src/utils/adapter/__tests__/manager.ts
  packages/gatsby/src/utils/adapter/manager.ts
Labels: bot: merge on green, topic: adapters

#38650 docs: Changes the name of one of the service
  docs/docs/how-to/previews-deploys-hosting/deploying-to-other-services.md
Labels: status: triage needed

#38656 test: bump node version for pnp tests
  .circleci/config.yml
Labels: type: maintenance

#38644 fix(gatsby): Adapter header rules
  packages/gatsby/index.d.ts
  packages/gatsby/src/utils/adapter/__tests__/__snapshots__/manager.ts.snap
  packages/gatsby/src/utils/adapter/__tests__/manager.ts
  packages/gatsby/src/utils/adapter/constants.ts
  packages/gatsby/src/utils/adapter/manager.ts
  packages/gatsby/src/utils/adapter/types.ts
Labels: topic: adapters

#38654 chore: added logging for cache handling
  packages/gatsby-adapter-netlify/src/index.ts
Labels: topic: adapters

#38657 fix: respect 'force' and 'conditions' properties on redirects
  e2e-tests/adapters/cypress/e2e/redirects.cy.ts
  e2e-tests/adapters/gatsby-node.ts
  e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
  e2e-tests/adapters/src/pages/routes/redirect/existing-force.jsx
  e2e-tests/adapters/src/pages/routes/redirect/hit-de.jsx
  e2e-tests/adapters/src/pages/routes/redirect/hit-us.jsx
  packages/gatsby-adapter-netlify/src/__tests__/route-handler.ts
  packages/gatsby-adapter-netlify/src/route-handler.ts
  packages/gatsby-core-utils/.gitignore
  packages/gatsby/src/utils/adapter/__tests__/__snapshots__/manager.ts.snap
  packages/gatsby/src/utils/adapter/__tests__/fixtures/state.ts
  packages/gatsby/src/utils/adapter/__tests__/manager.ts
  packages/gatsby/src/utils/adapter/manager.ts
Labels: topic: adapters

#38652 fix(gatsby-adapter-netlify): adapter use headerRoutes
  e2e-tests/adapters/cypress/e2e/basics.cy.ts
  e2e-tests/adapters/cypress/e2e/headers.cy.ts
  e2e-tests/adapters/cypress/utils/dont-cache-responses-in-browser.ts
  e2e-tests/adapters/debug-adapter.ts
  e2e-tests/adapters/gatsby-config.ts
  e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
  e2e-tests/adapters/src/pages/routes/ssr/static.jsx
  packages/gatsby-adapter-netlify/src/index.ts
  packages/gatsby-adapter-netlify/src/route-handler.ts
Labels: topic: adapters
