Repository gatsbyjs/gatsby, pull requests merged in 2023-06, with the labels that each got.

#38136 feat(gatsby-transformer-screenshot): Add screenshotEndpoint option
  packages/gatsby-transformer-screenshot/README.md
  packages/gatsby-transformer-screenshot/src/gatsby-node.js
Labels: topic: plugins

#38194 chore(docs): Add Flightcontrol to "Deploying to Other Services"
  docs/docs/how-to/previews-deploys-hosting/deploying-to-other-services.md
Labels: type: documentation

#38205 chore(gatsby-plugin-feed): depend on `joi` instead of `@hapi/joi`
  packages/gatsby-plugin-feed/package.json
Labels: topic: plugins

#38235 fix(gatsby): allow touching nodes owned by another plugin
  packages/gatsby/src/redux/reducers/type-owners.ts
Labels: topic: core

#38241 chore(gatsby-source-wordpress): remove warning about multiple plugin instances
  packages/gatsby-source-wordpress/src/gatsby-node.ts
  packages/gatsby-source-wordpress/src/steps/index.ts
  packages/gatsby-source-wordpress/src/steps/temp-prevent-multiple-instances.ts
Labels: topic: source-wordpress, topic: source-plugins

#38250 chore(docs): Improve "using-local-fonts"
  docs/docs/how-to/styling/using-local-fonts.md
Labels: type: documentation

#38261 fix: Pin broken `unist-util-find` dep
  packages/gatsby-remark-custom-blocks/package.json
  packages/gatsby-remark-graphviz/package.json
  packages/gatsby-remark-responsive-iframe/package.json
  yarn.lock
Labels: topic: plugins

#38267 fix(babel-plugin-remove-graphql-queries): Correct `staticQueryDir` default and improved Storybook support
  packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.ts.snap
  packages/babel-plugin-remove-graphql-queries/src/index.ts
  packages/gatsby/src/utils/babel-loader-helpers.ts
Labels: topic: GraphQL

#38271 chore(e2e-tests): change deprecated e2e test repo name
  e2e-tests/README.md
Labels: type: documentation
