Repository gatsbyjs/gatsby, pull requests merged in 2024-06, with the labels that each got.

#39023 chore(docs): update v5 support date
  docs/docs/reference/release-notes/gatsby-version-support.md
Labels: type: documentation

#39012 Fix getNodesByIds typo
  packages/gatsby/src/schema/node-model.js
Labels: type: documentation, status: accepted

#38915 Docs update.
  docs/docs/how-to/local-development/starters.md
  docs/docs/tutorial/getting-started/part-0/index.mdx
Labels: type: documentation, status: accepted

#38744 docs: image and file cdn adapter docs
  docs/docs/how-to/previews-deploys-hosting/creating-an-adapter.md
Labels: type: documentation, status: accepted, topic: adapters
