Repository gatsbyjs/gatsby, pull requests merged in 2024-07, with the labels that each got.

#38909 Update how-gatsby-works-with-github-pages.md
  docs/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages.md
Labels: type: documentation, status: accepted

#39005 fix(gatsby-adapter-netlify): support monorepos
  .circleci/config.yml
  e2e-tests/adapters/make-monorepo.sh
  e2e-tests/adapters/netlify.toml
  e2e-tests/adapters/package.json
  e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
  packages/gatsby-adapter-netlify/src/lambda-handler.ts
  packages/gatsby/src/utils/page-ssr-module/lambda.ts
  scripts/e2e-test.sh
  yarn.lock
Labels: topic: adapters

#39051 fix(gatsby): remove jsx tag from comment
  packages/gatsby/src/utils/webpack/plugins/cache-folder-resolver.ts
Labels: status: triage needed

#38816 Fixing missing .default #38606
  packages/gatsby-adapter-netlify/README.md
Labels: type: documentation, status: accepted

#39052 Remove link to self
  docs/docs/reference/config-files/gatsby-node.md
Labels: type: documentation, status: accepted
