Repository gatsbyjs/gatsby, pull requests merged in 2024-01, with the labels that each got.

#38787 fix(gatsby-source-contentful): remove outdated `forceFullSync` option from readme
  packages/create-gatsby/src/plugin-schemas.json
  packages/gatsby-source-contentful/README.md
Labels: bot: merge on green, topic: source-contentful

#38590 fix(types): navigate doesn't return anything
  packages/gatsby-link/index.d.ts
Labels: topic: TypeScript

#38535 fix(gatsby): fix broken DevOverlay when there is no stack trace.
  packages/gatsby/cache-dir/__tests__/runtime-errors.js
  packages/gatsby/cache-dir/fast-refresh-overlay/components/hooks.js
  packages/gatsby/cache-dir/fast-refresh-overlay/components/runtime-errors.js
  packages/gatsby/package.json
  yarn.lock
Labels: topic: DX

#38516 fix(gatsby): support builtin modules prefixed with `node:` on `build-html`
  packages/gatsby/src/utils/webpack.config.js
Labels: status: triage needed

#38773 fix(gatsby): try to automatically recover when parcel segfaults
  .jestSetup.js
  packages/gatsby/src/utils/parcel/__tests__/compile-gatsby-files.ts
  packages/gatsby/src/utils/parcel/__tests__/fixtures/error-in-code-ts/gatsby-node.ts
  packages/gatsby/src/utils/parcel/compile-gatsby-files.ts
Labels: topic: TypeScript

#38757 fix(gatsby): fix webpack compilation when pnpm is used
  .circleci/config.yml
  packages/gatsby-dev-cli/src/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/index.js
  packages/gatsby-dev-cli/src/local-npm-registry/install-packages.js
  packages/gatsby-dev-cli/src/local-npm-registry/verdaccio-config.js
  packages/gatsby-dev-cli/src/watch.js
  packages/gatsby/src/internal-plugins/functions/api-function-webpack-loader.ts
  packages/gatsby/src/internal-plugins/functions/gatsby-node.ts
  packages/gatsby/src/utils/webpack/plugins/cache-folder-resolver.ts
Labels: topic: webpack/babel

#38797 chore: swap babel-plugin-lodash with updated version that doesn't use deprecated APIs
  examples/using-remark/package.json
  packages/babel-preset-gatsby-package/lib/__tests__/index.js
  packages/babel-preset-gatsby-package/lib/index.js
  packages/babel-preset-gatsby-package/package.json
  packages/gatsby-cli/package.json
  packages/gatsby-cli/rollup.config.js
  packages/gatsby-plugin-lodash/package.json
  packages/gatsby-plugin-lodash/src/gatsby-node.js
  packages/gatsby/package.json
  packages/gatsby/src/internal-plugins/bundle-optimisations/gatsby-node.js
  yarn.lock
Labels: topic: webpack/babel

#38820 perf: use must-revalidate cache-control header as common and only create header routes for routes with different cache-control
  packages/gatsby/src/utils/adapter/__tests__/__snapshots__/manager.ts.snap
  packages/gatsby/src/utils/adapter/__tests__/manager.ts
  packages/gatsby/src/utils/adapter/manager.ts
Labels: topic: performance, topic: adapters

#38822 fix: add missing fs method rewrites to handle fetchRemoteFile in dsg/ssr engine
  e2e-tests/adapters/cypress/e2e/remote-file.cy.ts
  e2e-tests/adapters/src/pages/routes/ssr/remote-file.jsx
  packages/gatsby-adapter-netlify/src/file-cdn-url-generator.ts
  packages/gatsby/src/schema/graphql-engine/bundle-webpack.ts
  packages/gatsby/src/schema/graphql-engine/entry.ts
  packages/gatsby/src/utils/page-ssr-module/lambda.ts
Labels: topic: media, topic: render-mode
