Repository gatsbyjs/gatsby, pull requests merged in 2025-01, with the labels that each got.

#39082 feat!(gatsby-source-shopify): upgrade from Shopify API version 2022-04 to 2024-04
  packages/gatsby-source-shopify/__tests__/__snapshots__/create-operations.ts.snap
  packages/gatsby-source-shopify/__tests__/__snapshots__/create-schema-customization.ts.snap
  packages/gatsby-source-shopify/__tests__/__snapshots__/source-from-operation.ts.snap
  packages/gatsby-source-shopify/__tests__/fixtures/bulk-results/collections.jsonl
  packages/gatsby-source-shopify/__tests__/fixtures/bulk-results/products.jsonl
  packages/gatsby-source-shopify/__tests__/fixtures/bulk-results/variants.jsonl
  packages/gatsby-source-shopify/__tests__/fixtures/ids.json
  packages/gatsby-source-shopify/__tests__/fixtures/index.ts
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyCollection.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyExternalVideo.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyInventoryItem.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyInventoryLevel.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyLineItem.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyLocation.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyMediaImage.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyMetafield.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyModel3d.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyOrder.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyProduct.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyProductVariant.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyProductVariantPricePair.json
  packages/gatsby-source-shopify/__tests__/fixtures/shopify-nodes/ShopifyVideo.json
  packages/gatsby-source-shopify/src/create-schema-customization.ts
  packages/gatsby-source-shopify/src/plugin-options-schema.ts
  packages/gatsby-source-shopify/src/query-builders/collections-query.ts
  packages/gatsby-source-shopify/src/query-builders/product-variants-query.ts
  packages/gatsby-source-shopify/src/query-builders/products-query.ts
  packages/gatsby-source-shopify/src/type-builders/collection-type.ts
  packages/gatsby-source-shopify/src/type-builders/location-type.ts
  packages/gatsby-source-shopify/src/type-builders/product-type.ts
  packages/gatsby-source-shopify/src/type-builders/product-variant-type.ts
Labels: topic: source-shopify

#39211 chore: bump caniuse-lite
  yarn.lock
Labels: type: maintenance

#39222 test: use branch/alias deploys for e2e test suite
  e2e-tests/adapters/scripts/deploy-and-run/netlify.mjs
Labels: topic: automation
